### PR TITLE
Set culture to culture invariant in LightGBM

### LINKED ISSUE #440: Wrong Culture when passing arguments to LightGBM
### System information

- Win 10
- dotnet core

### Issue

When calling the Train Method the arguments are parsed with the local culture instead of en or us, which leads to an Error:

41993623-57553e14-7a4c-11e8-9d75-12d423f54f8e

### PR DESCRIPTION
**Pull request by codemzs**
fixes #440

### CODE REVIEW

File: src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs [hunk 1]
```diff
@@ -60,6 +61,8 @@ private sealed class CategoricalMetaData
 
         protected LightGbmTrainerBase(IHostEnvironment env, LightGbmArguments args, PredictionKind predictionKind, string name)
         {
+            Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: >Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US"); [](start = 12, length = 63)

This is nice, and solves all the current problems, but are you sure this is a separate thread we spawn and not are user thread?
I can image users surprise if they code just stop working because somewhere in separate library you setup current thread culture to en-us :)

File: src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs [hunk 2]
```diff
@@ -11,6 +11,7 @@
 using Microsoft.ML.Runtime.Internal.Utilities;
 using Microsoft.ML.Runtime.Training;
 using Microsoft.ML.Runtime.FastTree.Internal;
+using System.Globalization;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: order

File: src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs (hunk 1 above)
Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: This is current thread at the start of the argument parsing on line 71.

---
In reply to: [199274365](https://github.com/dotnet/machinelearning/pull/454#discussion_r199274365) [](ancestors = 199274365)

Comment (TomFinley) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: Reactivating. Just to be clear since it's not obvious, changing a user's culture is not an appropriate solution.

---
In reply to: [199275306](https://github.com/dotnet/machinelearning/pull/454#discussion_r199275306) [](ancestors = 199275306,199274365)

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: ok, let me give you example:
TrainAndPredictIrisModelWithStringLabelTest

Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("fr-FR");
double v = 1.5f;
string t = v.ToString();

put this in begining of test

replace learner with LightGBM and check what you get same 1.5 as parse result

v = double.Parse(t);
pipeline.Add(new LightGbmClassifier());

run training:
            PredictionModel<IrisDataWithStringLabel, IrisPrediction> model = pipeline.Train<IrisDataWithStringLabel, IrisPrediction>();
            v = double.Parse(t);

check value in v


---
In reply to: [199275306](https://github.com/dotnet/machinelearning/pull/454#discussion_r199275306) [](ancestors = 199275306,199274365)

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: proper solution is 
a) change all places where we work with Option argument from ToString(CultureInfo("en-US")) preferably move culture to const variable
b) report this issue to LightGBM folks: [https://github.com/Microsoft/LightGBM/blob/ba3e1ff24fd43ed33d7703881d8efad83a5ed452/include/LightGBM/utils/common.h#L174](https://github.com/Microsoft/LightGBM/blob/ba3e1ff24fd43ed33d7703881d8efad83a5ed452/include/LightGBM/utils/common.h#L174) people who do they own parsing mechanism, have special place in hell.
c) put comments which describe what this is temporary solution and ToString can be reverted to normal state as soon as LightGBM folks fix their parser.

---
In reply to: [199277210](https://github.com/dotnet/machinelearning/pull/454#discussion_r199277210) [](ancestors = 199277210,199275306,199274365)

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: [https://github.com/Microsoft/LightGBM/issues/1481](https://github.com/Microsoft/LightGBM/issues/1481)
here is issue to track

---
In reply to: [199279475](https://github.com/dotnet/machinelearning/pull/454#discussion_r199279475) [](ancestors = 199279475,199277210,199275306,199274365)

Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: Thanks for opening the issue on LightGBM repo.

---
In reply to: [199284806](https://github.com/dotnet/machinelearning/pull/454#discussion_r199284806) [](ancestors = 199284806,199279475,199277210,199275306,199274365)

File: src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs [hunk 3]
```diff
@@ -3,14 +3,12 @@
 // See the LICENSE file in the project root for more information.
 
 using System;
-using System.Linq;
-using System.Threading;
-using System.Threading.Tasks;
 using System.Collections.Generic;
+using System.Globalization;
+using System.Linq;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: do you really need linq?

Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: yeah there are references to it in this file. Last()

---
In reply to: [199288120](https://github.com/dotnet/machinelearning/pull/454#discussion_r199288120) [](ancestors = 199288120)

File: src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs [hunk 4]
```diff
@@ -108,10 +108,10 @@ protected override void CheckDataValid(IChannel ch, RoleMappedData data)
 
         protected override void CheckAndUpdateParametersBeforeTraining(IChannel ch, RoleMappedData data, float[] labels, int[] groups)
         {
-            Options["objective"] = "regression";
+            Options["objective"] = "regression".ToString(CultureInfo.InvariantCulture);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs]: >"regression".ToString(CultureInfo.InvariantCulture); [](start = 35, length = 52)

I have so many questions...

File: src/Microsoft.ML.LightGBM/LightGbmArguments.cs [hunk 5]
```diff
@@ -402,12 +403,13 @@ public enum EvalMetricType
             if (!string.IsNullOrEmpty(metric))
                 res["metric"] = metric;
             res["sigmoid"] = "0.5";
-            res["label_gain"] = CustomGains;
-            res[GetArgName(nameof(UseMissing))] = UseMissing.ToString();
-            res[GetArgName(nameof(MinDataPerGroup))] = MinDataPerGroup.ToString();
-            res[GetArgName(nameof(MaxCatThreshold))] = MaxCatThreshold.ToString();
-            res[GetArgName(nameof(CatSmooth))] = CatSmooth.ToString();
-            res[GetArgName(nameof(CatL2))] = CatL2.ToString();
+            res["label_gain"] = CustomGains.ToString(CultureInfo.InvariantCulture);
```
Comment (TomFinley) [inline src/Microsoft.ML.LightGBM/LightGbmArguments.cs]: >CustomGains.ToString [](start = 32, length = 20)

Anything that is a string, there is of course no need to call this.

File: src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs [hunk 6]
```diff
@@ -132,7 +133,7 @@ protected override void GetDefaultParameters(IChannel ch, int numRow, bool hasCa
             base.GetDefaultParameters(ch, numRow, hasCategorical, totalCats, true);
             int numLeaves = int.Parse(Options["num_leaves"]);
```
Comment (TomFinley) [inline src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: >int.Parse(Options["num_leaves"]); [](start = 28, length = 33)

If you're doing it one way, you must also do it the other way.

File: src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs (hunk 3 above)
Comment (TomFinley) [reply src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: Reactivating. This is actually pretty bad. Change that code to get the second to last index. I know it's not your fault, but, let's not let bad code stand, if we know where it is.

---
In reply to: [199289028](https://github.com/dotnet/machinelearning/pull/454#discussion_r199289028) [](ancestors = 199289028,199288120)

**Comment by codemzs** [comment]
Thanks, Tom! This is a great feedback and indeed results in a more maintainable code.

---
In reply to: [401497686](https://github.com/dotnet/machinelearning/pull/454#issuecomment-401497686) [](ancestors = 401497686)

File: src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs (hunk 4 above)
Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmRegressionTrainer.cs]: 99 questions but ... aint one? 

---
In reply to: [199290138](https://github.com/dotnet/machinelearning/pull/454#discussion_r199290138) [](ancestors = 199290138)

File: src/Microsoft.ML.Data/Transforms/ConcatTransform.cs [hunk 7]
```diff
@@ -90,19 +90,6 @@ public bool TryUnparse(StringBuilder sb)
 
         public sealed class Arguments : TransformInputBase
         {
-            public Arguments()
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Transforms/ConcatTransform.cs]: >public Arguments() [](start = 12, length = 18)

I think something terribly wrong happen with your merge

Comment (codemzs) [reply src/Microsoft.ML.Data/Transforms/ConcatTransform.cs]: Yes, I am aware and fixing it via interactive rebase.

---
In reply to: [199600627](https://github.com/dotnet/machinelearning/pull/454#discussion_r199600627) [](ancestors = 199600627)

File: src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs [hunk 8]
```diff
@@ -130,9 +131,9 @@ protected override void ConvertNaNLabels(IChannel ch, RoleMappedData data, float
         protected override void GetDefaultParameters(IChannel ch, int numRow, bool hasCategorical, int totalCats, bool hiddenMsg=false)
         {
             base.GetDefaultParameters(ch, numRow, hasCategorical, totalCats, true);
-            int numLeaves = int.Parse(Options["num_leaves"]);
+            int numLeaves = int.Parse(string.Format(CultureInfo.InvariantCulture, "{0}", Options["num_leaves"]));
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: >int.Parse(string.Format(CultureInfo.InvariantCulture, "{0}", Options["num_leaves"])); [](start = 28, length = 85)

why can you just call int.Parse(Options["num_leaves"],CultureInfo.InvariantCulture); ?

Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: That won't work. You will need to convert object to string first and even then what advantage does this give over what I have now? I'm also concerned that we will convert to string without invariant and then try to parse with invariant flag.

---
In reply to: [199603671](https://github.com/dotnet/machinelearning/pull/454#discussion_r199603671) [](ancestors = 199603671)

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: It would work if your Options["num_leaves"] was Invarianted string. But in your case Option["num_leaves"] contains already int value which you hide behind object. So all you need to is just a cast.
int numLeaves = (int)Options["num_leaves"];

---
In reply to: [199605092](https://github.com/dotnet/machinelearning/pull/454#discussion_r199605092) [](ancestors = 199605092,199603671)

Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: That will work but here I don't want to make an assumption that num_leaves is int, what if tomorrow someone inserts num_leaves as string or some other type? I'd rather have a generic way to translate to invariant string and then parse. What do you think?

---
In reply to: [199607828](https://github.com/dotnet/machinelearning/pull/454#discussion_r199607828) [](ancestors = 199607828,199605092,199603671)

File: src/Microsoft.ML.LightGBM/WrappedLightGbmTraining.cs [hunk 9]
```diff
@@ -33,9 +33,9 @@ internal static class WrappedLightGbmTraining
             double bestScore = double.MaxValue;
             double factorToSmallerBetter = 1.0;
 
-            if (earlyStoppingRound > 0 && (parameters["metric"] == "auc"
-                || parameters["metric"] == "ndcg"
-                || parameters["metric"] == "map"))
+            if (earlyStoppingRound > 0 && (parameters["metric"].ToString() == "auc"
```
Comment (TomFinley) [inline src/Microsoft.ML.LightGBM/WrappedLightGbmTraining.cs]: >parameters["metric"].ToString() [](start = 43, length = 31)

What are these originally?

If they're strings, just use a direct cast. That communicates that you expect them to actually *be* strings. `ToString()` suggests there's some conversion going on.

Comment (codemzs) [reply src/Microsoft.ML.LightGBM/WrappedLightGbmTraining.cs]: Here it makes to cast to string because a string is represented as a string unlike int, double, etc that can be represented in their original type or as strings.

---
In reply to: [199613266](https://github.com/dotnet/machinelearning/pull/454#discussion_r199613266) [](ancestors = 199613266)

File: src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs [hunk 10]
```diff
@@ -219,7 +221,7 @@ private static List<int> GetCategoricalBoundires(int[] categoricalFeatures, int
         private static List<string> ConstructCategoricalFeatureMetaData(int[] categoricalFeatures, int rawNumCol, ref CategoricalMetaData catMetaData)
         {
             List<int> catBoundaries = GetCategoricalBoundires(categoricalFeatures, rawNumCol);
-            catMetaData.NumCol = catBoundaries.Count() - 1;
```
Comment (TomFinley) [inline src/Microsoft.ML.LightGBM/LightGbmTrainerBase.cs]: >Count() [](start = 47, length = 7)

Ah very good. Yes that is terrible. There really be a warning or something on `Count()`... :P

File: src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs (hunk 8 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: I have a proposal which will benefit all of us and remove any concerns regarding culture.  Don't do parsing at all. Just set numLeaves as out parameter in the function and set it properly in base call.


---
In reply to: [199611982](https://github.com/dotnet/machinelearning/pull/454#discussion_r199611982) [](ancestors = 199611982,199607828,199605092,199603671)

Comment (codemzs) [reply src/Microsoft.ML.LightGBM/LightGbmMulticlassTrainer.cs]: In this case casting to int is fine. I spoke with Tom and he mentioned we can make this hard assumptions if the datastructure/code is internal.

---
In reply to: [199630347](https://github.com/dotnet/machinelearning/pull/454#discussion_r199630347) [](ancestors = 199630347,199611982,199607828,199605092,199603671)
