### PR TITLE
Remove Done method from IPipe

### LINKED ISSUE #803: Make IChannel `.Done` Done
One of the most fun design decisions w.r.t. `IChannel` is that it should have a `.Done()` method, analogous perhaps to things we see in databases like commits and whatnot. The purpose is to indicate that the channel actually reached the end of the code block successfully, in the way that the code writer thought it would, and thus distinguish between the case where the channel was disposed because we reached the end vs. the channel was disposed for some other reason. (Because, I guess, the alternative, an exception being thrown and interrupting the flow of code, wasn't conspicuous enough of a signal.)

That's fine if a little redundant. However, this *does* incur a cost to code. Consider for example this code here:

https://github.com/dotnet/machinelearning/blob/a3b67d393714ebeb873a41af82cd22ea7311e44c/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L229-L235

Now, it *could* have been written like this:

```csharp
using (var ch = host.Start(channelName))
    return func(ch);
```

But we can't, because, of course, we need to make sure we call `ch.Done()`, which means we have to store the return value somewhere else, etc. etc.

By itself that isn't that bad, except we use channels literally everywhere. So we see this pattern repeated over, and over, and over again. I've done this so often I even have a standard variable name I personally use to work around this thing, `retval`.

Yet, despite being used everywhere in the codebase, over the years I can count the number of times that check has been useful on exactly zero of my hands. In fact it is so useless that we never actually bothered to consider it an error condition, since there are far more examples of people forgetting to do that than examples where it actually signaled a problem -- refer to the example above, the "mistake" is far more obvious than the correct actually implemented pattern -- and again, the alternative, an exception being thrown, was far more obvious anyway. So it just writes an easily ignored warning to the *trace* stream if it's detected (which is a logging layer people by default cannot visibly access anyway).

Maybe we ought to get rid of it, just rely on the fact that the channel is being disposed (which contrary to this `Done` thing does convey very useful information), and simplify a bunch of code.

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Two donut people walk into a bar.
"Are we done?" ask first one.
"No we are not dumb!" answers second.

Fixes #803.

@yaeldekel If you think this would slowdown your current project, feel free to block it until you done with it.

### CODE REVIEW

File: src/Microsoft.ML.Core/Data/IHostEnvironment.cs [hunk 1]
```diff
@@ -104,11 +104,6 @@ public interface IPipe<TMessage> : IExceptionContext, IDisposable
         /// The caller relinquishes ownership of the <paramref name="msg"/> object.
         /// </summary>
         void Send(TMessage msg);
-
-        /// <summary>
-        /// Called to indicate a normal shut-down of the pipe before disposing.
-        /// </summary>
-        void Done();
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Core/Data/IHostEnvironment.cs]: >Done [](start = 13, length = 4)

Main change A

File: src/Microsoft.ML.Core/Environment/ConsoleEnvironment.cs [hunk 2]
```diff
@@ -139,7 +139,7 @@ public void ChannelStarted(Channel channel)
                 }
             }
 
-            public void ChannelFinished(Channel channel)
+            public void ChannelDisposed(Channel channel)
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Core/Environment/ConsoleEnvironment.cs]: Main change B

File: src/Microsoft.ML.Core/Environment/HostEnvironmentBase.cs [hunk 3]
```diff
@@ -174,11 +174,6 @@ protected abstract class PipeBase<TMessage> : ChannelProviderBase, IPipe<TMessag
         {
             public override int Depth { get; }
 
-            /// <summary>
-            /// Whether this pipe is still active.
-            /// </summary>
-            public bool IsActive { get; private set; }
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Core/Environment/HostEnvironmentBase.cs]: Main change C.

Everything is just removing ch.Done from code.

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs [hunk 4]
```diff
@@ -61,7 +61,6 @@ public sealed partial class TextLoader
                 var readerEst = StaticPipeUtils.ReaderEstimatorAnalyzerHelper(env, ch, ctx, rec, func);
                 Contracts.AssertValue(readerEst);
                 var reader = readerEst.Fit(files);
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs]: >var reader = readerEst.Fit(files); [](start = 16, length = 34)

FYI if you happen to post another iteration, you may as well clean this up too.

File: src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs [hunk 5]
```diff
@@ -589,8 +589,6 @@ private void SetColumnArgument(IChannel ch, object inputInstance, string argName
                 var entryPointNode = new EntryPointNode(env, ch, context, context.GenerateId(entryPointName), entryPointName,
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs]: >var entryPointNode = new [](start = 16, length = 24)

Similar, instead of `var entryPointNode = new ...` could be `return new ...`.

File: src/Microsoft.ML.Data/EntryPoints/InputBase.cs [hunk 6]
```diff
@@ -188,8 +188,6 @@ public static string FindColumn(IExceptionContext ectx, ISchema schema, Optional
 
                 var predictor = TrainUtils.Train(host, ch, cachedRoleMappedData, trainer, calibrator, maxCalibrationExamples);
                 var output = new TOut() { PredictorModel = new PredictorModel(host, roleMappedData, input.TrainingData, predictor) };
-
-                ch.Done();
                 return output;
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/EntryPoints/InputBase.cs]: >output [](start = 23, length = 6)

Again

File: src/Microsoft.ML.Data/Scorers/SchemaBindablePredictorWrapper.cs [hunk 7]
```diff
@@ -125,7 +125,6 @@ public ISchemaBoundMapper Bind(IHostEnvironment env, RoleMappedSchema schema)
                     }
                 }
                 var mapper = BindCore(ch, schema);
-                ch.Done();
                 return mapper;
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/Scorers/SchemaBindablePredictorWrapper.cs]: >mapper [](start = 23, length = 6)

Same

File: src/Microsoft.ML.Data/StaticPipe/Estimator.cs [hunk 8]
```diff
@@ -74,7 +74,6 @@ string NameMap(PipelineColumn col)
                 var est = AsDynamic.Append(estTail);
                 var newOut = StaticSchemaShape.Make<TNewOutShape>(method.ReturnParameter);
                 var toReturn = new Estimator<TInShape, TNewOutShape, ITransformer>(Env, est, _inShape, newOut);
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/StaticPipe/Estimator.cs]: >toReturn [](start = 20, length = 8)

Same

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs (hunk 4 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderStatic.cs]: Not worth posting a new iteration though... just only if you have to for some other reason anyway.
