### PR TITLE
One type label policy in trainers

### LINKED ISSUE #2628: Mismatch in Label expectations for Multiclass Learners
When training a multiclass classifier, the label must be converted to `KeyType`. Some learners, such as `SDCA`, do the conversion from `R4` automatically, while some, like `LogisticRegression` do not. This behavior   is confusing from an end-user perspective, as one cannot simply interchange learners without modifying the input pipeline.

I suggest adding auto-label-conversion for all multiclass learners in ML.NET.

### LINKED ISSUE #2750: R4 label works with some but not all binary classification trainers
This code:

```C#
using System;
using Microsoft.ML.Data;

namespace Microsoft.ML.Samples
{
    internal static class Program
    {
        static void Main(string[] args)
        {
            var context = new MLContext();
            var options = new TextLoader.Options()
            {
                Columns = new TextLoader.Column[]
                {
                    new TextLoader.Column("Label", DataKind.Single, 0),
                    new TextLoader.Column("Sentiment", DataKind.String, 1)
                },
                HasHeader = true
            };
            var loader = context.Data.CreateTextLoader(options);
            var data = loader.Read(@"C:\AutoMLDotNet\src\Samples\Data\wikipedia-detox-250-line-data.tsv");
            var estimator = context.Transforms.Text.FeaturizeText("Features", "Sentiment")
                .Append(context.BinaryClassification.Trainers.AveragedPerceptron());
            var transformer = estimator.Fit(data);
            var scoredData = transformer.Transform(data);
            var metrics = context.BinaryClassification.EvaluateNonCalibrated(scoredData);
            Console.WriteLine(metrics.Accuracy);
            Console.WriteLine("Press any key...");
            Console.ReadLine();
        }
    }
}
```
works great!

If you replace AveragedPerceptron with LogisticRegression, it throws the exception:
```
 'Schema mismatch for label column: expected Bool, got R4'
```

This may indicate a bug in label schema validation with some binary learners

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
This PR fixes #2628 and fixes #2750. fixes https://github.com/dotnet/machinelearning/issues/2810

### CODE REVIEW

File: src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs [hunk 1]
```diff
@@ -151,7 +151,7 @@ public static IDataView LoadFeaturizedAdultDataset(MLContext mlContext)
                         new TextLoader.Column("capital-loss", DataKind.Single, 11),
                         new TextLoader.Column("hours-per-week", DataKind.Single, 12),
                         new TextLoader.Column("native-country", DataKind.Single, 13),
-                        new TextLoader.Column("IsOver50K", DataKind.Boolean, 14),
+                        new TextLoader.Column("IsOver50K", DataKind.Single, 14),
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.SamplesUtils/SamplesDatasetUtils.cs]: revert

**Comment by rogancarr** [comment]
> namespace Microsoft.ML.Trainers.FastTree

FastTree and GAM binary classification convert from R4 to boolean with a custom function. Do we want to drop that functionality?

---
Refers to: src/Microsoft.ML.FastTree/FastTreeRanking.cs:40 in 5707e17. [](commit_id = 5707e17a1bbb09c98ca90d53d42f32c112c258cc, deletion_comment = False)

File: test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs [hunk 2]
```diff
@@ -20,21 +20,23 @@ public void SdcaWorkout()
             var data = TextLoaderStatic.CreateLoader(Env, ctx => (Label: ctx.LoadFloat(0), Features: ctx.LoadFloat(1, 10)))
                 .Load(dataPath).Cache();
 
+            var binaryData = ML.Transforms.Conversion.ConvertType("Label", outputKind: DataKind.Boolean).Fit(data.AsDynamic).Transform(data.AsDynamic);
```
Comment (rogancarr) [inline test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs]: > var binaryData [](start = 11, length = 15)

Maybe break lines? This is a bit of a mouthful.

File: test/Microsoft.ML.Tests/Scenarios/OvaTest.cs [hunk 3]
```diff
@@ -125,9 +128,9 @@ public void OvaLinearSvm()
                             new TextLoader.Column("Features", DataKind.Single, new [] { new TextLoader.Range(1, 4) }),
                         }
             });
-
             // Data
-            var data = mlContext.Data.Cache(reader.Load(GetDataPath(dataPath)));
+            var textData = reader.Load(GetDataPath(dataPath));
+            var data = mlContext.Data.Cache(mlContext.Transforms.Conversion.MapValueToKey("Label").Fit(textData).Transform(textData));
```
Comment (rogancarr) [inline test/Microsoft.ML.Tests/Scenarios/OvaTest.cs]: >var data  [](start = 12, length = 9)

Maybe for lines like this in this file, break the steps out a bit for easier reading?

File: test/Microsoft.ML.Tests/Scenarios/OvaTest.cs [hunk 4]
```diff
@@ -61,19 +61,21 @@ public void OvaAveragedPerceptron()
...
+
             var pipeline = mlContext.MulticlassClassification.Trainers.OneVersusAll(ap, useProbabilities: false);
 
             var model = pipeline.Fit(data);
             var predictions = model.Transform(data);
 
             // Metrics
             var metrics = mlContext.MulticlassClassification.Evaluate(predictions);
-            Assert.True(metrics.MicroAccuracy > 0.71);
+            Assert.True(metrics.MicroAccuracy > 0.66);
```
Comment (rogancarr) [inline test/Microsoft.ML.Tests/Scenarios/OvaTest.cs]: >Assert.True(metrics.MicroAccuracy > 0.66) [](start = 12, length = 41)

Did changing the concurrency give lower `MicroAccuracy`?

File: src/Microsoft.ML.Core/Data/AnnotationUtils.cs [hunk 5]
```diff
@@ -307,11 +307,11 @@ public static void GetSlotNames(RoleMappedSchema schema, RoleMappedSchema.Column
                 schema.Schema[list[0].Index].Annotations.GetValue(Kinds.SlotNames, ref slotNames);
         }
 
-        public static bool HasKeyValues(this SchemaShape.Column col)
+        public static bool ShouldAddSlotNames(this SchemaShape.Column col)
```
Comment (rogancarr) [inline src/Microsoft.ML.Core/Data/AnnotationUtils.cs]: >ShouldAddSlotNames [](start = 27, length = 18)

`NeedsSlotNames`? Having a modal verb here feels odd to me.

File: test/Microsoft.ML.Tests/Scenarios/OvaTest.cs (hunk 4 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/Scenarios/OvaTest.cs]: No.
I still need to debug it properly.
We have ova with 3 labels which gives me 0 vs 1,2; 1 vs 0,2 and 2 vs 0,1.
For 1 vs 0,2 AP with 1 iteration (which is default) treats everything as 0,2. I've even modify file and relabel it accordingly to test that.  For other cases AP perfectly overfits and give you correct predictions on training data. Which leads to 2/3 accuracy. 
For some reason what wasn't the case before with float labels, as I said, I need to look on that.
Concurency =1 set for ease of debugging, I can remove it.

File: src/Microsoft.ML.Core/Data/AnnotationUtils.cs [hunk 6]
```diff
@@ -307,11 +307,11 @@ public static void GetSlotNames(RoleMappedSchema schema, RoleMappedSchema.Column
...
         {
             return col.Annotations.TryFindColumn(Kinds.KeyValues, out var metaCol)
                 && metaCol.Kind == SchemaShape.Column.VectorKind.Vector
-                && metaCol.ItemType is TextDataViewType;
+                && metaCol.ItemType is TextDataViewType; ;
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/AnnotationUtils.cs]: double `;`

File: test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs [hunk 7]
```diff
@@ -422,7 +422,14 @@ private IDataView GetDenseDataset(TaskType task = TaskType.Regression)
 
             var pipeline = ML.Transforms.Concatenate("Features", "X1", "X2Important", "X3", "X4Rand")
                 .Append(ML.Transforms.Normalize("Features"));
-
+            if (task == TaskType.BinaryClassification)
+                return pipeline.Append(ML.Transforms.Conversion.ConvertType("Label", outputKind: DataKind.Boolean))
+                    .Fit(srcDV).Transform(srcDV);
+            else
```
Comment (eerhardt) [inline test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs]: `else if` should be on one line.

**Comment by Ivanidzo4ka** [comment]
> namespace Microsoft.ML.Trainers.FastTree

Good question.
Main reason for this PR is to have consistency and support only one type of label.
Boolean feels natural for binary classification, but I can see benefits of floats for binary classification.
How useful that conversion is? 
For Gam we just do this:
 `boolArray[doc] = targets[doc] > 0;` 
Which is same thing as ConvertFromR4ToBool.
Not sure I know where to look for FastTree.

---
In reply to: [469402531](https://github.com/dotnet/machinelearning/pull/2804#issuecomment-469402531) [](ancestors = 469402531)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeRanking.cs:40 in 5707e17. [](commit_id = 5707e17a1bbb09c98ca90d53d42f32c112c258cc, deletion_comment = False)

**Comment by rogancarr** [comment]
> namespace Microsoft.ML.Trainers.FastTree

GAM and FastTreeClassification call `TrainerUtils.MakeBoolScalarLabel` to convert the labels if they are not bools already. If we are only going to support bool for binary classification labels, then we should not be calling this function and instead throwing.

---
In reply to: [469443560](https://github.com/dotnet/machinelearning/pull/2804#issuecomment-469443560) [](ancestors = 469443560,469402531)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeRanking.cs:40 in 5707e17. [](commit_id = 5707e17a1bbb09c98ca90d53d42f32c112c258cc, deletion_comment = False)

**Comment by rogancarr** [comment]
> namespace Microsoft.ML.Trainers.FastTree

In FastTree, we do this crazy thing:

```cs
private IEnumerable<bool> GetClassificationLabelsFromRatings(Dataset set)
        {
            // REVIEW: Historically FastTree has this test as >= 1. TLC however
            // generally uses > 0. Consider changing FastTree to be consistent.
            return set.Ratings.Select(x => x >= 1);
        }
```

---
In reply to: [469443560](https://github.com/dotnet/machinelearning/pull/2804#issuecomment-469443560) [](ancestors = 469443560,469402531)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeRanking.cs:40 in 5707e17. [](commit_id = 5707e17a1bbb09c98ca90d53d42f32c112c258cc, deletion_comment = False)

**Comment by rogancarr** [comment]
> namespace Microsoft.ML.Trainers.FastTree

Note that one thing we *don't* do is allow probability-as-labels for calibrated trainers. That is, there are times when I may want to specify that I believe that the correct probability out is 0.7 and not 1.0 for an example.

---
In reply to: [469456048](https://github.com/dotnet/machinelearning/pull/2804#issuecomment-469456048) [](ancestors = 469456048,469443560,469402531)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeRanking.cs:40 in 5707e17. [](commit_id = 5707e17a1bbb09c98ca90d53d42f32c112c258cc, deletion_comment = False)

**Comment by sfilipi** [comment]
> namespace Microsoft.ML.Trainers.FastTree

would changing this cause the cmd to stop working the way it is?

---
In reply to: [469456970](https://github.com/dotnet/machinelearning/pull/2804#issuecomment-469456970) [](ancestors = 469456970,469456048,469443560,469402531)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeRanking.cs:40 in 5707e17. [](commit_id = 5707e17a1bbb09c98ca90d53d42f32c112c258cc, deletion_comment = False)

File: src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs [hunk 8]
```diff
@@ -99,19 +98,16 @@ private protected IDataView MapLabelsCore<T>(DataViewType type, InPredicate<T> e
             Host.Assert(data.Schema.Label.HasValue);
 
             var lab = data.Schema.Label.Value;
-
-            InPredicate<T> isMissing;
-            if (!Args.ImputeMissingLabelsAsNegative && Conversions.Instance.TryGetIsNAPredicate(type, out isMissing))
+            IDataView dataView = data.Data;
+            if (!Args.ImputeMissingLabelsAsNegative)
             {
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs]: >{ [](start = 12, length = 1)

remove

File: test/BaselineOutput/Common/OVA/OVA-CV-iris-out.txt [hunk 9]
```diff
@@ -1,4 +1,4 @@
-maml.exe CV tr=OVA{p=AvgPer{ lr=0.8 }} threads=- norm=No dout=%Output% data=%Data% seed=1
+maml.exe CV tr=OVA{p=AvgPer{ lr=0.8 }} threads=- norm=No dout=%Output% data=%Data% seed=1 xf=Term{col=Label}
```
Comment (sfilipi) [inline test/BaselineOutput/Common/OVA/OVA-CV-iris-out.txt]: >xf=Term{col=Label} [](start = 90, length = 18)

Would Covert do it, rather than Term?

File: test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt [hunk 10]
```diff
@@ -53,50 +53,56 @@ Virtual memory usage(MB): %Number%
...
+[3] (%Time%)	12 iterations	Loss: 0.192447692155838	Improvement: 0.001383
+[3] (%Time%)	13 iterations	Loss: 0.189304739236832	Improvement: 0.002703
+[3] (%Time%)	14 iterations	Loss: 0.187662661075592	Improvement: 0.001907
+[3] (%Time%)	15 iterations	Loss: 0.185374572873116	Improvement: 0.002193
+[3] (%Time%)	16 iterations	Loss: 0.18364554643631	Improvement: 0.001845
+[3] (%Time%)	17 iterations	Loss: 0.180794909596443	Improvement: 0.002599
+[3] (%Time%)	18 iterations	Loss: 0.178908497095108	Improvement: 0.002065
+[3] (%Time%)	19 iterations	Loss: 0.175620675086975	Improvement: 0.002982
+[3] (%Time%)	20 iterations	Loss: 0.174758642911911	Improvement: 0.001392
+[3] (%Time%)	21 iterations	Loss: 0.173962101340294	Improvement: 0.0009454
```
Comment (sfilipi) [inline test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt]: >0.173962101340294 [](start = 33, length = 17)

why would those be different?

File: test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt [hunk 11]
```diff
@@ -53,50 +53,56 @@ Virtual memory usage(MB): %Number%
...
-[4] (%Time%)	16 iterations	Loss: 0.209267094731331	Improvement: 0.0006523
-[4] 'LBFGS Optimizer #2' finished in %Time%.
+[1] 'Building term dictionary' started.
+[1] (%Time%)	71 examples	Total Terms: 3
+[1] 'Building term dictionary' finished in %Time%.
+[2] 'LBFGS data prep' started.
+[2] 'LBFGS data prep' finished in %Time%.
+[3] 'LBFGS Optimizer' started.
+[3] (%Time%)	0 iterations	Loss: 1.0986123085022
+[3] (%Time%)	1 iterations	Loss: 1.00646448135376	Improvement: 0.09215
```
Comment (sfilipi) [inline test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt]: >1.00646448135376	Improvement: 0.09215 [](start = 32, length = 37)

it starts differing here..

File: test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs [hunk 12]
```diff
@@ -1,197 +0,0 @@
...
-using BenchmarkDotNet.Attributes;
-using Microsoft.Data.DataView;
-using Microsoft.ML.Benchmarks.Harness;
-using Microsoft.ML.Data;
-using Microsoft.ML.TestFramework;
-using Microsoft.ML.Trainers;
-using Microsoft.ML.Transforms;
-using Microsoft.ML.Transforms.Text;
-
-namespace Microsoft.ML.Benchmarks
```
Comment (sfilipi) [inline test/Microsoft.ML.Benchmarks/PredictionEngineBench.cs]: >espace Microsoft.ML.Benchmarks [](start = 3, length = 30)

is the deletion intentional?

File: test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs [hunk 13]
```diff
@@ -1,190 +0,0 @@
...
-using BenchmarkDotNet.Engines;
-using Microsoft.Data.DataView;
-using Microsoft.ML.Benchmarks.Harness;
-using Microsoft.ML.Data;
-using Microsoft.ML.TestFramework;
-using Microsoft.ML.Trainers;
-using Microsoft.ML.Transforms;
-using Microsoft.ML.Transforms.Text;
-
-namespace Microsoft.ML.Benchmarks
```
Comment (sfilipi) [inline test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs]: same here, did you mean to delete?

File: test/BaselineOutput/Common/OVA/OVA-CV-iris-out.txt (hunk 9 above)
Comment (Ivanidzo4ka) [reply test/BaselineOutput/Common/OVA/OVA-CV-iris-out.txt]: OVA is multiclass, and for multiclass we would require Key type.

---
In reply to: [263165077](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263165077) [](ancestors = 263165077)

File: test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt (hunk 11 above)
Comment (Ivanidzo4ka) [reply test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt]: different seed I would assume because of added transform.
It converge to same metrics at least.

---
In reply to: [263166427](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263166427) [](ancestors = 263166427)

File: test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs (hunk 13 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Benchmarks/StochasticDualCoordinateAscentClassifierBench.cs]: No, have no idea how what happened.

---
In reply to: [263167708](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263167708) [](ancestors = 263167708)

File: test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs [hunk 14]
```diff
@@ -40,14 +40,14 @@ public void TestPfiRegressionOnDenseFeatures()
             // X4Rand: 3
 
             // For the following metrics lower is better, so maximum delta means more important feature, and vice versa
-            Assert.Equal(3, MinDeltaIndex(pfi, m => m.MeanAbsoluteError.Mean));
```
Comment (sfilipi) [inline test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs]: >       [](start = 0, length = 6)

one too many

File: test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs [hunk 15]
```diff
@@ -294,7 +294,7 @@ private List<BreastCancerExample> ReadBreastCancerExamples()
         public void TestTrainTestSplit()
         {
             var mlContext = new MLContext(0);
-            
+
             var dataPath = GetDataPath("adult.tiny.with-schema.txt");
```
Comment (sfilipi) [inline test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs]: one

File: src/Microsoft.ML.Data/Scorers/MultiClassClassifierScorer.cs [hunk 16]
```diff
@@ -419,7 +419,7 @@ internal static bool CanWrap(ISchemaBoundMapper mapper, DataViewType labelNameTy
             var scoreType = outSchema[scoreIdx].Type;
 
             // Check that the type is vector, and is of compatible size with the score output.
-            return labelNameType is VectorType vectorType && vectorType.Size == scoreType.GetVectorSize();
+            return labelNameType is VectorType vectorType && vectorType.Size == scoreType.GetVectorSize() && vectorType.ItemType == TextDataViewType.Instance;
```
Comment (wschin) [inline src/Microsoft.ML.Data/Scorers/MultiClassClassifierScorer.cs]: >vectorType.ItemType == TextDataViewType.Instance [](start = 109, length = 48)

Can't it be key?

File: test/BaselineOutput/Common/FeatureContribution/FastForestBinary.tsv [hunk 17]
```diff
@@ -4,14 +4,15 @@
 #@   col=X2VBuffer:R4:1-4
 #@   col=X3Important:R4:5
 #@   col=Label:R4:6
-#@   col=Features:R4:7-12
-#@   col=Features:R4:13-18
-#@   col=FeatureContributions:R4:19-24
-#@   col=FeatureContributions:R4:25-30
-#@   col=FeatureContributions:R4:31-36
-#@   col=FeatureContributions:R4:37-42
+#@   col=Label:BL:7
```
Comment (wschin) [inline test/BaselineOutput/Common/FeatureContribution/FastForestBinary.tsv]: Where does it come from? New trainer can also produce new labels?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs [hunk 18]
```diff
@@ -1523,20 +1523,6 @@ private protected SdcaBinaryTrainerBase(IHostEnvironment env, BinaryOptionsBase
 
         private protected abstract SchemaShape.Column[] ComputeSdcaBinaryClassifierSchemaShape();
 
-        private protected override void CheckLabelCompatible(SchemaShape.Column labelCol)
```
Comment (wschin) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: >CheckLabelCompatible [](start = 40, length = 20)

Can label be text? If no, we still a check.

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 19]
```diff
@@ -899,6 +909,18 @@ public void Convert(in BL src, ref SB dst)
...
+        public void Convert(in R8 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in R4 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in I1 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in I2 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in I4 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in I8 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in U1 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in U2 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in U4 src, ref BL dst) => dst = src > 0 ? true : false;
+        public void Convert(in U8 src, ref BL dst) => dst = src > 0 ? true : false;
```
Comment (wschin) [inline src/Microsoft.ML.Data/Data/Conversion.cs]: From my understanding of #2628, it seems we don't want auto-conversion or any auto magics. Here is a message from Tom,
```
We do not do "auto-conversion" for anything in ML.NET because (1) conversion is the job of transforms and (2) adding the smarts "anywhere" requires that we add them "everywhere," which is a maintainability nightmare. (In fact, it has proven to be practically impossible.)
```

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 20]
```diff
@@ -899,6 +909,18 @@ public void Convert(in BL src, ref SB dst)
         public void Convert(in DT src, ref SB dst) { ClearDst(ref dst); dst.AppendFormat("{0:o}", src); }
         public void Convert(in DZ src, ref SB dst) { ClearDst(ref dst); dst.AppendFormat("{0:o}", src); }
         #endregion ToStringBuilder
+        #region ToBL
+        public void Convert(in R8 src, ref BL dst) => dst = src > 0 ? true : false;
```
Comment (wschin) [inline src/Microsoft.ML.Data/Data/Conversion.cs]:
```suggestion
        public void Convert(in R8 src, ref BL dst) => dst = src > 0.5 ? true : false;
```

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 21]
```diff
@@ -899,6 +909,18 @@ public void Convert(in BL src, ref SB dst)
...
+        public void Convert(in R4 src, ref BL dst) => dst = src > 0 ? true : false;
```
Comment (wschin) [inline src/Microsoft.ML.Data/Data/Conversion.cs]:
```suggestion
        public void Convert(in R4 src, ref BL dst) => dst = src > 0.5 ? true : false;
```

File: test/BaselineOutput/Common/FeatureContribution/AveragePerceptronBinary.tsv [hunk 22]
```diff
@@ -4,14 +4,15 @@
 #@   col=X2VBuffer:R4:1-4
 #@   col=X3Important:R4:5
 #@   col=Label:R4:6
-#@   col=Features:R4:7-12
-#@   col=Features:R4:13-18
-#@   col=FeatureContributions:R4:19-24
-#@   col=FeatureContributions:R4:25-30
-#@   col=FeatureContributions:R4:31-36
-#@   col=FeatureContributions:R4:37-42
+#@   col=Label:BL:7
```
Comment (wschin) [inline test/BaselineOutput/Common/FeatureContribution/AveragePerceptronBinary.tsv]: Any reason to have two label columns?

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs [hunk 23]
```diff
@@ -2014,13 +2015,28 @@ public void EntryPointLinearSVM()
         [Fact]
         public void EntryPointBinaryEnsemble()
         {
-            TestEntryPointRoutine("iris.txt", "Trainers.EnsembleBinaryClassifier");
+            TestEntryPointRoutine("iris.txt", "Trainers.EnsembleBinaryClassifier", xfNames:
+                new[] {
+                    "Transforms.ColumnTypeConverter",
+
```
Comment (wschin) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs]: Extra line?

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs [hunk 24]
```diff
@@ -2351,10 +2367,30 @@ internal void TestEntryPointPipelineRoutine(string dataFile, string schema, stri
...
+            var transforms = "";
+
+            for (int i = 0; i < Utils.Size(xfNames); i++)
+            {
+                transforms =
+                    $@"{transforms}
+                       {{
+                         {string.Format(xfTemplate, xfNames[i], i + 1, xfArgs[i], i + 2)}
+                       }},";
+
```
Comment (wschin) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs]: Extra line?

File: test/Microsoft.ML.TestFramework/Datasets.cs [hunk 25]
```diff
@@ -454,7 +454,9 @@ public static class TestDatasets
             trainFilename = @"iris.txt",
             testFilename = @"iris.txt",
             fileHasHeader = true,
-            fileSeparator = '\t'
+            fileSeparator = '\t',
+            mamlExtraSettings = new[] { "xf=Term{col=Label}" }
+
```
Comment (wschin) [inline test/Microsoft.ML.TestFramework/Datasets.cs]: Extra line? Can auto-formatting handle it?

File: test/Microsoft.ML.Tests/FeatureContributionTests.cs [hunk 26]
```diff
@@ -1,344 +0,0 @@
-// Licensed to the .NET Foundation under one or more agreements.
```
Comment (wschin) [inline test/Microsoft.ML.Tests/FeatureContributionTests.cs]: Is the removal of this file intended?

**Comment by wschin** [comment]
Do we have any test to ensure that wrong label type incurs exception?

File: test/BaselineOutput/Common/FeatureContribution/FastForestBinary.tsv (hunk 17 above)
Comment (Ivanidzo4ka) [reply test/BaselineOutput/Common/FeatureContribution/FastForestBinary.tsv]: We restrict binary classification to work only with boolean columns.
It's easier to add convert than change shared code which generate R4 labels for different classes.

---
In reply to: [263181449](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263181449) [](ancestors = 263181449)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs (hunk 18 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: As you can see this is override method. By removing this one, I would force system to fallback to default behavior. Which is - to check it's a boolean column.

---
In reply to: [263182006](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263182006) [](ancestors = 263182006)

File: src/Microsoft.ML.Data/Data/Conversion.cs (hunk 20 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: I'm not sure about that.

---
In reply to: [263190893](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263190893) [](ancestors = 263190893)

File: test/Microsoft.ML.Tests/FeatureContributionTests.cs (hunk 26 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/FeatureContributionTests.cs]: I have no idea why this is happening....

---
In reply to: [263192471](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263192471) [](ancestors = 263192471)

File: src/Microsoft.ML.Data/Data/Conversion.cs (hunk 20 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: I think 0.00000001 looks more closer to 0?

---
In reply to: [263196830](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263196830) [](ancestors = 263196830,263190893)

File: test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs (hunk 15 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs]: one what?

---
In reply to: [263175595](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263175595) [](ancestors = 263175595)

File: test/Microsoft.ML.Tests/FeatureContributionTests.cs [hunk 27]
```diff
@@ -0,0 +1,344 @@
...
+        }
+
+        /// <summary>
+        /// Features: x1, x2vBuff(sparce vector), x3. 
+        /// y = 10x1 + 10x2vBuff + 30x3 + e.
+        /// Within xBuff feature  2nd slot will be sparse most of the time.
+        /// 2nd slot of xBuff has the least importance: Evaluation metrics do not change a lot when this slot is permuted.
+        /// x3 has the biggest importance.
+        /// </summary>
+        private IDataView GetSparseDataset(TaskType task = TaskType.Regression, int numberOfInstances = 1000)
```
Comment (rogancarr) [inline test/Microsoft.ML.Tests/FeatureContributionTests.cs]: Can we put these into a common static library where it can be accessed from all the places that use it, rather than copy it here?

File: test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs (hunk 15 above)
Comment (sfilipi) [reply test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs]: one empty line, or did you mean to have two?

---
In reply to: [263510301](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263510301) [](ancestors = 263510301,263175595)

File: test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs (hunk 14 above)
Comment (sfilipi) [reply test/Microsoft.ML.Tests/PermutationFeatureImportanceTests.cs]: i mean new lines

---
In reply to: [263174998](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263174998) [](ancestors = 263174998)

File: test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt (hunk 11 above)
Comment (sfilipi) [reply test/BaselineOutput/SingleDebug/MulticlassLogisticRegression/LogisticRegression-Non-Negative-CV-iris-out.txt]: actually it is fine. 

---
In reply to: [263168167](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263168167) [](ancestors = 263168167,263166427)

**Comment by rogancarr** [comment]
Side note: This description is pretty vague ! :)

File: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs [hunk 28]
```diff
@@ -145,7 +145,14 @@ private protected virtual void CheckLabelCompatible(SchemaShape.Column labelCol)
             IDataView validationSet = null, IPredictor initPredictor = null)
         {
             var trainRoleMapped = MakeRoles(trainSet);
-            var validRoleMapped = validationSet == null ? null : MakeRoles(validationSet);
+            CheckInputSchema(SchemaShape.Create(trainSet.Schema));
```
Comment (rogancarr) [inline src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs]: >CheckInputSchema [](start = 12, length = 16)

Nit: Ordering for `train` and `valid` in `Make` and `Check` are different. I'd prefer to have the same sequence.

File: src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs [hunk 29]
```diff
@@ -99,19 +98,14 @@ private protected IDataView MapLabelsCore<T>(DataViewType type, InPredicate<T> e
             Host.Assert(data.Schema.Label.HasValue);
 
             var lab = data.Schema.Label.Value;
```
Comment (rogancarr) [inline src/Microsoft.ML.StandardLearners/Standard/MultiClass/MetaMulticlassTrainer.cs]: >lab [](start = 16, length = 3)

Nit: This hurts my eyes.

File: test/BaselineOutput/Common/FeatureContribution/AveragePerceptronBinary.tsv (hunk 22 above)
Comment (rogancarr) [reply test/BaselineOutput/Common/FeatureContribution/AveragePerceptronBinary.tsv]: Ditto

---
In reply to: [263191537](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263191537) [](ancestors = 263191537)

File: test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs (hunk 15 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs]: It's actually codeflow specific. it show two new lines if you remove leading spaces from it

---
In reply to: [263685676](https://github.com/dotnet/machinelearning/pull/2804#discussion_r263685676) [](ancestors = 263685676,263510301,263175595)
