### PR TITLE
Fix bug in WordBagEstimator when training on empty data

### LINKED ISSUE #969: TestEstimatorCore fails when training on EmptyDataView for the listed transforms.
`TestEstimatorCore` method tests the schema of estimator that of transformer. It trains estimator on EmptyDataView and get the schema. Then, it fits the estimator on actual data, and get the schema from transformer.

#### Ngram
It then verifies of both schema are same. However for the case of ngram transform, schema learnt from EmptyDataView is different from actually learned from data. The actual cause is size of ngram is zero in case of training on EmptyDataView which causes output vector type to be variable length. Additionally, some other meta are not filled properly in this case.

#### PCA Transform
Can not applied on EmptyDataView. Exception is thrown regrading empty data view.

Because of this following tests are failing right now.

WordBagWorkout
NgramWorkout
PcaWorkout

Need to think how to fix it.

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #969 .
Related to issue #4693 .

### CODE REVIEW

File: src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs [hunk 1]
```diff
@@ -28,6 +28,31 @@
 
 namespace Microsoft.ML.Transforms
 {
+    internal sealed class MissingValueDroppingEstimator : TrivialEstimator<MissingValueDroppingTransformer>
```
Comment (harishsk) [inline src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs]: Is this useful in other cases? Do we need to add this to the catalog and make it public?

File: src/Microsoft.ML.Transforms/Text/WordBagTransform.cs [hunk 2]
```diff
@@ -149,17 +148,14 @@ internal static ITransformer CreateTransfomer(IHostEnvironment env, Options opti
...
-            return new TransformerChain<ITransformer>(new[] { t0, t1, t2 });
+            IEstimator<ITransformer> estimator = NgramExtractionUtils.GetConcatEstimator(h, options.Columns);
+            estimator = estimator.Append(new WordTokenizingEstimator(env, tokenizeColumns));
+            estimator = estimator.Append(NgramExtractorTransform.CreateEstimator(h, extractorArgs, estimator.GetOutputSchema(inputSchema)));
+            return estimator;
         }
 
         internal static IDataTransform Create(IHostEnvironment env, Options options, IDataView input) =>
-            (IDataTransform)CreateTransfomer(env, options, input).Transform(input);
+            (IDataTransform)CreateEstimator(env, options, SchemaShape.Create(input.Schema)).Fit(input).Transform(input)/* CreateTransfomer(env, options, input).Transform(input)*/;
```
Comment (harishsk) [inline src/Microsoft.ML.Transforms/Text/WordBagTransform.cs]: Nit: Can you please remove the commented code?

File: src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs (hunk 1 above)
Comment (yaeldekel) [reply src/Microsoft.ML.Transforms/MissingValueDroppingTransformer.cs]: I don't think it is - seems to be something very specific to Ngram extraction.

---
In reply to: [370393234](https://github.com/dotnet/machinelearning/pull/4696#discussion_r370393234) [](ancestors = 370393234)
