### PR TITLE
Using internal TempFilePath

### LINKED ISSUE #6170: Using ML.NET with Mono On Unity
**System Information (please complete the following information):**
 - OS & Version: Android (Compile code from Mono)
 - ML.NET Version: ML.NET 1.7.1
 - .NET Version: .NET Standard 2.0

**Describe the bug**
When I am trying to load model from my device, I will get "UnauthorizedAccessException: Access to the path "/tmp" is denied".

**To Reproduce**
1. Use Mono to Compile your code,
2. Run it on android,
3. Get the exception.

**Expected behavior**
I expected it to load the model correctly. I think this is because the Mono makes "Path.GetTempPath() " you used to return "/tmp/", but I cannot get the permission to access that because my device is not rooted. Is there any chance to skip the code which use the temp path? 

**Screenshots, Code, Sample Projects**
Here is the Exception Screenshot:
image

And here is the Code:
```
            Debug.Log(Path.GetTempPath()); // This line will print "/tmp/"
            DirectoryInfo dirInfo = new DirectoryInfo(Application.persistentDataPath + "/MLModel");
            if (!dirInfo.Exists)
            {
                dirInfo.Create();
            }

            FileInfo info = new FileInfo(Application.persistentDataPath + ModelPath);
            if (!info.Exists)
            {
                info.Create().Dispose();
                InitializeModelFromStreamingData(Application.persistentDataPath + ModelPath);
            }

            Stream stream = info.OpenRead();
            _transformer = _context.Model.Load(stream, out _schema); // This line will throw the exception.
            _model = _context.Model.CreatePredictionEngine<ModelInput, ModelOutput>(_transformer);
            stream.Close();
```

**Additional context**
I am using Unity with C#. If this problem cannot be solved, is there any suggestion to make me load the model in Unity?

Thank you!

### PR DESCRIPTION
**Pull request by michaelgsharp**
Using `IHostInternal.TempFilePath` when possible when using the `RepositoryWriter`. This will use the location set by the user when possible. Fixes #6170

### CODE REVIEW

**Comment by michaelgsharp** [comment]
Besides making our code more consistent and using the specified temp file path, this fixes an issue where users may not have access to the path returned by `Path.GetTempPath()` as noted here #6170.

File: src/Microsoft.ML.Core/Data/Repository.cs [hunk 1]
```diff
@@ -113,14 +113,19 @@ internal Repository(bool needDir, IExceptionContext ectx)
...
             else
                 GC.SuppressFinalize(this);
         }
 
-        private static string GetShortTempDir()
+        private static string GetShortTempDir(IExceptionContext ectx)
         {
-            var path = Path.Combine(Path.GetFullPath(Path.GetTempPath()), "ml_dotnet", Path.GetRandomFileName());
+            string path;
+            if (ectx is IHostEnvironmentInternal iHostInternal)
```
Comment (LittleLittleCloud) [inline src/Microsoft.ML.Core/Data/Repository.cs:124]: In what circumstance would a ectx be an `IHostEnvironmentInternal `

Comment (michaelgsharp) [reply src/Microsoft.ML.Core/Data/Repository.cs:124]: It actually is all the time. The only time that it _wouldn't_ be is if an end user made their own class that implements `IExceptionContext`. That's why the check is still there for the off chance that actually happens.

File: src/Microsoft.ML.Core/Data/Repository.cs [hunk 2]
```diff
@@ -113,14 +113,19 @@ internal Repository(bool needDir, IExceptionContext ectx)
...
+                path = Path.Combine(Path.GetFullPath(iHostInternal.TempFilePath), "ml_dotnet", Path.GetRandomFileName());
```
Comment (tarekgh) [inline src/Microsoft.ML.Core/Data/Repository.cs:125]: >ml_dotnet [](http://example.com/codeflow?start=83&length=9)

how we usually clean the generated files?

**Review by tarekgh — APPROVED** [review]

File: src/Microsoft.ML.Data/Commands/DataCommand.cs [hunk 3]
```diff
@@ -398,28 +398,28 @@ internal static class LoaderUtils
         /// <summary>
         /// Saves <paramref name="loader"/> to the specified <paramref name="file"/>.
         /// </summary>
-        public static void SaveLoader(ILegacyDataLoader loader, IFileHandle file)
+        public static void SaveLoader(ILegacyDataLoader loader, IFileHandle file, IExceptionContext ectx)
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Commands/DataCommand.cs:401]: I wouldn't cast these as `IExceptionContext`. I would use `IHostEnvironment` instead.

File: src/Microsoft.ML.Data/Commands/DataCommand.cs [hunk 4]
```diff
@@ -398,28 +398,28 @@ internal static class LoaderUtils
...
-                SaveLoader(loader, stream);
+                SaveLoader(loader, stream, ectx);
             }
         }
 
         /// <summary>
         /// Saves <paramref name="loader"/> to the specified <paramref name="stream"/>.
         /// </summary>
-        public static void SaveLoader(ILegacyDataLoader loader, Stream stream)
+        public static void SaveLoader(ILegacyDataLoader loader, Stream stream, IExceptionContext ectx)
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Commands/DataCommand.cs:416]:
```suggestion
        public static void SaveLoader(ILegacyDataLoader loader, Stream stream, IHostEnvironment host)
```

File: src/Microsoft.ML.Data/Commands/DataCommand.cs (hunk 3 above)
Comment (eerhardt) [reply src/Microsoft.ML.Data/Commands/DataCommand.cs:401]:
```suggestion
        public static void SaveLoader(ILegacyDataLoader loader, IFileHandle file, IHostEnvironment host)
```

File: src/Microsoft.ML.Core/Data/Repository.cs [hunk 5]
```diff
@@ -113,14 +113,19 @@ internal Repository(bool needDir, IExceptionContext ectx)
...
+            else
+                path = Path.Combine(Path.GetFullPath(Path.GetTempPath()), "ml_dotnet", Path.GetRandomFileName());
+
             Directory.CreateDirectory(path);
             return path;
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/Repository.cs:130]: This could be rewritten so it doesn't duplicate the strings:

```suggestion
            string tempPath = ectx is IHostEnvironmentInternal iHostInternal ?
                iHostInternal.TempFilePath :
                Path.GetTempPath();

            string path = Path.Combine(Path.GetFullPath(tempPath), "ml_dotnet", Path.GetRandomFileName());
            Directory.CreateDirectory(path);
            return path;
```
