### PR TITLE
Fix GcNorm and LpNorm xml doc

### LINKED ISSUE #3502: LpNorm and GcNorm doc math equations
Math display error in the LpNormNormalizingEstimator:
$y = \frac{x - \mu(x)}{L(x)}$

As well as in the GlobalContrastNormalizingEstimator.

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.lpnormnormalizingestimator?view=ml-dotnet&branch=smoke-test-preview

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.globalcontrastnormalizingestimator?view=ml-dotnet&branch=smoke-test-preview

### LINKED ISSUE #3540: Fix the XML documentation of GcNorm and LpNorm
It is missing the part of the template that mentions the estimator:  Create <estimator>.

### PR DESCRIPTION
**Pull request by artidoro**
Fixes #3540
Fixes #3502

### CODE REVIEW

File: src/Microsoft.ML.Transforms/GcnTransform.cs [hunk 1]
```diff
@@ -814,27 +814,23 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
...
     /// if the user specifies that the mean should be zero, or otherwise:
-    ///
-    ///     $y = \frac{x}{L(x)}$
-    ///
+    /// $y = \frac{x}{L(x)}$
     /// There are four types of norm that can be selected by the user to be applied on input vector $x$. They are defined as follows:
-    /// - <xref:Microsoft.ML.Transforms.LpNormNormalizingEstimatorBase.NormFunction.L1>
+    /// - <xref:Microsoft.ML.Transforms.LpNormNormalizingEstimatorBase.NormFunction.L1>:
     ///
     ///     $L_1(x) = \sum_i |x_i|$
```
Comment (shmoradims) [inline src/Microsoft.ML.Transforms/GcnTransform.cs]: > $L_1(x) = \sum_i |x_i|$ [](start = 11, length = 24)

Let's move these righ after ':' on the same line. they'd look nicer: 
[https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.lpnormnormalizingestimator?view=ml-dotnet&branch=smoke-test-preview](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.lpnormnormalizingestimator?view=ml-dotnet&branch=smoke-test-preview)
