### PR TITLE
Cleaned and fixed public API surface for KMeans, NaiveBayes, OLS.

### LINKED ISSUE #2620: Scrubbing rest of learners
Sub task of #2613
`FieldAwareFactorizationMachineTrainer`
`MatrixFactorizationTrainer`
`PriorTrainer`
`RandomTrainer`
`SymSgdClassificationTrainer`
`KMeansPlusPlusTrainer`
`MultiClassNaiveBayesTrainer`
`OlsLinearRegressionTrainer`
and their base classes

### PR DESCRIPTION
**Pull request by zeahmed**
This is the final PR related to #2620. This PR finally fixes #2620

The following learners are addressed in this PR.

* KMeansPlusPlusTrainer
* MultiClassNaiveBayesTrainer (No sample for NaiveBayes opened issue #2818)
* OlsLinearRegressionTrainer

the following tasks were performed in classes related to above learners.

Checking to make sure that unnecessary public methods/properties be internal.
Renaming parameters according to standard.
Creating/Refactoring samples according to standards.

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
>             public float L2Weight = 1e-6f;

L2Regularization please.

---
Refers to: src/Microsoft.ML.HalLearners/OlsLinearRegression.cs:50 in 7b2890b. [](commit_id = 7b2890b021c1e36285875a303150adc2e9f9c019, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>             public bool PerParameterSignificance = true;

CalculateStatistics ?

---
Refers to: src/Microsoft.ML.HalLearners/OlsLinearRegression.cs:56 in 7b2890b. [](commit_id = 7b2890b021c1e36285875a303150adc2e9f9c019, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>             public int ClustersCount = Defaults.ClustersCount;

NumberOfClusters?

---
Refers to: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs:61 in 7b2890b. [](commit_id = 7b2890b021c1e36285875a303150adc2e9f9c019, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>             KMeansParallel = 2

KMeansYinyang ?

---
Refers to: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs:43 in 7b2890b. [](commit_id = 7b2890b021c1e36285875a303150adc2e9f9c019, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
Small comments, otherwise looks super good!

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs [hunk 1]
```diff
@@ -9,7 +9,7 @@ public static void Example()
         {
             // Create a new ML context, for ML.NET operations. It can be used for exception tracking and logging, 
             // as well as the source of randomness.
-            var ml = new MLContext();
+            var ml = new MLContext(seed: 1, conc: 1);
```
Comment (sfilipi) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs]: >seed: 1, conc: 1 [](start = 35, length = 16)

is this needed?

**Comment by sfilipi** [comment]
>         /// </summary>

Please link to the KMeansPlusPlusTrainerthrough <see cref="KMeansPlusPlusTrainer">

Shahab put a template in place for how to document extensions, so we have a pointer to the main estimator where there are more explanations. 


---
Refers to: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs:19 in 2a1bb29. [](commit_id = 2a1bb29eae3e6537e50e052955cacf9921e37931, deletion_comment = False)

**Comment by sfilipi** [comment]
>         /// Train a KMeans++ clustering algorithm.

similr, link to KMeansPlusPlusTrainer

---
Refers to: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs:48 in 2a1bb29. [](commit_id = 2a1bb29eae3e6537e50e052955cacf9921e37931, deletion_comment = False)

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs (hunk 1 above)
Comment (zeahmed) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs]: Yes, its needed otherwise results different on every run.

---
In reply to: [262274167](https://github.com/dotnet/machinelearning/pull/2819#discussion_r262274167) [](ancestors = 262274167)
