### PR TITLE
Fixing parameters in ML.NET Public API

### LINKED ISSUE #2257: Rename `weights` parameter in ML.NET Public API
Couple of conventions to follow for `weights` parameter in ML.NET Public API

- Name of the `weight` argument in trainer API should be consistent with the other column names i.e it should end on *Column.
- Proposal to disambiguate this by calling it exampleWeightColumn.

@glebuk

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #2257, #2660, #2177 

Also related to #2680 #2613 

Using ApiReview tool, went through the public surface area making the changes (as described in the issue)

### CODE REVIEW

File: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs [hunk 1]
```diff
@@ -29,7 +29,7 @@ public static class KMeansClusteringExtensions
         /// </example>
         public static KMeansPlusPlusTrainer KMeans(this ClusteringCatalog.ClusteringTrainers catalog,
            string featureColumn = DefaultColumnNames.Features,
```
Comment (TomFinley) [inline src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: >featureColumn [](start = 18, length = 13)

So we're calling this `exampleWeightColumnName`, but calling the above `featureColumn`. I'm not terribly insistent one way or the other, but we should at least be consistent I think.

In the original issue you proposed calling this `* exampleWeightColumn`, which seems to me to be consistent with the existing behavior *here*. Yet elsewhere I see that we are calling things `labelColumn` and `labelColumnName` here and there.

Is this on someone's radar? If we are not going to fix it (we should!) a second best alternative would be to be at least locally consistent. Not sure what @rogancarr and @eerhardt and @sfilipi think?

Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: Issue #2177  proposes we use suffix *ColumnName consistently  

In this PR I am making that change for  weight, groupid  parameters.  In a follow up PR I will do it for label and features.  

So once  *both* PRs go in, we will mark #2177 as complete, and the following convention will be used
- labelColumnName
- featureColumnName
- exampleWeightColumnName
- rowGroupColumnName

This is certainly on my radar, as i drive towards consistency in the APIs . I have also updated the description of the issue so it has reference to issue #2177 .  Hope that sounds good ?

Comment (TomFinley) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: Very good, thank you @abgoswam ! Sorry missed that discussion.

File: src/Microsoft.ML.HalLearners/HalLearnersCatalog.cs [hunk 2]
```diff
@@ -31,15 +31,15 @@ public static class HalLearnersCatalog
...
+            string exampleWeightColumnName = null)
         {
             Contracts.CheckValue(catalog, nameof(catalog));
             var env = CatalogUtils.GetEnvironment(catalog);
             var options = new OlsLinearRegressionTrainer.Options
             {
                 LabelColumn = labelColumnName,
                 FeatureColumn = featureColumnName,
-                WeightColumn = weightColumn != null ? Optional<string>.Explicit(weightColumn) : Optional<string>.Implicit(DefaultColumnNames.Weight)
+                WeightColumn = exampleWeightColumnName != null ? Optional<string>.Explicit(exampleWeightColumnName) : Optional<string>.Implicit(DefaultColumnNames.Weight)
```
Comment (TomFinley) [inline src/Microsoft.ML.HalLearners/HalLearnersCatalog.cs]: Uh oh. Am I wrong or is there *literally no way* to have non-weighted training if you happen to have a column named `Weight`????

It looks like there's an existing issue #1065 that is capturing this.

Comment (TomFinley) [reply src/Microsoft.ML.HalLearners/HalLearnersCatalog.cs]: Although I see it's incidentally assigned to you @abgoswam . 😄 Maybe after this PR we can think about how to address this.

Comment (abgoswam) [reply src/Microsoft.ML.HalLearners/HalLearnersCatalog.cs]: Sounds good. We should fix this behavior as part of  #1065   (in a separate PR).

File: src/Microsoft.ML.PCA/PCACatalog.cs [hunk 3]
```diff
@@ -15,21 +15,21 @@ public static class PcaCatalog
...
+        /// <param name="exampleWeightColumnName">The name of the example weight column (optional).</param>
         /// <param name="rank">The number of principal components.</param>
         /// <param name="overSampling">Oversampling parameter for randomized PrincipalComponentAnalysis training.</param>
         /// <param name="center">If enabled, data is centered to be zero mean.</param>
         /// <param name="seed">The seed for random number generation.</param>
         public static PrincipalComponentAnalysisEstimator ProjectToPrincipalComponents(this TransformsCatalog.ProjectionTransforms catalog,
             string outputColumnName,
             string inputColumnName = null,
-            string weightColumn = PrincipalComponentAnalysisEstimator.Defaults.WeightColumn,
+            string exampleWeightColumnName = PrincipalComponentAnalysisEstimator.Defaults.WeightColumn,
```
Comment (eerhardt) [inline src/Microsoft.ML.PCA/PCACatalog.cs]: Defaulting this to `null` will be covered in #1065, right?

Comment (abgoswam) [reply src/Microsoft.ML.PCA/PCACatalog.cs]: Yes, perhaps #1065 would be the right place to  set this to `null` as default value, since that issue related to changing the _behavior_ of the weights parameters.

The issues addressed by this PR are all related  to _consistency_ in API naming convention.

File: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs (hunk 1 above)
Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: @tomfinley. I have consolidated all the changes in this PR.  So  this PR  addresses   {features, labels, groupid, weight} column names in a consistent manner.

---
In reply to: [258779314](https://github.com/dotnet/machinelearning/pull/2665#discussion_r258779314) [](ancestors = 258779314)

Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: @tomfinley. I have consolidated all the changes in this PR.  So  this PR  addresses   {features, labels, groupid, weight} column names in a consistent manner.

---
In reply to: [258776812](https://github.com/dotnet/machinelearning/pull/2665#discussion_r258776812) [](ancestors = 258776812)

File: src/Microsoft.ML.PCA/PCACatalog.cs (hunk 3 above)
Comment (abgoswam) [reply src/Microsoft.ML.PCA/PCACatalog.cs]: #1065 did not address this. hence taking care of this in this PR

---
In reply to: [259028009](https://github.com/dotnet/machinelearning/pull/2665#discussion_r259028009) [](ancestors = 259028009)

Comment (abgoswam) [reply src/Microsoft.ML.PCA/PCACatalog.cs]: fixed in this PR itself.

---
In reply to: [259039000](https://github.com/dotnet/machinelearning/pull/2665#discussion_r259039000) [](ancestors = 259039000)

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs [hunk 4]
```diff
@@ -97,27 +97,27 @@ public static class TreeExtensions
         /// Ranks a series of inputs based on their relevance, training a decision tree ranking model through the <see cref="FastTreeRankingTrainer"/>.
         /// </summary>
         /// <param name="catalog">The <see cref="RankingCatalog"/>.</param>
-        /// <param name="labelColumn">The labelColumn column.</param>
-        /// <param name="featureColumn">The featureColumn column.</param>
-        /// <param name="groupId">The groupId column.</param>
-        /// <param name="weights">The optional weights column.</param>
+        /// <param name="labelColumnName">The name of the label column.</param>
+        /// <param name="featureColumnName">The name of the feature column.</param>
+        /// <param name="rowGroupColumnName">The name of the group column.</param>
```
Comment (eerhardt) [inline src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: This isn't necessary for this PR, but I wonder if we need some documentation around the `row group` column. I'm obviously not an expert, but I have no idea what this is.

File: test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs [hunk 5]
```diff
@@ -513,7 +513,7 @@ private static void RunEndToEnd(MLContext mlContext, IDataView trainData, string
             // Construct the learning pipeline. Note that we are now providing a contract name for the custom mapping:
             // otherwise we will not be able to save the model.
             var estimator = mlContext.Transforms.CustomMapping<InputRow, OutputRow>(CustomMappings.IncomeMapping, nameof(CustomMappings.IncomeMapping))
-                .Append(mlContext.BinaryClassification.Trainers.FastTree(labelColumn: "Label"));
+                .Append(mlContext.BinaryClassification.Trainers.FastTree(labelColumnName: "Label"));
```
Comment (eerhardt) [inline test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs]: This usually means the cookbook .md file needs to be updated as well.

Comment (abgoswam) [reply test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs]: Thanks for making me take a second look at this.  Updated the cookbook .md file in a couple of places.

p.s. my initial search for "labelColumn" in the cookbook .md file did not return relevant results.  Apparently it used to be called just "label" at some point :)

---
In reply to: [259626158](https://github.com/dotnet/machinelearning/pull/2665#discussion_r259626158) [](ancestors = 259626158)

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs (hunk 4 above)
Comment (abgoswam) [reply src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: fyi...#2536 gives some context on this.  we can add more documentation around this in  follow up documentation focused  PRs.
