### PR TITLE
Combined methods related to splitting data into one single method. Also fixed related issues.

### LINKED ISSUE #4048: System.ArgumentOutOfRangeException : Could not find input column 'SamplingKeyColumn'
### System information

- **Win10/distro**:
- **.NET Version Core 2.1**: 

### Issue

When I am running my RefitBestPipeline function. i.e my function to run my model over the entire data I got this error.

Message: System.ArgumentOutOfRangeException : Could not find input column 'SamplingKeyColumn'
Parameter name: inputSchema

This is some internal error I am calling the same load and transfer function that I used to build my model.

### Source code / logs
private ITransformer RefitBestPipeline(ExperimentResult<RegressionMetrics> experimentResult)
        {
            DebugHelper.WriteHeader("=============== Re-fitting best pipeline ===============");
            //var textLoader = mlContext.Data.CreateTextLoader(columnInference.TextLoaderOptions);
            //_trainDataView = _mlContext.Data.LoadFromEnumerable<T>(trainingCollection);
            //_testDataView = _mlContext.Data.LoadFromEnumerable<T>(testCollection);

            //IEnumerable<T> allData = trainingCollection.Concat(testCollection);
            //IDataView allDataView = _mlContext.Data.LoadFromEnumerable<T>(testCollection);          
            // Generate the dataview for all of the data
            LoadData(_modelInput.TrainingCollection);
            TransformData();

            //var combinedDataView = textLoader.Load(new MultiFileSource(TrainDataPath, TestDataPath));
            RunDetail<RegressionMetrics> bestRun = experimentResult.BestRun;

            return bestRun.Estimator.Fit(_trainDataView); // pass in the data view for all of the data.
        }

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

### LINKED ISSUE #5221: CrossValidation Macros stops working in 1.5.0
ML.NET 1.5.0

Have NimbusML (built with ML.NET 1.5.0, here is [PR](https://dev.azure.com/aifx/public/_build/results?buildId=2988&view=results) that does this )
Run the tests in [test.cv](https://github.com/microsoft/NimbusML/blob/master/src/python/nimbusml/tests/model_selection/test_cv.py) 
test_default_label2  fails with error:
Error: *** System.InvalidOperationException: 'Column 'GroupId' not found' StackTrace:    at Microsoft.ML.EntryPoints.TrainerEntryPointsUtils.FindColumn(IExceptionContext ectx, DataViewSchema schema, Optional`1 value)
at Microsoft.ML.EntryPoints.TrainerEntryPointsUtils.Train[TArg,TOut](IHost host, TArg input, Func`1 createTrainer, Func`1 getLabel, Func`1 getWeight, Func`1 getGroup, Func`1 getName, Func`1 getCustom, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples)
at Microsoft.ML.Trainers.LightGbm.LightGbm.TrainRanking(IHostEnvironment env, Options input)

This is a regression from ML.NET 1.5.0.preview2

I did some debugging, it appears that once macros is expanded ColumnSelector Transform drops GroupId. ColumnSelector appears to be added by Macros expansion.

### LINKED ISSUE #5256: AutoML Exception: System.ArgumentOutOfRangeException: 'Could not find input column 'SamplingKeyColumn' (Parameter 'inputSchema')'
Hi, I get an exception on prediction with AutoML. 
Before you run the Problem you need to reference two NuGet Packages Microsoft.ML and Microsoft.ML.AutoML
Here ist the complete code to reproduce the error. Run in VS2019:

```C#
using Microsoft.ML;
using Microsoft.ML.AutoML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using System;
using System.Collections.Generic;
using System.Linq;
using static Microsoft.ML.DataOperationsCatalog;

namespace AutoML
{
    class Program
    {
        static void Main(string[] args)
        {
            var mlContext = new MLContext(seed: 0);

            var examples = GenerateData(100);

            var dataview = mlContext.Data.LoadFromEnumerable(examples);

            TrainTestData trainTestSplit = mlContext.Data.TrainTestSplit(dataview, testFraction: 0.1, samplingKeyColumnName: null);
            IDataView trainingData = trainTestSplit.TrainSet;
            IDataView testData = trainTestSplit.TestSet;

            ITransformer model = TrainRegresionAutoML(trainingData);
            ReportOnFeatureImportance(mlContext, model, dataview);            

            OutputData prediction = PredictRegresinAutoML<InputData,OutputData>(model, new InputData(){A = 6, B = 6});          
        }

        static ITransformer TrainRegresionAutoML(IDataView trainData)
        {
            var mlContext = new MLContext(seed: 0);

            var settings = new RegressionExperimentSettings
            {
                MaxExperimentTimeInSeconds = 10, // In Second
                OptimizingMetric = RegressionMetric.RSquared,
                CacheDirectory = null
            };

            var experiment = mlContext.Auto().CreateRegressionExperiment(settings);
            
            var model = experiment.Execute(trainData);            


            return model.BestRun.Model;
        }

        private static void ReportOnFeatureImportance(MLContext context, ITransformer model, IDataView data)
        {            
            // Need to cast from the ITransformer interface to gain access to the LastTransformer property.
            var typedModel = (TransformerChain<IPredictionTransformer<object>>)model;
            var modelParams = typedModel.LastTransformer.Model as FastTreeRegressionModelParameters;
            var weights = new VBuffer<float>();
            modelParams.GetFeatureWeights(ref weights);            
        }

        static TDst PredictRegresinAutoML<TSrc, TDst>(ITransformer model, TSrc inputData) 
            where TSrc : class
            where TDst : class, new()
        {
            var mlContext = new MLContext(seed: 0);

            var predictor = mlContext.Model.CreatePredictionEngine<TSrc, TDst>(model);
            return predictor.Predict(inputData);
        }      

        private static IEnumerable<InputData> GenerateData(int count,
            int seed = 0)

        {
            for (int i = 0; i < count; i++)
            {
                for (int ii = 0; ii < count; ii++)
                {
                    yield return new InputData
                    {
                        A = i,
                        B = ii,
                        Value = i * ii
                    };
                }
            }
        }       
    }

    public class InputData
    {     
        public float A { get; set; }
        
        public float B { get; set; }

        [ColumnName("Label")]
        public float Value { get; set; }
    }

    public class OutputData
    {
        [ColumnName("Score")]
        public float Result;
    }

    public class FeatureImportance
    {
        public string Name { get; set; }

        public double RSquaredMean { get; set; }

        public double CorrelationCoefficient { get; set; }
    }
}
```

### PR DESCRIPTION
**Pull request by antoniovs1029**
This PR combines `CreateStratificationColumn` and `EnsureGroupPreservationColumn`, and some code on `GetSplitColumn`, into a new method called `CreateSplitColumn`. This method receives a `samplingKeyColumnName` parameter and _always_ creates a new column named `SplitColumn` based on the `samplingKeyColumn`... the new column is elsewhere in the code used for splitting datasets for Train-Test splits or Cross-Validation Splits, and it's _always_ safe to drop the new column as well. **Note**: the `samplingKeyColumn` that `CreateSplitColumn` receives as parameter, or the column it creates, are called `samplingKeyColumn`, `stratificationColumn`, `groupPreservationColumn`, or `splitColumn` (or maybe even `rowGroupColumn` ?) elsewhere in the code or docs, depending on where on the code you're / which API you're calling (ML.NET's TrainTestSplit, CrossValidationSplit, Evaluate or CrossValidate... AutoML, MAML, or NimbusML/Entrypoints). The inconsistency of the naming for this column is a long-standing problem, but since they're names used both in public APIs and for historical reasons, I guess there's not much we can do now (see #2536, and related issues and PR's).

This PR also solves multiple issues related with the "samplingKeyColumn" when splitting data:

**Issue**:  When `samplingKeyColumn` is KeyType, dropping the original samplingKeyColumn when calling from entrypoints, makes it impossible to reuse that column
**Solution**: Use a copy column transformer to copy the original column, so that it's safe to drop the new column elsewhere without loosing the original column
Fixes #5221 : Issue with NimbusML test

**Issue** : a "samplingKeyColumn" is created, but not dropped, when users split data with ML.NET's API before training a model with AutoML, causing some problems when reusing the AutoML model
**Solution**: Always drop the new column when calling from ML.NET's APIs. Note: to distinguish between the "samplingKeyColumn" provided by the user, and the one we internally create, the new column is now called "SplitColumn".
Fixes #5256
Fixes #4048
Fixes https://github.com/dotnet/machinelearning-modelbuilder/issues/694

**Issue**: If the "samplingKeyColumn" is float/double type, and includes negative values, or is normalized and outside the (0,1) range, then it might not work as expected.
**Solution**: Use `ensureZeroUntouched = false` in the normalizing estimator, and always normalize if it's float/double
Fixes https://github.com/dotnet/machinelearning/pull/5227#discussion_r441994977

### CODE REVIEW

File: src/Microsoft.ML.EntryPoints/TrainTestSplit.cs [hunk 1]
```diff
@@ -106,11 +108,15 @@ public static string CreateStratificationColumn(IHost host, ref IDataView data,
                 else
                 {
                     if (data.Schema[stratificationColumn].IsNormalized() || (type != NumberDataViewType.Single && type != NumberDataViewType.Double))
-                        return stratificationColumn;
-
-                    data = new NormalizingEstimator(host,
-                        new NormalizingEstimator.MinMaxColumnOptions(stratCol, stratificationColumn, ensureZeroUntouched: true))
-                        .Fit(data).Transform(data);
+                    {
+                        data = new ColumnCopyingEstimator(host,(stratCol,stratificationColumn)).Fit(data).Transform(data);
```
Comment (yaeldekel) [inline src/Microsoft.ML.EntryPoints/TrainTestSplit.cs:112]: >ColumnCopyingEstimator [](start = 35, length = 22)

Should this be added to `EnsureGroupPreservationColumn` as well?

And more generally, would it make sense to unify the two methods? There is also a method called `GetSplitColumn` in line 285 in CrossValidationCommand.cs that does more or less the same thing. I think the same utility method should be called for maml, entry points and the C# API.

**Comment by yaeldekel** [comment]
Can you add a unit test that has a similar case to the NimbusML test that exposed this bug?

File: src/Microsoft.ML.EntryPoints/TrainTestSplit.cs (hunk 1 above)
Comment (antoniovs1029) [reply src/Microsoft.ML.EntryPoints/TrainTestSplit.cs:112]: So I took a quick look into the `EnsureGroupPreservationColumn` callers, and it doesn't seem that they drop the created column, so this wouldn't be an issue there. I'll look into it more later to confirm this.

About merging these methods, I think it would be a good idea to maintain consistency across the codebase, although it wouldn't be necessary to fix the issue opened by @ganik to unblock NimbusML update. I'll look into this idea.

---
In reply to: [438552643](https://github.com/dotnet/machinelearning/pull/5227#discussion_r438552643) [](ancestors = 438552643)

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs [hunk 2]
```diff
@@ -6613,5 +6613,231 @@ public void SummarizeEntryPointTest()
 
             Done();
         }
+
+        [Fact]
+        void RankingWithColumnIdEntryPoint()
+        {
+            Env.ComponentCatalog.RegisterAssembly(typeof(LightGbmBinaryModelParameters).Assembly);
```
Comment (antoniovs1029) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:6620]: I added this test with pretty much the same graph produced by the NimbusML test that created this issue.

For some reason it seems that to test LightGBM trainers using entrypoints we actually need to explicitly register the LightGbm assembly... otherwise the LightGBM's entrypoints aren't found when running the test and an exception is thrown. Does anybody know why we need to have this special treatment for LightGBM on entrypoint tests? @yaeldekel @ganik ? I was confused by this, and it might become relevant to know why this is necessary in the future. Thanks !

Comment (yaeldekel) [reply test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:6620]: Hi @antoniovs1029 , The reason you need to register the LightGbm assembly when you use entrypoints, is because the graph runner gets the graph as a json object, and from the entrypoint name it has to figure out which method to call. This is done using the appropriate LoadableClassAttribute (or EntrypointModuleAttribute, I forget exactly which one is used), which is defined in the LightGbm assembly.
This is similar to the reason we have to register the required assemblies when running maml, since it has to figure out the correct trainer/estimator to instantiate from the string specified in the commandline, and also why we have to register assemblies when loading a model from disk.
Specifically in the case of your test, I think that in the constructor of one of the base classes of the test project some assemblies are registered, if LightGbm is not one of them you can add it there.

File: src/Microsoft.ML.EntryPoints/TrainTestSplit.cs (hunk 1 above)
Comment (antoniovs1029) [reply src/Microsoft.ML.EntryPoints/TrainTestSplit.cs]: I confirmed that when `EnsureGroupPreservationColumn` was called, the `samplingKeyColumn` was never dropped, so the issue didn't apply on that case.

Also, I've merged the methods you've mentioned, so now only `CreateGroupPreservationColumn` exists

---
In reply to: [438969558](https://github.com/dotnet/machinelearning/pull/5227#discussion_r438969558) [](ancestors = 438969558,438552643)

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs (hunk 2 above)
Comment (antoniovs1029) [reply test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:6620]: Thanks for your reply. I understand that if I don't register the assembly, then when calling [ComponentCatalog.TryFindEntryPoint()](https://github.com/dotnet/machinelearning/blob/3d11ce42ab108d467ea6076dc14eaded57f46172/src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs#L483-L484) it won't be able to find `Trainers.LightGbmRanker` because it hasn't be registered. What I still don't understand is why we need to explicitly register LightGBM assembly, but not others... for instance, `FastTree` trainers are registered even if I don't register them explicitly in the test. So I guess my question could also be phrased as: Which trainers get always registered and where does this happen?

---
In reply to: [441779796](https://github.com/dotnet/machinelearning/pull/5227#discussion_r441779796) [](ancestors = 441779796)

File: src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs [hunk 3]
```diff
@@ -491,50 +491,87 @@ internal static IEnumerable<TrainTestData> CrossValidationSplit(IHostEnvironment
...
+                    {
+                        data = new ColumnCopyingEstimator(env, (newSamplingKeyColumn, samplingKeyColumn)).Fit(data).Transform(data);
+                    }
+                    else
                     {
-                        var origStratCol = samplingKeyColumn;
-                        samplingKeyColumn = data.Schema.GetTempColumnName(samplingKeyColumn);
-                        data = new NormalizingEstimator(env, new NormalizingEstimator.MinMaxColumnOptions(samplingKeyColumn, origStratCol, ensureZeroUntouched: true)).Fit(data).Transform(data);
+                        data = new NormalizingEstimator(env, new NormalizingEstimator.MinMaxColumnOptions(newSamplingKeyColumn, samplingKeyColumn, ensureZeroUntouched: false)).Fit(data).Transform(data);
                     }
```
Comment (antoniovs1029) [inline src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:570]: Notice the change of `ensureZeroUntouched` from `true` to `false`.

I did this for the reasons you've mentioned me offline, @yaeldekel , about another issue that would happen if the values of the samplingKeyColumn weren't inside 0-1. In fact, one of the tests I've added on this PR won't pass without `ensureZeroUntouched = false`.

File: test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs [hunk 4]
```diff
@@ -426,6 +427,36 @@ public void TestTrainTestSplitWithStratification()
...
+                "KeyStrat" };
+
+            foreach(var colname in colnames)
+            {
+                var cvSplits = mlContext.Data.CrossValidationSplit(inputWithKey, numberOfFolds: 2, samplingKeyColumnName: colname);
+                var idsTest1 = cvSplits[0].TestSet.GetColumn<int>(cvSplits[0].TestSet.Schema[nameof(Input.Id)]);
+                var idsTest2 = cvSplits[1].TestSet.GetColumn<int>(cvSplits[1].TestSet.Schema[nameof(Input.Id)]);
+                Assert.True(Enumerable.Intersect(idsTest1, idsTest2).Count() == 0);
+                Assert.True(idsTest1.Count() > 0, $"CV Split 0 for Column {colname} was empty");
+                Assert.True(idsTest2.Count() > 0, $"CV Split 1 for Column {colname} was empty");
```
Comment (antoniovs1029) [inline test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs:455]: As mentioned on my [previous comment](https://github.com/dotnet/machinelearning/pull/5227#discussion_r441994977), this test won't pass for the `FloatStrat` column, if I leave the `ensureZeroUntouched = true`. The reason for this is that rows with id `4` and `5` won't appear in the second fold, and in that fold the test set will be empty, because those rows have negative values (i.e. outside of 0-1) in the samplingKeyColumn.

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs [hunk 5]
```diff
@@ -5734,7 +5734,7 @@ public void TestCrossValidationMacroWithStratification()
                 getter(ref stdev);
                 foldGetter(ref fold);
                 Assert.True(ReadOnlyMemoryUtils.EqualsStr("Standard Deviation", fold));
-                Assert.Equal(0.0087, stdev, 5);
+                Assert.Equal(0.02582, stdev, 5);
```
Comment (antoniovs1029) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:5737]: This changed because of `ensureZeroUntouched = false` (see [https://github.com/dotnet/machinelearning/pull/5227#discussion_r441994977](https://github.com/dotnet/machinelearning/pull/5227#discussion_r441994977) )

File: src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs (hunk 3 above)
Comment (yaeldekel) [reply src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:570]: I agree that this change is needed. In this case there is no down side to it, since we know that the column being normalized is not a vector column (otherwise it would have gone into the other branch of the "if").
I think we should also consider normalizing even if `data.Schema[samplingKeyColumn].IsNormalized()` is true, because it could happen that it will be true but the values won't be in the range 0-1 (for example, if `samplingKeyColumn` was normalized using `MinMaxNormalizer` with `ensureZeroUntouched=true`).

---
In reply to: [441994977](https://github.com/dotnet/machinelearning/pull/5227#discussion_r441994977) [](ancestors = 441994977)

File: test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs [hunk 6]
```diff
@@ -402,12 +402,13 @@ public void TestTrainTestSplitWithStratification()
...
             });
 
+            // TEST TRAINTESTSPLIT
             var split = mlContext.Data.TrainTestSplit(input, 0.5, nameof(Input.TextStrat));
             var ids = split.TestSet.GetColumn<int>(split.TestSet.Schema[nameof(Input.Id)]);
             Assert.Contains(1, ids);
             Assert.Contains(5, ids);
             split = mlContext.Data.TrainTestSplit(input, 0.5, nameof(Input.FloatStrat));
-            ids = split.TrainSet.GetColumn<int>(split.TrainSet.Schema[nameof(Input.Id)]);
+            ids = split.TestSet.GetColumn<int>(split.TestSet.Schema[nameof(Input.Id)]);
```
Comment (yaeldekel) [inline test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs:411]: >TestSet [](start = 24, length = 7)

why?

Comment (antoniovs1029) [reply test/Microsoft.ML.Tests/Scenarios/Api/TestApi.cs:411]: Because of the change to `ensureZeroUntouched = false`

---
In reply to: [443437139](https://github.com/dotnet/machinelearning/pull/5227#discussion_r443437139) [](ancestors = 443437139)

File: src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs (hunk 3 above)
Comment (antoniovs1029) [reply src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:570]: Updated so that it normalizes even if IsNormalized is true.

---
In reply to: [443435362](https://github.com/dotnet/machinelearning/pull/5227#discussion_r443435362) [](ancestors = 443435362,441994977)

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs (hunk 2 above)
Comment (antoniovs1029) [reply test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:6620]: Ok, so simply whenever we run tests, most of the assemblies are registered here:
[https://github.com/dotnet/machinelearning/blob/bb13d629000c218136e741b643767cf45ae12fc4/test/Microsoft.ML.TestFramework/EnvironmentExtensions.cs#L20-L27](https://github.com/dotnet/machinelearning/blob/bb13d629000c218136e741b643767cf45ae12fc4/test/Microsoft.ML.TestFramework/EnvironmentExtensions.cs#L20-L27)

Which, for whatever reason, doesn't include LightGBM or these other assemblies, which need to be registered manually when working with Entrypoints:
[https://github.com/dotnet/machinelearning/blob/bb13d629000c218136e741b643767cf45ae12fc4/test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs#L328-L335](https://github.com/dotnet/machinelearning/blob/bb13d629000c218136e741b643767cf45ae12fc4/test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs#L328-L335)

---
In reply to: [441993836](https://github.com/dotnet/machinelearning/pull/5227#discussion_r441993836) [](ancestors = 441993836,441779796)

Comment (antoniovs1029) [reply test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:6620]: I was confused because I didn't understand/remember why typically users don't need to manually register assemblies, when loading models from disk, but I think it's simply because whenever a model is loaded the `EnsuredLoaderAssemblyIsRegistered` method is called, which actually tries to register the assembly that is needed

[https://github.com/dotnet/machinelearning/blob/bb13d629000c218136e741b643767cf45ae12fc4/src/Microsoft.ML.Core/Data/ModelLoading.cs#L284-L291](https://github.com/dotnet/machinelearning/blob/bb13d629000c218136e741b643767cf45ae12fc4/src/Microsoft.ML.Core/Data/ModelLoading.cs#L284-L291)

Anyway. Everything clear now.

---
In reply to: [444673165](https://github.com/dotnet/machinelearning/pull/5227#discussion_r444673165) [](ancestors = 444673165,441993836,441779796)

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs [hunk 7]
```diff
@@ -202,6 +202,63 @@ public void AutoFitRecommendationTest()
             Assert.NotEqual(0, metrices.MeanSquaredError);
         }
 
+        [Fact]
+        public void AutoFitWithPresplittedData()
+        {
+            // Models created in AutoML should work over the same data,
+            // no matter how that data is splitted before passing it to the experiment execution
+            // or to the model for prediction
```
Comment (antoniovs1029) [inline test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:210]: This test abstracts the issue in #5256 (which is also the issue in #4048 and https://github.com/dotnet/machinelearning-modelbuilder/issues/694 )

This test fails with a 
`System.ArgumentOutOfRangeException : Could not find input column 'SamplingKeyColumn'` without the changes on this PR.

The particular change that fixed this issue is dropping the (temporary version of) `SamplingKeyColumn`, on `DataOperationsCatalog.CrossValidationSplit`.

File: src/Microsoft.ML.EntryPoints/TrainTestSplit.cs (hunk 1 above)
Comment (antoniovs1029) [reply src/Microsoft.ML.EntryPoints/TrainTestSplit.cs]: Update: I've renamed `CreateGroupPreservationColumn` to `CreateSplitColumn` and made similar renames elsewhere to make the code easier to read. Now "splitColumn" is the name of the temporary column we create for splitting, regardless if it's based-off a "samplingKeyColumn" (ML.NET) or a "stratificationColumn" (NimbusML, Maml, legacy TLC naming conventions...)

Also now I do drop the new "splitColumn" when it's created while splitting through ML.NET's API, because not dropping it was causing other issues... see comment:
[https://github.com/dotnet/machinelearning/pull/5227#discussion_r446485476](https://github.com/dotnet/machinelearning/pull/5227#discussion_r446485476)

---
In reply to: [441992076](https://github.com/dotnet/machinelearning/pull/5227#discussion_r441992076) [](ancestors = 441992076,438969558,438552643)

File: src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs [hunk 8]
```diff
@@ -455,20 +458,26 @@ public IReadOnlyList<TrainTestData> CrossValidationSplit(IDataView data, int num
...
         }
 
-        internal static IEnumerable<TrainTestData> CrossValidationSplit(IHostEnvironment env, IDataView data, int numberOfFolds = 5, string samplingKeyColumnName = null)
+        /// <summary>
+        /// Splits the data based on the splitColumn, and drops that column as it is only
+        /// intended to be used for splitting the data, and shouldn't be part of the output schema.
+        /// </summary>
+        internal static IEnumerable<TrainTestData> CrossValidationSplit(IHostEnvironment env, IDataView data, string splitColumn, int numberOfFolds = 5)
         {
+            env.CheckValue(splitColumn, nameof(splitColumn));
```
Comment (yaeldekel) [inline src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:474]: >splitColumn [](start = 27, length = 11)

Should we check/assert that this column exists in the data?

File: src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs [hunk 9]
```diff
@@ -478,63 +487,104 @@ internal static IEnumerable<TrainTestData> CrossValidationSplit(IHostEnvironment
...
+                    Column = splitColumn,
                     Min = (double)fold / numberOfFolds,
                     Max = (double)(fold + 1) / numberOfFolds,
                     Complement = false,
                     IncludeMin = true,
                     IncludeMax = true
                 }, data);
 
-                yield return new TrainTestData(trainFilter, testFilter);
+                var trainDV = ColumnSelectingTransformer.CreateDrop(env, trainFilter, splitColumn);
```
Comment (yaeldekel) [inline src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:498]: >CreateDrop [](start = 57, length = 10)

Is this a new behavior? Or is it needed now because of the other changes?
If it is a new behavior, why is it needed?

Comment (antoniovs1029) [reply src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:498]: Dropping the SplitColumn is something new to fix the situation I mentioned here:
[https://github.com/dotnet/machinelearning/pull/5227#discussion_r446491522](https://github.com/dotnet/machinelearning/pull/5227#discussion_r446491522)

Not dropping it was causing an issue with AutoML. And also it didn't make sense that we didn't drop it, because if we didn't do it then the schema of a DataView was changed by splitting it, which I think should be considered unexpected behavior.

---
In reply to: [447415004](https://github.com/dotnet/machinelearning/pull/5227#discussion_r447415004) [](ancestors = 447415004)

File: src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs (hunk 8 above)
Comment (antoniovs1029) [reply src/Microsoft.ML.Data/DataLoadSave/DataOperationsCatalog.cs:474]: I did it because if the column doesn't exist it is going to throw an exception anyway inside the RangeFilter. Since it's necessary that the column exists for the RangeFilter to work, I thought it was sensible to check for this here and don't let `splitColumn` to be null.

---
In reply to: [447414598](https://github.com/dotnet/machinelearning/pull/5227#discussion_r447414598) [](ancestors = 447414598)
