### PR TITLE
Fix bug in ApplyAt in VBufferUtils

### LINKED ISSUE #1756: Bug in "ApplyAt" method in VBufferUtils
In the sparse case, it should create the VBufferEditor with keepOldOnResize set to true, so that we don't lose the existing values and indices.

### PR DESCRIPTION
**Pull request by yaeldekel**
When we create the editor, we lose the old values that were in the VBuffer in case it has to be resized.
Fixes #1756 .

### CODE REVIEW

File: test/Microsoft.ML.Core.Tests/UnitTests/TestVBuffer.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+using System;
+using System.Collections.Generic;
+using System.Text;
+using Microsoft.ML.Runtime.Data;
+using Microsoft.ML.Runtime.Internal.Utilities;
+using Xunit;
+
+namespace Microsoft.ML.Core.Tests.UnitTests
+{
+    public sealed class TestVBuffer
```
Comment (eerhardt) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestVBuffer.cs]: (Nit) I would name this class and file “TestVBufferUtils” instead, because that is what it is testing.

File: test/Microsoft.ML.Core.Tests/UnitTests/TestVBuffer.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+    {
+        [Fact]
+        public void TestApplyAt()
+        {
+            var buffer = new VBuffer<float>(10, 3, new[] { 0.5f, 1.2f, -3.8f }, new[] { 1, 5, 8 });
+            VBufferUtils.ApplyAt(ref buffer, 6, (int slot, ref float value) => { value = value + 1; });
+            Assert.Equal(4, buffer.GetValues().Length);
+            Assert.Equal(1, buffer.GetValues()[2]);
```
Comment (eerhardt) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestVBuffer.cs]: Can you verify all the values and indices are correct?
