### PR TITLE
Fix the ApproximatedKernelMappingEstimator XML doc

### LINKED ISSUE #3544: Fix the ApproximatedKernelMappingEstimator XML doc
The mathematical expression for the kernel functions is written in XML and the input and output types should be mentioned in the extension.

### PR DESCRIPTION
**Pull request by artidoro**
Fixes #3544.

### CODE REVIEW

File: src/Microsoft.ML.Transforms/FourierDistributionSampler.cs [hunk 1]
```diff
@@ -68,9 +68,15 @@ internal abstract class FourierRandomNumberGeneratorBase
...
 
     /// <summary>
-    /// The Gaussian kernel is defined as k(x,y)=exp(-gamma*|x-y|_2^2). The distribution that is the Fourier transform of
-    /// this kernel is the Normal distribution with variance 2*gamma.
+    /// The Gaussian kernel.
     /// </summary>
+    /// <remarks>
+    /// <format type="text/markdown"><![CDATA[
+    /// The Gaussian kernel is defined as $k(x,y) = \exp(-\gamma||x-y||^2)$. The distribution that is the Fourier transform of
+    /// this kernel is the Normal distribution with variance $2 \gamma$.
```
Comment (wschin) [inline src/Microsoft.ML.Transforms/FourierDistributionSampler.cs]: What does this mean?
```The distribution that is the Fourier transform of this kernel is the Normal distribution with variance $2 \gamma$.```

File: src/Microsoft.ML.Transforms/FourierDistributionSampler.cs [hunk 2]
```diff
@@ -183,9 +189,14 @@ public override float Next(Random rand)
     }
 
     /// <summary>
-    /// The Laplacian kernel is defined as k(x,y)=exp(-a*|x-y|_1). The distribution that is the Fourier transform of this
-    /// kernel is the Cauchy distribution with parameters (0, a).
+    /// The Laplacian kernel.
     /// </summary>
+    /// <remarks>
+    /// <format type="text/markdown"><![CDATA[
+    /// The Laplacian kernel is defined as $k(x,y)=\exp(-a||x-y||)$. The distribution that is the Fourier transform of
```
Comment (wschin) [inline src/Microsoft.ML.Transforms/FourierDistributionSampler.cs]: The second sentence is not quite clear to me.

File: src/Microsoft.ML.Transforms/FourierDistributionSampler.cs [hunk 3]
```diff
@@ -183,9 +189,14 @@ public override float Next(Random rand)
...
+    /// this kernel is the Cauchy distribution with parameters $(0, a)$.
```
Comment (wschin) [inline src/Microsoft.ML.Transforms/FourierDistributionSampler.cs]: Please add a link to Cauchy distribution.

File: src/Microsoft.ML.Transforms/FourierDistributionSampler.cs (hunk 1 above)
Comment (yaeldekel) [reply src/Microsoft.ML.Transforms/FourierDistributionSampler.cs]: This refers to the comment on the base class: that the Fourier transform of a continuous positive definite kernel is a non-negative measure. 

Perhaps we should mention this in the documentation of each implementation? Alternatively, we can remove the sentences mentioning the distributions, since the methods on these classes that sample from the distributions are internal anyway.

What do you guys think?

---
In reply to: [277855942](https://github.com/dotnet/machinelearning/pull/3545#discussion_r277855942) [](ancestors = 277855942)

Comment (shmoradims) [reply src/Microsoft.ML.Transforms/FourierDistributionSampler.cs]: it's not clear to me either. please reword.

---
In reply to: [277889125](https://github.com/dotnet/machinelearning/pull/3545#discussion_r277889125) [](ancestors = 277889125,277855942)

File: src/Microsoft.ML.Transforms/FourierDistributionSampler.cs (hunk 2 above)
Comment (shmoradims) [reply src/Microsoft.ML.Transforms/FourierDistributionSampler.cs]: +1. please reword the second sentence about fourier transform.

---
In reply to: [277856329](https://github.com/dotnet/machinelearning/pull/3545#discussion_r277856329) [](ancestors = 277856329)
