### PR TITLE
Correct documentation for MapKeyToVector.

### LINKED ISSUE #2772: KeyToVectorMappingEstimator catalog extension method summary is wrong
This documentation appears to be incorrect.

https://github.com/dotnet/machinelearning/blob/a0edc5c5724ed2895fd0c2fa5c2525d03de13455/src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs#L93-L97

This is for taking a key value (or key values) and mapping it into a floating point vector suitable for learning (variously, one-hot-encoding, or bag-of-words vector, depending on the type of input data and other applications). But to say it "converts it back to its original vector" is in no way accurate.

Perhaps someone got a little excited copying and pasting from the `KeyToValue` methods above.

### PR DESCRIPTION
**Pull request by codemzs**
fixes #2772

### CODE REVIEW

File: src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs [hunk 1]
```diff
@@ -90,7 +90,8 @@ public static KeyToValueMappingEstimator MapKeyToValue(this TransformsCatalog.Co
              => new KeyToValueMappingEstimator(CatalogUtils.GetEnvironment(catalog), ColumnOptions.ConvertToValueTuples(columns));
 
         /// <summary>
-        /// Convert the key types back to their original vectors.
+        /// Maps key types (or key values) into a floating point vector suitable for learning (variously, one-hot-encoding,
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs]: >variously [](start = 95, length = 9)

While I did use this language in the issue, it is not suitable language for documentation. The way in which I write is not generally suitable language for documentation.

Comment (codemzs) [reply src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs]: Oh come'on you are the [Shakespeare ](https://en.wikipedia.org/wiki/William_Shakespeare) of our team ... I'll change the language to be more ideal.

**Comment by codemzs** [comment]
@TomFinley Can you please take another look?
