### PR TITLE
Fixing renmants of argument keyword in public API

### LINKED ISSUE #2557: Renmants of Arguments keyword in public API
There are some classes in our public API which still have word 'Arguments' in them 

https://github.com/dotnet/machinelearning/blob/17c037f757113aba8acdc88abf2803b86fe95b93/src/Microsoft.ML.StandardLearners/Standard/Online/OnlineLinear.cs#L22

We should rename them to *Options instead. Related to #1798 #1758

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #2557

- Scrubbed the public API surface area using the **ApiReviewer** tool

### CODE REVIEW

File: src/Microsoft.ML.FastTree/GamClassification.cs [hunk 1]
```diff
@@ -112,29 +112,29 @@ private static bool[] ConvertTargetsToBool(double[] targets)
             return new ValueMapperCalibratedModelParameters<BinaryClassificationGamModelParameters, PlattCalibrator>(Host, predictor, calibrator);
         }
 
-        private protected override ObjectiveFunctionBase CreateObjectiveFunction()
+        protected override ObjectiveFunctionBase CreateObjectiveFunction()
         {
             return new FastTreeBinaryClassificationTrainer.ObjectiveImpl(
                 TrainSet,
                 ConvertTargetsToBool(TrainSet.Targets),
-                Args.LearningRates,
```
Comment (artidoro) [inline src/Microsoft.ML.FastTree/GamClassification.cs]: >Args [](start = 16, length = 4)

Why nor `Options`?

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 2]
```diff
@@ -104,7 +104,7 @@ public sealed class Options : OptionsBase
         internal MulticlassLogisticRegression(IHostEnvironment env, Options options)
             : base(env, options, TrainerUtils.MakeU4ScalarColumn(options.LabelColumn))
         {
-            ShowTrainingStats = Args.ShowTrainingStats;
+            ShowTrainingStats = LbfgsTrainerOptions.ShowTrainingStats;
```
Comment (artidoro) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >LbfgsTrainerOptions [](start = 32, length = 19)

Same here why not naming this `Options`?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs [hunk 3]
```diff
@@ -73,7 +73,7 @@ public Options()
         {
             Host.CheckNonEmpty(featureColumn, nameof(featureColumn));
             Host.CheckNonEmpty(labelColumn, nameof(labelColumn));
-            _loss = loss ?? Args.LossFunction.CreateComponent(env);
+            _loss = loss ?? SdcaTrainerOptions.LossFunction.CreateComponent(env);
```
Comment (artidoro) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs]: >SdcaTrainerOptions [](start = 28, length = 18)

Here as well? why not `Options`?

File: src/Microsoft.ML.Onnx/SaveOnnxCommand.cs [hunk 4]
```diff
@@ -200,13 +200,13 @@ private void Run(IChannel ch)
 
             if (_model == null)
             {
-                if (string.IsNullOrEmpty(Args.InputModelFile))
+                if (string.IsNullOrEmpty(ImplOptions.InputModelFile))
```
Comment (artidoro) [inline src/Microsoft.ML.Onnx/SaveOnnxCommand.cs]: >ImplOptions [](start = 41, length = 11)

If possible could you not use abbreviations? And here too, just curious why not `Options`?

File: src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BaseSubsetSelector.cs [hunk 5]
```diff
@@ -20,23 +20,23 @@ public abstract class ArgumentsBase
         }
 
         protected readonly IHost Host;
-        protected readonly TArgs Args;
+        protected readonly TOptions BaseSubsetSelectorOptions;
```
Comment (artidoro) [inline src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BaseSubsetSelector.cs]: >BaseSubsetSelectorOptions [](start = 36, length = 25)

Why not `Options`?

File: src/Microsoft.ML.FastTree/GamClassification.cs (hunk 1 above)
Comment (abgoswam) [reply src/Microsoft.ML.FastTree/GamClassification.cs]: I wanted to give a name to this property so that users would easily be able to distinguish to from the class `Options` .  


---
In reply to: [258278906](https://github.com/dotnet/machinelearning/pull/2636#discussion_r258278906) [](ancestors = 258278906)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 2 above)
Comment (abgoswam) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Mostly for clarity.  Throughout the public API surface we have the class `Options`  to represent a particular concept.  

I wanted to name this property something different , so users can draw the distinction with the `Options` class

---
In reply to: [258279561](https://github.com/dotnet/machinelearning/pull/2636#discussion_r258279561) [](ancestors = 258279561)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs (hunk 3 above)
Comment (abgoswam) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs]: Mostly for clarity, to help users distinguish between this property v/s class `Options`

---
In reply to: [258279715](https://github.com/dotnet/machinelearning/pull/2636#discussion_r258279715) [](ancestors = 258279715)

File: src/Microsoft.ML.Onnx/SaveOnnxCommand.cs (hunk 4 above)
Comment (abgoswam) [reply src/Microsoft.ML.Onnx/SaveOnnxCommand.cs]: (plz see above)

---
In reply to: [258279957](https://github.com/dotnet/machinelearning/pull/2636#discussion_r258279957) [](ancestors = 258279957)

File: src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BaseSubsetSelector.cs (hunk 5 above)
Comment (abgoswam) [reply src/Microsoft.ML.Ensemble/Selector/SubsetSelector/BaseSubsetSelector.cs]: (plz see above)

---
In reply to: [258280102](https://github.com/dotnet/machinelearning/pull/2636#discussion_r258280102) [](ancestors = 258280102)
