### PR TITLE
 Enable a QuantileRegression Test & Fix Duplicated Baseline Files

### LINKED ISSUE #410: Suggestion for test framework improvements.
No reason to have same baselines for Debug and Release if they are same.

Currently we have /test/BaselineOutput folder which contains folders Common, SingleDebug and SingleRelease and they filled with pretty much same files. We need to modify our test framework so it will look first in Common folder and if file is not found then it should look in respectful folders.
Also word Single is legacy artifact and can be omitted. 

This would reduce size of repo, and simplify peoples life. Also it give more room to have platform specific tests since many of our tests disabled because we verify everything with windows output, which sometimes differ because of native code implementation.

### PR DESCRIPTION
**Pull request by eerhardt**
Enable CommandTrainScoreEvaluateQuantileRegression, add the dataset and the necessary baselines.

The only baseline changes were of the form that were caused by dotnet/corefx#31847.

Allow BaseTestBaseline to check Common first.

A lot of baseline tests have duplicated baselines between debug and release. Allow BaseTestBaseline to check the Common baseline directory for a baseline file first.

Also, I cleaned a bunch of dead code from BaseTestBaseline.

Fix #410

### CODE REVIEW

File: test/Microsoft.ML.TestFramework/BaseTestBaseline.cs [hunk 1]
```diff
@@ -838,7 +748,7 @@ protected static StreamReader OpenReader(string path)
         {
             Contracts.CheckNonWhiteSpace(path, nameof(path));
 #if CORECLR
-            return new StreamReader(File.Open(path, FileMode.Open, FileAccess.Read));
+            return new StreamReader(File.Open(path, FileMode.Open, FileAccess.Read, FileShare.Read));
```
Comment (eerhardt) [inline test/Microsoft.ML.TestFramework/BaseTestBaseline.cs]: FYI - this is a nicety when debugging tests and trying to use Beyond Compare (or similar) to diff the output and baseline files. As currently implemented, it is impossible to open these files in 2 processes at the same time.

File: test/data/housing.txt [hunk 2]
```diff
@@ -0,0 +1,506 @@
+24.00	0.00632	18.00	2.310	0	0.5380	6.5750	65.20	4.0900	1	296.0	15.30	396.90	4.98
+21.60	0.02731	0.00	7.070	0	0.4690	6.4210	78.90	4.9671	2	242.0	17.80	396.90	9.14
```
Comment (sfilipi) [inline test/data/housing.txt]: Last time i asked about this dataset, I believe we couldn't use it. 
I switched my test to the wine quality. 
Might have to use the regression dataset that is in the repo already. 

 @shauheen @artidoro to comment further

File: test/Microsoft.ML.TestFramework/BaseTestBaseline.cs [hunk 3]
```diff
@@ -125,19 +121,6 @@ protected override void Cleanup()
...
-
-        // Return the location of the local scope folder under Samples. Used primarily 
-        // by Scope scripts and for Scope tests
-        protected string ScopeSamplesDir { get { return Path.Combine(RootDir, ScopeRootRelPath); } }
-
-        // Return the local of the directory where external binaries for test purposes are located
-        protected string ExternalTestBinariesDir { get { return Path.Combine(RootDir, TestExtDir); } }
-
-        protected string TestDirectory { get { return Path.Combine(RootDir, TestDir); } }
-
```
Comment (sfilipi) [inline test/Microsoft.ML.TestFramework/BaseTestBaseline.cs]: cc @yaeld to check whether this conflicts with her work.

Comment (eerhardt) [reply test/Microsoft.ML.TestFramework/BaseTestBaseline.cs]: Thanks for thinking of that work, @sfilipi.

If there are things that are only used in the internal repo, we should move them to only be in the internal repo. It isn't sustainable to have a bunch of methods in dotnet/machinelearning that are not used.

@yaeldekel - if any of these are necessary for your work, can you add them to a `partial` class in the internal repo?

File: test/data/housing.txt (hunk 2 above)
Comment (eerhardt) [reply test/data/housing.txt]: From all I could find online, this dataset appears to be in the public domain.

This site claims the dataset is in the public domain:
http://b-course.hiit.fi/obc/housingexpl.html
“ B-Course provides a public domain data set called Boston Housing Data so that one can try out B-Course without own data. Below you can find some details of our example data set.”

The dataset is also distributed in an R package here:
https://www.rdocumentation.org/packages/mlbench/versions/2.1-1

It's used in books as well: https://github.com/rasbt/python-machine-learning-book-2nd-edition/blob/master/code/ch10/housing.data.txt

I've added the attribution to the README.

By the way, this is a different dataset from the "King County Housing" (kc_housing) dataset.

Comment (justinormont) [reply test/data/housing.txt]: CELA has approved the re-distribution of the Boston Housing dataset.

File: test/data/housing.txt [hunk 4]
```diff
@@ -0,0 +1,506 @@
+24.00	0.00632	18.00	2.310	0	0.5380	6.5750	65.20	4.0900	1	296.0	15.30	396.90	4.98
```
Comment (justinormont) [inline test/data/housing.txt]: Would it be reasonable to add a header to the file to help users understand it:
`CrimesPerCapita	PercentResidental	PercentNonRetail	CharlesRiver	NitricOxides	RoomsPerDwelling	PercentPre40s	EmploymentDistance	HighwayDistance	TaxRate	TeacherRatio	BlackIndex	PercentLowIncome	MedianHomeValue`

The headed is also used when producing the feature importance as it will then print the column headers (textual form) instead of just a semi-opaque 'F13'.

File: test/data/README.md [hunk 5]
```diff
@@ -65,6 +65,12 @@ The dataset is under a CC-by 4.0 license.
 }
 ```
 
+### Boston Housing Data
```
Comment (justinormont) [inline test/data/README.md]: Can you add a more info link? I also added a link to our copy of the dataset so folks know what we are referencing. 
```
### Boston Housing Data
 Redistributing the dataset "[housing.txt](housing.txt)" with attribution:
 > Harrison, D. and Rubinfeld, D.L. 'Hedonic prices and the demand for clean air', J. Environ. Economics & Management, vol.5, 81-102, 1978.

More information: http://b-course.hiit.fi/obc/housingexpl.html
```

Comment (eerhardt) [reply test/data/README.md]: Done.

File: test/data/housing.txt (hunk 4 above)
Comment (eerhardt) [reply test/data/housing.txt]: Done.

**Comment by justinormont** [comment]
Closing/re-opening to restart CI tests
