### PR TITLE
Scrubbing SDCA learners

### LINKED ISSUE #2616: Scrubbing SDCA learners
Sub task of #2613
`SgdNonCalibratedBinaryTrainer`
`SgdBinaryTrainer`
`SdcaBinaryTrainer`
`SdcaNonCalibratedBinaryTrainer`
`SdcaRegressionTrainer`
`SdcaMultiClassTrainer`
and their base classes

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #2616 .  Related #2613

### CODE REVIEW

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs [hunk 1]
```diff
@@ -159,38 +159,63 @@ public abstract class SdcaTrainerBase<TOptions, TTransformer, TModel> : Stochast
...
+            /// Number of iterations.
+            /// </summary>
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Maximum number of iterations; set to 1 to simulate online learning. Defaults to automatic.", NullName = "<Auto>", ShortName = "iter, MaxIterations")]
             [TGUI(Label = "Max number of iterations", SuggestedSweeps = "<Auto>,10,20,100")]
             [TlcModule.SweepableDiscreteParam("MaxIterations", new object[] { "<Auto>", 10, 20, 100 })]
-            public int? MaxIterations;
+            public int? NumberOfIterations;
 
+            /// <summary>
+            /// Whether to shuffle data at every epoch (default true).
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: >epoch [](start = 49, length = 5)

iteration? or it's two different things?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs [hunk 2]
```diff
@@ -159,38 +159,63 @@ public abstract class SdcaTrainerBase<TOptions, TTransformer, TModel> : Stochast
...
             [Argument(ArgumentType.AtMostOnce, HelpText = "Shuffle data every epoch?", ShortName = "shuf")]
             [TlcModule.SweepableDiscreteParam("Shuffle", null, isBool: true)]
             public bool Shuffle = true;
 
+            /// <summary>
+            /// Convergence check frequency (in terms of <see cref="NumberOfIterations"/>). Set as negative or zero for not checking at all.
+            /// If left blank, it defaults to check after every <see cref="NumberOfThreads"/> iterations.
+            /// </summary>
             [Argument(ArgumentType.AtMostOnce, HelpText = "Convergence check frequency (in terms of number of iterations). Set as negative or zero for not checking at all. If left blank, it defaults to check after every 'numThreads' iterations.", NullName = "<Auto>", ShortName = "checkFreq")]
             public int? CheckFrequency;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: >CheckFrequency [](start = 24, length = 14)

Maybe ConvergenceCheckFrequency?
Also can you copy this documentation across other CheckFrequency options?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs [hunk 3]
```diff
@@ -1756,17 +1787,17 @@ public class OptionsBase : TrainerInputBaseWithWeight
...
+            public int NumberOfIterations = Defaults.NumberOfIterations;
 
             /// <summary>
             /// The initial <a href="tmpurl_lr">learning rate</a> used by SGD.
             /// </summary>
-            [Argument(ArgumentType.AtMostOnce, HelpText = "Initial learning rate (only used by SGD)", ShortName = "ilr,lr")]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Initial learning rate (only used by SGD)", ShortName = "ilr,lr, InitLearningRate")]
             [TGUI(Label = "Initial Learning Rate (for SGD)")]
-            public double InitLearningRate = Defaults.InitLearningRate;
+            public double InitialLearningRate = Defaults.InitialLearningRate;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: >InitialLearningRate [](start = 26, length = 19)

So it works this way: in the beginning of each iteration we set learning rate to this one, and then with going through examples we decrease it. But in each iteration it starts with this one. 
So technically it's initial learning rate, but it remain same for each iteration....
Can you look other example of InitialLearningRate, and are they have same pattern or not?
I would probably just call it LearningRate.

File: src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs [hunk 4]
```diff
@@ -26,7 +26,7 @@ namespace Microsoft.ML.Trainers
 {
     // SDCA linear multiclass trainer.
     /// <include file='doc.xml' path='doc/members/member[@name="SDCA"]/*' />
-    public class SdcaMultiClassTrainer : SdcaTrainerBase<SdcaMultiClassTrainer.Options, MulticlassPredictionTransformer<MulticlassLogisticRegressionModelParameters>, MulticlassLogisticRegressionModelParameters>
+    public sealed class SdcaMultiClassTrainer : SdcaTrainerBase<SdcaMultiClassTrainer.Options, MulticlassPredictionTransformer<MulticlassLogisticRegressionModelParameters>, MulticlassLogisticRegressionModelParameters>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaMultiClass.cs]: >sealed [](start = 11, length = 6)

How I can put thumbs up emoji?
Anyway thanks for catching this!

File: src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs [hunk 5]
```diff
@@ -36,9 +36,9 @@ public static class StandardLearnersCatalog
             string labelColumnName = DefaultColumnNames.Label,
             string featureColumnName = DefaultColumnNames.Features,
             string exampleWeightColumnName = null,
-            int maxIterations = SgdBinaryTrainer.Options.Defaults.MaxIterations,
-            double initLearningRate = SgdBinaryTrainer.Options.Defaults.InitLearningRate,
-            float l2Weight = SgdBinaryTrainer.Options.Defaults.L2Weight)
+            int maxIterations = SgdBinaryTrainer.Options.Defaults.NumberOfIterations,
```
Comment (artidoro) [inline src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs]: >maxIterations [](start = 16, length = 13)

Should you reflect the change in the extensions as well?

**Comment by Ivanidzo4ka** [comment]
@abgoswam Any chance you plan to update and merge this one?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs (hunk 1 above)
Comment (abgoswam) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: retaining the latest documentation updates being done in parallel

---
In reply to: [261895645](https://github.com/dotnet/machinelearning/pull/2825#discussion_r261895645) [](ancestors = 261895645)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs (hunk 3 above)
Comment (abgoswam) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs]: I do not see other examples of InitialLearningRate in the other learners.  

To me the names makes sense, esp. since it does indicate that  this learning rate is adaptive in nature. We can add more documentation as to why this helps .

---
In reply to: [261897003](https://github.com/dotnet/machinelearning/pull/2825#discussion_r261897003) [](ancestors = 261897003)
