### PR TITLE
Fix SDCA sample runtime exception.

### LINKED ISSUE #3258: Fix runtime exception in SDCA sample
Throws exception because it cannot find features and probability column.

### PR DESCRIPTION
**Pull request by codemzs**
fixes #3258

### CODE REVIEW

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs [hunk 1]
```diff
@@ -69,7 +69,7 @@ public static void Example()
                                       }));
 
             // Run Cross-Validation on this second pipeline.
-            var cvResults_advancedPipeline = mlContext.BinaryClassification.CrossValidate(data, pipeline, labelColumnName: "Sentiment", numberOfFolds: 3);
```
Comment (sfilipi) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs]: Why change this? I believe SDCA has both

Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs]: Done. I was thinking the same.
