### PR TITLE
Fix feature selection catalog XML documentaion

### LINKED ISSUE #3547: Feature selection catalog xml doc should be fixed
Feature selection catalog does not mention the input output types in the extensions.
There is a missing Seealso reference in one of the estimators.

### PR DESCRIPTION
**Pull request by artidoro**
Fixes #3547.

### CODE REVIEW

File: src/Microsoft.ML.Transforms/CountFeatureSelection.cs [hunk 1]
```diff
@@ -27,9 +27,9 @@ namespace Microsoft.ML.Transforms
     /// ###  Estimator Characteristics
     /// |  |  |
     /// | -- | -- |
-    /// | Does this estimator need to look at the data to train its parameters? | Yes. |
-    /// | Input column data type | Vector or primitive of numeric, text or [key](xref:Microsoft.ML.Data.KeyDataViewType) data types.|
-    /// | Output column data type | Same as the input column.|
+    /// | Does this estimator need to look at the data to train its parameters? | Yes |
+    /// | Input column data type | Vector or scalar of numeric, text or [key](xref:Microsoft.ML.Data.KeyDataViewType) data types|
```
Comment (shmoradims) [inline src/Microsoft.ML.Transforms/CountFeatureSelection.cs]: >text [](start = 64, length = 4)

xref text to TextDataViewType
