### PR TITLE
move regex to right place to reduce test time

### LINKED ISSUE #1348: Build failed because of building time larger than 60 mins
[My build](https://dnceng.visualstudio.com/public/_build/results?buildId=34123&view=logs) got canceled because it needs more than 60 mins for debug mode. A screen shot is attached below.

image

### LINKED ISSUE #1382: CI build failing due to timeout errors
Some of the tests are taking really long time to run which cause the build to run for more than 60 mins and are then declared as failure. Some of tests that Run for a lot of time are

Microsoft.ML.Runtime.RunTests.TestPredictors takes 33mins and it only executes 59 tests
TestHyperparameterFreezing -24min
FastTreeBinaryClassificationCategoricalSplitTest -18min
SavePipeWithHeader -4min

Maybe we should fix those tests. We can try running the tests in parallel using helix rather than in a chain.

cc @eerhardt @safern

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes #1382 fixes #1348

### CODE REVIEW

File: test/Microsoft.ML.TestFramework/BaseTestBaseline.cs [hunk 1]
```diff
@@ -506,16 +509,14 @@ protected bool CheckEqualityFromPathsCore(string relPath, string basePath, strin
 
         private void GetNumbersFromFile(ref string firstString, ref string secondString, int digitsOfPrecision)
         {
-            // The Regex matches both positive and negative decimal point numbers present in a string.
-            // The numbers could be a part of a word. They can also be in Exponential form eg. 3E-9
-            Regex _matchNumer = new Regex(@"-?\b[0-9]+\.?[0-9]*(E-[0-9]*)?\b", RegexOptions.IgnoreCase | RegexOptions.Compiled);
-            MatchCollection firstCollection = _matchNumer.Matches(firstString);
-            MatchCollection secondCollection = _matchNumer.Matches(secondString);
+
```
Comment (artidoro) [inline test/Microsoft.ML.TestFramework/BaseTestBaseline.cs]: Could you remove the extra line?
