### PR TITLE
Replaces ChooseColumnsTransform and DropColumnsTransform with SelectColumnsTransform

### LINKED ISSUE #1342: Change unit tests to use SelectColumnsTransform instead of ChooseColumnsTransform
After serialization, ChooseColumnsTransform is deserialized as a SelectColumnsTransform, causing unit tests to fail.

We should also consider changing transforms that use DropColumnsTransform (such as WordHashBag, evaluators etc.) to start using SelectColumnsTransform instead.

### PR DESCRIPTION
**Pull request by singlis**
Replaces ChooseColumnsTransform and DropColumnsTransform with SelectColumnsTransform. 

These changes include:
* Updates to SelectColumnsTransform to respect ordering when keeping
columns. For example, if the input is ABC and CB is selected, the output
will be CB.
* Updates to code that used Choose or Drop columns, replacing with
SelectColumns.
* Updates to baseline output for tests to pass
* Re-enabled the SavePipeline tests

This fixes #1342
These changes are also related to #754

### CODE REVIEW

File: src/Microsoft.ML.Data/Commands/SaveDataCommand.cs [hunk 1]
```diff
@@ -129,11 +130,10 @@ private void RunCore(IChannel ch)
...
             if (!string.IsNullOrWhiteSpace(Args.Columns))
             {
-                var args = new ChooseColumnsTransform.Arguments();
-                args.Column = Args.Columns
-                    .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(s => new ChooseColumnsTransform.Column() { Name = s }).ToArray();
-                if (Utils.Size(args.Column) > 0)
-                    data = new ChooseColumnsTransform(Host, args, data);
+                var keepColumns = Args.Columns
+                    .Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToArray();
+                if (keepColumns.Length > 0)
```
Comment (yaeldekel) [inline src/Microsoft.ML.Data/Commands/SaveDataCommand.cs]: >Length [](start = 32, length = 6)

Does Split always return non-null? Otherwise we should use Utils.Size(keepColumns) instead of keepColumns.Length.

**Comment by yaeldekel** [comment]
>             public bool KeepHidden = true;

The default behavior of ChooseTransform was the opposite of this. We should consider whether we want to change it here as well.
Also, in all the components that use Choose/Drop columns (such as NAHandle, TermLookup, etc.) we should verify that the behavior stays the same, i.e. that no extra columns are dropped/kept.


---
Refers to: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs:182 in 99e8aa5. [](commit_id = 99e8aa5d7c96be90bc2a829ebb54f4f3ba691a8b, deletion_comment = False)

**Comment by yaeldekel** [comment]
>             //env.CheckDecode(cbFloat == sizeof(Float));

Should this be uncommented?

---
Refers to: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs:235 in 99e8aa5. [](commit_id = 99e8aa5d7c96be90bc2a829ebb54f4f3ba691a8b, deletion_comment = False)

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs [hunk 2]
```diff
@@ -490,21 +511,59 @@ public int GetInputIndex(int outputIndex)
...
 
-                    var columnName = inputSchema[colIdx].Name;
-                    var selected = selectedColumns.Contains(columnName);
-                    selected = (keepColumns) ? selected : !selected;
-                    if (selected)
+                    // Since the ordering matters, iterate through the selected columns
+                    // finding the associated index that should be used.
+                    foreach(var columnName in selectedColumns)
+                    {
+                        if (columnDict.TryGetValue(columnName, out List<int> columnList))
```
Comment (yaeldekel) [inline src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: >TryGetValue [](start = 39, length = 11)

I think this should fail if the schema doesn't contain a column by that name.

Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: Are you referring to in general or specifically in this case? In general there is an ignoreMissing parameter that when it is true will ignore any columns specified not being in the input. This is checked earlier before the Mapper is created.

---
In reply to: [228247404](https://github.com/dotnet/machinelearning/pull/1371#discussion_r228247404) [](ancestors = 228247404)

**Comment by singlis** [comment]
>             public bool KeepHidden = true;

I feel the same -- Pete preferred this to be KeepHidden as the default. So there are places in code where I have to explicitly specify the drop. Lets bring Pete into the conversation.

---
In reply to: [433115221](https://github.com/dotnet/machinelearning/pull/1371#issuecomment-433115221) [](ancestors = 433115221)

---
Refers to: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs:182 in 99e8aa5. [](commit_id = 99e8aa5d7c96be90bc2a829ebb54f4f3ba691a8b, deletion_comment = False)

**Comment by singlis** [comment]
>             //env.CheckDecode(cbFloat == sizeof(Float));

Yes

---
In reply to: [433118204](https://github.com/dotnet/machinelearning/pull/1371#issuecomment-433118204) [](ancestors = 433118204)

---
Refers to: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs:235 in 99e8aa5. [](commit_id = 99e8aa5d7c96be90bc2a829ebb54f4f3ba691a8b, deletion_comment = False)

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs [hunk 3]
```diff
@@ -384,6 +384,27 @@ public static IDataView Create(IHostEnvironment env, ModelLoadContext ctx, IData
             return transform.Transform(input);
         }
 
+        public static IDataTransform CreateKeep(IHostEnvironment env, IDataView input, params string[] keepColumns)
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: >IDataTransform CreateKeep [](start = 22, length = 25)

Do you have any place where it requires to be IDataTransform and not IDataView?
If not, I would suggest you to not use arguments class and just create SelectColumnsTransform and pass required parameters into constructor and then call .Transform on input.

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs (hunk 2 above)
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: @Zruty0 - Yael makes a great point! What are your thoughts on defaulting ignoreMissing to false?

**Comment by singlis** [comment]
FYI - the build failed on the mac debug build but passed on all other platforms which leads me to believe this is one of the intermittent test failures that we see on the mac. I am following up with @TomFinley to confirm since he is investigating this issue.

**Comment by shauheen** [comment]
@singlis can you update the branch so that we get a fresh build?

**Comment by singlis** [comment]
yes - will do.

File: src/Microsoft.ML.Transforms/TermLookupTransform.cs [hunk 4]
```diff
@@ -507,12 +509,15 @@ private static byte[] GetBytesFromDataView(IHost host, IDataView lookup, string
...
-                new ChooseColumnsTransform.Column {Name = "Value", Source = valueColumn},
+            var args = new CopyColumnsTransform.Arguments();
+            var copyColumns = new List<CopyColumnsTransform.Column>() {
+                new CopyColumnsTransform.Column {Name = "Term", Source = termColumn},
+                new CopyColumnsTransform.Column {Name = "Value", Source = valueColumn},
             };
-            var view = new ChooseColumnsTransform(host, args, lookup);
+            args.Column = copyColumns.ToArray();
+
+            var view = CopyColumnsTransform.Create(host, args, lookup);
```
Comment (Zruty0) [inline src/Microsoft.ML.Transforms/TermLookupTransform.cs]: >CopyColumnsTransform [](start = 23, length = 20)

can we use a constructor instead of args-based `Create` ?

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs (hunk 2 above)
Comment (Zruty0) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: I agree

---
In reply to: [228266038](https://github.com/dotnet/machinelearning/pull/1371#discussion_r228266038) [](ancestors = 228266038)

**Comment by Zruty0** [comment]
>             public bool KeepHidden = true;

I don't remember a specific reason. Probably, let's do the least destructive conversion, so preserve whatever `ChooseColumns` was doing by default

---
In reply to: [433130838](https://github.com/dotnet/machinelearning/pull/1371#issuecomment-433130838) [](ancestors = 433130838,433115221)

---
Refers to: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs:182 in 99e8aa5. [](commit_id = 99e8aa5d7c96be90bc2a829ebb54f4f3ba691a8b, deletion_comment = False)

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs (hunk 3 above)
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: Sorry Ivan, I misunderstood - so the feedback is to not use Arguments inside the function and return an IDataView instead of IDataTransform. Got it, I will make those changes.

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs (hunk 2 above)
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: Ok I will default ignoreMissing to false.

Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: ignoreMissing now defaults to false.

---
In reply to: [228264779](https://github.com/dotnet/machinelearning/pull/1371#discussion_r228264779) [](ancestors = 228264779,228264118,228257636,228247404)

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs (hunk 3 above)
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: I was able to remove the usage of Arguments however I was not able to move to an IDataView. There are other transforms that will use this transform and expect to return an IDataTransform.

---
In reply to: [229034034](https://github.com/dotnet/machinelearning/pull/1371#discussion_r229034034) [](ancestors = 229034034)

File: src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs [hunk 5]
```diff
@@ -179,14 +179,14 @@ public sealed class Arguments : TransformInputBase
             public string[] DropColumns;
 
             [Argument(ArgumentType.AtMostOnce, HelpText = "Specifies whether to keep or remove hidden columns.", ShortName = "hidden", SortOrder = 3)]
-            public bool KeepHidden = true;
+            public bool KeepHidden = false;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Transforms/SelectColumnsTransform.cs]: >false [](start = 37, length = 5)

nit: We usually have Defaults class with const properties, which ease a bit spreading of parameters across code.

File: test/Microsoft.ML.Tests/Transformers/SelectColumnsTests.cs [hunk 6]
```diff
@@ -0,0 +1,371 @@
...
+using Microsoft.ML.Runtime.Tools;
+using Microsoft.ML.TestFramework;
+using Microsoft.ML.Transforms;
+using System;
+using System.Collections.Generic;
+using System.IO;
+using Xunit;
+using Xunit.Abstractions;
+
+namespace Microsoft.ML.Tests
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/Transformers/SelectColumnsTests.cs]: >Microsoft.ML.Tests [](start = 10, length = 18)

nit: it's Microsoft.ML.Tests.Transformers in other tests.
