### PR TITLE
Fixed Averaged Perceptron default value

### LINKED ISSUE #5568: AveragedPerceptron default iterations
When changing AveragedPerceptron's default number of iterations from 1 to 10 in https://github.com/dotnet/machinelearning/pull/5258, we missed one.

The main interface continues to default to 1 iteration:
image

Previous issues:
* https://github.com/dotnet/machinelearning/issues/4749
* https://github.com/dotnet/machinelearning/pull/5258

### Code location
Default is set here:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs#L172

Which originates from:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedLinear.cs#L108-L113

Which in-turn inherits its value from:
https://github.com/dotnet/machinelearning/blob/5dbfd8acac0bf798957eea122f1413209cdf07dc/src/Microsoft.ML.StandardTrainers/Standard/Online/OnlineLinear.cs#L62-L65

### Possible fix
We may want to make a new class within AveragedPerceptron to hold its overrides:
```c#
        internal class AveragedPerceptronDefault : AveragedDefault
        { 
            public const float NumberOfIterations = 10; 
        } 
```

/cc @michaelgsharp

### PR DESCRIPTION
**Pull request by michaelgsharp**
Fixes #5568. Several months ago the default value of iterations for averaged perceptron was changed from 1 to 10. It was missed in 1 location, so this pr addresses that and fixes it there as well.

### CODE REVIEW

File: src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs [hunk 1]
```diff
@@ -76,6 +77,11 @@ public sealed class AveragedPerceptronTrainer : AveragedLinearTrainer<BinaryPred
 
         private readonly Options _args;
 
+        internal class AveragedPerceptronDefault : AveragedDefault
+        {
+            public new const int NumberOfIterations = 10;
```
Comment (eerhardt) [inline src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:82]: In the reported issue:

image

The above API is setting

```C#
int numberOfIterations = AveragedLinearOptions.AveragedDefault.NumberOfIterations
```

adding a `new const` field here isn't going to change the API. It needs to change to reference `AveragedPerceptronDefault.NumberOfIterations`.

Comment (michaelgsharp) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:82]: I didn't realize there was another place with the old reference as well, so thanks for the catch!  I have update the extension method to point to the new class.

File: src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs [hunk 2]
```diff
@@ -76,6 +77,11 @@ public sealed class AveragedPerceptronTrainer : AveragedLinearTrainer<BinaryPred
 
         private readonly Options _args;
 
+        internal class AveragedPerceptronDefault : AveragedDefault
```
Comment (tarekgh) [inline src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:80]: >AveragedPerceptronDefault [](start = 23, length = 25)

I am wondering is it worth it to introduce a new class just to contain a const value?

Comment (michaelgsharp) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:80]: The pattern so far in ML.NET has been to have classes to contain the default values, so I have just continued that pattern. While it does seem weird to have a class with just 1 value, I think keeping the pattern so that the code is consistent is better then breaking with consistency. Thoughts?

Comment (tarekgh) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:80]: I still not familiar with the whole space so I cannot judge that. but in general I am seeing ending up with many classes would make it difficult to use I guess. please don't block on my comment. I am just thinking loudly with you.

Comment (tarekgh) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:80]: can we put this constant in AveragedDefault and rename it to something like PerceptronNumberOfIterations or something similar?

Comment (michaelgsharp) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:80]: I am not sure how well that will look. If you look [here](https://github.com/dotnet/machinelearning/blob/c2ddff17abbaf4d873ae3a805f2688d4a11f7988/src/Microsoft.ML.StandardTrainers/Standard/Online/OnlineLinear.cs#L29), we have a bunch of attributes that affect how it shows up with the command line interface. Since we are using a class and overriding just that value, those attributes (I think) will come as well. I am not sure how it will behave if we have a constant value with a different name we use.

Comment (tarekgh) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs:80]: got it. please continue with your original plan if no one else have more thoughts about it.

**Comment by michaelgsharp** [comment]
@eerhardt @ericstj I am not sure who all has permission to approve PR's right now, but if one of you has a few minutes could you look over this again now that all comments are resolved? Thanks!

**Review by tarekgh — APPROVED** [review]

**Review by eerhardt — CHANGES_REQUESTED** [review]
:clock1:

**Review by eerhardt — APPROVED** [review]
:shipit:

**Comment by ericstj** [comment]
FYI, I've added @tarekgh and @maryamariyan to the team and their reviews will now count towards approval.
