### PR TITLE
sample link and xml format  fixes

### LINKED ISSUE #1557: The format of the example XML is not correct in a few cases.
The sample link for the NormalizerCatalog.cs has an extra bracket out of place. 
The samples in MatrixFactorization and TimeSeries are missing the surrounding <example> XML  node. 

Those are causing problems with the samples displaying in the APIs documentation site.

### PR DESCRIPTION
**Pull request by sfilipi**
Fixes #1557 by correcting the link and XML format.

### CODE REVIEW

**Comment by sfilipi** [comment]
@wschin @ganik would you have time to take a look?

File: src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs [hunk 1]
```diff
@@ -78,11 +78,13 @@ namespace Microsoft.ML.Trainers
     ///     </list>
     /// </p>
     /// <p>Example code can be found by searching for <i>MatrixFactorization</i> in <a href='https://github.com/dotnet/machinelearning'>ML.NET.</a></p>
+    /// <example>
     /// <format type="text/markdown">
     /// <![CDATA[
-    /// [!code-csharp[MF](~/../docs/samples/docs/samples/Microsoft.ML.Samples/Dynamic/MatrixFactorization.cs "A matrix factorization example.")]
```
Comment (wschin) [inline src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs]: Why do we remove the example name? Why don't we use the entire file? Having 4 lines of copyright can free us from the risky line numbers.

Comment (sfilipi) [reply src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs]: Yep, we are doing that with #1576. 

This PR was to show the documentation team what to fix for the 0.7 release.
