### PR TITLE
Sample for IID spike and changepoint detection using time series stateful prediction engine.

### LINKED ISSUE #978: Time Series
**Time Series in ML.NET**
* Forecasting
  * Singular Spectrum Analysis
    * Modeling univariate time series. Implementation based on the model taken from http://arxiv.org/pdf/1206.6910.pdf. 

* Anomaly Detection 
  * Spike Detector
    * Detects spikes in an independent and identical(IID) sequence using adaptive kernel density estimation
  * Change Point Detector
    * Detects the change-points in an independent and identical(IID) sequence using adaptive kernel density estimation and martingales

* Smoothing transforms
  * Exponential Average Transform
    * Is a weighted average of the values: ExpAvg(yt) = a * yt + (1-a) * ExpAvg(yt-1).
  * Moving Average Transform
    * Applies a moving average on a time series
  * Percentile Threshold Transform
    * Is a sequential transform that decides whether the current value of the time-series belongs to the 'percentile' % of the top values in the sliding window. The output of the transform will be a boolean flag.
  * P Value Transform
    * Calculates the p-value of the current input in the sequence with regard to the values in the sliding window.

**New Features to come**
* **Estimator and PiGSTy APIs** for the below components
  * |Component|Priority|
     |---|---|
     | IidChangePointDetector | 0 |
     | IidSpikeDetector  | 0 |
     | SsaChangePointDetector| 0 |
     | ExponentialAverageTransform| 1 |
     | MovingAverageTransform| 1 |
     | PercentileThresholdTransform| 1 |
     | PValueTransform| 1 |
     | SlidingWindowTransform| 1 |
     
     Example:
      ```csharp
      var data = new[] { new Data() { Feature = 2 }, new Data() { Feature = 1} }; 
      var dataView = ComponentCreation.CreateDataView(Env, data); 
      var pipe = new SpikeDetectorEstimator(Env, new[]{ 
      new SpikeDetectorTransformer.ColumnInfo("Feature", "Anomaly", twnd:500, swnd:50) 
       }); 
      var result = pipe.Fit(dataView).Transform(dataView); 
      var resultRoles = new RoleMappedData(result);
      ```
* **Prediction Engine**
  * The prediction engine we have today is a stateless one. For time series it is important we update the state of the model as we make prediction in the case of SSA models that have temporal relation between data points. This will require creating a new variant of prediction engine that will be used by time series components listed above. #163 
  * Currently to achieve stateful prediction engine users have to write the below code and then create checkpoints by saving the model every so often. 
    ```csharp
               const int size = 10;
                List<Data> data = new List<Data>(size);
                var dataView = env.CreateStreamingDataView(data);
                List<Data> tempData = new List<Data>();
                for (int i = 0; i < size / 2; i++)
                    tempData.Add(new Data(5));

                for (int i = 0; i < size / 2; i++)
                    tempData.Add(new Data((float)(5 + i * 1.1)));

                foreach (var d in tempData)
                    data.Add(new Data(d.Value));

                var args = new IidChangePointDetector.Arguments()
                {
                    Confidence = 80,
                    Source = "Value",
                    Name = "Change",
                    ChangeHistoryLength = size,
                    Data = dataView
                };
               
               //Train
                var detector = TimeSeriesProcessing.IidChangePointDetector(env, args);
                //Anomaly Detection
                var output = detector.Model.Apply(env, dataView);
                var enumerator = output.AsEnumerable<Prediction>(env, true).GetEnumerator();
               //Save the updated model 
               detector.Model.Save();
      ```
  * Instead we could have a below API that allows the user to save the model at fixed intervals to a disk or a stream while updating the model. 
```csharp 
           using (var env = new LocalEnvironment(seed: 1, conc: 1))
            {
                // Pipeline
                var loader = TextLoader.ReadFile(env, MakeArgs(), new MultiFileSource(GetDataPath(TestDatasets.AnomalyDetection)));
                var cachedTrain = new CacheDataView(env, loader, prefetch: null);

                // Train.
                var IidDetector = new IidChangePointDetector(env, new IidChangePointDetector.Arguments
                {
                   Confidence = 80,
                    Source = "Features",
                    Name = "Change",
                    ChangeHistoryLength = size,
                    Data = dataView
                });
                var trainRoles = new RoleMappedData(cachedTrain, feature: "Features");
                var predictor = IidDetector.Train(new Runtime.TrainContext(trainRoles));

                PredictionEngine<Input, Prediction> model;
                using (var file = env.CreateTempFile())
                {
                    // Save model. 
                    var roles = new RoleMappedData(trans, feature: "Features");
                    using (var ch = env.Start("saving"))
                        TrainUtils.SaveModel(env, ch, file, predictor, roles);

                    // Load model.
                    using (var fs = file.OpenReadStream())
                        model = env.CreatePredictionEngine<Input, Prediction>(fs);
                }

                // Take a couple examples out of the test data and run predictions on top.
                var testLoader = TextLoader.ReadFile(env, MakeArgs(), new MultiFileSource(GetDataPath(TestDatasets.AnomalyDetection));
                var testData = testLoader.AsEnumerable<Input>(env, false);
                foreach (var input in testData.Take(10))
                {
                   //Anomaly detection + update the model.
                    var prediction = model.Predict(input);
                }                
               
               //Save the model with updated state.
                model.Save();
            }
```

* **Online Training**
   Currently we have to train the model with the entire train dataset to update the model but instead it would be nice if the model got updated as the data came in. #163

* **Evaluator**
  * Currently we don’t have any evaluator for time series. Rolling CV is better for time dependent datasets by always testing on data which is newer than the training data. Standard CV leaks future data in to the training set. Other names of Rolling CV include { walk-forward / roll-forward / rolling origin / window } CV. Refer to #1026

* **ARIMA model** 
It seems the first thing novice time series users look for in a toolkit when doing a forecasting task is ARMIA model because it is the first thing that comes up in search results for forecasting. While ARMIA model isn’t the most accurate or performant model but it is the most well-known forecasting model. We should consider bringing in a simple implementation of ARIMA in ML.NET. #929 

* **Time Series Featurizer**  
The more performant models are the one that combine the features from a time series transform with non-time series features and feed in the resulting vector into a black-box regression learning algorithm. For example, one could have two features A and B, where A will contain data points that have temporal relationship between them, example, stock price and B contains non-temporal feature like country or zip code. We could feed A into SSA transform that will extract various components from an individual feature value such as trend, level, seasonality and then repeat this for all the feature values of A and then combine the result vector with feature B that could be feed into a regressor for prediction. The feature extraction step could be SSA or it could be a deep learning model such as LSTM. The regressor could be any regression based learner.  #929 

... and many more with `time`.

### PR DESCRIPTION
**Pull request by codemzs**
Sample for IID spike and changepoint detection using time series stateful prediction engine. Fixes #978

### CODE REVIEW

**Comment by montebhoover** [comment]
@sfilipi is added to the review. #Closed

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 1]
```diff
@@ -83,5 +87,84 @@ public static void IidSpikeDetectorTransform()
...
+                Console.WriteLine("{0}\t{1}\t{2:0.00}\t{3:0.00}", 5, prediction.Prediction[0],
+                    prediction.Prediction[1], prediction.Prediction[2]);
+            }
+
+            // Spike.
+            var spikePrediction = engine.Predict(new IidSpikeData(10));
+            Console.WriteLine("{0}\t{1}\t{2:0.00}\t{3:0.00}", 10, spikePrediction.Prediction[0],
+                spikePrediction.Prediction[1], spikePrediction.Prediction[2]);
+
+            // Checkpoint the model.
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: >// Checkpoint the model. [](start = 12, length = 24)

why we doing this?

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 2]
```diff
@@ -83,5 +87,84 @@ public static void IidSpikeDetectorTransform()
...
+            for (int index = 0; index < 5; index++)
+            {
+                // Anomaly spike detection.
+                var prediction = engine.Predict(new IidSpikeData(5));
+                Console.WriteLine("{0}\t{1}\t{2:0.00}\t{3:0.00}", 5, prediction.Prediction[0],
+                    prediction.Prediction[1], prediction.Prediction[2]);
+            }
+
+            // Prediction column obtained post-transformation.
+            // Datat Alert   Score   P-Value
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: >Datat [](start = 15, length = 5)

Data?

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 3]
```diff
@@ -83,5 +87,84 @@ public static void IidSpikeDetectorTransform()
...
+            ITransformer model = new IidSpikeEstimator(ml, args).Fit(dataView);
+
+            // Create a time series prediction engine from the model.
+            var engine = model.CreateTimeSeriesPredictionFunction<IidSpikeData, IidSpikePrediction>(ml);
+            for (int index = 0; index < 5; index++)
+            {
+                // Anomaly spike detection.
+                var prediction = engine.Predict(new IidSpikeData(5));
+                Console.WriteLine("{0}\t{1}\t{2:0.00}\t{3:0.00}", 5, prediction.Prediction[0],
+                    prediction.Prediction[1], prediction.Prediction[2]);
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: No offense, but this is awful.
How I'm suppose to know size of array I need to pass?
How I'm suppose to know what is meaning behind index 0, index 1, index 2, index 3?

Why this not wrap in a proper class with properties?

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 2 above)
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: >Datat Alert   Score   P-Value [](start = 15, length = 29)

Did we spell anywhere in our documentation what this Alert, Score, and P-Value means?

Imagine person without statistical background who will try to run this Spike prediction.
All he wants is predict DDOS attack based on current traffic numbers.
Is he need to look on Alert column only?
What Score column for?
Should he look into P-Value column? (What is our null hypothesis here? Absence of spike or presence of spike?)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 4]
```diff
@@ -83,5 +87,84 @@ public static void IidSpikeDetectorTransform()
...
+
+            // Setup IidSpikeDetector arguments
+            string outputColumnName = "Prediction";
+            string inputColumnName = "Value";
+            var args = new IidSpikeDetector.Arguments()
+            {
+                Source = inputColumnName,
+                Name = outputColumnName,
+                Confidence = 95,                // The confidence for spike detection in the range [0, 100]
+                PvalueHistoryLength = size / 4  // The size of the sliding window for computing the p-value
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: >size / 4  [](start = 38, length = 9)

Any reason why we divide by 4?
Is it magic number, or it has some useful meaning?

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 5]
```diff
@@ -83,5 +87,84 @@ public static void IidSpikeDetectorTransform()
...
+            data.Add(new IidSpikeData(10));
+            for (int i = 0; i < size / 2; i++)
+                data.Add(new IidSpikeData(5));
+
+            // Convert data to IDataView.
+            var dataView = ml.CreateStreamingDataView(data);
+
+            // Setup IidSpikeDetector arguments
+            string outputColumnName = "Prediction";
+            string inputColumnName = "Value";
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: >"Value" [](start = 37, length = 7)

nameof(IidSpikeData.Value)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 6]
```diff
@@ -83,5 +87,84 @@ public static void IidSpikeDetectorTransform()
...
+            // This is a spike
+            data.Add(new IidSpikeData(10));
+            for (int i = 0; i < size / 2; i++)
+                data.Add(new IidSpikeData(5));
+
+            // Convert data to IDataView.
+            var dataView = ml.CreateStreamingDataView(data);
+
+            // Setup IidSpikeDetector arguments
+            string outputColumnName = "Prediction";
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: >Prediction [](start = 39, length = 10)

nameof(IidSpikePrediction.Prediction)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 3 above)
Comment (montebhoover) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: I think Zeeshan made a note of this in the PR for prediction engine, and mentioned that it would require a bit of extra refactoring so he would make it in a separate PR.  I'll let him elaborate.

---
In reply to: [237329405](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237329405) [](ancestors = 237329405)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs [hunk 7]
```diff
@@ -88,5 +92,92 @@ public static void IidChangePointDetectorTransform()
             // 7       0       7.00    0.50    0.00
             // 7       0       7.00    0.50    0.00
         }
+
+        // This example creates a time series (list of Data with the i-th element corresponding to the i-th time slot).
```
[the remark this answers is not in the document]
Comment (montebhoover) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs]: Sorry, I was just mentioning that everything we add to this file will show up verbatim in the docs site on the page for IidChangePointDetector.  Since this adds a second sample to the file, we now have two samples on the docs site - just checking if that is what we actually want.

---
In reply to: [237313709](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237313709) [](ancestors = 237313709)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs [hunk 8]
```diff
@@ -88,5 +92,92 @@ public static void IidChangePointDetectorTransform()
...
+        // IidChangePointDetector is applied then to identify points where data distribution changed using time series 
+        // prediction engine. The engine is checkpointed and then loaded back from disk into memory and used for prediction.
+        public static void IidChangePointDetectorPrediction()
+        {
+            // Create a new ML context, for ML.NET operations. It can be used for exception tracking and logging, 
+            // as well as the source of randomness.
+            var ml = new MLContext();
+
+            // Generate sample series data with a change
+            const int size = 16;
```
Comment (montebhoover) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs]: Do we use the C# convention of PascalCase for constants?

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 4 above)
Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: You can have any length of history. I'm just replicating the above example here to show it can also be used with prediction engine.

---
In reply to: [237330349](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237330349) [](ancestors = 237330349)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs [hunk 9]
```diff
@@ -88,5 +92,92 @@ public static void IidChangePointDetectorTransform()
...
+            var args = new IidChangePointDetector.Arguments()
+            {
+                Source = inputColumnName,
+                Name = outputColumnName,
+                Confidence = 95,                // The confidence for spike detection in the range [0, 100]
+                ChangeHistoryLength = size / 4, // The length of the sliding window on p-values for computing the martingale score. 
+            };
+
+            // Time Series model.
+            ITransformer model = new IidChangePointEstimator(ml, args).Fit(dataView);
```
Comment (GalOshri) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs]: Should the `IidChangePointEstimator` be accessed through `MLContext` instead?

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs [hunk 10]
```diff
@@ -88,5 +92,92 @@ public static void IidChangePointDetectorTransform()
...
+
+            // Create a time series prediction engine from the model.
+            var engine = model.CreateTimeSeriesPredictionFunction<IidChangePointData, ChangePointPrediction>(ml);
+            for(int index = 0; index < 8; index++)
+            {
+                // Anomaly change point detection.
+                var prediction = engine.Predict(new IidChangePointData(5));
```
Comment (montebhoover) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs]: I think this is not exactly right for demonstrating ChangePoint since it is supposed to identify when there has been a change in trend, as opposed to SpikeDetection.  By definition, we would want to run a prediction on a series of new data points and see if at any point in the series it detects something that is not just a spike, a change in the trend.

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 3 above)
Comment (montebhoover) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: Do we still want to do the future work to wrap this output vector column in a class with named properties, or even turning it into three scalar output columns?

---
In reply to: [237625679](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237625679) [](ancestors = 237625679,237595774,237329405)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidChangePointDetectorTransform.cs]: I'll sync offline with you on this.

---
In reply to: [237596871](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237596871) [](ancestors = 237596871,237313709)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 1 above)
Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: We are checkpointing the model so that we can reload it with the updated saved from the predictions. Yep, I have addressed that as part of documentation.

---
In reply to: [237327645](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237327645) [](ancestors = 237327645)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 4 above)
Comment (montebhoover) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: Does it help to have a comment something like this: "The size of the sliding window for computing the p-value; shorter windows are more sensitive to spikes."

---
In reply to: [237623190](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237623190) [](ancestors = 237623190,237330349)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 1 above)
Comment (montebhoover) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: Where is the documentation?  I wanted to see if I need to add anything for Martingale, P-Value, etc.

---
In reply to: [237702797](https://github.com/dotnet/machinelearning/pull/1762#discussion_r237702797) [](ancestors = 237702797,237327645)

Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: Its in this PR, check files under src/Microsoft.ML.TimeSeries

File: src/Microsoft.ML.TimeSeries/PredictionFunction.cs [hunk 11]
```diff
@@ -246,6 +252,27 @@ public override void Predict(TSrc example, ref TDst prediction)
...
+        /// <see cref="TimeSeriesPredictionFunction{TSrc, TDst}"/> creates a prediction function/engine for a time series pipeline
+        /// It updates the state of time series model with observations seen at prediction phase and allows checkpointing the model.
+        /// </summary>
+        /// <typeparam name="TSrc">Class describing input schema to the model.</typeparam>
+        /// <typeparam name="TDst">Class describing the output schema of the prediction.</typeparam>
+        /// <param name="transformer">The time series pipeline in the form of a <see cref="ITransformer"/></param>
+        /// <param name="env">Usually <see cref="MLContext"/></param>
+        /// <param name="ignoreMissingColumns"></param>
+        /// <param name="inputSchemaDefinition"></param>
+        /// <param name="outputSchemaDefinition"></param>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/PredictionFunction.cs]: Can you either fill it with description or just remove from public facing API?

File: src/Microsoft.ML.TimeSeries/PredictionFunction.cs [hunk 12]
```diff
@@ -246,6 +252,27 @@ public override void Predict(TSrc example, ref TDst prediction)
...
+        /// <returns></returns>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/PredictionFunction.cs]: remove

File: src/Microsoft.ML.TimeSeries/PredictionFunction.cs [hunk 13]
```diff
@@ -246,6 +252,27 @@ public override void Predict(TSrc example, ref TDst prediction)
 
     public static class PredictionFunctionExtensions
     {
+        /// <summary>
+        /// <see cref="TimeSeriesPredictionFunction{TSrc, TDst}"/> creates a prediction function/engine for a time series pipeline
+        /// It updates the state of time series model with observations seen at prediction phase and allows checkpointing the model.
+        /// </summary>
+        /// <typeparam name="TSrc">Class describing input schema to the model.</typeparam>
+        /// <typeparam name="TDst">Class describing the output schema of the prediction.</typeparam>
+        /// <param name="transformer">The time series pipeline in the form of a <see cref="ITransformer"/></param>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/PredictionFunction.cs]: >>< [](start = 105, length = 2)

add `.`

File: src/Microsoft.ML.TimeSeries/PredictionFunction.cs [hunk 14]
```diff
@@ -53,6 +53,12 @@ public sealed class TimeSeriesPredictionFunction<TSrc, TDst> : PredictionEngineB
         private long _rowPosition;
         private ITransformer InputTransformer { get; set; }
 
+        /// <summary>
+        /// Checkpoints <see cref="TimeSeriesPredictionFunction{TSrc, TDst}"/> to disk with the updated
+        /// state.
+        /// </summary>
+        /// <param name="env">Usually <see cref="MLContext"/></param>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/PredictionFunction.cs]: >>< [](start = 60, length = 2)

add .

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 15]
```diff
@@ -4,6 +4,10 @@
 using Microsoft.ML.Runtime.Data;
 using Microsoft.ML.Runtime.Api;
 using Microsoft.ML.Runtime.TimeSeriesProcessing;
+using Microsoft.ML.Core.Data;
+using Microsoft.ML.TimeSeries;
+using System.IO;
+using Microsoft.ML.Data;
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: ctrl+r+g, aka sort them :)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs [hunk 16]
```diff
@@ -83,5 +87,83 @@ public static void IidSpikeDetectorTransform()
...
+
+            // Spike.
+            var spikePrediction = engine.Predict(new IidSpikeData(10));
+            Console.WriteLine("{0}\t{1}\t{2:0.00}\t{3:0.00}", 10, spikePrediction.Prediction[0],
+                spikePrediction.Prediction[1], spikePrediction.Prediction[2]);
+
+            // Checkpoint the model.
+            var modelPath = "temp.zip";
+            engine.CheckPoint(ml, modelPath);
+
```
Comment (Ivanidzo4ka) [inline docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: I understand what you trying to show up here, but I'm not sure it would be clear to user.

Can you do following:
Train model.
Score it with data A.
Checkpoint at some moment.
Score it with data B.
Load model with check point.
Score it with data B.

To show up what we preserve state.

Right now you have following:
Train model.
Score it with data A.
Checkpoint at some moment.
Load model with check point.
Score it with data B.

**Comment by sfilipi** [comment]
> using System.Linq;

the samples are a bit too long. The API samples should illustrate just the API usage; not a full end-to-end example of how to do time-series. 

I think as they are , without prediction they are better. You can add a full sample with prediction to the machinelearning-samples repo. 

If asked, i would not merge this PR at all, and contribute the full work to that repo. 

---
Refers to: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs:2 in 96aa6ec. [](commit_id = 96aa6ece5f81296a785d0688ef99702d69b8f083, deletion_comment = False)

File: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs (hunk 16 above)
Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs]: I made this change in IID Change Point detector example.

---
In reply to: [238025595](https://github.com/dotnet/machinelearning/pull/1762#discussion_r238025595) [](ancestors = 238025595)

**Comment by codemzs** [comment]
> using System.Linq;

I'll sync offline with you on this.

---
In reply to: [443404897](https://github.com/dotnet/machinelearning/pull/1762#issuecomment-443404897) [](ancestors = 443404897)

---
Refers to: docs/samples/Microsoft.ML.Samples/Dynamic/IidSpikeDetectorTransform.cs:2 in 96aa6ec. [](commit_id = 96aa6ece5f81296a785d0688ef99702d69b8f083, deletion_comment = False)
