### PR TITLE
Ensured Sanitized Column Names are Unique in AutoML CLI

### LINKED ISSUE #3902: Ensure Sanitized Column Names are Unique in AutoML
When creating sanitized column names, we have to ensure the column names are distinct.

### Error
We generate non-compilable C# code when there are naming collisions.

Example build error:
`/private/tmp/out/CivicHonesty/CivicHonesty.Model/DataModels/ModelInput.cs(23,23): Error CS0102: The type 'ModelInput' already contains a definition for 'Country' (CS0102) (CivicHonesty.Model)`

### Repro
In the [Civic Honesty dataset](https://dataverse.harvard.edu/api/access/datafile/3451248?format=original&gbrecs=true) (CSV), we cause a naming collision in the generated C# code:
```C#
namespace CivicHonesty.Model.DataModels
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }

        [ColumnName("country"), LoadColumn(1)]
        public float Country { get; set; }

        [ColumnName("Country"), LoadColumn(2)]
        public string Country { get; set; }

        [ColumnName("city"), LoadColumn(3)]
        public float City { get; set; }
```

You'll note the two variables both called `Country`.

This comes from the dataset using "country" and "Country":
> image

Dataset: https://dataverse.harvard.edu/api/access/datafile/3451248?format=original&gbrecs=true

CLI command:
`mlnet auto-train --dataset "behavioral data (csv file).csv"  --label-column-name response --mltask multiclass-classification --ignore-columns responsetime,id --max-exploration-time 60 --output-path /tmp/out/ --name CivicHonesty`

### Cause
Currently, we have no detection for duplicate column names. 

The above "country" vs. "Country" is a rather direct example. This will occur less directly and more often due to our name sanitization where we map, for example, "$ spent" and "% spent" both to "__spent":
https://github.com/dotnet/machinelearning/blob/227da9d7db2ce80b073cc64bfd067b04e6189de1/src/mlnet/Utilities/Utils.cs#L67-L83

https://github.com/dotnet/machinelearning/blob/227da9d7db2ce80b073cc64bfd067b04e6189de1/src/mlnet/Utilities/Utils.cs#L47-L50

### Work
Todo:
* Check that sanitized column names are unique
* Check that when converted to C# variable names, the sanitized column names will be unique and valid C# variables

### PR DESCRIPTION
**Pull request by mstfbl**
Fix #3902. This PR ensures that column names that are pulled from datasets and used to generate C# model input are unique. As a result, naming collisions are prevented and are valid C# variables. This is done by adding the column naming-collision fix in `ML.CodeGenerator.Utilities.Utils.GenerateClassLabels`.

This naming-collision fix consists of appending the type of the variable to the name of the second duplicate. For example, let us have 3 columns in a sample dataset:

```csharp
int id;
int Country;
string country;
```

This is represented with `TextLoader.Columns[]` as:
```csharp

new TextLoader.Column[]
{
    new TextLoader.Column(){ Name = "id", Source = new TextLoader.Range[]{new TextLoader.Range(0) }, DataKind = DataKind.Int32 },
    new TextLoader.Column(){ Name = "Country", Source = new TextLoader.Range[]{new TextLoader.Range(1) }, DataKind = DataKind.Int32 },
    new TextLoader.Column(){ Name = "country", Source = new TextLoader.Range[]{new TextLoader.Range(2) }, DataKind = DataKind.String },
}
```

For `string country` to be a valid class variable, its first letter has to be capitalized, which would result in a naming collision. This PR ensures that this doesn't happen, and the generated code becomes:

```csharp
public class ModelInput
{
    [ColumnName("id"), LoadColumn(0)]
    public float Id_col_0 { get; set; }


    [ColumnName("Country"), LoadColumn(1)]
    public float Country_col_1 { get; set; }


    [ColumnName("country"), LoadColumn(2)]
    public string Country_col_2 { get; set; }
}
```

In addition, this PR ensures non-unique column names are properly named and differentiated, as shown below:

```csharp
new TextLoader.Column[]
{
    new TextLoader.Column(){ Name = "column1", Source = new TextLoader.Range[]{new TextLoader.Range(0) }, DataKind = DataKind.String },
    new TextLoader.Column(){ Name = "column1_string", Source = new TextLoader.Range[]{new TextLoader.Range(1) }, DataKind = DataKind.String },
    new TextLoader.Column(){ Name = "column1_string_1", Source = new TextLoader.Range[]{new TextLoader.Range(2) }, DataKind = DataKind.String },
    new TextLoader.Column(){ Name = "column1_string_2", Source = new TextLoader.Range[]{new TextLoader.Range(3) }, DataKind = DataKind.String },
    new TextLoader.Column(){ Name = "Column1", Source = new TextLoader.Range[]{new TextLoader.Range(4) }, DataKind = DataKind.String },
    new TextLoader.Column(){ Name = "column1_int", Source = new TextLoader.Range[]{new TextLoader.Range(5) }, DataKind = DataKind.Int32 },
    new TextLoader.Column(){ Name = "column1_string", Source = new TextLoader.Range[]{new TextLoader.Range(6) }, DataKind = DataKind.String },
    new TextLoader.Column(){ Name = "column1", Source = new TextLoader.Range[]{new TextLoader.Range(7) }, DataKind = DataKind.Int32 }
}
```
```csharp
public class ModelInput
{
    [ColumnName("column1"), LoadColumn(0)]
    public string Column1_col_0{get; set;}

    [ColumnName("column1_string"), LoadColumn(1)]
    public string Column1__string_col_1{get; set;}

    [ColumnName("column1_string_1"), LoadColumn(2)]
    public string Column1_string_1_col_2{get; set;}

    [ColumnName("column1_string_2"), LoadColumn(3)]
    public string Column1_string_2_col_3{get; set;}

    [ColumnName("Column1"), LoadColumn(4)]
    public string Column1_col_4{get; set;}

    [ColumnName("column1_int"), LoadColumn(5)]
    public int Column1_int_col_5{get; set;}

    [ColumnName("column1_string"), LoadColumn(6)]
    public string Column1_string_col_6{get; set;}

    [ColumnName("column1"), LoadColumn(7)]
    public int Column1_col_7{get; set;}
}
```

This PR also adds unit tests to test naming collision scenarios in both `CodeGenTests` and `ConsoleCodeGeneratorTests`.

In addition, this PR also cleans up duplicate code with respect to the `ML.CodeGenerator.Utilities.Utils.GenerateClassLabels` function, by linking its duplicate function `ML.CodeGenerator.CodeGenerator.GenerateClassLabels` to the former.

### CODE REVIEW

File: src/Microsoft.ML.CodeGenerator/CodeGenerator/CSharp/CodeGenerator.cs [hunk 1]
```diff
@@ -257,77 +257,12 @@ internal IList<(string, string[])> GenerateTransformsAndUsings(IEnumerable<Pipel
             return (trainerString, trainerUsings);
         }
 
+        /// <summary>
+        /// Utilize <see cref="ML.CodeGenerator.Utilities.Utils.GenerateClassLabels(ColumnInferenceResults, IDictionary{string, CodeGeneratorSettings.ColumnMapping})"/>
+        /// </summary>
         internal IList<string> GenerateClassLabels(IDictionary<string, CodeGeneratorSettings.ColumnMapping> columnMapping = default)
```
Comment (mstfbl) [inline src/Microsoft.ML.CodeGenerator/CodeGenerator/CSharp/CodeGenerator.cs:263]: I've decided to keep this `GenerateClassLabels` as it is possible that a `CodeGenerator` instance can call this function, as it does below:

File: test/Microsoft.ML.CodeGenerator.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs [hunk 2]
```diff
@@ -281,7 +291,7 @@ public void ModelInputClassTest()
                 }.TransformText(),
                 Name = "ModelInput.cs",
             };
-            NamerFactory.AdditionalInformation = "null_map";
+            NamerFactory.AdditionalInformation = info + "_null_map";
```
Comment (mstfbl) [inline test/Microsoft.ML.CodeGenerator.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs:294]: I made this change to produce and check for 4 "approved" files within 1 unit test, instead of making a new unit test consisting of mostly duplicate code from this test.

File: test/Microsoft.ML.CodeGenerator.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs [hunk 3]
```diff
@@ -296,7 +306,7 @@ public void ModelInputClassTest()
                 }.TransformText(),
                 Name = "ModelInput.cs",
             };
-            NamerFactory.AdditionalInformation = "map";
+            NamerFactory.AdditionalInformation = info + "_map";
```
Comment (mstfbl) [inline test/Microsoft.ML.CodeGenerator.Tests/ApprovalTests/ConsoleCodeGeneratorTests.cs:309]: Same logic as above.

File: src/Microsoft.ML.CodeGenerator/Utils.cs [hunk 4]
```diff
@@ -309,12 +281,45 @@ internal static IList<string> GenerateClassLabels(ColumnInferenceResults columnI
                     result.Add($"[ColumnName(\"{columnName}\"), LoadColumn({column.Source[0].Min})]");
                 }
                 sb.Append(" ");
-                sb.Append(Utils.Normalize(column.Name));
+                string normalizedColumnName = Utils.Normalize(column.Name);
+                if (columnNames.Contains(normalizedColumnName))
+                {
+                    normalizedColumnName = normalizedColumnName + "_" + GetSymbolOfDataKind(dataKind);
+                    if (columnNames.Contains(normalizedColumnName))
+                        throw new ArgumentException($"The column '{column.Name}' with type '{dataKind}' is not unique in the dataset.");
```
Comment (LittleLittleCloud) [inline src/Microsoft.ML.CodeGenerator/Utils.cs:289]: so it will still throw an error when user has (col:int, col:string and Col:string) in their dataset?

Comment (mstfbl) [reply src/Microsoft.ML.CodeGenerator/Utils.cs:289]: Currently yes. Thank you for noting this. When there is an input column of the same name and type and when `columnMapping = null`, it currently throws an error. However, I can implement to do the following: 

When 2 input columns share the same name and type (say 1 "Country" and 2 "country" and `typeof(country)=string' columns, the second identical "country" column could be named as "Country_string_1". Would we like to implement this, or would we want to expect unique columns of the exact name(case-sensitive) and type?

Comment (mstfbl) [reply src/Microsoft.ML.CodeGenerator/Utils.cs]: Hi @LittleLittleCloud , I just updated my code to address your concern.

File: src/Microsoft.ML.CodeGenerator/Utils.cs [hunk 5]
```diff
@@ -309,12 +284,51 @@ internal static IList<string> GenerateClassLabels(ColumnInferenceResults columnI
...
-                sb.Append("{get; set;}");
+                string normalizedColumnName = Utils.Normalize(column.Name);
+                // Put placeholder for normalized and unique version of column name
+                if (!duplicateColumnNamesExist && normalizedColumnNames.Contains(normalizedColumnName))
+                    duplicateColumnNamesExist = true;
+                normalizedColumnNames.Add(normalizedColumnName);
                 result.Add(sb.ToString());
                 result.Add("\r\n");
             }
+            for (int i = 1; i < result.Count; i+=3)
```
Comment (LittleLittleCloud) [inline src/Microsoft.ML.CodeGenerator/Utils.cs:295]: Could you make sure the generated label are identical for other source files in generated project?
For example, here in Program.tt
https://github.com/mstfbl/machinelearning/blob/42dfa105fddf04ab23d0e574580edf6f99a955a6/src/Microsoft.ML.CodeGenerator/Templates/Console/PredictProgram.tt#L47

and here: (SampleData also call into Util.Normalize)
https://github.com/mstfbl/machinelearning/blob/42dfa105fddf04ab23d0e574580edf6f99a955a6/src/Microsoft.ML.CodeGenerator/Templates/Console/PredictProgram.tt#L27

Comment (mstfbl) [reply src/Microsoft.ML.CodeGenerator/Utils.cs:295]: Currently, these generated labels are generated using `Utils.Normalize` in [GenerateSampleData](https://github.com/dotnet/machinelearning/blob/1296c29c9e08cbe0720b021144d2d08fa2c04a8e/src/Microsoft.ML.CodeGenerator/Utils.cs#L50-L69), and hence are not added the `_col_x` suffix for conflicting column names. I am making an issue to track this change. Thanks!
