### PR TITLE
Turned TensorFlowEstimator into non-trivial estimator and removed shuffling as part of TensorFlowTransform.

### LINKED ISSUE #1106: Error due to ShuffleTransform in pipeline.
Need to convert `ShuffleTransform` into Transformer/Estimator design. Currently, when it is used in `TensorFlowTransform` to enable shuffling of data during training, it gives error regarding <b>`ShuffleTransform is not RowToRowMapper`</b>.

### Update
It seems like the transform works fine during training. The error is somewhere when creating prediction engine.

The following is the exact location where assertion fails during creation of prediction engine.
https://github.com/dotnet/machinelearning/blob/8ca1c9386587aa4ef77c56f605f8244debefce93/src/Microsoft.ML.Data/DataLoadSave/TransformWrapper.cs#L133

Here is the test failure log
```
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8050239]         E:\TLC_git\machinelearning\test\Microsoft.ML.TestFramework\GlobalBase.cs(70,0): at Microsoft.ML.Runtime.Internal.Internallearn.Test.GlobalBase.AssertHandler(String msg, IExceptionContext ectx)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8060923]         E:\TLC_git\machinelearning\src\Microsoft.ML.Core\Utilities\Contracts.cs(777,0): at Microsoft.ML.Runtime.Contracts.DbgFailCore(String msg, IExceptionContext ctx)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8064869]         E:\TLC_git\machinelearning\src\Microsoft.ML.Core\Utilities\Contracts.cs(786,0): at Microsoft.ML.Runtime.Contracts.DbgFail(IExceptionContext ctx)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8067575]         E:\TLC_git\machinelearning\src\Microsoft.ML.Core\Utilities\Contracts.cs(841,0): at Microsoft.ML.Runtime.Contracts.Assert(IExceptionContext ctx, Boolean f)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8070263]         E:\TLC_git\machinelearning\src\Microsoft.ML.Data\DataLoadSave\TransformWrapper.cs(133,0): at Microsoft.ML.Runtime.Data.TransformWrapper.GetRowToRowMapper(ISchema inputSchema)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8073429]         E:\TLC_git\machinelearning\src\Microsoft.ML.Api\PredictionEngine.cs(190,0): at Microsoft.ML.Runtime.Api.PredictionEngine`2..ctor(IHostEnvironment env, Func`2 makeMapper, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8076450]         E:\TLC_git\machinelearning\src\Microsoft.ML.Api\PredictionEngine.cs(172,0): at Microsoft.ML.Runtime.Api.PredictionEngine`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8078831]         E:\TLC_git\machinelearning\src\Microsoft.ML.Api\PredictionEngine.cs(166,0): at Microsoft.ML.Runtime.Api.PredictionEngine`2..ctor(IHostEnvironment env, IDataView dataPipe, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8081564]         E:\TLC_git\machinelearning\src\Microsoft.ML.Api\ComponentCreation.cs(190,0): at Microsoft.ML.Runtime.Api.ComponentCreation.CreatePredictionEngine[TSrc,TDst](IHostEnvironment env, IDataView dataPipe, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8084805]         E:\TLC_git\machinelearning\test\Microsoft.ML.Tests\ScenariosWithDirectInstantiation\TensorflowTests.cs(438,0): at Microsoft.ML.Scenarios.ScenariosTests.ExecuteTFTransformMNISTLRTrainingTest(Boolean shuffle, Nullable`1 shuffleSeed, Double expectedMicroAccuracy, Double expectedMacroAccruacy)
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8087841]         E:\TLC_git\machinelearning\test\Microsoft.ML.Tests\ScenariosWithDirectInstantiation\TensorflowTests.cs(365,0): at Microsoft.ML.Scenarios.ScenariosTests.TensorFlowTransformMNISTLRTrainingTest()
[10/9/2018 4:18:27 PM Informational] [xUnit.net 00:00:10.8586866]   Finished:    Microsoft.ML.Tests
```

### LINKED ISSUE #1110: Convert TensorFlowEstimator into Non-TrivialEstimator.
The `TensorFlowEstimator` is currently a `TrivialEstimator`. Recently, model retraining feature was added to `TensorFlowTransform` which requires the `TensorFlowEstimator` to be non-trivial estimator.

### PR DESCRIPTION
**Pull request by zeahmed**
This PR fixes #1106 and it also fixes #1110.

- Converted TensorFlowEstimator into non-trivial estimator because of training feature.
- Removed the shuffling of data that was being done internally in TensorFlowTransform (was commented out due to #1106). The idea is to give user more control over the shuffling by allowing them to use the ShuffleTransform in their pipeline explicit. This also reduces the number of parameters in TensorFlowTransform.Argument class. Please see the modified tests for use-cases.

### CODE REVIEW

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 1]
```diff
@@ -299,13 +293,6 @@ internal TensorFlowTransform(IHostEnvironment env, Arguments args, IDataView inp
 
             if (args.ReTrain)
             {
-                // Shuffling fails because ShuffleTransform is not RowToRowMapper
-                // https://github.com/dotnet/machinelearning/issues/1106
-                //if(args.Shuffle)
-                //{
-                //    input = new ShuffleTransform(env, new ShuffleTransform.Arguments(), input);
```
Comment (Zruty0) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >input [](start = 22, length = 5)

frankly, I think the shuffle functionality could be preserved quite easily. You just need to make sure that `ShuffleTransform` is only applied at training time, and doesn't get applied after training.

So, don't do
`input = new Shuffle(input)`
but rather
`trainData = new Shuffle(input)`.

Comment (Zruty0) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: Then again, I don't know how important it is to shuffle, so I'm fine either way.

---
In reply to: [224558825](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224558825) [](ancestors = 224558825)

Comment (abgoswam) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: Not quite sure how helpful it is to remove vs keep it , esp. since tests for it are also commented out. 

(don't quite see the value of training component at this point with/without shuffle)

---
In reply to: [224558981](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224558981) [](ancestors = 224558981,224558825)

Comment (zeahmed) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: @Pete, Shuffle is important as can be witnessed by the performance of the tests(shuffle vs. non-shuffle). The test dataset is small but on larger datasets performance gains are much better. I have moved the shuffling out of transform to give user more control over the shuffling.

I have done the way you have mentioned but I am currently not sure what the end user scenario will be for transforms like "Shuffle", "Filter" etc.. If this would be the same in Estimator/Pigsty world that would be great then.

@Abhishek, code was commented for tests because of error. Now its no longer commented out as I have fixed it.

---
In reply to: [224568214](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224568214) [](ancestors = 224568214,224558981,224558825)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 2]
```diff
@@ -290,7 +284,7 @@ public static IDataTransform Create(IHostEnvironment env, Arguments args, IDataV
             return new TensorFlowTransform(env, args, input).MakeDataTransform(input);
         }
 
-        internal TensorFlowTransform(IHostEnvironment env, Arguments args, IDataView input)
+        public TensorFlowTransform(IHostEnvironment env, Arguments args, IDataView input)
```
Comment (Zruty0) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >public [](start = 8, length = 6)

This is a mistake. Training constructor should not be public.

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 1 above)
Comment (Zruty0) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: This is not what I meant. You can have the same logic (train on shuffle, then apply without shuffle) right here in this code, it doesn't have to be done by the caller.

---
In reply to: [224573294](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224573294) [](ancestors = 224573294,224568214,224558981,224558825)

Comment (pete) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: @zeahmed I am not aware of having mentioned anything like that, but I think I agree with @Zruty0 on the issue.

Comment (zeahmed) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: Ahh I see. That's actually I did not intend to do inside TFTransform. The reason being is that Shuffle has its own parameters e.g. `ForceShuffleSeed` which I will have to expose as another parameter in `TFTransform.Arguments` in addition to `Shuffle` (or may be more depending on usage). But I am fine if you think that's ok to have those parameters as `TFTransform.Arguments`.

I will change it to what you said unless you agree with my thinking...:)

---
In reply to: [224594321](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224594321) [](ancestors = 224594321,224573294,224568214,224558981,224558825)

Comment (zeahmed) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: Sorry wrong Pete...CodeFlow seems to have issue with tagging people.

---
In reply to: [224607610](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224607610) [](ancestors = 224607610)

Comment (Zruty0) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: So, I would be OK with either:
- Having no 'shuffle' at all, performing shuffling in the test, but still don't make the training constructor public: use estimator to `Fit` the transform.
- Having Shuffle available without extra shuffling params and doing training as I outlined above.
- Same, but with additional params to Shuffle also available.

My preference would be to do 2, or 1, but not 3, unless it is obvious that having extra args to Shuffle is actually helpful

---
In reply to: [224617477](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224617477) [](ancestors = 224617477,224594321,224573294,224568214,224558981,224558825)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 3]
```diff
@@ -299,17 +305,19 @@ internal TensorFlowTransform(IHostEnvironment env, Arguments args, IDataView inp
...
-                //if(args.Shuffle)
-                //{
-                //    input = new ShuffleTransform(env, new ShuffleTransform.Arguments(), input);
-                //}
-
                 env.CheckValue(input, nameof(input));
 
                 CheckTrainingParameters(args);
 
+                if(args.Shuffle)
```
Comment (Zruty0) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >Shuffle [](start = 24, length = 7)

how is this bypassing the row mapper problem?

Comment (zeahmed) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: This is happening at training time. The row mapper problem is happening at `CreatePredictionEngine` time. Please see #1106 for more info.

---
In reply to: [224640317](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224640317) [](ancestors = 224640317)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 1 above)
Comment (zeahmed) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: hmm...1 or 2 requires `TensorFlowEstimator`  to be non-trivial estimator then. Currently, `TensorFlowEstimator` is trivial estimator. I will change the `TensorFlowEstimator` to non-trivial one and update the PR title and description to reflect changes.

---
In reply to: [224640105](https://github.com/dotnet/machinelearning/pull/1208#discussion_r224640105) [](ancestors = 224640105,224617477,224594321,224573294,224568214,224558981,224558825)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 4]
```diff
@@ -1095,47 +1100,88 @@ public TFTensor GetBufferedBatchTensor()
         }
     }
 
-    public sealed class TensorFlowEstimator : TrivialEstimator<TensorFlowTransform>
+    public sealed class TensorFlowEstimator : IEstimator<TensorFlowTransform>
     {
-        public TensorFlowEstimator(IHostEnvironment env, string model, string[] inputs, string[] outputs)
-           : this(env, new TensorFlowTransform(env, TensorFlowUtils.GetSession(env, model), inputs, outputs, TensorFlowUtils.IsSavedModel(env, model) ? model : null, false))
+        private readonly IHost _host;
+        private readonly TensorFlowTransform.Arguments _args;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >TensorFlowTransform.Arguments _args [](start = 25, length = 35)

@Zruty0, are you ok with that? Or you ok with check this in, and clean it after?

Comment (zeahmed) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: Let me know if this needs to be done in different way. I will update it.

---
In reply to: [227577377](https://github.com/dotnet/machinelearning/pull/1208#discussion_r227577377) [](ancestors = 227577377)
