### PR TITLE
Fixed the TextTransform bug where chargrams where being computed differently when using with/without word tokenizer.

### LINKED ISSUE #530: [TextTransform] Char n-grams are different when using with/without word n-grams.
### System information

`Not relevant`

### Issue
When using TextTransform to compute n-grams, it has been observed that character n-grams produced are not consistent when computing it with/without word n-grams option. For example, for the following sentence 
```
This is a cat
```
The character n-grams produced are as follows. where `<STX>`, `<ETX>` and `<SP>` are start of sentence, end of sentence and space control characters respectively.

| Char 3-gram | Char 3-gram + Word 3-gram|
|-|-|
|\<STX\>\|t\|h | \<STX\>\|t\|h
| t\|h\|i | t\|h\|i
| h\|i\|s | h\|i\|s
| i\|s\|\<SP\> | i\|s\|\<ETX\>
| s\|\<SP\>\|i | s\|\<ETX\>\|\<STX\>
| \<SP\>\|i\|s | \<ETX\>\|\<STX\>\|i
| s\|\<SP\>\|a | \<STX\>\|i\|s
| \<SP\>\|a\|\<SP\> | \<ETX\>\|\<STX\>\|a
| a\|\<SP\>\|c | \<STX\>\|a\|\<ETX\>
| \<SP\>\|c\|a | a\|\<ETX\>\|\<STX\>
| c\|a\|t | \<ETX\>\|\<STX\>\|c
| a\|t\|\<ETX\> | \<STX\>\|c\|a
|-| c\|a\|t
|-| a\|t\|\<ETX\>

### Source code / logs
The cause of the problem is word tokenizer which is applied at the following location in the code.

https://github.com/dotnet/machinelearning/blob/669f4fad33184c9c558314f8bc758f7928ad62bf/src/Microsoft.ML.Transforms/Text/TextTransform.cs#L266

The `NeedsWordTokenizationTransform` property is set according to following criteria
https://github.com/dotnet/machinelearning/blob/669f4fad33184c9c558314f8bc758f7928ad62bf/src/Microsoft.ML.Transforms/Text/TextTransform.cs#L169

This means whenever word n-grams are being computed the tokenization is performed first and character n-gram extractor computes n-grams on words instead of sentences i.e. 

instead of computing char n-grams on 
```
<STX>This<SP>is<SP>a<SP>cat<ETX>
```
it computes char n-grams on
```
<STX>This<ETX>
<STX>is<ETX>
<STX>a<ETX>
<STX>cat<ETX>
```
First of all, is the expected behavior?
I my point of view `NOT` because in this way character n-gram is adding noise and losing important information regarding the sentence which in some cases may give superior performance.

### Solution
Apply char n-gram extractor on `IDataView` that was not used for word processing in the code.

### PR DESCRIPTION
**Pull request by zeahmed**
This PR fixes #530. The cause of the problem was `word tokenizer` being applied before `char tokenizer` causing scalar valued text (e.g. `This is a cat`) to become vector (e.g. <This, is, a, cat>). 

Previously, char tokenizer treated every vector item as separate text item (e.g. computing chargrams on each item by placing start and end markers `<STX>token<ETX>` instead of taking `This is a cat` as single text item).

The fix is in CharTokenizeTransform. The CharTokenizeTransform can take either a scalar or vector column as input. The processing of chargrams are done as follows.

- If the input column is a scalar with text type then chargrams are computed by prepending `<STX>` and appending `<ETX>` characters at the start and at the end of the text respectively.  For example, if the input is `This is a cat` then chargrams will be computed on `<STX>This is a cat<ETX>`.

- If the input column is a vector with text type (it could be a result of concatenation of several text columns together or application of word tokenizer before char tokenizer) then chargrams will be computed by prepending `<STX>` and appending `<ETX>` characters at start and at the end of the vector respectively. Also, <US> characters are inserted after every item in the vector. For example, if the input is `<This, is, a, cat>` then chargrams will be computed on `<STX>This<US>is<US>a<US>cat<ETX>`.

- To be backward compatible, CharTokenizerTransform version was bumped up and the support for loading models saved with previous version is added.

Moving forward, the chargrams will be computed as follows

- if `stop word removal` is request, chargrams will be computed after `StopwordRemovalTransform` is applied e.g. `<STX>This<US>is<US>a<US>cat<ETX>`.
- otherwise, raw text after text normalization will be used for chargram computing e.g. `This is a cat`.

### CODE REVIEW

File: src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs [hunk 1]
```diff
@@ -405,34 +405,55 @@ private ValueGetter<VBuffer<ushort>> MakeGetterVec(IRow input, int iinfo)
...
+
                         for (int i = 0; i < src.Count; i++)
                         {
                             if (!src.Values[i].HasChars)
                                 continue;
-                            if (_useMarkerChars)
-                                values[index++] = TextStartMarker;
+
+                            if (i > 0)
+                                values[index++] = ' ';
```
[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: Right. Space was *not* selected as the breaking character between tokens in a vector explicitly because it was quite likely to occur within individual tokens. This is why we chose a character unlikely to occur in text (vs. ***one of the most frequently observed characters***) in the first place. :)

---
In reply to: [203213571](https://github.com/dotnet/machinelearning/pull/548#discussion_r203213571) [](ancestors = 203213571)

[the remark this answers is not in the document]
Comment (zeahmed) [reply src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: So, there is no way to get the token that was used for tokenization?

**Comment by zeahmed** [comment]
@TomFinley, actually that's not the solution. In TextTransform, it is quite often desirable to compute both wordgrams and chargrams. If wordgrams are being computed then text will be tokenized and character tokenizer will see vector of text instead of just scalar text.

Text will also be tokenized when "stop words removal" option is set where user wants to remove stop words before computing chargrams. 

So, in both cases, character tokenizer will compute chargrams that are not valid chargrams (cf. #530). That's the only solution right now I see.

File: src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (zeahmed) [reply src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: In reality, if an statistical technique for word tokenization is applied then there is no reliable way to get the actual text after it has been tokenized. 

So, use of space is just an approximation. Otherwise, it not possible to get actual text string.

[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: > So, there is no way to get the token that was used for tokenization?

No. Indeed you have absolutely no idea whether the tokenization scheme involved breaking on single characters at all -- a vector of text could have come from anywhere. Indeed, more elaborate tokenization schemes exist, that involve an actual language model and so are considerably more elaborate than a simple `string.Split(char)`, which of course is the assumption made by this "fix."

I suggest that we not try to get into the business of trying to guess *how* the data that was fed into a transform, since doing so degrades the system. It would do more harm than good to do it -- we've built a modular system of transforms and data pipelines, but the consequence of a modular transform is that you must accept that your data *could* come from literally anywhere.

What I believe is a reasonable compromise, is that some sort of special character... perhaps a character not used often in text, but that is nonetheless specially reserved to indicate the start and end of a given block of text.

Happily, I believe that was the state of affairs of this transform in its existing implementation, before it was "fixed." :smile:

**Comment by justinormont** [comment]
The original issue was: the chargrams produced differed depending on if n-grams were also produced. This oddity should be fixed. 

I'm unsure the order we run the transforms, but I assume we can run as:

1. Language Detection _[not often used]_
2. Text normalization (lowercase, diacritics, punctuation, numbers) 
3. Word Tokenization
4. Stopword removal on tokenized text
5. **Chararacter tokenizer (on `#4` if stop word removal is enabled, otherwise on `#2`)**
6. Hashing (TF) / dictionary (TF, IDF, TF-IDF) of n-grams & Lp vector normalizer (LInf, L1 or L2)
7. Hashing (TF) / dictionary (TF, IDF, TF-IDF) of chargrams & Lp vector normalizer (LInf, L1 or L2)
8. Concat n-gram & chargram vectors
9. Return `#8` & optionally `#3` for `tokens=+`

Let me know if I'm wrong... 
Currently, the character tokenizer is reading from `#4` when n-grams are enabled, and `#2` when not. We can improve on this.

I think to produce consistency we can have the character tokenizer read from `#4` when the stop words are enabled, and `#2` when stop words are not enabled. [Option A]

This still produces the artifact of `<STX>This<ETX><STX>is<ETX><STX>a<ETX><STX>cat<ETX>` when the stop word remover is enabled. **I'm ok leaving this specific oddity in place,** as when you turn on the stop word remover, the user is expecting the output tokens to change (though this exact change is odd). The downside to this method is the wasted `char` of having both `<ETX>` & `<STX>` between tokens, which is lost signal. For instance from `This is a cat`, a 5-char-gram should get `a cat` but instead we produce `<ETX><STX>cat`. Perhaps replacing `<ETX><STX>` w/ [`<US>`](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#US) to _reduce_ this waste.

One stronger way to produce consistency, is to always have the character tokenizer read from `#2`. The effect of this is, the user's choice for stop words is ignored. [Option B]

I prefer [Option A]. Thoughts @Ivanidzo4ka, @TomFinley, @zeahmed?

**Comment by Ivanidzo4ka** [comment]
I'm no so familiar with Text transform pipeline, but I would prefer not to apply char tokenizer on top of word tokenizer. They should be treated independently, and consume same data source. 

---
In reply to: [405858371](https://github.com/dotnet/machinelearning/pull/548#issuecomment-405858371) [](ancestors = 405858371)

**Comment by TomFinley** [comment]
> Perhaps replacing <ETX><STX> w/ <US> to reduce this waste.

A single character delimiter to represent a transition vs. two seems fine and beneficial to me. The [unit separator](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Field_separators) seems like a fine choice, considering its description. Of course we must ensure that we don't break backcompat of previously serialized and composed models.

> One stronger way to produce consistency, is to always have the character tokenizer read from #2

Then you have one path that has stopwords removed, and another that does not. I don't see how that is more consistent. I don't even know what we're arguing is inconsistent in the current scheme.

**Comment by zeahmed** [comment]
> Hi @Justin Ormont , a single character delimiter to represent a transition vs. two seems fine and beneficial to me. The unit separator seems like a fine choice, considering its description. Of course we must ensure that we don't break backcompat of previously serialized and composed models.

I think this is in my current fix in this PR except that
- space is being used instead of unit separator character.
- data is read always read from `#4` instead of making a choice based on `stop word removal`.

The only problem I see from previous comments is whether it is good to do this fix in CharTokenizeTransform or not? In my opinion, it should be done in TextTransform. However, it does not seem possible unless there is a kind of string concate transform that can concatenate strings with separator (let me know if there is a way to do that?).

@Justin Ormont, yes [Option A] does seem a reasonable approach with `<ETX><STX>` replaced with `<US>`. Lets have a total agreement on it before I procced with further changes. I have to also look at the backcompat issue.

Thanks @Justin, @Ivan and @Tom for your useful insights, comments and feedback.

---
In reply to: [406017378](https://github.com/dotnet/machinelearning/pull/548#issuecomment-406017378) [](ancestors = 406017378)

**Comment by TomFinley** [comment]
> I think this is in my current fix in this PR except that
> * space is being used instead of unit separator character.

Right. That's a big difference, and a poor choice since the space is likely to occur in actual text. `<US>` is better from that perspective.

Not to harp on this, but the major problem with your PR of course is that you broke backwards compatibility for models.

**Comment by zeahmed** [comment]
> The original issue was: the chargrams produced differed depending on if n-grams were also produced. This oddity should be fixed. 
>
> I'm unsure the order we run the transforms, but I assume we can run as:
>
> 1. Language Detection _[not often used]_
> 2. Text normalization (lowercase, diacritics, punctuation, numbers) 
> 3. Word Tokenization
> 4. Stopword removal on tokenized text
> 5. **Chararacter tokenizer (on `#4` if stop word removal is enabled, otherwise on `#2`)**
> 6. Hashing (TF) / dictionary (TF, IDF, TF-IDF) of n-grams & Lp vector normalizer (LInf, L1 or L2)
> 7. Hashing (TF) / dictionary (TF, IDF, TF-IDF) of chargrams & Lp vector normalizer (LInf, L1 or L2)
> 8. Concat n-gram & chargram vectors
> 9. Return `#8` & optionally `#3` for `tokens=+`
>
> Let me know if I'm wrong... 

Currently, if word tokenization is requested, TextNormalization is applied after word tokenization. Should it be reversed? Is there any significance of TextNormalization being more effective after word tokenization is applied?

---
In reply to: [405858371](https://github.com/dotnet/machinelearning/pull/548#issuecomment-405858371) [](ancestors = 405858371)

**Comment by zeahmed** [comment]
Following are the changes in the new commit.
- Bumped version in CharTokenizerTransform so that new changes are backward compatible.
- Char tokenizer reads from the output of NormalizedTextTransform when `stop word removal` is not requested otherwise from the output of `StopwordRemovalTransform`.
- Moved `TextNormalization` before `WordTokenizer`. Let me know if there is any adverse effect of this.

File: src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs [hunk 2]
```diff
@@ -438,6 +442,67 @@ private ValueGetter<VBuffer<ushort>> MakeGetterVec(IRow input, int iinfo)
...
+
+                        if (_useMarkerChars)
+                            values[index++] = TextEndMarker;
+
+                        Contracts.Assert(index == len);
+                    }
+
+                    dst = new VBuffer<ushort>(len, values, dst.Indices);
+                };
+            return CurrentModelVersion < version.VerReadableCur ? valueGetterOldVersion : valueGetterCurrentVersion;
```
Comment (zeahmed) [inline src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: @TomFinley and @Ivanidzo4ka, Is this correct way to maintain backward compatibility?

File: src/Microsoft.ML.Transforms/Text/TextTransform.cs [hunk 3]
```diff
@@ -262,6 +262,30 @@ public static IDataTransform Create(IHostEnvironment env, Arguments args, IDataV
                 view = new ConcatTransform(h, new ConcatTransform.Arguments() { Column = xfCols }, view);
             }
 
+            if (tparams.NeedsNormalizeTransform)
```
Comment (zeahmed) [inline src/Microsoft.ML.Transforms/Text/TextTransform.cs]: @justinormont, I moved `TextNormalizer` above `WordTokenizer`. Let me know if there is any adverse effect of it?

File: src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs (hunk 2 above)
Comment (TomFinley) [reply src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: Not exactly. For one thing you've stored this in a static variable, which is not correct, since this behavior will be specific to the instance. So if you read *two* instances of the transform, one with the old version, one with the new version, you'd break one or the other (depending on the order in which you read them). As a general rule, not just in ML.NET but in any coding anywhere, storing *instance* specific data inside a *static* variable is generally a bad idea. :)

For the sake of resaving an *old* model to the *new* format, you ought to store a boolean variable in the new  version of the file, to control whether it is the old or new version. So the saver will have `ctx.Writer.WriteBoolByte(_isStartEnd)` and in the reader have something like `_isStartEnd = ctx.Header.ModelVerReadable < 0x00010002 || ctx.Reader.ReadBoolByte()`. This hypothetical `_isStartEnd` will be `private readonly`, and emphatically not `public static`.

If anything about that is not clear let me know, thanks @zeahmed!

---
In reply to: [203896119](https://github.com/dotnet/machinelearning/pull/548#discussion_r203896119) [](ancestors = 203896119)

File: src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs [hunk 4]
```diff
@@ -119,6 +121,7 @@ private CharTokenizeTransform(IHost host, ModelLoadContext ctx, IDataView input)
             // <base>
             // byte: _useMarkerChars value.
             _useMarkerChars = ctx.Reader.ReadBoolByte();
+            CurrentModelVersion = ctx.Header.ModelVerReadable;
```
Comment (TomFinley) [inline src/Microsoft.ML.Transforms/Text/CharTokenizeTransform.cs]: >CurrentModelVersion [](start = 12, length = 19)

Oh I see what you've done here.. this is not good, static variables are essentially global state. They are not particular to an instance.

File: src/Microsoft.ML.Transforms/Text/TextTransform.cs (hunk 3 above)
Comment (TomFinley) [reply src/Microsoft.ML.Transforms/Text/TextTransform.cs]: I don't like this change. It's far from clear to me that if someone asks to remove stopwords that they meant for the content of stopwords to be retained in the chargrams. At the very least this ought to be a configurable option.

---
In reply to: [204000786](https://github.com/dotnet/machinelearning/pull/548#discussion_r204000786) [](ancestors = 204000786)

Comment (zeahmed) [reply src/Microsoft.ML.Transforms/Text/TextTransform.cs]: @TomFinley, your comment is not clear to me. Can you elaborate more on this? Don't you see it good to have `TextNormalizer` applied before `WordTokenizer`?

---
In reply to: [204201054](https://github.com/dotnet/machinelearning/pull/548#discussion_r204201054) [](ancestors = 204201054,204000786)

Comment (TomFinley) [reply src/Microsoft.ML.Transforms/Text/TextTransform.cs]: Sorry thought you were saying something else for some reason got confused.

**Comment by zeahmed** [comment]
Thanks @TomFinley, @justinormont and @Ivanidzo4ka!
