### PR TITLE
Better names to calibreated linear classification models

### LINKED ISSUE #3016: The "Binary" in "LogisticRegressionBInaryTrainer" Looks Redundant
As title. Logistic regression is clearly a binary classifier, so we can consider dropping "Binary" among "LogisticRegressionBinaryTrainer". In addition, as L-BFGS is outperformed by SDCA and SymSGD, I feel we should not call this class `LogisticRegressionTrainer`. A suggested solution is to prepend `Lbfgs` to this class' name.

### PR DESCRIPTION
**Pull request by wschin**
Fix #3016 by renaming `LogisticRegressionBinaryTrainer` to `LbfgsLogisticRegressionTrainer`. Note that for multiclass case, we have `LbfgsMaximumEntropyTrainer`. In addition, as [SDCA (aka dual coordinate descent methods) outperforms L-BFGS](https://www.csie.ntu.edu.tw/~cjlin/papers/maxent_dual.pdf) when training logistic regression models, we should not make L-BFGS looks like the default trainer of logistic regression model.

**[This link](https://github.com/dotnet/machinelearning/issues/3016#issuecomment-476369026) contains our the conclusion of those new names.**

### CODE REVIEW

File: src/Microsoft.ML.StaticPipe/LbfgsStatic.cs [hunk 1]
```diff
@@ -9,15 +9,15 @@
...
 namespace Microsoft.ML.StaticPipe
 {
-    using Options = LogisticRegressionBinaryTrainer.Options;
+    using Options = LbfgsLogisticRegressionTrainer.Options;
 
     /// <summary>
     /// Binary Classification trainer estimators.
     /// </summary>
-    public static class LbfgsBinaryClassificationStaticExtensions
+    public static class LbfgsBinaryExtensions
```
Comment (artidoro) [inline src/Microsoft.ML.StaticPipe/LbfgsStatic.cs]: >LbfgsBinaryExtensions [](start = 24, length = 21)

I think these are just static extensions, if possible could you keep static in the name of the class?

**Comment by yaeldekel** [comment]
>         [TlcModule.EntryPoint(Name = "Trainers.LogisticRegressionBinaryClassifier",

Should we update the name of the entry point as well?

---
Refers to: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs:407 in ba22e12. [](commit_id = ba22e1265508967b70815118ca485a8ddc542de2, deletion_comment = False)

**Comment by wschin** [comment]
>         [TlcModule.EntryPoint(Name = "Trainers.LogisticRegressionBinaryClassifier",

No for BC.

---
In reply to: [474926238](https://github.com/dotnet/machinelearning/pull/3034#issuecomment-474926238) [](ancestors = 474926238)

---
Refers to: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs:407 in ba22e12. [](commit_id = ba22e1265508967b70815118ca485a8ddc542de2, deletion_comment = False)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs [hunk 2]
```diff
@@ -15,21 +15,21 @@
...
-[assembly: LoadableClass(typeof(void), typeof(LogisticRegressionBinaryTrainer), null, typeof(SignatureEntryPointModule), LogisticRegressionBinaryTrainer.LoadNameValue)]
+[assembly: LoadableClass(typeof(void), typeof(LbfgsLogisticRegressionTrainer), null, typeof(SignatureEntryPointModule), LbfgsLogisticRegressionTrainer.LoadNameValue)]
 
 namespace Microsoft.ML.Trainers
 {
 
     /// <include file='doc.xml' path='doc/members/member[@name="LBFGS"]/*' />
     /// <include file='doc.xml' path='docs/members/example[@name="LogisticRegressionBinaryClassifier"]/*' />
-    public sealed partial class LogisticRegressionBinaryTrainer : LbfgsTrainerBase<LogisticRegressionBinaryTrainer.Options,
+    public sealed partial class LbfgsLogisticRegressionTrainer : LbfgsTrainerBase<LbfgsLogisticRegressionTrainer.Options,
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs]: >LbfgsLogisticRegressionTrainer [](start = 32, length = 30)

Can you call it `LbfgsBinaryTrainer`?

Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs]: It looks fine if we consider this trainer and its SDCA counterpart (they all solve LR). However, it will break the consistency between LBFGS trainers. Please take a look at Iteration 3.

---
In reply to: [267460936](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267460936) [](ancestors = 267460936)

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs]: @sfilipi has comment on your issue, and I share it as well.
Putting word `Regression` without `Binary`  in the trainer is confusing.
If I would saw name of this trainer I would assume it's part of regression task.
Which is not.


---
In reply to: [267475700](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267475700) [](ancestors = 267475700,267460936)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 3]
```diff
@@ -516,7 +516,7 @@ public IClassificationLoss CreateComponent(IHostEnvironment env)
         /// ]]>
         /// </format>
         /// </example>
-        public static LogisticRegressionBinaryTrainer LogisticRegression(this BinaryClassificationCatalog.BinaryClassificationTrainers catalog,
+        public static LbfgsLogisticRegressionTrainer LbfgsLogisticRegressio(this BinaryClassificationCatalog.BinaryClassificationTrainers catalog,
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: >LbfgsLogisticRegressio [](start = 53, length = 22)

you miss `n` in the end.
And I don't think this new verb any better than previous one.
More importantly I don't understand why you even changing this? We had @agoswami issue and PR regarding names, where we spend quite a lot of effort in attempt to figure out names, why you change it out of blue now?

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs (hunk 2 above)
Comment (sfilipi) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs]: yeah, given the target user base, IMO should do a one off for this one, and keep binary in the name. 

(also this feels like a classic academic vs engineering solution of  a problem :D )

---
In reply to: [267477762](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267477762) [](ancestors = 267477762,267475700,267460936)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: I don't think my changes violate his rule.

---
In reply to: [267478532](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267478532) [](ancestors = 267478532)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs]: It will make the API looks like `mlContext.BinaryClassification.LbfgsBinary(...)` so I switch to SDCA-style name `LbfgsCalibrated`.

---
In reply to: [267481155](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267481155) [](ancestors = 267481155,267477762,267475700,267460936)

File: docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs [hunk 4]
```diff
@@ -63,7 +63,7 @@ public static void Example()
                 .Append(ml.Transforms.Text.FeaturizeText("TextFeatures", "Text"))
                 .Append(ml.Transforms.Concatenate("Features", "TextFeatures", "age", "fnlwgt",
                     "education-num", "capital-gain", "capital-loss", "hours-per-week"))
-                .Append(ml.BinaryClassification.Trainers.LogisticRegression());
+                .Append(ml.BinaryClassification.Trainers.LbfgsCalibrated());
```
Comment (rogancarr) [inline docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: >LbfgsCalibrated [](start = 57, length = 15)

I don't think we should call it this. `LogisticRegression` is fine but `LbfgsCalibrated` is too esoteric.

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 3 above)
Comment (rogancarr) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: This PR makes me nervous so close to ship date. Let's get consensus in #3016 before we make the change.

---
In reply to: [267481247](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267481247) [](ancestors = 267481247,267478532)

File: docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs (hunk 4 above)
Comment (rogancarr) [reply docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: Plus it's not a calibrated linear model. It's fitting the to the logistic loss function.

Comment (wschin) [reply docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: As long as it returns `CalibratedModelParametersBase<LinearBinaryModelParameters, PlattCalibrator`, I feel `LbfgsCalibrated` is fine. SDCA is doing the same.

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LogisticRegression.cs]: > 
> 
> yeah, given the target user base, IMO should do a one off for this one, and keep binary in the name.
> 
> (also this feels like a classic academic vs engineering solution of a problem :D )
> 
> Also, IMO not all details need to be in the name. IMO we don't need to distingush that this is Lbfgs logistic regression through renaming. It can be in the documentations. shorter names are better...

There are several trainers returning the same model types. Only this one is called `LogisticRegression` and this one has been outperformed by other algorithms. Thus, I want to append `Lbfgs` to emphasize that 'this is not the only trainer for logistic regression`.

> 
> In reply to: [267477762](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267477762) [](ancestors = 267477762,267475700,267460936)

File: docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs (hunk 4 above)
Comment (rogancarr) [reply docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: Technically true, but wouldn't it be clearer from a user perspective to call it `LogisticRegression`? Everybody knows what that is. Behind the scenes, many packages solve LR with variants of L-BFGS (e.g. Spark), so I don't think it would be misleading to say that it's called `LogisticRegression`. We can put technical details like "Implemented with L-BFGS etc." in the docs.

Look at `FastTree`. We don't call that `CalibratedLambdaMART` ;)

---
In reply to: [267857743](https://github.com/dotnet/machinelearning/pull/3034#discussion_r267857743) [](ancestors = 267857743)

Comment (wschin) [reply docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: A problem here is that L-BFGS is not good for large-scale sparse data sets. SDCA in that case is usually much faster. If we call LBFGS-LogisticRegression just LogisticRegression, external users may view LBFGS as the default solver to all logistic regression problems.

File: docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs [hunk 5]
```diff
@@ -63,7 +63,7 @@ public static void Example()
                 .Append(ml.Transforms.Text.FeaturizeText("TextFeatures", "Text"))
                 .Append(ml.Transforms.Concatenate("Features", "TextFeatures", "age", "fnlwgt",
                     "education-num", "capital-gain", "capital-loss", "hours-per-week"))
-                .Append(ml.BinaryClassification.Trainers.LogisticRegression());
+                .Append(ml.BinaryClassification.Trainers.LbfgsLogisticRegression());
```
Comment (rogancarr) [inline docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: How do you feel about making the other calibrated linear trainers, like SDCA into `XyzLogisticRegression()`.

Comment (rogancarr) [reply docs/samples/Microsoft.ML.Samples/Dynamic/LogisticRegression.cs]: We can always add that at a later time.

**Comment by abgoswam** [comment]
Here is my understanding of how we arrived at naming convention of Trainers/ModelParameters

- we had couple of issues #2762 and #2938  discussing this, summarized in the comments :
  - https://github.com/dotnet/machinelearning/issues/2762#issuecomment-471845715
  - https://github.com/dotnet/machinelearning/issues/2938#issuecomment-474131883
- MulticlassLR was discussed, and finalized while fixing issue #2976


The PR proposes to **modify the API** as follows : 
- Renames several MLContext names  
  - `LogisticRegression` to `LbfgsLogisticRegression` 
  - `PoissonRegression` to `LbfgsPoissonRegression`
- Renames Class names
  - `LogisticRegressionBinaryTrainer` to `LbfgsLogisticRegressionTrainer`
 
Why do we think adding prefix "Lbfgs" in the name is a better alternative than what we have currently ?

@eerhardt

**Comment by eerhardt** [comment]
> Why do we think adding prefix "Lbfgs" in the name is a better alternative than what we have currently ? In fact to me it seems having 'Lbfgs' as prefix might throw users off

I believe @wschin answered this in the first comment:

> In addition, as SDCA (aka dual coordinate descent methods) outperforms L-BFGS when training logistic regression models, we should not make L-BFGS looks like the default trainer of logistic regression model.

It seems to me that is his exact intention here. Don't use this one when you want to do LR. Or at least, don't think this is the "good"/"default" one. We have a better one.

**Comment by rogancarr** [comment]
I think that it would also make sense to convert the binary `SDCA` trainer to be called `SdcaLogisticRegression` if we make this change to `Lbfgs`. That way, they both get the "LR Brand Name".

**Comment by abgoswam** [comment]
> In addition, as SDCA (aka dual coordinate descent methods) outperforms L-BFGS when training logistic regression models, we should not make L-BFGS looks like the default trainer of logistic regression model.

- The PR  proposes adding "LbfgsLogisticRegression" in API name itself to make it  concrete  that this  particular  API  uses  "Lbfgs" as the optimization algorithm.  Is that the correct approach ? 

- Are we sure we are using "LBFGS" as the optimizing algorithm ?  The internal repo  refers to this [paper](https://www.microsoft.com/en-us/research/publication/scalable-training-of-l1-regularized-log-linear-models/?from=http%3A%2F%2Fresearch.microsoft.com%2Fapps%2Fpubs%2Fdefault.aspx%3Fid%3D78900),  which leads me to believe  that what we use the the  optimization algo is  not LBFGS itself, but rather  one of its variants "OWN-QN"

- Scikit-learn [solves this](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) by adding parameter  called "solver" 

> solver : str, {‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’}, default: ‘liblinear’.
Algorithm to use in the optimization problem.

**Comment by wschin** [comment]
> 
> 
> > In addition, as SDCA (aka dual coordinate descent methods) outperforms L-BFGS when training logistic regression models, we should not make L-BFGS looks like the default trainer of logistic regression model.
> 
>     * The PR  proposes adding "LbfgsLogisticRegression" in API name itself to make it  concrete  that this  particular  API  uses  "Lbfgs" as the optimization algorithm.  Is that the correct approach ?
> 

LBFGS can mean LBFGS family algorithms.

>     * Are we sure we are using "LBFGS" as the optimizing algorithm ?  The internal repo  refers to this [paper](https://www.microsoft.com/en-us/research/publication/scalable-training-of-l1-regularized-log-linear-models/?from=http%3A%2F%2Fresearch.microsoft.com%2Fapps%2Fpubs%2Fdefault.aspx%3Fid%3D78900),  which leads me to believe that the optimization algo that ML.NET uses is  not LBFGS itself, but rather  one of its variants "OWN-QN". All the more reason to _not_ include Lbfgs in the name of the API itself
> 

It's a variant of LBFGS, as stated in your link.

>     * Scikit-learn [solves this](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) by adding parameter  called "solver"
> 
> 
> > solver : str, {‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’}, default: ‘liblinear’.
> > Algorithm to use in the optimization problem.

No. It's not necessary. L1-norm --> a variant of LBFGS, No L1-norm --> LBFGS.

**Comment by abgoswam** [comment]
Couple of notes after discussing with @wschin 

- Since ML.NET is type-safe, we cannot really  follow the same paradigm as Scikit-Learn's way of handling this (using the `solver` parameter)

- We can take inspiration from Spark.ML  to finilize the API  

  - Spark.ML package exposes just 1 API
    -  [`LogisticRegression`](https://spark.apache.org/docs/2.2.0/api/scala/index.html#org.apache.spark.ml.classification.LogisticRegression)  and clarifies in documentation it uses LBFGS / OWLQN 

  - Spark.Mllib package exposes 2 APIs
    -  [`LogisticRegressionWithLBFGS`](https://spark.apache.org/docs/2.2.0/api/scala/index.html#org.apache.spark.mllib.classification.LogisticRegressionWithLBFGS)  
    -  [`LogisticRegressionWithSGD`](https://spark.apache.org/docs/2.2.0/api/scala/index.html#org.apache.spark.mllib.classification.LogisticRegressionWithSGD)  

- SDCA has other subtelities to it e.g.  supports SVM loss,  calibration/non-calibration etc.  We can keep the SDCA API as is.

File: src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs [hunk 6]
```diff
@@ -19,20 +19,20 @@
 using Microsoft.ML.Trainers;
 using Microsoft.ML.Transforms;
 
-[assembly: LoadableClass(typeof(SymbolicSgdTrainer), typeof(SymbolicSgdTrainer.Options),
+[assembly: LoadableClass(typeof(SymbolicSgdLogisticRegressionBinaryTrainer), typeof(SymbolicSgdLogisticRegressionBinaryTrainer.Options),
```
Comment (rogancarr) [inline src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs]: >SymbolicSgdLogisticRegressionBinaryTrainer [](start = 32, length = 42)

`LogisticRegressionBinaryTrainer` => `LbfgsLogisticRegressionTrainer`. Shall `SymbolicSgdBinaryTrainer` => `SymbolicSgdLogisticRegressionTrainer` instead of `SymbolicSgdLogisticRegressionBinaryTrainer`? Right now, the namings don't line up.

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 7]
```diff
@@ -181,7 +181,7 @@ public static class StandardTrainersCatalog
         }
 
         /// <summary>
-        /// Predict a target using a linear classification model trained with <see cref="SdcaCalibratedBinaryTrainer"/>.
+        /// Predict a target using a linear classification model trained with <see cref="SdcaLogisticRegressionBinaryTrainer"/>.
```
Comment (rogancarr) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: >SdcaLogisticRegressionBinaryTrainer [](start = 89, length = 35)

Similar to `SymSgd`, now `Sdca` has `LogisticRegression` and `Binary`.

File: src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs (hunk 6 above)
Comment (abgoswam) [reply src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs]: @rogancarr..could you cross-check ? To me the *Class* names do match up `LbfgsLogisticRegressionBinaryTrainer` and `SymbolicSgdLogisticRegressionBinaryTrainer`

---
In reply to: [268859710](https://github.com/dotnet/machinelearning/pull/3034#discussion_r268859710) [](ancestors = 268859710)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 7 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: Yes, adding both of `LogisticRegression` and `Binary` to trainer classes was our decision. For API, we only append `LogisticRegression` because `Binary` naturally comes from their context.

---
In reply to: [268859905](https://github.com/dotnet/machinelearning/pull/3034#discussion_r268859905) [](ancestors = 268859905)

File: src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs (hunk 6 above)
Comment (wschin) [reply src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs]: Yeah. Our conclusion was having `LR` and `Binary` for trainer classes and only `LR` for APIs.

---
In reply to: [268865148](https://github.com/dotnet/machinelearning/pull/3034#discussion_r268865148) [](ancestors = 268865148,268859710)

Comment (rogancarr) [reply src/Microsoft.ML.Mkl.Components/SymSgdClassificationTrainer.cs]: Got it. I was mixing up catalogs & classes.
