### PR TITLE
AutoML aggregate exception

### LINKED ISSUE #5612: How to get around the exception caused because of #5506 fix?
Using the AutoML version 0.17.2 and 0.17.4, I get a few exceptions during SdcaRegression (simillar to #4363)
However, a new behaviour using 0.17.4, I get the AggregateException (changes because of #5445).

Exception during AutoML iteration: System.InvalidOperationException: The weights/bias contain invalid values (NaN or Infinite). Potential causes: high learning rates, no normalization, high initial weights, etc.
   at Microsoft.ML.Trainers.OnlineLinearTrainer`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 
metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Operation was canceled.) (Operation was canceled.) (Operation was canceled.) (Operation was canceled.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at Microsoft.ML.Trainers.FastTree.ThreadTaskManager.ThreadTask.RunTask()
   at Microsoft.ML.Trainers.FastTree.LeastSquaresRegressionTreeLearner.FindBestSplitOfRoot(Double[] targets)
   at Microsoft.ML.Trainers.FastTree.LeastSquaresRegressionTreeLearner.FitTargets(IChannel ch, Boolean[] activeFeatures, Double[] targets)
   at Microsoft.ML.Trainers.FastTree.RandomForestLeastSquaresTreeLearner.FitTargets(IChannel ch, Boolean[] activeFeatures, Double[] weightedtargets, Double[] targets, Double[] weights)
   at Microsoft.ML.Trainers.FastTree.RandomForestOptimizer.TrainingIteration(IChannel ch, Boolean[] activeFeatures)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.Train(IChannel ch)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.TrainCore(IChannel ch)
   at Microsoft.ML.Trainers.FastTree.FastForestRegressionTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.AutoML.SmacSweeper.FitModel(IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.SmacSweeper.ProposeSweeps(Int32 maxSweeps, IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.PipelineSuggester.SampleHyperparameters(MLContext context, SuggestedTrainer trainer, IEnumerable`1 history, Boolean isMaximizingMetric, IChannel logger)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IChannel logger, IEnumerable`1 trainerAllowList)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteTrainValidate(IDataView trainData, ColumnInformation columnInfo, IDataView validationData, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, IDataView validationData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, IDataView validationData, String labelColumnName, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at AutoMLApp.Experiment2Template.Train() in C:\Users\abbas\OneDrive\Documents\WorkingProgress\MLStcokMarketPrediction\AutoMLApp\Class1.cs:line 446
   at AutoMLApp.MlModelTemplate.BuildModel() in C:\Users\abbas\OneDrive\Documents\WorkingProgress\MLStcokMarketPrediction\AutoMLApp\Class1.cs:line 363
   at AutoMLApp.MlExperimentsFactory.Experiment2Tasks(Kind kind, OutputLabels op, BinaryClassificationMetric optimizingMetric, List`1 trainers) in C:\Users\abbas\OneDrive\Documents\WorkingProgress\MLStcokMarketPrediction\AutoMLApp\Class1.cs:line 177
   at AutoMLApp.MlExperimentsFactory.<>c__DisplayClass30_1.<GetTask>b__1() in C:\Users\abbas\OneDrive\Documents\WorkingProgress\MLStcokMarketPrediction\AutoMLApp\Class1.cs:line 135
   at AutoMLApp.MlExperimentsFactory.StartNew(String ticker, ExperimentElementCollection expColl, PredictionTestDataElement testData) in C:\Users\abbas\OneDrive\Documents\WorkingProgress\MLStcokMarketPrediction\AutoMLApp\Class1.cs:line 109
   at AutoMLApp.Program.Main(String[] args) in C:\Users\abbas\OneDrive\Documents\WorkingProgress\MLStcokMarketPrediction\AutoMLApp\Program.cs:line 31

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
OperationCanceledException: Operation was canceled.

### PR DESCRIPTION
**Pull request by michaelgsharp**
Fixes #5612. In AutoML when the max experiment time is up a cancellation token is used to cancel any runs in progress. We catch the `OperationCanceledException` so that it doesn't prevent the finished models from being returned. However for some trainers, like FastTree, because training is done in parallel it can throw multiple `OperationCancelledExceptions` grouped together in an `AggregateException`. This was missing the original `catch` block and so was causing no results to be returned. This PR adds in another check for the `AggregateException` where all inner exceptions are of type `OperationCancelledException`, and treats it the same was as a plain `OperationCancelledException`.

I was not sure how to really add tests for this, It was brought up by a user and you _can_ repro it locally though its not consistent. If any of you have ideas for good tests let me know.

### CODE REVIEW

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 1]
```diff
@@ -196,6 +196,22 @@ public IList<TRunDetail> Execute()
...
+                catch (AggregateException e)
+                {
+                    // This exception is thrown when the IHost/MLContext of the trainer is canceled due to
+                    // reaching maximum experiment time. Simply catch this exception and return finished
+                    // iteration results. For some trainers, Like FastTree, because training is done in parallel
+                    // in can throw multiple OperationCancelledExceptions. This causes them to be returned as an
+                    // AggregateException and misses the first catch block. This is to handle that case.
+                    if (e.InnerExceptions.All( exception => exception is OperationCanceledException))
+                    {
+                        _logger.Warning("OperationCanceledException has been caught after maximum experiment time" +
```
Comment (eerhardt) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:208]: (nit) pull the message out so it doesn't need to be duplicated with the above.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 2]
```diff
@@ -196,6 +196,22 @@ public IList<TRunDetail> Execute()
...
+                        "was reached, and the running MLContext was stopped. Details: {0}", e.Message);
+                        return iterationResults;
+                    }
+
+                    Console.WriteLine(e.Message);
```
Comment (eerhardt) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:213]: I don't think we should be writing to the console in a library. Instead I think we should just

```suggestion
                    throw;
```

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 3]
```diff
@@ -196,6 +196,22 @@ public IList<TRunDetail> Execute()
                         "was reached, and the running MLContext was stopped. Details: {0}", e.Message);
                     return iterationResults;
                 }
+                catch (AggregateException e)
+                {
+                    // This exception is thrown when the IHost/MLContext of the trainer is canceled due to
+                    // reaching maximum experiment time. Simply catch this exception and return finished
+                    // iteration results. For some trainers, Like FastTree, because training is done in parallel
```
Comment (eerhardt) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:203]:
```suggestion
                    // iteration results. For some trainers, like FastTree, because training is done in parallel
```

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 2 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:213]: Good catch. That was left over from my debugging.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 4]
```diff
@@ -196,6 +196,22 @@ public IList<TRunDetail> Execute()
...
                     return iterationResults;
                 }
+                catch (AggregateException e)
+                {
+                    // This exception is thrown when the IHost/MLContext of the trainer is canceled due to
+                    // reaching maximum experiment time. Simply catch this exception and return finished
+                    // iteration results. For some trainers, like FastTree, because training is done in parallel
+                    // in can throw multiple OperationCancelledExceptions. This causes them to be returned as an
+                    // AggregateException and misses the first catch block. This is to handle that case.
+                    if (e.InnerExceptions.All( exception => exception is OperationCanceledException))
```
Comment (tarekgh) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:206]: >e.InnerExceptions.All( exception => exception is OperationCanceledException [](start = 24, length = 75)

Is it possible to get a mix of exception in the list? I mean some be OperationCanceledException and some be other exceptions? if so, should change `All` to `Any`?

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:206]: nit: also spacing
```suggestion
                    if (e.InnerExceptions.Any(exception => exception is OperationCanceledException))
```

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 5]
```diff
@@ -196,6 +196,22 @@ public IList<TRunDetail> Execute()
...
+                        _logger.Warning("OperationCanceledException has been caught after maximum experiment time" +
+                        "was reached, and the running MLContext was stopped. Details: {0}", e.Message);
+                        return iterationResults;
+                    }
+
+                    throw;
+                }
             } while (_history.Count < _experimentSettings.MaxModels &&
                     !_experimentSettings.CancellationToken.IsCancellationRequested &&
                     !_experimentTimerExpired);
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:217]: ### Method of passing log messages
In a related (non-filed) issue, to support the the ability to cancel runs, we needed a separate context for the child runs, and we pass the log messages from the child to parent. 

Current method of passing the messages is imperfect.

**Current returned log format:**
`"[Source=AutoML, Kind=Trace] [Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 3954"`

This duplicates the header on the messages (`[Source=AutoML, Kind=Trace]` and `[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace]`),  and makes it difficult to filter/select to the wanted log lines.

**Correct format:**
`"[Source=AutoML; ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 3954"`

This single header then lets you filter on the log line properties (e.g. `e.Source == "xyz"`) instead of its free text.

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:217]: I logged this as a separate issue, since I'm not sure it'll be fixed while you're working on similar code here.

https://github.com/dotnet/machinelearning/issues/5632

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 6]
```diff
@@ -196,6 +196,22 @@ public IList<TRunDetail> Execute()
...
+                    {
+                        _logger.Warning("OperationCanceledException has been caught after maximum experiment time" +
+                        "was reached, and the running MLContext was stopped. Details: {0}", e.Message);
+                        return iterationResults;
+                    }
+
+                    throw;
+                }
             } while (_history.Count < _experimentSettings.MaxModels &&
                     !_experimentSettings.CancellationToken.IsCancellationRequested &&
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:216]: > I was not sure how to really add tests for this, It was brought up by a user and you can repro it locally though its not consistent. If any of you have ideas for good tests let me know.

To add a unit test focusing on `OperationCanceledException`, you could set the AutoML setting to use only FastTree:
```c#
var experimentSettings = new RegressionExperimentSettings { MaxExperimentTimeInSeconds = 1 };
experimentSettings.Trainers.Clear();
experimentSettings.Trainers.Add(RegressionTrainer.FastTree);
```

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 4 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:206]: I am not sure. Originally we weren't catching any errors there, then that was changed to only catch the cancelled exception. I am trying to keep the same behavior, just accounting for the cases when multiple cancelled exception are thrown so its an aggregate exception. If you think Any would be better I am happy to change it, that is just a behavior change and I'm not sure if we want that or not.

@JakeRadMSFT thoughts? @justinormont thoughts?

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 6 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:216]: I have tried that, but it only throws this exception in 1 specific method and this wasn't a stable repro. Not stable enough to try and have a consistent test for it anyways.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 5 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:217]: This doesn't seem like something I can change in this location though is it?

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 1 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs]: Pulled out to private readonly variable.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 4 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:209]: I think it should be all because that keeps the current behavior of only catching the OperationCancelled behavior. I'm happy to change it if we think it should be Any though.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 6 above)
Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:218]: Agreed. After discussing, even restricting to only FastTree will not make for a stable unit test.

If the timeout occurs in certain steps of FastTree, `AggregateException` is thrown; while at other steps, `OperationCanceledException` is thrown.

Comment (ericstj) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:218]: Could you force it with a test-specific Trainer, or set of trainers?

Comment (michaelgsharp) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:218]: I tried that. The problem is that there is only 1 specific place that causes this issue when a timeout occurs, and I haven't found a way to get it to repro consistently without modifying the method to always throw there.

Comment (ericstj) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:218]: I was thinking more along the lines of a test-only mock trainer.  Ignore if we don't already have a framework / pattern for this, that'd be more of a future-looking test strategy piece of feedback.

**Review by ericstj — APPROVED** [review]
