### PR TITLE
Code generate TextLoader API and enhance it with convenience API.

### LINKED ISSUE #15: Need to support more types than string and float
_From @eerhardt on Apr 12, 2018, 6:52 AM PDT_

See code in `machinelearning/src/Microsoft.MachineLearning.EntryPoints/TextLoader.cs`

```
	private string TypeToName(Type type) 
	{ 
	if (type == typeof(string)) 
	return "TX"; 
	else if (type == typeof(float) || type == typeof(double)) 
	return "R4"; 
	else 
	throw new Exception("Type not implemented or supported."); //Add more types. 
	} 
```
(Refers to Lines 70 to 78 in 6e74d72)

We should fill all supported types out and add tests.

### PR DESCRIPTION
**Pull request by codemzs**
*Code generate support for IDataLoader 
*Make TextLoader API code generated so that it's at functional parity with the text loader in the ML.Net infrastructure.
*Move TextLoader API under Microsoft.ML.Data namespace
*Add convenience TextLoader API.
*Add error checking for invalid loader arguments such as ordinal, column names.
*Update baselines.
*Update samples with new loader API and backward compatibility with old loader API.

[*ADDRESS COMMENTS FROM PR# 38*](https://github.com/dotnet/machinelearning/pull/38)
fixes #15

### CODE REVIEW

File: src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs [hunk 1]
```diff
@@ -27,13 +27,25 @@ public sealed class Input
             public string CustomSchema = null;
         }
 
+        [TlcModule.EntryPointKind(typeof(ILearningPipelineLoader))]
+        public sealed class LoaderInput
+        {
+            [Argument(ArgumentType.Required, ShortName = "data", HelpText = "Location of the input file", SortOrder = 1)]
+            public IFileHandle InputFile;
+
+            [Argument(ArgumentType.Required, ShortName = "args", HelpText = "Arguments", SortOrder = 1)]
```
Comment (TomFinley) [inline src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs]: >1 [](start = 101, length = 1)

`SortOrder` is the same here.

File: src/Microsoft.ML.Core/Data/DataKind.cs [hunk 2]
```diff
@@ -205,7 +205,7 @@ public static bool TryGetDataKind(this Type type, out DataKind kind)
                 kind = DataKind.R4;
             else if (type == typeof(Double))
                 kind = DataKind.R8;
-            else if (type == typeof(DvText))
+            else if (type == typeof(DvText) || type == typeof(string))
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/DataKind.cs]: This is inappropriate. Actually the below `bool` below is wrong as well.

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs [hunk 3]
```diff
@@ -294,9 +294,12 @@ public class ArgumentsCore
                 ShortName = "size")]
             public int? InputSize;
 
-            [Argument(ArgumentType.AtMostOnce, HelpText = "Source column separator. Options: tab, space, comma, single character", ShortName = "sep")]
+            [Argument(ArgumentType.AtMostOnce, Visibility = ArgumentAttribute.VisibilityType.CmdLineOnly, HelpText = "Source column separator. Options: tab, space, comma, single character", ShortName = "sep")]
             public string Separator = "tab";
 
+            [Argument(ArgumentType.AtMostOnce, Visibility = ArgumentAttribute.VisibilityType.EntryPointsOnly, HelpText = "Source column separator. Option: single character ONLY", ShortName = "del")]
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: >Option: single character ONLY [](start = 147, length = 29)

I think the fact that it's a single character is implied by the fact that the argument is of type `char`. We don't usually clarify that non-array arguments can only have a single value specified, since that information is part of the type anyway.

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs [hunk 4]
```diff
@@ -1005,26 +1008,32 @@ public TextLoader(IHostEnvironment env, Arguments args, IMultiStreamSource files
                 _inputSize = SrcLim - 1;
 
             _host.CheckNonEmpty(args.Separator, nameof(args.Separator), "Must specify a separator");
-            string sep = args.Separator.ToLowerInvariant();
+            _host.CheckNonEmpty(args.Delimiter.ToString(), nameof(args.Delimiter), "Must specify a delimeter");
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: >args.Delimiter.ToString(), [](start = 32, length = 26)

What is the purpose of this check?

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs [hunk 5]
```diff
@@ -1005,26 +1008,32 @@ public TextLoader(IHostEnvironment env, Arguments args, IMultiStreamSource files
...
 
-            if (sep == ",")
-                _separators = new char[] { ',' };
+            if (args.Delimiter != '\t')
+                _separators = new char[] { args.Delimiter };
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: Maybe comment on the code how this relies on the fact that the default `arg.Separator` is `"tab"`, since to a reader this will look odd.

File: src/Microsoft.ML.PipelineInference/Microsoft.ML.PipelineInference.csproj [hunk 6]
```diff
@@ -7,6 +7,10 @@
     <DefineConstants>CORECLR</DefineConstants>
   </PropertyGroup>
 
+  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
+    <NoWarn>;1591;0618</NoWarn>
+  </PropertyGroup>
```
Comment (TomFinley) [inline src/Microsoft.ML.PipelineInference/Microsoft.ML.PipelineInference.csproj]: Could we clarify this? What warnings are these, and what is the relationship to your change?

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs (hunk 3 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: Though it would be nice if this argument was as capable as `Separator`, which can support multiple delimiters.

---
In reply to: [188001984](https://github.com/dotnet/machinelearning/pull/142#discussion_r188001984) [](ancestors = 188001984)

Comment (TomFinley) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: >Argument [](start = 13, length = 8)

This is a little unfortunate... on the one hand we have `Separator`. On the other hand we have `Delimiter`. I know you're doing this to avoid a name collision, but it would be nice if, from the *user's* perspective, the same concept had the same name in API usage and command line usage.

I think the `Name` attribute on `Argument` exists for this purpose. You can name the field whatever (maybe `Delimiter` could instead be `SeparatorChar`, or `SeparatorChars` if you fix it to be `char[]` instead). Then you can use `Name = nameof(Separator)` to make sure it has the same name in command line usage. The shortname I hope can I think be consistent between the two as well.

File: src/Microsoft.ML.Core/Data/DataKind.cs (hunk 2 above)
Comment (TomFinley) [reply src/Microsoft.ML.Core/Data/DataKind.cs]: There's another utility function I mentioned in the other code review, `GetDataType`, in the `ModuleArgs.cs` that has this more "informal" mapping. But assuredly the core definitions of `IDataView` and its supporting type structures are not the place to have this sort of stuff. :D

---
In reply to: [188000280](https://github.com/dotnet/machinelearning/pull/142#discussion_r188000280) [](ancestors = 188000280)

File: test/Microsoft.ML.Tests/TextLoaderTests.cs [hunk 7]
```diff
@@ -26,11 +27,11 @@ public void ConstructorDoesntThrow()
         {
             Assert.NotNull(new TextLoader<Input>("fakeFile.txt"));
             Assert.NotNull(new TextLoader<Input>("fakeFile.txt", useHeader: true));
-            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", separator: "tab"));
-            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", useHeader: false, separator: "tab"));
-            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", useHeader: false, separator: "tab", false, false));
-            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", useHeader: false, separator: "tab", supportSparse: false));
-            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", useHeader: false, separator: "tab", allowQuotedStrings: false));
+            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", delimeter: ','));
+            Assert.NotNull(new TextLoader<Input>("fakeFile.txt", useHeader: false, delimeter: ','));
```
Comment (TomFinley) [inline test/Microsoft.ML.Tests/TextLoaderTests.cs]: >',' [](start = 94, length = 3)

I'm not sure it matters given the nature of this test, but was there any particular reason to shift from `tab` to `,`?

Given how you've made `\t` an exceptional case in the constructor, might want to do both.

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs (hunk 3 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: When you shift to multiple delimiters, take the same care as is taken with `Separator` to ensure uniqueness, etc.

---
In reply to: [188006909](https://github.com/dotnet/machinelearning/pull/142#discussion_r188006909) [](ancestors = 188006909,188001984)

File: test/Microsoft.ML.Predictor.Tests/Microsoft.ML.Predictor.Tests.csproj [hunk 8]
```diff
@@ -5,6 +5,7 @@
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
     <PlatformTarget>AnyCPU</PlatformTarget>
+    <NoWarn>1701;1702;1705;0618</NoWarn>
```
Comment (TomFinley) [inline test/Microsoft.ML.Predictor.Tests/Microsoft.ML.Predictor.Tests.csproj]: Perhaps if the warning really is inappropriate in one very specific case, we could mark the very specific case rather than saying, "forevermore we will never, under any circumstances, be aware when this warning is generated."

File: test/Microsoft.ML.TestFramework/ModelHelper.cs [hunk 9]
```diff
@@ -40,24 +41,187 @@ public static void WriteKcHousePriceModel(string dataPath, Stream stream)
...
+                Arguments = new TextLoaderArguments
+                {
+                    Delimiter = ',',
+                    HasHeader = true,
+                    Column = new[]
+                    {
+                        new TextLoaderColumn()
+                        {
+                            Name = "Id",
+                            Source = new [] { new TextLoaderRange() { Min = 0, Max = 0} },
```
Comment (TomFinley) [inline test/Microsoft.ML.TestFramework/ModelHelper.cs]: >  [](start = 40, length = 1)

Maybe VS could format the file to clean up thse whitespace issues, I think default VS formatting is `new[]` not `new []`.

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+                var name = mappingAttr.Name ?? field.Name;
+                if (name.Any(c => !Char.IsLetterOrDigit(c)))
+                    throw Contracts.Except($"{name} is not alphanumeric.");
+
+                DataKind dk;
+                (field.FieldType.IsArray ? field.FieldType.GetElementType() : field.FieldType).TryGetDataKind(out dk);
+                var col = Runtime.Data.TextLoader.Column.Parse(
+                    $"{name}:" +
+                    $"{dk.ToString()}:" +
+                    $"{mappingAttr.Ordinal}"
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: This is unnecessary. We only needed to parse out `Ordinal`. We could use `TextLoader.Range(Ordinal)` for that.

Alternately, we could exploit the fact that we now *have* a range type defined, and use that instead of making our users learn the mini-language.

Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Still a big improvement over the old system of course.

---
In reply to: [188021126](https://github.com/dotnet/machinelearning/pull/142#discussion_r188021126) [](ancestors = 188021126)

File: src/Microsoft.ML/CSharpApi.cs [hunk 11]
```diff
@@ -1236,6 +1248,39 @@ public void Add(Microsoft.ML.Transforms.WordTokenizer input, Microsoft.ML.Transf
...
         }
     }
+    namespace Data
+    {
+
+        /// <summary>
+        /// Import a dataset from a text file
+        /// </summary>
+        [Obsolete("Use TextLoader instead.")]
+        public sealed partial class CustomTextLoader
```
Comment (TomFinley) [inline src/Microsoft.ML/CSharpApi.cs]: Nice

File: src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs [hunk 12]
```diff
@@ -27,13 +27,25 @@ public sealed class Input
...
+
         public sealed class Output
         {
             [TlcModule.Output(Desc = "The resulting data view", SortOrder = 1)]
             public IDataView Data;
         }
 
-        [TlcModule.EntryPoint(Name = "Data.TextLoader", Desc = "Import a dataset from a text file")]
+#pragma warning disable 0618
+        [Obsolete("Use TextLoader instead.", false)]
```
Comment (TomFinley) [inline src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs]: >, false [](start = 43, length = 7)

This is the default for the overload without it specified anyway, so it can be omitted.

File: src/Microsoft.ML/CSharpApi.cs [hunk 13]
```diff
@@ -1293,22 +1338,184 @@ public sealed class Output
...
+            /// </summary>
+            public bool Contiguous { get; set; } = true;
+
+        }
+
         /// <summary>
         /// Import a dataset from a text file
         /// </summary>
-        public sealed partial class TextLoader
+        public partial class TextLoader : Microsoft.ML.ILearningPipelineLoader
```
Comment (TomFinley) [inline src/Microsoft.ML/CSharpApi.cs]: >public partial [](start = 8, length = 14)

So why not sealed?

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 14]
```diff
@@ -0,0 +1,101 @@
...
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Reflection;
+using System.Text;
+using System.Text.RegularExpressions;
+
+namespace Microsoft.ML.Data
+{
+    public sealed class TextLoader<TInput> : TextLoader
```
[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Having read this, it looks like this "subclass"'s only job is to take the type and a few constructor arguments, and that's the beginning and end of what it is used for.

This is a fairly odd use of inheritance, one without parallel in our codebase. This ought to be structured differently, either as a static generic utility method on top of `TextLoader`, but to declare a new class just for that convenience is odd.

---
In reply to: [188032656](https://github.com/dotnet/machinelearning/pull/142#discussion_r188032656) [](ancestors = 188032656)

File: src/Microsoft.ML.Core/EntryPoints/ModuleCatalog.cs [hunk 15]
```diff
@@ -40,6 +40,7 @@ public sealed class ModuleCatalog
         /// </summary>
         public sealed class EntryPointInfo
         {
+            public readonly bool NoSeal;
             public readonly string Name;
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/EntryPoints/ModuleCatalog.cs]: Let's revert this change of `NoSeal`. (The other change, the `ObsoleteAttribute` change is good, so please don't revert the whole file.)

Firstly, there's the point as made elsewhere that inheritance wasn't the right way to solve that problem, but there's a larger point...

The `EntryPointAttribute` is a description *of the component*. You wanted that class to be unsealed specifically because you had an idea of how to structure the C# API *specifically*. Setting aside the merits of that idea, or even supposing that it was a good idea, we should avoid putting things that are so extremely specific stuff in one environment (in this case, the code in `CSharpApiGenerator.cs`) in the entry-point definition meant to service everyone. Let's think about everything else in this info class... it's useful and necessary practically everywhere.  This is not the case with `NoSeal`.

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: It's also strange. Let's imagine that I have a `TextLoader<T>`. Is `T` used *anywhere*? Nope. Is `T` even **slightly relevant**? Not really -- by defining this to be an inheritance relationship, you are retaining the mutable properties that usual usage of `TextLoader` depends on. Which means, a user is free to change/ignore any information garnered from `T`. :)

---
In reply to: [188038035](https://github.com/dotnet/machinelearning/pull/142#discussion_r188038035) [](ancestors = 188038035,188032656)

File: src/Microsoft.ML/TextLoader.cs [hunk 16]
```diff
@@ -1,125 +0,0 @@
...
-using System.Text;
-
-namespace Microsoft.ML
-{
-    public class TextLoader<TInput> : ILearningPipelineLoader
-    {
-        private string _inputFilePath;
-        private string CustomSchema;
-        private Data.TextLoader ImportTextInput;
-
```
Comment (TomFinley) [inline src/Microsoft.ML/TextLoader.cs]: I'm not a fan of this old code, but it had the benefit that `TInput` meant something. Now we're doing inheritance, it means nothing. If you want to generate a `TextLoader`, make a method to generate a text loader.

File: src/Microsoft.ML/CSharpApi.cs (hunk 13 above)
Comment (TomFinley) [reply src/Microsoft.ML/CSharpApi.cs]: Ah I see. Because of that other issue. Reseal, maybe make another part of the partial class to introduce a `Create<TInput>` convenience method that returns a `TextLoader`.

---
In reply to: [188022924](https://github.com/dotnet/machinelearning/pull/142#discussion_r188022924) [](ancestors = 188022924)

File: src/Microsoft.ML.PipelineInference/Microsoft.ML.PipelineInference.csproj (hunk 6 above)
Comment (codemzs) [reply src/Microsoft.ML.PipelineInference/Microsoft.ML.PipelineInference.csproj]: I had added 0618 but now I have removed it and applied to code sections.

---
In reply to: [188006377](https://github.com/dotnet/machinelearning/pull/142#discussion_r188006377) [](ancestors = 188006377)

File: test/Microsoft.ML.TestFramework/ModelHelper.cs (hunk 9 above)
Comment (codemzs) [reply test/Microsoft.ML.TestFramework/ModelHelper.cs]: I tried ctrl-k-d but still there is space.

---
In reply to: [188013046](https://github.com/dotnet/machinelearning/pull/142#discussion_r188013046) [](ancestors = 188013046)

File: test/Microsoft.ML.Tests/TextLoaderTests.cs (hunk 7 above)
Comment (codemzs) [reply test/Microsoft.ML.Tests/TextLoaderTests.cs]: This was on an accident. Reverted back.

---
In reply to: [188011098](https://github.com/dotnet/machinelearning/pull/142#discussion_r188011098) [](ancestors = 188011098)

File: test/Microsoft.ML.TestFramework/ModelHelper.cs (hunk 9 above)
Comment (TomFinley) [reply test/Microsoft.ML.TestFramework/ModelHelper.cs]: Ah. How strange. Oh well.

---
In reply to: [188121093](https://github.com/dotnet/machinelearning/pull/142#discussion_r188121093) [](ancestors = 188121093,188013046)

File: src/Microsoft.ML/CSharpApi.cs [hunk 17]
```diff
@@ -1293,22 +1338,184 @@ public sealed class Output
...
+            /// Source index range(s) of the column
+            /// </summary>
+            public TextLoaderRange[] Source { get; set; }
+
+            /// <summary>
+            /// For a key column, this defines the range of values
+            /// </summary>
+            public KeyRange KeyRange { get; set; }
+
+        }
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/CSharpApi.cs]: I too wanted to do this as I converted test cases to use the code generated API and realized it was inconvenient to specify an ordinal twice when it could be done by specifying once.

---
In reply to: [188015114](https://github.com/dotnet/machinelearning/pull/142#discussion_r188015114) [](ancestors = 188015114)

File: src/Microsoft.ML/CSharpApi.cs [hunk 18]
```diff
@@ -1328,40 +1413,185 @@ public sealed class Output
...
-            public sealed class Output
-            {
-                /// <summary>
-                /// The resulting data view
-                /// </summary>
-                public Var<Microsoft.ML.Runtime.Data.IDataView> Data { get; set; } = new Var<Microsoft.ML.Runtime.Data.IDataView>();
+            /// <summary>
+            /// Source column separator.
+            /// </summary>
+            public char[] Separator { get; set; } = { '	' };
```
Comment (TomFinley) [inline src/Microsoft.ML/CSharpApi.cs]: >	 [](start = 55, length = 1)

Oh that's *nasty*... :) if we had declared `\n` in some other argument with type `char` we'd have parse errors. :D

Can we make the code generator robust to this? The offending line in `CSharpApiGenerator.cs` is 267. It should escape things that need escaping. (Tabs don't "need" escaping, but this looks silly.)

The idea would be, a simple utility method there that takes a character and, if necessary, escapes it. We can probably get away with anything likely to ever occur in any sort of default (`\t`, `\n`, `\r` come to mind), and just returning the char otherwise.

Previously it looks like only one other thing exposed `char` specifically, but there it was `w` so this was not evident.

File: src/Microsoft.ML/LearningPipeline.cs [hunk 19]
```diff
@@ -184,7 +184,7 @@ public LearningPipeline()
                 {
                     if (lastTransformModel != null)
                         transformModels.Insert(0, lastTransformModel);
-
+                        
                     var modelInput = new Transforms.ModelCombiner
```
Comment (TomFinley) [inline src/Microsoft.ML/LearningPipeline.cs]: Somehow lines with whitespace got inserted here semi-randomly.

File: src/Microsoft.ML/LearningPipeline.cs [hunk 20]
```diff
@@ -154,7 +154,7 @@ public LearningPipeline()
                     step = currentItem.ApplyStep(step, experiment);
                     if (step is ILearningPipelineDataStep dataStep && dataStep.Model != null)
                         transformModels.Add(dataStep.Model);
-                     
+
                     else if (step is ILearningPipelinePredictorStep predictorDataStep)
```
Comment (TomFinley) [inline src/Microsoft.ML/LearningPipeline.cs]: Another one

File: src/Microsoft.ML.Core/Utilities/Utils.cs [hunk 21]
```diff
@@ -1069,5 +1070,54 @@ public static string GetDescription(this Enum value)
...
+                kind = DataKind.BL;
+            else if (type == typeof(DvTimeSpan))
+                kind = DataKind.TS;
+            else if (type == typeof(DvDateTime))
+                kind = DataKind.DT;
+            else if (type == typeof(DvDateTimeZone))
+                kind = DataKind.DZ;
+            else if (type == typeof(UInt128))
+                kind = DataKind.UG;
+            else
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/Utils.cs]: Why is this here?

As near as I see the only usage is the `TextLoader` partial class you wrote, so why isn't this a private static method there?

`DvInt/Date/etc.` are wrappers for corresponding types except capable of expressing missing values. If you're mapping `bool` to `DvBool`, why are you not mapping `int` to `DvInt4`, etc.? Same with other types.

File: src/Microsoft.ML/LearningPipeline.cs (hunk 19 above)
Comment (codemzs) [reply src/Microsoft.ML/LearningPipeline.cs]: I think it during merge with master. My fault.

---
In reply to: [188484776](https://github.com/dotnet/machinelearning/pull/142#discussion_r188484776) [](ancestors = 188484776)

File: src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs [hunk 22]
```diff
@@ -177,6 +177,38 @@ public static string Capitalize(string s)
...
+                    case '\a':
+                        return "\\a";
+                    case '\b':
+                        return "\\b";
+                    case '\f':
+                        return "\\f";
+                    case '\v':
+                        return "\\v";
+                    default:
+                        Contracts.Assert(!Char.IsWhiteSpace(value));
```
Comment (TomFinley) [inline src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: And a space, how about that?

Comment (TomFinley) [reply src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: I'm not sure this is a useful assert.

---
In reply to: [188506120](https://github.com/dotnet/machinelearning/pull/142#discussion_r188506120) [](ancestors = 188506120)

File: src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs [hunk 23]
```diff
@@ -177,6 +177,38 @@ public static string Capitalize(string s)
                 return char.ToUpperInvariant(s[0]) + s.Substring(1);
             }
 
+            public static string GetCharValue(char value)
```
Comment (TomFinley) [inline src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: >public [](start = 12, length = 6)

Why is this method public?

File: src/Microsoft.ML.Core/Utilities/Utils.cs [hunk 24]
```diff
@@ -12,6 +12,7 @@
 using System.Text;
 using System.Text.RegularExpressions;
 using System.Threading;
+using Microsoft.ML.Runtime.Data;
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/Utils.cs]: And let's get rid of this, since we're reverting changes to this file.

File: src/Microsoft.ML/CSharpApi.cs [hunk 25]
```diff
@@ -1328,40 +1413,185 @@ public sealed class Output
...
-            public sealed class Output
-            {
-                /// <summary>
-                /// The resulting data view
-                /// </summary>
-                public Var<Microsoft.ML.Runtime.Data.IDataView> Data { get; set; } = new Var<Microsoft.ML.Runtime.Data.IDataView>();
+            /// <summary>
+            /// Source column separator.
+            /// </summary>
+            public char[] Separator { get; set; } = { '\t' };
```
Comment (TomFinley) [inline src/Microsoft.ML/CSharpApi.cs]: >\t [](start = 55, length = 2)

Nice... it's the little things. :D

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 26]
```diff
@@ -0,0 +1,152 @@
...
+using System.Text;
+using System.Text.RegularExpressions;
+
+namespace Microsoft.ML.Data
+{
+    public sealed partial class TextLoaderRange
+    {
+        [JsonIgnore]
+        public int Ordinal { get { return Ordinal; } set { Min = value; Max = value; } }
+    }
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: Let me point out a couple things. The `get` is interesting. The property recurses on itself, so I expect if anyone were to try to use it the result would be a stack overflow. :) I don't think a get is sensible for this property.

Since there is no sensible get possible for this property, this should probably not be a property at all, since set-only-getters I've noticed tend to engender confusion. So let's remove this property. Rather, define a constructor of `TextLoaderRange` that takes a single `int`.

Once you get rid of the property, you can I think omit `Newtonsoft.Json` (or wherever that `JsonIgnoreAttribute` is coming from, if not there).

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 27]
```diff
@@ -0,0 +1,152 @@
...
+
+    public sealed partial class TextLoader
+    {
+
+        /// <summary>
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: nit: You have a line right after the brace here.

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 28]
```diff
@@ -0,0 +1,152 @@
...
+
+            return this;
+        }
+
+        /// <summary>
+        /// Try to map a System.Type to a corresponding DataKind value.
+        /// </summary>
+        private static bool TryGetDataKind(Type type, out DataKind kind)
+        {
+            Contracts.CheckValueOrNull(type);
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: I consider this somewhat confusing, since by declaring this you're saying that the input type *might* be `null`, but as near as I can see from the one usage of this function, it cannot be. So why was it structured this way? Copy-paste, I guess, a deeper reason I don't appreciate?

If there is no other reason maybe make it assert (not check, since it's private) that it can't be null.

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 26 above)
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Wow! This was a huge miss on my end. Thanks for catching this. So nasty! :(

---
In reply to: [188708433](https://github.com/dotnet/machinelearning/pull/142#discussion_r188708433) [](ancestors = 188708433)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 29]
```diff
@@ -0,0 +1,160 @@
...
+        public TextLoaderRange(int ordinal)
+        {
+            Min = ordinal;
+            Max = ordinal;
+        }
+
+        public TextLoaderRange(int min, int max)
+        {
+            Min = min;
+            Max = max;
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: Similar for this.

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 30]
```diff
@@ -0,0 +1,160 @@
...
+    {
+        public TextLoaderRange()
+        {
+        }
+
+        public TextLoaderRange(int ordinal)
+        {
+            Min = ordinal;
+            Max = ordinal;
+        }
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: You may want to document for the users what the purpose of this is. It may not be obvious.

Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Something like, perhaps, `Convenience constructor for the scalar case. Min and Max are set to the single value ordinal." (Naturally use proper `<see` and `<paramref` cases.)

I'm writing that 

---
In reply to: [188720218](https://github.com/dotnet/machinelearning/pull/142#discussion_r188720218) [](ancestors = 188720218)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 29 above)
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Documentation I mean.

---
In reply to: [188720207](https://github.com/dotnet/machinelearning/pull/142#discussion_r188720207) [](ancestors = 188720207)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 31]
```diff
@@ -0,0 +1,160 @@
...
+
+            return this;
+        }
+
+        /// <summary>
+        /// Try to map a System.Type to a corresponding DataKind value.
+        /// </summary>
+        private static bool TryGetDataKind(Type type, out DataKind kind)
+        {
+            Contracts.Assert(type != null);
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: >Contracts.Assert(type != null); [](start = 12, length = 31)

Assertvalue...

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 32]
```diff
@@ -0,0 +1,160 @@
...
+            char separator = '\t', bool allowQuotedStrings = true,
+            bool supportSparse = true, bool trimWhitespace = false)
+        {
+            var fields = typeof(TInput).GetFields();
+            Arguments.Column = new TextLoaderColumn[fields.Length];
+            for (int index = 0; index < fields.Length; index++)
+            {
+                var field = fields[index];
+                var mappingAttr = field.GetCustomAttribute<ColumnAttribute>();
+                if (mappingAttr == null)
```
Comment (yaeldekel) [inline src/Microsoft.ML/Data/TextLoader.cs]: >mappingAttr [](start = 20, length = 11)

Do we want to throw here, or maybe just ignore?

File: src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs [hunk 33]
```diff
@@ -27,13 +27,25 @@ public sealed class Input
...
+
         public sealed class Output
         {
             [TlcModule.Output(Desc = "The resulting data view", SortOrder = 1)]
             public IDataView Data;
         }
 
-        [TlcModule.EntryPoint(Name = "Data.TextLoader", Desc = "Import a dataset from a text file")]
+#pragma warning disable 0618
+        [Obsolete("Use TextLoader instead.")]
```
Comment (yaeldekel) [inline src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs]: >Obsolete [](start = 9, length = 8)

Is this the right place to have this attribute?
If a user has code that calls Experiment.Add(new TextLoader() {...}) with the old API, won't that code break, since TextLoader will now have different fields?

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 34]
```diff
@@ -0,0 +1,160 @@
...
+
+        public TextLoaderRange(int ordinal)
+        {
+            Min = ordinal;
+            Max = ordinal;
+        }
+
+        public TextLoaderRange(int min, int max)
+        {
+            Min = min;
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Please refer to \src\microsoft.ml.data\dataloadsave\text\textloader.cs line 149 - isValid method

---
In reply to: [188737311](https://github.com/dotnet/machinelearning/pull/142#discussion_r188737311) [](ancestors = 188737311)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 35]
```diff
@@ -0,0 +1,160 @@
...
+
+namespace Microsoft.ML.Data
+{
+    public sealed partial class TextLoaderRange
+    {
+        public TextLoaderRange()
+        {
+        }
+
+        public TextLoaderRange(int ordinal)
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Please refer to \src\microsoft.ml.data\dataloadsave\text\textloader.cs line 149 - isValid method

---
In reply to: [188737039](https://github.com/dotnet/machinelearning/pull/142#discussion_r188737039) [](ancestors = 188737039)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 34 above)
[the remark this answers is not in the document]
Comment (veikkoeeva) [reply src/Microsoft.ML/Data/TextLoader.cs]: @codemzs It's https://github.com/dotnet/machinelearning/blob/c023727b76970ab913ec1ce38276508835c17bcf/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L149 I suppose. While there is this function, it would make sense to check invariants "on the spot" _also_ (if these cases really are not allowed). Now it's not possible to see this invariant here, locally, just by looking at this code and correspondginly have an error "on the spot" for erroneous case. It also creates a precedent to write code that is more brittle in that if something is changed "somebody else somewhere checks for the validity". It's very difficult to anyone outside of the project, or new to project, make any changes without reading a lot of code (which likely means it won't happen).

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 36]
```diff
@@ -0,0 +1,160 @@
...
+using Microsoft.ML.Runtime.Api;
+using Microsoft.ML.Runtime.Data;
+using System;
+using System.Linq;
+using System.Reflection;
+using System.Text.RegularExpressions;
+
+namespace Microsoft.ML.Data
+{
+    public sealed partial class TextLoaderRange
```
Comment (veikkoeeva) [inline src/Microsoft.ML/Data/TextLoader.cs]: Having `DebuggerDisplay` showing the ranges could be helpful here.

File: src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs [hunk 37]
```diff
@@ -177,6 +177,37 @@ public static string Capitalize(string s)
                 return char.ToUpperInvariant(s[0]) + s.Substring(1);
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: Thanks but I think this should be a change on its own that deals with the multi-cultural issue.

---
In reply to: [188742606](https://github.com/dotnet/machinelearning/pull/142#discussion_r188742606) [](ancestors = 188742606)

File: src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs [hunk 38]
```diff
@@ -177,6 +177,37 @@ public static string Capitalize(string s)
...
             }
 
+            private static string GetCharValue(char value)
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: It gets character value in GetValue function. Yes, it converts the character value to string.

---
In reply to: [188745409](https://github.com/dotnet/machinelearning/pull/142#discussion_r188745409) [](ancestors = 188745409)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 32 above)
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Can you please clarify?

---
In reply to: [188731983](https://github.com/dotnet/machinelearning/pull/142#discussion_r188731983) [](ancestors = 188731983)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 34 above)
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: I have added the checks for invariants here but I'm not sure if this is really needed because the checks are already performed by the same class since it has a partial implementation that calls into isValid method as I have previously pointed. 

---
In reply to: [188838661](https://github.com/dotnet/machinelearning/pull/142#discussion_r188838661) [](ancestors = 188838661)

File: src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs (hunk 33 above)
Comment (codemzs) [reply src/Microsoft.ML/Runtime/EntryPoints/ImportTextData.cs]: Yes, that is the whole point. We want to discourage people from using this API.

---
In reply to: [188734634](https://github.com/dotnet/machinelearning/pull/142#discussion_r188734634) [](ancestors = 188734634)

File: src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs (hunk 38 above)
[the remark this answers is not in the document]
Comment (veikkoeeva) [reply src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: I was unclear, though wontfixed, just to be extra clear, perhaps `WhitespaceCharToString` could be clearer? Now it takes `char` and returns "char value" the type being "string", which could take more time to parse mentally (considering what IntelliSense displays too).

[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Runtime/Internal/Tools/CSharpApiGenerator.cs]: It handles all characters not just whitespace.

---
In reply to: [188853623](https://github.com/dotnet/machinelearning/pull/142#discussion_r188853623) [](ancestors = 188853623)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 39]
```diff
@@ -0,0 +1,180 @@
...
+        /// Convenience constructor for the scalar case.
+        /// Min and Max are set to the single value ordinal.
+        /// When a given column spans only a single column in the
+        /// dataset.
+        /// <see cref="ML.Runtime.Data.TextLoader.Range"/>
+        /// </summary>
+        public TextLoaderRange(int ordinal)
+        {
+
+            Contracts.Assert(ordinal >= 0);
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: >Contracts.Assert(ordinal >= 0); [](start = 12, length = 31)

Not asserts! These are public facing methods.

Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: More detail: Asserts are debug only constructs, and we only use them to indicate what we *expect* is true -- e.g., verification of invariants in code. These should be `.CheckParam`, etc.

Checks with error messages are more appropriate here. I see your message to @veikko_e@hotmail.com 

---
In reply to: [189048133](https://github.com/dotnet/machinelearning/pull/142#discussion_r189048133) [](ancestors = 189048133)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 35 above)
[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Hi Zeeshan! Just reactivating, sorry. I'm not certain I agree. When we have the sort of thing when we're building up through use of property setting, then sure, there's an expectation that we can't *really* validate much until `Pipeline.Train` is called, since of course literally anything could change up till that time, and it's a bit awkward to try to communicate what checks should go in property setters *anyway*. (E.g., I might imagine being able to test that `Min` and `Max` are above 0, but I couldn't necessarily check that `Min <= Max` in a setter, since I have no idea when that occurs.)

However in this case, we are talking about an actual constructor. We should fail as soon as we are able to *reasonably* detect that something is wrong. We can't do it there, but we can do it here.

---
In reply to: [188836637](https://github.com/dotnet/machinelearning/pull/142#discussion_r188836637) [](ancestors = 188836637,188737039)

[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Just think about what a better experience is. Someone comes in, calls this constructor, builds a whole pipeline, does a bunch of stuff, does a lot of work, calls `Train` and *then* hits the error, or not.

---
In reply to: [189080344](https://github.com/dotnet/machinelearning/pull/142#discussion_r189080344) [](ancestors = 189080344,188836637,188737039)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 32 above)
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Ignoring doesn't quite work since you need to specify the ranges.

---
In reply to: [188844047](https://github.com/dotnet/machinelearning/pull/142#discussion_r188844047) [](ancestors = 188844047,188731983)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 40]
```diff
@@ -0,0 +1,180 @@
...
+{
+    public sealed partial class TextLoaderRange
+    {
+        public TextLoaderRange()
+        {
+        }
+
+        /// <summary>
+        /// Convenience constructor for the scalar case.
+        /// Min and Max are set to the single value ordinal.
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: >Min [](start = 12, length = 3)

`<see`, also `ordinal` should be in a `<paramref`.

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 41]
```diff
@@ -0,0 +1,180 @@
...
+        /// When a given column spans only a single column in the
+        /// dataset.
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: You're using two distinct meanings of the word column in one sentence. This is fairly confusing.

Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: This is not a sentence. It almost works if you were to append it to the *first* sentence, followed by a comma.

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 40 above)
Comment (veikkoeeva) [reply src/Microsoft.ML/Data/TextLoader.cs]: @TomFinley These rules could be enforced as errors too. Though the problem currently is that many of the interfaces aren't commented. I'm not sure if going in stages could be a viable alternative.

A good take on commenting: https://github.com/dotnet/orleans/issues/209#issuecomment-77937822.

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 41 above)
Comment (veikkoeeva) [reply src/Microsoft.ML/Data/TextLoader.cs]: I concur, as a non-native speaker, I'd go to read the code (and be slightly annoyed). :)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 40 above)
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Thanks, Veikko.

---
In reply to: [189102883](https://github.com/dotnet/machinelearning/pull/142#discussion_r189102883) [](ancestors = 189102883)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 41 above)
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Still not a sentence. Perhaps reading this summary comment aloud to yourself would help?

---
In reply to: [189083569](https://github.com/dotnet/machinelearning/pull/142#discussion_r189083569) [](ancestors = 189083569)

Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Oh OK... I see what went wrong here.

Append this third "sentence" to the first sentence followed by a comma.

By this I mean, I am **not** proposing the following transformation.

"I like to run. When the sun shines." => "I like to run. When the sun shines," because that's still not a sentence and its punctuation makes no sense.

I am proposing the following transformation.

"I like to run, when the sun shines."

---
In reply to: [189340150](https://github.com/dotnet/machinelearning/pull/142#discussion_r189340150) [](ancestors = 189340150,189083569)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 42]
```diff
@@ -0,0 +1,178 @@
...
+            Contracts.CheckParam(ordinal >= 0, nameof(ordinal));
+
+            Min = ordinal;
+            Max = ordinal;
+        }
+
+        /// <summary>
+        /// Convenience constructor for the vector case.
+        /// When a given column in the schema spans contiguous columns in the dataset,
+        /// <see cref="ML.Runtime.Data.TextLoader.Range"/>
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: ><see cref="ML.Runtime.Data.TextLoader.Range"/> [](start = 12, length = 46)

So, why are we having code in the public API reference classes in the runtime namespaces?

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 43]
```diff
@@ -0,0 +1,178 @@
...
+        /// </summary>
+        public TextLoaderRange(int min, int max)
+        {
+
+            Contracts.CheckParam(min >= 0, nameof(min));
+            Contracts.CheckParam(max >= 0, nameof(max));
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: Max should be >= than min. You also do not have any message at all for the user for what actually happened.

The `TextLoader` class is arguably one of the most important components in this API, wouldn't we say? If a user misuses it, and we throw an exception, we really ought to be clear.

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 40 above)
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: Thanks for adding the `<paramref`. Min and max still not in `<see`

---
In reply to: [189082232](https://github.com/dotnet/machinelearning/pull/142#discussion_r189082232) [](ancestors = 189082232)

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 44]
```diff
@@ -0,0 +1,178 @@
...
+            Min = ordinal;
+            Max = ordinal;
+        }
+
+        /// <summary>
+        /// Convenience constructor for the vector case.
+        /// When a given column in the schema spans contiguous columns in the dataset,
+        /// <see cref="ML.Runtime.Data.TextLoader.Range"/>
+        /// </summary>
+        public TextLoaderRange(int min, int max)
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: `<param` tags? Isn't it important to explain these?

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 45]
```diff
@@ -0,0 +1,160 @@
...
+        /// and distinguish empty values from missing values. When true, consecutive separators 
+        /// denote a missing value and an empty value is denoted by \"\". 
+        /// When false, consecutive separators denote an empty value.</param>
+        /// <param name="supportSparse">Whether the input may include sparse representations e.g. 
+        /// if one of the row contains "5 2:6 4:3" that's mean there are 5 columns all zero 
+        /// except for 3rd and 5th columns which have values 6 and 3</param>
+        /// <param name="trimWhitespace">Remove trailing whitespace from lines</param>
+        public TextLoader CreateFrom<TInput>(bool useHeader = false,
+            char separator = '\t', bool allowQuotedStrings = true,
+            bool supportSparse = true, bool trimWhitespace = false)
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: I think cultureinfo changes should be a change of its own. TrimeWhiteSpace is also the name used in the TextLoader.Arguments class.

---
In reply to: [188739739](https://github.com/dotnet/machinelearning/pull/142#discussion_r188739739) [](ancestors = 188739739)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 36 above)
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Can you please clarify the debugging scenario you are thinking about? If you are in the TextLoader you can inspect ranges by looking into the column class.

---
In reply to: [188839042](https://github.com/dotnet/machinelearning/pull/142#discussion_r188839042) [](ancestors = 188839042)

Comment (veikkoeeva) [reply src/Microsoft.ML/Data/TextLoader.cs]: I'm not sure if I understand the question. I'm thinking straight that the difference is this:
DebuggerDisplay

Where having the attribute is more pleasing. It also sets the tone of the codebase that one should apply aids where appropriate. So to speak, not to set a tone in which to leave things out if one can get away it by "doing something else", but be helpful on the spot.

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 46]
```diff
@@ -0,0 +1,179 @@
...
+        /// Convenience constructor for the vector case, when a given column 
+        /// in the schema spans contiguous columns in the dataset.
+        /// </summary>
+        /// <param name="min">Starting column index in the dataset.</param>
+        /// <param name="max">Ending column index in the dataset.</param>
+        public TextLoaderRange(int min, int max)
+        {
+
+            Contracts.CheckParam(min >= 0, nameof(min), "Cannot be negative number.");
+            Contracts.CheckParam(max >= min, nameof(max), $"Cannot be less than {nameof(min)}.");
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: >$"Cannot be less than {nameof(min)}." [](start = 58, length = 37)

Note that this `$` interpolation means this isn't a constant. Note however, that `"Cannot be less than " + nameof(min) + "."` would be a constant, and so we could use it in a `Check` error message.

File: src/Microsoft.ML/Data/TextLoader.cs [hunk 47]
```diff
@@ -0,0 +1,179 @@
...
+        /// <summary>
+        /// Convenience constructor for the vector case, when a given column 
+        /// in the schema spans contiguous columns in the dataset.
+        /// </summary>
+        /// <param name="min">Starting column index in the dataset.</param>
+        /// <param name="max">Ending column index in the dataset.</param>
+        public TextLoaderRange(int min, int max)
+        {
+
+            Contracts.CheckParam(min >= 0, nameof(min), "Cannot be negative number.");
```
Comment (TomFinley) [inline src/Microsoft.ML/Data/TextLoader.cs]: >Cannot be negative number. [](start = 57, length = 26)

Make consistent with the above "Cannot be **a** negative number."

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 36 above)
Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: I actually rather like this idea. `"Min = {Min}, Max = `{Max}`". Maybe also utilize the underlying method `TryUnparse` in some fashion in the corresponding `Runtime` class, but is a bit more idiosyncratic.

---
In reply to: [189518236](https://github.com/dotnet/machinelearning/pull/142#discussion_r189518236) [](ancestors = 189518236)

Comment (TomFinley) [reply src/Microsoft.ML/Data/TextLoader.cs]: While I was driving in I was thinking about this, and I like the idea, but I think we could possibly do something a bit more comprehensive than a one-off here. I have however added a new issue #194. where I outline an idea where perhaps we could actually generate this attribute for literally *everything* in `CSharpApi.cs`. It might actually be really easy to do... (That of course would be beyond the scope of this change.)

---
In reply to: [189653741](https://github.com/dotnet/machinelearning/pull/142#discussion_r189653741) [](ancestors = 189653741,189518236)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 32 above)
Comment (yaeldekel) [reply src/Microsoft.ML/Data/TextLoader.cs]: I was just wondering whether there could be a case where a class has additional fields that don't have the ColumnAttribute and that would be ok.

---
In reply to: [189081999](https://github.com/dotnet/machinelearning/pull/142#discussion_r189081999) [](ancestors = 189081999,188844047,188731983)

File: src/Microsoft.ML/Data/TextLoader.cs (hunk 36 above)
Comment (codemzs) [reply src/Microsoft.ML/Data/TextLoader.cs]: Thanks, Veikko and Tom. I think this is a great suggestion but unfortunately out of scope for this change. 

---
In reply to: [189661430](https://github.com/dotnet/machinelearning/pull/142#discussion_r189661430) [](ancestors = 189661430,189653741,189518236)
