### PR TITLE
Fix hash join transform.

### LINKED ISSUE #1891: Hash join fails with bad image exception.
Add this test:
```
        [Fact]
        public void EntryPointHashJoinCountTable()
        {
            TestEntryPointPipelineRoutine(GetDataPath("breast-cancer.txt"), "col=Text:TX:1-9 col=Label:0",
                new[]
                {
                    "Transforms.HashConverter",
                },
                new[]
                {
                    @"'Column': [
                      {
                        'Name': 'Temp',
                        'Src': 'Text',
                        'CustomSlotMap': '0,1;2,3,4,5'
                      }
                      ]",
                });
        }
```
you get following exception.
```
Message: System.InvalidOperationException : Splitter/consolidator worker encountered exception while consuming source data---- 
System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes #1891

### CODE REVIEW

File: src/Microsoft.ML.Transforms/HashJoiningTransform.cs [hunk 1]
```diff
@@ -541,28 +540,11 @@ private ValueGetter<VBuffer<uint>> ComposeGetterVecToVec<TSrc>(Row input, int ii
             var mask = (1U << _exes[iinfo].HashBits) - 1;
             var hashSeed = _exes[iinfo].HashSeed;
             bool ordered = _exes[iinfo].Ordered;
-            TSrc[] denseValues = null;
             return
                 (ref VBuffer<uint> dst) =>
                 {
                     getSrc(ref src);
                     Host.Check(src.Length == expectedSrcLength);
-                    ReadOnlySpan<TSrc> values;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Transforms/HashJoiningTransform.cs]: >ReadOnlySpan<TSrc> values; [](start = 20, length = 26)

I have no idea why, but as soon as I add ReadOnlySpan inside delegate, I start getting BadImage exception.
So I access elements directly instead of that strange copying mechanism.

Comment (Zruty0) [reply src/Microsoft.ML.Transforms/HashJoiningTransform.cs]: ouch. Is this something .NET colleagues should look at? It kind of smells of a .NET issue to me

---
In reply to: [242317331](https://github.com/dotnet/machinelearning/pull/1892#discussion_r242317331) [](ancestors = 242317331)

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs [hunk 2]
```diff
@@ -4037,6 +4037,33 @@ public void EntryPointSlidingWindow()
                       'L': '1'"
                 });
         }
+
+        [Fact]
+        public void EntryPointHashJoinCountTable()
```
Comment (sfilipi) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs]: >EntryPointHashJoinCountTable [](start = 20, length = 28)

does it have to be an entry point test?

File: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs [hunk 3]
```diff
@@ -4037,6 +4037,33 @@ public void EntryPointSlidingWindow()
...
+                        'Src': 'Text'
+                      },
+                      {
+                        'Name': 'Temp2',
+                        'Src': 'Text',
+                        'CustomSlotMap': '0,1;2,3,4,5'
+                      }
+
+                      ]"
+                });
```
Comment (sfilipi) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs]: does it need to call  Done();

File: src/Microsoft.ML.Transforms/HashJoiningTransform.cs (hunk 1 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Transforms/HashJoiningTransform.cs]: @danmosemsft do you know who can take a look on this?
