### PR TITLE
SDCA Regression and BinaryClassification Pigsty extensions

### LINKED ISSUE #632: Direct API: Static Typing of Data Pipelines
Currently in all iterations of the pipeline concept, whether they be based on the v0.1 idiom of `LearningPipeline`, or the #371 proposal where `IDataView` is directly created, or the refinement of that in #581, or the convenience constructors, or whatever, there is always this idea of a pipeline being a runtime-checked thing, where each stage has some output schema with typed columns indexed by a string name, and all of this is known only at runtime -- at compile time, all the compiler knows is you have *some* estimator, or *some* data view, or something like that, but has no idea what is in it.

This makes sense from a practical perspective, since there are many applications where you cannot know the schema until runtime. E.g.: loading a model from a file, or loading a Parquet file, you aren't going to know anything until the code actually runs. So we want the underlying system to remain dynamically typed to serve those scenarios, and I do not propose changing that. That said, there are some definite usability costs:

* Typos on those column names are found at runtime, which is unfortunate.
* Application of the wrong transform or learner is found at runtime.
* Discoverability is an issue. You just sort of have to know what transforms are applicable to your case, which is somewhat difficult since if we were to collect all the things you could apply to data (transform, train a learner), there are probably about 100 of these or thereabouts. Intellisense will be of no help to you here, because at compile time, the only thing the language knows is you have *some*.

It's sort of like working with `Dictionary<string, object>` as your central data structure, and an API that just takes `Dictionary<string, object>` everywhere. In a way that's arbitrarily powerful, but the language itself can give you no help at all about what you should do with it, which is kind of a pity since we have this nice statically typed language we're working in.

So: a statically typed helper API on top of this that was sufficiently powerful would help increase the confidence that if someone compiles it might run, and also give you some help in the form of proper intellisense of what you can do, while you are typing before you've run anything. Properly structured, if you had strong typing at the columnar level, nearly everything you can do can be automatically discoverable through intellisense. The documentation would correspondingly become a lot more focused.

The desire to have something like this is very old, but all prior attempts I recall ran into some serious problems sooner or later. In this issue I discuss such an API that I've been kicking around for a little bit, and at least so far it doesn't seem to have any show-stopping problems, at least so far as I've discovered in my initial implementations.

The following proposal is built on top of #581. (For those seeking actual code, the current exploratory work in progress is based out of [this branch](https://github.com/TomFinley/machinelearning/tree/tfinley/StrongPipe), which in turn is a branch based of @Zruty0's [branch here](https://github.com/Zruty0/machinelearning/tree/feature/estimators/src/Microsoft.ML.Core/Data).)

# Simple Example

It may be that the easiest way to explain the proposal is to show a simple example, then explain it. This will be where we [train sentiment classification](https://github.com/dotnet/machinelearning/blob/89dfc82f5edcfe23015dc2c1291bc7a836188e80/test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/SentimentPredictionTests.cs#L24), though I've simplified the text settings to just the diacritics option

```csharp
// We load two columns, the boolean "label" and the textual "sentimentText".
var text = TextLoader.Create(
    c => (label: c.LoadBool(0), sentimentText: c.LoadText(1)),
    sep: '\t', header: true);

// We apply the text featurizer transform to "sentimentText" producing the column "features".
var transformation = text.CreateTransform(r =>
    (r.label, features: r.sentimentText.TextFeaturizer(keepDiacritics: true)));

// We apply a learner to learn "label" given "features", which will in turn produce
// float "score", float "probability", and boolean "predictedLabel".
var training = transformation.CreateTransform(r =>
    r.label.TrainLinearClassification(r.features))
```

An alternative is we might do a continuous, non-segmented form (where they are all merged into a single thing):

```csharp
var pipeline = TextLoader.Create(
    c => (label: c.LoadBool(0), sentimentText: c.LoadText(1)),
    sep: '\t', header: true)
    .ExtendWithTransform(r => (r.label, features: sentimentText.TextFeaturizer(keepDiacritics: true)))
    .ExtendWithTransform(r => r.label.TrainLinearClassification(r.features));
```

or even the following:

```csharp
var pipeline = TextLoader.Create(c =>
    c.LoadBool(0).TrainLinearClassification(c.LoadText(1).TextFeaturizer(keepDiacritics: true)));
```

## Developer Story

Here's how I imagine this playing out by someone maybe like me. So: first we have this `TextLoader.Create` method. (Feel free to suggest better names.)

* The developer knows they have some data file, a TSV with two fields, a label, and some sentiment text. They write `TextLoader.Create`. The first argument is delegate, with a text loader context input, and is responsible for producing a tuple out of things composed out of that context. (Both the method signature, and the XML doc commentary, can explain this.) When they write `c => c.`, intellisense hits them with what they can do... `c.LoadBool`, `c.LoadDouble`, `c.LoadFloat`, etc. These methods produce things like `Scalar<bool>`, `Vector<bool>`, `Scalar<double>`, etc., depending on which is called, what overload is used, and so on. The developer ultimately creates a value-tuple out of all this stuff, with the bool and text loading values.

* Then they have this object, here called `text`. So they type `text.`, and Intellisense pops up again. They know they want to do *something* with the data they've told the framework to load, and they see `CreateTransform` or `ExtendWithTransform`. Even if they haven't read a bit of documentation, that has enough of a name that they think, maybe, "heck, maybe this is where I belong." So they choose that.

* Again they are hit with a delegate. But this time, the input type is the value-tuple created in the loader. And they might type, `text.CreateTransform(r => r.label.TrainLinearClassification`. They try to feed in their `sentimentText`, but the compiler complains at them, saying, I want a `Vector<float>`, not a `Scalar<text>`. So maybe they now do `r.sentimentText.TextFeaturizer` as something sufficiently promising, since it has a promising sounding name and also returns the `Vector<float>` that the classifier claims to want. In VS it looks something like this (click the image to see zoomed in version, sorry that the screenshot is so wide):

image

Given that setup, there is I think only one thing here that cannot be plausibly discovered via intellisense, or the XML docs that pop up with intellisense, and that is the fact that you would want to start the pipeline with something like `TextLoader.Create`. But I figure this will be so ubiquitous even in "example 1" that we can get away with it. There's also the detail about training happening through a "label," and unless they happen to have the right type (`Scalar<bool>`) it simply won't show up for them. But someone reading documentation on the linear classifier would surely see that extension method and figure out what to do with it.

# More Details

Now we drill a little bit more into the shape and design of this API.

## `PipelineColumn` and its subclasses

As we saw in the example, many transformations are indicated by the type of data. For this we have the abstract class `PipelineColumn`, which are manifested to the user through the following abstract subclasses.

* `Scalar<>` represents a scalar-column of a particular type.
* `Vector<>` represents a vector-valued column of a particular type, where the vector size will be fixed and known (though we might not know the actual size at compiled time)
* `VarVector<>` is similar, but on known size.
* `Key<>`, indicating a key type, which are essentially enumerations into a set.
* `Key<,>`, indicating a key type with a known value, which are essentially enumerations into a set.
* `VarKey<>` which is a key type of unknown cardinality. (These are fairly rare.)

## `ValueTuple`s of `PipelineColumn`s

The pipeline  are the smallest granularity structures. Above that you have collections of these representing the values present at any given time, upon which you can apply more transformations. That value, as mentioned earlier, is a potentially nested value tuple. By potentially nested, what I mean is that you can have as many `ValueTuple`s as you want. So all of the following are fine, if we imagine that `a`, `b`, and `c` are each some sort of `PipelineColumn`:

```csharp
(a, b)
(a, x: (b, c))
a
```

In the first case the actual underlying data-view, when produced, would have two columns named `a` and `b`. In the second, there would be three columns, `a`, `x.b`, and `x.c`. In the last, since there is no way as near as I can tell to have a named `ValueTuple<>`, I just for now picked the name `Data`. (Note that in the case where value-tuples are present, the names of the items become the names of the output columns in the data-view schema.)

The reason for supporting nesting is, some estimators produce multiple columns (notably, in the example, the binary classification trainer produces three columns), and as far as I can tell there is no way to "unpack" a returned value-tuple into another value-tuple. Also it provides a convenient way to just bring along all the inputs, if we wanted to do so, by just assigning the input tuple itself as an item in the output tuple.

## The Pipeline Components

At a higher level of the columns, and the (nested) tuples of columns, you have the objects that represent the pipeline components that describe each step of what you are actually doing with these things. That is, those objects mappings into those value tuples, or between them. To return to the example with `text` and `transformation` and `training`, these have the following types, in the sense that all the following statements in code would be true:

```csharp
text is DataReaderEstimator<IMultiStreamSource,
    (Scalar<bool> label, Scalar<string> sentimentText)>;

transformation is Estimator<
    (Scalar<bool> label, Scalar<string> sentimentText),
    (Scalar<bool> label, Scalar<float> features)>;

training is Estimator<
    (Scalar<bool> label, Scalar<float> features),
    (Scalar<float> score, Scalar<float> probability, Scalar<bool> predictedLabel)>;
```

and also in those "omnibus" equivalents;

```csharp
pipeline is DataReaderEstimator<IMultiStreamSource,
    (Scalar<float> score, Scalar<float> probability, Scalar<bool> predictedLabel)>;
```

One may note that the statically-typed API is strongly parallel to the structures proposed in #581. That is, for every core structure following the `IEstimator` idiom laid out in #581, I envision a strongly typed variant of each type. In the current working code, in fact, the objects actually implement those interfaces, but I might go to having them actually wrap them.

Like the underlying dynamically typed objects, they can be combined in the usual way to form cohesive pipelines. So for example: one could take a `DataReaderEstimator<TIn, TA>` and an `Estimator<TA, TB>` to produce a `DataReaderEstimator<TIn, TB>`. (So for example, when I was using `ExtendWithTransform` instead of )

This duality is deliberate. While the *usage* of the static estimators will necessarily not resemble the dynamically typed estimators, based as it is on actual .NET types and identifiers, the structure that is being built up *is* an estimator based pipeline, and so will resemble it structurally. This duality enables one to use static-typing for as long as is convenient, then when done drop back down to the dynamically typed one. But you could also go in reverse, start with something dynamically typed -- perhaps a model loaded from a file -- essentially assert that this dynamically typed thing has a certain shape (which of course could only be checked at runtime), and then from then on continue with the statically-typed pipe. So as soon as the static typing stops being useful, there's no cliff -- you can just stop using it at that point, and continue dynamically.

However if you can stay in the statically typed world, that's fine. You can fit a strongly typed `Estimator` to to get a strongly typed `Transformer`. You can then further get a strongly typed `DataView` out of a strongly typed `Transformer`. In the end this is still just a veneer, kind of like the `PredictionEngine` stuff, but it's a veneer that has a strong likelihood of working.

## One or Two Implementation Details

The following is not something that most users will need to concern themselves with, and we won't go into too many details. However at least a loose idea of how the system works might help clear up some of the mystery.

The `Scalar<>`, `Vector<>`, etc. classes are abstract classes. The `PipelineColumn`s that are created from the helper extension methods have actual concrete implementations intended to be nested private classes in whatever estimator they're associated with. A user never sees those implementations. The component author is responsible for calling the `protected` constructor on those objects, so as to feed it the list of dependencies (what `PipelineColumn` it needs to exist before it would want to chain its own estimator), as well as a little factory object for now called a "reconciler" that the analyzer can call once it has satisfied those dependencies.

The analyzer itself takes the delegate. It constructs the input object, then pipes it thorugh the delegate. In the case of the estimator,  these are *not* the ones returned from any prior delegate (indeed we have no requirement that there *be* a prior delegate -- estimators can function as independent building blocks), but special instances made for that analysis task). The resulting output will be a value-tuple of `PipelineColumn`s, and by tracing back the dependencies, until we get the graph of dependencies.

The actual constructed inputs have no dependencies, and are assumed to just be there already. We then iteratively "resolve" dependencies -- we take all columns that have their dependencies resolved, and take some subset that all have the same "reconciler." That reconciler is responsible for returning the actual `IEstimator`. Then anything that depends on *that* column gets resolved. And so on.

In this way these delegates are declarative structures. Each extension method provides these `PipelineColumn` implementations, which as objects, but it is the analyzer that goes ahead and figures out in what sequence those factory methods will be called, with what names, etc.

It might be more clear if we saw that actual engine.

https://github.com/TomFinley/machinelearning/blob/8e0298f64f0a9f439bb83426b09e54967065793b/src/Microsoft.ML.Core/StrongPipe/BlockMaker.cs#L13

The system mostly has fake objects everywhere as standins right now just to validate the approach, so for example if I were to actually run the code in the first example, I get the following diagnostic output. (It should be relatively easy to trace back the diagnostic output.)

```
Called CreateTransform !!!
Using input with name label
Using input with name sentimentText
Constructing TextTransform estimator!
    Will make 'features' out of 'sentimentText'
Exiting CreateTransform !!!

Called CreateTransform !!!
Using input with name label
Using input with name features
Constructing LinearBinaryClassification estimator!
    Will make 'score' out of 'label', 'features'
    Will make 'probability' out of 'label', 'features'
    Will make 'predictedLabel' out of 'label', 'features'
Exiting CreateTransform !!!
```

If I had another example, like this:

```csharp
var text = TextLoader.Create(
    ctx => (
    label: ctx.LoadBool(0),
    text: ctx.LoadText(1),
    numericFeatures: ctx.LoadFloat(2, 9)
    ));

var transform = text.CreateTransform(r => (
    r.label,
    features: r.numericFeatures.ConcatWith(r.text.Tokenize().Dictionarize().BagVectorize())
    ));

var train = transform.CreateTransform(r => (
    r.label.TrainLinearClassification(r.features)
```

then the output looks a little something like this:

```
Called CreateTransform !!!
Using input with name label
Using input with name numericFeatures
Using input with name text
Constructing WordTokenize estimator!
    Will make '#Temp_0' out of 'text'
Constructing Term estimator!
    Will make '#Temp_1' out of '#Temp_0'
Constructing KeyToVector estimator!
    Will make '#Temp_2' out of '#Temp_1'
Constructing Concat estimator!
    Will make 'features' out of 'numericFeatures', '#Temp_2'
Exiting CreateTransform !!!

Called CreateTransform !!!
Using input with name label
Using input with name features
Constructing LinearBinaryClassification estimator!
    Will make 'score' out of 'label', 'features'
    Will make 'probability' out of 'label', 'features'
    Will make 'predictedLabel' out of 'label', 'features'
Exiting CreateTransform !!!
```

You can sort of trace though what the analyzer is doing as it resolves dependencies, constructs `IEstimator`s, etc. etc. (Obviously the real version won't have all those little console writelines everywhere.)

## Stuff Not Covered

There's a lot of stuff I haven't yet talked about. We create these blocks, how do we mix and match? What does the strongly typed `Transformer` or `DataView` look like? We talked about the text loader, what about sources that come from actual .NET objects? These we might cover in future editions on this, or in subsequent comments. But I think perhaps this writing has gone on long enough...

/cc @Zruty0 , @ericstj , @eerhardt , @terrajobst , @motus

### PR DESCRIPTION
**Pull request by TomFinley**
Related to the closed #632 and the API overall. In here I introduce extensions for SDCA regression and binary classification. (No multiclass until I also write extensions for term.)

This also includes a sort of general purpose utilities for writing reconcilers for trainers, though, again, only regression, binary classification, and binary classification without probabilities so far.

Also a minor change to the linear classification trainer, as it was not identifying that it was producing probabilities sometimes.

### CODE REVIEW

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 1]
```diff
@@ -0,0 +1,335 @@
...
+        /// The output columns. Note that subclasses should return exactly the same items each time,
+        /// and the items should correspond to the output names passed into the constructor.
+        /// </summary>
+        protected abstract IEnumerable<PipelineColumn> Outputs { get; }
+
+        /// <summary>
+        /// Constructor for the base class.
+        /// </summary>
+        /// <param name="inputs">The set of inputs</param>
+        /// <param name="outputNames">The names of the outputs, which we assume cannot be changed</param>
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: real question: do we put a period in the sentences of the <summary>section, but not in the sentences in <params>?

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 2]
```diff
@@ -0,0 +1,335 @@
...
+using System.Linq;
+using Microsoft.ML.Core.Data;
+using Microsoft.ML.Runtime;
+using Microsoft.ML.Runtime.Data;
+using Microsoft.ML.Runtime.Internal.Utilities;
+
+namespace Microsoft.ML.Data.StaticPipe.Runtime
+{
+    /// <summary>
+    /// General purpose reconciler for a typical case with trainers, where they accept some generally
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: >reconciler [](start = 24, length = 10)

I am still fuzzy on the purpose of reconcilers. is it a bridge from estimators to trainers?

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 3]
```diff
@@ -0,0 +1,335 @@
...
+        /// <param name="inputNames">The names of the inputs, which corresponds exactly to the input columns
+        /// fed into the constructor</param>
+        /// <returns>An estimator, which should produce the additional columns indicated by the output names
+        /// in the constructor</returns>
+        protected abstract IEstimator<ITransformer> ReconcileCore(IHostEnvironment env, string[] inputNames);
+
+        /// <summary>
+        /// Produces the estimator. Note that this is made out of <see cref="ReconcileCore(IHostEnvironment, string[])"/>'s
+        /// return value, plus whatever usages of <see cref="CopyColumnsEstimator"/> are necessary to avoid collisions with
+        /// the output names fed to the constructor. This class provides the implementation, and subclassses should instead
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: >subclassses [](start = 97, length = 11)

typo

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+                            onFit(pred, cali);
+                        });
+                    }
+                    return trainer;
+                }, label, features, weights);
+
+            return rec.Output;
+        }
+
+        private sealed class TrivialFactory : ISupportSdcaClassificationLossFactory
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >TrivialFactory [](start = 29, length = 14)

would 'BaseLossFactory' be a better name?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+
+        public static (Scalar<float> score, Scalar<float> probability, Scalar<bool> predictedLabel)
+            PredictSdcaBinaryClassification(this Scalar<bool> label, Vector<float> features, Scalar<float> weights = null,
+                float? l2Const = null,
+                float? l1Threshold = null,
+                float convergenceTolerance = 0.1f,
+                int? maxIterations = null,
+                bool shuffle = true,
+                float biasLearningRate = 0,
+                Action<LinearBinaryPredictor, ParameterMixingCalibratedPredictor> onFit = null)
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >onFit [](start = 82, length = 5)

is this so we can pass different types of calibrators?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+
+            public ISupportSdcaClassificationLoss CreateComponent(IHostEnvironment env)
+            {
+                // REVIEW: We are ignoring env?
+                return _loss;
+            }
+        }
+
+        public static (Scalar<float> score, Scalar<bool> predictedLabel)
+            PredictSdcaBinaryClassificationCustomLoss(this Scalar<bool> label, Vector<float> features, Scalar<float> weights = null,
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >PredictSdcaBinaryClassificationCustomLoss [](start = 12, length = 41)

Are we going to test those methods through the samples code we're doing later?

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 7]
```diff
@@ -0,0 +1,335 @@
...
+        {
+            /// <summary>
+            /// The delegate to parameterize the <see cref="Regression"/> instance.
+            /// </summary>
+            /// <param name="env">The environment with which to create the estimator</param>
+            /// <param name="label">The label column name</param>
+            /// <param name="features">The features column name</param>
+            /// <param name="weights">The weights column name, or <c>null</c> if the reconciler was constructed with <c>null</c> weights</param>
+            /// <returns>Some sort of estimator producing columns with the fixed name <see cref="DefaultColumnNames.Score"/></returns>
+            public delegate IEstimator<ITransformer> EstimatorMaker(IHostEnvironment env, string label, string features, string weights);
```
Comment (Zruty0) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: >Maker [](start = 62, length = 5)

Either 'builder' or 'factory' seems a bit more common for a factory method like this

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 8]
```diff
@@ -0,0 +1,156 @@
...
+using Microsoft.ML.Runtime.Internal.Calibration;
+
+namespace Microsoft.ML.Runtime.Learners
+{
+    /// <summary>
+    /// Extension methods and utilities.
+    /// </summary>
+    public static class SdcaStatic
+    {
+        public static Scalar<float> PredictSdcaRegression(this Scalar<float> label, Vector<float> features, Scalar<float> weights = null,
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >PredictSdcaRegression [](start = 36, length = 21)

Let's get into habit of writing extensive summary comments for these, since this is our public API now

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 9]
```diff
@@ -0,0 +1,156 @@
...
+                MaxIterations = maxIterations,
+                Shuffle = shuffle,
+                BiasLearningRate = biasLearningRate,
+                LossFunction = loss ?? new SquaredLossFactory()
+            };
+
+            var rec = new TrainerEstimatorReconciler.Regression(
+                (env, labelName, featuresName, weightsName) =>
+                {
+                    var trainer = new SdcaRegressionTrainer(env, args, featuresName, labelName, weightsName);
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >args [](start = 65, length = 4)

Yuck, args! In transforms, I was trying to get rid of them. I think we should do the same for trainers?

Comment (Zruty0) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: asking for a friend :) 
That is, not insisting that you do so now.

---
In reply to: [215368077](https://github.com/dotnet/machinelearning/pull/837#discussion_r215368077) [](ancestors = 215368077)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 10]
```diff
@@ -0,0 +1,156 @@
...
+                int? maxIterations = null,
+                bool shuffle = true,
+                float biasLearningRate = 0,
+                ISupportSdcaClassificationLoss loss = null,
+                Action<LinearBinaryPredictor> onFit = null
+            )
+        {
+            ISupportSdcaClassificationLossFactory lossFactory = new LogLossFactory();
+            if (loss != null)
+                lossFactory = new TrivialFactory(loss);
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >TrivialFactory [](start = 34, length = 14)

I think this is what `SimpleComponentFactory` is for, is it not?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs (hunk 4 above)
Comment (Zruty0) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: I think the idea is that this 'factory' will always return an existing object, so it's more 'trivial' than it is 'base'

---
In reply to: [215330387](https://github.com/dotnet/machinelearning/pull/837#discussion_r215330387) [](ancestors = 215330387)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 11]
```diff
@@ -0,0 +1,156 @@
...
+            private readonly ISupportSdcaClassificationLoss _loss;
+
+            public TrivialFactory(ISupportSdcaClassificationLoss loss)
+            {
+                _loss = loss;
+            }
+
+            public ISupportSdcaClassificationLoss CreateComponent(IHostEnvironment env)
+            {
+                // REVIEW: We are ignoring env?
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >REVIEW: We are ignoring env? [](start = 19, length = 28)

well, in this case the loss has been given to us, so no need to use env to manufacture anything, right?

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 12]
```diff
@@ -0,0 +1,335 @@
...
+            }
+
+            private sealed class ImplBool : Scalar<bool>
+            {
+                public ImplBool(BinaryClassifier rec) : base(rec, rec._inputs) { }
+            }
+        }
+
+        /// <summary>
+        /// A reconciler for regression capable of handling the most common cases for binary classification
```
Comment (Zruty0) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: >regression [](start = 29, length = 10)

binary classification?

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 13]
```diff
@@ -0,0 +1,335 @@
...
+            }
+
+            private sealed class Impl : Scalar<float>
+            {
+                public Impl(Regression rec) : base(rec, rec._inputs) { }
+            }
+        }
+
+        /// <summary>
+        /// A reconciler for regression capable of handling the most common cases for binary classifier with calibrated outputs.
```
Comment (Zruty0) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: >regression [](start = 29, length = 10)

seems like a copypasta error

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs [hunk 14]
```diff
@@ -0,0 +1,335 @@
...
+            private readonly EstimatorMaker _estMaker;
+            private static readonly string[] _fixedOutputNamesProb = new[] { DefaultColumnNames.Score, DefaultColumnNames.Probability, DefaultColumnNames.PredictedLabel };
+            private static readonly string[] _fixedOutputNames = new[] { DefaultColumnNames.Score, DefaultColumnNames.PredictedLabel };
+
+            /// <summary>
+            /// The general output for binary classifiers.
+            /// </summary>
+            public (Scalar<float> score, Scalar<bool> predictedLabel) Output { get; }
+
+            protected override IEnumerable<PipelineColumn> Outputs { get; }
```
Comment (Zruty0) [inline src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: I'm not sure I fully grasp the difference between `Output` and `Outputs`...

File: test/Microsoft.ML.StaticPipelineTesting/Training.cs [hunk 15]
```diff
@@ -0,0 +1,156 @@
...
+using Microsoft.ML.Runtime.Data;
+using Microsoft.ML.Runtime.Internal.Calibration;
+using Microsoft.ML.Runtime.Learners;
+using System;
+using Xunit;
+using Xunit.Abstractions;
+
+namespace Microsoft.ML.StaticPipelineTesting
+{
+    public sealed class Training : MakeConsoleWork
```
Comment (Zruty0) [inline test/Microsoft.ML.StaticPipelineTesting/Training.cs]: >MakeConsoleWork [](start = 35, length = 15)

can we rename this to something that indicates that it's a base class for tests?
Like `BaseTestClassWithConsole` ?

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs (hunk 1 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: Having complete sentences in the summary is essential. About params, I'm less sure about that, but I think I prefer to have them, I'll try to add them.

---
In reply to: [215322337](https://github.com/dotnet/machinelearning/pull/837#discussion_r215322337) [](ancestors = 215322337)

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs (hunk 7 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: Let's do factory I guess.

---
In reply to: [215366624](https://github.com/dotnet/machinelearning/pull/837#discussion_r215366624) [](ancestors = 215366624)

File: src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs (hunk 14 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/StaticPipe/TrainerEstimatorReconciler.cs]: I'll add a comment. They only really differ in content in this one class, due to the fact that are compile time we can only be sure two are present, while at runtime we also have to be sensitive as to whether we are in fact producing that extra probability column.

---
In reply to: [215371730](https://github.com/dotnet/machinelearning/pull/837#discussion_r215371730) [](ancestors = 215371730)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: OK. In order to encourage "early" resolution I will also move the `loss` argument to be right after the delegate, and make it a non-default argument to encourage people to actually set it.

---
In reply to: [215378059](https://github.com/dotnet/machinelearning/pull/837#discussion_r215378059) [](ancestors = 215378059)

[the remark this answers is not in the document]
Comment (TomFinley) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: Ooo... hmmm. Maybe it has to go after `features`, but before `weights`. Hmmm. Hmmm.

---
In reply to: [215414897](https://github.com/dotnet/machinelearning/pull/837#discussion_r215414897) [](ancestors = 215414897,215378059)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs (hunk 9 above)
Comment (TomFinley) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: Hi @Zruty0 , I agree with you. I can make an issue on this subject.

---
In reply to: [215368265](https://github.com/dotnet/machinelearning/pull/837#discussion_r215368265) [](ancestors = 215368265,215368077)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs (hunk 5 above)
Comment (TomFinley) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: No, this is so the user of this method can be informed about the calibrator, so they know the slope, etc.

---
In reply to: [215331242](https://github.com/dotnet/machinelearning/pull/837#discussion_r215331242) [](ancestors = 215331242)

File: src/Microsoft.ML.Data/StaticPipe/SchemaBearing.cs [hunk 16]
```diff
@@ -37,11 +37,12 @@ private protected SchemaBearing(IHostEnvironment env, StaticSchemaShape shape)
...
-        /// Create an object that can be used as the start of a new pipeline, that assumes it uses
-        /// something with the sahape of <typeparamref name="TTupleShape"/> as its input schema shape.
-        /// The returned object is an empty estimator.
+        /// Starts a new pipeline, using the output schema of this object. Note that the returned
+        /// estimator does not contain this object, but it has its schema informed by <typeparamref name="TTupleShape"/>.
+        /// The returned object is an empty estimator, on which a new segment of the pipeline can be created.
         /// </summary>
-        internal Estimator<TTupleShape, TTupleShape, ITransformer> MakeNewEstimator()
+        /// <returns>An empty estimator with the same shape as the object on which it was created</returns>
+        public Estimator<TTupleShape, TTupleShape, ITransformer> MakeNewEstimator()
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/StaticPipe/SchemaBearing.cs]: >public [](start = 8, length = 6)

As discussed [here](https://github.com/dotnet/machinelearning/pull/809#discussion_r215093150) I believe the POR for right now until we change our minds again is for the method to create new estimator pipes to exist directly on these schema bearing objects (whatever they may be).

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs [hunk 17]
```diff
@@ -0,0 +1,230 @@
...
+        /// <param name="features">The features, or independent variables.</param>
+        /// <param name="weights">The optional example weights.</param>
+        /// <param name="l2Const">The L2 regularization hyperparameter.</param>
+        /// <param name="l1Threshold">The L1 regularization hyperparameter. Higher values will tend to lead to more sparse model.</param>
+        /// <param name="maxIterations">The maximum number of passes to perform over the data.</param>
+        /// <param name="loss">The custom loss, if unspecified will be <see cref="SquaredLossSDCARegressionLossFunction"/>.</param>
+        /// <param name="onFit">A delegate that is called every time the
+        /// <see cref="Estimator{TTupleInShape, TTupleOutShape, TTransformer}.Fit(DataView{TTupleInShape})"/> method is called on the
+        /// <see cref="Estimator{TTupleInShape, TTupleOutShape, TTransformer}"/> instance created out of this. This delegate will receive
+        /// the linear model that was learnt.  Note that this action cannot change the result in any way; it is only a way for the caller to
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: >learnt [](start = 38, length = 6)

maybe 'trained'? :)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs (hunk 8 above)
Comment (Zruty0) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: I do

---
In reply to: [215430305](https://github.com/dotnet/machinelearning/pull/837#discussion_r215430305) [](ancestors = 215430305,215367489)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs (hunk 17 above)
Comment (TomFinley) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaStatic.cs]: Yes. I think the first instance can be trained, but I feel like the trailing word has to be learnt or something.
