### PR TITLE
Use Timer and ctx.CancelExecution() to fix AutoML max-time experiment bug

### LINKED ISSUE #5437: Auto train pipeline Bug
### System information

- **OS version/distro**: Windows server 2012r2 - windows 10
- **.NET Version**: .net core 3.1
- **Ml.net Version**: Last Stable Version.

### Issue

- **What did you do?**: Set a auto Training pipeline using API, set a long MaxExperimentTimeInSeconds (For example 600) for small dataset.
- **What happened?**: Program hanged without any response.
- **What did you expect?**: the program should stop training after 600 seconds. and show me the result.
- **Am I Tested it with shorter time?**: Yes! I Tested it with 120Seconds and 100 Seconds. Its work currectly!

### Source code / logs

```
var experimentSettings = new MulticlassExperimentSettings()
            {
                MaxExperimentTimeInSeconds = 600,
                CacheDirectory = new DirectoryInfo("cache"),
                CacheBeforeTrainer = CacheBeforeTrainer.Auto,
                OptimizingMetric = MulticlassClassificationMetric.MicroAccuracy,
            };
```

            var experiment = mlContext.Auto().CreateMulticlassClassificationExperiment(experimentSettings);

            var crossValidationExperimentResult = experiment.Execute(
                trainData: mappedInputData,
                labelColumnName: "Label",
                progressHandler: new Progress<RunDetail<MulticlassClassificationMetrics>>()
            );

toplearn

### PR DESCRIPTION
**Pull request by mstfbl**
Fix #5437 

This PR utilizes `Timer` and `ctx.CancelExecution` in AutoML's `Experiment` to listen for and cancel ongoing experiment after given `MaxExperimentTime` has elapsed.

### CODE REVIEW

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 1]
```diff
@@ -49,12 +51,41 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
             _logger = logger;
+            _endExperimentWhenAble = false;
+        }
+
+        private void MaxExperimentTimeExpiredEvent(object sender, EventArgs e)
+        {
+            // If at least one model was run, end experiment immediately.
+            // Else, wait for first model to run before experiment is concluded.
+            _endExperimentWhenAble = true;
+            if (_history.Count > 0)
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:62]: I think checking for a successful model is slightly more user friendly as the first model may have failed and the second model may be 95% complete. Granted, the difference to the user will be minimal.

Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:62]: Good point, thank you!

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 2]
```diff
@@ -49,20 +53,58 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+
+                // A new MLContext is needed per model run. When max experiment time is reached, each used
+                // context is canceled to stop further model training. The cancellation of the main MLContext
+                // a user has instantiated is not desirable, thus additional MLContexts are used.
+                var activeMLContext = new MLContext(((ISeededEnvironment)_context.Model.GetEnvironment()).Seed);
+                _activeMLContexts.Add(activeMLContext);
+                var pipeline = PipelineSuggester.GetNextInferredPipeline(activeMLContext, _history, _datasetColumnInfo, _task,
                     _optimizingMetricInfo.IsMaximizing, _experimentSettings.CacheBeforeTrainer, _trainerAllowList);
 
                 var pipelineInferenceTimeInSeconds = getPipelineStopwatch.Elapsed.TotalSeconds;
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:110]: Unused:
```suggestion
```

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs [hunk 3]
```diff
@@ -320,6 +322,36 @@ public void AutoFitWithPresplittedData()
...
+            var trainData = textLoader.Load(dataPath);
+            var experiment = context.Auto()
+                .CreateBinaryClassificationExperiment(5)
+                .Execute(trainData, new ColumnInformation() { LabelColumnName = DatasetUtil.UciAdultLabel });
+            RunDetail<BinaryClassificationMetrics>[] runDetails = experiment.RunDetails.Where(r => r.Model != null).ToArray();
+            foreach(RunDetail<BinaryClassificationMetrics> runDetail in runDetails)
+			{
+                ModelContainer modelContainer = GetInstanceField(typeof(RunDetail<BinaryClassificationMetrics>), runDetail, "_modelContainer") as ModelContainer;
+                MLContext thisContext = GetInstanceField(typeof(ModelContainer), modelContainer, "_mlContext") as MLContext;
+                Assert.True((thisContext.Model.GetEnvironment() as ICancelable).IsCanceled);
```
Comment (justinormont) [inline test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:344]: Shouldn't just the last model be canceled, the one model which was training when the timer expired?

Side note: there's mixed tab/spaces for indentation in the new code.

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs [hunk 4]
```diff
@@ -246,7 +248,7 @@ public void AutoFitRecommendationTest()
             RunDetail<RegressionMetrics> bestRun = experimentResult.BestRun;
             Assert.True(experimentResult.RunDetails.Count() > 1);
             Assert.NotNull(bestRun.ValidationMetrics);
-            Assert.True(experimentResult.RunDetails.Max(i => i.ValidationMetrics.RSquared != 0));
+            Assert.True(experimentResult.RunDetails.Max(i => i?.ValidationMetrics?.RSquared) != 0);
```
Comment (justinormont) [inline test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:251]: May want to check that R<sup>2</sup> is `>0.5` (or any other expected value). Being exactly `0.0` would be odd as the range for R<sup>2</sup> is `-Infinity` to `1.0`.
```suggestion
            Assert.True(experimentResult.RunDetails.Max(i => i?.ValidationMetrics?.RSquared) > 0.5);
```

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs [hunk 5]
```diff
@@ -320,6 +322,36 @@ public void AutoFitWithPresplittedData()
...
+                .CreateBinaryClassificationExperiment(5)
+                .Execute(trainData, new ColumnInformation() { LabelColumnName = DatasetUtil.UciAdultLabel });
+            RunDetail<BinaryClassificationMetrics>[] runDetails = experiment.RunDetails.Where(r => r.Model != null).ToArray();
+            foreach(RunDetail<BinaryClassificationMetrics> runDetail in runDetails)
+			{
+                ModelContainer modelContainer = GetInstanceField(typeof(RunDetail<BinaryClassificationMetrics>), runDetail, "_modelContainer") as ModelContainer;
+                MLContext thisContext = GetInstanceField(typeof(ModelContainer), modelContainer, "_mlContext") as MLContext;
+                Assert.True((thisContext.Model.GetEnvironment() as ICancelable).IsCanceled);
+            }
+        }
```
Comment (justinormont) [inline test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:346]: I might recommend extending this unit test to test the ability to refit/transform/evaluate the BestRun after canceling: _(or perhaps as its own test)_
```suggestion
            var refitModel = experiment.BestRun.Estimator.Fit(trainData);
            IDataView predictions = refitModel.Transform(trainData);
            var metrics = mlContext.BinaryClassification.Evaluate(predictions, labelColumnName: DatasetUtil.UciAdultLabel);
            assert(metrics?.Accuracy > 0.5); 
        }
```

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs (hunk 3 above)
Comment (mstfbl) [reply test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:344]: As we're now adding new MLContext's per each model run in addition to the MLContext which is tied to the origination of the experiment, I think all additional MLContexts should be canceled. Should this be so, or only the MLContext that is tied to the last model be canceled?

Comment (mstfbl) [reply test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:344]: That is so, I have now made it so that the last model that was in the middle of training is canceled.

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs (hunk 5 above)
Comment (mstfbl) [reply test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs:346]: Added. I've also removed using reflection to check if the last model is canceled, as the `RunDetails` of the last model has an `Exception` field which contains the "Operation was canceled" message of the `OperationCanceledException`. :)

**Comment by mstfbl** [comment]
MacOS builds will pass once PR #5457 is merged.

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs (hunk 3 above)
Comment (justinormont) [reply test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs]: The goal of the refitting unit test I was recommending is to ensure the refitting workflow continues working after this PR's change  -- https://github.com/dotnet/machinelearning/pull/5445#discussion_r510599919.

Method 1:
One way to have the unit test pass is to only cancel the last MLContext (more specifically, anything that was actually canceled). Then the `experimentResult.BestRun` (and other non-canceled iterations) can be refit.

The multi-step reasoning is, if we cancel a MLContext it is no longer usable for training. The MLContext is stored as part of the Estimator returned from the AutoML API call. The Estimator is used to retrain the pipeline found by AutoML on additional data, for instance thrice training on (train/valid/test) data to make a more useful model, which is the [recommend final step](https://github.com/dotnet/machinelearning-samples/blob/ab652eadb1f7552c1816bc4d2ed0a27ef4675a37/samples/csharp/getting-started/AdvancedExperiment_AutoML/AdvancedTaxiFarePrediction/Program.cs#L186-L197) in the AutoML workflow.

If we cancel all MLContexts, retraining will only be doable if the time limit isn't hit. Sometimes the user will have a canceled context, sometimes not. 

Method 2:
Another possible way is if we keep around a second copy of the Estimator, and return it to the user. We fit one to make the model and cancel it after AutoML uses it, and returns a clean non-canceled copy of the Estimator to the user.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 6]
```diff
@@ -49,23 +53,55 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+            // elapsed, MaxExperimentTimeExpiredEvent is called to interrupt training
+            // of current model. Timer is not used if no experiment time is given, or
+            // is not a positive number.
+            if (_experimentSettings.MaxExperimentTimeInSeconds > 0)
+            {
+                Timer timer = new Timer(_experimentSettings.MaxExperimentTimeInSeconds * 1000);
+                timer.Elapsed += MaxExperimentTimeExpiredEvent;
+                timer.AutoReset = false;
+                timer.Enabled = true;
+            }
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:85]: We may need a second timer to check for, and propagate the cancelation signal from the main MLContext to all the new child MLContexts. Then if a user calls `ctx.Cancel()` on the main, the AutoML run will end, just like if the time expired.

File: test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs (hunk 5 above)
Comment (justinormont) [reply test/Microsoft.ML.AutoML.Tests/AutoFitTests.cs]: Good find.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 7]
```diff
@@ -7,6 +7,8 @@
 using System.Diagnostics;
 using System.IO;
 using System.Linq;
+using System.Timers;
```
Comment (eerhardt) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:10]: Use `System.Threading.Timer` instead. There are 2 of them in .NET, but the Threading.Timer is more preferred.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 8]
```diff
@@ -49,23 +53,55 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
                 // get next pipeline
                 var getPipelineStopwatch = Stopwatch.StartNew();
-                var pipeline = PipelineSuggester.GetNextInferredPipeline(_context, _history, _datasetColumnInfo, _task,
-                    _optimizingMetricInfo.IsMaximizing, _experimentSettings.CacheBeforeTrainer, _trainerAllowList);
 
-                var pipelineInferenceTimeInSeconds = getPipelineStopwatch.Elapsed.TotalSeconds;
+                // A new MLContext is needed per model run. When max experiment time is reached, each used
+                // context is canceled to stop further model training. The cancellation of the main MLContext
+                // a user has instantiated is not desirable, thus additional MLContexts are used.
+                _currentModelMLContext = new MLContext(((ISeededEnvironment)_context.Model.GetEnvironment()).Seed);
```
Comment (eerhardt) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:102]: Won't this use the same Seed at the beginning of each iteration?

Comment (eerhardt) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:102]: What good is the `_context`? What is not desired about cancelling the main MLContext?

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:102]: Thanks for hopping on the code review. 

The main `_context` is for when the _user_ canceled their ML workflow. The purpose of the `_currentModelMLContext` is only to stop the current model being trained, when time expires, and return back to the user code.

If we cancel the main MLContext, the user's subsequent steps like refitting the estimator will not work after you return from the AutoML call.

Normal AutoML use looks like:
1. Load data
2. Call AutoML
3. Score test dataset
4. Refit estimator on all available data (thrice training)
5. ...any other steps in the user's ML workflow... perhaps model stacking?

Just because the time expired for the AutoML job in step (2), doesn't mean the user doesn't need the next steps.

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:102]: > Won't this use the same Seed at the beginning of each iteration?

Yes, and it is slightly different behavior than current. Previously it could just continue pulling new random numbers from the PRNG; now it will reset between iterations to the same steam of random numbers. The main difference I see is this causes deterministic splitting of the dataset for all iterations in the sweep (if the user sets a seed). This lowers the variability within the sweep iterations, which is a bit less optimal for the Bayesian hyperparamameter optimization, as it can otherwise overfit the repeating splits it sees.

Perhaps we should make a new PRNG seeded on the `_context` seed, and feed the next random as the seed to each new MLContext? This gives the best of both worlds, (1) the user has a now more deterministic run if the call AutoML with the same seed, as the splits are now regenerated identically for each AutoML re-run, and (2) the variability between iterations is maintained.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 6 above)
Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:85]: I don't think we should end all the MLContexts of made experiments. We should always end the MLContext of the training model that is interrupted, which is what the code is currently doing. What if the user would like to use one of the "sub-optimal" models made in the experiment, rather than the model of the best run? If we cancel their respectiveMLContext, they won't be able to use these models. After all, these trained models are all available to use in `experiment.RunDetails.Select(experiment_id).Estimator`. If we don't intend for the user to be able to use these sub-optimal models, we shouldn't even make them available to reach or use.

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:85]: Yes, I think we are saying the same thing. We should only cancel the _one_ active model. 

But currently, if the user, outside of AutoML, cancels the main token, it will not cancel the active training since we don't convey the cancelation from the main token to the one active child token.

Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:95]: Got it, thank you. I've added the second timer to check for MLContext's status per 1 second. I'm looking for a better way of checking for this though, perhaps an object listener of some sort where once an object is canceled, the event listener triggers. Any suggestions for those listeners that work on Windows, Linux and MacOS?

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 7 above)
Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs]: Hi @eerhardt , I am now using `System.Threading.Timer` instead of `System.Timers`, but I'm seeing that the `System.Threading.Timer` is not always canceling, whereas `System.Timers` is. For example, in[ this run](https://dev.azure.com/dnceng/public/_build/results?buildId=869420&view=logs&j=d1af5113-e574-5a31-f7f3-02fc40ea7b26&t=b03e2d69-ce1a-5899-6643-e9b6085777b9&l=372) with `System.Threading.Timer`, cancelation of the long running model did not occur, whereas this was not the case with `System.Timers`.

In addition, I see that `System.Timers` is wrapping around `System.Threading.Timer`. Are there any specific reasons for why `System.Timers` shouldn't be used other than the other's popularity?

Comment (eerhardt) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs]: `System.Threading.Timer` is lower-level, like you said `System.Timers.Timer` is built on top of `Threading.Timer`. `Timers.Timer` is part of the `System.ComponentModel` assembly, and has dependencies on things like `Component` and `ISite`, which are out-of-date .NET Framework 1.0 concepts. Basically, it is heavier-weight and has some "cruft" on it.

> but I'm seeing that the System.Threading.Timer is not always canceling

https://github.com/dotnet/machinelearning/commit/603c0ba8bbd93e21f5fe0e268577bbd6d5fb973a#diff-300431556836fdebc33d05dceb15b3d040a3b52a302967c4ebd2c6c803b9bce2R81

Is the `Timer` object getting garbage collected? I don't see you holding on to it in that commit.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 6 above)
Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:95]: Looking at the `ICancelable` interface, there's no way to register a delegate which would be auto-executed when the context is canceled:
https://github.com/dotnet/machinelearning/blob/6b2d1a5330bf2f73253edf5895baec367dd329a6/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L71-L83

I think polling is an ok choice. If `ICancelable` had a way to register a delegate, the code would be a bit more simple (and react on average 0.5s faster). 

@eerhardt may know of a better solution. Does C# have a built-in property watcher (to watch the [IsCanceled property](https://github.com/dotnet/machinelearning/blob/6b2d1a5330bf2f73253edf5895baec367dd329a6/src/Microsoft.ML.Core/Data/IHostEnvironment.cs#L82))? Or perhaps implement a register-delegate function in `ICancelable` or directly in `MLContext`?

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 9]
```diff
@@ -49,23 +53,70 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+
+        private void MainContextCanceledEvent(object state)
+		{
+            // If the main MLContext is canceled, cancel the ongoing model training and MLContext.
+            if ((_context.Model.GetEnvironment() as ICancelable).IsCanceled)
+            {
+                _logger.Warning("Main MLContext has been canceled. Ending experiment...");
+                _currentModelMLContext.CancelExecution();
+            }
+		}
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:80]: There are tab here instead of spaces. I'd recommend a search/replace of the tab.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 6 above)
Comment (eerhardt) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:95]: Typically in .NET we use `CancellationToken` and `CancellationTokenSource`. You can pass a `CancellationToken` around and register an `Action` that will be called when the corresponding `CancellationTokenSource` is cancelled.

Maybe we could use [`CancellationTokenSource.CancelAfter(TimeSpan)`](https://apisof.net/catalog/System.Threading.CancellationTokenSource.CancelAfter(TimeSpan)) instead of the Timer all together?

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 10]
```diff
@@ -49,23 +56,75 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+                    new TimerCallback(MaxExperimentTimeExpiredEvent), null,
+                    _experimentSettings.MaxExperimentTimeInSeconds * 1000, Timeout.Infinite
+                );
+            }
+            // If given max duration of experiment is 0, only 1 model will be trained.
+            // _experimentSettings.MaxExperimentTimeInSeconds is of type uint, it is
+            // either 0 or >0.
+            else
+                _experimentTimerExpired = true;
+            // Add second timer to check for the cancelation signal from the main MLContext
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:104]: Nit: newline before comment
```suggestion
            // Add second timer to check for the cancelation signal from the main MLContext
            
```

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 11]
```diff
@@ -49,23 +56,75 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+            // to the active child MLContext. This timer will propagate the cancelation
+            // signal from the main to the child MLContexs if the main MLContext is
+            // canceled.
+            _mainContextCanceledTimer = new Timer(new TimerCallback(MainContextCanceledEvent), null, 1000, 1000);
+
+            // Pseudo random number generator to result in deterministic runs with the provided main MLContext's seed and to
+            // maintain variability between training iterations.
+            int? mainContextSeed = ((ISeededEnvironment)_context.Model.GetEnvironment()).Seed;
+            _newContextSeedGenerator = (mainContextSeed.HasValue) ? RandomUtils.Create(mainContextSeed.Value) : RandomUtils.Create();
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:113]: I would set `_newContextSeedGenerator ` to `null` if the user didn't set a seed. 

Then later when creating the new MLContexts, propagate the null by not setting a seed on the child contexts if the user didn't set a seed.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 12]
```diff
@@ -49,23 +56,75 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
                 // get next pipeline
                 var getPipelineStopwatch = Stopwatch.StartNew();
-                var pipeline = PipelineSuggester.GetNextInferredPipeline(_context, _history, _datasetColumnInfo, _task,
-                    _optimizingMetricInfo.IsMaximizing, _experimentSettings.CacheBeforeTrainer, _trainerAllowList);
 
-                var pipelineInferenceTimeInSeconds = getPipelineStopwatch.Elapsed.TotalSeconds;
+                // A new MLContext is needed per model run. When max experiment time is reached, each used
+                // context is canceled to stop further model training. The cancellation of the main MLContext
+                // a user has instantiated is not desirable, thus additional MLContexts are used.
+                _currentModelMLContext = new MLContext(_newContextSeedGenerator.Next());
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:125]: Related to the [comment above](https://github.com/dotnet/machinelearning/pull/5445/files#r514683136), to propagate the lack of a seed:
```suggestion
                _currentModelMLContext = _newContextSeedGenerator == null ? new MLContext() : new MLContext(_newContextSeedGenerator.Next());
```

File: src/Microsoft.ML.AutoML/Experiment/SuggestedPipeline.cs [hunk 13]
```diff
@@ -52,6 +52,11 @@ public override int GetHashCode()
             return ToString().GetHashCode();
         }
 
+        public MLContext GetContext()
+		{
+            return _context;
+		}
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/SuggestedPipeline.cs:58]: Nit: tabs used instead of spaces

**Review by justinormont — APPROVED** [review]
LGTM; thanks for a great PR. 

One remaining slight improvement is to propagate the lack of a seed:
* https://github.com/dotnet/machinelearning/pull/5445#discussion_r514683136
* https://github.com/dotnet/machinelearning/pull/5445#discussion_r514686504

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 7 above)
Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs]: Got it, thank you for explaining. I have made it so that the `Timer` objects are not garbage collected by refencing them outside of the `Execute()`. This way, when that function is complete, the `Timer` objects will still be accessible, which will prevent them from being GCed until the entire Experiment is complete.

**Review by antoniovs1029 — APPROVED** [review]
LGTM

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs (hunk 11 above)
Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:114]: I was thinking something similar to:
```suggestion
            _newContextSeedGenerator = (mainContextSeed.HasValue) ? RandomUtils.Create(mainContextSeed.Value) : null;
```

Then the line below can see the `null` and not set a seed for the child contexts. Alternatively, we could create the PRNG here, but not use it later by checking for `mainContextSeed.HasValue` instead of `_newContextSeedGenerator  == null`.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 14]
```diff
@@ -49,60 +56,122 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+
+            // Add second timer to check for the cancelation signal from the main MLContext
+            // to the active child MLContext. This timer will propagate the cancelation
+            // signal from the main to the child MLContexs if the main MLContext is
+            // canceled.
+            _mainContextCanceledTimer = new Timer(new TimerCallback(MainContextCanceledEvent), null, 1000, 1000);
+
+            // Pseudo random number generator to result in deterministic runs with the provided main MLContext's seed and to
+            // maintain variability between training iterations.
+            int ? mainContextSeed = ((ISeededEnvironment)_context.Model.GetEnvironment()).Seed;
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:113]: nit:
```suggestion
            int? mainContextSeed = ((ISeededEnvironment)_context.Model.GetEnvironment()).Seed;
```

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 15]
```diff
@@ -49,60 +56,122 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+                _currentModelMLContext.CancelExecution();
+            }
+        }
+
+        private void MainContextCanceledEvent(object state)
+        {
+            // If the main MLContext is canceled, cancel the ongoing model training and MLContext.
+            if ((_context.Model.GetEnvironment() as ICancelable).IsCanceled)
+            {
+                _logger.Warning("Main MLContext has been canceled. Ending experiment...");
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:80]: Will `_mainContextCanceledTimer` keep running after this? If so, the user will get multiple warnings until the model returns and the timer is garbage collected.

Perhaps could either cancel the timer, or add a boolean to track if it was run.

Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:80]: Good point, added changes to properly stop timer and never restart.

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:80]: Thanks #Resolved

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 16]
```diff
@@ -49,60 +56,125 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
+                    // If after third run, all runs have failed so far, throw exception
+                    if (_history.Count() == 3 && _history.All(r => !r.RunSucceeded))
+                    {
+                        throw new InvalidOperationException($"Training failed with the exception: {_history.Last().Exception}");
+                    }
                 }
-
-                // If after third run, all runs have failed so far, throw exception
-                if (_history.Count() == 3 && _history.All(r => !r.RunSucceeded))
+                catch (OperationCanceledException e)
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:166]: Might make sense to catch the `OperationCanceledException` where the other AutoML iteration errors are caught:
https://github.com/dotnet/machinelearning/blob/f87a3bbd8adb12934dae0a0060813ce9b7500664/src/Microsoft.ML.AutoML/Experiment/Runners/RunnerUtil.cs#L26-L51

Comment (mstfbl) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:166]: I figured it's better to catch `OperationCanceledException` in `Execute()` as the timers that triggers that exception are started and defined in `Execute()` as well. Plus catching `OperationCanceledException` in `RunnerUtil.cs` requires returning a whole new `(ModelContainer model, TMetrics metrics, Exception exception, double score)` tuple, whereas when caught in `Execute()`, we can send the same `iterationResults` in `Execute()` and the same `(ModelContainer model, TMetrics metrics, Exception exception, double score)` tuple as should be.

File: src/Microsoft.ML.AutoML/Experiment/Experiment.cs [hunk 17]
```diff
@@ -49,60 +56,125 @@ internal class Experiment<TRunDetail, TMetrics> where TRunDetail : RunDetail
...
-                    break;
+                    var iterationStopwatch = Stopwatch.StartNew();
+
+                    // get next pipeline
+                    var getPipelineStopwatch = Stopwatch.StartNew();
+
+                    // A new MLContext is needed per model run. When max experiment time is reached, each used
+                    // context is canceled to stop further model training. The cancellation of the main MLContext
+                    // a user has instantiated is not desirable, thus additional MLContexts are used.
+                    _currentModelMLContext = _newContextSeedGenerator == null ? new MLContext() : new MLContext(_newContextSeedGenerator.Next());
```
Comment (LittleLittleCloud) [inline src/Microsoft.ML.AutoML/Experiment/Experiment.cs:131]: Will this stop user from getting log from the on-trainig context? as the context that is used for training will be different from the context where AutoML experiment is created

Comment (LittleLittleCloud) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:131]: @justinormont @mstfbl  @JakeRadMSFT

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:131]: @LittleLittleCloud: Good point. Have you seen issues?

We can always duplicate the logger. Or attach a logger to the new context, and when called, have it pass the message to the original context.

Comment (LittleLittleCloud) [reply src/Microsoft.ML.AutoML/Experiment/Experiment.cs:131]: Yes, in Image classification we subscribe to the log channel to show training progress. It's quite important since image-classification training is way more time consuming than other scenarios and we need to show something to let users know the training progress
