### PR TITLE
Replace DV data type system with .NET standard type system.

### LINKED ISSUE #673: .NET data type system instead of DvTypes
# .NET data type system instead of DvTypes
## Motivation
Machine Learning datasets often have missing values and to accommodate them along with C# native
types without increasing the memory footprint DvType system was created. If we were to use
`Nullable<T>` then we are looking at additional memory for `HasValue` boolean field plus another 3
bytes for 4 byte alignment. The C# native types that are replaced using DvTypes are bool as DvBool,
sbyte as DvInt1, int16 as DvInt2, int32 as DvInt4, int64 as DvInt8, DvDateTime as System.DateTime,
DvDateTimeZone as combination of DvDateTime and DvInt2 offset, DvTimeSpan as SysTimeSpan and string
as DvText. Float and Double types already have a special value called NaN that can be used for
missing value. DvType system achieves a smaller memory footprint by denoting special value for
missing value which is usually the smallest number that can be represented by the native type that
is encapsulated by DvType, example, DvInt1's missing value indicator would be SByte.MinValue and in
the case of types that represent date/time types it is a value that represent maximum ticks. 

We plan to remove DvTypes to make IDataView a general commodity that can be used in other products
and for this to happen it would be nice if it did not having a dependency on a special type system.
If in future we find having DvTypes was useful then we can consider exposing it natively from .NET
platform. Once we remove DvTypes then ML.NET platform will be using native non-nullable C# types.
Float or double types can be used to represent missing value.

## Column Types 
Columns in ML.NET make up the dataset and `ColumnType` defines a column. At high level there are two
kinds of column, first is `PrimitiveType` and that comprises of types such as `NumberType`,
`BoolType`, `TextType`, `DateTimeType`, `DateTimeZoneType`, `KeyType`, second is `Structured type`
and it comparises of `VectorType`. `ColumnType` is primarily made up of `Type` and `DataKind`.
`Type` could refer to any type but it is instantiated with a type referred by `DataKind` which is an
identifer for data types that comprises of DvTypes, native C# types such as float, double and custom
big integer UInt128.  

## Type conversion
DvTypes have implicit and explicit override for assignment operator that handles type conversion.
Lets consider DvInt1 for example:

| To  | From | Current behavior
|:-:|:-:|:-:
| DvInt1 | sbyte | Copy the value as it is 
| DvInt1 | sbyte? | Assign missing value if null otherwise copy the value as it is 
| sbyte | DvInt1 | Copy if not a missing value otherwise throw exception 
| sbyte? | DvInt1 | Assign null for missing values otherwise copy over 
| DvInt1 | DvBool | Assign missing value for a missing value otherwise copy value over | sbyte = bool?
| DvInt1 | DvInt2 | Cast raw value from short to sbyte and compare it with original value if they are not same assign missing value otherwise casted value 
| DvInt1 | DvInt4 | Same as above
| DvInt1 | DvInt8 | Same as above 
| DvInt1 | Float |
| DvInt1 | Double | Same as above 
| Float | DvInt1 | Assign NaN for missing value 
| Double | DvInt1 | Same as above

Similar conversion rules exist for DvInt2, DvInt4, DvInt8 and DvBool. 

## Logical, bitwise and numerical operators
Operations such as `==`, `!=`, `!`, `>`, `>=`, `<`, `<=`, `+`,`-`,`*`,`pow`,`|`,`&` take place
between same DvTypes only. They also handle missing values and in the case of arithmetic operators
overflow is also handled. Most of these overrides are implemented but only few are actively used.
Whenever there is an overflow the resulting value is represented as missing value and the same goes
when one of the operands is a missing value.

## Serialization
DvTypes have their own codecs for efficiently compressing data and writing it to disk, for example,
to write DvBool to disk, two bits are used to represent a boolean value, 0x00 is false, 0x01 is true
and 0x10 is missing value indicator. Boolean values are written at the level of int32 which has 32
bits that can accommodate 32/2 or 16 boolean values in 4 bytes as opposed to using 1 byte per
boolean value using the naive approach that does not even handle missing value. We can reuse this
approach to serialize bool by using one bit instead of two. DvInt* codecs need not be changed at
all. DateTime and DvText codecs will require some changes.

## Intermediate Language(IL) code generation
ML.NET contains a mini compiler that generates IL code at runtime for peak and poke functions that
basically perform reflection of objects to set and get values in a more performant manner. Here we
can use OpCodes.Stobj to emit IL code for `DvTimeSpan`,`DvDateTime`, `DvDateTimeZone` and
`ReadOnlyMemory<char>` types.

# New Behavior 
* `DvInt1`, `DvInt2`, `DvInt4`, `DvInt8` will be replaced with `sbyte`, `short`, `int` and `long`
  respectively.
  * Conversions will conform to .NET standard conversions.
  * Types will be converted using casting and this might cause underflow and overflow and therefore
    behavior is undefined here, example, casting `long` to `sbyte` will result in assigning of low 8
    bits from long to sbyte. ML.NET projects by default are unchecked because checked is expensive
    and hence used in code blocks where it is needed.
    ```
    > unchecked((sbyte)long.MaxValue)
    -1
    ```
  * Conversion from `Text` to `Integer` type is done by first converting `Text` to `long` value in
    the case of positive number and `ulong` in the case of negative number and then validating this
    value is within the legal bounds of the type that it is being converted to from `Text` type,
    example, legal bound for `sbyte` is -128 to 127, so converting "-129" or "128" will result in an
    exception, also converting a value that is out of legal bounds for a `long` type will also
    result in an exception.
    ``` 
    var c = Convert.ToSByte("129");
    Value was either too large or too small for a signed byte.
    sbyte.Parse(string, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
    System.Convert.ToSByte(string)
    ```

* `DvTimeSpan`, `DvDateTime` and `DvDateTimeZone` will be replaced with `TimeSpan`, `DateTime` and
  `DateTimeOffset` respectively.
  * Offset in `DataTimeOffset` is represented as long because it records the ticks. Previously this
    was represented as DvInt2 or short in `DvDateTimeZone` because it was recorded as minutes and
    due to this it had a smaller footprint on the disk. With offset being long the footprint will
    increase, one work around is to convert it to minutes before writing and then converting minutes
    back to ticks but this might lead to loss in precision. Since DataTime is very rarely used in
    Machine Learning so I'm not sure if it is worth making an optimization here.

* `DvText` will be replaced with `ReadOnlyMemory<char>`.
  * `ReadOnlyMemory<char>` does not implement `IEquatable<T>` and due to this it cannot be be used a
    type in `GroupKeyColumnChecker` in `Cursor` in GroupTransform. The workaround for this is to
    remove the `IEquatable<T>` contraint on the type and instead use if else to check if the type
    implements `IEquatable<T>` then cast and call `Equals` method otherwise check if the type is of
    `ReadOnlyMemory<char>` then use its utility method for equality otherwise throw an exception.
  * `ReadOnlyMemory<char>` does not implement `GetHashCode()` and due to this it cannot be used as a
    key in a dictionary in `ReconcileSlotNames<T>` in EvaluatorUtils.cs. The workaround for this is
    to use string representation of `ReadOnlyMemory<char>` as a key. While this is wastage of memory
    but its not too bad because this is only used at the end of evaluation phase and the number of
    strings allocated here will be roughly proportional to the number of classes.
  * Due to above limitations in `ReadOnlyMemory<char>` it is still under discussion how to best
    replace DvText with `ReadOnlyMemory<char>`.

* `DvBool` will be replaced with bool.       
  * `GetPredictedLabel` and `GetPredictedLabelCore` will result in an undefined behavior in the case
    where score contains a missing value represented as NaN. Here we will default to false.

* Backward compatiblity when reading `IDV` files written with `DvTypes`.
  * `Integers` are read as they were written to disk, i.e minimum value of the corresponding data
      type in the case of missing value.
  * `Boolean` is read using the old codec, where two bits are used per value and missing values are
      converted to `false` to fit in `bool` type.
  * `DateTime`, `DateTimeSpan`, `DateTimeZone` use `long` and `short` type underneath to represent
      ticks and offset and they are converted using the `Integer` scheme defined above. In the case
      where ticks or offset is read and found to contain missing value represented as a minimum of
      the underlying type then it is converted to default value of that type to prevent an exception
      from `DateTime` or `TimeSpan` or `DateTimeOffset` class as such minimum values indicate an
      invalid date. 
  * `DvText` is read as it is. Missing values when being converted to Integer types are converted to
    minimum value of that `integer` type and empty string is converted to `default` value of that
    `integer` type.

* TextLoader
  * Will throw an exception if it encounters missing value.
  * Will convert empty string to `default` values of type it is being converted to.

* Parquet Loader
  * Will throw an exception for nullables or overflow.

# Future consideration
Introduce an option in the loader whether to throw an exception in the case of missing value or just
replace them with `default` values. With the current design we will throw an exception in the case
of missing for Text Loader and Parquet loader but not IDV(Binary Loader).

CC: @eerhardt @Zruty0 @Ivanidzo4ka @TomFinley @shauheen

### PR DESCRIPTION
**Pull request by codemzs**
This change replaces DvType system with .NET standard data type system and fixes #673 

| Old Type | New Type  
|:-:|:-:
| DvInt1 | `sbyte`  
| DvInt2 | `short`  
| DvInt4 | `int`
| DvInt8 | `long`  
| DvBool | `bool`  
| DvDateTime | `DateTime`
| DvDateTimeZone | `DateTimeOffset`  
| DvTimeSpan | `TimeSpan`  
| DvText | `ReadOnlyMemory<char>`

### CODE REVIEW

File: src/Microsoft.ML.Core/Data/MetadataUtils.cs [hunk 1]
```diff
@@ -295,7 +295,7 @@ public static IEnumerable<int> GetColumnSet(this ISchema schema, string metadata
         /// Returns <c>true</c> if the specified column:
         ///  * is a vector of length N (including 0)
         ///  * has a SlotNames metadata
-        ///  * metadata type is VBuffer&lt;DvText&gt; of length N
+        ///  * metadata type is VBuffer&lt;ReadOnlyMemory&gt; of length N
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/MetadataUtils.cs]: >ReadOnlyMemory [](start = 43, length = 14)

If you wanted to read it out it would be not `ReadOnlyMemory` but `ReadOnlyMemory&ltchar&gt`, but this is why we have `<see` tags in the XML docs.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 2]
```diff
@@ -0,0 +1,399 @@
...
+using System.Collections.Generic;
+using System.Text;
+
+namespace Microsoft.ML.Runtime.Data
+{
+    public static class ReadOnlyMemoryUtils
+    {
+
+        /// <summary>
+        /// This implements IEquatable's Equals method.
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >This implements IEquatable's Equals method. [](start = 12, length = 43)

It couldn't possibly be implementing an interface method since this is a static method on a static class, and even if it wasn't you couldn't make `ReadOnlyMemory<char>` implement any interface anyway, since it is not a type under your control.

I *think* you meant to say it was a utility function out of which one could make an `IEquatityComparer<ReadOnlyMemory<char>>`, but it's difficult to be certain.

Comment (TomFinley) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Also please try to use `<see` tags.

---
In reply to: [216126127](https://github.com/dotnet/machinelearning/pull/863#discussion_r216126127) [](ancestors = 216126127)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 3]
```diff
@@ -0,0 +1,399 @@
...
+                if (memory.Span[i] != b.Span[i])
+                    return false;
+            }
+            return true;
+        }
+
+        /// <summary>
+        /// Compare equality with the given system string value.
+        /// </summary>
+        public static bool EqualsStr(string s, ReadOnlyMemory<char> memory)
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >EqualsStr [](start = 27, length = 9)

Is this different method necessary due to perf reasons of `s.AsMemory`?

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 4]
```diff
@@ -0,0 +1,399 @@
...
+        public static bool Equals(ReadOnlyMemory<char> b, ReadOnlyMemory<char> memory)
+        {
+            if (memory.Length != b.Length)
+                return false;
+
+            Contracts.Assert(memory.IsEmpty == b.IsEmpty);
+
+            for (int i = 0; i < memory.Length; i++)
+            {
+                if (memory.Span[i] != b.Span[i])
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >Span [](start = 27, length = 4)

Please store the spans as a variable upfront, then operate on them. These calls to `.Span` property are not free. Here and everywhere.

Consider this code.

```csharp
class Program
{
    private static void TimeTest(string str)
    {
        long temp = 0;

        var sw = new Stopwatch();
        const int trials = 1_000_000_000;

        sw.Restart();
        for (int i = 0; i < trials; ++i)
            temp += str[0];
        sw.Stop();
        Console.WriteLine($"{sw.Elapsed} on string");
        temp = 0;

        sw.Restart();
        var mem = str.AsMemory();
        for (int i = 0; i < trials; ++i)
            temp += mem.Span[0];
        sw.Stop();
        Console.WriteLine($"{sw.Elapsed} on memory.Span");
        temp = 0;

        sw.Restart();
        var span = mem.Span;
        for (int i = 0; i < trials; ++i)
            temp += span[0];
        sw.Stop();
        Console.WriteLine($"{sw.Elapsed} on a stored span");
    }

    private static void Main(string[] args)
    {
        TimeTest("hello");
    }
}
```

When compiled and run in .NET Core 2.1, in a release build, the timings are this:

```
00:00:00.4667924 on string
00:00:01.8801733 on memory.Span
00:00:00.2327934 on a stored span
```

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 5]
```diff
@@ -0,0 +1,399 @@
...
+            if (memory.IsEmpty)
+                yield break;
+
+            if (separators == null || separators.Length == 0)
+            {
+                yield return memory;
+                yield break;
+            }
+
+            int ichMin = 0;
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >ichMin [](start = 16, length = 6)

As far as I see both `ichMin` and `ichLim` could, here and most methods in this file, be replaced with direct usage of the `0` literal and `memory.Length` (or, more precisely, `span.Length` since we should be storing the span upfront, see above) literal. This would both simplify the code and make it more clear.

Look at it this way. If we had code over an array `a` that looked like this:

```csharp
for (int i=0; i<a.Length; ++i)
    DoSomething(a[i]);
```

we certainly would not welcome any movement to change the code to this.

```csharp
int min = 0;
int lim = a.Length;
for (int i=min; i<lim; ++i)
    DoSomething(a[i]);
```

That's less clear and needlessly verbose.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 6]
```diff
@@ -0,0 +1,399 @@
...
+            // Note that we don't use any fields of "this" here in case one
+            // of the out parameters is the same as "this".
+            left = memory.Slice(ichMin, ichCur - ichMin);
+            right = memory.Slice(ichCur + 1, ichLim - ichCur - 1);
+            return true;
+        }
+
+        /// <summary>
+        /// Splits this instance on the left-most occurrence of an element of separators character array and
+        /// produces the left and right ReadOnlyMemory values. If this instance does not contain any of the
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >ReadOnlyMemory [](start = 40, length = 14)

Another textual reference to a non-generic `ReadOnlyMemory` structure. I think these can be replaced more or less well with `<see cref="ReadOnlyMemory{char}"/>`.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 7]
```diff
@@ -0,0 +1,399 @@
...
+                Contracts.Assert(j == ichLim);
+                if (min != j)
+                    sb.Append(memory, min, j - min);
+            }
+        }
+
+        // REVIEW: Can this be faster?
+        private static bool ContainsChar(char ch, char[] rgch)
+        {
+            Contracts.CheckNonEmpty(rgch, nameof(rgch));
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >Contracts.CheckNonEmpty(rgch, nameof(rgch)); [](start = 12, length = 44)

Since there's that review comment (though I suspect it was just copy/pasted over), yes, this can be faster.

First this is a private method that you're calling repeatedly in tight loops in the split code. An *assert* on the non-emptyness of the input is appropriate for sure, and you ought to check that the code is unreachable in any situation where the separators fed in should not be null, but other than that it seems fine. A check is code run all the time even in a release build, which is not needed here.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 8]
```diff
@@ -0,0 +1,399 @@
...
+                    return true;
+            }
+            return false;
+        }
+
+        public static StringBuilder AppendAll(this StringBuilder sb, ReadOnlyMemory<char> memory) => Append(sb, memory, 0, memory.Length);
+
+        public static StringBuilder Append(this StringBuilder sb, ReadOnlyMemory<char> memory, int startIndex, int length)
+        {
+            Contracts.Assert(startIndex >= 0, nameof(startIndex));
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >Assert [](start = 22, length = 6)

In contrast, this, on the other hand, is a public method in a public class, and so a check is appropriate, rather than the assert written here.

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs [hunk 9]
```diff
@@ -70,9 +70,12 @@ public enum Result
             Error = 3
         }
 
-        public static Result Parse(out Single value, string s, int ichMin, int ichLim)
+        public static Result Parse(out Single value, ReadOnlyMemory<char> s)
         {
-            Contracts.Assert(0 <= ichMin && ichMin <= ichLim && ichLim <= Utils.Size(s));
+            int ichMin = 0;
+            int ichLim = s.Length;
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: Similar comments as in other file. You cannot perhaps get rid of `ichMin` (though it should be simplified to `ich` or `i`, since it definitely isn't a `min` in any meaningful sense), but bounds checks ought to be against the length of the input `s`.

Once you do that, this assert becomes somewhat pointless, since it simplifies to this.

```csharp
i = 0;
Contracts.Assert(0 <= i && i <= s.Length && s.Length <= s.Length);
```

which obviously is not a helpful assert since its very existence causes more confusion than it addresses.

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs [hunk 10]
```diff
@@ -81,14 +84,14 @@ public static Result Parse(out Single value, string s, int ichMin, int ichLim)
                     value = 0;
                     return Result.Empty;
                 }
-                if (!char.IsWhiteSpace(s[ichMin]))
+                if (!char.IsWhiteSpace(s.Span[ichMin]))
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: >Span [](start = 41, length = 4)

Similar comments about repeated calls on `Span`.

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs [hunk 11]
```diff
@@ -160,15 +164,15 @@ public static Result Parse(out Double value, string s, int ichMin, int ichLim)
...
+                if (!char.IsWhiteSpace(s.Span[ichEnd]))
                     return Result.Extra;
                 ichEnd++;
             }
 
             return Result.Good;
         }
 
-        public static bool TryParse(out Single value, string s, int ichMin, int ichLim, out int ichEnd)
+        public static bool TryParse(out Single value, ReadOnlyMemory<char> s, int ichMin, int ichLim, out int ichEnd)
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: >public static bool TryParse(out Single value, ReadOnlyMemory<char> s, int ichMin, int ichLim, out int ichEnd) [](start = 8, length = 109)

So regarding this:

`ReadOnlyMemory<char> s, int ichMin, int ichLim`

Why was it written that way? Couldn't the caller just slice the memory *themselves* rather than having us pass around ranges, with the necessary complexities that this entails? Isn't that simplification much of the reason we're doing this work in the first place?

This signature can then be simplifed to:

```csharp
public static bool TryParse(out Single value, ReadOnlyMemory<char> s, out int ichEnd)
```

Comment (TomFinley) [reply src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: I think though, you *probably* want all these parse methods to be over `ReadOnlySpan<char>`, rather than `ReadOnlyMemory<char>`.

---
In reply to: [216127480](https://github.com/dotnet/machinelearning/pull/863#discussion_r216127480) [](ancestors = 216127480)

File: src/Microsoft.ML.Core/Utilities/Hashing.cs [hunk 12]
```diff
@@ -68,17 +68,19 @@ public static int HashInt(int n)
...
+
         /// <summary>
         /// Hash the characters in a sub-string. This MUST produce the same result
         /// as HashString(str.SubString(ichMin, ichLim - ichMin)).
         /// </summary>
         public static uint HashString(string str, int ichMin, int ichLim)
         {
             Contracts.Assert(0 <= ichMin & ichMin <= ichLim & ichLim <= Utils.Size(str));
-            return MurmurHash((5381 << 16) + 5381, str, ichMin, ichLim);
+            return MurmurHash((5381 << 16) + 5381, str.AsMemory().Slice(ichMin, ichLim - ichMin));
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/Hashing.cs]: >str.AsMemory() [](start = 51, length = 14)

`.AsMemory` is a pretty horrifyingly slow operation from my timings of it. I hope we aren't calling this too often.

File: src/Microsoft.ML.HalLearners/OlsLinearRegression.cs [hunk 13]
```diff
@@ -706,7 +706,7 @@ public override void SaveSummary(TextWriter writer, RoleMappedSchema schema)
                 for (int i = 0; i < coeffs.Length; i++)
                 {
                     var name = names.GetItemOrDefault(i);
-                    writer.WriteLine(format, i, DvText.Identical(name, DvText.Empty) ? $"f{i}" : name.ToString(),
+                    writer.WriteLine(format, i, ReadOnlyMemoryUtils.Equals(name, String.Empty.AsMemory()) ? $"f{i}" : name.ToString(),
```
Comment (TomFinley) [inline src/Microsoft.ML.HalLearners/OlsLinearRegression.cs]: >ReadOnlyMemoryUtils.Equals(name, String.Empty.AsMemory()) [](start = 48, length = 57)

Considering why this thing was useful in the first place (distinguishing missing from empty values), a simple `name.Length == 0` is a perfectly adequate replacement for this `ReadOnlyMemoryUtils.Equals(name, String.Empty.AsMemory())`.

Also do note that a `default(ReadOnlyChar<char>)` *is* the empty char span.

File: src/Microsoft.ML.Data/Utilities/ModelFileUtils.cs [hunk 14]
```diff
@@ -188,7 +189,7 @@ public static IDataLoader LoadLoader(IHostEnvironment env, RepositoryReader rep,
         }
 
         /// <summary>
-        /// REVIEW: consider adding an overload that returns <see cref="VBuffer{DvText}"/>
+        /// REVIEW: consider adding an overload that returns ReadOnlyMemory/>
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/Utilities/ModelFileUtils.cs]: >ReadOnlyMemory [](start = 61, length = 14)

This comment got mangled.

**Comment by TomFinley** [comment]
>             Assert.True(error);

Are you aware of `Assert.Throws`?

```csharp
var ex = Assert.ThrowsAny<Exception>(() => mapper(ref src, ref dst));
Assert.Equal("Value could not be parsed from text to sbyte.", ex.Message);
```

Two lines instead of twelve, not bad.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:56 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by TomFinley** [comment]
> 40	0				0

Uh oh. Previously we wrote missing float as missing text. Now you are writing missing float as empty text. That, if re-parsed, will be parsed as 0. Until then the text saver is no longer reversible.

You will have to instead render a missing float as something like `"NaN"` or somesuch. This would be a change in the conversion code, probably.

---
Refers to: test/BaselineOutput/SingleRelease/SymSGD/SymSGD-CV-breast-cancer.txt:17 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by TomFinley** [comment]
>     public class DataTypesTest : TestDataViewBase

Please add a test somewhere in here to verify that converting a `NaN` float to string then back again does not throw and is itself `NaN`.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:12 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by TomFinley** [comment]
>         

I see extra spaces here.

---
Refers to: test/Microsoft.ML.Tests/TextLoaderTests.cs:142 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by TomFinley** [comment]
>     public class TextLoaderTestPipe : TestDataPipeBase

Possibly in this class, but at least somewhere, there ought to be a test that should check saving a file with missing values, then parsing it back, works, now that we have removed missing value support for text. This should I hope catch the bug.

(Also of course please seal the class.)

---
Refers to: test/Microsoft.ML.Tests/TextLoaderTests.cs:19 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 15]
```diff
@@ -1036,14 +978,14 @@ public ValueGetter<T> GetNAOrDefaultGetter<T>(ColumnType type)
         public void Convert(ref BL src, ref SB dst)
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/Data/Conversion.cs]: I'm not sure if this is the source of the text-saver bug or a separate bug, but either way this ought to be fixed as well.

Comment (codemzs) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: Do you mean the two functions above? 

---
In reply to: [216129079](https://github.com/dotnet/machinelearning/pull/863#discussion_r216129079) [](ancestors = 216129079)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 3 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: You can say that.

---
In reply to: [216126482](https://github.com/dotnet/machinelearning/pull/863#discussion_r216126482) [](ancestors = 216126482)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 6 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: <see cref="ReadOnlyMemory{char}"/>  gives an error but apparently it needs to be <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/>

---
In reply to: [216127057](https://github.com/dotnet/machinelearning/pull/863#discussion_r216127057) [](ancestors = 216127057)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 3 above)
Comment (TomFinley) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Would you say that?

---
In reply to: [216189037](https://github.com/dotnet/machinelearning/pull/863#discussion_r216189037) [](ancestors = 216189037,216126482)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 5 above)
Comment (TomFinley) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: > ichLim might be worth keeping since we don't want to call memory.Length multiple times.

Why? Are you under the impression that calling this on a `ReadOnlySpan<char>` is a perf hit? Have you checked?

Just reactivating, since it reads like you aren't going to do this.

---
In reply to: [216189476](https://github.com/dotnet/machinelearning/pull/863#discussion_r216189476) [](ancestors = 216189476,216126883)

Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: No, I did not check but based on your comment for Span I assumed it might also be the case for Length but may be I'm wrong. I will replace ichLim as well.

---
In reply to: [216192013](https://github.com/dotnet/machinelearning/pull/863#discussion_r216192013) [](ancestors = 216192013,216189476,216126883)

File: src/Microsoft.ML.Data/Data/Conversion.cs (hunk 15 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: Probably. I am trying to give you a hint of where your bug is, however I need you to fix it.

---
In reply to: [216184946](https://github.com/dotnet/machinelearning/pull/863#discussion_r216184946) [](ancestors = 216184946,216129079)

Comment (codemzs) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: I fixed the bug even before I read this comment but got confused after reading it so I asked. I believe the bug is in the functions above this one, where we need to print special value for NaN so that when they are converted back to float/double they are parsed as NaN instead of default.

Thanks for finding the float/double to text bug. 

---
In reply to: [216192538](https://github.com/dotnet/machinelearning/pull/863#discussion_r216192538) [](ancestors = 216192538,216184946,216129079)

File: src/Microsoft.ML.Core/Utilities/Hashing.cs (hunk 12 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Utilities/Hashing.cs]: We should take this issue up with the .Net team. I don't understand why ReadOnlyMemory<char> cannot be instantiated with a string? It does have an implicit operator for assignment with T[].

---
In reply to: [216127951](https://github.com/dotnet/machinelearning/pull/863#discussion_r216127951) [](ancestors = 216127951)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 5 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Span doing additional computation is also concerning to me. We need to take this up with the .NET team and provide this feedback. 

---
In reply to: [216194473](https://github.com/dotnet/machinelearning/pull/863#discussion_r216194473) [](ancestors = 216194473,216192140,216192013,216189476,216126883)

**Comment by eerhardt** [comment]
>                     fString = null

I think this should stay `null` to keep the same coverage.

---
Refers to: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs:402 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = True)

**Comment by eerhardt** [comment]
>                 new ClassWithArrays() { fInt = new int[3] { -2, 1, 0 }, fFloat = new float[3] { 0.99f, 0f, -0.99f }, fString = new string[2] { "", "" } },

This should stay `null`.

---
Refers to: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs:664 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>                 new ClassWithArrayProperties() { IntProp = new int[3] { -2, 1, 0 }, FloatProp = new float[3] { 0.99f, 0f, -0.99f }, StringProp = new string[2] { "", "Tom" } },

stay `null`?

---
Refers to: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs:729 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
> using System;

Necessary?

---
Refers to: test/Microsoft.ML.Tests/Scenarios/TensorflowTests.cs:13 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
> using System;

Necessary?

---
Refers to: test/Microsoft.ML.Tests/Scenarios/IrisPlantClassificationWithStringLabelTests.cs:10 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
> using System;

I won't comment on each one, but all the files in this folder only have `using System;` additions.  Are they all necessary?

---
Refers to: test/Microsoft.ML.Tests/Scenarios/PipelineApi/CrossValidation.cs:9 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>                 //On Linux for some reason the baseline file is not found. 

I think this is a casing issue - check the email from me.

---
Refers to: test/Microsoft.ML.TestFramework/TestCommandBase.cs:2038 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>             bool exception = false;

Don't do this.  Use `Assert.Throws` instead.

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:36 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>             catch (Exception ex)

We should be using the specific exception type that is being thrown. (And we shouldn't be throwing `System.Exception`, it should be a specific exception type.)

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:41 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>         val mutable SentimentText : ReadOnlyMemory<char>

This should stay `string`.

---
Refers to: test/Microsoft.ML.FSharp.Tests/SmokeTests.fs:69 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>           SentimentText : ReadOnlyMemory<char>

This should stay `string`.

---
Refers to: test/Microsoft.ML.FSharp.Tests/SmokeTests.fs:136 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>     <PackageReference Include="System.Memory" Version="4.5.1" />

This shouldn't be necessary. All the APIs should be part of `netcoreapp2.1`.

---
Refers to: test/Microsoft.ML.Core.Tests/Microsoft.ML.Core.Tests.csproj:35 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>                         new TextLoader.Column("F2", DataKind.R4, 2),

?? Shouldn't this stay `I4`?

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:69 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>                     "Transforms.ColumnTypeConverter",

?? Why the changes to this test?  It doesn't seem like it should need to be changed.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:1969 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = True)

**Comment by eerhardt** [comment]
>             src = ((long)minValue - 1).ToString().AsMemory();

Is this cast to `(long)` necessary?  `minValue` is already a `long`.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:223 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>                 error = true;

Don't use this pattern.  Use `Assert.Throws` instead.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:239 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>             Assert.True(typeof(TSrc).TryGetDataKind(out DataKind srcDataKind));

`srcDataKind` doesn't appear to be used.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:253 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by eerhardt** [comment]
>                 error = true;

Repeated elsewhere in this file.

---
In reply to: [420020012](https://github.com/dotnet/machinelearning/pull/863#issuecomment-420020012) [](ancestors = 420020012)

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:239 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

File: src/Microsoft.ML.Core/Utilities/Hashing.cs [hunk 16]
```diff
@@ -125,23 +127,21 @@ public static uint MurmurRound(uint hash, uint chunk)
         /// * 0x0800 to 0xFFFF : 1110xxxx 10xxxxxx 10xxxxxx
         /// NOTE: This MUST match the StringBuilder version below.
         /// </summary>
-        public static uint MurmurHash(uint hash, string data, int ichMin, int ichLim, bool toUpper = false)
+        public static uint MurmurHash(uint hash, ReadOnlyMemory<char> data, bool toUpper = false)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Utilities/Hashing.cs]: Since we don't need to store the `ReadOnlyMemory<char>`, this should be a `ReadOnlySpan<char>` instead.

File: src/Microsoft.ML.Api/Microsoft.ML.Api.csproj [hunk 17]
```diff
@@ -15,6 +15,7 @@
 
   <ItemGroup>
      <PackageReference Include="System.CodeDom" Version="$(SystemCodeDomPackageVersion)" />
+     <PackageReference Include="System.Memory" Version="4.5.1" />
```
Comment (eerhardt) [inline src/Microsoft.ML.Api/Microsoft.ML.Api.csproj]: These references flow transitively through project-to-project references. So you should only need it on `Microsoft.ML.Core.csproj`, and all the other .csprojs will automatically get the `PackageReference`.

**Comment by eerhardt** [comment]
We will need to add `System.Memory` as a `<PackageReference` to https://github.com/dotnet/machinelearning/blob/a6e3c0a79c225c84f882cb8c8c6013f070cf0e7a/pkg/Microsoft.ML/Microsoft.ML.nupkgproj#L11-L14

File: src/Microsoft.ML.Api/DataViewConstructionUtils.cs [hunk 18]
```diff
@@ -125,61 +125,11 @@ private Delegate CreateGetter(int index)
...
-                        else if (outputType.GetElementType() == typeof(bool))
-                        {
-                            Ch.Assert(colType.ItemType.IsBool);
-                            return CreateConvertingArrayGetterDelegate<bool, DvBool>(index, x => x);
-                        }
-                        else if (outputType.GetElementType() == typeof(bool?))
-                        {
-                            Ch.Assert(colType.ItemType.IsBool);
-                            return CreateConvertingArrayGetterDelegate<bool?, DvBool>(index, x => x ?? DvBool.NA);
+                            return CreateConvertingArrayGetterDelegate<string, ReadOnlyMemory<char>>(index, x =>  x != null ? x.AsMemory() : "".AsMemory() );
```
Comment (eerhardt) [inline src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: The end should be `ReadOnlyMemory<char>.Empty`

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 19]
```diff
@@ -0,0 +1,397 @@
...
+
+namespace Microsoft.ML.Runtime.Data
+{
+    public static class ReadOnlyMemoryUtils
+    {
+
+        /// <summary>
+        /// Compares two <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/> byte by byte.
+        /// </summary>
+        public static bool Equals(ReadOnlyMemory<char> b, ReadOnlyMemory<char> a)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: We should be using `MemoryExtensions.SequenceEqual` or `MemoryExtensions.CompareTo() == 0` instead. Those methods are optimized to use hardware acceleration under the covers.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 20]
```diff
@@ -0,0 +1,397 @@
...
+            if (s == null)
+                return memory.Length == 0;
+
+            if (s.Length != memory.Length)
+                return false;
+
+            var span = memory.Span;
+            for (int i = 0; i < memory.Length; i++)
+            {
+                if (s[i] != span[i])
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Should use `MemoryExtensions.SequenceEquals` instead.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 21]
```diff
@@ -0,0 +1,397 @@
...
+                    return false;
+            }
+            return true;
+        }
+
+        /// <summary>
+        /// For implementation of <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/>. Uses code point comparison.
+        /// Generally, this is not appropriate for sorting for presentation to a user.
+        /// </summary>
+        public static int CompareTo(ReadOnlyMemory<char> b, ReadOnlyMemory<char> a)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Should use `MemoryExtensions.CompareTo` instead.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 22]
```diff
@@ -0,0 +1,397 @@
...
+            }
+        }
+
+        /// <summary>
+        /// Splits <paramref name="memory"/> on the left-most occurrence of separator and produces the left
+        /// and right <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/> values. If <paramref name="memory"/> does not contain the separator character,
+        /// this returns false and sets <paramref name="left"/> to this instance and <paramref name="right"/>
+        /// to the default <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/> value.
+        /// </summary>
+        public static bool SplitOne(char separator, out ReadOnlyMemory<char> left, out ReadOnlyMemory<char> right, ReadOnlyMemory<char> memory)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: The order of parameters to this method seems wrong.  Typically the `out` parameters are at the end.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 23]
```diff
@@ -0,0 +1,397 @@
...
+            for (; ; ichCur++)
+            {
+                Contracts.Assert(0 <= ichCur && ichCur <= memory.Length);
+                if (ichCur >= memory.Length)
+                {
+                    left = memory;
+                    right = default;
+                    return false;
+                }
+                if (span[ichCur] == separator)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Should use `MemoryExtensions.IndexOf` instead. It is hardware accelerated.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 24]
```diff
@@ -0,0 +1,397 @@
...
+            {
+                left = memory;
+                right = default;
+                return false;
+            }
+
+            var span = memory.Span;
+
+            int ichCur = 0;
+            if (separators.Length == 1)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Use `MemoryExtensions.IndexOfAny` instead?

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 25]
```diff
@@ -0,0 +1,397 @@
...
+            left = memory.Slice(0, ichCur);
+            right = memory.Slice(ichCur + 1, memory.Length - ichCur - 1);
+            return true;
+        }
+
+        /// <summary>
+        /// Returns a <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/> with leading and trailing spaces trimmed. Note that this
+        /// will remove only spaces, not any form of whitespace.
+        /// </summary>
+        public static ReadOnlyMemory<char> Trim(ReadOnlyMemory<char> memory)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: I kind of think we shouldn't have a public method named `Trim` that performs differently than the typical .NET "Trim()" method.  Trim will trim any whitespace, not just spaces.
I think we should either rename the methods, or make them internal.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 26]
```diff
@@ -0,0 +1,397 @@
...
+            while (0 < ichLim && char.IsWhiteSpace(span[ichLim - 1]))
+                ichLim--;
+
+            return memory.Slice(0, ichLim);
+        }
+
+        /// <summary>
+        /// This produces zero for an empty string.
+        /// </summary>
+        public static bool TryParse(out Single value, ReadOnlyMemory<char> memory)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: This feels wrong to have `Parse` on `DoubleParser` and `TryParse` on ReadOnlyMemoryUtils.  I think they should go together.

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs [hunk 27]
```diff
@@ -70,25 +70,26 @@ public enum Result
             Error = 3
         }
 
-        public static Result Parse(out Single value, string s, int ichMin, int ichLim)
+        public static Result Parse(out Single value, ReadOnlyMemory<char> s)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: These methods would be more usable/applicable if they took `ReadOnlySpan<char>` instead. That way if someone only has a Span, they can still call this function.

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs (hunk 11 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: 100% with you!

---
In reply to: [216127512](https://github.com/dotnet/machinelearning/pull/863#discussion_r216127512) [](ancestors = 216127512,216127480)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 25 above)
Comment (TomFinley) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Let's rename at least and make internal if we can. I'm very curious however to see what application requires such a seemingly oddly specifically different semantics

File: src/Microsoft.ML.Core/Data/TypeUtils.cs [hunk 28]
```diff
@@ -23,81 +21,5 @@ public static class TypeUtils
         public static bool IsNA(this R4 src) { return R4.IsNaN(src); }
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/TypeUtils.cs]: I have removed them but I wonder why they were there at the first place? 

---
In reply to: [216447632](https://github.com/dotnet/machinelearning/pull/863#discussion_r216447632) [](ancestors = 216447632)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 23 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: These take Span as input and in our case we have character(s) as input so I will have to convert character to span which I think is expensive because AsMemory() seemed expensive so may be AsSpan might also be?

---
In reply to: [216468406](https://github.com/dotnet/machinelearning/pull/863#discussion_r216468406) [](ancestors = 216468406)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 24 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: These take Span as input and in our case we have character(s) as input so I will have to convert character to span which I think is expensive because AsMemory() seemed expensive so may be AsSpan might also be?

---
In reply to: [216468683](https://github.com/dotnet/machinelearning/pull/863#discussion_r216468683) [](ancestors = 216468683)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 25 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Renamed but internal will throw error due to protection level.

---
In reply to: [216758599](https://github.com/dotnet/machinelearning/pull/863#discussion_r216758599) [](ancestors = 216758599)

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs (hunk 27 above)
Comment (codemzs) [reply src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: So true.

---
In reply to: [216471029](https://github.com/dotnet/machinelearning/pull/863#discussion_r216471029) [](ancestors = 216471029)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 20 above)
Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: That's totally fine. You can easily convert a string to Span using `.AsSpan()`. If we targeted just .NET Core 2.1, there is an implicit conversion. But since we are only .NET Standard 2.0, you need to call the `.AsSpan()` extension method.

The "Performance" section of [this blog post](https://blogs.msdn.microsoft.com/dotnet/2018/08/20/bing-com-runs-on-net-core-2-1/) explains why you want to call these methods - because they are vectorized.

Comment (codemzs) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Awesome!!!

---
In reply to: [216850011](https://github.com/dotnet/machinelearning/pull/863#discussion_r216850011) [](ancestors = 216850011)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 24 above)
Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: You have a `char[] separators` which is simply converted to Span by calling `.AsSpan()` on it. You won't be doing it in a loop, so it won't incur a perf penalty.  Plus IndexOfAny is getting vectorized in .NET Core 3.0.  See [https://github.com/dotnet/coreclr/pull/19790](https://github.com/dotnet/coreclr/pull/19790)

---
In reply to: [216845408](https://github.com/dotnet/machinelearning/pull/863#discussion_r216845408) [](ancestors = 216845408,216468683)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 23 above)
Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: There is an IndexOf overload that takes a single character.  

```
public static int IndexOf<T>(this System.Span<T> span, T value) where T : System.IEquatable<T>
```

---
In reply to: [216845370](https://github.com/dotnet/machinelearning/pull/863#discussion_r216845370) [](ancestors = 216845370,216468406)

**Comment by codemzs** [comment]
>             Assert.True(error);

Nice!!

---
In reply to: [419635980](https://github.com/dotnet/machinelearning/pull/863#issuecomment-419635980) [](ancestors = 419635980)

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/DataTypes.cs:56 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by codemzs** [comment]
>             catch (Exception ex)

We are not throwing, it gets thrown when you try to assign a null value to non-nullable type. This is by design and documented in the spec.

---
In reply to: [420016697](https://github.com/dotnet/machinelearning/pull/863#issuecomment-420016697) [](ancestors = 420016697)

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:41 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

**Comment by codemzs** [comment]
>                     "Transforms.ColumnTypeConverter",

There are missing values and that will cause exception since we don't support missing values anymore for I1, so change it to R4 that supports MVs.

---
In reply to: [420018617](https://github.com/dotnet/machinelearning/pull/863#issuecomment-420018617) [](ancestors = 420018617)

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:1969 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = True)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 26 above)
Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Yes. I shouldn't have to go to `DoubleParser` to call `Parse` and then `ReadOnlyMemoryUtils` to call `TryParse`. The methods go together and belong in the same place.

**Comment by eerhardt** [comment]
>             var ex = Assert.ThrowsAny<Exception>(() => TestCore(pathData, false, new[] { "loader=Parquet{bigIntDates=+}" }, forceDense: true));

We should use the specific type of Exception that is thrown, not just any `Exception`.

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:36 in d45bc2c. [](commit_id = d45bc2cc7768f7b39427567f6126a675e1fa16d8, deletion_comment = False)

File: pkg/Microsoft.ML/Microsoft.ML.nupkgproj [hunk 29]
```diff
@@ -12,6 +12,7 @@
     <PackageReference Include="System.Reflection.Emit.Lightweight" Version="$(SystemReflectionEmitLightweightPackageVersion)" />
     <PackageReference Include="System.Threading.Tasks.Dataflow" Version="$(SystemThreadingTasksDataflowPackageVersion)" />
     <PackageReference Include="System.CodeDom" Version="$(SystemCodeDomPackageVersion)" />
+	<PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />
```
Comment (eerhardt) [inline pkg/Microsoft.ML/Microsoft.ML.nupkgproj]: (nit) tab here. The rest of the file uses spaces.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 30]
```diff
@@ -0,0 +1,333 @@
...
+            if (separators == null || separators.Length == 0)
+            {
+                yield return memory;
+                yield break;
+            }
+
+            if (separators.Length == 1)
+            {
+                char chSep = separators[0];
+                for (int ichCur = 0; ;)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Let's use `MemoryExtensions.IndexOf` here instead. It is vectorized.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 31]
```diff
@@ -0,0 +1,333 @@
...
+
+                    yield return memory.Slice(ichMinLocal, ichCur - ichMinLocal);
+
+                    // Skip the separator.
+                    ichCur++;
+                }
+            }
+            else
+            {
+                for (int ichCur = 0; ;)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Can we use `MemoryExtensions.IndexOfAny` here to simply this code? And also it is getting vectorized in .NET Core 3.0.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 32]
```diff
@@ -0,0 +1,333 @@
...
+                if (min != j)
+                    sb.Append(memory, min, j - min);
+            }
+        }
+
+        private static bool ContainsChar(char ch, char[] rgch)
+        {
+            Contracts.AssertNonEmpty(rgch, nameof(rgch));
+
+            for (int i = 0; i < rgch.Length; i++)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: This should be changed to `return rgch.AsSpan().IndexOf(ch) >= 0`. In the future it can just be `return rgch.AsSpan().Contains(ch)` after we get a build with [https://github.com/dotnet/coreclr/pull/19863](https://github.com/dotnet/coreclr/pull/19863) (i.e. .NET Core 3.0).

Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Although, if you fix the caller to no longer call this method, it can just be deleted all together.

---
In reply to: [217071879](https://github.com/dotnet/machinelearning/pull/863#discussion_r217071879) [](ancestors = 217071879)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 33]
```diff
@@ -0,0 +1,333 @@
...
+            {
+                if (rgch[i] == ch)
+                    return true;
+            }
+            return false;
+        }
+
+        public static StringBuilder AppendAll(this StringBuilder sb, ReadOnlyMemory<char> memory) => Append(sb, memory, 0, memory.Length);
+
+        public static StringBuilder Append(this StringBuilder sb, ReadOnlyMemory<char> memory, int startIndex, int length)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: `ReadOnlyMemory` has a `Slice(start, length)` method.  Why have this overload when you can just have a single method that takes `ReadOnlyMemory` and the caller can `Slice` it anyway they'd like. That way you don't have to do any checking for `startIndex` or `length` to be in the right range. You are guaranteed that the `ReadOnlyMemory` only points to the right memory.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 34]
```diff
@@ -0,0 +1,333 @@
...
+            Contracts.Check(startIndex >= 0, nameof(startIndex));
+            Contracts.Check(length >= 0, nameof(length));
+
+            int ichLim = startIndex + length;
+
+            Contracts.Check(memory.Length >= ichLim, nameof(memory));
+
+            var span = memory.Span;
+            for (int index = startIndex; index < ichLim; index++)
+                sb.Append(span[index]);
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Instead of doing this one element at a time, we should just duplicate the coreclr implementation of this method:

[https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/shared/System/Text/StringBuilder.cs#L1199-L1212](https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/shared/System/Text/StringBuilder.cs#L1199-L1212)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 33 above)
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: >ReadOnlyMemory [](start = 66, length = 14)

Also, you should just take a `ReadOnlySpan<char>` here. That way if the caller only has a span, they can still call this method.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 35]
```diff
@@ -0,0 +1,333 @@
...
+        /// This produces zero for an empty string.
+        /// </summary>
+        public static bool TryParse(ReadOnlyMemory<char> memory, out Double value)
+        {
+            var res = DoubleParser.Parse(out value, memory.Span);
+            Contracts.Assert(res != DoubleParser.Result.Empty || value == 0);
+            return res <= DoubleParser.Result.Empty;
+        }
+
+        public static uint Hash(ReadOnlySpan<char> span, uint seed) => Hashing.MurmurHash(seed, span);
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: A few questions about this function.

1. Why have it when all it does is a simple call forward to another function?  Why not just change all the callers to call the `Hashing` function? That would be one less public method we would need to maintain.
2. If we are going to keep this function, why are the arguments flipped from the MurmurHash function?

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 36]
```diff
@@ -1389,61 +1326,53 @@ private bool TryParseNonNegative(string text, int ich, int lim, out long result)
...
                 result = -(long)val;
-                Contracts.Assert(long.MinValue < result && result <= 0);
-                return true;
+                Contracts.Assert(long.MinValue <= result && result <= 0);
+                return;
             }
 
-            if (!TryParseNonNegative(text, ichMin, ichLim, out val))
+            long sVal;
+            if (!TryParseNonNegative(text.Slice(0), out sVal))
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Data/Conversion.cs]: `text.Slice(0)` is the same thing is `text`, right?  Shouldn't need to `Slice` here.

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 37]
```diff
@@ -1389,61 +1326,53 @@ private bool TryParseNonNegative(string text, int ich, int lim, out long result)
...
-
-            long val;
+            ulong val;
+            var span = text.Span;
             if (span[0] == '-')
             {
-                if (span.Length == 1 ||
-                    !TryParseNonNegative(text, ichMin + 1, ichLim, out val) ||
-                    val > max)
+                if (span.Length == 1 || !TryParseCore(text.Slice(1, text.Length - 1), out val) || (val > ((ulong)max + 1)))
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Data/Conversion.cs]: `text.Slice(1, text.Length - 1)` is the same as `text.Slice(1)`, isn't it?

**Comment by eerhardt** [comment]
>     <PackageReference Include="System.Memory" Version="4.5.1" />

We shouldn't need this PackageReference anymore, because ML.Core references it, and this project references ML.Core.

But if we are going to keep it, `4.5.1` should be changed to `$(SystemMemoryVersion)`

---
Refers to: src/Microsoft.ML.Data/Microsoft.ML.Data.csproj:21 in d45bc2c. [](commit_id = d45bc2cc7768f7b39427567f6126a675e1fa16d8, deletion_comment = False)

File: src/Microsoft.ML.Data/Transforms/HashTransform.cs [hunk 38]
```diff
@@ -670,28 +670,28 @@ private ValueGetter<VBuffer<uint>> ComposeGetterVec(IRow input, int iinfo)
...
         #region Core Hash functions, with and without index
         [MethodImpl(MethodImplOptions.AggressiveInlining)]
-        private static uint HashCore(uint seed, ref DvText value, uint mask)
+        private static uint HashCore(uint seed, ref ReadOnlyMemory<char> value, uint mask)
         {
             Contracts.Assert(Utils.IsPowerOfTwo(mask + 1));
-            if (!value.HasChars)
+            if (value.IsEmpty)
                 return 0;
-            return (value.Trim().Hash(seed) & mask) + 1;
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Transforms/HashTransform.cs]: >Trim() [](start = 26, length = 6)

We used to call `DvText.Trim()` here, which only trims space ' ' characters. Now we are calling ROS.Trim(), which trims all whitespace. My initial calculations say changing this to ROMUtils.TrimSpaces takes off ~2%.

File: src/Microsoft.ML.Data/Transforms/HashTransform.cs [hunk 39]
```diff
@@ -670,28 +670,28 @@ private ValueGetter<VBuffer<uint>> ComposeGetterVec(IRow input, int iinfo)
...
 
         [MethodImpl(MethodImplOptions.AggressiveInlining)]
-        private static uint HashCore(uint seed, ref DvText value, int i, uint mask)
+        private static uint HashCore(uint seed, ref ReadOnlyMemory<char> value, int i, uint mask)
         {
             Contracts.Assert(Utils.IsPowerOfTwo(mask + 1));
-            if (!value.HasChars)
+            if (value.IsEmpty)
                 return 0;
-            return (value.Trim().Hash(Hashing.MurmurRound(seed, (uint)i)) & mask) + 1;
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Transforms/HashTransform.cs]: Same as above here - used to call `DvText.Trim()` but now are calling `Span.Trim()`, which changes behavior and perf.

File: src/Microsoft.ML.Data/Transforms/HashTransform.cs [hunk 40]
```diff
@@ -1063,16 +1063,13 @@ public TextEqualityComparer(uint seed)
...
-                }
+                public bool Equals(ReadOnlyMemory<char> x, ReadOnlyMemory<char> y) => x.Span.SequenceEqual(y.Span);
 
-                public int GetHashCode(DvText obj)
+                public int GetHashCode(ReadOnlyMemory<char> obj)
                 {
-                    if (!obj.HasChars)
+                    if (obj.IsEmpty)
                         return 0;
-                    return (int)obj.Trim().Hash(_seed) + 1;
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Transforms/HashTransform.cs]: >Trim() [](start = 36, length = 6)

One more `DvText.Trim()` => `Span.Trim()` here.

File: src/Microsoft.ML.Data/Transforms/TermTransformImpl.cs [hunk 41]
```diff
@@ -119,15 +119,15 @@ public override TermMap Finish()
                         return new TermMap.TextImpl(_pool);
                     // REVIEW: Should write a Sort method in NormStr.Pool to make sorting more memory efficient.
                     var perm = Utils.GetIdentityPermutation(_pool.Count);
-                    Comparison<int> comp = (i, j) => _pool.GetNormStrById(i).Value.CompareTo(_pool.GetNormStrById(j).Value);
+                    Comparison<int> comp = (i, j) => _pool.GetNormStrById(i).Value.Span.CompareTo(_pool.GetNormStrById(j).Value.Span, StringComparison.InvariantCulture);
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Transforms/TermTransformImpl.cs]: Should this and the below comparisons be `Ordinal` instead?

File: src/Microsoft.ML.Core/Utilities/NormStr.cs [hunk 42]
```diff
@@ -18,37 +19,28 @@ namespace Microsoft.ML.Runtime.Internal.Utilities
...
             Value = str;
             Id = id;
             _hash = hash;
         }
 
-        public override string ToString()
-        {
-            return Value;
-        }
+        public override string ToString() => Value.ToString();
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Utilities/NormStr.cs]: I'm a bit concerned about this change.  Every time someone calls the ToString() method of NormStr it will copy from the ROM<char> to a new string.

I see this used to just hold on to `string` and not `DvText`.  Should we change it back to hold on to `string` instead?  (and do the copy on insertion into the pool, as opposed to potentially every time it is accessed through `NormStr.ToString()`)

/cc @TomFinley

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 43]
```diff
@@ -0,0 +1,325 @@
...
+                return memory;
+
+            while (ichMin < ichLim && span[ichMin] == ' ')
+                ichMin++;
+            while (ichMin < ichLim && span[ichLim - 1] == ' ')
+                ichLim--;
+            return memory.Slice(ichMin, ichLim - ichMin);
+        }
+
+        public static ReadOnlySpan<char> TrimSpaces(ReadOnlySpan<char> span)
```
Comment (ahsonkhan) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Use the existing Trim extension method overload that accepts a trim character.

```C#
span.Trim(' ');
```

The same would apply to the ReadOnlyMemory utility method once we add the new Trim method.
https://github.com/dotnet/corefx/issues/30592

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 44]
```diff
@@ -0,0 +1,325 @@
...
+        }
+
+        public static void AddToStringBuilder(ReadOnlyMemory<char> memory, StringBuilder sb)
+        {
+            Contracts.CheckValue(sb, nameof(sb));
+            if (!memory.IsEmpty)
+                sb.Append(memory);
+        }
+
+        public static void AddLowerCaseToStringBuilder(ReadOnlyMemory<char> memory, StringBuilder sb)
```
Comment (ahsonkhan) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: @eerhardt, with your recent change to add the span-based Append method, we should be able to change this to accept a span instead of a memory.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 45]
```diff
@@ -284,16 +284,15 @@ public static void AddToStringBuilder(ReadOnlyMemory<char> memory, StringBuilder
                 sb.Append(memory);
         }
 
-        public static void AddLowerCaseToStringBuilder(ReadOnlyMemory<char> memory, StringBuilder sb)
+        public static void AddLowerCaseToStringBuilder(ReadOnlySpan<char> span, StringBuilder sb)
```
Comment (ahsonkhan) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Hmm, instead of this custom implementation that traverses the span a character at a time and does the check if ToLower changed it, maybe use the span.ToLowerInvariant(span) to first lower case the entire span, and then just call Append on it directly?

Granted, it would require some unsafe code to change the ReadOnlySpan to a Span, since the destination argument needs to be writable.

Is that feasible?

Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: You would also need to allocate new memory (the receiving span) that way.  Here we are trying to append the `ToLowerInvariant` string into an existing `StringBuilder`. If we took that approach, we would need to allocate some memory to write the `ToLowerInvariant` string into, and then append that to `StringBuilder` - i.e. 2 copies.

IMO it would be better if we had a `span.ToLowerInvariant(StringBuilder)` overload in the framework.  Or some way of getting a `Span` from `StringBuilder` that was of a sufficient size.

File: src/Microsoft.ML.Transforms/Text/WordTokenizeTransform.cs [hunk 46]
```diff
@@ -351,39 +351,39 @@ private ValueGetter<VBuffer<DvText>> MakeGetterVec(IRow input, int iinfo)
...
             {
-                while (rest.HasChars)
+                while (!rest.IsEmpty)
                 {
-                    DvText term;
-                    rest.SplitOne(separators, out term, out rest);
-                    term = term.Trim();
-                    if (term.HasChars)
+                    ReadOnlyMemory<char> term;
+                    ReadOnlyMemoryUtils.SplitOne(rest, separators, out term, out rest);
```
[the remark this answers is not in the document]
Comment (eerhardt) [reply src/Microsoft.ML.Transforms/Text/WordTokenizeTransform.cs]: I'm not sure I follow this comment.  Does it still apply to the latest code?

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 47]
```diff
@@ -0,0 +1,324 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
```
Comment (KrzysztofCwalina) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: @ahsonkhan, this whole file points at holes in our APIs. It would be great to see if we should not pull some of these into the BCL.

Comment (ahsonkhan) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: Agreed. Most of them are either already scheduled for 3.0 or redundant.
- [Split](https://github.com/dotnet/corefx/issues/26528), we should probably add one for Memory\<T\> too.
- [TrimSpaces](https://github.com/dotnet/corefx/issues/31011)
- SplitOne [not sure about this one, although it is relatively common in practice]

The ones related to StringBuilder are interesting:
- AddToStringBuilder
- StringBuilder.Append

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 45 above)
Comment (ahsonkhan) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: > You would also need to allocate new memory (the receiving span) that way.

I was thinking of using the input as the destination. Something like this:
```C#
ReadOnlySpan<char> span = "aAbBcCedbaG";
Span<char> destination = MemoryMarshal.CreateSpan(ref MemoryMarshal.GetReference(span), span.Length);
span.ToLowerInvariant(destination);
sb.Append(span); // or destination
```

Comment (eerhardt) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: It’s not acceptable to change the input.

Comment (ahsonkhan) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: > It’s not acceptable to change the input.

I see. Then, nvm.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs (hunk 47 above)
Comment (KrzysztofCwalina) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: @ahsonkhan, do we have issues for the stringbuilder and splitone operations?

Comment (ahsonkhan) [reply src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: No, we don't, yet. I will create them soon.

File: src/Microsoft.ML.Data/Data/Conversion.cs [hunk 48]
```diff
@@ -1130,24 +1069,23 @@ public bool TryParse(ref TX src, out U8 dst)
...
+            int offset = 2;
             ulong hi = 0;
             ulong num = 0;
             for (int i = 0; i < 2; ++i)
             {
                 for (int d = 0; d < 16; ++d)
                 {
                     num <<= 4;
-                    char c = tx[offset++];
+                    char c = span[offset++];
```
[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: Your code seems to have more CPU cycles but can you please clarify how it has fewer branches?

---
In reply to: [217328366](https://github.com/dotnet/machinelearning/pull/863#discussion_r217328366) [](ancestors = 217328366)

**Comment by codemzs** [comment]
>             var ex = Assert.ThrowsAny<Exception>(() => TestCore(pathData, false, new[] { "loader=Parquet{bigIntDates=+}" }, forceDense: true));

Below we verify the specific type of exception by checking for its message.

---
In reply to: [420677248](https://github.com/dotnet/machinelearning/pull/863#issuecomment-420677248) [](ancestors = 420677248)

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:36 in d45bc2c. [](commit_id = d45bc2cc7768f7b39427567f6126a675e1fa16d8, deletion_comment = False)

**Comment by codemzs** [comment]
>     public class TextLoaderTestPipe : TestDataPipeBase

I have added test for this in DataTypesTest

---
In reply to: [419637006](https://github.com/dotnet/machinelearning/pull/863#issuecomment-419637006) [](ancestors = 419637006)

---
Refers to: test/Microsoft.ML.Tests/TextLoaderTests.cs:19 in 0511d74. [](commit_id = 0511d74661f107f1d3ccc0034335cc59ff2bf3cd, deletion_comment = False)

File: src/Microsoft.ML.Data/Data/Conversion.cs (hunk 48 above)
[the remark this answers is not in the document]
Comment (ahsonkhan) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: > can you please clarify how it has fewer branches?

Instead of two comparisons, you have one.
`if ('0' <= c && c <= '9')` <= this has two comparisons that we `and` together.

`if ((uint)(c - '0') <= ('9'- '0'))` <= this is the suggestion, with a single comparison, and no need to `and` anything.

[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: I believe comparison underneath uses subtraction but will need to check.

**Comment by eerhardt** [comment]
>             var ex = Assert.ThrowsAny<Exception>(() => TestCore(pathData, false, new[] { "loader=Parquet{bigIntDates=+}" }, forceDense: true));

That's not really the same thing. When you test for exceptions you should verify the exception type and optionally you can verify its message.

The code could start throwing `MyCrazyException("Nullable object must have a value.")` and this test would still pass. However, that could break user code that was catching a specific exception type, but is no longer thrown.

---
In reply to: [422599427](https://github.com/dotnet/machinelearning/pull/863#issuecomment-422599427) [](ancestors = 422599427,420677248)

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:36 in d45bc2c. [](commit_id = d45bc2cc7768f7b39427567f6126a675e1fa16d8, deletion_comment = False)

**Comment by codemzs** [comment]
>             var ex = Assert.ThrowsAny<Exception>(() => TestCore(pathData, false, new[] { "loader=Parquet{bigIntDates=+}" }, forceDense: true));

By that logic the code could also throw another exception of the same type and even with the same message..... :)

---
In reply to: [422847966](https://github.com/dotnet/machinelearning/pull/863#issuecomment-422847966) [](ancestors = 422847966,422599427,420677248)

---
Refers to: test/Microsoft.ML.TestFramework/DataPipe/Parquet.cs:36 in d45bc2c. [](commit_id = d45bc2cc7768f7b39427567f6126a675e1fa16d8, deletion_comment = False)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 49]
```diff
@@ -0,0 +1,285 @@
...
+            while (0 < ichLim && char.IsWhiteSpace(span[ichLim - 1]))
+                ichLim--;
+
+            return memory.Slice(0, ichLim);
+        }
+
+        /// <summary>
+        /// Returns a <see cref="ReadOnlyMemory{T}"/> of <see cref="char"/> with trailing whitespace trimmed.
+        /// </summary>
+        public static ReadOnlyMemory<char> TrimEndWhiteSpace(ReadOnlyMemory<char> memory, ReadOnlySpan<char> span)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: I think this method is a little awkward and should be removed. It is assuming that the `memory` and `span` are pointing to the same location. I see it is only called in 1 spot, which can just be moved to the above overload that only takes a `ROM<char>`.

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderParser.cs [hunk 50]
```diff
@@ -1065,18 +1075,18 @@ public int GatherFields(DvText lineSpan, string path = null, long line = 0)
...
-                private bool FetchNextField(ref ScanInfo scan)
+                private bool FetchNextField(ref ScanInfo scan, ReadOnlySpan<char> span)
                 {
                     Contracts.Assert(scan.IchMinBuf <= scan.IchMinNext && scan.IchMinNext <= scan.IchLimBuf);
 
                     var text = scan.TextBuf;
                     int ichLim = scan.IchLimBuf;
                     int ichCur = scan.IchMinNext;
-
+                    //var span = text.Span;
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderParser.cs]: (nit) can be removed.

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 51]
```diff
@@ -0,0 +1,285 @@
...
+            return pool.Add(memory);
+        }
+
+        public static NormStr FindInPool(ReadOnlyMemory<char> memory, NormStr.Pool pool)
+        {
+            Contracts.CheckValue(pool, nameof(pool));
+            return pool.Get(memory);
+        }
+
+        public static void AddToStringBuilder(ReadOnlyMemory<char> memory, StringBuilder sb)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: I wonder if we can get rid of this method and just have all the callers call `sb.Append(memory)` themselves. That way we don't have yet another public util method that does the same thing.

File: src/Microsoft.ML.Core/Utilities/DoubleParser.cs [hunk 52]
```diff
@@ -70,25 +70,44 @@ public enum Result
...
+        public static bool TryParse(ReadOnlySpan<char> span, out Double value)
         {
-            Contracts.Assert(0 <= ichMin && ichMin <= ichLim && ichLim <= Utils.Size(s));
+            var res = Parse(out value, span);
+            Contracts.Assert(res != Result.Empty || value == 0);
+            return res <= Result.Empty;
+        }
 
-            for (; ; ichMin++)
+        public static Result Parse(out Single value, ReadOnlySpan<char> span)
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Utilities/DoubleParser.cs]: While we are in here fixing this, can we switch the parameters around so the `out` variable is at the end?

**Comment by eerhardt** [comment]
I think this is looking really good. Just a couple last comments to address and I think this will be ready to merge.

**Comment by codemzs** [comment]
Thanks for reviewing! 

---
In reply to: [422861081](https://github.com/dotnet/machinelearning/pull/863#issuecomment-422861081) [](ancestors = 422861081)

File: src/Microsoft.ML.Data/Data/Conversion.cs (hunk 48 above)
[the remark this answers is not in the document]
Comment (ahsonkhan) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: A subtraction is better than a branch/comparison. Also, the subtraction doesn't show up as another instruction (its part of the `lea`).

In any case, this is a nit outside the scope of this PR. I noticed it so thought it was worth a mention.

See below (24 instructions vs 20):
[sharplab snippet with disassembly](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKEwGZ8AmXAYVwG9zc39qAbAewDsBzXAFkA+gQAU9ABaIATrgDGASmat26ngNy8ArqlwBeXNlJl16gJYAzXOPE6LvOEvELcAWlwBybF5UAeI3EvAE4vTx8/JTVzc119dCCHJxc3CN8lU1i2AFNOZBzca1t7R2dXD28AQT9cQNsvADFw6qiY7LZ43ETbZPK01twAalwCbEz29TyCops7PtTKr0Ra+uCrFuW2sw72Lp7SlIqIleHR8azszAB2bT1LtgBfdvaqXE1BURpJGXllVR2sQ+d30RhMk3YxWCvjqRjcADJ4YpYd4wtFAbt9kkyot0n4HuZpoUoV4aiiEUi3PUmn4IbEsb0ccdBiMxhMMYT8sS5ltybhEcjqRt0bs9nputijgNeayLnT8Ld4gTnmRHkA)

[the remark this answers is not in the document]
Comment (codemzs) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: Doesn't comparison operator use subtraction?

From your suggestion:
lea ecx, [rdx-0x30]
cmp ecx, 0x9

[rdx-0x30] will incur subtraction operation and cmp operation is a subtraction operation where the result is not stored anywhere but the result is used for conditional jump from flags register. So in total you are performing 2 subtraction operations in best and worst case.

What we have right now:
cmp edx, 0x30
 jl L0016
cmp edx, 0x39
 jg L0016

Best case one subtraction operation and worst case two. May be I'm missing something but how is your proposal any better than what we have? BTW, I like this website that spits out assembly code.


---
In reply to: [218992111](https://github.com/dotnet/machinelearning/pull/863#discussion_r218992111) [](ancestors = 218992111)

[the remark this answers is not in the document]
Comment (ahsonkhan) [reply src/Microsoft.ML.Data/Data/Conversion.cs]: Unlike instructions like subtraction, having branches (like cmp/jumps) affects the branch predictor and hence could affect instruction pipelining (which hurts perf, if the prediction is incorrect). I am not 100% familiar with how the CPU deals with instructions, but I don't think the subtraction within the `lea` impacts cpu cycles. That instruction/pattern is really common and heavily optimized.

http://www.oopweb.com/Assembly/Documents/ArtOfAssembly/Volume/Chapter_6/CH06-1.html#HEADING1-136

Unlike the sub instruction,
> The lea instruction does not affect any of the 80x86's flag bits.

We use this 'merge range checks into one comparison' optimization within corelib.
