### PR TITLE
Fixed output schema produced by ValueMappingEstimator

### LINKED ISSUE #2385: Fix output schema produced by ValueMappingEstimator
There is a bug in `ValueMappingEstimator` output schema. 
https://github.com/dotnet/machinelearning/blob/0e80d6c07580cea5ce072fd7cba02d7171dc61f4/src/Microsoft.ML.Data/Transforms/ValueMapping.cs#L61

When input is a vector the output produced is a vector. However, the schema produced by the `ValueMappingEstimator` shows that the output is scalar. This throws an exception when `ValueMappingEstimator` is followed by another estimator which checks for schema.

This regression was caused by #2162

### PR DESCRIPTION
**Pull request by zeahmed**
This PR fixes #2385.

### CODE REVIEW

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 1]
```diff
@@ -73,9 +73,13 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
...
 
-                if ((originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector ||
-                   originalColumn.Kind == SchemaShape.Column.VectorKind.Vector) && Transformer.ValueColumnType is VectorType)
-                    throw Host.ExceptNotSupp("Column '{0}' cannot be mapped to values when the column and the map values are both vector type.", inputColumnName);
+                if (originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector ||
+                   originalColumn.Kind == SchemaShape.Column.VectorKind.Vector)
+                {
+                    if (Transformer.ValueColumnType is VectorType)
+                        throw Host.ExceptNotSupp("Column '{0}' cannot be mapped to values when the column and the map values are both vector type.", inputColumnName);
+                    vectorKind = originalColumn.Kind;
```
Comment (zeahmed) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >vectorKind = originalColumn.Kind; [](start = 20, length = 33)

When input is a vector, output should always be a vector. Otherwise, output is of ValueType kind.

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 2]
```diff
@@ -89,6 +89,9 @@ public void ValueMapInputIsVectorTest()
             var estimator = new WordTokenizingEstimator(Env, new[]{
                     new WordTokenizingTransformer.ColumnInfo("TokenizeA", "A")
                 }).Append(new ValueMappingEstimator<ReadOnlyMemory<char>, int>(Env, keys, values, new[] { ("VecD", "TokenizeA"), ("E", "B"), ("F", "C") }));
+            var schema = estimator.GetOutputSchema(SchemaShape.Create(dataView.Schema));
+            Assert.True(schema.TryFindColumn("VecD", out var originalColumn));
+            Assert.Equal(SchemaShape.Column.VectorKind.VariableVector, originalColumn.Kind);
```
Comment (abgoswam) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: >originalColumn [](start = 71, length = 14)

can u also add test for values for this vector.

i believe it should be <2, 3 1> ?

Comment (zeahmed) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: If you look at the following code, it does exactly what meant.

---
In reply to: [253622276](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253622276) [](ancestors = 253622276)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 3]
```diff
@@ -73,9 +73,13 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
...
                     throw Host.ExceptSchemaMismatch(nameof(inputSchema), "input", inputColumnName);
 
-                if ((originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector ||
-                   originalColumn.Kind == SchemaShape.Column.VectorKind.Vector) && Transformer.ValueColumnType is VectorType)
-                    throw Host.ExceptNotSupp("Column '{0}' cannot be mapped to values when the column and the map values are both vector type.", inputColumnName);
+                if (originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector ||
+                   originalColumn.Kind == SchemaShape.Column.VectorKind.Vector)
+                {
+                    if (Transformer.ValueColumnType is VectorType)
+                        throw Host.ExceptNotSupp("Column '{0}' cannot be mapped to values when the column and the map values are both vector type.", inputColumnName);
```
Comment (abgoswam) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >when the column and the map values are both vector type. [](start = 90, length = 56)

i am not sure i understand this . could you give an example where this condition would be hit ?

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 4]
```diff
@@ -73,9 +73,13 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
                 if (!inputSchema.TryFindColumn(inputColumnName, out var originalColumn))
                     throw Host.ExceptSchemaMismatch(nameof(inputSchema), "input", inputColumnName);
 
-                if ((originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector ||
-                   originalColumn.Kind == SchemaShape.Column.VectorKind.Vector) && Transformer.ValueColumnType is VectorType)
-                    throw Host.ExceptNotSupp("Column '{0}' cannot be mapped to values when the column and the map values are both vector type.", inputColumnName);
+                if (originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector ||
+                   originalColumn.Kind == SchemaShape.Column.VectorKind.Vector)
```
Comment (abgoswam) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: it seems the bug is that we have not updated the `vectorKind`  when the `originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector`

As such , instead of changing this logic should we just update the vectorKind ? i.e. add the lines:

 if (originalColumn.Kind == SchemaShape.Column.VectorKind.VariableVector)
                    vectorKind = SchemaShape.Column.VectorKind.VariableVector;

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 3 above)
Comment (zeahmed) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: This is in a situation where column={"a", "b", "c"} and map={"a": [1,2,3], "b":[4,5], "c":[6]}
the resulting column will be output_col={[1,2,3], [4,5], [6]}


---
In reply to: [253629485](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253629485) [](ancestors = 253629485)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 4 above)
Comment (zeahmed) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: I think this what's happening right now both for fixed length and variable length vector.

---
In reply to: [253654474](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253654474) [](ancestors = 253654474)

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 5]
```diff
@@ -89,6 +89,9 @@ public void ValueMapInputIsVectorTest()
             var estimator = new WordTokenizingEstimator(Env, new[]{
                     new WordTokenizingTransformer.ColumnInfo("TokenizeA", "A")
                 }).Append(new ValueMappingEstimator<ReadOnlyMemory<char>, int>(Env, keys, values, new[] { ("VecD", "TokenizeA"), ("E", "B"), ("F", "C") }));
+            var schema = estimator.GetOutputSchema(SchemaShape.Create(dataView.Schema));
+            Assert.True(schema.TryFindColumn("VecD", out var originalColumn));
```
Comment (artidoro) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: Could you add a `TestEstimatorCore`, to your tests for `ValueMap`? Should be pretty quick and I think it would help make sure there are no further inconsistencies.

Comment (zeahmed) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: hmm... none of the test in this file use `TestEstimatorCore`. So, I would avoid that here too.
Also, checks made here are explicitly testing specific logic that I think cannot be tested with `TestEstimatorCore`.

---
In reply to: [253658781](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253658781) [](ancestors = 253658781)

Comment (artidoro) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: The reason I think it's important to have `TestEstimatorCore` is that it checks that the schema in` GetOutpuSchema` matches the schema that is actually produced. Since you found a bug in the output schema, I think it would be good to have this special case of an vector input go through the `TestEstimatorCore`. There is a test that uses `TestEstimatorCore` bellow: `ValueMappingWorkout`. 

---
In reply to: [253661005](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253661005) [](ancestors = 253661005,253658781)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 3 above)
Comment (abgoswam) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: thanks for the example.

so we shouldn't support  a scenario  where Transformer.ValueColumnType is VectorType
i.e   map={"a": [1,2,3], "b":[4,5], "c":[6]}

but then i do not understand  why we need the  condition in line #76-#77 ?  

if input is not vector :   
e.g.  
column="a"  => output_col = {[1,2, 3]}
column="b" =>  output_col = {[4,5]}

maybe i am missing something ?

---
In reply to: [253656971](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253656971) [](ancestors = 253656971,253629485)

Comment (zeahmed) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: We do support the scenario where Transformer.ValueColumnType is VectorType. However, we don't support scenario where both input and Transformer.ValueColumnType is VectorType are of vector type. 

---
In reply to: [253665022](https://github.com/dotnet/machinelearning/pull/2386#discussion_r253665022) [](ancestors = 253665022,253656971,253629485)

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs (hunk 5 above)
Comment (singlis) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: @zeahmed please see here:
https://github.com/dotnet/machinelearning/blob/2dfc51aa7172199c1b2145e48ecb9eb855bb87f1/test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs#L506

You can add to this test by adding a new DataView that produces an array. Then the TestEstimatorCore would validate as what @artidoro  is suggesting.

Comment (zeahmed) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: Thanks for the explanation @artidoro and @singlis, I think this is an end to end scenario where an input is a valid input and output is being tested against expected output. The semantics of `TestEstimatorCore` is different where it test the schema propagation for valid, invalid inputs for estimators and transforms. 

Adding that here in this test needlessly complicate the test and will not test the problem that is being tested between line 92-94.

I think it should be done as a separate test and that is what `ValueMappingWorkout` is doing. However, its not doing it for all the input scenarios. So, I am creating an issue to do it separately https://github.com/dotnet/machinelearning/issues/2410

**Comment by zeahmed** [comment]
Thanks all for the useful feedback!
