### PR TITLE
Fixed output schema of OnnxTransformer

### LINKED ISSUE #2980: ONNX outputs don't match model outputs after serialization
When I save a model to ONNX, load, and apply it with `ApplyOnnxModel`, it adds a zero as a suffix to all columns, including the expected output. This includes input columns, so the resulting `IDataView` now has double the columns, plus the output. To top it off, it's not clear how to find the output because it's been renamed.

Example:
ML.NET model
  Input:  `Features`
  Output: `Score`
  Resulting Schema: `Features`, `Score`

After Onnx Serialization / Deserialization:
  Input: `Features`
  Output: `Features0`, `Score0`
  Resulting Schema: `Features`, `Features0`, `Score0`

I am not sure if this is by design, but it feels like a bug.

### LINKED ISSUE #2981: Cannot fit an Onnx Transform as part of a pipeline
It is possible to fit an ONNX model by itself:

```cs
var onnxEstimator = mlContext.Transforms.ApplyOnnxModel(modelPath)
var onnxModel = onnxEstimator.Fit(data);
```

But it throws when it is part of a pipeline:
```cs
var onnxEstimator = mlContext.Transforms.ApplyOnnxModel(modelPath)
    // TODO #2980: ONNX outputs don't match the outputs of the model, so we must hand-correct this for now.
    .Append(mlContext.Transforms.CopyColumns("Score", "Score0"));
    .Append(mlContext.Transforms.CopyColumns("Label", "Fable"));
    .Append(mlContext.Transforms.NormalizeLpNorm("Features2", "Features", LpNormNormalizingEstimatorBase.NormFunction.L2));
var onnxModel = onnxEstimator.Fit(data);
```
Any of these `Append` statements cause a throw. They do not affect the ONNX model at all, and use either the result of the calculation (`Score0`), rows unused by the model (`Label`) or rows also used by the transform (`Features`).

In this case, the error message is:
`System.ArgumentOutOfRangeException : Schema mismatch for input column 'Label': expected vector, got R4
Parameter name: inputSchema`

### PR DESCRIPTION
**Pull request by harishsk**
This fixes a long standing issue about Onnx in ML.NET that the output variables of the onnx graph show up as columns with different names in the output schema of OnnxTransformer. After much investigation, it turns out that the output variables in the Onnx graph cannot be fixed because it is not possible to specify in onnx which particular node you want your output variable to be connected to. 

This fix, adds a known ".output" suffix to all Onnx models exported from ML.NET. And when reading a model, if the model was exported from ML.NET, it recognizes the suffix, strips it and maps it back to the input column. 

As a result of fixing this PR also contains updates to the tests and baseline files. 

Fixes #2980. Fixes #2981

### CODE REVIEW

File: test/Microsoft.ML.Functional.Tests/ONNX.cs [hunk 1]
```diff
@@ -109,7 +104,7 @@ public void SaveOnnxModelLoadAndScoreKMeans()
             // TODO #2980: ONNX outputs don't match the outputs of the model, so we must hand-correct this for now.
             // TODO #2981: ONNX models cannot be fit as part of a pipeline, so we must use a workaround like this.
```
Comment (ganik) [inline test/Microsoft.ML.Functional.Tests/ONNX.cs]: Are these comments still valid? Do we do hand correction now?

File: test/Microsoft.ML.Functional.Tests/ONNX.cs [hunk 2]
```diff
@@ -109,7 +104,7 @@ public void SaveOnnxModelLoadAndScoreKMeans()
...
             var onnxWorkaroundPipeline = onnxModel.Append(
-                mlContext.Transforms.CopyColumns("Score", "Score.onnx").Fit(onnxModel.Transform(data)));
+                mlContext.Transforms.CopyColumns("Score", "Score").Fit(onnxModel.Transform(data)));
```
Comment (ganik) [inline test/Microsoft.ML.Functional.Tests/ONNX.cs]: >CopyColumns("Score", "Score") [](start = 37, length = 29)

Do we need CopyColumn now?

File: test/Microsoft.ML.Functional.Tests/ONNX.cs (hunk 1 above)
Comment (harishsk) [reply test/Microsoft.ML.Functional.Tests/ONNX.cs]: The comments are not valid. I have removed them in the next commit. 

---
In reply to: [381300021](https://github.com/dotnet/machinelearning/pull/4849#discussion_r381300021) [](ancestors = 381300021)

File: test/Microsoft.ML.Functional.Tests/ONNX.cs (hunk 2 above)
Comment (harishsk) [reply test/Microsoft.ML.Functional.Tests/ONNX.cs]: We don't need CopyColumns either. 

---
In reply to: [381300171](https://github.com/dotnet/machinelearning/pull/4849#discussion_r381300171) [](ancestors = 381300171)
