### PR TITLE
Handle inputs with unknown shapes in TensorFlow

### LINKED ISSUE #848: TensorFlowScorer in ML.NET does not support input tensor of unknown shape
Using Microsoft.ML 0.5.0
Yael told me she's already working on a PR to fix this issue. 👍 

**Issue/Bug:** 
We’d like to extend your test case TensorFlowTransformCifarLearningPipelineTest for making a demo, but instead of loading your “cifar” frozen model, we’ll be using an inception model trained for imagenet (downloaded from https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip  ).

The main issue is that when executing the Train method of the pipeline, we get an error related to the initialization of the TensorFlowScorer, which I believe is related with using an input tensor of unknown shape. 

Details of the bug/issue are below, but the main question is if we’ll be able to use an input tensor of unknown shape.
 
var shape = tfShapes[i].ToIntArray().Skip(tfShapes[i][0] == -1 ? BatchSize : 0)

Former code is executed in the method TensorFlowMapper.GetInputMetaData(). tfShapes[i] is an object of type TFShape; if the shape is unknown, accessing by the indexer to the first dimension ( tfSfapes[i][0] ) throws a null exception. I checked that most of the methods in TFShape have a guard condition on dims == null, but the overridden indexer doesn’t have this guard, what could be the culprit of the NullReferenceException

But even if you fix the indexer, then the method tfShapes[i].ToIntArray() it will return null for an unknown tensor, so this will throw again an exception.

Full source code of the demo (and the crash) is available here:
https://github.com/CESARDELATORRE/TensorFlowMLNETSamples/blob/master/src/TensorFlowMLNETInceptionv3ModelScoring/Program.cs

### PR DESCRIPTION
**Pull request by yaeldekel**
This PR adds support for unknown shapes in the inputs and in the outputs of TensorFlow transform.
Closes #848 .

### CODE REVIEW

**Comment by Ivanidzo4ka** [comment]
>                 _host.CheckNonEmpty(output, nameof(outputs));

probably should be same as in input, can you change it to CheckNonWhiteSpace ?

---
Refers to: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs:210 in 34f91f8. [](commit_id = 34f91f87b1ecb3a94544df06d562ab29cacd34ed, deletion_comment = False)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 1]
```diff
@@ -191,6 +191,8 @@ private TensorFlowTransform(IHostEnvironment env, byte[] modelBytes, string[] in
             Contracts.CheckValue(env, nameof(env));
             _host = env.Register(nameof(RegistrationName));
             _host.CheckValue(modelBytes, nameof(modelBytes));
+            _host.CheckNonEmpty(inputs, nameof(inputs));
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >inputs [](start = 47, length = 6)

outputs as well?

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 2]
```diff
@@ -554,7 +591,11 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
                     throw Host.ExceptSchemaMismatch(nameof(inputSchema), "input", input, expectedType.ToString(), col.ItemType.ToString());
             }
             for (var i = 0; i < Transformer.Outputs.Length; i++)
-                resultDic[Transformer.Outputs[i]] = new SchemaShape.Column(Transformer.Outputs[i], SchemaShape.Column.VectorKind.Vector, Transformer.OutputTypes[i].ItemType, false);
+            {
+                resultDic[Transformer.Outputs[i]] = new SchemaShape.Column(Transformer.Outputs[i],
+                    Transformer.OutputTypes[i].VectorSize > 0 ? SchemaShape.Column.VectorKind.Vector
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >.VectorSize > 0 [](start = 46, length = 15)

can we use IsKnownSizeVector?

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 3]
```diff
@@ -311,26 +319,56 @@ public Mapper(IHostEnvironment env, TensorFlowTransform parent, ISchema inputSch
                 _schema = inputSchema;
                 _inputColIndices = new int[_parent.Inputs.Length];
                 _isInputVector = new bool[_parent.Inputs.Length];
+                _fullySpecifiedShapes = new TFShape[_parent.Inputs.Length];
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >_fullySpecifiedShapes [](start = 16, length = 21)

I feel like this one should be part of Transformer, rather than mapper.
You do estimator.Fit(somedata) and gain transformer, and it resolves it's variable lengths[?,?,3] as [3,3,3].
Not sure it would be right to accept data rather than [3,3,3] to transformer after that.

(Same probably states for _isInputVector, not sure why I didn't put it to Transformer)
@Zruty0 to make sure I correctly understand estimator/transformer business.

Comment (yaeldekel) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: The problem is that when you instantiate the estimator you only have the TF model and not the IDV, so we don't necessarily know all the dimensions in the shape. However, in order to convert a VBuffer to a Tensor we need to know the fully specified shape.

Instead of having this field, I could instantiate a new shape object on every getter call, using _inputColIndices and _schema to figure out the input size. Do you think this is a good solution?


---
In reply to: [216115594](https://github.com/dotnet/machinelearning/pull/857#discussion_r216115594) [](ancestors = 216115594)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 4]
```diff
@@ -233,7 +240,7 @@ private TensorFlowTransform(IHostEnvironment env, byte[] modelBytes, string[] in
             {
                 var tfOutput = new TFOutput(Graph[Outputs[i]]);
                 var shape = Graph.GetTensorShape(tfOutput);
-                int[] dims = shape.ToIntArray().Skip(shape[0] == -1 ? BatchSize : 0).ToArray();
+                int[] dims = shape.NumDimensions > 0 ? shape.ToIntArray().Skip(shape[0] == -1 ? BatchSize : 0).ToArray() : new[] { 0 };
```
Comment (zeahmed) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >0 [](start = 131, length = 1)

Does this zero mean variable length?

File: test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs [hunk 5]
```diff
@@ -70,6 +70,115 @@ public void TensorFlowTransformMatrixMultiplicationTest()
...
+                    var inputBuffer = default(VBuffer<byte>);
+                    while (curs.MoveNext())
+                    {
+                        getInput(ref inputBuffer);
+                        getBoxes(ref buffer);
+                        getScores(ref buffer);
+                        getNum(ref buffer);
+                        getClasses(ref buffer);
+                    }
+                }
```
Comment (abgoswam) [inline test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: do we want to validate anything here ?

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 6]
```diff
@@ -220,10 +223,15 @@ private TensorFlowTransform(IHostEnvironment env, byte[] modelBytes, string[] in
                 var tfInput = new TFOutput(Graph[Inputs[i]]);
                 TFInputTypes[i] = tfInput.OutputType;
                 TFInputShapes[i] = Graph.GetTensorShape(tfInput);
-                var newShape = new long[TFInputShapes[i].NumDimensions];
-                for (int j = 0; j < TFInputShapes[i].NumDimensions; j++)
-                    newShape[j] = TFInputShapes[i][j] == -1 ? BatchSize : TFInputShapes[i][j];
-                TFInputShapes[i] = new TFShape(newShape);
+                if (TFInputShapes[i].NumDimensions != -1)
```
Comment (abgoswam) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >if (TFInputShapes[i].NumDimensions != -1) [](start = 16, length = 41)

am curious - why did we need this check ? 

Did some of the pre-trained models have TFInputShapes[i].NumDimensions == -1  (that we were not handling before)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 7]
```diff
@@ -220,10 +223,15 @@ private TensorFlowTransform(IHostEnvironment env, byte[] modelBytes, string[] in
...
+                {
+                    var newShape = new long[TFInputShapes[i].NumDimensions];
+                    newShape[0] = TFInputShapes[i][0] == -1 ? BatchSize : TFInputShapes[i][0];
```
Comment (abgoswam) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >newShape[0] = TFInputShapes[i][0] == -1 ? BatchSize : TFInputShapes[i][0]; [](start = 20, length = 74)

so we will have special handling only for the 1st dimension, and not for the other dimensions -- is that the intent ?

(looks like we should have been doing this previously too, instead of doing special handling for all the columns)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 8]
```diff
@@ -233,7 +241,7 @@ private TensorFlowTransform(IHostEnvironment env, byte[] modelBytes, string[] in
             {
                 var tfOutput = new TFOutput(Graph[Outputs[i]]);
                 var shape = Graph.GetTensorShape(tfOutput);
-                int[] dims = shape.ToIntArray().Skip(shape[0] == -1 ? BatchSize : 0).ToArray();
+                int[] dims = shape.NumDimensions > 0 ? shape.ToIntArray().Skip(shape[0] == -1 ? BatchSize : 0).ToArray() : new[] { 0 };
```
Comment (abgoswam) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >shape.NumDimensions > 0 [](start = 29, length = 23)

I am presuming we are using this here as a check for models producing variable length outputs...Am i right ?

Does TF document such behaviour somewhere ?

File: src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.tt [hunk 9]
```diff
@@ -37,13 +37,14 @@ namespace Microsoft.ML.Transforms.TensorFlow
         /// </summary>
         /// <typeparam name="T[]">.NET type of tensor to create</typeparam>
         /// <param name="data">value of tensor</param>
+        /// <param name="count">The number of elements in the tensor</param>
```
Comment (abgoswam) [inline src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.tt]: did we have to re-generate the TensorGeneric.cs file after making these changes ?

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs [hunk 10]
```diff
@@ -384,18 +423,18 @@ private Delegate[] MakeGetters(IRow input, Func<int, bool> activeOutput)
...
+                var valueGetters = new Delegate[_parent.Outputs.Length];
                 for (int i = 0; i < _parent.Outputs.Length; i++)
                 {
                     if (activeOutput(i))
                     {
                         var type = TFTensor.TypeFromTensorType(_parent.TFOutputTypes[i]);
                         _host.Assert(type == _parent.OutputTypes[i].ItemType.RawType);
                         var srcTensorGetters = GetTensorValueGetters(input);
-                        valueGetters.Add(Utils.MarshalInvoke(MakeGetter<int>, type, input, i, srcTensorGetters, activeOutputColNames, outputCache));
+                        valueGetters[i] = Utils.MarshalInvoke(MakeGetter<int>, type, input, i, srcTensorGetters, activeOutputColNames, outputCache);
```
Comment (abgoswam) [inline src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: >valueGetters[i] [](start = 24, length = 15)

am curious about this bug in the getter -- could you kindly elaborate a bit on this ? .. is this some artifact of the activateOutput() call above..

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 3 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: I think I just have incorrect understanding of estimator/transformer, and we don't have to have same schema for input fitting and input transforming.

---
In reply to: [216382814](https://github.com/dotnet/machinelearning/pull/857#discussion_r216382814) [](ancestors = 216382814,216115594)

File: test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs (hunk 5 above)
Comment (yaeldekel) [reply test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: The images I am using here don't have any detections, so all of the outputs will be all 0. Once I get the models uploaded, I will also upload some images that have detections, then I can add validation of the outputs.

---
In reply to: [216457130](https://github.com/dotnet/machinelearning/pull/857#discussion_r216457130) [](ancestors = 216457130)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 6 above)
Comment (yaeldekel) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: If the shape is completely unknown, then its NumDimensions property is -1.

---
In reply to: [216460739](https://github.com/dotnet/machinelearning/pull/857#discussion_r216460739) [](ancestors = 216460739)

Comment (abgoswam) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: makes sense. in another comment i was asking if TF has this documented somewhere -- or we are using this as a heuristic based on models we have played with so far ?

---
In reply to: [216475056](https://github.com/dotnet/machinelearning/pull/857#discussion_r216475056) [](ancestors = 216475056,216460739)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 8 above)
Comment (yaeldekel) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: If the shape is unknown, it has shape.NumDimensions == -1, and shape.ToIntArray() == null, which would cause a null reference exception when we try to access shape[0].

---
In reply to: [216462762](https://github.com/dotnet/machinelearning/pull/857#discussion_r216462762) [](ancestors = 216462762)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 7 above)
Comment (abgoswam) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: yeap. good catch!

---
In reply to: [216477499](https://github.com/dotnet/machinelearning/pull/857#discussion_r216477499) [](ancestors = 216477499,216461730)

File: src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.tt (hunk 9 above)
Comment (yaeldekel) [reply src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.tt]: Yes. Apparently TensorGeneric.tt regenerates TensorGeneric.cs automatically whenever it is saved.

---
In reply to: [216466572](https://github.com/dotnet/machinelearning/pull/857#discussion_r216466572) [](ancestors = 216466572)

Comment (abgoswam) [reply src/Microsoft.ML.TensorFlow/TensorFlow/TensorGeneric.tt]: awesome. thanks for the info.

---
In reply to: [216479096](https://github.com/dotnet/machinelearning/pull/857#discussion_r216479096) [](ancestors = 216479096,216466572)

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 10 above)
Comment (yaeldekel) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: This bug surfaced when I added the new unit test. It happens in the following situation:

- Create a TensorFlowTransform that computes two outputs, say A and B.
- Create another transform/learner that only uses B as input.
- When we try to cursor over the data, the activeOutput predicate will say that output 0 is not active and output 1 is active, thus returning an array of length 1.
- When we try to get the getter of column B, we do so using its index, which is 1 (the index of column A is 0 and the index of column B is 1). So we try to access the getters array which is of length 1, at index 1 which is out of bounds...

The fix was to always create an array with length equal to the number of output columns in the transform, but populate just the indices where the active columns are.



---
In reply to: [216469314](https://github.com/dotnet/machinelearning/pull/857#discussion_r216469314) [](ancestors = 216469314)

File: test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs [hunk 11]
```diff
@@ -152,11 +262,52 @@ public void TensorFlowTransformMNISTConvTest()
...
+            var dataPath = GetDataPath("Train-Tiny-28x28.txt");
+
+            var pipeline = new LearningPipeline(seed: 1);
+            pipeline.Add(new Microsoft.ML.Data.TextLoader(dataPath).CreateFrom<MNISTData>(useHeader: false));
+            pipeline.Add(new Transforms.ColumnCopier() { Column = new[] { new CopyColumnsTransformColumn() { Name = "reshape_input", Source = "Placeholder" } } });
+            pipeline.Add(new TensorFlowScorer()
+            {
+                ModelFile = model_location,
+                OutputColumns = new[] { "Softmax", "dense/Relu" },
+                InputColumns = new[] { "Placeholder", "reshape_input" }
```
[the remark this answers is not in the document]
Comment (yaeldekel) [reply test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: It is required, this column is created in line 273 by the CopyColumns transform.
This input is required for computing the "dense/Relu" output. Actually, I am not sure why it is needed, since if I understand correctly, reshape_input is computed by the input layer Placeholder by simply reshaping from 28x28 to 784. @zeahmed , do you know why "Placeholder" is not enough to compute "dense/Relu"?

File: src/Microsoft.ML.TensorFlow/TensorflowTransform.cs (hunk 6 above)
Comment (yaeldekel) [reply src/Microsoft.ML.TensorFlow/TensorflowTransform.cs]: I haven't seen it documented, I just saw it by debugging different models.

---
In reply to: [216476239](https://github.com/dotnet/machinelearning/pull/857#discussion_r216476239) [](ancestors = 216476239,216475056,216460739)

File: test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs (hunk 11 above)
[the remark this answers is not in the document]
Comment (zeahmed) [reply test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: This is the problem with the model. [https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py](https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py)

If you want to access the `features` (named `dense/Relu`) only then `reshape_input` is required if you want to access the `Softmax` then `Placeholder` is required. This is the problem with model. If you closely look at the model graph attached. You would observe two graph that are working in parallel. Having said that I think its a good model to test two inputs and two outputs.

If you think if its going to make an issue I can update the model.

---
In reply to: [216485826](https://github.com/dotnet/machinelearning/pull/857#discussion_r216485826) [](ancestors = 216485826)

[the remark this answers is not in the document]
Comment (zeahmed) [reply test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: Also, i think we should rename the nodes properly to avoid strange names like `dense/Relu` etc....:)

---
In reply to: [216502475](https://github.com/dotnet/machinelearning/pull/857#discussion_r216502475) [](ancestors = 216502475,216485826)

File: src/Microsoft.ML.TensorFlow/TensorFlow/Tensor.cs [hunk 12]
```diff
@@ -410,9 +410,9 @@ public unsafe TFTensor(long value)
         public TFTensor(Complex[] data) : base(SetupTensor(TFDataType.Complex128, data, size: 16)) { }
 
         // Convenience function to factor out the setup of a new tensor from an array
-        internal static IntPtr SetupTensor(TFDataType dt, long[] dims, Array data, int size)
+        internal static IntPtr SetupTensor(TFDataType dt, long[] dims, Array data, int count, int size)
         {
-            return SetupTensor(dt, dims, data, start: 0, count: data.Length, size: size);
+            return SetupTensor(dt, dims, data, start: 0, count: count, size: size);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TensorFlow/TensorFlow/Tensor.cs]: >start: 0, count: count, size: size [](start = 47, length = 34)

nit: do you need to specify param names here? don't you invoke function with all params already
