### PR TITLE
Handle Indexed Pixel Format correctly in Image Resize transform.

### LINKED ISSUE #3600: Image Resize Transform does not handle Indexed Pixel Format images correctly.
It tries to Graphics.DrawImage when resizing images that are of Indexed Pixel Format as evident from the below code. This will throw an exception "A Graphics object cannot be created from an image that has an indexed pixel format." This bug seems to affects images converted to `.gif` format as well.

```csharp
dst = new Bitmap(info.ImageWidth, info.ImageHeight, src.PixelFormat);

var srcRectangle = new Rectangle(sourceX, sourceY, sourceWidth, sourceHeight);
var destRectangle = new Rectangle(destX, destY, destWidth, destHeight);
using (var g = Graphics.FromImage(dst))
 {
    g.DrawImage(src, destRectangle, srcRectangle, GraphicsUnit.Pixel);
|
                        
```

Instead of Indexed Pixel Format the images should be resized in the below manner:

```csharp
if (src.PixelFormat == PixelFormat.Format1bppIndexed ||
    src.PixelFormat == PixelFormat.Format4bppIndexed ||
    src.PixelFormat == PixelFormat.Format8bppIndexed)
 {
   dst = new Bitmap(info.ImageWidth, info.ImageHeight);
}
else
   dst = new Bitmap(info.ImageWidth, info.ImageHeight, src.PixelFormat);

var srcRectangle = new Rectangle(sourceX, sourceY, sourceWidth, sourceHeight);
var destRectangle = new Rectangle(destX, destY, destWidth, destHeight);
using (var g = Graphics.FromImage(dst))
{
    g.DrawImage(src, destRectangle, srcRectangle, GraphicsUnit.Pixel);
}
```
To read more refer to https://stackoverflow.com/questions/17313285/graphics-on-indexed-image and specifically the last answer is the most accurate.

### PR DESCRIPTION
**Pull request by codemzs**
fixes #3600

### CODE REVIEW

**Comment by eerhardt** [comment]
Should we add a test?

**Comment by codemzs** [comment]
@eerhardt Yes, absolutely.

File: src/Microsoft.ML.ImageAnalytics/ImageResizer.cs [hunk 1]
```diff
@@ -381,7 +382,15 @@ protected override Delegate MakeGetter(DataViewRow input, int iinfo, Func<int, b
                             destHeight = info.ImageHeight;
                         }
 
-                        dst = new Bitmap(info.ImageWidth, info.ImageHeight, src.PixelFormat);
+                        if (src.PixelFormat == PixelFormat.Format1bppIndexed ||
```
Comment (eerhardt) [inline src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: This check can be simplified using the same check from the corefx code:

https://source.dot.net/#System.Drawing.Common/System/Drawing/Graphics.Windows.cs,138

```C#
 if ((image.PixelFormat & PixelFormat.Indexed) != 0)
```

Comment (codemzs) [reply src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: Thanks, @eerhardt ! you are the best!

File: src/Microsoft.ML.ImageAnalytics/ImageResizer.cs [hunk 2]
```diff
@@ -381,7 +382,11 @@ protected override Delegate MakeGetter(DataViewRow input, int iinfo, Func<int, b
                             destHeight = info.ImageHeight;
                         }
 
-                        dst = new Bitmap(info.ImageWidth, info.ImageHeight, src.PixelFormat);
+                        if ((src.PixelFormat & PixelFormat.Indexed) != 0)
+                            dst = new Bitmap(info.ImageWidth, info.ImageHeight);
```
Comment (shmoradims) [inline src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: >new Bitmap(info.ImageWidth, info.ImageHeight); [](start = 34, length = 46)

this overload creates a bitmap with a PixelFormat enumeration value of Format32bppArgb. So we're dropping the src's indexed format and forcing it to be Format32bppArgb? Is that ok?

[https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.-ctor?view=netframework-4.8#System_Drawing_Bitmap__ctor_System_Int32_System_Int32](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.-ctor?view=netframework-4.8#System_Drawing_Bitmap__ctor_System_Int32_System_Int32)_

Comment (codemzs) [reply src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: 32bppArgb is ok. @shmoradims read more here: https://stackoverflow.com/questions/17313285/graphics-on-indexed-image

File: test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs [hunk 3]
```diff
@@ -845,7 +845,7 @@ public void TensorFlowTransformCifar()
             var imageHeight = type.Dimensions[0];
             var imageWidth = type.Dimensions[1];
 
-            var dataFile = GetDataPath("images/images.tsv");
+            var dataFile = GetDataPath("images/imagesmixedpixelformat.tsv");
```
Comment (shmoradims) [inline test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: >imagesmixedpixelformat [](start = 47, length = 22)

so we know, this code is not throwing exceptions, but have you looked at the output pixel to make sure the don't look scrambled? This formatting changes can seem to work on the surface, but when you look at the pixels, the might not be what you want. Especially b/c we don't have a baseline for this test.

**Comment by eerhardt** [comment]
> What is the license on the image file?

I had the same question.... are we free to reproduce this image? Do we need attribution?

File: src/Microsoft.ML.ImageAnalytics/ImageResizer.cs (hunk 2 above)
Comment (eerhardt) [reply src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: Maybe it would be good to stick a comment in here on why this is necessary... Up to you.

---
In reply to: [279062683](https://github.com/dotnet/machinelearning/pull/3601#discussion_r279062683) [](ancestors = 279062683)

File: test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs (hunk 3 above)
Comment (codemzs) [reply test/Microsoft.ML.Tests/ScenariosWithDirectInstantiation/TensorflowTests.cs]: Yep verified, please see my response below. Great question.

File: src/Microsoft.ML.ImageAnalytics/ImageResizer.cs (hunk 2 above)
Comment (codemzs) [reply src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: Please see my response below.

**Comment by eerhardt** [comment]
Where are we using the `resizedindexedpixelformat.jpeg` file? I don't see it being used.

File: src/Microsoft.ML.ImageAnalytics/ImageResizer.cs (hunk 2 above)
Comment (codemzs) [reply src/Microsoft.ML.ImageAnalytics/ImageResizer.cs]: Done.

---
In reply to: [279069616](https://github.com/dotnet/machinelearning/pull/3601#discussion_r279069616) [](ancestors = 279069616,279062683)

**Comment by codemzs** [comment]
sorry removed the image. it was just to show the output to people that it does not mess with the image by itself.

---
In reply to: [487175959](https://github.com/dotnet/machinelearning/pull/3601#issuecomment-487175959) [](ancestors = 487175959)
