### PR TITLE
fix #6949

### LINKED ISSUE #6949: Microsoft.ML.StandardTrainers references Microsoft.ML.SearchSpace but it's not included in Microsoft.ML package
**System Information (please complete the following information):**
 - OS & Version: Any
 - ML.NET Version: 3.0
 - .NET Version: Any

**Describe the bug**
Microsoft.ML.StandardTrainers.dll references Microsoft.ML.SearchSpace.dll but the latter is not included in the Microsoft.ML package, but the Microsoft.ML.AutoML package.

I haven't noticed any side-effects from this _yet_ since the usage of Microsoft.ML.SearchSpace is only in attributes, but it's possible that anything trying to enumerate other attributes on these types would see `FileLoadException`s.

I discussed it with @LittleLittleCloud and suggested a couple options, _if_ we decide we need to fix this.
1. Just include Microsoft.ML.SearchSpace.dll in Microsoft.ML.  While this is possible it may add dependencies to Microsoft.ML - one in particular is `System.Text.Json` which may be odd next to `Newtonsoft.Json` which it already references.  Eventually we should try to move away from Newtonsoft to STJ, but that's not planned yet.
2. Refactor the implementation of the attributes in SearchSpace to be pure attributes that merely expose their parameters (see [guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/attributes) for inspiration) and typeforward those down into Microsoft.ML.Core without any of the options types they internally reference.

### PR DESCRIPTION
**Pull request by LittleLittleCloud**
We are excited to review your PR.

So we can do the best job, please check:

- [ ] There's a descriptive title that will make sense to other developers some time from now. 
- [ ] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [ ] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [ ] You have included any necessary tests in the same PR.

Fix #6949

### CODE REVIEW

File: src/Microsoft.ML.SearchSpace/Microsoft.ML.SearchSpace.csproj [hunk 1]
```diff
@@ -9,6 +9,7 @@
   </PropertyGroup>
 
   <ItemGroup>
+    <ProjectReference Include="..\Microsoft.ML.Core\Microsoft.ML.Core.csproj" />
```
Comment (ericstj) [inline src/Microsoft.ML.SearchSpace/Microsoft.ML.SearchSpace.csproj:12]: Can you please add `TypeForwardedTo` attributes here for these?

```c#
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(Microsoft.ML.SearchSpace.BooleanChoiceAttribute))]
[assembly: TypeForwardedTo(typeof(Microsoft.ML.SearchSpace.ChoiceAttribute))]
[assembly: TypeForwardedTo(typeof(Microsoft.ML.SearchSpace.NestOptionAttribute))]
[assembly: TypeForwardedTo(typeof(Microsoft.ML.SearchSpace.RangeAttribute))]
```

**Comment by ericstj** [comment]
Interesting, the addition of `SearchSpace` sub-namespace now causes a type name resolution problem:
https://github.com/dotnet/machinelearning/blob/d0d8569220da60ff8acde3650393110c54dea8d0/src/Microsoft.ML.TorchSharp/NasBert/Models/NasBertEncoder.cs#L258-L264

Looks like those were meant to refer to this internal class: https://github.com/dotnet/machinelearning/blob/d0d8569220da60ff8acde3650393110c54dea8d0/src/Microsoft.ML.TorchSharp/NasBert/Modules/SearchSpace.cs#L13

Maybe we just rename that @michaelgsharp?

**Comment by ericstj** [comment]
> any classes directly involved in the TorchSharp model itself need to match names exactly with the name that was used to save the weights file. 

How would we be persisting the name of this static class in our saved file?  Still might be worth renaming since we try to avoid name collisions in our codebases.
