### PR TITLE
Polish marshalling of MF model and MF problem and enable 32-bit tests

### LINKED ISSUE #1441: Matrix factorization should work in x86
Matrix factorization fails in x86 (MatrixFactorizationSimpleTrainAndPredict test was disabled as part of #1432).

The reason is that the MFModel struct is architecture dependent: https://github.com/dotnet/machinelearning/blob/eae76959e6714af44caa212e102a5f06f0110e72/src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs#L67-L80

The struct matches the output data structure produced by c++ code in the libmf library. 

See the following comment for how this issue should be solved using P/Invoke instead: https://github.com/dotnet/machinelearning/pull/1432#discussion_r229095196

### PR DESCRIPTION
**Pull request by wschin**
Fix #1441. Also related to some suggestion made in #3210.

### CODE REVIEW

File: src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs [hunk 1]
```diff
@@ -17,31 +17,50 @@ namespace Microsoft.ML.Recommender.Internal
...
         {
-            [FieldOffset(0)]
+            /// <summary>
+            /// Row index.
+            /// </summary>
             public int U;
-            [FieldOffset(4)]
+
+            /// <summary>
+            /// olumn index;
```
Comment (eerhardt) [inline src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs]: `olumn`

File: test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs [hunk 2]
```diff
@@ -17,7 +17,7 @@ public MatrixFactorizationFactAttribute() : base("Disabled - this test is being
         /// <inheritdoc />
         protected override bool IsEnvironmentSupported()
         {
-            return Environment.Is64BitProcess;
+            return true;
```
Comment (eerhardt) [inline test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs]: Can probably just remove this whole thing, I think.

Comment (wschin) [reply test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs]: I'd keep it. We will be enabling LIBMF's SSE/AVX and I guess this might be useful if LIBMF's numerical stability changes.

File: src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs (hunk 1 above)
Comment (wschin) [reply src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs]: Fixed. Thanks.

File: test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs (hunk 2 above)
Comment (eerhardt) [reply test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs]: Can you at least remove `base("Disabled - this test is being fixed as part of https://github.com/dotnet/machinelearning/issues/1441")`, as that appears to no longer be valid?

Comment (wschin) [reply test/Microsoft.ML.TestFramework/Attributes/MatrixFactorizationFactAttribute.cs]: No problem.
