### PR TITLE
Fix FieldAwareFactorizationMachineBinaryTrainer documentation

### LINKED ISSUE #3490: Issues with FieldAwareFactorizationMachineTrainer documentation
The Latex is not being rendered correctly in the "Scoring Function" section.

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #3490 .

### CODE REVIEW

File: src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs [hunk 1]
```diff
@@ -67,16 +67,21 @@ namespace Microsoft.ML.Trainers
...
-    /// where $\left\langle \cdot, \cdot \right\rangle$ is the inner product operator, $\boldsymbol{w}\in{\mathbb R}^n$ stores the linear coefficients, and $\boldsymbol{v}_{j, f}\in {\mathbb R}^k$ is the $j$-th feature's representation in the $f$-th field's latent space.
+    /// Assume that all $m$ feature columns are concatenated into a long feature vector $\textbf{x}\in {\mathbb R}^n$ and ${\mathcal F}(j)$ denotes the $j$-th feature's field indentifier.
+    /// The corresponding score is
+    /// $\hat{y}\left(\textbf{x}\right) = \langle \textbf{w}, \textbf{x} \rangle + \sum_{j = 1}^n \sum_{j' = j + 1}^n \langle \textbf{v}_{j, {\mathcal F}(j')} , \textbf{v}_{j', {\mathcal F}(j)} \rangle x_j x_{j'}$,
+    /// where $\langle \cdot, \cdot \rangle$ is the inner product operator, $\textbf{w}\in{\mathbb R}^n$ stores the linear coefficients,
+    /// and $\textbf{v}_{j, f}\in {\mathbb R}^k$ is the $j$-th feature's representation in the $f$-th field's latent space.
+    ///
     /// Note that $k$ is the latent dimension specified by the user.
```
Comment (wschin) [inline src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs]: Why do we have the three extra empty lines?

File: src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs [hunk 2]
```diff
@@ -67,16 +67,21 @@ namespace Microsoft.ML.Trainers
     ///
     /// ### Scoring Function
     /// Field-aware factorization machine is a scoring function which maps feature vectors from different fields to a scalar score.
-    /// Assume that all $m$ feature columns are concatenated into a long feature vector $\boldsymbol{x}\in {\mathbb R}^n$ and ${\mathcal F}(j)$ denotes the $j$-th feature's field indentifier.
-    /// The corresponding score is $\hat{y}\left(\boldsymbol{x}\right) = \left\langle \boldsymbol{w}, \boldsymbol{x} \right\rangle + \sum_{j = 1}^n \sum_{j' = j + 1}^n \left\langle \boldsymbol{v}_{j, {\mathcal F}(j')} , \boldsymbol{v}_{j', {\mathcal F}(j)} \right\rangle x_j x_{j'}$,
```
Comment (wschin) [inline src/Microsoft.ML.StandardTrainers/FactorizationMachine/FactorizationMachineTrainer.cs]: >left [](start = 169, length = 4)

Any special reason to remove `\left` and `\right`?
