### PR TITLE
Doc fixes for FeatureContributionCalculatingEstimator

### LINKED ISSUE #3489: Issues with FeatureContributionCalculatingEstimator  documentation
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.featurecontributioncalculatingestimator?view=ml-dotnet&branch=smoke-test-preview

Would be nice to have link to `FeatureContributionCalculatingTransformer ` somewhere.

>Feature Contribution Calculation is currently supported for the following models:

They need to be links.

I don't see clear difference in description for 
`CalculateFeatureContribution<TModelParameters,TCalibrator>(TransformsCatalog, ISingleFeaturePredictionTransformer<CalibratedModelParametersBase<TModelParameters,TCalibrator>>, Int32, Int32, Boolean)` and `CalculateFeatureContribution(TransformsCatalog, ISingleFeaturePredictionTransformer<ICalculateFeatureContribution>, Int32, Int32, Boolean)`
Would be nice to write for first one what it's for calibrated models.

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.isinglefeaturepredictiontransformer-1?view=ml-dotnet&branch=smoke-test-preview

>The Microsoft.ML.IPredictor 

Need to be updated.

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #3489 

- Added link to `FeatureContributionCalculatingTransformer`
- Clarified one of the APIs is for calibrated models
- Added xref links to supported models.

### CODE REVIEW

File: src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransformer.cs [hunk 1]
```diff
@@ -246,31 +246,31 @@ private Delegate GetValueGetter<TSrc>(DataViewRow input, int colSrc)
...
-    ///   - OnlineGradientDescentTrainer
-    ///   - LbfgsPoissonRegressionTrainer
-    ///   - GamRegressionTrainer
-    ///   - LightGbmRegressionTrainer
-    ///   - FastTreeRegressionTrainer
-    ///   - FastForestRegressionTrainer
-    ///   - FastTreeTweedieTrainer
+    ///   - <xref:Microsoft.ML.Trainers.OlsTrainer>
+    ///   - <xref:Microsoft.ML.Trainers.SdcaRegressionTrainer>
+    ///   - <xref:Microsoft.ML.Trainers.OnlineGradientDescentTrainer>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Transforms/FeatureContributionCalculationTransformer.cs]: >OnlineGradientDescentTrainer [](start = 40, length = 28)

I wish I had your patience
