### PR TITLE
Get the cross validation macro to work with non-default column names

### LINKED ISSUE #292: Cross validation macro doesn't work with non-default label column name
If the label column is not called "Label" there is no way to pass the correct column name to the CV macro for it to pass to the evaluator.

### PR DESCRIPTION
**Pull request by yaeldekel**
When the label/weight/group Id column has a non-default name, we need to know how to pass that name to the evaluator in the CV macro.
Fixes #292 .

### CODE REVIEW

File: src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs [hunk 1]
```diff
@@ -383,10 +404,13 @@ public sealed class CombinedOutput
...
-            var combineConfusionMatrix = new Var<IDataView>();
-            combineConfusionMatrix.VarName = node.GetOutputVariableName(nameof(Output.ConfusionMatrix));
-            combineOutputMap.Add(nameof(TrainTestMacro.Output.ConfusionMatrix), combineConfusionMatrix.VarName);
+            if (confusionMatricesOutput != null)
+            {
+                var combineConfusionMatrix = new Var<IDataView>();
+                combineConfusionMatrix.VarName = node.GetOutputVariableName(nameof(Output.ConfusionMatrix));
+                combineOutputMap.Add(nameof(TrainTestMacro.Output.ConfusionMatrix), combineConfusionMatrix.VarName);
 
+            }
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs]: extra line

File: src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs [hunk 2]
```diff
@@ -455,22 +484,22 @@ private static IMamlEvaluator GetEvaluator(IHostEnvironment env, MacroUtils.Trai
...
-                    return new RankerMamlEvaluator(env, new RankerMamlEvaluator.Arguments());
-                case MacroUtils.TrainerKinds.SignatureAnomalyDetectorTrainer:
-                    return new AnomalyDetectionMamlEvaluator(env, new AnomalyDetectionMamlEvaluator.Arguments());
-                case MacroUtils.TrainerKinds.SignatureClusteringTrainer:
-                    return new ClusteringMamlEvaluator(env, new ClusteringMamlEvaluator.Arguments());
-                case MacroUtils.TrainerKinds.SignatureMultiOutputRegressorTrainer:
-                    return new MultiOutputRegressionMamlEvaluator(env, new MultiOutputRegressionMamlEvaluator.Arguments());
-                default:
-                    throw env.ExceptParam(nameof(kind), $"Trainer kind {kind} does not have an evaluator");
+            case MacroUtils.TrainerKinds.SignatureBinaryClassifierTrainer:
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs]: >             [](start = 0, length = 12)

My VS keeps old style if I ctrl+K+D this file. And I would personally prefer to have extra indent for case.

File: src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs [hunk 3]
```diff
@@ -508,6 +509,43 @@ public float Cost
...
+            }
+            if (!string.IsNullOrEmpty(weight) && inputInstance is LearnerInputBaseWithWeight)
+            {
+                var weightInputInstance = inputInstance as LearnerInputBaseWithWeight;
+                if (weight != weightInputInstance.WeightColumn)
+                    ch.Warning(warning, "weight", weight, weightInputInstance.WeightColumn);
+                else
+                    weightInputInstance.WeightColumn = weight;
+            }
+            if (!string.IsNullOrEmpty(weight) && inputInstance is UnsupervisedLearnerInputBaseWithWeight)
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs]: >WithWeight [](start = 94, length = 10)

Is it possible to refactor it into IHaveLabelColumn, IHaveWeightColum, IHaveGroupColumn? And check for interface instead of abstract class?

File: src/Microsoft.ML.Data/EntryPoints/InputBuilder.cs [hunk 4]
```diff
@@ -426,81 +429,81 @@ private static object ParseJsonValue(IExceptionContext ectx, Type type, Attribut
...
-                        if (type == typeof(int))
-                            return value.Value<int>();
-                        ectx.Assert(false);
-                        throw ectx.ExceptNotSupp();
-                    case TlcModule.DataKind.UInt:
-                        if (type == typeof(ulong))
-                            return value.Value<ulong>();
-                        if (type == typeof(uint))
-                            return value.Value<uint>();
+                case TlcModule.DataKind.Bool:
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/EntryPoints/InputBuilder.cs]: >                 [](start = 0, length = 16)

can you return old indentation? it's really hard to read changes

File: test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs [hunk 5]
```diff
@@ -593,5 +593,118 @@ public void TestCrossValidationMacroWithStratification()
...
+                var textToKey = new ML.Transforms.TextToKeyConverter();
+                textToKey.Column = new[] { new ML.Transforms.TermTransformColumn() { Name = "Label1", Source = "Label" } };
+                var textToKeyOutput = subGraph.Add(textToKey);
+
+                var hash = new ML.Transforms.HashConverter();
+                hash.Column = new[] { new ML.Transforms.HashJoinTransformColumn() { Name = "GroupId1", Source = "Workclass" } };
+                hash.Data = textToKeyOutput.OutputData;
+                var hashOutput = subGraph.Add(hash);
+
+                var learnerInput = new Trainers.FastTreeRanker
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs]: >FastTreeRanker [](start = 48, length = 14)

You can add Transforms.RandomNumberGenerator to emulate Weight column.

File: src/Microsoft.ML/Runtime/EntryPoints/MacroUtils.cs [hunk 6]
```diff
@@ -30,9 +30,8 @@ public sealed class EvaluatorSettings
         {
             public string LabelColumn { get; set; }
             public string NameColumn { get; set; }
-            public string ScoreColumn { get; set; }
-            public string[] StratColumn { get; set; }
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/MacroUtils.cs]: just curios, why?
don't we use it?

File: src/Microsoft.ML/CSharpApi.cs [hunk 7]
```diff
@@ -3456,6 +3481,21 @@ public sealed partial class TrainTestEvaluator
...
+
+            /// <summary>
+            /// Column to use for example weight
+            /// </summary>
+            public Microsoft.ML.Runtime.EntryPoints.Optional<string> WeightColumn { get; set; }
+
+            /// <summary>
+            /// Column to use for grouping
+            /// </summary>
+            public Microsoft.ML.Runtime.EntryPoints.Optional<string> GroupColumn { get; set; }
```
Comment (george-microsoft) [inline src/Microsoft.ML/CSharpApi.cs]: Is there any default which makes sense here for GorupColumn, such as Label has?

File: src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs [hunk 8]
```diff
@@ -188,7 +203,10 @@ public sealed class CombinedOutput
                 var args = new TrainTestMacro.Arguments
                 {
                     Nodes = new JArray(graph.Select(n => n.ToJson()).ToArray()),
-                    TransformModel = null
+                    TransformModel = null,
+                    LabelColumn = input.LabelColumn,
+                    GroupColumn = input.GroupColumn.IsExplicit ? input.GroupColumn : Optional<string>.Implicit(DefaultColumnNames.GroupId),
+                    WeightColumn = input.WeightColumn.IsExplicit ? input.WeightColumn : Optional<string>.Implicit(DefaultColumnNames.Weight)
```
Comment (george-microsoft) [inline src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs]: Does the second branch of the logic for GroupColumn again define the same default from Arguments? (I could be misunderstanding the code.) If it does repeat, might it be better to have it just use the value already assigned to the input arguments?

File: src/Microsoft.ML/Runtime/EntryPoints/MacroUtils.cs (hunk 6 above)
Comment (yaeldekel) [reply src/Microsoft.ML/Runtime/EntryPoints/MacroUtils.cs]: We don't. This class is used only when instantiating evaluator entry points in macros, where the score column always has the default name. The stratification option is not exposed there either.

---
In reply to: [192859511](https://github.com/dotnet/machinelearning/pull/291#discussion_r192859511) [](ancestors = 192859511)

File: src/Microsoft.ML/CSharpApi.cs (hunk 7 above)
Comment (yaeldekel) [reply src/Microsoft.ML/CSharpApi.cs]: The GroupColumn argument has a default value (see in TrainTestMacro.cs). I think this might be an issue with the CSharpCodeGenerator. I'll open an issue.

---
In reply to: [192864697](https://github.com/dotnet/machinelearning/pull/291#discussion_r192864697) [](ancestors = 192864697)

File: test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs (hunk 5 above)
Comment (yaeldekel) [reply test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs]: I couldn't add it to this test because the ranker trainer expects the weights to be constant per group. I added it instead to another CV macro test.

---
In reply to: [192858690](https://github.com/dotnet/machinelearning/pull/291#discussion_r192858690) [](ancestors = 192858690)
