### PR TITLE
Fix zero based key input from C# classes for matrix factorization

### LINKED ISSUE #1442: Matrix Factorization Doesn't Support Key Starting with 0
For row index = 0 or column index = 0, [this mapper](https://github.com/dotnet/machinelearning/blob/ef2bade365a90d926a944ebfc424b8a84374921c/src/Microsoft.ML.Recommender/MatrixFactorizationPredictor.cs#L230) always use NaN as the output score.

### PR DESCRIPTION
**Pull request by wschin**
Because of the getter in IDataView created from C# classes doesn't handle key properly, matrix factorization fails whenever there is a zero-based key input. This PR fixes this issue by modifying getter upon [peek](https://github.com/dotnet/machinelearning/blob/d68388a1c9994a5b429b194b64b2b0782834cb78/src/Microsoft.ML.Api/ApiUtils.cs#L53), which doesn't care key type at all. The major fix occurs in `src/Microsoft.ML.Api/DataViewConstructionUtils.cs`.
In addition, a test based on matrix factorization is made for preventing such an error from happening again in `test/Microsoft.ML.Tests/TrainerEstimators/MatrixFactorizationTests.cs`.

In addition, matrix factorization also got polished. We clean up unnecessary fields and make its comments better.

Fix #1442.

### CODE REVIEW

File: src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs [hunk 1]
```diff
@@ -29,44 +29,50 @@ public sealed class MatrixFactorizationTrainer : TrainerBase<MatrixFactorization
     {
         public sealed class Arguments
         {
-            [Argument(ArgumentType.AtMostOnce, HelpText = "Regularization parameter")]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Regularization parameter." +
+                "It's the weight of factor matrices' norms in the objective function minimized by matrix factorization's algorithm." +
+                "A amall value could cause over-fitting.")]
```
Comment (TomFinley) [inline src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs]: >amall [](start = 19, length = 5)

Typo

Comment (TomFinley) [inline src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs]: Note that `"algorithm."+"A"` has no space after the period.

File: src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs [hunk 2]
```diff
@@ -29,44 +29,50 @@ public sealed class MatrixFactorizationTrainer : TrainerBase<MatrixFactorization
...
 
-            [Argument(ArgumentType.AtMostOnce, HelpText = "Force the matrix factorization P and Q to be non-negative", ShortName = "nn")]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Force the factor matrices to be non-negative.", ShortName = "nn")]
             public bool NonNegative;
         };
 
         internal const string Summary = "From pairs of row/column indices and a value of a matrix, this trains a predictor capable of filling in unknown entries of the matrix, "
-            + "utilizing a low-rank matrix factorization. This technique is often used in recommender system, where the row and column indices indicate users and items, "
-            + "and the value of the matrix is some rating. ";
+            + "using a low-rank matrix factorization. This technique is often used in recommender system, where the row and column indices indicate users and items, "
```
Comment (TomFinley) [inline src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs]: >, " [](start = 163, length = 3)

You did it correctly here, so this is fine.

File: src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs [hunk 3]
```diff
@@ -29,44 +29,50 @@ public sealed class MatrixFactorizationTrainer : TrainerBase<MatrixFactorization
...
+                "It's the weight of factor matrices' norms in the objective function minimized by matrix factorization's algorithm." +
+                "A amall value could cause over-fitting.")]
             [TGUI(SuggestedSweeps = "0.01,0.05,0.1,0.5,1")]
             [TlcModule.SweepableDiscreteParam("Lambda", new object[] { 0.01f, 0.05f, 0.1f, 0.5f, 1f })]
-            public Double Lambda = 0.1;
+            public double Lambda = 0.1;
 
-            [Argument(ArgumentType.AtMostOnce, HelpText = "Latent space dimension")]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Latent space dimension (denoted by k). If the factorized matrix is m-by-n," +
+                "two factor matrices found by matrix factorization are m-by-k and k-by-n, respectively." +
```
Comment (TomFinley) [inline src/Microsoft.ML.Recommender/MatrixFactorizationTrainer.cs]: Same note. In fact review all of the places where you've split your documentation strings across multiple lines, since they are incorrect more often than they are correct.
