### PR TITLE
CpuMathNative assembly is not getting copied when using packages.config.

### LINKED ISSUE #93: Microsoft.ML NuGet package doesn't work with packages.config
### Original Title
Impossible to run Iris classification test

### System information

- **OS version/distro**:
Windows 10.0.17134
- **.NET Version (eg., dotnet --info)**: 
 Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

### Issue

- **What did you do?**
Try Iris tutorial

- **What happened?**
Runtime error:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Eccezione generata dalla destinazione di una chiamata.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.Run()
   at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAllNonMacros()
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
   at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
   at IrsiExample.Program.Main(String[] args) in C:\Users\gvolpi\source\repos\MLNetTest1\IrsiExample\Program.cs:line 69

Inner Exception 1:
TargetInvocationException: Eccezione generata dalla destinazione di una chiamata.

Inner Exception 2:
DllNotFoundException: Impossibile caricare la DLL 'CpuMathNative': Impossibile trovare il modulo specificato. (Eccezione da HRESULT: 0x8007007E).

- **What did you expect?**

### Source code / logs

Code copy/pasted from github

### PR DESCRIPTION
**Pull request by eerhardt**
When we refactored CpuMath to support netcoreapp3.0, we broke the packages.config support to copy the native assembly. This fixes it again by copying the file from the correct location.

Fix #93

### CODE REVIEW

File: pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    </Content>
+    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x86\nativeassets\netstandard2.0\*.dll"
+             Condition="'$(PlatformTarget)' == 'x86'">
+      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
+      <Visible>false</Visible>
+      <Link>%(Filename)%(Extension)</Link>
+    </Content>
+  </ItemGroup>
+
+</Project>
```
Comment (safern) [inline pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props]: Nit: Extra line at EOF

File: pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props [hunk 2]
```diff
@@ -0,0 +1,24 @@
+<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```
Comment (safern) [inline pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props]: Is the `xmlns` metadata needed?

Comment (eerhardt) [reply pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props]: We put it in there to support older MSBuild's - specifically we still support VS 2015 if you have the netstandard2.0 stuff installed on it.

Comment (eerhardt) [reply pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props]: We put it in there because this `.props` file gets loaded by the end-user's project. So we want to support as old of tools as possible. I believe we still support VS 2015 if you have the `netstandard2.0` support installed.

Comment (safern) [reply pkg/Microsoft.ML.CpuMath/build/netstandard2.0/Microsoft.ML.CpuMath.props]: Makes sense.
