### PR TITLE
Fixing inconsistency in usage of LossFunction

### LINKED ISSUE #2174: Inconsistency in usage of LossFunction for AveragedPerceptron and OnlineGradientDescent
The `Options`  class for AveragedPerceptron  and  OnlineGradientDescent  have a field  `LossFunction`  which is used as a factory 

https://github.com/dotnet/machinelearning/blob/cabf55b543129e8962ba716e8e22c72ac08773e3/src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs#L42-L46

https://github.com/dotnet/machinelearning/blob/cabf55b543129e8962ba716e8e22c72ac08773e3/src/Microsoft.ML.StandardLearners/Standard/Online/OnlineGradientDescent.cs#L38-L43
 
Instead of using the factory pattern, they should be  defined  as `IClassificationLoss` and `IRegressionLoss` respectively.  

That's  what the public API also uses:

https://github.com/dotnet/machinelearning/blob/cabf55b543129e8962ba716e8e22c72ac08773e3/src/Microsoft.ML.StandardLearners/StandardLearnersCatalog.cs#L167-L172

Refer to test case `OnlineLinearWorkout`

@sfilipi

### LINKED ISSUE #2594: user defined loss function
How to declare/use user defined loss function in RegressionMetrics ? RegressionMetrics.LossFn is read only. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd659ba-d3ca-b421-9b98-0ef4696eea68
* Version Independent ID: 54bb95b7-ec27-4880-c464-7c1f5c292e7f
* Content: [RegressionMetrics Class (Microsoft.ML.Data)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.regressionmetrics?view=ml-dotnet#applies-to)
* Content Source: [dotnet/xml/Microsoft.ML.Data/RegressionMetrics.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Data/RegressionMetrics.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

### PR DESCRIPTION
**Pull request by ganik**
fixes #2174
fixes #2594 
I had to re-do the PR due to messed up forked branch. This is a duplicate of #2856

### CODE REVIEW

File: src/Microsoft.ML.Data/Utils/LossFunctions.cs [hunk 1]
```diff
@@ -455,7 +466,7 @@ public sealed class Options : ISupportRegressionLossFactory
         private readonly Double _index1; // 1 minus the index parameter.
         private readonly Double _index2; // 2 minus the index parameter.
 
-        public TweedieLoss(Options options)
+        private TweedieLoss(Options options)
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Utils/LossFunctions.cs]: >private [](start = 8, length = 7)

why this one is private why every other constructor with options is internal?

Comment (ganik) [reply src/Microsoft.ML.Data/Utils/LossFunctions.cs]: others cant become internal due to build dependencies. This one can. 

---
In reply to: [264448101](https://github.com/dotnet/machinelearning/pull/2915#discussion_r264448101) [](ancestors = 264448101)
