### PR TITLE
Fix the treatment of LightGbm Evaluation Metric parameters in ML.NET …

### LINKED ISSUE #3761: The given key 'metric' was not present in the dictionary
### System information

- **OS version/distro**:
Windows 10
Windows 2012
Windows 2019
- **.NET Version (eg., dotnet --info)**: 
Core 3.0                          Version 3.0.100-preview5-011568
Microsoft.ML.LightGbm  Version 1.0.0.0, Culture=neutral
Microsoft.ML                   Version 1.0.0.0

### Issue
- **What did you do?**
Load csv file as and train model loading by all floats in single vector 
see code bellow

- **What happened?**
Get error _The given key 'metric' was not present in the dictionary_ during the training 

- **What did you expect?**
Not sure why I get the error, also I do not mention a key metric.

### Source code / logs
The error:
```
[Source=LightGBMMulticlass; Training with LightGBM, Kind=Trace] Channel disposed. Elapsed 00:00:04.0970203
.57.erLeaf = 5059.0337420.
Error stack    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)r_6_MinTicks_In_15Sec_B_ND.tsv
   at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmTraining.Train(IChannel ch, IProgressChannel pch, Dictionary`2 param
eters, Dataset dtrain, Dataset dvalid, Int32 numIteration, Boolean verboseEval, Int32 earlyStoppingRound)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainCore(IChannel ch, IProgressChannel pch, Dataset dtrain,
CategoricalMetaData catMetaData, Dataset dvalid)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredic
tor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Cats.DeepBookTrainer.Infrastructure.Trainer.ExecuteLightGbm(ITransformer& transformer, Nullable`1 maxIterations, N
ullable`1 maxThreads) 
```

Data Loading:
```
public static IDataView GetDataViewAsVector(MLContext mlContext, FileInfo trainingFile, int labelIndex=1, char[] separators = null, long? maxRows = null, bool makeBin=false)
{
    if (separators is null)
        separators = new[] { '|' };

    var loader = mlContext.Data.CreateTextLoader(options: new TextLoader.Options()
    {
        Columns = new[] {
            new TextLoader.Column(name:"Label", dataKind: DataKind.String, index: labelIndex),
            new TextLoader.Column(name:"RawFeatures",dataKind:DataKind.Single,minIndex:2,maxIndex:40732)
        },
        HasHeader = false,
        Separators = separators,
        UseThreads = false,
        MaxRows=maxRows
    });
    var dv = loader.Load(trainingFile.FullName);
    return dv;
}
```

Pipeline:
```
horizonDataset = mlContext.Data.TrainTestSplit(DataViewUtils.GetDataViewAsVector(mlContext, trainingFile, labelIndex: 1, separators: new[] {'|'}));

var options = new LightGbmMulticlassTrainer.Options
{
    LabelColumnName = "KeyColumn",
    FeatureColumnName = Features,
    Silent = false,
    Verbose = true,
    EvaluationMetric = LightGbmMulticlassTrainer.Options.EvaluateMetricType.Default,
    UseSoftmax       = true,
    NumberOfThreads  = 1,                
};

var featureColumns = Mapper.GetFieldNames();
var pipeline = mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "KeyColumn", inputColumnName: "Label")
        .Append(mlContext.Transforms.NormalizeMinMax(outputColumnName: "Features", inputColumnName: "RawFeatures"))
        .AppendCacheCheckpoint(mlContext)
        .Append(mlContext.MulticlassClassification.Trainers.LightGbm(options))
        .Append(mlContext.Transforms.CopyColumns(inputColumnName: "KeyColumn", outputColumnName: nameof(PredictedResult.PredictedLabelIndex)))
```
Line throwing the error 
`var model = pipeline.Fit(horizonDataset.TrainSet);`

### PR DESCRIPTION
**Pull request by najeeb-kazmi**
…and make them conform to LightGbm

Fixes #3761 plus some related issues discovered during investigation

1. There was a bug in LightGbm `EvaluateMetricType` where if a user specified `EvaluateMetricType.Default`, the metric would not get added to the options Dictionary, and `LightGbmWrappedTraining` would throw because of that. 

2. Secondly, `EvaluateMetricType.Default` in LightGbm is supposed to be an empty string "" and LightGbm chooses the default metric according to the problem type when this is specified. This was not present in ML.NET parameter name mappings. `EvaluateMetricType.None` is supposed to be "None" in LightGbm but was "" in ML.NET parameter name mappings.

3. [**Update: REVERTED**] Third, in ML.NET, the default `EvaluationMetric` is set to `EvaluateMetricType.Error` for multiclass, `EvaluationMetricType.LogLoss` for binary, and so on. This leads to inconsistent behavior from the user's perspective: If a user specified `EvaluationMetric = EvaluateMetricType.Default`, the parameter passed to LightGbm would be the empty string "" but if they do not specify `EvaluationMetric` at all, the parameter passed to LightGbm would be Error for multiclass, LogLoss for binary, and so on.

This PR does the following:
- Fixes the bug in (1)
- Addresses (2) by adding all the parameters to the options dictionary with the correct values (i.e. conforming to LightGbm [docs](https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric-parameters)
- [**Update: REVERTED**] Addresses (3) by changing the default `EvaluationMetric` in ML.NET to `EvaluationMetricType.Default`

### CODE REVIEW

File: src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs [hunk 1]
```diff
@@ -109,8 +111,7 @@ static Options()
                 var res = base.ToDictionary(host);
 
                 res[GetOptionName(nameof(Sigmoid))] = Sigmoid;
-                if(EvaluationMetric != EvaluateMetricType.Default)
-                    res[GetOptionName(nameof(EvaluateMetricType))] = GetOptionName(EvaluationMetric.ToString());
+                res[GetOptionName(nameof(EvaluateMetricType))] = GetOptionName(EvaluationMetric.ToString());
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs]: >EvaluateMetricType [](start = 41, length = 18)

wouldn't it be nice to have test?

Comment (najeeb-kazmi) [reply src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs]: You mean like check if EvaluationMetric exists here?

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.LightGbm/LightGbmMulticlassTrainer.cs]: [https://github.com/dotnet/machinelearning/issues/3761](https://github.com/dotnet/machinelearning/issues/3761) that issue showing certain code failure.
You PR claims it fixes it.
Would it make sense to add that code from issue to test we don't fail anymore?

---
In reply to: [290089536](https://github.com/dotnet/machinelearning/pull/3815#discussion_r290089536) [](ancestors = 290089536)
