### PR TITLE
Make SchemaShape.Column a struct instead of a class

### LINKED ISSUE #1706: Final interface of SchemaShape
1. Move to `Microsoft.ML.Data`
2. `internal-best-friend` all methods that are not accessing columns.
3. Make `SchemaShape` be a `IReadOnlyList<SchemaShape.Column>`
4. Add an accessor by name, and `GetColumnOrNull`, like `Schema` has.
5. Make `SchemaShape.Column` a `struct`.
6. Remove `SchemaException`.

### PR DESCRIPTION
**Pull request by wschin**
Fixes #1706.

### CODE REVIEW

File: src/Microsoft.ML.Core/Data/IEstimator.cs [hunk 1]
```diff
@@ -112,13 +112,19 @@ public string GetTypeString()
                     result = $"VarVector<{result}>";
                 return result;
             }
+
+            /// <summary>
+            /// Return if this structure is not identical to the default value of <see cref="Column"/>. If true,
+            /// it means this structure is initialized properly and therefore considered as valid.
+            /// </summary>
+            public bool IsValid => !Equals(default);
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/IEstimator.cs]: >!Equals(default); [](start = 35, length = 17)

I don't like this usage of `Equals`. This method is on `object`, so and takes an `object`, so there's going to be some pretty wild double boxing going on here. There's a simpler way: in the case where this is not valid, the name will be `null`, so I think we can just use that ... `IsValid => Name != null;`.

File: src/Microsoft.ML.Core/Utilities/Contracts.cs [hunk 2]
```diff
@@ -584,6 +584,11 @@ public static void CheckParamValue<T>(this IExceptionContext ctx, bool f, T valu
             if (object.ReferenceEquals(val, null))
                 throw ExceptValue(ctx, paramName);
         }
+        public static void CheckStruct<T>(this IExceptionContext ctx, T val, string paramName) where T : struct
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/Contracts.cs]: >CheckStruct [](start = 27, length = 11)

I'm not sure I like this idea of a `CheckStruct`. I think rather I'd prefer that the checks on the columns not be this `CheckStruct`, but rather directly against where it `IsValid`.

File: src/Microsoft.ML.Core/Data/IEstimator.cs (hunk 1 above)
Comment (wschin) [reply src/Microsoft.ML.Core/Data/IEstimator.cs]: No problem.

---
In reply to: [238850532](https://github.com/dotnet/machinelearning/pull/1822#discussion_r238850532) [](ancestors = 238850532)

File: src/Microsoft.ML.Core/Utilities/Contracts.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.Core/Utilities/Contracts.cs]: Just change `CheckStruct(col, nameof(col))` to `Contracts.Check(col.IsValid, nameof(col))`
`

---
In reply to: [238850745](https://github.com/dotnet/machinelearning/pull/1822#discussion_r238850745) [](ancestors = 238850745)

File: src/Microsoft.ML.Core/Utilities/Contracts.cs [hunk 3]
```diff
@@ -758,10 +758,27 @@ public static void CheckAlive(this IHostEnvironment env)
...
+        /// </summary>
         [Conditional("INVARIANT_CHECKS")]
         public static void CheckValueOrNull<T>(this IExceptionContext ctx, T val) where T : class
         {
         }
+        /// <summary>
+        /// This documents that the parameter can not legally be null because it is struct.
+        /// </summary>
+        [Conditional("INVARIANT_CHECKS")]
+        public static void CheckValueOrDefault<T>(T val) where T : struct
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Utilities/Contracts.cs]: >CheckValueOrDefault [](start = 27, length = 19)

Given that we're now doing this through other means, should probably revert these changes as well.

File: src/Microsoft.ML.Core/Data/MetadataUtils.cs [hunk 4]
```diff
@@ -367,7 +367,7 @@ public static bool IsNormalized(this Schema schema, int col)
         /// of a scalar <see cref="BoolType"/> type, which we assume, if set, should be <c>true</c>.</returns>
         public static bool IsNormalized(this SchemaShape.Column col)
         {
-            Contracts.CheckValue(col, nameof(col));
+            Contracts.Check(col.IsValid, nameof(col));
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/MetadataUtils.cs]: >Check [](start = 22, length = 5)

This would be `CheckParam`. Also you will want to provide some sort of message.

File: src/Microsoft.ML.Core/Data/IEstimator.cs [hunk 5]
```diff
@@ -16,13 +17,17 @@ namespace Microsoft.ML.Core.Data
     /// This is more relaxed than the proper <see cref="ISchema"/>, since it's only a subset of the columns,
     /// and also since it doesn't specify exact <see cref="ColumnType"/>'s for vectors and keys.
     /// </summary>
-    public sealed class SchemaShape
+    public sealed class SchemaShape : IReadOnlyList<SchemaShape.Column>
     {
         public readonly Column[] Columns;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Core/Data/IEstimator.cs]: >Column [](start = 24, length = 6)

Can you make it ImmutableList?
What will save you from IEnumarable casting in line 205

File: src/Microsoft.ML.Core/Utilities/Contracts.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.Core/Utilities/Contracts.cs]: Ok. Note that in `TrainerEstimatorBase.cs` we now do
```csharp
        private protected TrainerEstimatorBase(IHost host,
            SchemaShape.Column feature,
            SchemaShape.Column label,
            SchemaShape.Column weight = default)
        {
            Contracts.CheckValue(host, nameof(host));
            Host = host;
            Host.Check(feature.IsValid, nameof(feature));
            Host.Check(label.IsValid, nameof(label));

            FeatureColumn = feature;
            LabelColumn = label;
            WeightColumn = weight;
        }
```
after removing `CheckValueOrDefault(weight, nameof(weight))` and `CheckValueOrDefault(label, nameof(label))`.

---
In reply to: [238870053](https://github.com/dotnet/machinelearning/pull/1822#discussion_r238870053) [](ancestors = 238870053)

File: src/Microsoft.ML.Core/Data/MetadataUtils.cs (hunk 4 above)
Comment (wschin) [reply src/Microsoft.ML.Core/Data/MetadataUtils.cs]: Sure. We will use `Contracts.CheckParam(col.IsValid, nameof(col), "struct not initialized");`

---
In reply to: [238870227](https://github.com/dotnet/machinelearning/pull/1822#discussion_r238870227) [](ancestors = 238870227)

File: src/Microsoft.ML.Core/Data/IEstimator.cs (hunk 5 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Core/Data/IEstimator.cs]: What type is sealed? ImmuatableList? Why it's bad?

Comment (wschin) [reply src/Microsoft.ML.Core/Data/IEstimator.cs]: I am not sure if I understand your comment correctly. Do you mean I need to use `public class SchemaShape : ImmutableList<SchemaShape.Column>,` which can't not be compiled because classes can't be derived from sealed classes?

---
In reply to: [238881290](https://github.com/dotnet/machinelearning/pull/1822#discussion_r238881290) [](ancestors = 238881290)

File: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs [hunk 6]
```diff
@@ -60,7 +60,6 @@ public abstract class TrainerEstimatorBase<TTransformer, TModel> : ITrainerEstim
             Contracts.CheckValue(host, nameof(host));
             Host = host;
             Host.Check(feature.IsValid, nameof(feature));
-            Host.Check(label.IsValid, nameof(label));
```
Comment (wschin) [inline src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs]: We remove this because in Kmeans, `label` is just default so that `IsValid` is `false`.

File: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs [hunk 7]
```diff
@@ -181,7 +180,6 @@ public abstract class TrainerEstimatorBaseWithGroupId<TTransformer, TModel> : Tr
                 SchemaShape.Column groupId = default)
             :base(host, feature, label, weight)
         {
-            Host.CheckParam(groupId.IsValid, nameof(groupId), "struct not initialized properly.");
```
Comment (wschin) [inline src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs]: `groupId` can be `default` (aka missing) so this check got removed.

File: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs [hunk 8]
```diff
@@ -55,13 +55,11 @@ public abstract class TrainerEstimatorBase<TTransformer, TModel> : ITrainerEstim
...
             SchemaShape.Column label,
-            SchemaShape.Column weight = null)
+            SchemaShape.Column weight = default)
         {
             Contracts.CheckValue(host, nameof(host));
             Host = host;
-            Host.CheckValue(feature, nameof(feature));
-            Host.CheckValueOrNull(label);
-            Host.CheckValueOrNull(weight);
+            Host.Check(feature.IsValid, nameof(feature));
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs]: >Check [](start = 17, length = 5)

Host.CheckParam(col.IsValid, nameof(col), "not initialized properly") ?

File: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs [hunk 9]
```diff
@@ -122,8 +120,8 @@ private void CheckInputSchema(SchemaShape inputSchema)
 
         protected virtual void CheckLabelCompatible(SchemaShape.Column labelCol)
         {
-            Contracts.CheckValue(labelCol, nameof(labelCol));
-            Contracts.AssertValue(LabelColumn);
+            Contracts.Check(labelCol.IsValid, nameof(labelCol));
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs]: >Contracts.Check(labelCol.IsValid, nameof(labelCol)); [](start = 12, length = 52)

Host.CheckParam(labelCol.IsValid, nameof(labelCol), "not initialized properly") ?

File: src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs [hunk 10]
```diff
@@ -122,8 +120,8 @@ private void CheckInputSchema(SchemaShape inputSchema)
...
+            Contracts.Assert(LabelColumn.IsValid);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs]: >Contracts [](start = 12, length = 9)

can be Host

File: src/Microsoft.ML.Core/Utilities/Contracts.cs [hunk 11]
```diff
@@ -758,6 +758,9 @@ public static void CheckAlive(this IHostEnvironment env)
         public static void CheckValueOrNull<T>(T val) where T : class
         {
         }
+        /// <summary>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Core/Utilities/Contracts.cs]: would be nice to add new line here

File: src/Microsoft.ML.Core/Data/IEstimator.cs [hunk 12]
```diff
@@ -16,13 +17,17 @@ namespace Microsoft.ML.Core.Data
     /// This is more relaxed than the proper <see cref="ISchema"/>, since it's only a subset of the columns,
     /// and also since it doesn't specify exact <see cref="ColumnType"/>'s for vectors and keys.
     /// </summary>
-    public sealed class SchemaShape
+    public sealed class SchemaShape : IReadOnlyList<SchemaShape.Column>
```
Comment (TomFinley) [inline src/Microsoft.ML.Core/Data/IEstimator.cs]: >: IReadOnlyList<SchemaShape.Column> [](start = 36, length = 35)

This is not right! You can make this a `ReadOnlyList` with proper indexers and so forth. *Or* you could expose this `Columns` thing as you do below. You *CANNOT DO BOTH*.

Comment (wschin) [reply src/Microsoft.ML.Core/Data/IEstimator.cs]: You're absolutely right. Thanks a lot for pointing this out.

---
In reply to: [239226291](https://github.com/dotnet/machinelearning/pull/1822#discussion_r239226291) [](ancestors = 239226291)

File: src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs [hunk 13]
```diff
@@ -163,7 +163,7 @@ protected override void CheckLabels(RoleMappedData data)
 
         protected override void CheckLabelCompatible(SchemaShape.Column labelCol)
         {
-            Contracts.AssertValue(labelCol);
+            Contracts.Assert(labelCol.IsValid, nameof(labelCol));
```
[the remark this answers is not in the document]
Comment (wschin) [reply src/Microsoft.ML.StandardLearners/Standard/Online/AveragedPerceptron.cs]: Fixed this and other places. Thanks.

---
In reply to: [239262489](https://github.com/dotnet/machinelearning/pull/1822#discussion_r239262489) [](ancestors = 239262489)
