### PR TITLE
 OnnxTransform freezing - replace  tensor.CopyTo(List<float>) with tensor.CopyTo(float[]).

### LINKED ISSUE #1228: ONNX Transform Crashing or Freezing
ONNX Transform occasionally crashes or freezes when running certain onnx models (currently found with the Split operator). 

- The error is non deterministic and varies based on different machines
- On some machines, the ML.NET process will freeze, while on others it will simply silently crash without producing any output
- The larger the input, the more likely the issue seems to occur - almost never happens with <100 inputs, sometimes happens with 100-300 inputs, and almost always happens with >300 inputs
- When ML.NET is built in debug mode, the error will never occur. It only happens if it is built in release mode
- The issue is not tied to any specific input. Smaller inputs will never produce an error, while larger ones almost always will (in release mode)

### PR DESCRIPTION
**Pull request by jignparm**
Fixes #1228.

Reduce the number of data copies of a tensor. Use the Tensor.Copy() method to move contents directly into destination, rather than into a list[T] first, and then destination.

### CODE REVIEW

**Comment by vaeksare** [comment]
>         /// </summary>

Since this comment is no longer accurate with new APIs, you should change/remove it.

---
Refers to: src/Microsoft.ML.OnnxTransform/OnnxUtils.cs:340 in 4cf52d8. [](commit_id = 4cf52d880284ad316c31b90020d5aad6b41f03b1, deletion_comment = False)

**Comment by vaeksare** [comment]
>         /// Sonoma API only provides CopyTo() functions with overloaded versions

Since this comment is no longer accurate, you should change/remove it.

---
Refers to: src/Microsoft.ML.OnnxTransform/OnnxUtils.cs:334 in 4cf52d8. [](commit_id = 4cf52d880284ad316c31b90020d5aad6b41f03b1, deletion_comment = False)

File: src/Microsoft.ML.OnnxTransform/OnnxUtils.cs [hunk 1]
```diff
@@ -342,11 +342,8 @@ public static void CopyTo<T>(Tensor tensor, T[] dst)
         {
             if (typeof(T) == typeof(System.Single))
             {
-                // Sonoma only takes List<T>. We need to do an extra copy to T[]
-                var listDst = new List<System.Single>();
                 var typedDst = (System.Single[])(object)dst;
-                tensor.CopyTo(listDst);
-                listDst.CopyTo(typedDst);
+                tensor.CopyTo(typedDst);
```
Comment (ericstj) [inline src/Microsoft.ML.OnnxTransform/OnnxUtils.cs]: You could add a CopyTo<T>(T[] dst) to Sonoma and avoid this method entirely.
