### PR TITLE
Fixes DateTimeTransformer file path issue for NimbusML

### LINKED ISSUE #5220: DateTimeTransformer cant find its own json data
ML.NET 1.5.0
ML.Featurizers 0.17.0
Featurizers 0.4.1

Run NimbusML test_datetimesplitter.py method test_holidays. You get Exception:

RuntimeError: Error: *** System.Exception: ''Canada' is not a supported country name'
StackTrace:    at Microsoft.ML.Featurizers.DateTimeTransformer.TypedColumn.CreateTransformerFromEstimatorBase(HolidayList country)
at Microsoft.ML.Featurizers.DateTimeTransformer..ctor(IHostEnvironment host, String inputColumnName, String columnPrefix, HolidayList country, DataViewSchema schema)
at Microsoft.ML.Featurizers.DateTimeEstimator.Fit(IDataView input)
at Microsoft.ML.Featurizers.DateTimeTransformerEntrypoint.DateTimeSplit(IHostEnvironment env, Options input)

This is regression from ML.NET 1.5.0.preview2.

### PR DESCRIPTION
**Pull request by michaelgsharp**
Fixes #5220. This is a regression issue that was resolved before, unless the fix only stayed in the private branch for the featurizers.

### CODE REVIEW

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs [hunk 1]
```diff
@@ -574,11 +574,23 @@ private protected unsafe TransformerEstimatorSafeHandle CreateTransformerFromEst
...
-                    fixed (byte* dataRootDir = Encoding.UTF8.GetBytes(AppDomain.CurrentDomain.BaseDirectory + char.MinValue))
+                    byte[] dataRoot;
+
+                    if (Directory.Exists(AppDomain.CurrentDomain.BaseDirectory + "/Data/DateTimeFeaturizer"))
+                    {
+                        dataRoot = Encoding.UTF8.GetBytes(AppDomain.CurrentDomain.BaseDirectory + char.MinValue);
+                    }
+                    else
+                    {
+                        dataRoot = Encoding.UTF8.GetBytes(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + char.MinValue);
```
Comment (Lynx1820) [inline src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:585]: Does this statement work all the time? would it make sense to get rid of the above?

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs [hunk 2]
```diff
@@ -675,7 +687,18 @@ internal override unsafe void CreateTransformerFromEstimator(DateTimeEstimator.H
...
+                {
+                    dataRoot = Encoding.UTF8.GetBytes(AppDomain.CurrentDomain.BaseDirectory + char.MinValue);
+                }
+                else
+                {
+                    dataRoot = Encoding.UTF8.GetBytes(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + char.MinValue);
+                }
+
+                fixed (byte* dataRootDir = dataRoot)
                 {
```
Comment (Lynx1820) [inline src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:702]: You mentioned this was fixed before? Is this only a temporary solution? If so, could add a comment saying so?

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs (hunk 1 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:585]: This is to be able to find the data files in NimbusML whether it was compiled with .Net core or the full .Net framework. both those cases are hit, just depends on the framework.

We have a lot of the featurziers work on a private branch because it wont be checked into master, and this fix was in that private branch. I thought it was also in master. If it was in master, then this is a regression. If it wasn't in master, then this is a needed fix for NimbusML.

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs (hunk 2 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:702]: This isn't a temporary fix, see the prior comment I just responded to.

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs [hunk 3]
```diff
@@ -574,11 +574,23 @@ private protected unsafe TransformerEstimatorSafeHandle CreateTransformerFromEst
...
+                    {
+                        dataRoot = Encoding.UTF8.GetBytes(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + char.MinValue);
+                    }
+
+                    fixed (byte* dataRootDir = dataRoot)
                     fixed (byte* countryPointer = Encoding.UTF8.GetBytes(Enum.GetName(typeof(DateTimeEstimator.HolidayList), country) + char.MinValue))
                     {
                         success = CreateEstimatorHelper(countryPointer, dataRootDir, out estimator, out errorHandle);
                     }
+
```
Comment (Lynx1820) [inline src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:593]: nit: could we get rid of this line?

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs [hunk 4]
```diff
@@ -574,11 +574,23 @@ private protected unsafe TransformerEstimatorSafeHandle CreateTransformerFromEst
                 }
                 else
                 {
-                    fixed (byte* dataRootDir = Encoding.UTF8.GetBytes(AppDomain.CurrentDomain.BaseDirectory + char.MinValue))
+                    byte[] dataRoot;
+
+                    if (Directory.Exists(AppDomain.CurrentDomain.BaseDirectory + "/Data/DateTimeFeaturizer"))
+                    {
```
Comment (harishsk) [inline src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:580]: Any idea why this wasn't caught by our unit tests? If there isn't a test for this, can you please add one?

Comment (michaelgsharp) [reply src/Microsoft.ML.Featurizers/DateTimeTransformer.cs:580]: This only applies when run through NimbusML. ML.Net itself runs just fine without this. I am not sure how I would add a unit test for that? Any ideas?

File: src/Microsoft.ML.Featurizers/DateTimeTransformer.cs (hunk 3 above)
Comment (michaelgsharp) [reply src/Microsoft.ML.Featurizers/DateTimeTransformer.cs]: Removed.
