### PR TITLE
[One Line Change] Fix Kmeans Options Link

### LINKED ISSUE #3492: xref link in some Options classes isn't displayed correctly
AveragedPerceptronTrainer.Options:
Options for the AveragedPerceptronTrainer as used in [AveragedPerceptron(Options)](xref:Microsoft.ML.StandardTrainersCatalog.AveragedPerceptron(Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers,Microsoft.ML.Trainers.AveragedPerceptronTrainer.Options)

### PR DESCRIPTION
**Pull request by wschin**
Fix #3492 by replacing xref with cref in Kmean's Options. Other places have been fixed by someone.

### CODE REVIEW

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs [hunk 1]
```diff
@@ -91,7 +91,7 @@ internal static class Defaults
 
         /// <summary>
         /// Options for the <see cref="KMeansTrainer"/> as used in
-        /// [KMeansTrainer(Options)](xref:"Microsoft.ML.KMeansClusteringExtensions.KMeans(Microsoft.ML.ClusteringCatalog.ClusteringTrainers,Microsoft.ML.Trainers.KMeansTrainer.Options)".
```
Comment (yaeldekel) [inline src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: >xref [](start = 37, length = 4)

xref does work (see for example in `SgdCalibratedTrainer.Options`). I think the quotes are messing it up, and also there is a close parentheses that is missing.

Comment (wschin) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: I am not sure. I have seen xref are not rendered correctly in other places. After discussing Arti and Ivan, we feel ok to use cref because user will still be lined to the right page.

---
In reply to: [277886641](https://github.com/dotnet/machinelearning/pull/3550#discussion_r277886641) [](ancestors = 277886641)

Comment (shmoradims) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: please don't change xrefs where they are used to shorten the anchor text.

Yael pointed out the issues: delete quotes, add missing ) at the end.

if you paste UID from xref service directly into [anchor](xref:UID) you shouldn't have rendering issues.



---
In reply to: [277888214](https://github.com/dotnet/machinelearning/pull/3550#discussion_r277888214) [](ancestors = 277888214,277886641)

Comment (wschin) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: Ok. Fixed.

---
In reply to: [277889265](https://github.com/dotnet/machinelearning/pull/3550#discussion_r277889265) [](ancestors = 277889265,277888214,277886641)

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs [hunk 2]
```diff
@@ -90,8 +90,7 @@ internal static class Defaults
         }
 
         /// <summary>
-        /// Options for the <see cref="KMeansTrainer"/> as used in
-        /// [KMeansTrainer(Options)](xref:"Microsoft.ML.KMeansClusteringExtensions.KMeans(Microsoft.ML.ClusteringCatalog.ClusteringTrainers,Microsoft.ML.Trainers.KMeansTrainer.Options)".
+        /// Options for the <see cref="KMeansTrainer"/> as used in [KMeansTrainer(Options)](xref:Microsoft.ML.KMeansClusteringExtensions.KMeans(Microsoft.ML.ClusteringCatalog.ClusteringTrainers,Microsoft.ML.Trainers.KMeansTrainer.Options)).
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: >[KMeansTrainer(Options)](xref:Microsoft.ML.KMeansClusteringExtensions.KMeans(Microsoft.ML.ClusteringCatalog.ClusteringTrainers,Microsoft.ML.Trainers.KMeansTrainer.Options) [](start = 67, length = 171)

any reason why you not using `<see cref="Microsoft.ML.Trainers.KMeansTrainer.Options()"/> here?
I though only reason to use xref is then they inside markdown there usual `<see>` tags don't work.

Comment (wschin) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: @shmoradims said xref is desired because it can shorten the name of reference. Using xref is a explicit request from him.
