### PR TITLE
Added IDisposable to OnnxTransformer and fixed memory leaks

### LINKED ISSUE #5342: Load ONNX model creates temp file
### System information

- **OS version/distro**: Windows
- **.NET Version (eg., dotnet --info)**: .NET framework 4

### Issue

- **What did you do?**
Load model saved by ML.NET, the base model is in ONNX format
- **What happened?**
Everytime I load the model, a new onnx model file is created in %temp% folder and it is not deleted after releasing model object or after exiting the application. File path: %temp%\7bf1a39c-b65c-4874-927b-2bacbbf57b15\model.onnx
I tried to delete the file when the model was predicting but there is no error or exception and the result is the same.  
- **What did you expect?**
This file should be deleted or better not be created since it exposes our model to the user consumes too much user's memory.
### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

### PR DESCRIPTION
**Pull request by harishsk**
Fixes #5342 
A temp file was being created when the Onnx model was being loaded from within an ML.NET model. This file wasn't being deleted when the session exited because OnnxTransformer didn't support IDisposable. (Also added Dispose calls to OnnxTransformer objects in the tests)

Thanks to the reported bug, this also fixes memory leaks that we would see from OnnxRuntime.dll because the native memory associated with InferenceSession wasn't freed.

### CODE REVIEW

File: src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs [hunk 1]
```diff
@@ -339,10 +339,7 @@ public static OnnxModel CreateFromBytes(byte[] modelBytes)
         public static OnnxModel CreateFromBytes(byte[] modelBytes, int? gpuDeviceId = null, bool fallbackToCpu = false,
             IDictionary<string, int[]> shapeDictionary = null)
         {
-            var tempModelDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
-            Directory.CreateDirectory(tempModelDir);
-
-            var tempModelFile = Path.Combine(tempModelDir, "model.onnx");
+            var tempModelFile = $"{Path.GetTempFileName()}.onnx";
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs:342]: `Path.GetTempFileName()` will first create the file with that name. So you are creating an empty file every time here and not deleting it.

https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=netcore-3.1

> Creates a uniquely named, zero-byte temporary file on disk and returns the full path of that file.

Comment (harishsk) [reply src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs]: Thanks for spotting this. Should be fixed now.

File: test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs [hunk 2]
```diff
@@ -145,7 +145,9 @@ public void TestSimpleCase()
             pipe.GetOutputSchema(SchemaShape.Create(invalidDataWrongVectorSize.Schema));
             try
             {
-                pipe.Fit(invalidDataWrongVectorSize);
+                var onnxTransformer = pipe.Fit(invalidDataWrongVectorSize);
+                (onnxTransformer as IDisposable)?.Dispose();
```
Comment (antoniovs1029) [inline test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs:149]: Does this mean that now we'll ask our users to actually dispose the onnx transformer? Should we add docs about it?

Comment (antoniovs1029) [reply test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs:149]: Also, what happens if their pipeline consists of several transformers, will they need to extract the onnxtransformer and call dispose only on it?

Comment (harishsk) [reply test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs:149]: Yes, It should always be disposed. The leftover file happens only when loading from disk. But the inference session always gets left behind.`
I have updated the docs now. Thanks for the reminder.

File: src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs [hunk 3]
```diff
@@ -339,10 +339,7 @@ public static OnnxModel CreateFromBytes(byte[] modelBytes)
         public static OnnxModel CreateFromBytes(byte[] modelBytes, int? gpuDeviceId = null, bool fallbackToCpu = false,
             IDictionary<string, int[]> shapeDictionary = null)
         {
-            var tempModelDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
-            Directory.CreateDirectory(tempModelDir);
-
-            var tempModelFile = Path.Combine(tempModelDir, "model.onnx");
```
Comment (antoniovs1029) [inline src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs:345]: Just curious, was it necessary to change this?

Comment (harishsk) [reply src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs:345]: It was a single file in a directory. It wasn't adding much to it and there was already code to delete the file, but not the directory. So I just stopped creating the directory.

File: test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs (hunk 2 above)
Comment (justinormont) [reply test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs:149]: How will a user know there is an ONNX model within the pipeline they load? 

The ImageFeaturizer transform uses an ONNX model behind the scenes. Also, AutoML also loads its pipelines from disk.

Comment (harishsk) [reply test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs:149]: Tensorflow, Onnxruntime, ImageClassification are also cases where it is necessary to dispose the transformer. You are right that it is hard to assess all cases, especially in the AutoML scenarios. The safe approach is to dispose all models.
