### PR TITLE
Fix runtime exception in prior trainer sample and update the comments.

### LINKED ISSUE #3294: Prior Trainer sample throws an exception and the output comments do not match the actual output
Prior trainer used to take label type of float but this was changed to take label type of boolean to make it consistent with other binary trainers. Update the sample to change the schema of the data loader to accept label type of boolean and also update the comments to be consistent with the actual output from ML.NET

### PR DESCRIPTION
**Pull request by codemzs**
fixes #3294

### CODE REVIEW

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/PriorTrainerSample.cs [hunk 1]
```diff
@@ -63,7 +63,7 @@ public static void Example()
             //  Positive Precision: 0.50
             //  Positive Recall: 1.00
             //  LogLoss: 1.05
-            //  LogLossReduction: -4.89
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/PriorTrainerSample.cs]: Why does it change the baseline?

Comment (codemzs) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/PriorTrainerSample.cs]: It didn't the documentation was stable. I verified this without the prior trainer change from the master branch (removed the change that changes label type to boolean) and below is the output:

Accuracy: 0.50
AUC: 0.50
F1 Score: 0.67
Negative Precision: 0.00
Negative Recall: 0.00
Positive Precision: 0.50
Positive Recall: 1.00
Log Loss: 1.05
Log Loss Reduction: -0.05
Entropy: 1.00
