### PR TITLE
CV macro with stratification column doesn't work

### LINKED ISSUE #182: CrossValidationMacro doesn't work with stratification column
The CrossValidatorDatasetSplitter entry point applies a HashJoinTransform with the default number of bits (31) to the stratification column, and the RangeFilter that tries to split the data expects a key with a well known count.

### PR DESCRIPTION
**Pull request by yaeldekel**
The stratification column is being hashed to too many hash bits, and the RangeFilter that does the stratified split can't do the split. We reduce number of hash bits in stratification column so that the RangeFilter can split the data.
Fixes #182 .

### CODE REVIEW

File: test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs [hunk 1]
```diff
@@ -330,5 +330,73 @@ public void TestCrossValidationMacro()
...
+                    TransformModels = new ArrayVar<ITransformModel>(nopOutput.Model),
+                    PredictorModel = learnerOutput.PredictorModel
+                };
+                var modelCombineOutput = subGraph.Add(modelCombine);
+
+                var experiment = env.CreateExperiment();
+                var importInput = new ML.Data.TextLoader(dataPath);
+                importInput.Arguments.Column = new ML.Data.TextLoaderColumn[]
+                {
+                    new ML.Data.TextLoaderColumn { Name = "Label", Source = new[] { new ML.Data.TextLoaderRange {  Min = 0, Max = 0 } }, Type = DataKind.R4 },
```
Comment (TomFinley) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs]: >ML.Data.TextLoaderRange [](start = 88, length = 23)

I think for these scalar columns you can just use the simpler `new ML.Data.TextLoaderRange(0)` constructor.
