### PR TITLE
XML documentation for FastTree regression trainer.

### LINKED ISSUE #2522: Docs and samples for the API reference site (P0 & P1 Trainers)
# List of trainers per catalog

## BinaryClassification.Trainers

BinaryClassification Trainers | Category | Priority | Docs (1st pass) | Docs (2nd pass) | Samples (1st   pass) | Samples (2nd   pass)
-- | -- | -- | -- | -- | -- | --
AveragedPerceptron | Linear | 0 | Shahab #2517 | Done Shahab #3310  | Shahab #2517 |  Artidoro #3311 |
LogisticRegression | Linear | 0 | Wei-Sheng #3385  | Done Wei-Sheng #3385   | ZeeshanA #3099 |  Artidoro #3311|
Stochastic GradientDescent | Linear | 0 | Shahab #2688 |  @codemzs #3392 | Shahab #2688 |  Artidoro #3311|
StochasticDual CoordinateAscent | Linear | 0 | Shahab #2771 |  @codemzs #3395  | Shahab #2771 |  Artidoro #3311|
SymbolicStochastic GradientDescent | Linear | 0 | Ivan  | @codemzs #3396   |   |  Artidoro #3311|
LightGbm | Tree | 0 | Shahab #2886 | Done @codemzs #3397 | Shahab #2729 |  Artidoro #3311|
FastTree | Tree | 0 | Shahab #2970 | Done @codemzs #3398  | Shahab #3035 |  Artidoro #3311|
FastForest | Tree | 0 | Shahab #2970 | Done @codemzs #3399  | Shahab #3035 |  Artidoro #3311|
Field Aware FactorizationMachine | FFM | 0 | Wei-Sheng #3374  | Done Wei-Sheng #3374  | #3312 Wei-Sheng  | Wei-Sheng #3374  |
Generalized AdditiveModels | GAM | 1 | Shahab #2970 | Done @codemzs #3425 | @codemzs   |  Artidoro #3311|
Linear Support VectorMachines | Linear | 2 | Yael | Done #3401 Yael  |   |  Artidoro #3311|
Prior | Baseline | 2 | Aridoro #2510 |  Done  @codemzs #3426  | Artidoro #2510 |  Artidoro #3311|

## MulticlassClassification.Trainers

MulticlassClassification   Trainers | Category | Priority | Docs (1st pass) | Docs (2nd pass) | Samples | Samples (2nd   pass)
-- | -- | -- | -- | -- | -- | --
Lbfgs   MaximumEntropy | Linear | 0 | Wei-Sheng #3389 | Done Wei-Sheng #3389 |   | Artidoro#3322
Sdca   Max Ent | Linear | 0 | Shahab     #2771 | Done Wei-Sheng #3433  | #2771 | Artidoro #3322
Sdca   Non Calibrated | Linear | 0 |   | Done Wei-Sheng #3433  |   | Artidoro #3322
LightGbm | Tree | 0 | Shahab     #2886 | Done @codemzs #3427  | #2729 | Artidoro #3322
OneVersusAll | Meta | 0 | Gani     Done | Done Gani  #3387  | Done | Artidoro #3322
PairwiseCoupling | Meta | 1 | Gani     Done | Done Gani #3387 | Done | Artidoro #3322
NaiveBayes | Linear | 2 | Gani     Done | Done Gani #3387 | Done | Artidoro #3322

## Regression.Trainers

Regression.Trainers | Category | Priority | Docs (1st pass) | Docs (2nd pass) | Samples | Samples (2nd   pass)
-- | -- | -- | -- | -- | -- | --
StochasticDual   CoordinateAscent | Linear | 0 | Shahab     #2771 | @codemzs #3403 | #2771 | Wei-Sheng #3319
PoissonRegression | Linear | 0 | Shahab     #3059 | Done @codemzs #3404   | #3067 | Wei-Sheng #3319
OrdinaryLeastSquares | Linear | 0 | Shahab     #3059 |  Done @codemzs #3405 | Done | Wei-Sheng #3319
OnlineGradientDescent | Linear | 1 | Shahab     #3059 |  Done @codemzs #3422  | #3067(#2425 needs   to be fixed for the sample to be included | Wei-Sheng #3319
LightGbm | Tree | 0 | Shahab     #2886 |  Done @codemzs #3410 | #2729 | Wei-Sheng #3319
FastForest | Tree | 0 | Shahab     #2970 | Done @codemzs #3411  | #2999 | Wei-Sheng #3319
FastTree | Tree | 0 | Shahab     #2970 | Done @codemzs #3412  | #2999 | Wei-Sheng #3319
FastTreeTweedie | Tree | 0 | Shahab     #2970 | Done @codemzs #3414  | #2999 | Wei-Sheng #3319
Generalized   AdditiveModels | GAM | 1 | Rogan |  Done @codemzs #3421 | #2999 | Wei-Sheng #3319

## Misc catalogs

Catalog | Trainer | Priority | Docs | Docs (2nd pass) | Samples | Samples (2nd   pass)
-- | -- | -- | -- | -- | -- | --
Clustering | KMeans | 0 |   | Done Gani #3387|   | Artidoro #3317
AnomalyDetection | RandomizedPca | 1 | Yael  | @codemzs #3429  |  Done  |  Done
Ranking | FastTree | 2 | Shahab     #2970 | Done @codemzs #3430  |   | Artidoro #3338
Ranking | LightGbm | 2 | Shahab     #2886 | Done @codemzs #3431  | #2729 | Artidoro #3338
Recommendation | MatrixFactorization | 1 | Wei-Sheng #3409  | Done Wei-Sheng #3409 |   | Wei-Sheng #3362

### PR DESCRIPTION
**Pull request by codemzs**
towards #2522

### CODE REVIEW

File: src/Microsoft.ML.FastTree/FastTreeRegression.cs [hunk 1]
```diff
@@ -32,7 +32,28 @@ namespace Microsoft.ML.Trainers.FastTree
...
+    /// | Is caching required? | No |
+    /// | Required NuGet in addition to Microsoft.ML | Microsoft.ML.FastTree |
+    ///
+    /// [!include[algorithm](~/../docs/samples/docs/api-reference/algo-details-fasttree.md)]
+    /// ]]>
+    /// </format>
+    /// </remarks>
+    /// <seealso cref="Microsoft.ML.TreeExtensions.FastTree(Microsoft.ML.RegressionCatalog.RegressionTrainers,System.String,System.String,System.String,System.Int32,System.Int32,System.Int32,System.Double)"/>
+    /// <seealso cref="Microsoft.ML.TreeExtensions.FastTree(Microsoft.ML.RegressionCatalog.RegressionTrainers,Microsoft.ML.Trainers.FastTree.FastTreeRegressionTrainer.Options)"/>
+    /// <seealso cref="Options"/>
```
Comment (shmoradims) [inline src/Microsoft.ML.FastTree/FastTreeRegression.cs]: please use intellisense as discussed
