### PR TITLE
Fix typo in nuget Microsoft.ML.TensorFlow.TestModels

### LINKED ISSUE #804: Bug/typo in namespace: Missing the second 'o' of Microsoft in Microsft.ML.TensorFlow.TestModels
Looks like a Bug/typo in namespace: Missing the second 'o' of Microsoft in Micro**sft**.ML.TensorFlow.TestModels:

https://github.com/dotnet/machinelearning/blob/5ef7a082e2718874477d2f6e0119512ca0af9820/test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj#L38

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #804 

1. Fix typo in name of nuget package
2. Update version

### CODE REVIEW

File: test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj [hunk 1]
```diff
@@ -36,6 +36,6 @@
     <None Include="Scenarios\Api\AspirationalExamples.cs" />
   </ItemGroup>
   <ItemGroup>
-    <PackageReference Include="Microsft.ML.TensorFlow.TestModels" Version="0.0.2-test" />
+    <PackageReference Include="Microsoft.ML.TensorFlow.TestModels" Version="0.0.3-test" />
```
Comment (zeahmed) [inline test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj]: >-test [](start = 81, length = 5)

just out of curiosity, are we going to remove it (`-test`) sometime or we actually named it like this?
