### PR TITLE
Hide argument object in ensemble multivoting

### LINKED ISSUE #443: Ensembles code required small cleanup
Some files doesn't comply with our internal code policies (i.e. no consecutive new lines).
Diversity Measurement for binary and regression classification are indistinguishable.
Weighted average has wrong friendly name.
Multivoting doesn't required arguments and should always use normalize option as false.

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
fixes #443

### CODE REVIEW

File: src/Microsoft.ML.Ensemble/OutputCombiners/BaseMultiCombiner.cs [hunk 1]
```diff
@@ -15,7 +15,7 @@ public abstract class BaseMultiCombiner : IMultiClassOutputCombiner
     {
         protected readonly IHost Host;
 
-        public abstract class ArgumentsBase
+        public class ArgumentsBase
```
Comment (TomFinley) [inline src/Microsoft.ML.Ensemble/OutputCombiners/BaseMultiCombiner.cs]: >public class ArgumentsBase [](start = 8, length = 26)

Classes should be either abstract or sealed.

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Ensemble/OutputCombiners/BaseMultiCombiner.cs]: sure.

---
In reply to: [199927554](https://github.com/dotnet/machinelearning/pull/488#discussion_r199927554) [](ancestors = 199927554)
