### PR TITLE
ML Context to create them all

### LINKED ISSUE #1098: MLContext to create them all
During one of the in-person API reviews we agreed that it would be a good idea to have a single object `MLContext` that would serve as a 'factory of everything' (similar to the HTTP context / DB context in the .NET world).

- `MLContext` will explicitly implement `IHostEnvironment`, so you can create all the existing estimators by giving the context as the first argument.
- `MLContext` will have properties `BinaryClassification`, `Regression`, `Clustering` etc. for canonical ML tasks (the ones that are currently classes in themselves), complete with `Evaluate` and all corresponding trainers.
- It will have *extension methods* for non-canonical tasks like recommendation or anomaly detection etc.
- It will have properties `Transformation`, `Filtering`, `Loading` to instantiate all known transform estimators, filters and data readers (again via extension methods).
- It will have a pair of methods `SaveModel` and `LoadModel` that handle model serialization.

/cc @KrzysztofCwalina @TomFinley @eerhardt @markusweimer @asthana86

### PR DESCRIPTION
**Pull request by Zruty0**
Fixes #1098 . 
Adds a couple extensions for transforms, and almost all trainers.
Adds text loading and saving, model loading.

### CODE REVIEW

**Comment by sfilipi** [comment]
> using System;

copyright

---
Refers to: src/Microsoft.ML.Data/DataLoadSave/DataLoadSaveCatalog.cs:1 in 26913ac. [](commit_id = 26913ac9c057fdd491983b839a79e98cebd4be0e, deletion_comment = False)

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+namespace Microsoft.ML
+{
+    public static class TextLoaderSaverCatalog
+    {
+        /// <summary>
+        /// Create a text reader.
+        /// </summary>
+        /// <param name="catalog">The catalog.</param>
+        /// <param name="args">The arguments to text reader, describing the data schema.</param>
+        /// <param name="dataSample">The optional data sample</param>
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs]: data sample, or dataSource?

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+        /// <returns></returns>
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs]: ><returns></returns> [](start = 12, length = 19)

empty returns

File: src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+
+        /// <summary>
+        /// Save the model to the stream.
+        /// </summary>
+        /// <param name="model">The trained model to be saved.</param>
+        /// <param name="stream">A writeable, seekable stream to save to.</param>
+        public void Save(ITransformer model, Stream stream) => model.SaveTo(Environment, stream);
+
+        /// <summary>
+        /// Load the model from the stream.
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs]: >model [](start = 21, length = 5)

If we are saving and loading an ITransformer, should we call the class TransformerOperationsCatalog?

File: src/Microsoft.ML.Data/Training/TrainContext.cs [hunk 4]
```diff
@@ -403,7 +372,7 @@ internal MulticlassClassificationTrainers(MulticlassClassificationContext ctx)
         /// the top-K accuracy, that is, the accuracy assuming we consider an example with the correct class within
         /// the top-K values as being stored "correctly."</param>
         /// <returns>The evaluation results for these calibrated outputs.</returns>
-        public MultiClassClassifierEvaluator.Result Evaluate(IDataView data, string label, string score = DefaultColumnNames.Score,
+        public MultiClassClassifierEvaluator.Result Evaluate(IDataView data, string label = DefaultColumnNames.Label, string score = DefaultColumnNames.Score,
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Training/TrainContext.cs]: >string label = DefaultColumnNames.Label [](start = 77, length = 39)

would assigning defaults here be error prone, this allows the users to trip and provide a name for the label column in the estimators, and leave it to the default name here? We have not assigned defaults in the estimators.

File: src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+    /// Extensions for normalizer operations.
+    /// </summary>
+    public static class NormalizerCatalog
+    {
+        /// <summary>
+        /// Normalize (rescale) the column according to the specified <paramref name="mode"/>.
+        /// </summary>
+        /// <param name="catalog">The transform catalog</param>
+        /// <param name="columnName">The column name</param>
+        /// <param name="mode">The normalization mode</param>
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs]: >The normalization mod [](start = 31, length = 21)

cref maybe

File: src/Microsoft.ML.Data/Transforms/TransformsCatalog.cs [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+
+using Microsoft.ML.Runtime;
+using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace Microsoft.ML.Runtime
+{
+    /// <summary>
+    /// Similar to training context, a transform context is an object serving as a 'catalog' of available transforms.
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/TransformsCatalog.cs]: I like catalog.

File: src/Microsoft.ML.FastTree/Microsoft.ML.FastTree.csproj [hunk 7]
```diff
@@ -26,6 +26,7 @@
     <Compile Include="FastTreeRanking.cs" />
     <Compile Include="FastTreeRegression.cs" />
     <Compile Include="FastTree.cs" />
+    <Compile Include="FastTreeCatalog.cs" />
     <Compile Include="FastTreeStatic.cs" />
```
Comment (sfilipi) [inline src/Microsoft.ML.FastTree/Microsoft.ML.FastTree.csproj]: ><Compile Include="FastTreeStatic.cs" /> [](start = 4, length = 39)

did you mean to remove this?

File: src/Microsoft.ML.KMeansClustering/KMeansStatic.cs [hunk 8]
```diff
@@ -5,11 +5,10 @@
 using Microsoft.ML.Runtime;
 using Microsoft.ML.Runtime.Data;
 using Microsoft.ML.Runtime.KMeans;
-using Microsoft.ML.StaticPipe;
 using Microsoft.ML.StaticPipe.Runtime;
 using System;
 
-namespace Microsoft.ML.Trainers
+namespace Microsoft.ML.StaticPipe
```
Comment (sfilipi) [inline src/Microsoft.ML.KMeansClustering/KMeansStatic.cs]: >StaticPipe [](start = 23, length = 10)

why change namespace?

File: src/Microsoft.ML.Data/Training/MLContext.cs [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+        public ClusteringContext Clustering { get; }
+        /// <summary>
+        /// Trainers and tasks specific to ranking problems.
+        /// </summary>
+        public RankingContext Ranking { get; }
+
+        /// <summary>
+        /// Data processing operations.
+        /// </summary>
+        public TransformsCatalog Transform { get; }
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Training/MLContext.cs]: I know the other properties are not plural, but for some reason the singular `Transform` sticks out to me. It feels like it should be `Transforms`.

File: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+    {
+        /// <summary>
+        /// Train a KMeans++ clustering algorithm.
+        /// </summary>
+        /// <param name="ctx">The regression context trainer object.</param>
+        /// <param name="features">The features, or independent variables.</param>
+        /// <param name="weights">The optional example weights.</param>
+        /// <param name="clustersCount">The number of clusters to use for KMeans.</param>
+        /// <param name="advancedSettings">Algorithm advanced settings.</param>
+        public static KMeansPlusPlusTrainer KMeans(this ClusteringContext.ClusteringTrainers ctx,
```
[the remark this answers is not in the document]
Comment (Zruty0) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: hmm, I'm not sure why

---
In reply to: [224950512](https://github.com/dotnet/machinelearning/pull/1252#discussion_r224950512) [](ancestors = 224950512)

File: src/Microsoft.ML.KMeansClustering/KMeansStatic.cs (hunk 8 above)
Comment (Zruty0) [reply src/Microsoft.ML.KMeansClustering/KMeansStatic.cs]: I made this sweeping change, because otherwise we are seeing 2 methods per trainer in the intellisense by default. 

I think for now we want users to 'opt in' to the static API by using `StaticPipe`, and have the dynamic API available right off the bat

---
In reply to: [224950522](https://github.com/dotnet/machinelearning/pull/1252#discussion_r224950522) [](ancestors = 224950522)

**Comment by Zruty0** [comment]
> // Licensed to the .NET Foundation under one or more agreements.

It has to be in one of the folders :) It is mostly used for composing pipelines, so I picked `Training`. Do you have a better idea?

---
In reply to: [429941509](https://github.com/dotnet/machinelearning/pull/1252#issuecomment-429941509) [](ancestors = 429941509)

---
Refers to: src/Microsoft.ML.Data/Training/MLContext.cs:1 in 26913ac. [](commit_id = 26913ac9c057fdd491983b839a79e98cebd4be0e, deletion_comment = False)

File: src/Microsoft.ML.Data/Training/MLContext.cs (hunk 9 above)
Comment (Zruty0) [reply src/Microsoft.ML.Data/Training/MLContext.cs]: Hmm, I like it the way it is. Maybe other commenters can swing the vote?

---
In reply to: [225254551](https://github.com/dotnet/machinelearning/pull/1252#discussion_r225254551) [](ancestors = 225254551)

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs (hunk 1 above)
Comment (Zruty0) [reply src/Microsoft.ML.Data/DataLoadSave/Text/TextLoaderSaverCatalog.cs]: It's a sample

---
In reply to: [224948938](https://github.com/dotnet/machinelearning/pull/1252#discussion_r224948938) [](ancestors = 224948938)

File: src/Microsoft.ML.Data/Training/TrainContext.cs (hunk 4 above)
Comment (Zruty0) [reply src/Microsoft.ML.Data/Training/TrainContext.cs]: Actually, all the trainer extensions also have default names for `Label` and `Features`. This is why I made this change as well.

---
In reply to: [224950306](https://github.com/dotnet/machinelearning/pull/1252#discussion_r224950306) [](ancestors = 224950306)

File: src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs (hunk 3 above)
Comment (Zruty0) [reply src/Microsoft.ML.Data/Model/ModelOperationsCatalog.cs]: I think the name should reflect the user-facing concept, rather than the implementation fact that 'trained model is a transformer'.

---
In reply to: [224950106](https://github.com/dotnet/machinelearning/pull/1252#discussion_r224950106) [](ancestors = 224950106)

**Comment by eerhardt** [comment]
> // Licensed to the .NET Foundation under one or more agreements.

What's wrong with the folder: [https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.Data](https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.Data) ?

In general, the .NET Core team follows folders-namespace alignment, so it is easier to find files.  Since this type is in the root of the namespace: `Microsoft.ML`, I believe it should be in the root of the folders.

---
In reply to: [429953480](https://github.com/dotnet/machinelearning/pull/1252#issuecomment-429953480) [](ancestors = 429953480,429941509)

---
Refers to: src/Microsoft.ML.Data/Training/MLContext.cs:1 in 26913ac. [](commit_id = 26913ac9c057fdd491983b839a79e98cebd4be0e, deletion_comment = False)

File: src/Microsoft.ML.Data/Training/MLContext.cs [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+        public Action<string> Log { get; set; }
+
+        /// <summary>
+        /// Create the ML context.
+        /// </summary>
+        /// <param name="seed">Random seed. Set to <c>null</c> for a non-deterministic environment.</param>
+        /// <param name="conc">Concurrency level. Set to 1 to run single-threaded. Set to 0 to pick automatically.</param>
+        public MLContext(int? seed = null, int conc = 0)
+        {
+            _env = new LocalEnvironment(seed, conc);
```
[the remark this answers is not in the document]
Comment (Zruty0) [reply src/Microsoft.ML.Data/Training/MLContext.cs]: I would probably not bundle this change right now, but I'll write a REVIEW and a GitHib issue

---
In reply to: [225262172](https://github.com/dotnet/machinelearning/pull/1252#discussion_r225262172) [](ancestors = 225262172,225250207)

File: src/Microsoft.ML.Data/Training/MLContext.cs (hunk 9 above)
Comment (Zruty0) [reply src/Microsoft.ML.Data/Training/MLContext.cs]: Ok, I renamed it

---
In reply to: [225262070](https://github.com/dotnet/machinelearning/pull/1252#discussion_r225262070) [](ancestors = 225262070,225254551)

**Comment by Zruty0** [comment]
> // Licensed to the .NET Foundation under one or more agreements.

I put it in the root.

---
In reply to: [429967563](https://github.com/dotnet/machinelearning/pull/1252#issuecomment-429967563) [](ancestors = 429967563,429953480,429941509)

---
Refers to: src/Microsoft.ML.Data/Training/MLContext.cs:1 in 26913ac. [](commit_id = 26913ac9c057fdd491983b839a79e98cebd4be0e, deletion_comment = False)

File: docs/code/MlNetCookBook.md [hunk 12]
```diff
@@ -293,11 +288,11 @@ In the file above, the last column (12th) is label that we predict, and all the
 ```csharp
 // Create a new environment for ML.NET operations. It can be used for exception tracking and logging,
```
Comment (artidoro) [inline docs/code/MlNetCookBook.md]: >environment [](start = 16, length = 11)

Would be a good idea to replace with the above comments:

// Create a new context for ML.NET operations. It can be used for exception tracking and logging, 
// as a catalog of available operations and as the source of randomness.

File: docs/code/MlNetCookBook.md [hunk 13]
```diff
@@ -449,13 +437,13 @@ The prediction code now looks as follows:
 ```csharp
 // Create a new environment for ML.NET operations. It can be used for exception tracking and logging, 
 // as well as the source of randomness.
```
Comment (artidoro) [inline docs/code/MlNetCookBook.md]: Same as above, would be a good idea to replace with the above comments:

// Create a new context for ML.NET operations. It can be used for exception tracking and logging, 
// as a catalog of available operations and as the source of randomness.

File: docs/code/MlNetCookBook.md [hunk 14]
```diff
@@ -797,10 +776,10 @@ Sentiment   SentimentText
...
```
Comment (artidoro) [inline docs/code/MlNetCookBook.md]: Would be a good idea to replace with the above comments:

// Create a new context for ML.NET operations. It can be used for exception tracking and logging, 
// as a catalog of available operations and as the source of randomness.

File: docs/code/MlNetCookBook.md [hunk 15]
```diff
@@ -345,7 +337,7 @@ Assuming the example above was used to train the model, here's how you calculate
 var testData = reader.Read(new MultiFileSource(testDataPath));
 // Calculate metrics of the model on the test data.
 // We are using the 'regression' context object here to perform evaluation.
-var metrics = regression.Evaluate(model.Transform(testData), label: r => r.Target, score: r => r.Prediction);
+var metrics = mlContext.Regression.Evaluate(model.Transform(testData), label: r => r.Target, score: r => r.Prediction);
```
Comment (artidoro) [inline docs/code/MlNetCookBook.md]: Is this sentence still correct?

File: src/Microsoft.ML.Data/MLContext.cs [hunk 16]
```diff
@@ -0,0 +1,108 @@
...
+
+namespace Microsoft.ML
+{
+    /// <summary>
+    /// The <see cref="MLContext"/> is a starting point for all ML.NET operations. It is instantiated by user,
+    /// provides mechanisms for logging and entry points for training, prediction, model operations etc.
+    /// </summary>
+    public sealed class MLContext : IHostEnvironment
+    {
+        // REVIEW: consider making LocalEnvironment and MLContext the same class instead of encapsulation.
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/MLContext.cs]: I still don't fully understand our plan here with `LocalEnvironment` and `ConsoleEnvironment`. How could I ever use a `ConsoleEnvironment` with this new `MLContext` class?

And if the answer is "you can't - you'd use ConsoleEnvironment directly", I think that is a pretty poor answer because then my whole API paradigm changes. I can no longer use `BinaryClassificationContext`, `Transforms`, etc. from the `MLContext`.

Comment (eerhardt) [reply src/Microsoft.ML.Data/MLContext.cs]: What do you think about the answer: "you can't use ConsoleEnvironment because it is internal and only used by MAML"?

---
In reply to: [225986842](https://github.com/dotnet/machinelearning/pull/1252#discussion_r225986842) [](ancestors = 225986842)

Comment (Zruty0) [reply src/Microsoft.ML.Data/MLContext.cs]: That would be fine with me. For now, I would think it's completely fine to have our custom console printing internal to the commandline tool

---
In reply to: [225989180](https://github.com/dotnet/machinelearning/pull/1252#discussion_r225989180) [](ancestors = 225989180,225986842)

Comment (eerhardt) [reply src/Microsoft.ML.Data/MLContext.cs]: https://github.com/dotnet/machinelearning/issues/1284

Comment (Zruty0) [reply src/Microsoft.ML.Data/MLContext.cs]: Thanks.

---
In reply to: [226052093](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226052093) [](ancestors = 226052093)

File: test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs [hunk 17]
```diff
@@ -131,21 +127,20 @@ private void TrainRegression(string trainDataPath, string testDataPath, string m
...
             // Calculate metrics of the model on the test data.
-            // We are using the 'regression' context object here to perform evaluation.
-            var metrics = regression.Evaluate(model.Transform(testData), label: r => r.Target, score: r => r.Prediction);
+            var metrics = mlContext.Regression.Evaluate(model.Transform(testData), label: r => r.Target, score: r => r.Prediction);
 
             using (var stream = File.Create(modelPath))
             {
                 // Saving and loading happens to 'dynamic' models, so the static typing is lost in the process.
-                model.AsDynamic.SaveTo(env, stream);
+                mlContext.Model.Save(model.AsDynamic, stream);
```
Comment (eerhardt) [inline test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs]: Thoughts on making this so I don't have to say `model.AsDynamic`?  Can we open an issue to add that overload?

Comment (Zruty0) [reply test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs]: absolutely

---
In reply to: [226105313](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226105313) [](ancestors = 226105313)

File: test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs [hunk 18]
```diff
@@ -665,11 +643,36 @@ private void MixMatch(string dataPath)
...
+
+            // Create the reader: define the data columns and where to find them in the text file.
+            var reader = mlContext.Data.TextReader(new[] {
+	                // We read the first 10 values as a single float vector.
+                    new TextLoader.Column("FeatureVector", DataKind.R4, new[] {new TextLoader.Range(0, 9)}),
+                    // Separately, read the target variable.
+                    new TextLoader.Column("Target", DataKind.R4, 10)
+                },
+                // Default separator is tab, but we need a comma.
+                s => s.Separator = ",");
```
Comment (eerhardt) [inline test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs]: (This is probably not exactly related to `MLContext`, but since you wrote this new test, I'll ask the question):

Do we like having `s =>` here? Why isn't the separator just an argument in the `TextReader()` method?

Comment (Zruty0) [reply test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamples.cs]: The pattern we want to have is that we add the most important options as ctor options, and the rest 'advanced' inside the delegate.
The other pattern is that we want the extensions to replicate the signatures of constructors, to avoid any mapping logic in strange places. 
Because of that, I'd rather change the signature of `TextLoader` ctor to add 'hasHeader' and 'separator', but we will need to do it in a separate PR.

Also 'separator' should not really be a string :)

---
In reply to: [226106086](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226106086) [](ancestors = 226106086)

File: src/Microsoft.ML.Transforms/CategoricalTransform.cs [hunk 19]
```diff
@@ -128,7 +128,7 @@ public Arguments()
         public static IDataView Create(IHostEnvironment env, IDataView input, string name,
             string source = null, OutputKind outputKind = CategoricalEstimator.Defaults.OutKind)
         {
-            return new CategoricalEstimator(env, name, source, outputKind).Fit(input).Transform(input) as IDataView;
+            return new CategoricalEstimator(env, source, name, outputKind).Fit(input).Transform(input) as IDataView;
```
Comment (eerhardt) [inline src/Microsoft.ML.Transforms/CategoricalTransform.cs]: Maybe we should consider renaming and re-ordering the parameters to this method as well. `name` and `source` don't really help say what they are. Also, if `new CategoricalEstimator` has it one way, and `CategoricalTransform.Create` has it the other way, that is going to lead to confusion.

File: src/Microsoft.ML.Transforms/Text/TextTransformCatalog.cs [hunk 20]
```diff
@@ -0,0 +1,38 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using Microsoft.ML.Runtime;
+using Microsoft.ML.Runtime.Data;
+using System;
+using System.Collections.Generic;
+
+namespace Microsoft.ML
```
Comment (eerhardt) [inline src/Microsoft.ML.Transforms/Text/TextTransformCatalog.cs]: (nit) Since this is in the `Microsoft.ML` namespace, my preference would be for the file to not be under the `Text` folder. I think namespaces and folders should align.

File: src/Microsoft.ML.Transforms/CategoricalTransform.cs (hunk 19 above)
Comment (Zruty0) [reply src/Microsoft.ML.Transforms/CategoricalTransform.cs]: Sure

---
In reply to: [226108453](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226108453) [](ancestors = 226108453)

File: src/Microsoft.ML.FastTree/FastTreeCatalog.cs [hunk 21]
```diff
@@ -0,0 +1,102 @@
...
+using Microsoft.ML.Runtime.Internal.Internallearn;
+using Microsoft.ML.StaticPipe.Runtime;
+using System;
+
+namespace Microsoft.ML
+{
+    /// <summary>
+    /// FastTree <see cref="TrainContextBase"/> extension methods.
+    /// </summary>
+    public static partial class RegressionTrainers
```
Comment (eerhardt) [inline src/Microsoft.ML.FastTree/FastTreeCatalog.cs]: There already is a `Microsoft.ML.RegressionTrainers` class in the StandardLearners and LightGBM assemblies. We shouldn't have public types with the same namespace and name across multiple assemblies. It is only going to cause headaches for our users.

Comment (eerhardt) [reply src/Microsoft.ML.FastTree/FastTreeCatalog.cs]: This applies to all the other extension classes as well.

---
In reply to: [226109180](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226109180) [](ancestors = 226109180)

Comment (Zruty0) [reply src/Microsoft.ML.FastTree/FastTreeCatalog.cs]: I believe this was intentionally done by Senja for some documentation reasons?

---
In reply to: [226109272](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226109272) [](ancestors = 226109272,226109180)

File: src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs [hunk 22]
```diff
@@ -0,0 +1,44 @@
...
+using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace Microsoft.ML.Data.Transforms
+{
+    /// <summary>
+    /// Extensions for normalizer operations.
+    /// </summary>
+    public static class NormalizerCatalog
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs]: What are the use cases for `NormalizerCatalog`? I don't see any usages of it in this PR.

I see it is a static class, while all the other "catalog" classes are instance members of MLContext. Should it be designed the same as say `TransformsCatalog`?

Also, I don't see any tests using this class.

File: src/Microsoft.ML.FastTree/FastTreeCatalog.cs (hunk 21 above)
Comment (Zruty0) [reply src/Microsoft.ML.FastTree/FastTreeCatalog.cs]: Let me keep it as is for now, and I'll sync with her and understand why it was done. For me, it would've been much easier to group by trainer, into `FastTreeTrainerCatalog` or something

---
In reply to: [226109747](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226109747) [](ancestors = 226109747,226109272,226109180)

File: src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs (hunk 22 above)
Comment (eerhardt) [reply src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs]: Ah, I get it - this provides extension methods to the `TransformsCatalog`. How about we name these "Extension" only classes differently then? It is confusing in my opinion that `NormalizerCatalog` and `TransformsCatalog` are named similarly, but are designed differently.

---
In reply to: [226110284](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226110284) [](ancestors = 226110284)

Comment (Zruty0) [reply src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs]: This is a set of extensions to `TransformsCatalog`. I guess I will need to rename it

---
In reply to: [226110284](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226110284) [](ancestors = 226110284)

Comment (eerhardt) [reply src/Microsoft.ML.Data/Transforms/NormalizerCatalog.cs]: And add tests :D

---
In reply to: [226110673](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226110673) [](ancestors = 226110673,226110284)

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs [hunk 23]
```diff
@@ -1320,6 +1337,8 @@ public void Save(ModelSaveContext ctx)
 
         public IDataView Read(IMultiStreamSource source) => new BoundLoader(this, source);
 
+        public IDataView Read(string path) => Read(new MultiFileSource(path));
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: :heart:

File: src/Microsoft.ML.FastTree/FastTreeCatalog.cs (hunk 21 above)
Comment (eerhardt) [reply src/Microsoft.ML.FastTree/FastTreeCatalog.cs]: > Let me keep it as is for now

I don't know .... this is a pretty strong "don't" rule in general. If we are going to fix this very soon (like the next few days), I'm OK with it. But please log an issue. We can't ship with conflicting types across our assemblies.

Comment (Zruty0) [reply src/Microsoft.ML.FastTree/FastTreeCatalog.cs]: OK spoke to Senja, we should revert that :)

---
In reply to: [226113726](https://github.com/dotnet/machinelearning/pull/1252#discussion_r226113726) [](ancestors = 226113726)
