### PR TITLE
Fix CV macro to output the warnings data view properly.

### LINKED ISSUE #384: The warnings data view in CV macro is always null
The inputs and outputs are not being wired correctly in the macro, resulting in a null for the warnings data view.

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #384 .

### CODE REVIEW

File: src/Microsoft.ML.Data/Evaluators/MulticlassClassifierEvaluator.cs [hunk 1]
```diff
@@ -256,6 +256,8 @@ public Double MacroAvgAccuracy
                 {
                     get
                     {
+                        if (_numInstances == 0)
+                            return 0;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Evaluators/MulticlassClassifierEvaluator.cs]: >0 [](start = 35, length = 1)

maybe NaN?

Comment (codemzs) [reply src/Microsoft.ML.Data/Evaluators/MulticlassClassifierEvaluator.cs]: NaN means not a number but if instances are zero then isn't it accurate to say accuracy is zero? 

---
In reply to: [196921243](https://github.com/dotnet/machinelearning/pull/385#discussion_r196921243) [](ancestors = 196921243)

File: test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs [hunk 2]
```diff
@@ -528,6 +528,89 @@ public void TestCrossValidationMacroWithMultiClass()
...
+
+        [Fact]
+        public void TestCrossValidationMacroMultiClassWithWarnings()
+        {
+            var dataPath = GetDataPath(@"Train-Tiny-28x28.txt");
+            using (var env = new TlcEnvironment(42))
+            {
+                var subGraph = env.CreateExperiment();
+
+                var nop = new ML.Transforms.NoOperation();
```
Comment (codemzs) [inline test/Microsoft.ML.Core.Tests/UnitTests/TestCSharpApi.cs]: Using entrypoints graph is fine for now in C# but please consider not using it and instead call the low level C# APIs for component initialization from now on. We will be getting rid of CSharpCodeGenerator as there is no need to use C# code generated APIs when low level C# APIs already exist. Refer to issue #371
