### PR TITLE
Scrub Fast Tree Family

### LINKED ISSUE #2375: Parameter name Consistency in FastTree
https://github.com/dotnet/machinelearning/blob/4bb3e0006c656387ec96dc7e5878e204e1710f50/src/Microsoft.ML.FastTree/FastTreeArguments.cs#L528

Should this be LearningRate? The Options have it named wrongly.

The named parameter for the FastTree is named correctly as learningRate.
https://github.com/dotnet/machinelearning/blob/4bb3e0006c656387ec96dc7e5878e204e1710f50/src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs#L34

It would be great if you can check the same with all the trainers and transforms. i.e the named parameters(in the method) resemble the Actual Property name(in the options). In my opinion these all should be consistent. In case of named params (camel case) and for actual Property (of course is pascal case)

### LINKED ISSUE #2617: Scrubbing FastTree learners
Sub task of #2613
`FastTreeBinaryClassificationTrainer`
`FastTreeRankingTrainer`
`FastTreeRegressionTrainer`
`FastTreeTweedieTrainer`
`BinaryClassificationGamTrainer`
`RegressionGamTrainer`
`FastForestClassification`
`FastForestRegression`

and their base classes.
Also note how everywhere in code we call AlgoTypeOfTask for our trainers and in GAM it's opposite.

and their base classes

### LINKED ISSUE #2857: GAM parameter names are non-standard
The trained `Generalized Additive Models` (aka `GAMs`) methods for obtaining trained model parameters have non-standard names and various inconsistencies.

These are the properties:
```cs
var shapeFunctionsBins = gamModel.GetBinUpperBounds();
var shapeFunctionsValues = gamModel.GetBinEffects();
var numShapeFunctions = gamModel.NumShapeFunctions;
var intercept = gamModel.Intercept;
```

There are a few issues here:
1. Nonstandard names
I propose `BinUpperBounds` and `BinEffects` be renamed `ShapeFunctionsBins` and `ShapeFunctionsBinValues`.
2. Inconsistent names
Sometimes we say `ShapeFunctions`, sometimes we done. Same solution proposed as No. 1.
3. Inconsistency in `Get` methods vs. properties
e.g. `Intercept` vs. `GetBinUpperBounds`.
I propose we move all the methods to be properties.
e.g. `model.ShapeFunctionsBins`.
4. Names leak implementation
`BinUpperBounds` vs. `Bins`.
Question: should we just say `Bins` rather than `BinUpperBounds` and say that they are the upper bounds for the bin in the documentation? `BinUpperBounds` is very verbose, and speaks to how we bin.

### PR DESCRIPTION
**Pull request by wschin**
This PR fixes #2617 (also fixes #2375, fixes #2857) and is also a part of #2613.

Cleaned items:

- [x] FastTree.cs
- [x] FastTreeArguments.cs
- [x] Derived fast tree classes
- [x] Gam family

### CODE REVIEW

File: docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs [hunk 1]
```diff
@@ -35,16 +35,6 @@ public static void Example()
 
             // Get the trained model parameters.
             var modelParams = model.LastTransformer.Model;
-
-            // Let's see where an example with Parity = 1 and Induced = 1 would end up in the single trained tree.
-            var testRow = new VBuffer<float>(2, new[] { 1.0f, 1.0f });
-            // Use the path object to pass to GetLeaf, which will populate path with the IDs of th nodes from root to leaf.
-            List<int> path = default;
-            // Get the ID of the leaf this example ends up in tree 0.
-            var leafID = modelParams.GetLeaf(0, in testRow, ref path);
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs]: Removed because our public APIs doesn't provide those functions.

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 2]
```diff
@@ -174,16 +174,16 @@ public abstract class TreeOptions : LearnerInputBaseWithGroupId
         /// <summary>
         /// The seed of the random number generator.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the random number generator", ShortName = "r1")]
-        public int RngSeed = 123;
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the random number generator", ShortName = "r1,RngSeed")]
+        public int RandomSeed = 123;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >RandomSeed [](start = 19, length = 10)

I think everywhere else we call it just `seed`.

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 3]
```diff
@@ -174,16 +174,16 @@ public abstract class TreeOptions : LearnerInputBaseWithGroupId
...
 
         // this random seed is only for active feature selection
         /// <summary>
         /// The seed of the active feature selection.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the active feature selection", ShortName = "r3", Hide = true)]
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the active feature selection", ShortName = "r3,FeatureSelectSeed", Hide = true)]
         [TGUI(NotGui = true)]
-        public int FeatureSelectSeed = 123;
+        public int FeatureSelectionRandomSeed = 123;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >FeatureSelectionRandomSeed [](start = 19, length = 26)

Do we really need two of them?

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 4]
```diff
@@ -231,16 +231,16 @@ public abstract class TreeOptions : LearnerInputBaseWithGroupId
         public int MaxCategoricalSplitPoints = 64;
 
         /// <summary>
-        /// Minimum categorical docs percentage in a bin to consider for a split.
+        /// Minimum categorical example percentage in a bin to consider for a split.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Minimum categorical docs percentage in a bin to consider for a split.", ShortName = "mdop")]
-        public double MinDocsPercentageForCategoricalSplit = 0.001;
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Minimum categorical docs percentage in a bin to consider for a split.", ShortName = "mdop,MinDocsPercentageForCategoricalSplit")]
+        public double MinExamplePercentageForCategoricalSplit = 0.001;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >Min [](start = 22, length = 3)

Minimum

Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >0.001 [](start = 64, length = 5)

is it 0.001% or 0.1% ?

File: src/Microsoft.ML.FastTree/FastTree.cs [hunk 5]
```diff
@@ -3232,7 +3233,10 @@ private void ToCSharp(InternalRegressionTree tree, TextWriter writer, int node,
             }
         }
 
-        public void GetFeatureWeights(ref VBuffer<Float> weights)
+        /// <summary>
+        /// Copy the weights of all training features to <paramref name="weights"/>.
+        /// </summary>
+        public void GetFeatureWeights(ref VBuffer<float> weights)
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTree.cs]: Not sure if this should return `IReadOnlyList<float>`.

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 6]
```diff
@@ -262,8 +262,8 @@ public abstract class TreeOptions : LearnerInputBaseWithGroupId
         /// <summary>
         /// Maximum number of distinct values (bins) per feature.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Maximum number of distinct values (bins) per feature", ShortName = "mb")]
-        public int MaxBins = 255;  // save one for undefs
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Maximum number of distinct values (bins) per feature", ShortName = "mb,MaxBins")]
+        public int MaxBinCountPerFeature = 255;  // save one for undefs
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >Max [](start = 19, length = 3)

Maximum

**Comment by Ivanidzo4ka** [comment]
>         /// Print execution time breakdown to stdout.

are we really print into stdout or we use our logging mechanism?

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:301 in d64a4ae. [](commit_id = d64a4aed005c8861947bab650bfc18df079b7570, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 7]
```diff
@@ -346,18 +346,18 @@ public abstract class TreeOptions : LearnerInputBaseWithGroupId
...
         /// <summary>
         /// The fraction of features (chosen randomly) to use on each split.
         /// </summary>
-        [Argument(ArgumentType.AtMostOnce, HelpText = "The fraction of features (chosen randomly) to use on each split", ShortName = "sf")]
-        public Double SplitFraction = 1;
+        [Argument(ArgumentType.AtMostOnce, HelpText = "The fraction of features (chosen randomly) to use on each split", ShortName = "sf,SplitFraction")]
+        public Double FeatureFractionPerSplit = 1;
 
         /// <summary>
         /// Smoothing paramter for tree regularization.
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >paramter [](start = 22, length = 8)

parameter

**Comment by Ivanidzo4ka** [comment]
>         public bool PrintTrainValidGraph;

is this remnants of TLC TV ?
Do we need to expose them?

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:410 in d64a4ae. [](commit_id = d64a4aed005c8861947bab650bfc18df079b7570, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 3 above)
Comment (TomFinley) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: Kind of. There are two degrees of control that internal people wanted to independently vary or not vary: selection of *features* and selection of *data*. I have not kept touch with this set of people over the years but the reasoning at one point was definitely considered important. Let us not change it.

**Comment by TomFinley** [comment]
> > ```
> >     public bool PrintTrainValidGraph;
> > ```
> 
> is this remnants of TLC TV ?
> Do we need to expose them?
> 
> Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:410 in [d64a4ae](https://github.com/dotnet/machinelearning/commit/d64a4aed005c8861947bab650bfc18df079b7570). [](commit_id = [d64a4ae](https://github.com/dotnet/machinelearning/commit/d64a4aed005c8861947bab650bfc18df079b7570), deletion_comment = False)

It has nothing to do with TLC TV. Let us make internal for now.

File: docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs (hunk 1 above)
Comment (Ivanidzo4ka) [reply docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs]: But you can still traverse through trees with new structure, right?

---
In reply to: [260562343](https://github.com/dotnet/machinelearning/pull/2753#discussion_r260562343) [](ancestors = 260562343)

**Comment by Ivanidzo4ka** [comment]
>         public RegressionTreeEnsemble TrainedTreeEnsemble { get; }

I've looked into RegressionTree.cs and some things like:
NumLeaves, NumNodes, GtChild, LteChild doesn't sound like great names
Shall we address that in this PR as well?

---
Refers to: src/Microsoft.ML.FastTree/FastTree.cs:3393 in aa0b9c2. [](commit_id = aa0b9c2baa6a609e2b87b7cf44234c6cf4191d8a, deletion_comment = False)

File: docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs (hunk 1 above)
Comment (wschin) [reply docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs]: No, we cannot. @tfinley@gmail.com, do you think this feature is required in tree's public APIs?

---
In reply to: [261011054](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261011054) [](ancestors = 261011054,260562343)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: Sure.

---
In reply to: [260562756](https://github.com/dotnet/machinelearning/pull/2753#discussion_r260562756) [](ancestors = 260562756)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: Yes sir.

---
In reply to: [260863640](https://github.com/dotnet/machinelearning/pull/2753#discussion_r260863640) [](ancestors = 260863640)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 4 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: 0.1%.

---
In reply to: [260563129](https://github.com/dotnet/machinelearning/pull/2753#discussion_r260563129) [](ancestors = 260563129)

**Comment by wschin** [comment]
>         public RegressionTreeEnsemble TrainedTreeEnsemble { get; }

Separated I'd suggest. This PR is too large, I feel.

---
In reply to: [468095313](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468095313) [](ancestors = 468095313)

---
Refers to: src/Microsoft.ML.FastTree/FastTree.cs:3393 in d8957fd. [](commit_id = d8957fde4dbd68b5c80232d1706162a9741db82c, deletion_comment = False)

**Comment by wschin** [comment]
>         public bool PrintTrainValidGraph;

I will do internal-best-friend.

---
In reply to: [467689803](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-467689803) [](ancestors = 467689803)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:410 in d64a4ae. [](commit_id = d64a4aed005c8861947bab650bfc18df079b7570, deletion_comment = False)

**Comment by wschin** [comment]
Sure.

---
In reply to: [467958748](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-467958748) [](ancestors = 467958748)

**Comment by wschin** [comment]
>         /// Print execution time breakdown to stdout.

We use `ch` defined in
```csharp
           using (var ch = Host.Start("Training"))
            {
                ch.CheckValue(trainData, nameof(trainData));
                trainData.CheckBinaryLabel();
                trainData.CheckFeatureFloatVector();
                trainData.CheckOptFloatWeight();
                FeatureCount = trainData.Schema.Feature.Value.Type.GetValueCount();
                ConvertData(trainData);
                TrainCore(ch);
            }
```

---
In reply to: [467689294](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-467689294) [](ancestors = 467689294)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:301 in d64a4ae. [](commit_id = d64a4aed005c8861947bab650bfc18df079b7570, deletion_comment = False)

File: src/Microsoft.ML.Data/Prediction/Calibrator.cs [hunk 8]
```diff
@@ -14,7 +14,6 @@
 using Microsoft.ML.CommandLine;
 using Microsoft.ML.Data;
 using Microsoft.ML.EntryPoints;
-using Microsoft.ML.Internal.Internallearn;
```
Comment (singlis) [inline src/Microsoft.ML.Data/Prediction/Calibrator.cs]: Are you merged with master? I thought that InternalLearn was removed in a prior change.

**Comment by singlis** [comment]
>                 bestIteration = Ensemble.NumTrees;

Changing this to NumberOfTrees is probably out of scope for this PR right? 

---
Refers to: src/Microsoft.ML.FastTree/BoostingFastTree.cs:143 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

**Comment by wschin** [comment]
>                 bestIteration = Ensemble.NumTrees;

Let me double-check. Thanks!

---
In reply to: [468512482](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468512482) [](ancestors = 468512482)

---
Refers to: src/Microsoft.ML.FastTree/BoostingFastTree.cs:143 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

**Comment by singlis** [comment]
>             string featureColumn,

suggestion:
I know this constructor is not exposed publicly, but I renamed these parameters (featureColumn->featureColumnName, etc) in lightgbm so that they aligned with the parameters that are used in the catalog function. And technically they will align with the parameters in the Options class. 

---
Refers to: src/Microsoft.ML.FastTree/FastTree.cs:104 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTree.cs [hunk 9]
```diff
@@ -3230,6 +3231,9 @@ private void ToCSharp(InternalRegressionTree tree, TextWriter writer, int node,
             }
         }
 
+        /// <summary>
+        /// Copy the weights of all training features to <paramref name="weights"/>.
+        /// </summary>
```
Comment (singlis) [inline src/Microsoft.ML.FastTree/FastTree.cs]: ></ [](start = 12, length = 2)

Missing pararm for weights

File: src/Microsoft.ML.FastTree/FastTreeClassification.cs [hunk 10]
```diff
@@ -130,14 +129,14 @@ public sealed partial class FastTreeBinaryClassificationTrainer :
             string labelColumn = DefaultColumnNames.Label,
             string featureColumn = DefaultColumnNames.Features,
             string weightColumn = null,
-            int numLeaves = Defaults.NumLeaves,
-            int numTrees = Defaults.NumTrees,
-            int minDatapointsInLeaves = Defaults.MinDocumentsInLeaves,
-            double learningRate = Defaults.LearningRates)
+            int numLeaves = Defaults.NumberOfLeaves,
```
Comment (singlis) [inline src/Microsoft.ML.FastTree/FastTreeClassification.cs]: >numLeaves [](start = 16, length = 9)

same suggestion here to use the full names for the arguments.

**Comment by singlis** [comment]
>         internal BinaryClassificationGamTrainer(IHostEnvironment env, Options options)

Should this be renamed to GamBinaryClassificationTrainer? I know there is an issue that is tracking consistent naming with our algorithms, so probably not worth doing in this pr. 


---
Refers to: src/Microsoft.ML.FastTree/GamClassification.cs:52 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

**Comment by singlis** [comment]
>             /// wrong, this method will throw.

I dont think this comment is right - this doesnt look like it will throw.

---
Refers to: src/Microsoft.ML.FastTree/GamModelParameters.cs:865 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

File: src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs [hunk 11]
```diff
@@ -39,10 +39,10 @@ public static class TreeRegressionExtensions
         /// </example>
         public static Scalar<float> FastTree(this RegressionCatalog.RegressionTrainers catalog,
             Scalar<float> label, Vector<float> features, Scalar<float> weights = null,
-            int numLeaves = Defaults.NumLeaves,
-            int numTrees = Defaults.NumTrees,
-            int minDatapointsInLeaves = Defaults.MinDocumentsInLeaves,
-            double learningRate = Defaults.LearningRates,
+            int numLeaves = Defaults.NumberOfLeaves,
```
Comment (singlis) [inline src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs]: >numLeaves [](start = 16, length = 9)

Shouldnt these parameters also be fully named?

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 12]
```diff
@@ -221,26 +221,26 @@ public abstract class TreeOptions : TrainerInputBaseWithGroupId
...
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Maximum categorical split points to consider when splitting on a categorical feature.", ShortName = "maxcat,MaxCategoricalSplitPoints")]
+        public int MaximumCategoricalSplitPoints = 64;
 
         /// <summary>
-        /// Minimum categorical docs percentage in a bin to consider for a split.
+        /// Minimum categorical example percentage in a bin to consider for a split. Default is 0.1% of all training examples.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Minimum categorical docs percentage in a bin to consider for a split.", ShortName = "mdop")]
-        public double MinDocsPercentageForCategoricalSplit = 0.001;
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Minimum categorical docs percentage in a bin to consider for a split.", ShortName = "mdop,MinDocsPercentageForCategoricalSplit")]
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >docs [](start = 82, length = 4)

example

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 13]
```diff
@@ -221,26 +221,26 @@ public abstract class TreeOptions : TrainerInputBaseWithGroupId
...
+        public double MinimumExampleFractionForCategoricalSplit = 0.001;
 
         /// <summary>
-        /// Minimum categorical doc count in a bin to consider for a split.
+        /// Minimum categorical example count in a bin to consider for a split.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Minimum categorical doc count in a bin to consider for a split.", ShortName = "mdo")]
-        public int MinDocsForCategoricalSplit = 100;
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Minimum categorical doc count in a bin to consider for a split.", ShortName = "mdo,MinDocsForCategoricalSplit")]
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >doc [](start = 82, length = 3)

example

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 14]
```diff
@@ -221,26 +221,26 @@ public abstract class TreeOptions : TrainerInputBaseWithGroupId
...
+                                                             "there many categorical features.", ShortName = "mcg,MaxCategoricalGroupsPerNode")]
+        public int MaximumCategoricalGroupsPerNode = 64;
 
         /// <summary>
         /// Maximum categorical split points to consider when splitting on a categorical feature.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Maximum categorical split points to consider when splitting on a categorical feature.", ShortName = "maxcat")]
-        public int MaxCategoricalSplitPoints = 64;
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "Maximum categorical split points to consider when splitting on a categorical feature.", ShortName = "maxcat,MaxCategoricalSplitPoints")]
+        public int MaximumCategoricalSplitPoints = 64;
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >MaximumCategoricalSplitPoints [](start = 19, length = 29)

MaximumCategoricalGroupCountPerNode

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 15]
```diff
@@ -221,26 +221,26 @@ public abstract class TreeOptions : TrainerInputBaseWithGroupId
         /// </summary>
         [Argument(ArgumentType.LastOccurenceWins, HelpText = "Maximum categorical split groups to consider when splitting on a categorical feature. " +
                                                              "Split groups are a collection of split points. This is used to reduce overfitting when " +
-                                                             "there many categorical features.", ShortName = "mcg")]
-        public int MaxCategoricalGroupsPerNode = 64;
+                                                             "there many categorical features.", ShortName = "mcg,MaxCategoricalGroupsPerNode")]
+        public int MaximumCategoricalGroupsPerNode = 64;
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >MaximumCategoricalGroupsPerNode [](start = 19, length = 31)

MaximumCategoricalGroupCountPerNode

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 14 above)
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >MaximumCategoricalSplitPoints [](start = 19, length = 29)

MaximumCategoricalSplitPointCount

File: src/Microsoft.ML.FastTree/FastTree.cs (hunk 9 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTree.cs]: Thanks. I will add
```csharp
        /// <param name="weights">a <see cref="VBuffer{T}"/> where feature weights would be assigned to.
        /// The i-th element in <paramref name="weights"/> stores the weight of the i-th feature.</param>
```

---
In reply to: [261459910](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261459910) [](ancestors = 261459910)

File: src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs (hunk 11 above)
Comment (wschin) [reply src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs]: Thanks! I didn't realize they are FastTree static APIs.

---
In reply to: [261464899](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261464899) [](ancestors = 261464899)

File: src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs [hunk 16]
```diff
@@ -39,10 +39,10 @@ public static class TreeRegressionExtensions
...
+            int numTrees = Defaults.NumberOfTrees,
+            int minDatapointsInLeaves = Defaults.MinimumExampleCountPerLeaf,
```
Comment (wschin) [inline src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs]: >minDatapointsInLeaves [](start = 16, length = 21)

minimumExampleCountPerLeaf

File: src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs [hunk 17]
```diff
@@ -39,10 +39,10 @@ public static class TreeRegressionExtensions
         /// </example>
         public static Scalar<float> FastTree(this RegressionCatalog.RegressionTrainers catalog,
             Scalar<float> label, Vector<float> features, Scalar<float> weights = null,
-            int numLeaves = Defaults.NumLeaves,
-            int numTrees = Defaults.NumTrees,
-            int minDatapointsInLeaves = Defaults.MinDocumentsInLeaves,
-            double learningRate = Defaults.LearningRates,
+            int numLeaves = Defaults.NumberOfLeaves,
+            int numTrees = Defaults.NumberOfTrees,
```
Comment (wschin) [inline src/Microsoft.ML.StaticPipe/TreeTrainersStatic.cs]: >numTrees [](start = 16, length = 8)

numberOfTrees

**Comment by wschin** [comment]
>                 bestIteration = Ensemble.NumTrees;

They are internal data structures, so I don't want to touch them. But still thanks a lot for giving me a heads up because I did forget to update their corresponding public fields.

---
In reply to: [468512646](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468512646) [](ancestors = 468512646,468512482)

---
Refers to: src/Microsoft.ML.FastTree/BoostingFastTree.cs:143 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

**Comment by wschin** [comment]
>             /// wrong, this method will throw.

New comment:  `Attempts to initialize required items, from the input model file. It could throw if something goes wrong.`


---
In reply to: [468521412](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468521412) [](ancestors = 468521412)

---
Refers to: src/Microsoft.ML.FastTree/GamModelParameters.cs:865 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

**Comment by wschin** [comment]
>         internal BinaryClassificationGamTrainer(IHostEnvironment env, Options options)

It's an internal object.

---
In reply to: [468520295](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468520295) [](ancestors = 468520295)

---
Refers to: src/Microsoft.ML.FastTree/GamClassification.cs:52 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

File: docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs (hunk 1 above)
Comment (TomFinley) [reply docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs]: I think the trees should enable someone to explain what the tree is. I wouldn't make evaluation code part of the API.

---
In reply to: [261417026](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261417026) [](ancestors = 261417026,261011054,260562343)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 18]
```diff
@@ -174,16 +174,16 @@ public abstract class TreeOptions : TrainerInputBaseWithGroupId
...
-        public int RngSeed = 123;
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the random number generator", ShortName = "r1,RngSeed")]
+        public int Seed = 123;
 
         // this random seed is only for active feature selection
         /// <summary>
         /// The seed of the active feature selection.
         /// </summary>
-        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the active feature selection", ShortName = "r3", Hide = true)]
+        [Argument(ArgumentType.LastOccurenceWins, HelpText = "The seed of the active feature selection", ShortName = "r3,FeatureSelectSeed", Hide = true)]
```
Comment (TomFinley) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >FeatureSelectSeed [](start = 121, length = 17)

I notice that we're doing this -- is the intent to maintain back-compat with existing entry-points? If it is so, I *might* prefer to do `Name` attribute, so we suppress the new name. And if we don't *care* about back compat, then I think we can just say, "you know what, this is the new name now." I'd rather just do the "hard break" now and drop these existing things. Do we have a solid scenario that requires this back-compat on the arguments themselves?

Comment (TomFinley) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: So my preference would be, let's not do this.

---
In reply to: [261735355](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261735355) [](ancestors = 261735355)

**Comment by TomFinley** [comment]
>         public int FeatureCompressionLevel = 1;

`internal` please

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:380 in fb377c1. [](commit_id = fb377c1df15e2b8accc6310682a327dbb1095fd2, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 18 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: Is this comment applied to every other argument in other trainers?

---
In reply to: [261735502](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261735502) [](ancestors = 261735502,261735355)

File: docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs (hunk 1 above)
Comment (wschin) [reply docs/samples/Microsoft.ML.Samples/Dynamic/FastTreeRegression.cs]: Sounds good. I feel evaluation module should be independent to the expression of the trained objects. Thanks you!

---
In reply to: [261734289](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261734289) [](ancestors = 261734289,261417026,261011054,260562343)

**Comment by wschin** [comment]
>         public int FeatureCompressionLevel = 1;

Sure.

---
In reply to: [468789354](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468789354) [](ancestors = 468789354)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:380 in fb377c1. [](commit_id = fb377c1df15e2b8accc6310682a327dbb1095fd2, deletion_comment = False)

File: src/Microsoft.ML.Data/Prediction/Calibrator.cs (hunk 8 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Prediction/Calibrator.cs]: Yep, maybe rebase did something.

---
In reply to: [261456781](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261456781) [](ancestors = 261456781)

**Comment by wschin** [comment]
>             string featureColumn,

Fixed. Thanks.

---
In reply to: [468513567](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468513567) [](ancestors = 468513567)

---
Refers to: src/Microsoft.ML.FastTree/FastTree.cs:104 in 3257470. [](commit_id = 32574707983baa03782ba4a18e7c9b4ff8140cd6, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeClassification.cs (hunk 10 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeClassification.cs]: Sure.

---
In reply to: [261461521](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261461521) [](ancestors = 261461521)

**Comment by Ivanidzo4ka** [comment]
>             public string CustomGains = "0,3,7,15,31";

can we pass array of gains as array and not as comma separated string?

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:78 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>             // REVIEW: Hiding sorting for now. Should be an enum or component factory.

this is a good comment!

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:83 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>             public bool DistanceWeight2;

CoolName3

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:105 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 19]
```diff
@@ -392,22 +393,24 @@ public abstract class TreeOptions : TrainerInputBaseWithGroupId
         // REVIEW: Not used.
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >/ REVIEW: Not used. [](start = 9, length = 19)

Is it true?

**Comment by Ivanidzo4ka** [comment]
>             public int LambdaMartMaxTruncation = 100;

do we want to expose any of this parameter with hide=true?

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:93 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

File: src/Microsoft.ML.FastTree/RegressionTree.cs [hunk 20]
```diff
@@ -63,14 +63,14 @@ public abstract class RegressionTreeBase
         /// bitwise complement operator in C#; for details, see
         /// https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-complement-operator.
         /// </summary>
-        public IReadOnlyList<int> LteChild => _lteChild;
+        public IReadOnlyList<int> LessThanOrEqualToThresholdChildren => _lteChild;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/RegressionTree.cs]: >LessThanOrEqualToThresholdChildren [](start = 34, length = 34)

It looks like across lightgbm, catboost and whatever they use in scikit this one called: leftChildrends, or leftChild, another one is rightChild.

**Comment by wschin** [comment]
>             public int LambdaMartMaxTruncation = 100;

I think so. Can we remove "k" in top-k accuracy? No, we can't.

---
In reply to: [468890315](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468890315) [](ancestors = 468890315)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:93 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 19 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: True. Will remove it.

---
In reply to: [261814752](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261814752) [](ancestors = 261814752)

File: src/Microsoft.ML.FastTree/RegressionTree.cs (hunk 20 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/RegressionTree.cs]: Will do leftChild for this.

---
In reply to: [261814959](https://github.com/dotnet/machinelearning/pull/2753#discussion_r261814959) [](ancestors = 261814959)

**Comment by wschin** [comment]
>             // REVIEW: Hiding sorting for now. Should be an enum or component factory.

Will make it internal.

---
In reply to: [468890113](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468890113) [](ancestors = 468890113)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:83 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

**Comment by wschin** [comment]
>             public bool DistanceWeight2;

As suggested by @tfinley@gmail.com, this will be internal.

---
In reply to: [468890167](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468890167) [](ancestors = 468890167)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:105 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

**Comment by wschin** [comment]
>             public string CustomGains = "0,3,7,15,31";

Will be included in the next iteration. (iter 9)

---
In reply to: [468890070](https://github.com/dotnet/machinelearning/pull/2753#issuecomment-468890070) [](ancestors = 468890070)

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:78 in ee67d50. [](commit_id = ee67d505869e784921e2a0c1bc89d1bf3d6e5a09, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 21]
```diff
@@ -129,12 +273,12 @@ internal override void Check(IExceptionContext ectx)
 #if OLD_DATALOAD
                 ectx.CheckUserArg(0 <= secondaryMetricShare && secondaryMetricShare <= 1, "secondaryMetricShare", "secondaryMetricShare must be between 0 and 1.");
 #endif
-                ectx.CheckUserArg(0 < LambdaMartMaxTruncation, nameof(LambdaMartMaxTruncation), "lambdaMartMaxTruncation must be positive.");
+                ectx.CheckUserArg(0 < NdcgTruncationLevel, nameof(NdcgTruncationLevel), "lambdaMartMaxTruncation must be positive.");
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >lambdaMartMaxTruncation [](start = 89, length = 23)

no need for this one. you already use nameof

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs [hunk 22]
```diff
@@ -20,19 +20,81 @@ internal interface IFastTreeTrainerFactory : IComponentFactory<ITrainer>
...
+            /// </summary>
+            // Disable 649 because Visual Studio can't detect its assignment via property.
+            #pragma warning disable 649
+            private EarlyStoppingMetric _earlyStoppingMetric;
+            #pragma warning restore 649
+
+            /// <summary>
+            /// Early stopping metrics.
+            /// </summary>
+            public EarlyStoppingMetric EarlyStoppingMetric
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.FastTree/FastTreeArguments.cs]: >EarlyStoppingMetric [](start = 19, length = 19)

From comments for previous option it looks like it should be applicable only for regression and ranking problem. Does it actually works for binary classification?

**Comment by Ivanidzo4ka** [comment]
>         public int EarlyStoppingMetrics;

internal. otherwise i would see two places in which I can set this up. this one and `EarlyStoppingMetric`

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:633 in 157aedc. [](commit_id = 157aedc38d17258668dbd06c65f2e07104583702, deletion_comment = False)

File: src/Microsoft.ML.FastTree/FastTreeArguments.cs (hunk 22 above)
Comment (wschin) [reply src/Microsoft.ML.FastTree/FastTreeArguments.cs]: I don't exactly know but conceptually yes. It can be used to measure gradient norm.

---
In reply to: [262295829](https://github.com/dotnet/machinelearning/pull/2753#discussion_r262295829) [](ancestors = 262295829)

**Comment by Ivanidzo4ka** [comment]
>         public string BaselineScoresFormula;

make this one internal and next two below it.
In order to work with FreeForms we need to ship "NeuralTreeEvaluator.dll" which we can't expose.

---
Refers to: src/Microsoft.ML.FastTree/FastTreeArguments.cs:737 in 157aedc. [](commit_id = 157aedc38d17258668dbd06c65f2e07104583702, deletion_comment = False)

File: test/BaselineOutput/Common/EntryPoints/core_manifest.json [hunk 23]
```diff
@@ -9096,18 +9057,6 @@
           "IsNullable": false,
           "Default": false
         },
-        {
-          "Name": "MaxTreesAfterCompression",
-          "Type": "Int",
```
Comment (ganik) [inline test/BaselineOutput/Common/EntryPoints/core_manifest.json]: why this got deleted?

Comment (wschin) [reply test/BaselineOutput/Common/EntryPoints/core_manifest.json]: Not used at all.

---
In reply to: [262674075](https://github.com/dotnet/machinelearning/pull/2753#discussion_r262674075) [](ancestors = 262674075)
