### PR TITLE
More trainer extensions, bug fixes and consistency across trainer extensions

### LINKED ISSUE #1521: Need to make consistent the parameters across the API
**Issue: Similar classes/estimators methods have different parameters' order for the same concepts.** 

It looks like a "silly" error, but not straightforward to catch because the column's name provided as parameters are not typed (just strings, logically, since column names could vary) you get an error in execution time but in addition to that because the pipeline works as lazy loading, you find the error later on when fitting the model, so you initially don't know what API is incorrectly configured making it hard to find these kind of "silly" errors which are prone to happen because of different parameter's order in similar APIs (such as Estimators and Transformers). 

For instance, when migrating to the estimator by using mlContext, the following "silly" case happened to me:

```
// This line works
var trainer = new SdcaMultiClassTrainer(mlContext, "Features", "Label");
// This line doesn't work, but you'll find out later on when Fitting the model
var trainer = mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent("Features", "Label");
```

Error you get when fitting:
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  **Message=Training label column 'Features' type is not valid for multi-class: Vec<R4, 69981>. Type must be R4 or R8.**
  Source=Microsoft.ML.Data
```

```
//This line DOES work when changing to the right order of parameters accepted by the new API:
var trainer = mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscent("Label", "Features");
```
But you can see that is not consistent in order with this very similar line, the same trainer:
```
// This line works
var trainer = new SdcaMultiClassTrainer(mlContext, "Features", "Label");
```

I initially thought that the trainer in the mlcontext catalog was not working for any reason as a very similar API was working by directly creating the class.. But it was simply because the order is vice-versa in the case of the new trainer surfaced on the mlContext. ;)

**Improvement**

1. Obvious and already "work in progress": It will help if we are consistent in the order of the parameters across all the APIs. "Label" first, "Features" later, or vice-versa, but consistent.

2. Not sure if somehow we could use strongly-typed types for the column names or some kind of check/control.. like if for the column names we were able to use the fields in the schema classes and the "Label" field was "marked" as "Label" with an attribute, that could also help, I mean something like the following:

```
var trainer = mlContext.MulticlassClassification.Trainers.StochasticDualCoordinateAscentnameof(
                                                        nameof(MyObservation.MyLabel), 
                                                        "Features");
```

Then, the Label field is "marked" as Label:
```
    public class MyObservation
    {
        [Column(ordinal: "0")]
        public string ID;

        [Label]
        [Column(ordinal: "1")]
        public string MyLabel; // This is an issue label, for example "area-System.Threading"

        [Column(ordinal: "2")]
        public string Title;

        [Column(ordinal: "3")]
        public string Description;
    }
```

Not sure though..., this last approach might be too contrived and not realistic because in almost all the cases the Label is also a generated/Dictionarized field, as well as the "Features" column, both created/generated as new columns out of the original observation schema class, so this last attempt might not be feasible...

Any other possible check/control so errors when using strings for the column names could be less prone to happen?...

### PR DESCRIPTION
**Pull request by sfilipi**
Gam trainers placed in the right context, and removing arguments they weren't using from their signatures. 
Fixes #1521 making the order of the parameters consistent. 
Addresses part of #1318 by adding the FastForest extensions.

### CODE REVIEW

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs [hunk 1]
```diff
@@ -27,8 +27,8 @@ public static class TreeExtensions
         /// <param name="learningRate">The learning rate.</param>
         /// <param name="advancedSettings">Algorithm advanced settings.</param>
         public static FastTreeRegressionTrainer FastTree(this RegressionContext.RegressionTrainers ctx,
-            string label = DefaultColumnNames.Label,
-            string features = DefaultColumnNames.Features,
+            string label,
```
Comment (artidoro) [inline src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: I have seen in other files that features comes before label. We should pick one order and stick to it, otherwise it is very confusing. I would suggest features, label, optional weight. But either ways could work!

File: src/Microsoft.ML.LightGBM/LightGbmCatalog.cs [hunk 2]
```diff
@@ -30,8 +30,8 @@ public static class LightGbmExtensions
         /// if both are present and have different values.
         /// The columns names, however need to be provided directly, not through the <paramref name="advancedSettings"/>.</param>
         public static LightGbmRegressorTrainer LightGbm(this RegressionContext.RegressionTrainers ctx,
-            string label = DefaultColumnNames.Label,
-            string features = DefaultColumnNames.Features,
+            string label,
```
Comment (artidoro) [inline src/Microsoft.ML.LightGBM/LightGbmCatalog.cs]: >label, [](start = 19, length = 6)

Same comment regarding the order of this.

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs (hunk 1 above)
Comment (artidoro) [reply src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: Actually I think you already made the decision, label, features, optional weight, which is consistent with all other files in this PR. Maybe we should consider opening an issue and updating the order these in another PR?

---
In reply to: [230870480](https://github.com/dotnet/machinelearning/pull/1524#discussion_r230870480) [](ancestors = 230870480)

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs [hunk 3]
```diff
@@ -94,35 +94,39 @@ public class Arguments : UnsupervisedLearnerInputBaseWithWeight
         /// <summary>
         /// Initializes a new instance of <see cref="KMeansPlusPlusTrainer"/>
         /// </summary>
-        /// <param name="env">The private instance of <see cref="IHostEnvironment"/>.</param>
+        /// <param name="env">The local instance of <see cref="IHostEnvironment"/>.</param>
```
Comment (artidoro) [inline src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: >The local instance of <see cref="IHostEnvironment"/> [](start = 30, length = 52)

Maybe update to: The environment to use.
So that it easier to understand.

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs [hunk 4]
```diff
@@ -94,35 +94,39 @@ public class Arguments : UnsupervisedLearnerInputBaseWithWeight
...
 
-        private KMeansPlusPlusTrainer(IHostEnvironment env, Arguments args, string featureColumn, string weightColumn, Action<Arguments> advancedSettings = null)
-            : base(Contracts.CheckRef(env, nameof(env)).Register(LoadNameValue), TrainerUtils.MakeR4VecFeature(featureColumn), null, TrainerUtils.MakeR4ScalarWeightColumn(weightColumn))
+        private KMeansPlusPlusTrainer(IHostEnvironment env, Arguments args, Action<Arguments> advancedSettings = null)
+            : base(Contracts.CheckRef(env, nameof(env)).Register(LoadNameValue), TrainerUtils.MakeR4VecFeature(args.FeatureColumn), null, TrainerUtils.MakeR4ScalarWeightColumn(args.WeightColumn))
         {
             Host.CheckValue(args, nameof(args));
 
+            // override with the advanced settings.
             if (advancedSettings != null)
```
Comment (Zruty0) [inline src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: >if [](start = 12, length = 2)

`advancedSettings?.Invoke(args)`

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs [hunk 5]
```diff
@@ -125,23 +121,19 @@ public static class TreeExtensions
...
+        /// Predict a target using a decision tree binary classification model trained with the <see cref="RegressionGamTrainer"/>.
         /// </summary>
-        /// <param name="ctx">The <see cref="BinaryClassificationContext"/>.</param>
+        /// <param name="ctx">The <see cref="RegressionContext"/>.</param>
         /// <param name="label">The label column.</param>
         /// <param name="features">The features column.</param>
         /// <param name="weights">The optional weights column.</param>
-        /// <param name="numTrees">Total number of decision trees to create in the ensemble.</param>
-        /// <param name="numLeaves">The maximum number of leaves per decision tree.</param>
         /// <param name="minDatapointsInLeafs">The minimal number of datapoints allowed in a leaf of the tree, out of the subsampled data.</param>
```
Comment (Zruty0) [inline src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: >minDatapointsInLeafs [](start = 25, length = 20)

I sense inconsistent naming

File: src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs [hunk 6]
```diff
@@ -59,7 +59,7 @@ public Arguments()
                 BasePredictors = new[]
                 {
                     ComponentFactoryUtils.CreateFromFunction(
-                        env => new MulticlassLogisticRegression(env, FeatureColumn, LabelColumn))
+                        env => new MulticlassLogisticRegression(env, LabelColumn,FeatureColumn))
```
Comment (Zruty0) [inline src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs]: >,F [](start = 80, length = 2)

spacing

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 7]
```diff
@@ -83,7 +83,9 @@ public sealed class Arguments : ArgumentsBase
         /// <param name="memorySize">Memory size for <see cref="LogisticRegression"/>. Lower=faster, less accurate.</param>
         /// <param name="optimizationTolerance">Threshold for optimizer convergence.</param>
         /// <param name="advancedSettings">A delegate to apply all the advanced arguments to the algorithm.</param>
-        public MulticlassLogisticRegression(IHostEnvironment env, string featureColumn, string labelColumn,
+        public MulticlassLogisticRegression(IHostEnvironment env,
+            string labelColumn,
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >labelColumn [](start = 19, length = 11)

it used to be `label` and `features` in other trainers, right?

File: src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs [hunk 8]
```diff
@@ -31,7 +31,9 @@ public static class SdcaRegressionExtensions
         /// if both are present and have different values.
         /// The columns names, however need to be provided directly, not through the <paramref name="advancedSettings"/>.</param>
         public static SdcaRegressionTrainer StochasticDualCoordinateAscent(this RegressionContext.RegressionTrainers ctx,
-        string label = DefaultColumnNames.Label, string features = DefaultColumnNames.Features, string weights = null,
```
Comment (Zruty0) [inline src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: > = DefaultColumnNames.Label [](start = 20, length = 27)

why do we remove the defaults?

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs (hunk 5 above)
Comment (sfilipi) [reply src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: enlighten me? 

---
In reply to: [231226770](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231226770) [](ancestors = 231226770)

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs (hunk 3 above)
Comment (sfilipi) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: I think we are using this comment most everywhere. 

---
In reply to: [230873736](https://github.com/dotnet/machinelearning/pull/1524#discussion_r230873736) [](ancestors = 230873736)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs (hunk 8 above)
Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: we talked about them being error prone, better ask the user to define them explicitly. 

---
In reply to: [231231911](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231231911) [](ancestors = 231231911)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 7 above)
Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Thanks for this. 

---
In reply to: [231231728](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231231728) [](ancestors = 231231728)

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs (hunk 5 above)
Comment (Zruty0) [reply src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: MinDocsPerLeaf, MinDocumentsPerLeaf, MinDatapointsInLeafs

Also 'leaves', not 'leafs'

---
In reply to: [231232309](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231232309) [](ancestors = 231232309,231226770)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs (hunk 8 above)
Comment (Zruty0) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: @TomFinley do you have a preference? I would prefer to keep the defaults. Otherwise, why do we even have `DefaultColumnNames` in the API?

---
In reply to: [231234097](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231234097) [](ancestors = 231234097,231231911)

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs (hunk 3 above)
Comment (Zruty0) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: Actually, I don't think so. 'The local instance of IHostEnvironment' is a really bad comment for a public method.

---
In reply to: [231233831](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231233831) [](ancestors = 231233831,230873736)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 7 above)
Comment (Zruty0) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: but should we have it consistent?

---
In reply to: [231244854](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231244854) [](ancestors = 231244854,231231728)

Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: for sure. I changed them to be "label, features, weights". I personally lean more towards "labelColum, featureColumn and weightColumn" 

---
In reply to: [231367774](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231367774) [](ancestors = 231367774,231244854,231231728)

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs (hunk 3 above)
Comment (sfilipi) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: what would you suggest we use @Zruty0?

---
In reply to: [231367726](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231367726) [](ancestors = 231367726,231233831,230873736)

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs (hunk 5 above)
Comment (sfilipi) [reply src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: oh lol. Apparently it's been like this for a long time. 

---
In reply to: [231367379](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231367379) [](ancestors = 231367379,231232309,231226770)

File: src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs (hunk 8 above)
Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: I think the default arguments make sense for the case when the user doesn't supply anything, the pipeline just works. This is not the case for the column names; if they are not "Label" and "Features" in the datasets the pipelines fail, sometimes with esoteric messages. 

I fully endorse the default for the numeric values: they guide the user about ranges, and they just work most of the time. 
I am also ok with Default column names for the columns components produce and hard-code like "Score" "PredictedLabel"; but IMO hardcode the inputs is misleading and will hide errors like the ones we have fixed so far (not passing the column names at all, and things still work because our test datasets and the default col names match). 

---
In reply to: [231367619](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231367619) [](ancestors = 231367619,231234097,231231911)

File: src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs (hunk 3 above)
Comment (Zruty0) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: What Artidoro said.

---
In reply to: [231386902](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231386902) [](ancestors = 231386902,231367726,231233831,230873736)

Comment (sfilipi) [reply src/Microsoft.ML.KMeansClustering/KMeansPlusPlusTrainer.cs]: that doesn't sound more more helpful to me than the current one.. but 2 to 1. 

---
In reply to: [231618928](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231618928) [](ancestors = 231618928,231386902,231367726,231233831,230873736)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 7 above)
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: I also find labelColumn, featureColumn, weightColumn more appealing. I find them more representative of what the arguments specify (the name of these columns).

Comment (shauheen) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: FWIW, labelColumn, featureColumn, weightColumn sound better to me.

File: src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs (hunk 8 above)
Comment (TomFinley) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: I think generally it is a good policy to be cautious w.r.t. expanding defaults, as @sfilipi suggests. Being too aggressive with your defaults can lead to more confusion, not less.

> I think the default arguments make sense for the case when the user doesn't supply anything, the pipeline just works. This is not the case for the column names;

I would argue that it is the case for column names more often than we might think. The text loader when no settings are defined has the default behavior, which has proven to be valuable, that it considers the first field a scalar `Label` and subsequent fields a vector `Features`.

Further, while our text parser is built so that it can accommodate a diverse set of inputs (if properly configured), we should not loose sight of the fact that *generally* file formats for machine learning are far more restrictive than this. Consider formats like [SVM-light](http://svmlight.joachims.org/), the more esoteric Bing formats, (we have loaders for the previous that we haven't yet had the chance to open source) or the [VW format](http://hunch.net/~vw/). In these formats, "label" and "features" are priviledged concepts, and where we've written loaders for them, we name these things the columns `Label` and `Features`. Or the "wizard" case, where we apply heusitics to figure out how to load data, what else will the result be named but `Label` and `Features`?

Now consider two populations of people, under two conditions.

Condition A, with defaults!

1. Someone uses SVM-light loader, or the Bing BIN loader, or the text loader under default settings. (Or, in future, a hypothetical VW loader.) These will provide two columns `Label` and `Features`. With defaults, they call `Read()` then `Fit()`. Things work.

2. Now, you are talking about someone that overrides the default behavior of `TextLoader` (again, that default behavior ) and provides explicit names for their columns. They call `Fit` on this trainer. Things *fail* with the message that it could not find a label or feature column named `Label` or `Features`.

Condition B, without defaults!

1. Same actions, but nwo things fail. They need to provide these column names, but how could they reasonably know what the column names are? Indeed, someone just coming to ML.NET for the first time and just fires up a session with SVM-light loader for the first time, how could we expect them to even know what a column *is*?

2. Same action, things *still* fail.

It is far from clear to me that A2 is significantly more confusing than B2 -- in order to hit B2 we need a user that is both (1) smart enough to figure out how to come up with names for columns but (2) not smart enough to figure out that things downstream might want those names. Even if such a person exists, the situation of A2 is recoverable.

We must, I think, all agree that B1 is borderline disastrously confusing. And A1 both work.

*Some* people have really confusing pipelines with multiple featurizers, custom data, and all this stuff. But some people just have data, already nicely structured, and just want to read and train. IDataView and Columns are sort of one of those concepts you need to know if you're doing complex featurization, but if you don't, you don't really need to know it, and I'd like to keep it that way if we can.

Therefore, my own sense is that @Zruty0 is correct, and we ought to have defaults.

---
In reply to: [231388508](https://github.com/dotnet/machinelearning/pull/1524#discussion_r231388508) [](ancestors = 231388508,231367619,231234097,231231911)

Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: Thanks for taking a side, @TomFinley, appreciate the level of detail. My observation is that overriding the behavior of the TextLoader is actually the norm, and unless your immediate component is a trainerEstimator, you need the names of the columns to transform them further. 


Examples of ML.Net issues with non-standard TextLoader:
https://github.com/dotnet/machinelearning/issues/420
https://stackoverflow.com/questions/52689363/adding-data-from-new-textloader-into-exisitng-pipeline-ver-0-6 
https://elbruno.com/2018/06/19/mlnet-loading-data-in-our-learningpipeline-with-list-lists-for-ever/
https://carlos.mendible.com/2018/06/10/simple-machine-learning-with-dotnet-core-sample/

Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/SdcaCatalog.cs]: I wrote more about my experience with the default column names in #1360.
