### PR TITLE
Restore OVA ability to preserve key names on predicted label

### LINKED ISSUE #3090: Exception when converting PredictedLabel from Key To Value
When trying to convert the output PredictedLabel from key back to value, the exception
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Metadata KeyValues does not exist
  Source=Microsoft.ML.Core
  StackTrace:
   at Microsoft.ML.Runtime.Contracts.Check(IExceptionContext ctx, Boolean f, String msg) in C:\MLDotNet2\src\Microsoft.ML.Core\Utilities\Contracts.cs:line 497
```
is thrown.

Code to repro:
```C#
var mlContext = new MLContext();

var textLoaderOptions = new TextLoader.Options()
{
	Columns = new[]
	{
		new TextLoader.Column("Label", DataKind.Single, 0),
		new TextLoader.Column("Row", DataKind.Single, 1),
		new TextLoader.Column("Column", DataKind.Single, 2),
	},
	HasHeader = true,
	Separators = new[] { '\t' }
};
var textLoader = mlContext.Data.CreateTextLoader(textLoaderOptions);
var data = textLoader.Load(@"C:\MLDotNet2\test\data\trivial-train.tsv");

var ap = mlContext.BinaryClassification.Trainers.AveragedPerceptron();
var ova = mlContext.MulticlassClassification.Trainers.OneVersusAll(ap);

var pipeline = mlContext.Transforms.Conversion.MapValueToKey("Label")
	.Append(mlContext.Transforms.Concatenate("Features", "Row", "Column"))
	.Append(ova)
	.Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

var model = pipeline.Fit(data);
```

Replace `C:\MLDotNet2\` with path to ML.NET repo on your local machine

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes #3090.
I found usage of slot names _slightly_ confusing. In same time we have `TrainingLabelValues` which should do the trick.

### CODE REVIEW

File: src/Microsoft.ML.Data/Scorers/MulticlassClassificationScorer.cs [hunk 1]
```diff
@@ -450,7 +450,7 @@ internal static ISchemaBoundMapper WrapCore<T>(IHostEnvironment env, ISchemaBoun
                     trainSchema.Label.Value.GetKeyValues(ref value);
                 };
 
-            return LabelNameBindableMapper.CreateBound<T>(env, (ISchemaBoundRowMapper)mapper, type as VectorDataViewType, getter, AnnotationUtils.Kinds.SlotNames, CanWrap);
+            return LabelNameBindableMapper.CreateBound<T>(env, (ISchemaBoundRowMapper)mapper, type as VectorDataViewType, getter, AnnotationUtils.Kinds.TrainingLabelValues, CanWrap);
```
Comment (TomFinley) [inline src/Microsoft.ML.Data/Scorers/MulticlassClassificationScorer.cs]: >AnnotationUtils.Kinds.TrainingLabelValues [](start = 130, length = 41)

Hi @Ivanidzo4ka, could you explain this to me a bit more? It looks like we are no longer publishing these as slot names. Is that correct, or do I misread?

More broadly: I understand from the issue that there has been some regression from 0.11, but I am not certain I understand the nature of the regression completely (how did it regress, by which change?). That lack of knowledge makes this code difficult to review for me, even though the change itself is not too large.

File: test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs [hunk 2]
```diff
@@ -37,22 +37,22 @@ void PredictAndMetadata()
...
             // During prediction we will get Score column with 3 float values.
             // We need to find way to map each score to original label.
-            // In order to do what we need to get SlotNames from Score column.
-            // Slot names on top of Score column represent original labels for i-th value in Score array.
-            VBuffer<ReadOnlyMemory<char>> slotNames = default;
-            engine.OutputSchema[nameof(IrisPrediction.Score)].GetSlotNames(ref slotNames);
+            // In order to do what we need to get TrainingLabelValues from Score column.
+            // TrainingLabelValues on top of Score column represent original labels for i-th value in Score array.
+            VBuffer<ReadOnlyMemory<char>> originalLabels = default;
+            engine.OutputSchema[nameof(IrisPrediction.Score)].Annotations.GetValue(AnnotationUtils.Kinds.TrainingLabelValues, ref originalLabels);
```
Comment (TomFinley) [inline test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: >TrainingLabelValues [](start = 105, length = 19)

Is the distinction with slot names that slots names *must* be text, while these might be any type?

File: test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs [hunk 3]
```diff
@@ -37,22 +37,22 @@ void PredictAndMetadata()
...
             // Since we apply MapValueToKey estimator with default parameters, key values
             // depends on order of occurence in data file. Which is "Iris-setosa", "Iris-versicolor", "Iris-virginica"
             // So if we have Score column equal to [0.2, 0.3, 0.5] that's mean what score for
             // Iris-setosa is 0.2
             // Iris-versicolor is 0.3
             // Iris-virginica is 0.5.
-            Assert.True(slotNames.GetItemOrDefault(0).ToString() == "Iris-setosa");
-            Assert.True(slotNames.GetItemOrDefault(1).ToString() == "Iris-versicolor");
-            Assert.True(slotNames.GetItemOrDefault(2).ToString() == "Iris-virginica");
+            Assert.True(originalLabels.GetItemOrDefault(0).ToString() == "Iris-setosa");
```
Comment (TomFinley) [inline test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: >Assert.True [](start = 12, length = 11)

XUnit has something called `Assert.Equal`. The benefit to using something like that is, *if* the test fails, you get a more descriptive message than merely knowing that a boolean test failed somewhere.

Something to think about when writing tests.

File: src/Microsoft.ML.Data/Scorers/MulticlassClassificationScorer.cs (hunk 1 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Data/Scorers/MulticlassClassificationScorer.cs]: I ask you some time ago regarding nature of SlotNames, and what they are always should be Text instances. So I made change in `CanWrap` method which validates what KeyValues are actually TextInstances.
Which bring this bug.
I don't want to continue to use `SlotNames`, since they are limited by type. In same time `TrainingLabelValues` don't look like they have any restriction on data type of it content, so I just want to use it.

File: test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs (hunk 2 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: No we don't, but I can change that. Any reason while we want continue to propagate slotnames?

Comment (TomFinley) [reply test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: Well, let's imagine I write out a text file, and I have this scores column. With slot names, I get a descriptive header. Without it I don't. Does that make sense?

Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: Only if original labels were string, but ok.
Just before I make crucial mistake.
Do you prefer to have two wrappers on top of multiclass scorer one for `TrainingLabelValues` one for `SlotNames` or you would prefer to extend `LabelNameBindableMapper` to support multiple getters/ metakinds?

File: test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs [hunk 4]
```diff
@@ -51,6 +51,36 @@ public void OVAUncalibrated()
             Done();
         }
 
+        /// <summary>
+        /// Test what OVA preserves key values for label.
+        /// </summary>
+        [Fact]
+        public void OvaKeyNames()
```
Comment (TomFinley) [inline test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs]: >OvaKeyNames [](start = 20, length = 11)

Just curious, I heard something fairly troubling from @eerhardt, could we test this sort of scenario still works for things other than OVA?

**Comment by eerhardt** [comment]
@Ivanidzo4ka - this issue doesn't appear to be OVA specific. I'm also hitting it in upgrading [XamlBrewer.Uwp.MachineLearningSample](https://github.com/XamlBrewer/UWP-MachineLearning-Sample/blob/150b11ed4941451e0aa48c7f71500069efa2c2fb/XamlBrewer.Uwp.MachineLearningSample/Models/MulticlassClassification/MulticlassClassificationModel.cs#L19-L30) to the latest build.

File: test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs (hunk 4 above)
Comment (eerhardt) [inline test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs]: Can we add this to `FunctionalTests` instead? Let's not keep adding tests that the product allows InternalsVisibleTo. That way we can test like a customer uses the product.

File: test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs [hunk 5]
```diff
@@ -51,6 +51,36 @@ public void OVAUncalibrated()
...
+
+            var ap = ML.BinaryClassification.Trainers.AveragedPerceptron();
+            var ova = ML.MulticlassClassification.Trainers.OneVersusAll(ap);
+
+            var pipeline = ML.Transforms.Conversion.MapValueToKey("Label")
+                .Append(ML.Transforms.Concatenate("Features", "Row", "Column"))
+                .Append(ova)
+                .Append(ML.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
+
+            var model = pipeline.Fit(data);
```
Comment (eerhardt) [inline test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs]: We should do something with the model to ensure it was created correctly.

**Comment by Ivanidzo4ka** [comment]
I've check LR, SDCA and multiclass, all of them working fine with my changes.

---
In reply to: [477327070](https://github.com/dotnet/machinelearning/pull/3101#issuecomment-477327070) [](ancestors = 477327070)

File: test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs (hunk 4 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/TrainerEstimators/MetalinearEstimators.cs]: Any tests which use `TestEstimatorCore` will compare metadata from expected and resulted output schema.
I've change `AnnotationsForMulticlassScoreColumn` to always have TrainingLabelValue, and slotNames if key was text type, so technically we check that everywhere where we use `TestEstimatorCore`

---
In reply to: [269746627](https://github.com/dotnet/machinelearning/pull/3101#discussion_r269746627) [](ancestors = 269746627)

**Comment by eerhardt** [comment]
Can you address this comment? https://github.com/dotnet/machinelearning/pull/3101#discussion_r269747281

```
eerhardt 5 days ago
Can we add this to FunctionalTests instead? Let's not keep adding tests that the product allows InternalsVisibleTo. That way we can test like a customer uses the product.
````

File: test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs [hunk 6]
```diff
@@ -37,22 +37,22 @@ void PredictAndMetadata()
...
+
             // During prediction we will get Score column with 3 float values.
             // We need to find way to map each score to original label.
-            // In order to do what we need to get SlotNames from Score column.
-            // Slot names on top of Score column represent original labels for i-th value in Score array.
-            VBuffer<ReadOnlyMemory<char>> slotNames = default;
-            engine.OutputSchema[nameof(IrisPrediction.Score)].GetSlotNames(ref slotNames);
+            // In order to do what we need to get TrainingLabelValues from Score column.
+            // TrainingLabelValues on top of Score column represent original labels for i-th value in Score array.
+            VBuffer<ReadOnlyMemory<char>> originalLabels = default;
```
Comment (TomFinley) [inline test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: >ReadOnlyMemory [](start = 20, length = 14)

In this particular case we should be propagating *both* slot names and label names, right? Since they're string in both cases? While I see the point in augmenting the test to cover this new metadata type, is there any particular reason to remove the test that the vector has teh appropriate slot names?

File: test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs (hunk 2 above)
Comment (TomFinley) [reply test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: Multiple metadata kinds is good, thanks Ivan.

---
In reply to: [269742478](https://github.com/dotnet/machinelearning/pull/3101#discussion_r269742478) [](ancestors = 269742478)

File: test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs (hunk 6 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: This is old scenario test. Purpose of it to show user how to do work with metadata.
In this particular test label is string, and it has slotnames, but it wont in case of non string label.
If I add slotnames here it would be confusing? What for do I get slotnames?

All tests with TestEstimatorCore routing would test on presence of slotnames and TrainingLabelValues. And we have plenty of them,. why should we do anything here with slotname?

---
In reply to: [271046772](https://github.com/dotnet/machinelearning/pull/3101#discussion_r271046772) [](ancestors = 271046772)

Comment (TomFinley) [reply test/Microsoft.ML.Tests/Scenarios/Api/Estimators/PredictAndMetadata.cs]: OK, that's fine. I had the idea that these "showing the user" things were more the sake of functional tests, but as you like.

---
In reply to: [271050961](https://github.com/dotnet/machinelearning/pull/3101#discussion_r271050961) [](ancestors = 271050961,271046772)

File: test/Microsoft.ML.Functional.Tests/Training.cs [hunk 7]
```diff
@@ -467,5 +467,37 @@ public void MetacomponentsFunctionAsExpectedOva()
             // Evaluate the model.
             var binaryClassificationMetrics = mlContext.MulticlassClassification.Evaluate(binaryClassificationPredictions);
         }
+
+        /// <summary>
+        /// Training: Meta-compononts function as expected. For OVA (one-versus-all), a user will be able to specify only
```
Comment (eerhardt) [inline test/Microsoft.ML.Functional.Tests/Training.cs]: (nit) `compononts`

File: test/Microsoft.ML.Functional.Tests/Training.cs [hunk 8]
```diff
@@ -467,5 +467,37 @@ public void MetacomponentsFunctionAsExpectedOva()
...
+        /// binary classifier trainers. If they specify a different model class there should be a compile error.
+        /// </summary>
+        [Fact]
+        public void MetacomponentsFunctionWithKeyHandeling()
```
Comment (eerhardt) [inline test/Microsoft.ML.Functional.Tests/Training.cs]: (nit) `Handeling`

File: test/Microsoft.ML.Functional.Tests/Training.cs [hunk 9]
```diff
@@ -467,5 +467,37 @@ public void MetacomponentsFunctionAsExpectedOva()
...
+                .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
+
+            // Fit the binary classification pipeline.
+            var binaryClassificationModel = binaryClassificationPipeline.Fit(data);
+
+            // Transform the data
+            var binaryClassificationPredictions = binaryClassificationModel.Transform(data);
+
+            // Evaluate the model.
+            var binaryClassificationMetrics = mlContext.MulticlassClassification.Evaluate(binaryClassificationPredictions);
```
Comment (eerhardt) [inline test/Microsoft.ML.Functional.Tests/Training.cs]: Can we spot check some of these values to make sure the code isn't returning garbage?

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs [hunk 10]
```diff
@@ -131,7 +131,8 @@ private protected override NaiveBayesMulticlassModelParameters TrainModelCore(Tr
                     int size = cursor.Label + 1;
                     Utils.EnsureSize(ref labelHistogram, size);
                     Utils.EnsureSize(ref featureHistogram, size);
-                    Utils.EnsureSize(ref featureHistogram[cursor.Label], featureCount);
+                    if (featureHistogram[cursor.Label] == null)
+                        featureHistogram[cursor.Label] = new int[featureCount];
```
Comment (eerhardt) [inline src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: Was this change discovered by a test?

File: src/Microsoft.ML.Core/Data/AnnotationUtils.cs [hunk 11]
```diff
@@ -441,8 +441,15 @@ public static IEnumerable<SchemaShape.Column> GetTrainerOutputAnnotation(bool is
         public static IEnumerable<SchemaShape.Column> AnnotationsForMulticlassScoreColumn(SchemaShape.Column? labelColumn = null)
         {
             var cols = new List<SchemaShape.Column>();
-            if (labelColumn != null && labelColumn.Value.IsKey && NeedsSlotNames(labelColumn.Value))
-                cols.Add(new SchemaShape.Column(Kinds.SlotNames, SchemaShape.Column.VectorKind.Vector, TextDataViewType.Instance, false));
+            if (labelColumn != null && labelColumn.Value.IsKey)
+
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/AnnotationUtils.cs]: It would probably be good to wrap this in curly braces, now that it is more than one line (and that you have this blank line in between the if and the body.

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs (hunk 10 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: I wanted to make sure all multiclass learners works fine with my changes (so I run bunch of different one, on my test)
My test has only 2 features, and I got exception.
Mainly because Utils.EnsureSize use 4 as length for array even if you specify 1 or 2 or 3.
It make sense for VBuffer (since we have Count or Length, i'm always confused about which one is actual size of whole collection and which is size of elements in it), not sure why we do it for arrays as well.

---
In reply to: [271070400](https://github.com/dotnet/machinelearning/pull/3101#discussion_r271070400) [](ancestors = 271070400)

File: test/Microsoft.ML.Functional.Tests/Training.cs (hunk 8 above)
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Functional.Tests/Training.cs]: how it's different from what I have now?


---
In reply to: [271069790](https://github.com/dotnet/machinelearning/pull/3101#discussion_r271069790) [](ancestors = 271069790)

Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Functional.Tests/Training.cs]: did you mean `Handling`?

---
In reply to: [271072076](https://github.com/dotnet/machinelearning/pull/3101#discussion_r271072076) [](ancestors = 271072076,271069790)

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs (hunk 10 above)
Comment (eerhardt) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: Would it make sense to put all those tests into regression? That way we can catch bugs like this in the future?

File: test/Microsoft.ML.Functional.Tests/Training.cs (hunk 8 above)
Comment (eerhardt) [reply test/Microsoft.ML.Functional.Tests/Training.cs]: `Handeling` isn't a word (at least in English).
