### PR TITLE
Fix AP's output schema in its XML doc

### LINKED ISSUE #3496: Missing details in LinearSvmTrainer
There is only one short description for the mentioned trainer: `Linear SVM that implements PEGASOS for training. See: http://ttic.uchicago.edu/~shai/papers/ShalevSiSr07.pdf`. We should extend it to actually connect symbols in referenced paper and our implementation.

### LINKED ISSUE #3498: AveragedPerceptronTrainer's output schema is not correct
It should be
```
        private protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape inputSchema)
        {
            return new[]
            {
                // REVIEW AP is currently not calibrating. Add the probability column after fixing the behavior.
                new SchemaShape.Column(DefaultColumnNames.Score, SchemaShape.Column.VectorKind.Scalar, NumberDataViewType.Single, false, new SchemaShape(AnnotationUtils.GetTrainerOutputAnnotation())),
                new SchemaShape.Column(DefaultColumnNames.PredictedLabel, SchemaShape.Column.VectorKind.Scalar, BooleanDataViewType.Instance, false, new SchemaShape(AnnotationUtils.GetTrainerOutputAnnotation()))
            };
        }
```
but we accidentally added `Probability` at https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.averagedperceptrontrainer?view=ml-dotnet&branch=smoke-test-preview.

### PR DESCRIPTION
**Pull request by wschin**
Fix #3498 and fix #3496 by

- Add a new I/O file for binary classifier without probability output
- Reference that new file in AP's and LinearSVM's XML docs.

### CODE REVIEW

File: src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs [hunk 1]
```diff
@@ -30,7 +30,7 @@ namespace Microsoft.ML.Trainers
     /// To create this trainer, use [AveragedPerceptron](xref:Microsoft.ML.StandardTrainersCatalog.AveragedPerceptron(Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers,System.String,System.String,Microsoft.ML.Trainers.IClassificationLoss,System.Single,System.Boolean,System.Single,System.Int32))
     /// or [AveragedPerceptron(Options)](xref:Microsoft.ML.StandardTrainersCatalog.AveragedPerceptron(Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers,Microsoft.ML.Trainers.AveragedPerceptronTrainer.Options)).
     ///
-    /// [!include[io](~/../docs/samples/docs/api-reference/io-columns-binary-classification.md)]
+    /// [!include[io](~/../docs/samples/docs/api-reference/io-columns-binary-classification-no-prob.md)]
```
Comment (yaeldekel) [inline src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs]: >no-prob [](start = 92, length = 7)

I think SDCA also has a non-calibrated version, doesn't it?

Comment (yaeldekel) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs]: And it looks like `FastForest` doesn't calibrate either: `Fit` returns `BinaryPredictionTransformer<FastForestBinaryModelParameters>`.

---
In reply to: [277884116](https://github.com/dotnet/machinelearning/pull/3551#discussion_r277884116) [](ancestors = 277884116)

File: src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs [hunk 2]
```diff
@@ -45,12 +45,12 @@ namespace Microsoft.ML.Trainers
...
+    /// Linear [SVM](https://en.wikipedia.org/wiki/Support-vector_machine#Linear_SVM) implements
     /// an algorithm that finds a hyperplane in the feature space for binary classification, by solving an [SVM problem](https://en.wikipedia.org/wiki/Support-vector_machine#Computing_the_SVM_classifier).
     /// For instance, with feature values $f_0, f_1,..., f_{D-1}$, the prediction is given by determining what side of the hyperplane the point falls into.
-    /// That is the same as the sign of the feautures' weighted sum, i.e. $\sum_{i = 0}^{D-1} \left(w_i * f_i \right)$, where $w_0, w_1,..., w_{D-1}$ are the weights computed by the algorithm.
+    /// That is the same as the sign of the feautures' weighted sum, i.e. $\sum_{i = 0}^{D-1} \left(w_i * f_i \right) + b$, where $w_0, w_1,..., w_{D-1}$ and $b$ are the weights and bias computed by the algorithm.
     ///
-    /// This algorithm uses the PEGASOS method, which alternates between stochastic gradient descent steps and projection steps,
+    /// This algorithm implemented is the PEGASOS method, which alternates between stochastic gradient descent steps and projection steps,
```
Comment (shmoradims) [inline src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs]: >implemented is [](start = 23, length = 14)

implements

File: src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs (hunk 1 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/AveragedPerceptron.cs]: Sdca is just fixed in the 3rd iteration. FastForest can naturally produce probability.

---
In reply to: [277885158](https://github.com/dotnet/machinelearning/pull/3551#discussion_r277885158) [](ancestors = 277885158,277884116)

File: src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs]: algorithm cannot implement itself.

---
In reply to: [277888217](https://github.com/dotnet/machinelearning/pull/3551#discussion_r277888217) [](ancestors = 277888217)

Comment (codemzs) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs]: I'll let @TomFinley comment on this ..

File: src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs [hunk 3]
```diff
@@ -1641,7 +1641,7 @@ private protected override SchemaShape.Column[] ComputeSdcaBinaryClassifierSchem
     /// To create this trainer, use [SdcaNonCalibrated](xref:Microsoft.ML.StandardTrainersCatalog.SdcaNonCalibrated(Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers,System.String,System.String,System.String,Microsoft.ML.Trainers.ISupportSdcaClassificationLoss,System.Nullable{System.Single},System.Nullable{System.Single},System.Nullable{System.Int32}))
     /// or [SdcaNonCalibrated(Options)](xref:Microsoft.ML.StandardTrainersCatalog.SdcaNonCalibrated(Microsoft.ML.BinaryClassificationCatalog.BinaryClassificationTrainers,Microsoft.ML.Trainers.SdcaNonCalibratedBinaryTrainer.Options)).
     ///
-    /// [!include[io](~/../docs/samples/docs/api-reference/io-columns-binary-classification.md)]
+    /// [!include[io](~/../docs/samples/docs/api-reference/io-columns-binary-classification-no-prob.md)]
```
Comment (codemzs) [inline src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs]: thanks for fixing my mistake!

Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/SdcaBinary.cs]: No problem!

File: src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs]: I got Tom's support. :)

---
In reply to: [277907721](https://github.com/dotnet/machinelearning/pull/3551#discussion_r277907721) [](ancestors = 277907721)

Comment (TomFinley) [reply src/Microsoft.ML.StandardTrainers/Standard/Online/LinearSvm.cs]: Just to register my own opinion since I was explicitly asked, I agree with @shmoradims that the proposed edit was ungrammatical, and I also agree with what I interpret as @wschin's point that the proposed edit is not only ungrammatical but confuses the issue, and probably should not have happened. So I hope this phrasing remains unchanged, from its original point.
