### PR TITLE
Conversion of Logistic, Multiclass Logistic, and Poisson Regression to estimators

### LINKED ISSUE #956: Conversion of Logistic, Multiclass Logistic, and Poisson Regression to estimators
Conversion of Logistic, Multiclass Logistic, and Poisson Regression to estimators by deriving the base class LbfgsTrainerBase from TrainerEstimatorBase.

### PR DESCRIPTION
**Pull request by artidoro**
Fixes #956.

Conversion of Logistic, Multiclass Logistic, and Poisson Regression to estimators by deriving the base class LbfgsTrainerBase from TrainerEstimatorBase.

Working on testing the converted classes using TestEstimatorCore.

### CODE REVIEW

**Comment by sfilipi** [comment]
>         }

add a second constructor taking in the label, feature, weight column. 

---
Refers to: src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs:47 in c7a996e. [](commit_id = c7a996e34f3d00e1d8beb5248426e3fd1cdea71e, deletion_comment = False)

**Comment by sfilipi** [comment]
>         }

add the other constructor. 

---
Refers to: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs:76 in c7a996e. [](commit_id = c7a996e34f3d00e1d8beb5248426e3fd1cdea71e, deletion_comment = False)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 1]
```diff
@@ -277,6 +278,19 @@ protected override void ProcessPriorDistribution(Float label, Float weight)
...
             _prior[iLabel] += weight;
         }
+
+        protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape inputSchema)
+        {
+            return new[]
+            {
+                new SchemaShape.Column(DefaultColumnNames.Score, SchemaShape.Column.VectorKind.Scalar, NumberType.R4, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata())),
+                new SchemaShape.Column(DefaultColumnNames.Probability, SchemaShape.Column.VectorKind.Scalar, NumberType.R4, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata(true))),
+                new SchemaShape.Column(DefaultColumnNames.PredictedLabel, SchemaShape.Column.VectorKind.Scalar, BoolType.Instance, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata()))
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: don;t think we get probability for multi-class

File: src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs [hunk 2]
```diff
@@ -53,6 +54,19 @@ protected override void CheckLabel(RoleMappedData data)
             data.CheckRegressionLabel();
         }
 
+        protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape inputSchema)
+        {
+            return new[]
+            {
+                new SchemaShape.Column(DefaultColumnNames.Score, SchemaShape.Column.VectorKind.Scalar, NumberType.R4, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata())),
+                new SchemaShape.Column(DefaultColumnNames.Probability, SchemaShape.Column.VectorKind.Scalar, NumberType.R4, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata(true))),
+                new SchemaShape.Column(DefaultColumnNames.PredictedLabel, SchemaShape.Column.VectorKind.Scalar, BoolType.Instance, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata()))
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs]: only score.

File: test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+
+        public LbfgsTests(ITestOutputHelper output) : base(output)
+        {
+        }
+
+        [Fact]
+        public void TestEstimatorLogisticRegression()
+        {
+            var dataView = GetBreastCancerDataview();
+            dataView = Env.CreateTransform("Term{col=F1}", dataView);
```
[the remark this answers is not in the document]
Comment (artidoro) [reply test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs]: Thank you! I'll look into changing this then.

---
In reply to: [219323059](https://github.com/dotnet/machinelearning/pull/957#discussion_r219323059) [](ancestors = 219323059,219322724)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 4]
```diff
@@ -277,6 +284,18 @@ protected override void ProcessPriorDistribution(Float label, Float weight)
             Contracts.Assert(0 <= iLabel && iLabel < _numClasses);
             _prior[iLabel] += weight;
         }
+
+        protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape inputSchema)
+        {
+            return new[]
+            {
+                new SchemaShape.Column(DefaultColumnNames.Score, SchemaShape.Column.VectorKind.Scalar, NumberType.R4, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata())),
+                new SchemaShape.Column(DefaultColumnNames.PredictedLabel, SchemaShape.Column.VectorKind.Scalar, BoolType.Instance, false, new SchemaShape(MetadataUtils.GetTrainerOutputMetadata()))
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >new SchemaSh [](start = 138, length = 12)

look at what SDCA multiclass is doing for the metadata append the Label metadata here.

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 5]
```diff
@@ -69,8 +70,14 @@ public sealed class Arguments : ArgumentsBase
 
         protected override int ClassCount => _numClasses;
 
+        public MulticlassLogisticRegression(IHostEnvironment env, string featureColumn, string labelColumn,
+            string groupIdColumn = null, string weightColumn = null, Action<Arguments> advancedSettings = null)
+            : base(env, featureColumn, labelColumn, weightColumn, groupIdColumn, advancedSettings)
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >labelColumn [](start = 39, length = 11)

shape of the label column for multi-class is different than regression, will want to construct it here.

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 6]
```diff
@@ -173,6 +190,49 @@ internal LbfgsTrainerBase(ArgumentsBase args, IHostEnvironment env, string name,
...
+            Contracts.CheckUserArg(Args.SgdInitializationTolerance >= 0, nameof(Args.SgdInitializationTolerance), "Must be non-negative");
+            SgdInitializationTolerance = Args.SgdInitializationTolerance;
+            Quiet = Args.Quiet;
+            InitWtsDiameter = Args.InitWtsDiameter;
+            UseThreads = Args.UseThreads;
+            Contracts.CheckUserArg(Args.NumThreads == null || Args.NumThreads.Value >= 0, nameof(Args.NumThreads), "Must be non-negative");
+            NumThreads = Args.NumThreads;
+            DenseOptimizer = Args.DenseOptimizer;
+            //ShowTrainingStats = showTrainingStats; // TODO
+            EnforceNonNegativity = Args.EnforceNonNegativity;
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: try to avoid repetition between the two constructors

File: test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+            Done();
+        }
+
+        [Fact]
+        public void TestEstimatorMulticlassLogisticRegression()
+        {
+            var dataView = GetIrisDataview();
+            var data = FeatureCombiner.PrepareFeatures(Env, new FeatureCombiner.FeatureCombinerInput() { Data = dataView, Features = new[] { "SepalLength", "SepalWidth", "PetalLength", "PetalWidth" } }).OutputData;
+
+            var pipe = new LogisticRegression(Env, "Features", "Label");
```
Comment (sfilipi) [inline test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs]: >LogisticRegression [](start = 27, length = 18)

did you mean multiclassLR?

File: test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs [hunk 8]
```diff
@@ -0,0 +1,122 @@
...
+            TestEstimatorCore(pipe, data);
+            Done();
+        }
+
+        [Fact]
+        public void TestEstimatorPoissonRegression()
+        {
+            var dataView = GetGeneratedRegressionDataview();
+            var pipe = new LogisticRegression(Env, "Features", "Label");
```
Comment (sfilipi) [inline test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs]: >LogisticRegression [](start = 27, length = 18)

Possion

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 5 above)
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: I kept it as it is now and the tests seem to be passing correctly. Am I missing something?

---
In reply to: [219326153](https://github.com/dotnet/machinelearning/pull/957#discussion_r219326153) [](ancestors = 219326153)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 9]
```diff
@@ -173,6 +190,49 @@ internal LbfgsTrainerBase(ArgumentsBase args, IHostEnvironment env, string name,
                     ch.Done();
                 }
             }
+            _srcPredictor = default;
+        }
+
+        internal LbfgsTrainerBase(IHostEnvironment env, TArgs args)
+            : base(Contracts.CheckRef(env, nameof(env)).Register(RegisterName), MakeFeatureColumn(args.FeatureColumn), MakeFeatureColumn(args.LabelColumn), MakeWeightColumn(args.WeightColumn))
```
Comment (zeahmed) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: >MakeFeatureColumn [](start = 119, length = 17)

MakeLabelColumn?

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 10]
```diff
@@ -173,6 +190,49 @@ internal LbfgsTrainerBase(ArgumentsBase args, IHostEnvironment env, string name,
                     ch.Done();
                 }
             }
+            _srcPredictor = default;
+        }
+
+        internal LbfgsTrainerBase(IHostEnvironment env, TArgs args)
```
Comment (zeahmed) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: >LbfgsTrainerBase [](start = 17, length = 16)

I think you can this constructor from the other one to get ride to code redundancy.

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 1 above)
Comment (zeahmed) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: actually `Score` is the probability vector for the case of multiclass.

---
In reply to: [219044096](https://github.com/dotnet/machinelearning/pull/957#discussion_r219044096) [](ancestors = 219044096)

File: test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs [hunk 11]
```diff
@@ -0,0 +1,88 @@
...
+                    new TextLoader.Column("Features", DataKind.R4, new [] { new TextLoader.Range(0, 10) } )
+                }
+            }).Read(new MultiFileSource(GetDataPath(TestDatasets.generatedRegressionDataset.trainFilename)));
+        }
+
+        [Fact]
+        public void TestEstimatorLogisticRegression()
+        {
+            var dataView = GetBreastCancerDataview();
+            //var args = new LogisticRegression.Arguments();
```
Comment (zeahmed) [inline test/Microsoft.ML.Tests/TrainerEstimators/LbfgsTests.cs]: >//var args = new LogisticRegression.Arguments(); [](start = 12, length = 48)

please remove commented code.

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 12]
```diff
@@ -137,32 +143,55 @@ public abstract class ArgumentsBase : LearnerInputBaseWithWeight
...
+            : base(Contracts.CheckRef(env, nameof(env)).Register(RegisterName), MakeFeatureColumn(args.FeatureColumn), MakeFeatureColumn(args.LabelColumn), MakeWeightColumn(args.WeightColumn))
+        {
+            Host.CheckValue(args, nameof(args));
+            Args = args;
+
+            InitArguments();
+        }
+
+        protected void InitArguments()
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: >protected [](start = 8, length = 9)

would private suffice?

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 5 above)
Comment (sfilipi) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: i think the label for multiclass is a key, and item type U4. R4 is probably acceptable, but you need it to be a key. 

---
In reply to: [219349397](https://github.com/dotnet/machinelearning/pull/957#discussion_r219349397) [](ancestors = 219349397,219326153)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 13]
```diff
@@ -69,9 +70,20 @@ public sealed class Arguments : ArgumentsBase
 
         protected override int ClassCount => _numClasses;
 
+        public MulticlassLogisticRegression(IHostEnvironment env, string featureColumn, string labelColumn,
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >public [](start = 8, length = 6)

documentation

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 14]
```diff
@@ -137,32 +143,55 @@ public abstract class ArgumentsBase : LearnerInputBaseWithWeight
...
+            advancedSettings?.Invoke(Args);
+            Args.FeatureColumn = featureColumn;
+            Args.LabelColumn = labelColumn;
+            if (weightColumn != null)
+                Args.WeightColumn = weightColumn;
+
+            InitArguments();
+        }
+
+        internal LbfgsTrainerBase(IHostEnvironment env, TArgs args)
```
[the remark this answers is not in the document]
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: That might be a bit hard. The arguments would not be in Args before running the code in the original constructor. And I believe that happens after calling the other constructor. 

---
In reply to: [219355643](https://github.com/dotnet/machinelearning/pull/957#discussion_r219355643) [](ancestors = 219355643)

[the remark this answers is not in the document]
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: I'll try to keep them readonly though.

---
In reply to: [219593965](https://github.com/dotnet/machinelearning/pull/957#discussion_r219593965) [](ancestors = 219593965,219355643)

[the remark this answers is not in the document]
Comment (zeahmed) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: Actually for TAgrs, you could write a static method that would return the TArgs and that you could use in `this()` call as `this(...CreateArgs(...)..)`.



---
In reply to: [219594177](https://github.com/dotnet/machinelearning/pull/957#discussion_r219594177) [](ancestors = 219594177,219593965,219355643)

[the remark this answers is not in the document]
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: Oh that's a good idea! I will look into that.

---
In reply to: [219653751](https://github.com/dotnet/machinelearning/pull/957#discussion_r219653751) [](ancestors = 219653751,219594177,219593965,219355643)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 15]
```diff
@@ -277,6 +300,39 @@ protected override void ProcessPriorDistribution(Float label, Float weight)
...
+        /// <summary>
+        /// Normal metadata that we produce for score columns.
+        /// </summary>
+        private static IEnumerable<SchemaShape.Column> MetadataForScoreColumn()
+        {
+            var cols = new List<SchemaShape.Column>();
+            cols.Add(new SchemaShape.Column(MetadataUtils.Kinds.ScoreColumnSetId, SchemaShape.Column.VectorKind.Scalar, NumberType.U4, true));
+            cols.Add(new SchemaShape.Column(MetadataUtils.Kinds.ScoreColumnKind, SchemaShape.Column.VectorKind.Scalar, TextType.Instance, false));
+            cols.Add(new SchemaShape.Column(MetadataUtils.Kinds.SlotNames, SchemaShape.Column.VectorKind.Vector, TextType.Instance, false));
+            cols.Add(new SchemaShape.Column(MetadataUtils.Kinds.ScoreValueKind, SchemaShape.Column.VectorKind.Scalar, TextType.Instance, false));
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: can some of those come from MetadataUtils.GetTrainerOutputMetadata() and you add what you need?

**Comment by sfilipi** [comment]
> [assembly: LoadableClass(typeof(void), typeof(LogisticRegression), null, typeof(SignatureEntryPointModule), "LogisticRegression")]

if you do another iteration, substitute with LoadNameValue. 

---
Refers to: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs:28 in 3842583. [](commit_id = 384258381ef6b5e745ddbf3524f76f21946cd75c, deletion_comment = False)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs [hunk 16]
```diff
@@ -48,12 +49,38 @@ public sealed class Arguments : ArgumentsBase
...
+            _posWeight = 0;
+            ShowTrainingStats = Args.ShowTrainingStats;
+        }
+
+        /// <summary>
+        /// Initializes a new instance of <see cref="LogisticRegression"/>
+        /// </summary>
         public LogisticRegression(IHostEnvironment env, Arguments args)
-            : base(args, env, LoadNameValue, Contracts.CheckRef(args, nameof(args)).ShowTrainingStats)
+            : base(env, args, MakeLabelColumn(args.LabelColumn))
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LogisticRegression.cs]: >MakeLabelColumn [](start = 30, length = 15)

re-use TrainerUtils.MakeR4ScalarLabel

File: src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs [hunk 17]
```diff
@@ -5,6 +5,7 @@
 using Float = System.Single;
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs]: if you do another iteration, clean this up.

File: src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs [hunk 18]
```diff
@@ -40,11 +41,33 @@ public sealed class Arguments : ArgumentsBase
...
+            Host.CheckNonEmpty(featureColumn, nameof(featureColumn));
+            Host.CheckNonEmpty(labelColumn, nameof(labelColumn));
+        }
+
+        /// <summary>
+        /// Initializes a new instance of <see cref="PoissonRegression"/>
+        /// </summary>
         public PoissonRegression(IHostEnvironment env, Arguments args)
-            : base(args, env, LoadNameValue)
+            : base(env, args, MakeLabelColumn(args.LabelColumn))
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs]: >MakeLabelColumn [](start = 30, length = 15)

TrainerUtils

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 19]
```diff
@@ -69,9 +68,31 @@ public sealed class Arguments : ArgumentsBase
...
+            Host.CheckNonEmpty(featureColumn, nameof(featureColumn));
+            Host.CheckNonEmpty(labelColumn, nameof(labelColumn));
+
+            ShowTrainingStats = Args.ShowTrainingStats;
+        }
+
+        /// <summary>
+        /// Initializes a new instance of <see cref="MulticlassLogisticRegression"/>
+        /// </summary>
         public MulticlassLogisticRegression(IHostEnvironment env, Arguments args)
```
Comment (sfilipi) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >public [](start = 8, length = 6)

is internal enough?

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 20]
```diff
@@ -92,77 +93,89 @@ public abstract class ArgumentsBase : LearnerInputBaseWithWeight
...
+            OptTol = Args.OptTol;
+            MemorySize = Args.MemorySize;
+            MaxIterations = Args.MaxIterations;
+            SgdInitializationTolerance = Args.SgdInitializationTolerance;
+            Quiet = Args.Quiet;
+            InitWtsDiameter = Args.InitWtsDiameter;
+            UseThreads = Args.UseThreads;
+            NumThreads = Args.NumThreads;
+            DenseOptimizer = Args.DenseOptimizer;
+            EnforceNonNegativity = Args.EnforceNonNegativity;
```
[the remark this answers is not in the document]
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/LbfgsPredictorBase.cs]: They are been called by both constructors. I set it up so that the first constructor calls the second using this(...). It was suggested by Zeeshan A.

---
In reply to: [219994227](https://github.com/dotnet/machinelearning/pull/957#discussion_r219994227) [](ancestors = 219994227)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 15 above)
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: That unfortunately does not work. It was my first try. But MetadataUtils.GetTrainerOutputMetadata() returns a IEnumerable<SchemaShape.Column> which does not necessarily implement Add. We could make that work if we changed the return type of the function to be List<SchemaShape.Column>. I am not sure if that's fine though. 

---
In reply to: [219994603](https://github.com/dotnet/machinelearning/pull/957#discussion_r219994603) [](ancestors = 219994603,219936745)

File: src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs [hunk 21]
```diff
@@ -27,7 +26,7 @@
 namespace Microsoft.ML.Runtime.Learners
 {
     /// <include file='doc.xml' path='doc/members/member[@name="PoissonRegression"]/*' />
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs]: >PoissonRegression [](start = 64, length = 17)

If you look in doc.xml in our code sample we have this:
```
new PoissonRegressor
          {
            MaxIterations = 100,
            L2Weight = 0.6f
          }
```
Which is no longer are valid statement.

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 22]
```diff
@@ -38,7 +37,7 @@ namespace Microsoft.ML.Runtime.Learners
 {
     /// <include file = 'doc.xml' path='doc/members/member[@name="LBFGS"]/*' />
     /// <include file = 'doc.xml' path='docs/members/example[@name="LogisticRegressionClassifier"]/*' />
-    public sealed class MulticlassLogisticRegression : LbfgsTrainerBase<VBuffer<Float>, MulticlassLogisticRegressionPredictor>
+    public sealed class MulticlassLogisticRegression : LbfgsTrainerBase<MulticlassLogisticRegression.Arguments, MulticlassPredictionTransformer<MulticlassLogisticRegressionPredictor>, MulticlassLogisticRegressionPredictor>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: can you break this line?

File: src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs (hunk 21 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardLearners/Standard/PoissonRegression/PoissonRegression.cs]: Actually I think it's a much broader issue, and need to be resolved for all converted to estimators classes.

---
In reply to: [220025467](https://github.com/dotnet/machinelearning/pull/957#discussion_r220025467) [](ancestors = 220025467)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 23]
```diff
@@ -143,42 +164,42 @@ protected override void CheckLabel(RoleMappedData data)
...
         protected override Optimizer InitializeOptimizer(IChannel ch, FloatLabelCursor.Factory cursorFactory,
-            out VBuffer<Float> init, out ITerminationCriterion terminationCriterion)
+            out VBuffer<float> init, out ITerminationCriterion terminationCriterion)
         {
             var opt = base.InitializeOptimizer(ch, cursorFactory, out init, out terminationCriterion);
 
             // MeanImprovementCriterion:
             //   Terminates when the geometrically-weighted average improvement falls below the tolerance
-            terminationCriterion = new MeanImprovementCriterion(OptTol, (Float)0.25, MaxIterations);
+            terminationCriterion = new MeanImprovementCriterion(OptTol, (float)0.25, MaxIterations);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >(float)0.25 [](start = 72, length = 11)

0.25f
no reason to cast it.

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 24]
```diff
@@ -271,16 +292,47 @@ protected override void ComputeTrainingStatistics(IChannel ch, FloatLabelCursor.
...
+            => new MulticlassPredictionTransformer<MulticlassLogisticRegressionPredictor>(Host, model, trainSchema, FeatureColumn.Name, LabelColumn.Name);
+
+        /// <summary>
+        /// Normal metadata that we produce for score columns.
+        /// </summary>
+        private static IEnumerable<SchemaShape.Column> MetadataForScoreColumn()
+        {
+            var cols = new List<SchemaShape.Column>();
+            foreach (SchemaShape.Column col in MetadataUtils.GetTrainerOutputMetadata())
+            {
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >{ [](start = 12, length = 1)

I think we have tendency to omit braces for one liners.

Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Actually, why can't you do cols.AddRange(MetadataUtils.GetTrainerOutputMetadata()) ?

---
In reply to: [220026583](https://github.com/dotnet/machinelearning/pull/957#discussion_r220026583) [](ancestors = 220026583)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 25]
```diff
@@ -646,7 +698,7 @@ protected override void SaveCore(ModelSaveContext ctx)
         }
 
         // REVIEW: Destroy.
-        private static int NonZeroCount(ref VBuffer<Float> vector)
+        private static int NonZeroCount(ref VBuffer<float> vector)
         {
             if (!vector.IsDense)
                 return vector.Count;
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Not related to your changes, but I think this is wrong. 
Also, great review comment for this method!

**Comment by Ivanidzo4ka** [comment]
>             writer.WriteLine("MulticlassLogisticRegression bias and non-zero weights");

can you use nameof(MulticlassLogisticRegression) instead?

---
Refers to: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs:790 in 4dcb4ab. [](commit_id = 4dcb4ab0335d190608c23e760f7ade846bf4fa8a, deletion_comment = False)

File: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 25 above)
Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: I do think it's a pretty extreme review comment! haha


---
In reply to: [220027114](https://github.com/dotnet/machinelearning/pull/957#discussion_r220027114) [](ancestors = 220027114)

Comment (artidoro) [reply src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Should we file an issue on this?

---
In reply to: [220044369](https://github.com/dotnet/machinelearning/pull/957#discussion_r220044369) [](ancestors = 220044369,220027114)

**Comment by Ivanidzo4ka** [comment]
>             writer.WriteLine("MulticlassLogisticRegression bias and non-zero weights");

I don't meant to remove "bias and non-zero weights" from output, just replace string constant of class to nameof class.

---
In reply to: [424166489](https://github.com/dotnet/machinelearning/pull/957#issuecomment-424166489) [](ancestors = 424166489)

---
Refers to: src/Microsoft.ML.StandardLearners/Standard/LogisticRegression/MulticlassLogisticRegression.cs:790 in 4dcb4ab. [](commit_id = 4dcb4ab0335d190608c23e760f7ade846bf4fa8a, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
Please merge it with master.
