### PR TITLE
Remove DnnAnalyzer from the Microsoft.ML.TensorFlow nuget

### LINKED ISSUE #1027: Microsoft.ML.TensorFlow is currently broken
### System information

- **OS version/distro**: all
- **.NET Version (eg., dotnet --info)**:  any

### Issue

- **What did you do?**
Create a .NET Core console project that references the latest version of `Microsoft.ML.TensorFlow`.
- **What happened?**
I don't get a reference to the `Microsoft.ML.TensorFlow.dll`. I only get a reference to `DnnAnalyzer.dll`
image

- **What did you expect?**
I expected to get a reference to `Microsoft.ML.TensorFlow.dll` so I could call methods in it.

### Notes

The reason this happens is because we are including the `DnnAnalyzer.dll` in the `lib\netcoreapp2.0` directory of the `Microsoft.ML.TensorFlow` nuget package:

image

NuGet only picks assets from 1 of these folders. And since my app is .NET Core, it only picks the assemblies from the `lib\netcoreapp2.0` directory.

/cc @ericstj @yaeldekel @abgoswam

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #1027 .

### CODE REVIEW

File: src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj [hunk 1]
```diff
@@ -4,7 +4,6 @@
     <OutputType>Exe</OutputType>
     <TargetFramework>netcoreapp2.0</TargetFramework>
     <AssemblyName>DnnAnalyzer</AssemblyName>
-    <IncludeInPackage>Microsoft.ML.TensorFlow</IncludeInPackage>
   </PropertyGroup>
 
   <ItemGroup>
```
Comment (ericstj) [inline src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj]: Existing Issue: if you want this project to work on Linux/Mac you also need tensorflow_framework below, similar to https://github.com/dotnet/machinelearning/blob/eb264892e75219b1f191d3c35fcbc636186b8acf/test/Microsoft.ML.Tests/Microsoft.ML.Tests.csproj#L33.

File: src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj [hunk 2]
```diff
@@ -4,7 +4,6 @@
     <OutputType>Exe</OutputType>
     <TargetFramework>netcoreapp2.0</TargetFramework>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj]: >netcoreapp2.0 [](start = 21, length = 13)

Comment from @eerhardt from previous PR: 
>This should be netcoreapp2.1. Note that netcoreapp and netstandard are different things. We want netcoreapp2.1 for any and all executables and tests. We want netstandard2.0 for any libraries.

Comment (TomFinley) [reply src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj]: I'd prefer we just nuke this thing altogether and recast it as an `ICommand`. It should have been one anyway.

File: src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj (hunk 1 above)
Comment (shauheen) [reply src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj]: @yaeldekel I think this needs to be updated.

Comment (eerhardt) [reply src/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer/Microsoft.ML.DnnAnalyzer.csproj]: I'm not sure fixing this issue is 100% necessary for `0.6` since we aren't going to be shipping DnnAnalyzer in `0.6`.
