### PR TITLE
Remove the error tracing when assembly loading fails for Maml.

### LINKED ISSUE #1034: Error Message Returned by Command Line Tool (Fail to Load Native Assembly)
Btw, running the following command `dotnet bin\AnyCPU.Debug\Microsoft.ML.Console\netcoreapp2.0\MML.dll showdata data=machinelearning\x1 loader=text{sep=space col=C0:TX:0-2} xf=term{col=C0}`, I got three error messages (shown below) about failing to load assembly.

Could not load assembly D:\Repos\machinelearning1\bin\AnyCPU.Debug\Microsoft.ML.Console\netcoreapp2.0\CpuMathNative.dll:
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ML.Runtime.AssemblyLoadingUtils.LoadAssembly(IHostEnvironment env, String path) in D:\Repos\machinelearning1\src\Common\AssemblyLoadingUtils.cs:line 207
Could not load assembly D:\Repos\machinelearning1\bin\AnyCPU.Debug\Microsoft.ML.Console\netcoreapp2.0\FactorizationMachineNative.dll:
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ML.Runtime.AssemblyLoadingUtils.LoadAssembly(IHostEnvironment env, String path) in D:\Repos\machinelearning1\src\Common\AssemblyLoadingUtils.cs:line 207
Skipping assembly 'D:\Repos\machinelearning1\bin\AnyCPU.Debug\Microsoft.ML.Console\netcoreapp2.0\FastTreeNative.dll' because its name was filtered.
Could not load assembly D:\Repos\machinelearning1\bin\AnyCPU.Debug\Microsoft.ML.Console\netcoreapp2.0\LdaNative.dll:
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.ML.Runtime.AssemblyLoadingUtils.LoadAssembly(IHostEnvironment env, String path) in D:\Repos\machinelearning1\src\Common\AssemblyLoadingUtils.cs:line 207

### PR DESCRIPTION
**Pull request by eerhardt**
Also adding our native assemblies to the list to skip, so they aren't attempted to be loaded.

Fix #1034

### CODE REVIEW

**Comment by shauheen** [comment]
Will this fix #1042 ?

File: src/Common/AssemblyLoadingUtils.cs [hunk 1]
```diff
@@ -140,9 +140,12 @@ private static bool ShouldSkipPath(string path)
             string name = Path.GetFileName(path).ToLowerInvariant();
             switch (name)
             {
+                case "cpumathnative.dll":
```
Comment (Ivanidzo4ka) [inline src/Common/AssemblyLoadingUtils.cs]: >cpumathnative [](start = 22, length = 13)

symsgdnative.dll as well.

how it works for linux btw? we have libCpuMathNative.so not cpumathnative.dll

Comment (eerhardt) [reply src/Common/AssemblyLoadingUtils.cs]: I'll add symsgdnative.dll as well.

It works for linux because we are enumerating `*.dll` and then calling `ShouldSkipPath` on the results of that.  On linux, the file extension is `.so`, so that doesn't match `*.dll`, which means those assemblies are never returned.

**Comment by eerhardt** [comment]
> Will this fix #1042 ?

No that is a separate issue.
