### PR TITLE
Ensure the named model is loaded

### LINKED ISSUE #5831: [Microsoft.Extensions.ML] PredictionEnginePool.GetModel(string modelName) does not ensure the named model is loaded
### Preface

We're using a named prediction engine with the name `model1` in a `PredictionEnginePool`.

```c#
services
    .AddPredictionEnginePool<ModelInput, ModelOutput>()
    .FromFile(modelName: "model1", filePath: "MLModel.zip", watchForChanges: false);
```

Example usage:

```c#
private readonly PredictionEnginePool<ModelInput, ModelOutput> _pool;

public void ThisWorks()
{
    // This will initialize the "model1" prediction engine if it hasn't been used yet
    // See source code:
    // https://github.com/dotnet/machinelearning/blob/58450d4f0709c237de95f31f8f05d46983c7a5c0/src/Microsoft.Extensions.ML/PredictionEnginePool.cs#L81
    PredictionEngine<ModelInput, ModelOutput> engine = _pool.GetPredictionEngine("model1");
    
    // We can now use the engine, then return it to the pool
}
```

In the above snippet, the `PredictionEnginePool.GetPredictionEngine(string modelName)` method ensures the engine is loaded before use.

https://github.com/dotnet/machinelearning/blob/58450d4f0709c237de95f31f8f05d46983c7a5c0/src/Microsoft.Extensions.ML/PredictionEnginePool.cs#L101-L105

### The issue

If `_pool.GetPredictionEngine("model1")` has never been called before calling `_pool.GetModel("model1")`, the `model1` prediction engine is not loaded and `KeyNotFoundException` will be thrown.

```c#
private readonly PredictionEnginePool<ModelInput, ModelOutput> _pool;

public void ThisDoesNotWork()
{
    // Throws KeyNotFoundException unless _pool.GetPredictionEngine("model1") has been called before
    // See source code:
    // https://github.com/dotnet/machinelearning/blob/58450d4f0709c237de95f31f8f05d46983c7a5c0/src/Microsoft.Extensions.ML/PredictionEnginePool.cs#L51
    ITransformer model = _pool.GetModel("model1");
}
```

This inconsistent behavior can easily catch someone off-guard - one expects every public method on `PredictionEnginePool` to have the same "ensure initialized" behavior.

https://github.com/dotnet/machinelearning/blob/58450d4f0709c237de95f31f8f05d46983c7a5c0/src/Microsoft.Extensions.ML/PredictionEnginePool.cs#L51-L54

### Code example

https://github.com/wjwilimowski/UnexpectedPredictionEnginePool

### PR DESCRIPTION
**Pull request by feiyun0112**
Fix  #5831

### CODE REVIEW

File: test/Microsoft.Extensions.ML.Tests/PredictionEnginePoolTests.cs [hunk 1]
```diff
@@ -0,0 +1,61 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using System;
+using System.IO;
+using System.Threading;
+using Microsoft.Extensions.DependencyInjection;
+using Microsoft.Extensions.Logging;
```
Comment (Crabzmatic) [inline test/Microsoft.Extensions.ML.Tests/PredictionEnginePoolTests.cs:9]: Looks good! 

I think you have some redundant imports here.

**Review by michaelgsharp — APPROVED** [review]
Looks good! Thanks for the submission.
