### PR TITLE
Polish some options' XML document strings

### LINKED ISSUE #3507: Inheritance of LbfgsLogisticRegressionBinaryTrainer.Options class doesn't have links
Inheritance
Microsoft.ML.Trainers.LbfgsTrainerBase`3+OptionsBaseLbfgsLogisticRegressionBinaryTrainer.Options

### PR DESCRIPTION
**Pull request by wschin**
Fix #3507.

Note that some options don't have API references because they are not used to create trainers. For example, we cannot create SdcaMulticlassTrainerBase because it's a base class.

### CODE REVIEW

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 1]
```diff
@@ -24,7 +24,8 @@ public abstract class LbfgsTrainerBase<TOptions, TTransformer, TModel> : Trainer
       where TOptions : LbfgsTrainerBase<TOptions, TTransformer, TModel>.OptionsBase, new()
     {
         /// <summary>
-        /// Base options for <a href='https://en.wikipedia.org/wiki/Limited-memory_BFGS'>L-BFGS</a>-based trainers.
+        /// Options for the <see cref="LbfgsTrainerBase{TOptions, TTransformer, TModel}"/>.
+        /// It is used in <a href='https://en.wikipedia.org/wiki/Limited-memory_BFGS'>L-BFGS</a>-based trainers.
```
Comment (natke) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs]: Would it be better to have this wikipedia link on the trainer itself?

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs [hunk 2]
```diff
@@ -24,7 +24,8 @@ public abstract class LbfgsTrainerBase<TOptions, TTransformer, TModel> : Trainer
       where TOptions : LbfgsTrainerBase<TOptions, TTransformer, TModel>.OptionsBase, new()
     {
         /// <summary>
-        /// Base options for <a href='https://en.wikipedia.org/wiki/Limited-memory_BFGS'>L-BFGS</a>-based trainers.
+        /// Options for the <see cref="LbfgsTrainerBase{TOptions, TTransformer, TModel}"/>.
```
Comment (yaeldekel) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs]: >Options [](start = 12, length = 7)

Suggestion:
`Base Options class for trainer estimators deriving from ...`.
(For the SDCA base class too).

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs (hunk 1 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/LbfgsPredictorBase.cs]: I kind of feel adding link to this abstract class could make users thinking they can create it.
