### PR TITLE
Fixed score column name and order bugs in CalibratorTransformer

### LINKED ISSUE #4700: Using PlattCalibratorTransformer with custon name for Score Column
### Issue

- **What did you do?**
I tried to create a model with a PlattCalibratorEstimator that uses a `scoreColumnName` with a name different from "Score" (as done through [this API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.binaryclassificationcatalog.calibratorscatalog.platt?view=ml-dotnet#Microsoft_ML_BinaryClassificationCatalog_CalibratorsCatalog_Platt_System_String_System_String_System_String_))

- **What happened?**
After fitting the estimator, and while trying to transform the input dataview, the following exception is thrown:
`System.InvalidOperationException: 'The data to calibrate contains no 'Score' column'`

- **What did you expect?**
The model to work the same way as if I had used the name "Score" for my score column

Furthermore, I couldn't find any sample or test that actually used the optional parameter `scoreColumnName` of PlattCalibratorEstimator, or the other parameters (such as labelColumnName). So adding such tests might be also necessary (if my PR #4700 gets in, then fixing this issue in here would also require to add onnx tests to check that PlattCalibrator with custom scoreColumnName is saved correctly to onnx). Checking if this problem also occurs in the other CalibratorTransformers would also be relevant.

Notice that a simple workaround for this would be to copy the column that holds the score into a new column called Score, and specify Score as the scoreColumnName.

### Source code / logs
In EXAMPLE 1 I show that it works if my score column is named "Score". But if I change the name, then it doesn't work.

```C#
using Microsoft.ML;

namespace Platt2
{
    public static class Platt2
    {

        class ModelInput
        {
            public bool Label { get; set; }
            public float Score { get; set; }
        }

        class ModelInput2
        {
            public bool Label { get; set; }
            public float ScoreX { get; set; }
        }

        public static void Main()
        {
            var mlContext = new MLContext(seed: 0);

            // EXAMPLE 1 - Works
            IDataView data = mlContext.Data.LoadFromEnumerable<ModelInput>(
                new ModelInput[]
                {
                                new ModelInput { Score = 10, Label = true },
                                new ModelInput { Score = 15, Label = false },
                }
            );

            var calibratorEstimator = mlContext.BinaryClassification.Calibrators
                .Platt();

            var calibratorTransformer = calibratorEstimator.Fit(data);
            var finalData = calibratorTransformer.Transform(data);
            var prev = finalData.Preview();


            // EXAMPLE 2 - Doesn't Work
            IDataView data2 = mlContext.Data.LoadFromEnumerable<ModelInput2>(
                new ModelInput2[]
                {
                                new ModelInput2 { ScoreX = 10, Label = true },
                                new ModelInput2 { ScoreX = 15, Label = false },
                }
            );

            calibratorEstimator = mlContext.BinaryClassification.Calibrators
                .Platt(scoreColumnName: "ScoreX");

            calibratorTransformer = calibratorEstimator.Fit(data2);
            finalData = calibratorTransformer.Transform(data2); // Throws exception
            prev = finalData.Preview();

        }

    }
}
```

### PR DESCRIPTION
**Pull request by mstfbl**
Fix #4700 

As explained in #4700, the column order in which the Score column is given to `PlattCalibratorTransformer` exposes a bug in `CalibratorTransformer` where the name and the location of the score column is hard-coded. This PR fixes this hard-coding, where now the name and order of the score column given to `CalibratorTransformer` can be different than the default values.

I have also added unit tests to confirm these changes with respect to direct non-standard column name tests and Onnx Conversions.

### CODE REVIEW

File: test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs [hunk 1]
```diff
@@ -137,5 +137,101 @@ private sealed class CalibratorTestData
...
+                        new CalibratorTestInputReversedOrderAndUniqueScoreColumnName { ScoreX = 10, Label = true },
+                        new CalibratorTestInputReversedOrderAndUniqueScoreColumnName { ScoreX = 15, Label = false }
+                    })
+            };
+
+            // When label and/or score columns are different from their default names ("Label" and "Score", respectively), they
+            // need to be manually defined as done below.
+            // Successful training of estimators and transforming with transformers indicate correct label and score columns
+            // have been found.
+            for (int i = 0; i < dataArray.Length; i++)
```
Comment (mstfbl) [inline test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs:176]: Here, I also attempted to test the variability of the label column between the four calibrator trainers. However, there are inconsistencies between these trainers that prevented me from doing this smoothly. For one, [FixedPlattCalibratorEstimator ](https://github.com/dotnet/machinelearning/blob/ec159ec41c774ef1ae5ecc2a8db3cd4aea3ae55e/src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs#L363-L374)doesn't have a `labelColumn` parameter, which means only the default "Label" column name can be used with this estimator. In addition, "scoreColumnName" is used in PlattCalibratorEstimator, but in the others "scoreColumn" is used. In a separate PR I will make the necessary changes to fix the problems described.

File: src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs [hunk 2]
```diff
@@ -186,7 +188,9 @@ private protected CalibratorTransformer(IHostEnvironment env, ModelLoadContext c
 
             // *** Binary format ***
             // model: _calibrator
+            // scoreColumnName: _scoreColumnName
             ctx.LoadModel<TICalibrator, SignatureLoadModel>(env, out _calibrator, "Calibrator");
+            _scoreColumnName = ctx.LoadString();
```
Comment (antoniovs1029) [inline src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs:193]: I think this will fail if we load Calibrators that we serialized before your changes, because they won't include the new `scoreColumnName` string. This needs to be fixed by optionally reading the new string, depending on the value on `ctx.Header.ModelVerWritten`. E.g. in the same way we load text loaders:

https://github.com/dotnet/machinelearning/blob/709ec020b702fe69e0dcbf87fbcb538bea0af7b7/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1459-L1469

Adding a backward compatibility test with _at least_ one kind of calibrator would also be useful to ensure they are loaded correctly :wink:

File: test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs [hunk 3]
```diff
@@ -137,5 +137,101 @@ private sealed class CalibratorTestData
             }
         }
 
+        /// <summary>
+        /// Test to confirm calibrator estimators work with classes
+        /// where order of label and score columns are reversed, and
+        /// where 
+        /// </summary>
```
Comment (antoniovs1029) [inline test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs:144]: nit: the summary seems incomplete

File: test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs [hunk 4]
```diff
@@ -137,5 +137,101 @@ private sealed class CalibratorTestData
...
+        [Fact]
+        public void TestNonStandardCalibratorEstimatorClasses()
+        {
+            var mlContext = new MLContext(0);
+            // Store different possible variations of calibrator data classes.
```
Comment (antoniovs1029) [inline test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs:149]: (pinned to text to allow for threaded discussion)

On issue #4700 I mention that Onnx tests are also necessary to test that Onnx conversion works also with a non-default Score name. A quick look makes me thing that it won't be necessary to change anything in the onnx conversion logic to work with the new `scoreColumnName` parameter, so simply adding a test will do.

The test would belong here:
https://github.com/dotnet/machinelearning/blob/709ec020b702fe69e0dcbf87fbcb538bea0af7b7/test/Microsoft.ML.Tests/OnnxConversionTest.cs#L316-L331

File: src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs [hunk 5]
```diff
@@ -227,18 +234,20 @@ private sealed class Mapper<TCalibrator> : MapperBase, ISaveAsOnnx
...
             {
                 _calibrator = calibrator;
                 _parent = parent;
 
-                _scoreColIndex = inputSchema.GetColumnOrNull(DefaultColumnNames.Score)?.Index ?? -1;
+                _scoreColumnName = scoreColumnName;
+                _scoreColIndex = inputSchema.GetColumnOrNull(_scoreColumnName)?.Index ?? -1;
 
-                parent.Host.Check(_scoreColIndex > 0, "The data to calibrate contains no 'Score' column");
+                parent.Host.Check(_scoreColIndex >= 0, "The data to calibrate contains no 'Score' column");
```
Comment (antoniovs1029) [inline src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs:250]: Nit: change the check message to be "The data to calibrate contains no {scoreColumnName} column"

File: test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs (hunk 4 above)
Comment (mstfbl) [reply test/Microsoft.ML.Tests/TrainerEstimators/CalibratorEstimators.cs:150]: I agree, and have added on to `PlattCalibratorOnnxConversionTest2` testing Onnx Conversion with a non-default Score column name for a Platt Calibrator. I will add other Onnx Conversion unit tests for other calibrators in a future PR.

File: src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs (hunk 2 above)
Comment (mstfbl) [reply src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs]: Added!

File: src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs [hunk 6]
```diff
@@ -247,7 +254,7 @@ private sealed class Mapper<TCalibrator> : MapperBase, ISaveAsOnnx
                 _scoreColumnName = scoreColumnName;
                 _scoreColIndex = inputSchema.GetColumnOrNull(_scoreColumnName)?.Index ?? -1;
 
-                parent.Host.Check(_scoreColIndex >= 0, "The data to calibrate contains no 'Score' column");
+                parent.Host.Check(_scoreColIndex >= 0, @"The data to calibrate contains no \'{scoreColumnName}\' column");
```
Comment (antoniovs1029) [inline src/Microsoft.ML.Data/Prediction/CalibratorCatalog.cs:257]: nit: maybe you meant "$" instead of "@"?

image
