### PR TITLE
Fix column purpose for PipelineSweeperMacro

### LINKED ISSUE #460: PipelineSweeperMacro incorrect column purpose inference
PipelineSweeperMacro tries to infer the Purpose of the columns in the data-set, and then generates the parameter space to sweep over.  

For several datasets, it infers the purpose incorrectly e.g.  for some datasets, the PipelineSweeperMacro ended up using the label column as a feature.  There is currently no way for the user to override this behavior.  

The proposal is to add arguments to the PipelineSweeperMacro, corresponding to the intended purpose for a particular column.  Purpose inference will be done only on columns which were not specified by the user.

### PR DESCRIPTION
**Pull request by agoswamiazureml**
Fixes #460 

- Adding arguments to the PipelineSweeperMacro.  Users will be able to specify the columns for a particular purpose.  
- Updating the methods in the PurposeInference and TransformInference classes to pass the user provided column purposes as optional arguments.
- Added unit tests for the sweeping engines we have currently (Defaults, Rocket, UniformRandom)

### CODE REVIEW

**Comment by agoswamiazureml** [comment]
@yaeldekel . Could you kindly take a look at this PR ?

File: test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs [hunk 1]
```diff
@@ -272,6 +272,247 @@ public void EntryPointPipelineSweep()
...
+            runner.SetInput("TrainingData", datasetTrain);
+            runner.SetInput("TestingData", datasetTest);
+            runner.RunAll();
+
+            var autoMlState = runner.GetOutput<AutoInference.AutoMlMlState>("StateOut");
+            Assert.NotNull(autoMlState);
+            var allPipelines = autoMlState.GetAllEvaluatedPipelines();
+            var bestPipeline = autoMlState.GetBestPipeline();
+            Assert.Equal(allPipelines.Length, numIterations);
+            Assert.True(bestPipeline.PerformanceSummary.MetricValue > 0.87);
```
Comment (justinormont) [inline test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs]: I'd recommend a range. Perhaps 87-89?

In the future, we may cause a Label to be leaked, and I'd like that caught.

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 2]
```diff
@@ -370,19 +371,21 @@ public void UpdateTerminator(ITerminator terminator)
                 TransformInference.SuggestedTransform[] existingTransforms = null)
             {
                 // Infer transforms using experts
-                var levelTransforms = TransformInference.InferTransforms(_env, data, args);
+                var levelTransforms = TransformInference.InferTransforms(_env, data, args, this._columnPurpose);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: >this [](start = 91, length = 4)

we tend to omit usage of "this" word.

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs [hunk 3]
```diff
@@ -36,6 +36,33 @@ public sealed class Arguments
 
             [Argument(ArgumentType.AtMostOnce, HelpText = "Output datasets from previous iteration of sweep.", SortOrder = 7, Hide = true)]
             public IDataView[] CandidateOutputs;
+
+            [Argument(ArgumentType.MultipleUnique, HelpText = "Column(s) to use as purpose 'Ignore'", SortOrder = 8, Hide = true)]
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: >Hide = true [](start = 117, length = 11)

why you hide them?

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs [hunk 4]
```diff
@@ -98,6 +186,9 @@ public static Output ExtractSweepResult(IHostEnvironment env, ResultInput input)
                 "Must have a valid AutoML State, or pass arguments to create one.");
             env.Check(input.BatchSize > 0, "Batch size must be > 0.");
 
+            // Get the user-defined column purposes (if any)
+            var columnPurpose = SetColumnPurpose(env, input);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: >SetColumnPurpose [](start = 32, length = 16)

as you mention in comment you use this method to "Get' purposes, so it's better to name this method GetColumnPurpose

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 5]
```diff
@@ -536,7 +539,26 @@ public PipelinePattern[] GetNextCandidates(int numberOfCandidates)
...
+                using (var ch = h.Start("GetNextCandidates"))
+                {
+                    foreach (var pipeline in BatchCandidates)
+                    {
+                        ch.Info("AutoInference Suggested Transforms.");
+                        int transformK = 0;
+                        foreach (var transform in pipeline.Transforms)
+                        {
+                            transformK += 1;
+                            ch.Info($"Transform {transformK} : {transform.Transform.ToString()}");
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: >.ToString() [](start = 83, length = 11)

i'm not sure you need to call ToString here.

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 6]
```diff
@@ -536,7 +539,26 @@ public PipelinePattern[] GetNextCandidates(int numberOfCandidates)
                 var currentBatchSize = numberOfCandidates;
                 if (_terminator is IterationTerminator itr)
                     currentBatchSize = Math.Min(itr.RemainingIterations(_history), numberOfCandidates);
-                BatchCandidates = AutoMlEngine.GetNextCandidates(_sortedSampledElements.Select(kvp => kvp.Value), currentBatchSize);
+                BatchCandidates = AutoMlEngine.GetNextCandidates(
+                    _sortedSampledElements.Select(kvp => kvp.Value), 
+                    currentBatchSize,
+                    this._columnPurpose);
+
+                var h = _env.Register("AutoMlMlState");
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: > var h = _env.Register("AutoMlMlState"); [](start = 15, length = 40)

you should have _host field, no reason to create new host variable.

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 7]
```diff
@@ -536,7 +539,26 @@ public PipelinePattern[] GetNextCandidates(int numberOfCandidates)
...
+                using (var ch = h.Start("GetNextCandidates"))
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: >GetNextCandidates [](start = 41, length = 17)

Print suggested transforms?

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 8]
```diff
@@ -536,7 +539,26 @@ public PipelinePattern[] GetNextCandidates(int numberOfCandidates)
...
+                {
+                    foreach (var pipeline in BatchCandidates)
+                    {
+                        ch.Info("AutoInference Suggested Transforms.");
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: >AutoInference Suggested Transforms. [](start = 33, length = 35)

either add pipeline identification, or remove it, what's  the point to repeat same phrase all the time?

File: src/Microsoft.ML.PipelineInference/PurposeInference.cs [hunk 9]
```diff
@@ -318,8 +318,10 @@ private static IEnumerable<IPurposeInferenceExpert> GetExperts()
         /// <param name="data">The data to use for inference.</param>
         /// <param name="columnIndices">Indices of columns that we're interested in.</param>
         /// <param name="args">Additional arguments to inference.</param>
+        /// <param name="columnPurpose">(Optional) User defined mapping of Column to Purpose.</param>
         /// <returns>The result includes the array of auto-detected column purposes.</returns>
-        public static InferenceResult InferPurposes(IHostEnvironment env, IDataView data, IEnumerable<int> columnIndices, Arguments args)
+        public static InferenceResult InferPurposes(IHostEnvironment env, IDataView data, IEnumerable<int> columnIndices, Arguments args,
+            Dictionary<string, ColumnPurpose> columnPurpose = null)
```
Comment (sfilipi) [inline src/Microsoft.ML.PipelineInference/PurposeInference.cs]: >Dictionary<string, ColumnPurpose> columnPurpose = null [](start = 12, length = 54)

Why is this needed here? Should we intersect the result of this, with the purposes we have, in the places that call this?

File: test/BaselineOutput/Common/EntryPoints/core_manifest.json [hunk 10]
```diff
@@ -2727,6 +2727,114 @@
...
+            "ItemType": "String"
+          },
+          "Desc": "Column(s) to use as purpose 'Label'",
+          "Required": false,
+          "SortOrder": 10.0,
+          "IsNullable": false,
+          "Default": null
+        },
+        {
+          "Name": "NumericFeatureColumn",
```
Comment (sfilipi) [inline test/BaselineOutput/Common/EntryPoints/core_manifest.json]: >NumericFeatureColumn [](start = 19, length = 20)

I'd keep Column plural: NumericFeatureColumns

File: src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs [hunk 11]
```diff
@@ -30,12 +30,13 @@ public UniformRandomEngine(IHostEnvironment env)
             : base(env, env.Register("UniformRandomEngine(AutoML)"))
         {}
 
-        public override PipelinePattern[] GetNextCandidates(IEnumerable<PipelinePattern> history, int numberOfCandidates)
+        public override PipelinePattern[] GetNextCandidates(IEnumerable<PipelinePattern> history, int numberOfCandidates,
+            Dictionary<string, ColumnPurpose> columnPurpose = null)
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: >columnPurpose [](start = 46, length = 13)

any chance you can move them to base class PipelineOptimizerBase so you don't have to pass them around all the time?

File: test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs [hunk 12]
```diff
@@ -272,6 +272,259 @@ public void EntryPointPipelineSweep()
...
+            var inputFileTrain = new SimpleFileHandle(Env, pathData, false, false);
+#pragma warning disable 0618
+            var datasetTrain = ImportTextData.ImportText(Env,
+                new ImportTextData.Input { InputFile = inputFileTrain, CustomSchema = schema }).Data.Take(numOfSampleRows);
+            var inputFileTest = new SimpleFileHandle(Env, pathDataTest, false, false);
+            var datasetTest = ImportTextData.ImportText(Env,
+                new ImportTextData.Input { InputFile = inputFileTest, CustomSchema = schema }).Data.Take(numOfSampleRows);
+#pragma warning restore 0618
+            // Define entrypoint graph
+            string inputGraph = @"
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs]: I know what most of tests written in way of "Create manually json string and execute it", but it doesn't mean it has to be this way.
check TestSimpleExperiment 
any chance I can convince you to use C# classes instead of composing JSON string manually?

File: src/Microsoft.ML.PipelineInference/AutoInference.cs (hunk 2 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoInference.cs]: Thanks Ivan. I will take care of this in the next iteration

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs (hunk 4 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: Thanks Ivan. I will take care of this in the next iteration

File: src/Microsoft.ML.PipelineInference/AutoInference.cs (hunk 6 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoInference.cs]: Thanks Ivan. I will take care of this in the next iteration

File: src/Microsoft.ML.PipelineInference/AutoInference.cs (hunk 7 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoInference.cs]: Thanks Ivan. I will take care of this in the next iteration

File: src/Microsoft.ML.PipelineInference/AutoInference.cs (hunk 2 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoInference.cs]: Fixed

---
In reply to: [199589164](https://github.com/dotnet/machinelearning/pull/461#discussion_r199589164) [](ancestors = 199589164)

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs (hunk 4 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: Fixed

---
In reply to: [199590108](https://github.com/dotnet/machinelearning/pull/461#discussion_r199590108) [](ancestors = 199590108)

File: test/BaselineOutput/Common/EntryPoints/core_manifest.json (hunk 10 above)
Comment (agoswamiazureml) [reply test/BaselineOutput/Common/EntryPoints/core_manifest.json]: Using plural form as suggested

---
In reply to: [199593350](https://github.com/dotnet/machinelearning/pull/461#discussion_r199593350) [](ancestors = 199593350)

File: src/Microsoft.ML.PipelineInference/PurposeInference.cs (hunk 9 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/PurposeInference.cs]: We need it here because we want to first honor the column purpose set by the user -- In line #344 we set the 'SuggestedPurpose' to be what the user provided.  By doing this we ensure the  'Experts' below do not  do purpose inference  (and hence transform inference) on those user provided columns.   Auto inference will only be done on columns  which do not  have user intent 

---
In reply to: [199592844](https://github.com/dotnet/machinelearning/pull/461#discussion_r199592844) [](ancestors = 199592844)

File: src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs (hunk 11 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: For the engines, I have created a field in PipelineOptimizerBase. This reduces some clutter.

Recipes code uses a lot of static classes (with static methods).  For those I have added an additional method 

---
In reply to: [199593664](https://github.com/dotnet/machinelearning/pull/461#discussion_r199593664) [](ancestors = 199593664)

File: src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs [hunk 13]
```diff
@@ -30,8 +30,10 @@ public UniformRandomEngine(IHostEnvironment env)
             : base(env, env.Register("UniformRandomEngine(AutoML)"))
         {}
 
-        public override PipelinePattern[] GetNextCandidates(IEnumerable<PipelinePattern> history, int numberOfCandidates)
+        public override PipelinePattern[] GetNextCandidates(IEnumerable<PipelinePattern> history, int numberOfCandidates,
+            Dictionary<string, ColumnPurpose> colPurpose = null)
```
Comment (TomFinley) [inline src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: >colPurpose [](start = 46, length = 10)

I am somewhat unenthusiastic about this, since it basically seems like role-mappings, except in reverse (which also makes it, incidentally, less capable). Is there any possibility of re-using that concept, rather than inventing another thing that acts more or less just like it?

File: src/Microsoft.ML.PipelineInference/Interfaces/IPipelineOptimizer.cs [hunk 14]
```diff
@@ -44,6 +45,7 @@ public abstract class PipelineOptimizerBase : IPipelineOptimizer
         protected IDataView OriginalData;
         protected IDataView FullyTransformedData;
         protected AutoInference.DependencyMap DependencyMapping;
+        protected Dictionary<string, ColumnPurpose> columnPurpose;
```
Comment (TomFinley) [inline src/Microsoft.ML.PipelineInference/Interfaces/IPipelineOptimizer.cs]: >columnPurpose; [](start = 52, length = 14)

C# naming conventions, please.

File: src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs (hunk 13 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: It seems the 'recipe framework'  added the concept of  'Purpose'.  Not quite sure why the decision was made at that time to  introduce Purpose as an additional concept,   instead of re-using the  concept of Roles and extending it.

<snip>
    public enum ColumnPurpose
    {
        Ignore = 0,
        Name = 1,
        Label = 2,
        NumericFeature = 3,
        CategoricalFeature = 4,
        TextFeature = 5,
        Weight = 6,
        GroupId = 7,
        ImagePath = 8
    }
</snip>

Is there a simple way to extend Roles to include purpose (e.g. 'TextFeature', 'Ignore')  ?  My understanding is that  it would be a bigger change  that warrants a separate design / PR.   

---
In reply to: [199661532](https://github.com/dotnet/machinelearning/pull/461#discussion_r199661532) [](ancestors = 199661532)

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs (hunk 3 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: Any thoughts on what's the implication of the 'Hide' argument for a Macro?  Wasn't clear to me.

---
In reply to: [199589626](https://github.com/dotnet/machinelearning/pull/461#discussion_r199589626) [](ancestors = 199589626)

File: test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs (hunk 12 above)
Comment (agoswamiazureml) [reply test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs]: I added a 4th test case which follows this paradigm.  Does it look good ?  

The other 3 tests I would like to keep as is if possible

---
In reply to: [199594792](https://github.com/dotnet/machinelearning/pull/461#discussion_r199594792) [](ancestors = 199594792)

File: src/Microsoft.ML.PipelineInference/Interfaces/IPipelineOptimizer.cs (hunk 14 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/Interfaces/IPipelineOptimizer.cs]: Fixed.

---
In reply to: [199662160](https://github.com/dotnet/machinelearning/pull/461#discussion_r199662160) [](ancestors = 199662160)

File: src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs (hunk 13 above)
Comment (TomFinley) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: You don't extend roles, you simply use them. If you want to introduce roles appropriate for your task, that is totally fine and supported. I wonder though if the issue is that you do not have an actual `ISchema` implementation we're working on?

Comment (sfilipi) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: Is ColumnPurpose and Roles the same things? Feels to me they are not. There is a ColumnPurpose of "Date" but not such a Role, and Justin has ideas about adding more purposes. Purposes would be used to just communicate to Experts what transforms to suggest for the pipelines. Learners would not neccessarly need to know about them. 

---
In reply to: [200406010](https://github.com/dotnet/machinelearning/pull/461#discussion_r200406010) [](ancestors = 200406010)

Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: I don't think we have the actual ISchema implementation we're working on. AutoInference (aka Recipes) uses ColumnPurpose to get to there.  

---
In reply to: [200410413](https://github.com/dotnet/machinelearning/pull/461#discussion_r200410413) [](ancestors = 200410413,200406010)

Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: RecipeInference  uses  ColumnPurpose to get to the  Role-mappings.  

In the GUI users can modify the ColumnPurpose through the wizard.  We are adding arguments to the Macro so users can do the same when using the macro programmatically. 

@tfinley@gmail.com . Is the suggestion to completely do away with the notion of ColumnPurpose ?

---
In reply to: [200410413](https://github.com/dotnet/machinelearning/pull/461#discussion_r200410413) [](ancestors = 200410413,200406010)

Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/AutoMlEngines/UniformRandomEngine.cs]: Made a couple of changes to address this:
- Dropped ‘Ignore’  from Arguments to the PipelineSweepMacro.
- Using RoleMappedData in the API   (not exposing ColumnPurpose anymore in the APIs)


---
In reply to: [200723741](https://github.com/dotnet/machinelearning/pull/461#discussion_r200723741) [](ancestors = 200723741,200410413,200406010)

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs [hunk 15]
```diff
@@ -36,6 +36,30 @@ public sealed class Arguments
...
+            public string[] NumericFeatureColumns;
+
+            [Argument(ArgumentType.MultipleUnique, HelpText = "Column(s) to use as Role 'CategoricalFeature'", SortOrder = 13)]
+            public string[] CategoricalFeatureColumns;
+
+            [Argument(ArgumentType.MultipleUnique, HelpText = "Column(s) to use as Role 'TextFeature'", SortOrder = 14)]
+            public string[] TextFeatureColumns;
+
+            [Argument(ArgumentType.MultipleUnique, HelpText = "Column(s) to use as Role 'ImagePath'", SortOrder = 15)]
+            public string[] ImagePathColumns;
```
Comment (sfilipi) [inline src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: Shall we also log a bug about finding a more scalable solution?

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs [hunk 16]
```diff
@@ -88,6 +112,77 @@ public static Output ExtractSweepResult(IHostEnvironment env, ResultInput input)
             return new Output { Results = outputView, State = autoMlState };
         }
 
+        private static RoleMappedData GetDataRoles(IHostEnvironment env, Arguments input)
+        {
+            var roles = new List<KeyValuePair<RoleMappedSchema.ColumnRole, string>>();
+
+            if (input.LabelColumns != null)
```
Comment (sfilipi) [inline src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: >if (input.LabelColumns != null) [](start = 12, length = 31)

would you want to make specifying  this mandatory?

Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: one scenario that needs to be supported is  when user does not specify anything.  in that case case  we will do AutoInference on all columns.  

That's why these arguments (including Label) are not mandatory.   These arguments are meant to give user  the ability to override  the auto inference   (if needed)

---
In reply to: [202428925](https://github.com/dotnet/machinelearning/pull/461#discussion_r202428925) [](ancestors = 202428925)

File: src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs (hunk 15 above)
Comment (agoswamiazureml) [reply src/Microsoft.ML.PipelineInference/Macros/PipelineSweeperMacro.cs]: Yes, there is a bug for that already

---
In reply to: [202428704](https://github.com/dotnet/machinelearning/pull/461#discussion_r202428704) [](ancestors = 202428704)
