### PR TITLE
Make Multiclass Linear Trainers Typed Based on Output Model Types.

### LINKED ISSUE #1100: Getting SDCA multiclass weights requires using a MulticlassLogisticRegressionPredictor, which is strange
As shown [here](https://github.com/dotnet/machinelearning/blob/3cdd3c8b32705e91dcf46c429ee34196163af6da/test/Microsoft.ML.StaticPipelineTesting/Training.cs#L268), getting the predictor weights from multiclass-SDCA requires using `MulticlassLogisticRegressionPredictor`. This is counter-intuitive as I would expect that predictor to be used just for Logistic Regression. Perhaps something more general like `MulticlassLinearPredictor` should be created/used?

### PR DESCRIPTION
**Pull request by wschin**
Multiclass SDCA can train multi-class SVM but it always outputs multi-class logistic regression model. This is not correct because we should not apply softmax to SVM model.

To fix #1100, we got the following working items.
- [x] Clean code.
- [x] Create two multi-class linear models.
- [x] Make multiclass SDCA trainers typed.
- [x] Give the two new model classes better.

Framework changes:
- LogisticRegressionMulticlassClassificationTrainer (renamed to) ---> LbfgsMaximumEntropyTrainer 
- MulticlassLogisticRegressionModelParameters (refactorized to) ---> MaximumEntropyModelParameters (for multi-class LR) and LinearMulticlassModelParametersBase (for uncalibrated cases). The two new classes are also derived from LinearMulticlassModelParametersBase. MulticlassLogisticRegressionModelParameters.
- SdcaMulticlassClassificationTrainer (refactorized to) ---> SdcaMulticlassClassificationTrainer and SdcaNonCalibratedMulticlassClassificationTrainer. These two new classes' are derived from SdcaMulticlassClassificationTrainerBase.

API changes:
- (rename, static API) MulticlassLogisticRegression ---> LbfgsMaximumEntropy
- (rename, dynamic API) LogisticRegression ---> LbfgsMaximumEntropy
- (add, static API) SdcaNonCalibrated for multi-class linear models without calibration.
- (add, dynamic API) SdcaNonCalibrated for multi-class linear models without calibration.

### CODE REVIEW

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 1]
```diff
@@ -993,35 +949,282 @@ DataViewRow ICanGetSummaryAsIRow.GetSummaryIRowOrNull(RoleMappedSchema schema)
...
+        internal const string LoaderSignature = "MulticlassLinear";
+        internal const string RegistrationName = "MulticlassLinearPredictor";
+
+        private static VersionInfo VersionInfo =>
+            new VersionInfo(
+                modelSignature: "MCLINEAR",
+                // verWrittenCur: 0x00010001, // Initial
+                // verWrittenCur: 0x00010002, // Added class names
+                verWrittenCur: 0x00010003, // Added model stats
+                verReadableCur: 0x00010001,
```
Comment (TomFinley) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: As far as I know this is a new model type. Why is this not the initial version?

Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Thanks for pointing this out. Just fixed it.

---
In reply to: [266553016](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266553016) [](ancestors = 266553016)

File: test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs [hunk 2]
```diff
@@ -171,7 +171,7 @@ private ITransformer TrainOnIris(string irisDataPath)
             var trainedModel = pipeline.Fit(trainData);
 
             // Inspect the model parameters. 
-            var modelParameters = trainedModel.LastTransformer.Model as MulticlassLogisticRegressionModelParameters;
+            var modelParameters = trainedModel.LastTransformer.Model as MaximumEntropyModelParameters;
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs]: >MaximumEntropyModelParameters [](start = 72, length = 29)

obligatory "Update md file" comment

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 3]
```diff
@@ -298,6 +297,36 @@ public static class StandardTrainersCatalog
...
+        /// <param name="featureColumnName">The name of the feature column.</param>
+        /// <param name="exampleWeightColumnName">The name of the example weight column (optional).</param>
+        /// <param name="loss">Loss function to be minimized. Defaults to <see cref="LogLoss"/> if not specified.</param>
+        /// <param name="l2Regularization">The L2 <a href='tmpurl_regularization'>regularization</a> hyperparameter.</param>
+        /// <param name="l1Threshold">The L1 <a href='tmpurl_regularization'>regularization</a> hyperparameter. Higher values will tend to lead to more sparse model.</param>
+        /// <param name="maximumNumberOfIterations">The maximum number of passes to perform over the data.</param>
+        /// <example>
+        /// <format type="text/markdown">
+        /// <![CDATA[
+        ///  [!code-csharp[SDCA](~/../docs/samples/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/StochasticDualCoordinateAscent.cs)]
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: >StochasticDualCoordinateAscent [](start = 127, length = 30)

Should you add new sample file for non calibrated version?

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 4]
```diff
@@ -20,25 +20,28 @@
...
 namespace Microsoft.ML.Trainers
 {
     /// <include file = 'doc.xml' path='doc/members/member[@name="LBFGS"]/*' />
     /// <include file = 'doc.xml' path='docs/members/example[@name="LogisticRegressionClassifier"]/*' />
-    public sealed class LogisticRegressionMulticlassClassificationTrainer : LbfgsTrainerBase<LogisticRegressionMulticlassClassificationTrainer.Options,
-        MulticlassPredictionTransformer<MulticlassLogisticRegressionModelParameters>, MulticlassLogisticRegressionModelParameters>
+    public sealed class LbfgsMaximumEntropyTrainer : LbfgsTrainerBase<LbfgsMaximumEntropyTrainer.Options,
+        MulticlassPredictionTransformer<MaximumEntropyModelParameters>, MaximumEntropyModelParameters>
     {
+        internal const string Summary = "Logistic Regression is a method in statistics used to predict the probability of occurrence of an event and can be used as a classification algorithm.The algorithm predicts the probability of occurrence of an event by fitting data to a logistical function.";
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: space

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: I don't want to touch too many those APIs as they are being renamed and moved.

---
In reply to: [266641719](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266641719) [](ancestors = 266641719)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 5]
```diff
@@ -908,46 +866,46 @@ bool ISingleCanSaveOnnx.SaveAsOnnx(OnnxContext ctx, string[] outputs, string fea
...
+
+        /// <summary>
+        /// Gets the biases for the logistic regression predictor.
+        /// </summary>
+        public IEnumerable<float> GetBiases()
+        {
+            return Biases;
         }
 
         internal IEnumerable<float> DenseWeightsEnumerable()
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Not exactly related to your PR, but I found it strange what we expose weights and Bias(es) differently for binary and multiclass model.

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 6]
```diff
@@ -993,35 +951,280 @@ DataViewRow ICanGetSummaryAsIRow.GetSummaryIRowOrNull(RoleMappedSchema schema)
...
+        }
+
+        /// <summary>
+        /// This function applies softmax to <paramref name="dst"/>. For details about softmax, see https://en.wikipedia.org/wiki/Softmax_function.
+        /// </summary>
+        /// <param name="dst">Score vector should be calibrated.</param>
+        private protected override void Calibrate(Span<float> dst)
+        {
+            Host.Assert(dst.Length >= NumberOfClasses);
+
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Why is `dst.Lenght> NumberOfClasses` is ok?

File: test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs (hunk 2 above)
Comment (wschin) [reply test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs]: Will do now! Thanks.

---
In reply to: [266639456](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266639456) [](ancestors = 266639456)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 4 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Ok.

---
In reply to: [266642838](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266642838) [](ancestors = 266642838)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 6 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Fixed.

---
In reply to: [266662595](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266662595) [](ancestors = 266662595)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 5 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: The reason behind is that those parameters got one extra dimension. In binary, the bias is a scalar but in multiclass, the bias is a vector with #-of-class elements.

---
In reply to: [266661678](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266661678) [](ancestors = 266661678)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 7]
```diff
@@ -19,25 +19,28 @@
...
+[assembly: LoadableClass(typeof(void), typeof(LbfgsMaximumEntropyTrainer), null, typeof(SignatureEntryPointModule), LbfgsMaximumEntropyTrainer.LoadNameValue)]
 
 namespace Microsoft.ML.Trainers
 {
     /// <include file = 'doc.xml' path='doc/members/member[@name="LBFGS"]/*' />
     /// <include file = 'doc.xml' path='docs/members/example[@name="LogisticRegressionClassifier"]/*' />
-    public sealed class LogisticRegressionMulticlassClassificationTrainer : LbfgsTrainerBase<LogisticRegressionMulticlassClassificationTrainer.Options,
-        MulticlassPredictionTransformer<MulticlassLogisticRegressionModelParameters>, MulticlassLogisticRegressionModelParameters>
+    public sealed class LbfgsMaximumEntropyTrainer : LbfgsTrainerBase<LbfgsMaximumEntropyTrainer.Options,
```
Comment (abgoswam) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Can we have prefix match between the Trainer  and ModelParameter  class ?

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 8]
```diff
@@ -546,9 +596,9 @@ public static PoissonRegressionTrainer PoissonRegression(this RegressionCatalog.
         /// <param name="enforceNonNegativity">Enforce non-negative weights.</param>
         /// <param name="l1Regularization">Weight of L1 regularization term.</param>
         /// <param name="l2Regularization">Weight of L2 regularization term.</param>
-        /// <param name="historySize">Memory size for <see cref="Microsoft.ML.Trainers.LogisticRegressionMulticlassClassificationTrainer"/>. Low=faster, less accurate.</param>
+        /// <param name="historySize">Memory size for <see cref="Microsoft.ML.Trainers.LbfgsMaximumEntropyTrainer"/>. Low=faster, less accurate.</param>
         /// <param name="optimizationTolerance">Threshold for optimizer convergence.</param>
-        public static LogisticRegressionMulticlassClassificationTrainer LogisticRegression(this MulticlassClassificationCatalog.MulticlassClassificationTrainers catalog,
+        public static LbfgsMaximumEntropyTrainer LbfgsMaximumEntropy(this MulticlassClassificationCatalog.MulticlassClassificationTrainers catalog,
```
Comment (abgoswam) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: Its great we are following convention of having prefix match with the name of Trainer

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 7 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: This is not the only trainer that will produce MaximumEntropyTrainer.. Please consider this trainer and the associated model separately. Otherwise, every trainer which produces linear model should be called LinearModelTrainer.

---
In reply to: [266683935](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266683935) [](ancestors = 266683935)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 3 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: Then don't add example? I don't know how our documentation people track their work, but looks like it has everything it's needed, but in reality it's not.

---
In reply to: [266650832](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266650832) [](ancestors = 266650832,266641719)

Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: They have it now in Iteration 7.

---
In reply to: [266987401](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266987401) [](ancestors = 266987401,266650832,266641719)

File: src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs [hunk 9]
```diff
@@ -412,34 +413,131 @@ private protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape
...
+
+    /// <summary>
+    /// The <see cref="IEstimator{TTransformer}"/> for training a multiclass linear model using the stochastic dual coordinate ascent method.
+    /// The trained model <see cref="LinearMulticlassModelParameters"/> does not produces probabilities of classes, but we can still make decisions
+    /// by choosing the class associated with the largest score.
+    /// </summary>
+    /// <include file='doc.xml' path='doc/members/member[@name="SDCA_remarks"]/*' />
+    public sealed class SdcaNonCalibratedMulticlassClassificationTrainer : SdcaMulticlassClassificationTrainerBase<LinearMulticlassModelParameters>
+    {
+        public class Options : CommonOptions
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs]: >public class Options [](start = 8, length = 20)

sealed?

File: src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs [hunk 10]
```diff
@@ -412,34 +413,131 @@ private protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape
...
+    }
+
+    /// <summary>
+    /// The <see cref="IEstimator{TTransformer}"/> for training a maximum entropy classification model using the stochastic dual coordinate ascent method.
+    /// The trained model <see cref="MaximumEntropyModelParameters"/> produces probabilities of classes.
+    /// </summary>
+    /// <include file='doc.xml' path='doc/members/member[@name="SDCA_remarks"]/*' />
+    public sealed class SdcaMulticlassClassificationTrainer : SdcaMulticlassClassificationTrainerBase<MaximumEntropyModelParameters>
+    {
+        public class Options : CommonOptions
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs]: >public class Options  [](start = 8, length = 21)

sealed?

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: This PR fixes a big wrong thing I have been doing for years. I personally consider example is rather less important.

---
In reply to: [266987401](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266987401) [](ancestors = 266987401,266650832,266641719)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 11]
```diff
@@ -992,35 +950,280 @@ DataViewRow ICanGetSummaryAsIRow.GetSummaryIRowOrNull(RoleMappedSchema schema)
...
+            ctx.CheckAtModel(VersionInfo);
+            return new LinearMulticlassModelParameters(env, ctx);
+        }
 
-            return TrainerEntryPointsUtils.Train<LogisticRegressionMulticlassClassificationTrainer.Options, CommonOutputs.MulticlassClassificationOutput>(host, input,
-                () => new LogisticRegressionMulticlassClassificationTrainer(host, input),
-                () => TrainerEntryPointsUtils.FindColumn(host, input.TrainingData.Schema, input.LabelColumnName),
-                () => TrainerEntryPointsUtils.FindColumn(host, input.TrainingData.Schema, input.ExampleWeightColumnName));
+        /// <summary>
+        /// Output the text model to a given writer
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: > Output the text model to a given writer [](start = 11, length = 40)

nit: dot in the end of sentence for all this comments in file.

File: test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs [hunk 12]
```diff
@@ -130,5 +130,74 @@ public void SdcaSupportVectorMachine()
...
+            // We set the "Label" column as the label of the dataset, and the "Features" column as the features column.
+            var pipeline = mlContext.Transforms.Conversion.MapValueToKey("LabelIndex", "Label").
+                Append(mlContext.MulticlassClassification.Trainers.SdcaNonCalibrated(labelColumnName: "LabelIndex", featureColumnName: "Features", loss: new HingeLoss(), l2Regularization: 0.001f));
+
+            // Step 3: Train the pipeline created.
+            var model = pipeline.Fit(data);
+
+            // Step 4: Make prediction and evaluate its quality (on training set).
+            var prediction = model.Transform(data);
+            var metrics = mlContext.MulticlassClassification.Evaluate(prediction, label: "LabelIndex", topK: 1);
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs]: >label [](start = 82, length = 5)

unrelated to your PR, but wonder, why it's label and not labelColumnName.

Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs]: >label [](start = 82, length = 5)

I think @artidoro rename them to labelColumnName in his latest PR.

File: src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs (hunk 9 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs]: Sure. Thanks.

---
In reply to: [266991181](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266991181) [](ancestors = 266991181)

File: src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs (hunk 10 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/SdcaMulticlass.cs]: Sure. Thanks.

---
In reply to: [266991361](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266991361) [](ancestors = 266991361)

File: test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs (hunk 12 above)
Comment (wschin) [reply test/Microsoft.ML.Tests/TrainerEstimators/SdcaTests.cs]: Merged with master. Thanks.

---
In reply to: [266997235](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266997235) [](ancestors = 266997235)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 11 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Thanks. I just checked both of this file and SdcaMulticlass.cs.

---
In reply to: [266993940](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266993940) [](ancestors = 266993940)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 13]
```diff
@@ -308,11 +337,32 @@ public static class StandardTrainersCatalog
...
+        /// </summary>
+        /// <param name="catalog">The multiclass classification catalog trainer object.</param>
+        /// <param name="options">Trainer options.</param>
+        /// <example>
+        /// <format type="text/markdown">
+        /// <![CDATA[
+        ///  [!code-csharp[SDCA](~/../docs/samples/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/MulticlassClassification/StochasticDualCoordinateAscentWithOptions.cs)]
+        /// ]]></format>
+        /// </example>
+        public static SdcaCalibratedMulticlassTrainer SdcaCalibrated(this MulticlassClassificationCatalog.MulticlassClassificationTrainers catalog,
```
Comment (artidoro) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: >SdcaCalibratedMulticlassTrainer [](start = 22, length = 31)

nit: if you are doing another iteration, would be great if you keep the two extensions for `SdcaCalibratedMulticlassTraniner` one after the other.

**Comment by artidoro** [comment]
>         public static LogisticRegressionBinaryTrainer LogisticRegression(this BinaryClassificationCatalog.BinaryClassificationTrainers catalog,

Can we drop the `Binary` from `LogisticRegressionBInaryTrainer`?

---
Refers to: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs:519 in 63b46cb. [](commit_id = 63b46cb79d0512564327f5b2d384b682b826e1b3, deletion_comment = False)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 14]
```diff
@@ -537,7 +587,7 @@ public static PoissonRegressionTrainer PoissonRegression(this RegressionCatalog.
         }
 
         /// <summary>
-        /// Predict a target using a linear multiclass classification model trained with the <see cref="LogisticRegressionMulticlassClassificationTrainer"/> trainer.
+        /// Predict a target using a linear multiclass classification model trained with the <see cref="LbfgsMaximumEntropyTrainer"/> trainer.
         /// </summary>
```
Comment (artidoro) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: Do you think it's worth it to add a few words saying that this is the multi class extension of logistic regression? (here and below)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs [hunk 15]
```diff
@@ -992,35 +950,280 @@ DataViewRow ICanGetSummaryAsIRow.GetSummaryIRowOrNull(RoleMappedSchema schema)
...
+                    schema,
+                    "score[" + i.ToString() + "]");
+            }
+
+            writer.WriteLine(string.Format("var softmax = MathUtils.SoftMax(scores.AsSpan(0, {0}));", NumberOfClasses));
+            for (int c = 0; c < Biases.Length; c++)
+                writer.WriteLine("output[{0}] = Math.Exp(scores[{0}] - softmax);", c);
+        }
+
+        private protected override bool SaveAsOnnxCore(OnnxContext ctx, string[] outputs, string featureColumn)
```
Comment (artidoro) [inline src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: >SaveAsOnnxCore [](start = 40, length = 14)

It looks like the following three methods are very similar, if not the same, for `LinearMulticlassModelParameters` and `MaximumEntropyModelParameters`.
Can they be refactored in the base class?

**Comment by wschin** [comment]
>         public static LogisticRegressionBinaryTrainer LogisticRegression(this BinaryClassificationCatalog.BinaryClassificationTrainers catalog,

I need to do it in another PR if you really want. It will cause another batch of conflicts and is not related to this issue.

---
In reply to: [474542216](https://github.com/dotnet/machinelearning/pull/2976#issuecomment-474542216) [](ancestors = 474542216)

---
Refers to: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs:519 in 63b46cb. [](commit_id = 63b46cb79d0512564327f5b2d384b682b826e1b3, deletion_comment = False)

**Comment by artidoro** [comment]
>         public static LogisticRegressionBinaryTrainer LogisticRegression(this BinaryClassificationCatalog.BinaryClassificationTrainers catalog,

Ok, sounds good! 

---
In reply to: [474562462](https://github.com/dotnet/machinelearning/pull/2976#issuecomment-474562462) [](ancestors = 474562462,474542216)

---
Refers to: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs:519 in 63b46cb. [](commit_id = 63b46cb79d0512564327f5b2d384b682b826e1b3, deletion_comment = False)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 14 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: It will become
```csharp
/// Predict a target using a maximum entropy classification model trained with the L-BFGS method implemented in <see cref="LbfgsMaximumEntropyTrainer"/>.
```


---
In reply to: [267062024](https://github.com/dotnet/machinelearning/pull/2976#discussion_r267062024) [](ancestors = 267062024)

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs (hunk 13 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: Will fix it in next iteration.

---
In reply to: [267060562](https://github.com/dotnet/machinelearning/pull/2976#discussion_r267060562) [](ancestors = 267060562)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 15 above)
Comment (wschin) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Done. Thanks.

---
In reply to: [267075643](https://github.com/dotnet/machinelearning/pull/2976#discussion_r267075643) [](ancestors = 267075643)

File: src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs (hunk 5 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.StandardTrainers/Standard/LogisticRegression/MulticlassLogisticRegression.cs]: Which is weird.
NumClasses should be property of the model, bias and weights should be IReadonly<float> etc, but all this is out of scope of this PR:)

---
In reply to: [266668443](https://github.com/dotnet/machinelearning/pull/2976#discussion_r266668443) [](ancestors = 266668443,266661678)
