### PR TITLE
Pass fold index to cross validation metrics.

### LINKED ISSUE #570: CrossValidation RegressionMetrics has two more entries than number of folds
I might be incorrect on this, but wouldn't the number of `RegressionMetrics` be the same as the number of folds specified in the `CrossValidator`?

### System information
- Windows 10
- **.NET Version (eg., dotnet --info)**: 
```
.NET Command Line Tools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.9
  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037
```
### Issue

- **What did you do?**
Ran cross validation against a pipeline.
- **What happened?**
The `RegressionMetrics` count is two more than the number of folds specified.
- **What did you expect?**
The `RegressionMetrics` count to be the same as the number of folds.

### Source code / logs
```csharp
var pipeline = new LearningPipeline
{
    new TextLoader(dataset).CreateFrom<SalaryData>(useHeader: true, separator: ','),
    new ColumnConcatenator("Features", "YearsExperience"),
    new GeneralizedAdditiveModelRegressor()
};

var crossValidator = new CrossValidator()
{
    Kind = MacroUtilsTrainerKinds.SignatureRegressorTrainer,
    NumFolds = 2
};
var crossValidatorOutput = crossValidator.CrossValidate<SalaryData, SalaryPrediction>(pipeline);

crossValidatorOutput.RegressionMetrics.ForEach(m => Console.WriteLine(m.Rms));
```

2018-07-20 14_44_23-clipboard

2018-07-20 14_45_12-clipboard

Looking at `sklearn`, it seems to have the same number of results as the number of folds:

```python
from sklearn.model_selection import cross_val_score

cross_val_score(lin_reg, train_set, train_labels, cv=3)
```

```bash
array([0.96044449, 0.97351702, 0.92777218])
```

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes #570

### CODE REVIEW

File: src/Microsoft.ML/Models/BinaryClassificationMetrics.cs [hunk 1]
```diff
@@ -162,6 +164,12 @@ internal static List<BinaryClassificationMetrics> FromMetrics(IHostEnvironment e
         /// </summary>
         public ConfusionMatrix ConfusionMatrix { get; private set; }
 
+        /// <summary>
+        /// For cross validation gives fold number or standard deviation or average across all metrics.
```
Comment (Zruty0) [inline src/Microsoft.ML/Models/BinaryClassificationMetrics.cs]: >fold number or standard deviation or average across all metrics [](start = 39, length = 63)

let's elaborate, because right now it feels unclear.
Maybe call it 'row tag', and then add a comment that
```
For cross-validation, this is equal to "Fold N" for per-fold metric rows, "Overall" for the average metrics and "STD" for standard deviation.
For non-CV scenarios, this is equal to null.
```
(whatever the actual strings are).
