### PR TITLE
Fixing ModelParameter discrepancies

### LINKED ISSUE #2938: More trainer related naming alignment
Take another pass over the trainers and the model parameter types, and align them, because now we have:

`LogisticRegressionMulticlassClassificationTrainer` but `MulticlassLogisticRegressionModelParameters`. 

I think following the same principles on the ModelParams might make them more relatable; so change `MulticlassLogisticRegressionModelParameters` to `LogisticRegressionMulticlassModelParameters`

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #2938 

- Fixes to the ~7 odd ModelParameter types which were inconsistent  with the  rest of the ModelParameter types

Couple of notes: 

1.  PR follows naming convention  used by other ModelParameter types in the codebase
    - {AlgoName}(optional){TypeOfTask}ModelParameters
    - {TypeOfTask} is added  only when needed to distinguish between `Binary` , `Regression` or `Multiclass`

2. ModelParameter types do not use the word `Classification` in the {TypeOfTask} . PR follows that convention.

EDIT : MulticlassLogisticRegressionModelParameters is being refactored by separate issue #1100 .  SO not fixing that in this PR

### CODE REVIEW

File: src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs [hunk 1]
```diff
@@ -66,7 +66,7 @@ public Arguments()
                             // estimator, as opposed to a regular trainer.
                             var trainerEstimator = new LogisticRegressionMulticlassClassificationTrainer(env, LabelColumnName, FeatureColumnName);
                             return TrainerUtils.MapTrainerEstimatorToTrainer<LogisticRegressionMulticlassClassificationTrainer,
-                                MulticlassLogisticRegressionModelParameters, MulticlassLogisticRegressionModelParameters>(env, trainerEstimator);
+                                LogisticRegressionMulticlassModelParameters, LogisticRegressionMulticlassModelParameters>(env, trainerEstimator);
```
Comment (wschin) [inline src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs]: We can NOT swap them. Logistic regression is never a multiclass classification model while multi-class logistic regression is an alternative name of `[multinomial logistic regression](https://en.wikipedia.org/wiki/Multinomial_logistic_regression)`

Comment (abgoswam) [reply src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs]: One alternative name we can use is SoftmaxRegression (also mentioned in wikipedia link above).

While refactoring, could you fix the name of the trainer estimator for this as well. 

I will revert this, and wait for your refactoring PR. Sounds good ?

---
In reply to: [265806976](https://github.com/dotnet/machinelearning/pull/2968#discussion_r265806976) [](ancestors = 265806976)

File: src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs [hunk 2]
```diff
@@ -24,16 +24,16 @@
     OlsTrainer.LoadNameValue,
     OlsTrainer.ShortName)]
 
-[assembly: LoadableClass(typeof(OrdinaryLeastSquaresRegressionModelParameters), null, typeof(SignatureLoadModel),
+[assembly: LoadableClass(typeof(OlsModelParameters), null, typeof(SignatureLoadModel),
```
Comment (TomFinley) [inline src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs]: >OlsModelParameters [](start = 32, length = 18)

So, general .NET naming guidelines seem to suggest that we avoid acronyms. That is, `OrdinaryLeastSquaresRegressionModelParameters` is right, and `OlsTrainer` is wrong. Similar with PCA. Have we made a conscious decision to discard the .NET guidelines in this case? If we have, could I see where that discussion happened so I can better understand the rationale? It is not in the linked issue, but may have occurred somewhere else.Thanks.

Comment (artidoro) [reply src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs]: I think the discussion is in this thread: #2762

Comment (abgoswam) [reply src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs]: The summary is here : https://github.com/dotnet/machinelearning/issues/2762#issuecomment-471845715

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs [hunk 3]
```diff
@@ -20,14 +20,14 @@
...
-    "Multi Class Naive Bayes predictor", MulticlassNaiveBayesModelParameters.LoaderSignature)]
+[assembly: LoadableClass(typeof(NaiveBayesModelParameters), null, typeof(SignatureLoadModel),
+    "Multi Class Naive Bayes predictor", NaiveBayesModelParameters.LoaderSignature)]
 
 [assembly: LoadableClass(typeof(void), typeof(NaiveBayesTrainer), null, typeof(SignatureEntryPointModule), NaiveBayesTrainer.LoadName)]
 
 namespace Microsoft.ML.Trainers
 {
-    public sealed class NaiveBayesTrainer : TrainerEstimatorBase<MulticlassPredictionTransformer<MulticlassNaiveBayesModelParameters>, MulticlassNaiveBayesModelParameters>
+    public sealed class NaiveBayesTrainer : TrainerEstimatorBase<MulticlassPredictionTransformer<NaiveBayesModelParameters>, NaiveBayesModelParameters>
```
Comment (artidoro) [inline src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: >NaiveBayesTrainer [](start = 24, length = 17)

Why does `NaiveBayesTrainer` not have `Multiclass` or `MulticlassClassification` in its name?

Comment (artidoro) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: NaiveBayes is a very general probabilistic technique, and could be applied to many different tasks, so I don't understand the rational for removing the task from its name?

---
In reply to: [266106131](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266106131) [](ancestors = 266106131)

Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: https://github.com/dotnet/machinelearning/issues/2762#issuecomment-471845715

- {TypeOfTask} is added only only when the algorithm supports multiple kinds of tasks . When added, we will spell out each task fully.

Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: We renamed it as per the discussion here.

[https://github.com/dotnet/machinelearning/issues/2762#issuecomment-471845715](https://github.com/dotnet/machinelearning/issues/2762#issuecomment-471845715)

• {TypeOfTask} is added only only when the algorithm supports multiple kinds of tasks . When added, we will spell out each task fully.

Do u have any suggestions ?

---
In reply to: [266107249](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266107249) [](ancestors = 266107249,266106131)

Comment (artidoro) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: My concern is that if we add this algorithm for `binaryclassification` it would require a breaking change to add `Multiclass` to the name `NaiveBayes`. I think that the above guideline works well when the algorithm can only be applied to one learning task. But this algorithm can be applied at least to binary and multiclass so I would suggest to add `MulticlassClassification` to its name, similarly for the `ModelParameters`.

---
In reply to: [266136420](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266136420) [](ancestors = 266136420,266107249,266106131)

Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: I see. Currently in ML.NET  we only have NaiveBayes  under the  *Multiclass*  extension of MLContext

So your concern is about a possible breaking change in the future if we want to add NaiveBayes  classfication  as a binary classifier ?    

---
In reply to: [266138507](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266138507) [](ancestors = 266138507,266136420,266107249,266106131)

Comment (artidoro) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: Yes that was my concern, maybe @tfinley@gmail.com  has an opinion about this?

---
In reply to: [266143059](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266143059) [](ancestors = 266143059,266138507,266136420,266107249,266106131)

Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: @TomFinley . Would be great to get your thoughts on this.

File: src/Microsoft.ML.FastTree/RandomForestClassification.cs [hunk 4]
```diff
@@ -49,7 +49,7 @@ internal FastForestOptionsBase()
         }
     }
 
-    public sealed class FastForestClassificationModelParameters :
+    public sealed class FastForestMulticlassModelParameters :
```
Comment (sfilipi) [inline src/Microsoft.ML.FastTree/RandomForestClassification.cs]: >FastForestMulticlassModelParameters [](start = 24, length = 35)

thank you for not making it FastForestMulticlassClassificationModelParameters :)

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs (hunk 3 above)
Comment (sfilipi) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: I would keep multiclass on NaiveBayes too. 

---
In reply to: [266143921](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266143921) [](ancestors = 266143921,266143059,266138507,266136420,266107249,266106131)

File: src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs (hunk 2 above)
Comment (TomFinley) [reply src/Microsoft.ML.Mkl.Components/OlsLinearRegression.cs]: Ah, all right, thanks for linking the relevant issues.

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs (hunk 3 above)
Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: Looks like we favor naming it NaiveBayesMulticlass.  Updating accordingly.

---
In reply to: [266568218](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266568218) [](ancestors = 266568218,266143921,266143059,266138507,266136420,266107249,266106131)

File: src/Microsoft.ML.FastTree/GamClassification.cs [hunk 5]
```diff
@@ -171,7 +171,7 @@ private protected override SchemaShape.Column[] GetOutputColumnsCore(SchemaShape
     /// <summary>
     /// The model parameters class for Binary Classification GAMs
     /// </summary>
-    public sealed class BinaryClassificationGamModelParameters : GamModelParametersBase, IPredictorProducing<float>
+    public sealed class GamBinaryModelParameters : GamModelParametersBase, IPredictorProducing<float>
```
Comment (eerhardt) [inline src/Microsoft.ML.FastTree/GamClassification.cs]: `BinaryClassification`?

Do we need to put `Classification` in the name? We do everywhere else.

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs [hunk 6]
```diff
@@ -13,20 +13,20 @@
...
+[assembly: LoadableClass(typeof(NaiveBayesMulticlassModelParameters), null, typeof(SignatureLoadModel),
+    "Multi Class Naive Bayes predictor", NaiveBayesMulticlassModelParameters.LoaderSignature)]
 
-[assembly: LoadableClass(typeof(void), typeof(NaiveBayesTrainer), null, typeof(SignatureEntryPointModule), NaiveBayesTrainer.LoadName)]
+[assembly: LoadableClass(typeof(void), typeof(NaiveBayesMulticlassTrainer), null, typeof(SignatureEntryPointModule), NaiveBayesMulticlassTrainer.LoadName)]
 
 namespace Microsoft.ML.Trainers
 {
-    public sealed class NaiveBayesTrainer : TrainerEstimatorBase<MulticlassPredictionTransformer<MulticlassNaiveBayesModelParameters>, MulticlassNaiveBayesModelParameters>
+    public sealed class NaiveBayesMulticlassTrainer : TrainerEstimatorBase<MulticlassPredictionTransformer<NaiveBayesMulticlassModelParameters>, NaiveBayesMulticlassModelParameters>
```
Comment (eerhardt) [inline src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: `NaiveBayesMulticlassTrainer` => `NaiveBayesMulticlassClassificationTrainer`? Why are we dropping `Classification` from these names?

Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: as noted in the bug description, it seems for ModelParameters  we are consistent in *not* using the word "Classification"  . I am following the same convention in this PR.

Example:
- LinearBinaryModelParameters
- FastTreeBinaryModelParameters

I don't think we have solved the "Classification" debate completely yet #2623 

Here is my observation :
- For Trainers, we use "Classification" 
- For ModelParameters, we do not use "Classification"

---
In reply to: [266627123](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266627123) [](ancestors = 266627123)

File: src/Microsoft.ML.FastTree/GamClassification.cs (hunk 5 above)
Comment (abgoswam) [reply src/Microsoft.ML.FastTree/GamClassification.cs]: For ModelParameters we do not.  Please see the other comment.  

---
In reply to: [266626783](https://github.com/dotnet/machinelearning/pull/2968#discussion_r266626783) [](ancestors = 266626783)

File: src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs (hunk 6 above)
Comment (eerhardt) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: > For Trainers, we use "Classification"
For ModelParameters, we do not use "Classification"

Why is this a valid policy?

Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MulticlassClassification/MulticlassNaiveBayesTrainer.cs]: I cannot claim its a "valid" policy,  but one observation I have is that  

- we do not use "Classification" anywhere for ModelParameters
  - CalibratedModelParametersBase
  - LinearBinaryModelParameters 
- in some cases it leads to long names  e.g. `FastForestMulticlassClassificationModelParameter`

We have 2 options:

A. Follow the naming convention used by `Trainers` i.e.  "<>BinaryClassification" and "MulticlassClassification" uniformly.   
B.  Not  use "Classification"  for ModelParameters .

Which one you favor ?  @eerhardt @sfilipi
