### PR TITLE
Fix bug in TextLoader

### LINKED ISSUE #2996: Cannot create TextLoader without loading assemblies into ComponentCatalog
In the `TextLoader` constructor, it is allows to pass a null `Options`, or an `Options` object with a null `Columns` (see https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1095 and https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1111).
When this is the case, the constructor goes to `TryParseSchema` which uses the `ComponentCatalog` to load the schema, so we get a null reference exception here: https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs#L1293, if no assemblies are loaded.

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #2996. (This PR replaces #3011).

### CODE REVIEW

File: src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs [hunk 1]
```diff
@@ -1288,12 +1288,9 @@ private sealed class LoaderHolder
...
 
-                if (loader == null || string.IsNullOrWhiteSpace(loader.Name))
-                    goto LDone;
-
-                // Make sure the loader binds to us.
-                var info = host.ComponentCatalog.GetLoadableClassInfo<SignatureDataLoader>(loader.Name);
-                if (info.Type != typeof(ILegacyDataLoader) || info.ArgType != typeof(Options))
+                // Make sure that the schema is described using either the syntax TextLoader{<settings>} or the syntax Text{<settings>},
+                // where "settings" is a string that can be parsed by CmdParser into an object of type TextLoader.Options.
+                if (loader == null || string.IsNullOrWhiteSpace(loader.Name) || (loader.Name != LoaderSignature && loader.Name != "Text"))
```
Comment (yaeldekel) [inline src/Microsoft.ML.Data/DataLoadSave/Text/TextLoader.cs]: >Name [](start = 88, length = 4)

The previous check was to verify that `loader.Name` is one of the names defined in `TextLoader`'s `LoadableClassAttribute`. Since now we cannot rely on this attribute being in the `ComponentCatalog`, we explicitly require `loader.Name` to be one of the load names of `TextLoader`.
