### PR TITLE
Fix a value-mapping bug

### LINKED ISSUE #3166: The ValueMap Train method assumes that keys are on the first column, and values on the second, rather than storing the columns and using those
If the [lookupMap IDataView  in the MapValue API](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs#L412) is constructed so that the first column contains the keys, and the second one contains the values, this API will work as expected; if the lookup idv is constructed in any other order, the API won't work, because the Train method of the transformer has hardcoded the index = 0 to be the keys of the idv, and index = 1 to be the values .

The [ValueMapping Train](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Transforms/ValueMapping.cs#L836)  should not assume that the first column is the keys, and the second is the values; it should instead save the columns passed to it [from the API](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs#L412) (and not just the column names, like it is doing now) and get the cursor based on the columns, rather than indices. 

Easy repro: : swap the order of the members in the LookupMap class below, and see how it fails. 

```csharp
 // Type for the IDataView that will be serving as the map
private class LookupMap
 {
     public float Value { get; set; }
     public string Category { get; set; }
 }
```

```csharp
using System;
using System.Collections.Generic;

namespace Microsoft.ML.Samples.Dynamic
{
    public static class MapValueIdvLookup
    {
        /// This example demonstrates the use of MapValue by mapping floats to strings, looking up the mapping in an IDataView. 
        /// This is useful to map types to a grouping. 
        public static void Example()
        {
            // Create a new ML context, for ML.NET operations. It can be used for exception tracking and logging, 
            // as well as the source of randomness.
            var mlContext = new MLContext();

            // Get a small dataset as an IEnumerable.
            var rawData = new[] {
                new DataPoint() { Price = 3.14f },
                new DataPoint() { Price = 2000f },
                new DataPoint() { Price = 1.19f },
                new DataPoint() { Price = 2.17f },
                new DataPoint() { Price = 33.784f },

            };

            // Convert to IDataView
            var data = mlContext.Data.LoadFromEnumerable(rawData);

            // Create the lookup map data IEnumerable.   
            var lookupData = new[] {
                new LookupMap { Value = 3.14f, Category = "Low" },
                new LookupMap { Value = 1.19f , Category = "Low" },
                new LookupMap { Value = 2.17f , Category = "Low" },
                new LookupMap { Value = 33.784f, Category = "Medium" },
                new LookupMap { Value = 2000f, Category = "High"}

            };

            // Convert to IDataView
            var lookupIdvMap = mlContext.Data.LoadFromEnumerable(lookupData);

            // Constructs the ValueMappingEstimator making the ML.NET pipeline
            var pipeline = mlContext.Transforms.Conversion.MapValue("PriceCategory", lookupIdvMap, lookupIdvMap.Schema["Value"], lookupIdvMap.Schema["Category"], "Price");

            // Fits the ValueMappingEstimator and transforms the data converting the Price to PriceCategory.
            IDataView transformedData = pipeline.Fit(data).Transform(data);

            // Getting the resulting data as an IEnumerable.
            IEnumerable<TransformedData> features = mlContext.Data.CreateEnumerable<TransformedData>(transformedData, reuseRowObject: false);

            Console.WriteLine($" Price   PriceCategory");
            foreach (var featureRow in features)
                Console.WriteLine($"{featureRow.Price}\t\t{featureRow.PriceCategory}");

            // TransformedData obtained post-transformation.
            //
            // Price        PriceCategory
            // 3.14            Low
            // 2000            High
            // 1.19            Low
            // 2.17            Low
            // 33.784          Medium
        }

        // Type for the IDataView that will be serving as the map
        private class LookupMap
        {
            public float Value { get; set; }
            public string Category { get; set; }
        }

        private class DataPoint
        {
            public float Price { get; set; }
        }

        private class TransformedData : DataPoint
        {
            public string PriceCategory { get; set; }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by wschin**
This PR fixes #3166.

### CODE REVIEW

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 1]
```diff
@@ -46,7 +46,22 @@ public class ValueMappingEstimator : TrivialEstimator<ValueMappingTransformer>
...
+
+        /// <summary>
+        /// Constructs the ValueMappingEstimator, key type -> value type mapping
+        /// </summary>
+        /// <param name="env">The environment to use.</param>
+        /// <param name="lookupMap">An instance of <see cref="IDataView"/> that contains the key and value columns.</param>
+        /// <param name="keyColumn">Name of the key column in <paramref name="lookupMap"/>.</param>
+        /// <param name="valueColumn">Name of the value column in <paramref name="lookupMap"/>.</param>
+        /// <param name="columns">The list of names of the input columns to apply the transformation, and the name of the resulting column.</param>
+        internal ValueMappingEstimator(IHostEnvironment env, IDataView lookupMap, DataViewSchema.Column keyColumn, DataViewSchema.Column valueColumn, params (string outputColumnName, string inputColumnName)[] columns)
```
Comment (singlis) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: If we are adding this constructor, is the one above (that takes a key column name and value column name) needed?

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 2]
```diff
@@ -396,29 +414,32 @@ internal sealed class Options
...
+        private ValueMap CreateValueMapFromDataView(IDataView dataView, DataViewSchema.Column keyColumn, DataViewSchema.Column valueColumn)
         {
-            // Confirm that the key and value columns exist in the dataView
-            Host.Check(dataView.Schema.TryGetColumnIndex(keyColumn, out int keyIdx), "Key column " + keyColumn + " does not exist in the given dataview");
-            Host.Check(dataView.Schema.TryGetColumnIndex(valueColumn, out int valueIdx), "Value column " + valueColumn + " does not exist in the given dataview");
-            var keyType = dataView.Schema[keyIdx].Type;
-            var valueType = dataView.Schema[valueIdx].Type;
-            var valueMap = ValueMap.Create(keyType, valueType, ValueColumnMetadata);
-            using (var cursor = dataView.GetRowCursor(dataView.Schema[keyIdx], dataView.Schema[valueIdx]))
+            var retrievedKeyColumn = dataView.Schema[keyColumn.Index];
```
Comment (singlis) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >Schema [](start = 46, length = 6)

Can this be out of range?

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 3]
```diff
@@ -396,29 +414,32 @@ internal sealed class Options
...
+            Host.Check(retrievedKeyColumn.Index == keyColumn.Index, nameof(keyColumn) + "'s column index doesn't match that of the associated column in " + nameof(dataView));
+            Host.Check(retrievedKeyColumn.Type == keyColumn.Type, nameof(keyColumn) + "'s column type doesn't match that of the associated column in " + nameof(dataView));
+            Host.Check(retrievedKeyColumn.Annotations == keyColumn.Annotations, nameof(keyColumn) + "'s column annotions don't match those of the associated column in " + nameof(dataView));
+
+            var retrievedValueColumn = dataView.Schema[valueColumn.Index];
```
Comment (singlis) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: same here.

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 4]
```diff
@@ -324,11 +339,14 @@ public class ValueMappingTransformer : OneToOneTransformerBase
...
         private const string DefaultMapName = "DefaultMap.idv";
-        internal static string KeyColumnName = "Key";
-        internal static string ValueColumnName = "Value";
+        internal static string DefaultKeyColumnName = "Key";
+        internal static string DefaultValueColumnName = "Value";
         private ValueMap _valueMap;
         private readonly byte[] _dataView;
 
+        private readonly DataViewSchema.Column _lookupKeyColumn;
+        private readonly DataViewSchema.Column _lookupValueColumn;
```
Comment (singlis) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >private [](start = 8, length = 7)

Why store these? They look like they can be removed.

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 5]
```diff
@@ -46,7 +46,22 @@ public class ValueMappingEstimator : TrivialEstimator<ValueMappingTransformer>
         /// <param name="columns">The list of names of the input columns to apply the transformation, and the name of the resulting column.</param>
         internal ValueMappingEstimator(IHostEnvironment env, IDataView lookupMap, string keyColumn, string valueColumn, params (string outputColumnName, string inputColumnName)[] columns)
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >ValueMappingEstimator [](start = 17, length = 21)

I'm not getting why we still have this constructor
Public interface operates over Schema.Column object, any conversion from string to Schema.Column is unrelaable, why it's still around?

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 1 above)
Comment (sfilipi) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: +1, especially since the extension that calls into the ctor, takes in DataViewSchema.Column and passes down only the name of the column. 

---
In reply to: [271533565](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271533565) [](ancestors = 271533565)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 6]
```diff
@@ -396,29 +414,32 @@ internal sealed class Options
         }
 
         internal ValueMappingTransformer(IHostEnvironment env, IDataView lookupMap,
-            string keyColumn, string valueColumn, (string outputColumnName, string inputColumnName)[] columns)
+            DataViewSchema.Column lookupKeyColumn, DataViewSchema.Column lookupValueColumn, (string outputColumnName, string inputColumnName)[] columns)
             : base(Contracts.CheckRef(env, nameof(env)).Register(nameof(ValueMappingTransformer)), columns)
         {
-            Host.CheckNonEmpty(keyColumn, nameof(keyColumn), "A key column must be specified when passing in an IDataView for the value mapping");
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: > Host.CheckNonEmpty [](start = 11, length = 19)

maybe check lookupKeyColumn.HasValue

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 7]
```diff
@@ -659,5 +659,72 @@ void TestValueMapBackCompatTermLookupKeyTypeValue()
...
             }
         }
+
+        [Fact]
+        public static void TestValueMapWithNonDefaultColumnOrder()
+        {
+            // Create a new ML context, for ML.NET operations. It can be used for exception tracking and logging, 
+            // as well as the source of randomness.
+            var mlContext = new MLContext();
+
```
Comment (sfilipi) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: you don't need this, the file should already have it: ML

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 8]
```diff
@@ -659,5 +659,72 @@ void TestValueMapBackCompatTermLookupKeyTypeValue()
...
+            // Constructs the ValueMappingEstimator making the ML.NET pipeline
+            var pipeline = mlContext.Transforms.Conversion.MapValue("PriceCategory", lookupIdvMap, lookupIdvMap.Schema["Value"], lookupIdvMap.Schema["Category"], "Price");
+
+            // Fits the ValueMappingEstimator and transforms the data converting the Price to PriceCategory.
+            IDataView transformedData = pipeline.Fit(data).Transform(data);
+
+            // Getting the resulting data as an IEnumerable.
+            var features = mlContext.Data.CreateEnumerable<TransformedData>(transformedData, reuseRowObject: false).ToList();
+
+            var expectedPrices = new float[] { 3.14f, 2000f, 1.19f, 2.17f, 33.784f };
```
Comment (sfilipi) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: >expectedPrices [](start = 16, length = 14)

you have rawData storing those

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 9]
```diff
@@ -396,29 +414,32 @@ internal sealed class Options
...
-            Host.CheckNonEmpty(valueColumn, nameof(valueColumn), "A value column must be specified when passing in an IDataView for the value mapping");
-            _valueMap = CreateValueMapFromDataView(lookupMap, keyColumn, valueColumn);
-            int valueColumnIdx = 0;
-            Host.Check(lookupMap.Schema.TryGetColumnIndex(valueColumn, out valueColumnIdx));
-            ValueColumnMetadata = lookupMap.Schema[valueColumnIdx].Annotations;
+            _lookupKeyColumn = lookupKeyColumn;
+            _lookupValueColumn = lookupValueColumn;
+            _valueMap = CreateValueMapFromDataView(lookupMap, _lookupKeyColumn, _lookupValueColumn);
+            ValueColumnMetadata = lookupMap.Schema[_lookupValueColumn.Index].Annotations;
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: Does _lookupValueColumn.Annotations work?

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 2 above)
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >retrievedKeyColumn [](start = 16, length = 18)

why do you need this, if you have the keyColumn?

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 10]
```diff
@@ -396,29 +414,32 @@ internal sealed class Options
...
-            Host.Check(dataView.Schema.TryGetColumnIndex(valueColumn, out int valueIdx), "Value column " + valueColumn + " does not exist in the given dataview");
-            var keyType = dataView.Schema[keyIdx].Type;
-            var valueType = dataView.Schema[valueIdx].Type;
-            var valueMap = ValueMap.Create(keyType, valueType, ValueColumnMetadata);
-            using (var cursor = dataView.GetRowCursor(dataView.Schema[keyIdx], dataView.Schema[valueIdx]))
+            var retrievedKeyColumn = dataView.Schema[keyColumn.Index];
+            Host.Check(retrievedKeyColumn.Index == keyColumn.Index, nameof(keyColumn) + "'s column index doesn't match that of the associated column in " + nameof(dataView));
+            Host.Check(retrievedKeyColumn.Type == keyColumn.Type, nameof(keyColumn) + "'s column type doesn't match that of the associated column in " + nameof(dataView));
+            Host.Check(retrievedKeyColumn.Annotations == keyColumn.Annotations, nameof(keyColumn) + "'s column annotions don't match those of the associated column in " + nameof(dataView));
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >annotions [](start = 111, length = 9)

typo

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 2 above)
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >retrievedKeyColumn [](start = 16, length = 18)

do we have any overload for Equals on the DataViewSchema.Column? The checks below seem like they would belong in that Equals.

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs [hunk 11]
```diff
@@ -753,26 +774,29 @@ private protected override void SaveModel(ModelSaveContext ctx)
         /// </summary>
         private abstract class ValueMap
         {
+            public readonly string KeyColumnName;
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: >KeyColumnName [](start = 35, length = 13)

what do you think about using the entire column, rather than the name?

Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: I will merge `Name` and `Type` into `DataViewSchema.Column` and clean redundant functions up.

---
In reply to: [271579703](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271579703) [](ancestors = 271579703)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: We don't.

---
In reply to: [271578862](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271578862) [](ancestors = 271578862)

Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: Will add a check in the next iteration.

---
In reply to: [271535033](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271535033) [](ancestors = 271535033)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: Will add a check as well.

---
In reply to: [271535097](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271535097) [](ancestors = 271535097)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 6 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: We can't. This is a struct, not a class.

---
In reply to: [271577590](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271577590) [](ancestors = 271577590)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 1 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: I will remove it in the next iteration.

---
In reply to: [271577343](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271577343) [](ancestors = 271577343,271533565)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 5 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: Removed and related code is updated as well.

---
In reply to: [271544302](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271544302) [](ancestors = 271544302)

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs (hunk 8 above)
Comment (wschin) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: Yes. Thank you.

---
In reply to: [271578355](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271578355) [](ancestors = 271578355)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 4 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: Super nice catch. Thanks.

---
In reply to: [271535842](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271535842) [](ancestors = 271535842)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 9 above)
Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: Just did a small refactorization around `Annotations` and extent a test to cover it.

---
In reply to: [271578470](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271578470) [](ancestors = 271578470)

File: src/Microsoft.ML.Data/Transforms/ValueMapping.cs (hunk 2 above)
Comment (sfilipi) [reply src/Microsoft.ML.Data/Transforms/ValueMapping.cs]: I'll open a bug about it.. 

---
In reply to: [271966741](https://github.com/dotnet/machinelearning/pull/3180#discussion_r271966741) [](ancestors = 271966741,271578862)

File: src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs [hunk 12]
```diff
@@ -386,8 +416,15 @@ public static KeyToValueMappingEstimator MapKeyToValue(this TransformsCatalog.Co
...
-                    InputOutputColumnPair.ConvertToValueTuples(columns));
+
+            var lookupMap = DataViewHelper.CreateDataView(catalog.GetEnvironment(), keys, values,
+                ValueMappingTransformer.DefaultKeyColumnName,
+                ValueMappingTransformer.DefaultValueColumnName);
+
+            return new ValueMappingEstimator<TInputType, TOutputType>(catalog.GetEnvironment(), lookupMap,
+                lookupMap.Schema[ValueMappingTransformer.DefaultKeyColumnName],
+                lookupMap.Schema[ValueMappingTransformer.DefaultValueColumnName],
+                InputOutputColumnPair.ConvertToValueTuples(columns));
```
Comment (sfilipi) [inline src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs]: there is a bit of repetition here, does it make sense to make it part of the ctor?

Comment (wschin) [reply src/Microsoft.ML.Data/Transforms/ConversionsExtensionsCatalog.cs]: I feel columns must go with the associated `IDataView`. There should be no column if its `IDataView` hasn't been created.
