### PR TITLE
Metadata fixes for the ValueMappingEstimator

### LINKED ISSUE #2083: ValueMappingEstimator does not produce the correct output schema with metadata
The ValueMappingEstimator when calling GetOutputSchema and setting the treatAsKeyTypes to true does not return an output schema that contains metadata. This is can be reproduced by creating a ValueMappingEstimator and appending with a KeyToValueMappingEstimator to do a reverse lookup of the KeyType to the original value. 

Here is the code snippet that reproduces the error:
```
            var pipeline = new ValueMappingEstimator<string, string>(ml, educationKeys, educationValues, true, ("Education", "EducationKeyType"))
                              .Append(new KeyToValueMappingEstimator(ml, ("EducationKeyType", "EducationCategory")));
```

### LINKED ISSUE #2086: ValueMappingEstimator KeyType metadata maps to Key data and not to the Value data
### Issue
Discovered while fixing #2083.

When creating a ValueMappingEstimator with KeyTypes as the values, the generated KeyType does not covert back to the original value. This is demonstrated when appending a KeyToValueTransform to retrieve the original values using the following code:

```
            // Creating a list of keys that are based on the Education values
            // These lists are created by hand for the demonstration, but the ValueMappingEstimator can take in any IEnumerables.
            var educationKeys = new List<string>()
            {
                "0-5yrs",
                "6-11yrs",
                "12+yrs"
            };

            var educationValues = new List<string>()
            {
                "Cat1",
                "Cat2", 
                "Cat3"
            };

            // Generate the estimator with the key type set as true. Even though are values are strings, this will
            // create a key for each value. For this example, a KeyToValue Estimator is added to the ValueMapping Estimator to demonstrate the
            // reverse lookup of the KeyType
            var pipeline = new ValueMappingEstimator<string, string>(ml, educationKeys, educationValues, true, ("Education", "EducationKeyType"))
                              .Append(new KeyToValueMappingEstimator(ml, ("EducationKeyType", "EducationCategory")));
```

The expected results should be:
```
Age   Education   EducationCategory
26      0-5yrs          Cat1
42      0-5yrs          Cat1
39      12+yrs          Cat3
34      0-5yrs          Cat1
35      6-11yrs         Cat2
```
The actual results are:
```
Age     Education    EducationCategory
26      0-5yrs          0-5yrs
42      0-5yrs          0-5yrs
39      12+yrs          12+yrs
34      0-5yrs          0-5yrs
35      6-11yrs         6-11yrs
```

### PR DESCRIPTION
**Pull request by singlis**
The ValueMappingEstimator had a couple of issues when using the Values as KeyTypes:
1) The output schema for the Estimator did not contain the KeyType
information in the metadata.
2) The reverse lookup of the metadata had the incorrect value.

This now sets the correct metadata on the output schema and uses the
value data for the reverse lookup. A test was added to confirm the
changes using the KeyToValueMapping appended to a ValueMappingEstimator
for the reverse lookup.

Fixes #2086
Fixes #2083

### CODE REVIEW

File: src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs [hunk 1]
```diff
@@ -191,18 +192,15 @@ private static ValueGetter<VBuffer<ReadOnlyMemory<char>>> GetKeyValueGetter<TKey
                 // set of values. This is used for generating the metadata of
                 // the column.
                 HashSet<TValue> valueSet = new HashSet<TValue>();
-                HashSet<TKey> keySet = new HashSet<TKey>();
                 for (int i = 0; i < values.Count(); ++i)
                 {
                     var v = values.ElementAt(i);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs]: Can you replace it with foreach loop?
I found terrifying idea of fetching i-th element every time out of IEnumerable

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 2]
```diff
@@ -320,6 +320,31 @@ public void ValueMappingValuesAsStringKeyTypes()
...
+            // Generating the list of strings for the key type values, note that foo1 is duplicated as intended to test that the same index value is returned
+            IEnumerable<ReadOnlyMemory<char>> values = new List<ReadOnlyMemory<char>>() { "foo1".AsMemory(), "foo2".AsMemory(), "foo1".AsMemory(), "foo3".AsMemory() };
+
+            var estimator = new ValueMappingEstimator<ReadOnlyMemory<char>, ReadOnlyMemory<char>>(Env, keys, values, true, new[] { ("A", "D"), ("B", "E"), ("C", "F") })
+                            .Append(new KeyToValueMappingEstimator(Env, ("D","DOutput")));
+            var t = estimator.Fit(dataView);
+
+            var result = t.Transform(dataView);
+            var cursor = result.GetRowCursor((col) => true);
+            var getterD = cursor.GetGetter<ReadOnlyMemory<char>>(6);
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: >6 [](start = 65, length = 1)

magic numbers, can you do result.Schema["D"].Index?

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 3]
```diff
@@ -320,6 +320,31 @@ public void ValueMappingValuesAsStringKeyTypes()
             Assert.Equal<uint>(0, fValue);
         }
 
+        [Fact]
+        public void ValueMappingValuesAsKeyTypesReverseLookup()
+        {
+            var data = new[] { new TestClass() { A = "bar", B = "test", C = "notfound" } };
+            var dataView = ComponentCreation.CreateDataView(Env, data);
+
+            IEnumerable<ReadOnlyMemory<char>> keys = new List<ReadOnlyMemory<char>>() { "foo".AsMemory(), "bar".AsMemory(), "test".AsMemory(), "wahoo".AsMemory() };
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: >IEnumerable<ReadOnlyMemory<char>> [](start = 12, length = 33)

what's wrong with var?

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 4]
```diff
@@ -320,6 +320,31 @@ public void ValueMappingValuesAsStringKeyTypes()
...
+            var t = estimator.Fit(dataView);
+
+            var result = t.Transform(dataView);
+            var cursor = result.GetRowCursor((col) => true);
+            var getterD = cursor.GetGetter<ReadOnlyMemory<char>>(6);
+            cursor.MoveNext();
+
+            // The expected values will contain the generated key type values starting from 1.
+            ReadOnlyMemory<char> dValue = default;
+            getterD(ref dValue);
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: >dValue [](start = 24, length = 6)

can we validate it's a "bar"?

File: src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs (hunk 1 above)
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs]: absolutely.

---
In reply to: [246975951](https://github.com/dotnet/machinelearning/pull/2098#discussion_r246975951) [](ancestors = 246975951)

File: src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs [hunk 5]
```diff
@@ -100,13 +100,14 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
             var isKey = Transformer.ValueColumnType.IsKey;
             var columnType = (isKey) ? PrimitiveType.FromKind(DataKind.U4) :
                                     Transformer.ValueColumnType;
+            var metadata = SchemaShape.Create(Transformer.ValueColumnMetadata.Schema);
```
Comment (wschin) [inline src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs]:
```suggestion
            var metadataShape = SchemaShape.Create(Transformer.ValueColumnMetadata.Schema);
```
Maybe?

File: src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs [hunk 6]
```diff
@@ -100,13 +100,14 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
...
             foreach (var (Input, Output) in _columns)
             {
                 if (!inputSchema.TryFindColumn(Input, out var originalColumn))
                     throw Host.ExceptSchemaMismatch(nameof(inputSchema), "input", Input);
 
                 // Get the type from TOutputType
```
Comment (wschin) [inline src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs]: What is TOutputType here? Is it not Output?

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 7]
```diff
@@ -320,6 +320,32 @@ public void ValueMappingValuesAsStringKeyTypes()
...
+            var data = new[] { new TestClass() { A = "bar", B = "test", C = "notfound" } };
+            var dataView = ComponentCreation.CreateDataView(Env, data);
+
+            var keys = new List<ReadOnlyMemory<char>>() { "foo".AsMemory(), "bar".AsMemory(), "test".AsMemory(), "wahoo".AsMemory() };
+
+            // Generating the list of strings for the key type values, note that foo1 is duplicated as intended to test that the same index value is returned
+            var values = new List<ReadOnlyMemory<char>>() { "foo1".AsMemory(), "foo2".AsMemory(), "foo1".AsMemory(), "foo3".AsMemory() };
+
+            var estimator = new ValueMappingEstimator<ReadOnlyMemory<char>, ReadOnlyMemory<char>>(Env, keys, values, true, new[] { ("A", "D"), ("B", "E"), ("C", "F") })
+                            .Append(new KeyToValueMappingEstimator(Env, ("D","DOutput")));
```
Comment (wschin) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]:
```suggestion
                            .Append(new KeyToValueMappingEstimator(Env, ("D", "DOutput")));
```
Please format all files touched.

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs [hunk 8]
```diff
@@ -320,6 +320,32 @@ public void ValueMappingValuesAsStringKeyTypes()
...
+        {
+            var data = new[] { new TestClass() { A = "bar", B = "test", C = "notfound" } };
+            var dataView = ComponentCreation.CreateDataView(Env, data);
+
+            var keys = new List<ReadOnlyMemory<char>>() { "foo".AsMemory(), "bar".AsMemory(), "test".AsMemory(), "wahoo".AsMemory() };
+
+            // Generating the list of strings for the key type values, note that foo1 is duplicated as intended to test that the same index value is returned
+            var values = new List<ReadOnlyMemory<char>>() { "foo1".AsMemory(), "foo2".AsMemory(), "foo1".AsMemory(), "foo3".AsMemory() };
+
+            var estimator = new ValueMappingEstimator<ReadOnlyMemory<char>, ReadOnlyMemory<char>>(Env, keys, values, true, new[] { ("A", "D"), ("B", "E"), ("C", "F") })
```
Comment (wschin) [inline test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: Why do you need three columns? Only "D" is used below.

File: src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs (hunk 6 above)
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs]: That is old, I used to have the generic arguments be TInputType, TOutputType, but then changed to TKeyType and TValueType. I will update the comment.

---
In reply to: [247282739](https://github.com/dotnet/machinelearning/pull/2098#discussion_r247282739) [](ancestors = 247282739)

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs (hunk 7 above)
Comment (singlis) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: Thanks, they are both formatted now.

---
In reply to: [247284278](https://github.com/dotnet/machinelearning/pull/2098#discussion_r247284278) [](ancestors = 247284278)

File: test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs (hunk 8 above)
Comment (singlis) [reply test/Microsoft.ML.Tests/Transformers/ValueMappingTests.cs]: True - that is a result of copying code from another test. I have removed the other two columns.

---
In reply to: [247285144](https://github.com/dotnet/machinelearning/pull/2098#discussion_r247285144) [](ancestors = 247285144)

File: src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs [hunk 9]
```diff
@@ -100,13 +100,14 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
...
-                var col = new SchemaShape.Column(Output, vectorKind, columnType, isKey, originalColumn.Metadata);
+                var col = new SchemaShape.Column(Output, vectorKind, columnType, isKey, metadata);
```
[the remark this answers is not in the document]
Comment (singlis) [reply src/Microsoft.ML.Data/Transforms/ValueMappingTransformer.cs]: Although Name is more specific to what the object actually is, I think it goes against thinking of these as columns since you are talking about a input/output (or source/name). I would prefer to keep it as Output/Input. BTW - this will also go through another revision with #2064

---
In reply to: [247282892](https://github.com/dotnet/machinelearning/pull/2098#discussion_r247282892) [](ancestors = 247282892)
