### PR TITLE
Fix FeatureColumnName in the public API

### LINKED ISSUE #2975: FeatureColumn vs FeatureColumnName in Model Transformers.
In the public API, we've been switching `FeatureColumn` to `FeatureColumnName`. However, trained models like `SDCA` have `FeatureColumnName` in the input, but produce a `Transformer` that has a `FeatureColumn` property. I think this is widespread.

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #2975

- also fixes an incorrect parameter name `featureColumn` parameter in ExplanabilityCatalog.cs

### CODE REVIEW

File: src/Microsoft.ML.Data/Transforms/ExplainabilityCatalog.cs [hunk 1]
```diff
@@ -18,18 +18,18 @@ public static class ExplainabilityCatalog
...
+        /// <param name="featureColumnName">The name of the feature column that will be used as input.</param>
         /// <param name="numPositiveContributions">The number of positive contributions to report, sorted from highest magnitude to lowest magnitude.
         /// Note that if there are fewer features with positive contributions than <paramref name="numPositiveContributions"/>, the rest will be returned as zeros.</param>
         /// <param name="numNegativeContributions">The number of negative contributions to report, sorted from highest magnitude to lowest magnitude.
         /// Note that if there are fewer features with negative contributions than <paramref name="numNegativeContributions"/>, the rest will be returned as zeros.</param>
         /// <param name="normalize">Whether the feature contributions should be normalized to the [-1, 1] interval.</param>
         public static FeatureContributionCalculatingEstimator FeatureContributionCalculation(this ModelOperationsCatalog.ExplainabilityTransforms catalog,
             ICalculateFeatureContribution modelParameters,
-            string featureColumn = DefaultColumnNames.Features,
```
Comment (rogancarr) [inline src/Microsoft.ML.Data/Transforms/ExplainabilityCatalog.cs]: >featureColumn =  [](start = 19, length = 16)

#2966 rewrites these functions, so you can drop changes to `ExplainabilityCatalog`.

Comment (artidoro) [reply src/Microsoft.ML.Data/Transforms/ExplainabilityCatalog.cs]: That would be much appreciated indeed :)
