### PR TITLE
Register assemblies in  legacy predictor model

### LINKED ISSUE #1150: Model Backwards Compatability
Hi

Following up from issue #569 - when using the latest nightly builds `0.7.0-preview-27004-1` models trained using the previous ML.NET release (0.5) fail to load, with the following exception:

``` csharp
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstanceCore(Object[] ctorArgs)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstance(IHostEnvironment env, Object args, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes](IHostEnvironment env, Type signatureType, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes,TSig](IHostEnvironment env, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.Model.ModelLoadContext.TryLoadModelCore[TRes,TSig](IHostEnvironment env, TRes& result, Object[] extra)
   at Microsoft.ML.Runtime.Model.ModelLoadContext.TryLoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.Runtime.Model.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.Runtime.Model.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.Runtime.Model.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, String name, Object[] extra)
   at Microsoft.ML.Runtime.Model.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, String name, Object[] extra)
   at Microsoft.ML.Runtime.Data.CompositeDataLoader.LoadSelectedTransforms(ModelLoadContext ctx, IDataView srcView, IHostEnvironment env, Func`2 isTransformTagAccepted)
   at Microsoft.ML.Runtime.Model.ModelFileUtils.LoadTransforms(IHostEnvironment env, IDataView data, RepositoryReader rep)
   at Microsoft.ML.Runtime.Model.ModelFileUtils.LoadTransforms(IHostEnvironment env, IDataView data, Stream modelStream)
   at Microsoft.ML.Runtime.Api.ComponentCreation.LoadTransforms(IHostEnvironment env, Stream modelStream, IDataView data)
   at Microsoft.ML.Runtime.Api.DataViewConstructionUtils.LoadPipeWithPredictor(IHostEnvironment env, Stream modelStream, IDataView view)
   at Microsoft.ML.Runtime.Api.BatchPredictionEngine`2..ctor(IHostEnvironment env, Stream modelStream, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.Runtime.Api.ComponentCreation.CreateBatchPredictionEngine[TSrc,TDst](IHostEnvironment env, Stream modelStream, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.Legacy.PredictionModel.ReadAsync[TInput,TOutput](Stream stream)
   at Demo.Program.<Main>d__0.MoveNext() in C:\_Projects\OSS\MLNETPreviousModelLoadingError\Demo\Program.cs:line 25
```

I've attached a small demo that reproduces the above. The zip also contains a model trained on ML.NET 0.5 using the following code:

``` csharp
namespace Endjin.Expenses.Demo
{
    #region Using Directives

    using System.Collections.Generic;

    using Endjin.FreeAgent.Expenses.MachineLearning.Domain;

    using Microsoft.ML.Legacy;
    using Microsoft.ML.Legacy.Data;
    using Microsoft.ML.Legacy.Trainers;
    using Microsoft.ML.Legacy.Transforms;

    #endregion 

    public class ExpenseModelTrainer
    {
        public PredictionModel<TransactionModel, Prediction> Train(IEnumerable<TransactionModel> input)
        {
            var pipeline = new LearningPipeline
            {
                CollectionDataSource.Create(input),
                new TextFeaturizer("Features", nameof(TransactionModel.Description), nameof(TransactionModel.Reference), nameof(TransactionModel.Amount)),
                new Dictionarizer(nameof(TransactionModel.Label)),
                new StochasticDualCoordinateAscentClassifier(),
                new PredictedLabelColumnOriginalValueConverter { PredictedLabelColumn = nameof(Prediction.PredictedLabel) }
            };

            return pipeline.Train<TransactionModel, Prediction>();
        }
    }
}
```
(The "legacy" namespaces changed in the latest version, but if you change them back to the 0.5 version namespaces - nothing else changed)

[MLNETPreviousModelLoadingError.zip](https://github.com/dotnet/machinelearning/files/2446874/MLNETPreviousModelLoadingError.zip)

Many thanks,

Howard

### PR DESCRIPTION
**Pull request by ganik**
fixes #1150

### CODE REVIEW

File: src/Microsoft.ML.Legacy/PredictionModel.cs [hunk 1]
```diff
@@ -22,6 +21,7 @@ public class PredictionModel
         internal PredictionModel(Stream stream)
         {
             _env = new ConsoleEnvironment();
+            AssemblyRegistration.RegisterAssemblies(_env);
```
Comment (Zruty0) [inline src/Microsoft.ML.Legacy/PredictionModel.cs]: >RegisterAssemblies [](start = 33, length = 18)

do we need the same thing fir `TransformModel`?

Comment (ganik) [reply src/Microsoft.ML.Legacy/PredictionModel.cs]: This is only needed for Legacy namespace.

---
In reply to: [233615020](https://github.com/dotnet/machinelearning/pull/1570#discussion_r233615020) [](ancestors = 233615020)
