### PR TITLE
Fix Dnn image featurizer and Onnx XML documentation

### LINKED ISSUE #3542: Fix the Onnx XML doc and the DNN featurizer XML doc
The xml doc can be improved. There are some comments that were meant to be code documentation rather than user facing documentation.

The documentation for an estimator is on the transformer.

### PR DESCRIPTION
**Pull request by artidoro**
Fixes #3542.

### CODE REVIEW

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 1]
```diff
@@ -8,20 +8,21 @@
...
+    // This is a helper class that is required to use the <see cref="DnnImageFeaturizerEstimator"/>.
+    // Note that by default, it is not usable as it does not have any valid methods that return an <see cref="EstimatorChain{TLastTransformer}"/>
+    // that is used by the DnnImageFeaturizeEstimator.
+    // In order to use this, at least one model project with the corresponding extension methods must by included.
     /// <summary>
-    /// This is a helper class that is required to use the <see cref="DnnImageFeaturizerEstimator"/>.
-    /// Note that by default, it is not usable as it does not have any valid methods that return an <see cref="EstimatorChain{TLastTransformer}"/>
-    /// that is used by the DnnImageFeaturizeEstimator.
-    /// In order to use this, at least one model project with the corresponding extension methods must by included.
+    /// Helper class whose extension methods allow to select a pre-trained DNN image featurization model to use in the <see cref="DnnImageFeaturizerEstimator"/>.
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >whose extension methods allow to select [](start = 21, length = 39)

for selecting

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 2]
```diff
@@ -8,20 +8,21 @@
...
     /// </summary>
     /// <seealso cref="OnnxCatalog.DnnFeaturizeImage(TransformsCatalog, string, Func{DnnImageFeaturizerInput, EstimatorChain{ColumnCopyingTransformer}}, string)"/>
     public sealed class DnnImageModelSelector
     {
     }
 
     /// <summary>
-    /// This is a helper class used to store all the inputs to an extension method on a DnnImageModelSelector required to return
-    /// a chain of two <see cref="OnnxScoringEstimator"/>s.
+    /// This is a helper class used to store all the inputs to an extension method on a <see cref="DnnImageModelSelector"/> required to return
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >This is a helper class used to store [](start = 8, length = 36)

Helper class for storing

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 3]
```diff
@@ -41,10 +42,7 @@ internal DnnImageFeaturizerInput(string outputColumnName, string inputColumnName
     }
 
     /// <summary>
-    /// The Dnn Image Featurizer is a wrapper around two <see cref="OnnxScoringEstimator"/> and three <see cref="ColumnCopyingEstimator"/>
-    /// with present pretrained DNN models. The ColumnsCopying are there to allow arbitrary column input and output names, as by default
-    /// the ONNXTransformer requires the names of the columns to be identical to the names of the ONNX model nodes.
-    /// Note that because of this, it only works on Windows machines, as that is a constraint of the OnnxTransformer.
+    /// Applies a pre-trained deep neural network (DNN) model to featurize image input data.
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >image input data [](start = 75, length = 16)

input image data

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 4]
```diff
@@ -55,7 +53,18 @@ internal DnnImageFeaturizerInput(string outputColumnName, string inputColumnName
     /// | Does this estimator need to look at the data to train its parameters? | No |
     /// | Input column data type | Vector of <xref:System.Single> |
     /// | Output column data type | Vector of <xref:System.Single>, the size of the vector depends on the pre-trained DNN |
+    /// | Required NuGet in addition to Microsoft.ML | Microsoft.ML.OnnxTransformer and Microsoft.ML.OnnxRuntime or Microsoft.ML.OnnxRuntime.Gpu|
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: Let's delete this row, and expand it to a section: 

### NuGet requirements. 
* Microsoft.ML.OnnxTransformer
* Microsoft.ML.OnnxRuntime
* Microsoft.ML.OnnxRuntime.Gpu (only if GPU processing is used)
* Each pre-trained DNN model has a separate NuGet that must be included if that model is used:
 ** mention the models with their nuget info

File: src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs [hunk 5]
```diff
@@ -12,7 +12,7 @@ namespace Microsoft.ML
     public static class OnnxCatalog
     {
         /// <summary>
-        /// Applies a pre-trained Onnx model.
+        /// Create a <see cref="OnnxScoringEstimator"/>, which applies a pre-trained Onnx model to the input column.
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs]: > to the input column. [](start = 95, length = 21)

there's no input column param. should we add this? 

How about this: Input/output columns are determined based on the input/output columns of the provided ONNX model.

File: src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs [hunk 6]
```diff
@@ -12,7 +12,7 @@ namespace Microsoft.ML
...
         /// </summary>
         /// <remarks>
         /// All column names are provided, the input data column names/types must exactly match
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs]: >All column names are provided, the input data column names/types [](start = 12, length = 64)

The name/type of input columns must exactly match name/type of the ONNX model inputs. The name/type of the produced output columns will match name/type of the ONNX model outputs.

**Comment by shmoradims** [comment]
>         /// specified by the model.

The name/type of input columns must exactly match name/type of the ONNX model inputs. The name/type of the produced output columns will match name/type of the ONNX model outputs.

---
Refers to: src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs:20 in a7ada6f. [](commit_id = a7ada6ff37aa21685aef5e649100462036948ee1, deletion_comment = False)

File: src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs [hunk 7]
```diff
@@ -54,7 +54,7 @@ public static class OnnxCatalog
         => new OnnxScoringEstimator(CatalogUtils.GetEnvironment(catalog), new[] { outputColumnName }, new[] { inputColumnName }, modelFile, gpuDeviceId, fallbackToCpu);
 
         /// <summary>
-        /// Applies a pre-trained Onnx model.
+        /// Create a <see cref="OnnxScoringEstimator"/>, which applies a pre-trained Onnx model to the <paramref name="inputColumnNames"/> columns.
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs]: >Onnx [](start = 85, length = 4)

let's go with ONNX (all caps)

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs [hunk 8]
```diff
@@ -514,8 +488,35 @@ public NamedOnnxValue GetNamedOnnxValue()
...
+    /// <remarks>
+    /// <format type="text/markdown"><![CDATA[
+    ///
+    /// ###  Estimator Characteristics
+    /// |  |  |
+    /// | -- | -- |
+    /// | Does this estimator need to look at the data to train its parameters? | No |
+    /// | Input column data type | Known-sized vector of <xref:System.Single> or <xref:System.Double> types |
+    /// | Output column data type | As specified by the Onnx model |
+    /// | Required NuGet in addition to Microsoft.ML | Microsoft.ML.OnnxRuntime or Microsoft.ML.OnnxRuntime.Gpu |
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: >Microsoft.ML.OnnxRuntime or Microsoft.ML.OnnxRuntime.Gpu [](start = 55, length = 56)

Microsoft.ML.OnnxRuntime (always),  Microsoft.ML.OnnxRuntime.Gpu (only if using GPU device)

File: src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs (hunk 5 above)
Comment (artidoro) [reply src/Microsoft.ML.OnnxTransformer/OnnxCatalog.cs]: Sounds good!


---
In reply to: [277866453](https://github.com/dotnet/machinelearning/pull/3543#discussion_r277866453) [](ancestors = 277866453)

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 9]
```diff
@@ -8,20 +8,21 @@
...
     /// <seealso cref="OnnxCatalog.DnnFeaturizeImage(TransformsCatalog, string, Func{DnnImageFeaturizerInput, EstimatorChain{ColumnCopyingTransformer}}, string)"/>
     public sealed class DnnImageModelSelector
     {
     }
 
     /// <summary>
-    /// This is a helper class used to store all the inputs to an extension method on a DnnImageModelSelector required to return
-    /// a chain of two <see cref="OnnxScoringEstimator"/>s.
+    /// Helper class for storing all the inputs to an extension method on a <see cref="DnnImageModelSelector"/> required to return
+    /// a chain of two <see cref="OnnxScoringEstimator"/>.
```
Comment (ganik) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >>. [](start = 56, length = 2)

I think you need "s" at the end:  aka "chain of two estimatorS"

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 10]
```diff
@@ -56,6 +54,26 @@ internal DnnImageFeaturizerInput(string outputColumnName, string inputColumnName
     /// | Input column data type | Vector of <xref:System.Single> |
     /// | Output column data type | Vector of <xref:System.Single>, the size of the vector depends on the pre-trained DNN |
     ///
+    /// NuGet requirements:
+    ///	- Microsoft.ML.OnnxTransformer
+    /// - Microsoft.ML.OnnxRuntime(question: does OnnxTransformer already pull OnnxRuntime as dependency? if so we don't need to add this)
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >(question: does OnnxTransformer already pull OnnxRuntime as dependency? if so we don't need to add this) [](start = 34, length = 104)

this was a question for you, please remove it

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 11]
```diff
@@ -56,6 +54,26 @@ internal DnnImageFeaturizerInput(string outputColumnName, string inputColumnName
...
+    /// - Microsoft.ML.OnnxRuntime.Gpu(only if GPU processing is used)
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: space: Gpu (

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs [hunk 12]
```diff
@@ -56,6 +54,26 @@ internal DnnImageFeaturizerInput(string outputColumnName, string inputColumnName
...
+    /// - Each pre-trained DNN model has a separate NuGet that must be included if that model is used:
+    ///     - Microsoft.ML.DnnImageFeaturizer.AlexNet
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >     [](start = 8, length = 4)

let's use 2-spaces instead of 4, for the next level indentation. 4 might make the parser confuse it with code block.

File: src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs (hunk 10 above)
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/DnnImageFeaturizerTransform.cs]: >- Microsoft.ML.OnnxRuntime(question: does OnnxTransformer already pull OnnxRuntime as dependency? if so we don't need to add this) [](start = 8, length = 130)

please remove Microsoft.ML.OnnxRuntime requirement. It's already included in Microsoft.ML.OnnxTransformer

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs [hunk 13]
```diff
@@ -514,8 +488,35 @@ public NamedOnnxValue GetNamedOnnxValue()
...
+    /// <remarks>
+    /// <format type="text/markdown"><![CDATA[
+    ///
+    /// ###  Estimator Characteristics
+    /// |  |  |
+    /// | -- | -- |
+    /// | Does this estimator need to look at the data to train its parameters? | No |
+    /// | Input column data type | Known-sized vector of <xref:System.Single> or <xref:System.Double> types |
+    /// | Output column data type | As specified by the ONNX model |
+    /// | Required NuGet in addition to Microsoft.ML | Microsoft.ML.OnnxRuntime (always),  Microsoft.ML.OnnxRuntime.Gpu (only if using GPU device) |
```
Comment (shmoradims) [inline src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: > Microsoft.ML.OnnxRuntime (always),  Microsoft.ML.OnnxRuntime.Gpu (only if using GPU device)  [](start = 54, length = 93)

this is the correct one:

Microsoft.ML.OnnxTransformer (always), Microsoft.ML.OnnxRuntime.Gpu (only if GPU processing is used)
