### PR TITLE
Updated MultiFileSource.Load to fix inconsistent behavior with multiple files

### LINKED ISSUE #4982: TextLoader Load From Multiple Files Inconsistent Behavior
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 3.1
- **ML.NET Version (eg., dotnet --info)**: 1.5.0-preview2

### Issue

When loading data that is in multiple files, whether the data is in a single folder or multiple folders, the behavior in inconsistent. When the data is in a single folder, wildcards can be used. That, however is not the case when the data is in separate folders/subfolders.

The non-working examples don't work for various reasons. However, in general, the behavior appears inconsistent depending on the structure of the folder.

### Source code / logs
Data Folder Structure:

image

Data Sample:

```text
Size (Sq. ft.), HistoricalPrice1 ($), HistoricalPrice2 ($), HistoricalPrice3 ($), Current Price ($)
700, 100000, 3000000, 250000, 500000
```

Source code:

```csharp
class Program
    {
        static void Main(string[] args)
        {
            MLContext ctx = new MLContext();

            TextLoader textLoader = ctx.Data.CreateTextLoader<HousingData>(separatorChar: ',', hasHeader: true);

            IDataView dvSingleFolder = textLoader.Load("Data/*");
            IDataView dvMultipleFoldersNotWorking = textLoader.Load("DataFolder/*/*");
            IDataView dvMultipleFoldersNotWorking2 = textLoader.Load("DataFolder/SubFolder1/*", "DataFolder/SubFolder2/*");
            IDataView dvMultileFoldersWorking = textLoader.Load("DataFolder/SubFolder1/1.csv", "DataFolder/SubFolder2/2.csv");

            var singleFolderPreview = dvSingleFolder.Preview();
            var multipleFolderPreview = dvMultipleFoldersNotWorking.Preview();
            var multipleFolderPreview2 = dvMultipleFoldersNotWorking2.Preview();
            var multipleFoldersWorkingPreview = dvMultileFoldersWorking.Preview();
        }
    }

public class HousingData
    {
        [LoadColumn(0)]
        public float Size { get; set; }

        [LoadColumn(1, 3)]
        [VectorType(3)]
        public float[] HistoricalPrices { get; set; }

        [LoadColumn(4)]
        [ColumnName("Label")]
        public float CurrentPrice { get; set; }
    }
```

### PR DESCRIPTION
**Pull request by mstfbl**
Fixes #4982 

MultiFileSource's `Load` can now accommodate loading from multiple paths. Also added more test cases for the additional features of `MultiFileSource`.

Example usages:
`textLoader.Load("Data/*");`
`textLoader.Load("DataFolder/.../*");`
`textLoader.Load("DataFolder/SubFolder1/*", "DataFolder/SubFolder2/*");`
`textLoader.Load("DataFolder/SubFolder1/1.csv", "DataFolder/SubFolder2/2.csv");`

### CODE REVIEW

File: test/Microsoft.ML.Core.Tests/UnitTests/FileSource.cs [hunk 1]
```diff
@@ -41,7 +41,40 @@ public void MultiFileSourceUnitTest()
...
+            var fileDataB = Path.Combine(dataDir, "b.txt");
+
+            File.WriteAllText(fileDataA, "Unit Test");
+            File.WriteAllText(fileDataB, "Unit Test");
+
+            var dataFolderDir = Directory.CreateDirectory("MultiFileSourceUnitTest/DataFolder").FullName;
+            var subFolder1Dir = Directory.CreateDirectory("MultiFileSourceUnitTest/DataFolder/SubFolder1").FullName;
+            var subFolder2Dir = Directory.CreateDirectory("MultiFileSourceUnitTest/DataFolder/SubFolder2").FullName;
+
+            var fileDataSA = Path.Combine(subFolder1Dir, "a.txt");
```
Comment (frank-dong-ms) [inline test/Microsoft.ML.Core.Tests/UnitTests/FileSource.cs:67]: >fileDataSA [](start = 16, length = 10)

please delete test folder/file after you finish the unit test

**Comment by frank-dong-ms** [comment]
is there any place to describe the correct usage of wildcard of directory like below?
textLoader.Load("DataFolder/.../*");

**Comment by mstfbl** [comment]
@frank-dong-ms A description of the correct usage of wildcards for `MultiFileSource` doesn't exist in the original codebase. I have added a description on usage of wildcards with `MultiFileSource` to its XML documentation as a part of this PR.
