### PR TITLE
Cumulative bug bash fixes

### LINKED ISSUE #3467: Issues with KeyToValueMappingEstimator  documentation
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.keytovaluemappingestimator?view=ml-dotnet&branch=smoke-test-preview

>Utilizes KeyValues Microsoft.ML.Data.AnnotationInfo 

that part looks broken, no links, not sure what `KeyValues` means...

>Zero values of the KeyDataViewType

Missing values probably.

>Input column data type | key

I would prefer capital Key.

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.mapkeytovalue?view=ml-dotnet&branch=smoke-test-preview
> /// It is possible to have multiple values map to the same category.

Press `X` to doubt. I'm not sure we can have value "A" and "B" be mapped on key 1. Even if that's the case, what would happened if `MapKeyToValue` encounter key with value 1, would it be "A" or "B"?

>// at this point, the Label colum is tranformed from strings, to DataViewKeyType and

Capital letter. DataViewKeyType  need to be `<see cref>` (it's KeyDataViewType btw).
>  // the transformation has added the PredictedLabel column, with 

Some one just drop the sentence.

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.mapkeytovalue?view=ml-dotnet&branch=smoke-test-preview#Microsoft_ML_ConversionsExtensionsCatalog_MapKeyToValue_Microsoft_ML_TransformsCatalog_ConversionTransforms_System_String_System_String_

>// Get a small dataset as an IEnumerable and load it into ML.NET data set.
            IEnumerable<DatasetUtils.SampleTopicsData> data = DatasetUtils.GetTopicsData();

Are we ok with SamplesUtils?

In general that samples looks like it need some rewriting. Python_Names, printHelper in the middle of sample, GetColumn operates over `VBuffer`

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.mapvaluetokey?view=ml-dotnet&branch=smoke-test-preview#Microsoft_ML_ConversionsExtensionsCatalog_MapValueToKey_Microsoft_ML_TransformsCatalog_ConversionTransforms_Microsoft_ML_InputOutputColumnPair___System_Int32_Microsoft_ML_Transforms_ValueToKeyMappingEstimator_KeyOrdinality_System_Boolean_Microsoft_ML_IDataView_

> Warning 
It looks like the sample you are looking for has moved! Rest assured we are working on resolving this.

This does't looks right.

### LINKED ISSUE #3470: Issues with ValueToKeyMappingEstimator documentation
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.valuetokeymappingestimator?view=ml-dotnet&branch=master
>Converts input values (words, numbers, etc.) to index in a dictionary.

It converts data to KeyDataViewType.

>but can be defined through other means: either with the mapping defined directly on the command line, or as loaded from an external file.

Press 'X' to doubt. I don't see such methods, and that line was clearly taken from TLC documentation. Well maybe that  `Microsoft.ML.IDataView keyData = null` in sample, but that sentence need more polishing.

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.valuetokeymappingtransformer?view=ml-dotnet&branch=master

>The TextToKeyConverter transform builds up term vocabularies (dictionaries). The TextToKeyConverter and the Microsoft.ML.Transforms.HashConverter

What is TextToKeyConverter?

Methods table looks weird.

https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.conversionsextensionscatalog.mapvaluetokey?view=ml-dotnet&branch=master

Examples is absent.
> Warning It looks like the sample you are looking for has moved! Rest assured we are working on resolving this.

### LINKED ISSUE #3476: Issues with KeyToVectorMappingEstimator
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.keytovectormappingestimator?view=ml-dotnet&branch=smoke-test-preview

>Input column data type | key

I would prefer capital Key.

>Estimator for KeyToVectorMappingTransformer. Converts the key types back to their original vectors.

I don't think this is good description. It implies my original value was vector, which not always the true.

>The input and output columns. The new column's data type is a vector of Single representing the original value.

It's not original value. 

in sample we have following:
>mlContext.Transforms.Conversion.MapKeyToVector("CategoryVector", "Category", outputCountVector: true
Whether to combine multiple indicator vectors into a single vector of counts instead of concatenating them. This is only relevant when the input column is a vector of keys.

Why we turn this option if it's pointless for single key which Category column contains?

### LINKED ISSUE #3487: Issues with BootstrapSample documentation
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.dataoperationscatalog.bootstrapsample?view=ml-dotnet&branch=smoke-test-preview#Microsoft_ML_DataOperationsCatalog_BootstrapSample_Microsoft_ML_IDataView_System_Nullable_System_Int32__System_Boolean_

>Take an approximate bootstrap sample of input.

That's a really bad description of that it does.

>IEnumerable<Microsoft.ML.SamplesUtils.DatasetUtils.BinaryLabelFloatFeatureVectorFloatWeightSample> enumerableOfData = Microsoft.ML.SamplesUtils.DatasetUtils.GenerateBinaryLabelFloatFeatureVectorFloatWeightSamples(5);

Would be nice to replace SampleUtils with something in sample itself.

>Whether this is the out-of-bag sample, that is, all those rows that are not selected by the transform. Can be used to create a complementary pair of samples by using the same seed.

Am I only one who struggling with this description?

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes #3476 
Fixes #3470 
Fixes #3487
Fixes #3467

### CODE REVIEW

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs [hunk 1]
```diff
@@ -19,56 +20,62 @@ public static void Example()
...
+                new DataPoint() { Timeframe = 8, PartA=3, PartB=2},
+                new DataPoint() { Timeframe = 3, PartA=3, PartB=3}
             };
 
             var data = mlContext.Data.LoadFromEnumerable(rawData);
 
-            // Constructs the ML.net pipeline
+            // First transform just maps key type to indicator vector. i.e. it's produces vector of zeros with size of
+            // key cardinality and set 1 to corresponding key's value index in that array.
+            // Next we create vector of keys (same cardinality) and apply two transforms for them.
```
Comment (abgoswam) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs]: >Next we create vector of keys (same cardinality) and apply two transforms for them. [](start = 15, length = 83)

to me the explanation/example sounds confusing:

a) there are 5 transforms in the pipeline, the wording sounds like there are 3 
b)  after concatenation, we do MapValueToKey -- seems out of purview of the API  we are trying to explain  (MapKeyToVector)
c)  need to explain if MapValueToKey  would work on both slots  independently
d) `indexes in array` sounds confusing ..  what would happen if PartA=0 in one of the rows

File: docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs [hunk 2]
```diff
@@ -12,24 +11,17 @@ public static void Example()
...
-            IEnumerable<Microsoft.ML.SamplesUtils.DatasetUtils.BinaryLabelFloatFeatureVectorFloatWeightSample> enumerableOfData = Microsoft.ML.SamplesUtils.DatasetUtils.GenerateBinaryLabelFloatFeatureVectorFloatWeightSamples(5);
-            var data = mlContext.Data.LoadFromEnumerable(enumerableOfData);
+            // Get a small dataset as an IEnumerable.
+            var rawData = new[] {
+                new DataPoint() { Label = true, Feature = 1.017325f},
+                new DataPoint() { Label = false, Feature = 0.6326591f},
+                new DataPoint() { Label = false, Feature = 0.0326252f},
+                new DataPoint() { Label = false, Feature = 0.8426974f},
+                new DataPoint() { Label = true, Feature = 0.9947656f},
+                new DataPoint() { Label = true, Feature=1.017325f},
```
Comment (artidoro) [inline docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs]: >Feature=1 [](start = 48, length = 9)

nit: add extra space.

Good job on picking up this SampleUtils reference!

File: src/Microsoft.ML.Data/Transforms/KeyToVector.cs [hunk 3]
```diff
@@ -723,15 +723,11 @@ private bool SaveAsOnnxCore(OnnxContext ctx, int iinfo, ColInfo info, string src
     }
 
     /// <summary>
-    /// Estimator for <see cref="KeyToVectorMappingTransformer"/>. Converts the key types back to their original vectors.
-    /// </summary>
-    /// <summary>
-    /// Utilizes KeyValues <see cref="AnnotationInfo"/> of the input column, to map keys to a vector representing the original value.
-    /// Maps zero values of the <see cref="KeyDataViewType"/> are mapped to the <see langword="default"/> value of the output type.
+    /// Estimator for <see cref="KeyToVectorMappingTransformer"/>. Maps the value of a key
+    /// into a floating point vector representing the value.
```
Comment (artidoro) [inline src/Microsoft.ML.Data/Transforms/KeyToVector.cs]: >floating point [](start = 15, length = 14)

Should we avoid float in the descriptions? maybe: known-sized vector of <see cref="System.Single"/>

**Comment by abgoswam** [comment]
>     /// | Input column data type | [key](xref:Microsoft.Ml.Data.KeyDataViewType) |

i believe you also want to change this to `Key`

---
Refers to: src/Microsoft.ML.Data/Transforms/KeyToVector.cs:735 in 33f42be. [](commit_id = 33f42be6c25e0190ac20d0c4e6c0e484d1920e75, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
>     /// | Input column data type | [key](xref:Microsoft.Ml.Data.KeyDataViewType) |

I wanted, by they decided to go with lower case key. We have humble types is ml.net

---
In reply to: [485967242](https://github.com/dotnet/machinelearning/pull/3539#issuecomment-485967242) [](ancestors = 485967242)

---
Refers to: src/Microsoft.ML.Data/Transforms/KeyToVector.cs:735 in 33f42be. [](commit_id = 33f42be6c25e0190ac20d0c4e6c0e484d1920e75, deletion_comment = False)

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs (hunk 1 above)
Comment (Ivanidzo4ka) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs]: not sure how much better and cleaner it become, but hey, I tried!

Main reason why i'm doing concat + term is because we don't have other way to produce vector of keys, which I wanted to show off for `outputCountVector` parameter.

---
In reply to: [277855878](https://github.com/dotnet/machinelearning/pull/3539#discussion_r277855878) [](ancestors = 277855878)

File: docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs (hunk 2 above)
Comment (Ivanidzo4ka) [reply docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs]: [https://media0.giphy.com/media/YYfEjWVqZ6NDG/source.gif](https://media0.giphy.com/media/YYfEjWVqZ6NDG/source.gif)

---
In reply to: [277856475](https://github.com/dotnet/machinelearning/pull/3539#discussion_r277856475) [](ancestors = 277856475)

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs [hunk 4]
```diff
@@ -13,83 +13,65 @@ public static void Example()
...
-            // "car truck driver bus pickup horse"
+            var trainData = mlContext.Data.LoadFromEnumerable(rawData);
 
             // A pipeline to convert the terms of the 'Review' column in 
             // making use of default settings.
-            string defaultColumnName = "DefaultKeys";
-            // REVIEW create through the catalog extension
-            var default_pipeline = ml.Transforms.Text.TokenizeIntoWords("Review")
-                .Append(ml.Transforms.Conversion.MapValueToKey(defaultColumnName, "Review"));
+            var defaultPipeline = mlContext.Transforms.Text.TokenizeIntoWords("TokenizedText", "Review")
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs]:
```suggestion
            var defaultPipeline = mlContext.Transforms.Text.TokenizeIntoWords("TokenizedText", nameof(DataPoint.Review))
```

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs [hunk 5]
```diff
@@ -13,83 +13,65 @@ public static void Example()
...
+                .Append(mlContext.Transforms.Conversion.MapValueToKey("Keys", "TokenizedText"));
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs]:
```suggestion
                .Append(mlContext.Transforms.Conversion.MapValueToKey(nameof(TransformedData.Keys), "TokenizedText"));
```

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs [hunk 6]
```diff
@@ -13,83 +13,65 @@ public static void Example()
...
 
             // Another pipeline, that customizes the advanced settings of the ValueToKeyMappingEstimator.
             // We can change the maximumNumberOfKeys to limit how many keys will get generated out of the set of words, 
             // and condition the order in which they get evaluated by changing keyOrdinality from the default ByOccurence (order in which they get encountered) 
             // to value/alphabetically.
-            string customizedColumnName = "CustomizedKeys";
-            var customized_pipeline = ml.Transforms.Text.TokenizeIntoWords("Review")
-                .Append(ml.Transforms.Conversion.MapValueToKey(customizedColumnName, "Review", maximumNumberOfKeys: 10, keyOrdinality: ValueToKeyMappingEstimator.KeyOrdinality.ByValue));
+            var customizedPipeline = mlContext.Transforms.Text.TokenizeIntoWords("TokenizedText", "Review")
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs]: Would you consider `nameof` to define input and output column names?

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs [hunk 7]
```diff
@@ -13,83 +13,65 @@ public static void Example()
...
+            //  Keys
+            //  1,2,4,5,7,8
+            //  8,2,9,7,6,4
+            //  3,10,0,0,0
+            //  3,10,0,0,0,8
             // Retrieve the original values, by appending the KeyToValue etimator to the existing pipelines
             // to convert the keys back to the strings.
-            var pipeline = default_pipeline.Append(ml.Transforms.Conversion.MapKeyToValue(defaultColumnName));
-            transformedData_default = pipeline.Fit(trainData).Transform(trainData);
+            var pipeline = defaultPipeline.Append(mlContext.Transforms.Conversion.MapKeyToValue("Keys"));
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs]: Same here. I'd slightly prefer `nameof` over explicit string.

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs [hunk 8]
```diff
@@ -41,33 +34,71 @@ public static void Example()
             // Typically predictions would be in a different, validation set. 
             var dataWithPredictions = pipeline.Fit(dataView).Transform(dataView);
 
-            // at this point, the Label colum is tranformed from strings, to DataViewKeyType and
-            // the transformation has added the PredictedLabel column, with 
-            var newPipeline = mlContext.Transforms.Conversion.MapKeyToValue(new[] 
+            // At this point, the Label colum is tranformed from strings, to DataViewKeyType and
+            // the transformation has added the PredictedLabel column, with same DataViewKeyType as
+            // transformed Label column.
+            // MapKeyToValue would take columns with DataViewKeyType and convert them back to thier original values.
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs]: Please provide an example. Original value is not a super clear term.
```
Assume the original labels are "Good"/"Fair"/"Bad" and they are respectively be mapped to keys 1/2/3.
This transform maps 1/2/3 back to "Good"/"Fair"/"Bad".
```

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs [hunk 9]
```diff
@@ -41,33 +34,71 @@ public static void Example()
...
                 new InputOutputColumnPair("PredictedLabelOriginalValue","PredictedLabel")
             });
 
             var transformedData = newPipeline.Fit(dataWithPredictions).Transform(dataWithPredictions);
-
+            // Let's iterate over first 5 items.
+            transformedData = mlContext.Data.TakeRows(transformedData, 5);
             var values = mlContext.Data.CreateEnumerable<TransformedData>(transformedData, reuseRowObject: false);
 
             // Printing the columns of the transformed data.
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs]:
```suggestion
            // Printing the column names of the transformed data. 
```

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs [hunk 10]
```diff
@@ -41,33 +34,71 @@ public static void Example()
...
 
             var transformedData = newPipeline.Fit(dataWithPredictions).Transform(dataWithPredictions);
-
+            // Let's iterate over first 5 items.
+            transformedData = mlContext.Data.TakeRows(transformedData, 5);
             var values = mlContext.Data.CreateEnumerable<TransformedData>(transformedData, reuseRowObject: false);
 
             // Printing the columns of the transformed data. 
-            Console.WriteLine($" Label   LabelOriginalValue   PredictedLabel   PredictedLabelOriginalValue");
+            Console.WriteLine($"Label   LabelOriginalValue   PredictedLabel   PredictedLabelOriginalValue");
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToValueMultiColumn.cs]:
```suggestion
            Console.WriteLine($"Label   LabelOriginalValue   PredictedLabel   PredictedLabelOriginalValue");
            // Print content per column.
```

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs [hunk 11]
```diff
@@ -19,56 +20,62 @@ public static void Example()
...
+                new DataPoint() { Timeframe = 8, PartA=1, PartB=2},
+                new DataPoint() { Timeframe = 7, PartA=2, PartB=1},
+                new DataPoint() { Timeframe = 8, PartA=3, PartB=2},
+                new DataPoint() { Timeframe = 3, PartA=3, PartB=3}
             };
 
             var data = mlContext.Data.LoadFromEnumerable(rawData);
 
-            // Constructs the ML.net pipeline
+            // First transform just maps key type to indicator vector. i.e. it's produces vector filled with
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapKeyToVector.cs]: Very awesome description!!!

**Comment by shmoradims** [comment]
>             //  False   0.0326252

did the data change? is the output here changed?

---
Refers to: docs/samples/Microsoft.ML.Samples/Dynamic/DataOperations/BootstrapSample.cs:53 in 95fd30d. [](commit_id = 95fd30de4a2d35d96c97b49fa4b88d6fff9d7c8f, deletion_comment = False)

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs [hunk 12]
```diff
@@ -13,83 +13,65 @@ public static void Example()
...
+            IEnumerable<TransformedData> customizedData = mlContext.Data.CreateEnumerable<TransformedData>(transformedDataCustomized, reuseRowObject: false);
+            Console.WriteLine($"Keys");
+            foreach (var dataRow in defaultData)
+                Console.WriteLine($"{string.Join(',', dataRow.Keys)}");
+            // Expected output:
+            //  Keys
+            //  1,2,3,4,5,6
+            //  6,2,7,5,8,3
+            //  9,10,11,12,13
+            //  9,10,11,12,13,6
```
Comment (shmoradims) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs]: please verify, if input data has changed.

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValue.cs [hunk 13]
```diff
@@ -85,6 +85,7 @@ private class DataPoint
             public int Score { get; set; }
         }
 
+
```
Comment (shmoradims) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/MapValue.cs]: revert

File: src/Microsoft.ML.Data/Transforms/KeyToVector.cs [hunk 14]
```diff
@@ -723,15 +723,11 @@ private bool SaveAsOnnxCore(OnnxContext ctx, int iinfo, ColInfo info, string src
     }
 
     /// <summary>
-    /// Estimator for <see cref="KeyToVectorMappingTransformer"/>. Converts the key types back to their original vectors.
-    /// </summary>
-    /// <summary>
-    /// Utilizes KeyValues <see cref="AnnotationInfo"/> of the input column, to map keys to a vector representing the original value.
-    /// Maps zero values of the <see cref="KeyDataViewType"/> are mapped to the <see langword="default"/> value of the output type.
+    /// Estimator for <see cref="KeyToVectorMappingTransformer"/>. Maps the value of a key
+    /// into a known-sized vector of <see cref="System.Single"/>.
```
Comment (shmoradims) [inline src/Microsoft.ML.Data/Transforms/KeyToVector.cs]: >. [](start = 64, length = 1)

let's add that [the vector is the binary representation of the key value]

File: docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs (hunk 12 above)
Comment (Ivanidzo4ka) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Transforms/Conversion/KeyToValueToKey.cs]: I got them from my console output.

---
In reply to: [277895084](https://github.com/dotnet/machinelearning/pull/3539#discussion_r277895084) [](ancestors = 277895084)
