### PR TITLE
use parameter to save choice object

### LINKED ISSUE #6299: ChoiceAttribution doesn't work with int type.
reproduction

```csharp
class Param
{
   [Choice(1,2,3)]
   public int Index {get; set;}
}

// throw exception
var ss = new SearchSpace<Param>();
var tuner = new RandomTuner(ss);
tuner.Propose()
```

### PR DESCRIPTION
**Pull request by LittleLittleCloud**
We are excited to review your PR.

So we can do the best job, please check:

- [x There's a descriptive title that will make sense to other developers some time from now. 
- [x] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
- [x] Your change description explains what the change does, why you chose your approach, and anything else that reviewers should know.
- [x] You have included any necessary tests in the same PR.

fix #6299

### CODE REVIEW

**Comment by LittleLittleCloud** [comment]
WT*
/azp run

File: src/Microsoft.ML.SearchSpace/Attribute/ChoiceAttribute.cs [hunk 1]
```diff
@@ -26,7 +26,7 @@ public ChoiceAttribute(params object[] candidates)
             var candidatesType = candidates.Select(o => o.GetType()).Distinct();
             Contracts.Assert(candidatesType.Count() == 1, "multiple candidates type detected");
 
-            Option = new ChoiceOption(candidates.Select(c => Convert.ToString(c, CultureInfo.InvariantCulture)).ToArray());
```
Comment (tarekgh) [inline src/Microsoft.ML.SearchSpace/Attribute/ChoiceAttribute.cs:29]: >candidates [](http://example.com/codeflow?start=38&length=10)

why you need to call ToArray if `candidates` itself is array? this apply to other change in this file.

File: src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs [hunk 2]
```diff
@@ -68,9 +68,8 @@ public override double[] MappingToFeatureSpace(Parameter param)
                 return new double[0];
             }
 
-            var value = param.AsType<object>();
-            var x = Array.BinarySearch(Choices, value);
-            Contracts.Check(x != -1, $"{value} not contains");
+            var x = Array.IndexOf(Choices, param);
+            Contracts.Check(x != -1, $"{param} not contains");
```
Comment (tarekgh) [inline src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs:72]: >x != -1 [](http://example.com/codeflow?start=28&length=7)

make this `< 0`

File: src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs [hunk 3]
```diff
@@ -26,7 +26,7 @@ public ChoiceOption(params object[] choices)
             var distinctChoices = choices.Distinct();
             Contracts.Check(distinctChoices.Count() == choices.Length, "choices must not contain repeated values");
 
-            Choices = distinctChoices.OrderBy(x => x).ToArray();
+            Choices = distinctChoices.Select(o => Parameter.FromObject(o)).ToArray();
```
Comment (tarekgh) [inline src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs:29]: >Select [](http://example.com/codeflow?start=38&length=6)

Do we care optimizing the allocations in such places? I am asking because `Select()` will create intermediate object and then we'll create the array from that result.

File: src/Microsoft.ML.SearchSpace/Attribute/ChoiceAttribute.cs (hunk 1 above)
Comment (LittleLittleCloud) [reply src/Microsoft.ML.SearchSpace/Attribute/ChoiceAttribute.cs:29]: ### Resolved

File: src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs (hunk 3 above)
Comment (LittleLittleCloud) [reply src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs:29]: Not quite care, as in most of the cases the candidate value for `choice` will not exceed 10, and this constructor only gets called once during training (when creating `choice` option). So the major cost will still be the training cost.

File: src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs (hunk 2 above)
Comment (LittleLittleCloud) [reply src/Microsoft.ML.SearchSpace/Option/ChoiceOption.cs:72]: ### Resolved

**Review by tarekgh — APPROVED** [review]
