### PR TITLE
Provide proper calling conversion for x86 framework

### LINKED ISSUE #1721: StochasticDualCoordinateAscentClassifier issue when x86 (32 bits)
### System information

- **OS version/distro**:
Windows 10
- **.NET Version (eg., dotnet --info)**: 
4.6.1
### Issue

- **What did you do?**
try to use StochasticDualCoordinateAscentClassifier as classifier on My ML application
- **What happened?**
i ran it through 86x and through the following exception

> Managed Debugging Assistant 'PInvokeStackImbalance' 
  Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Microsoft.ML.CpuMath!Microsoft.ML.Runtime.Internal.CpuMath.Thunk::SumSqU' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

- **What did you expect?**
it should work normally in 86x as it work fine with 64 and this exception occur only with 86x and i need to run it with 86 

### Source code / logs
```pipeline.Add(CollectionDataSource.Create(noramalTagsTrainingData));
pipeline.Add(new Dictionarizer("Label"));
// Transform any text feature to numeric values
pipeline.Add(new CategoricalOneHotVectorizer(
"fontColor",
"tagText",
"firstWord"
));
pipeline.Add(new ColumnConcatenator(
"Features",
"fontSize",
"isBold",
"isItalic",
"isUnderLine",
"containsDot",
"containsQuestionMark",
"isAllCaps",
"tagText",
"firstWord"
));
pipeline.Add(new StochasticDualCoordinateAscentClassifier
            {
                MaxIterations = 100,
                NumThreads = 7,
                LossFunction = new SmoothedHingeLossSDCAClassificationLossFunction()
            });
pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });

 // The pipeline is trained on the dataset that has been loaded and transformed.
var model = pipeline.Train<NormalTagsModelFeatures, NormalTagsPrediction>();
```

it through the exception at last line within only 86x

any help please
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes #1721 
Right now if we call our nuget from .net framework 4.6 x86, we get ugly PInvokeStackImbalance exception.

I've check and it looks like we build our native libraries in __csdecl conversion which is standard for C and we have 
`#define EXPORT_API(ret) extern "C" __declspec(dllexport) ret` in our stdafx.h file.
by default PInvoke use WinApi convention which falls down to _stdcall.

On x64 platforms and .net core everything works fine, I assume as part of implementation.
For .net framework 4.6 with x86, it throws exception.

So I put implicit calling conversion in all our PInvoke calls, and also made sure we use our stdafx.h in all our native libraries.

Have no idea how to write test for this tho.

### CODE REVIEW

**Comment by tannergooding** [comment]
To my knowledge:
* On x86, Windows defaults to `WinApi` (which is `StdCall`); while Linux defaults to `Cdecl`
* On x64, the same defaults apply but on Windows all the calling conventions were folded together into the single `Windows x64 calling convention`

@jkotas may know if there is something else that changed on .NET Core that would allow `x86` to pass without explicitly specifying the correct calling convention
* I would have expected this to fail, given that x86 has actually diferences and who cleans the stack changes

**Comment by jkotas** [comment]
> I've check and it looks like we build our native libraries in __csdecl conversion which is standard for C
> `#define EXPORT_API(ret) extern "C" __declspec(dllexport) ret i`

On Windows, the standard calling convention to use is configurable with compiler command line switches. The de-facto standard is to use stdcall as default on Windows x86. You need to actually look at the compiler switches to figure out which calling convention this is using.

**Comment by eerhardt** [comment]
> My recommendation would be to avoid explicitly specified calling conventions in C# as much as possible,

I agree. 

> and just configure the compiler to use the right one as the default.

I was thinking we should just follow the same pattern as we do for `clrcompression.dll` in corefx:

https://github.com/dotnet/corefx/blob/8f2afd786b04ba95b13d5a50b6f1e566b16cf5ac/src/Native/AnyOS/zlib/pal_zlib.h#L5-L15

Would that work as well?

**Comment by jkotas** [comment]
> Would that work as well?

I do not see anything particularly wrong with what you have there right now. The key piece that clrcompression has, but this repo does not, is the `/Gz` comment line switch for x86: https://github.com/dotnet/corefx/blob/8f2afd786b04ba95b13d5a50b6f1e566b16cf5ac/src/Native/Windows/CMakeLists.txt#L48

**Comment by eerhardt** [comment]
> If this used to work on x86 before open sourcing, I think that the most likely cause was that the compiler switches got messed up by port to CMake.

Digging into the internal repo, they use checked in `.vcxproj` files. And looking at the project properties:

image

**Comment by Ivanidzo4ka** [comment]
I'll try to add `add_compile_options(/Gz)` and remove any calling conventions from our PInvokes.

Where is one thing which blocking me right now - SymSGD with it call to Mkl
`SymSgdNative.obj : error LNK2019: unresolved external symbol _cblas_sdot@20 referenced in function "float __stdcall SDOT(int,float const *,float const *)" (?SDOT@@YGMHPBM0@Z) [D:\src\fork-machinelearning\bin\obj\x86.Debug\Native\SymSgdNative\SymSgdNative.vcxproj] [d:\src\fork-machinelearning\src\Native\build.proj]
`

Which I think related to Mkl library been build with __cdecl.

**Comment by eerhardt** [comment]
> Which I think related to Mkl library been build with __cdecl.

We extern those function calls:

https://github.com/dotnet/machinelearning/blob/a7a15ff5bc9cee0ad2bf09e184639568d11685ff/src/Native/SymSgdNative/SparseBLAS.h#L8-L11

We can just explicitly add cdecl on those extern functions.

**Comment by Ivanidzo4ka** [comment]
>We can just explicitly add cdecl on those extern functions.
Can you teach me how to do that?

**Comment by Ivanidzo4ka** [comment]
>We can just explicitly add cdecl on those extern functions.

Yes and no. No because we still call MKLfrom C# code, and PInvoke call without specifying convention will throw exception

File: src/Microsoft.ML.CpuMath/IntUtils.cs [hunk 1]
```diff
@@ -285,7 +285,7 @@ private static int CbitHighZero(ulong u)
         /// returning the quotient and placing the remainder in <paramref name="rem"/>. Throws on overflow.
         /// </summary>
 #if !CORECLR
-        [DllImport(Thunk.NativePath), SuppressUnmanagedCodeSecurity]
+        [DllImport(Thunk.NativePath, CallingConvention =CallingConvention.Cdecl), SuppressUnmanagedCodeSecurity]
```
Comment (wschin) [inline src/Microsoft.ML.CpuMath/IntUtils.cs]:
```suggestion
        [DllImport(Thunk.NativePath, CallingConvention = CallingConvention.Cdecl), SuppressUnmanagedCodeSecurity]
```

File: src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs [hunk 2]
```diff
@@ -70,13 +70,14 @@ public override IntArray[] Split(int[][] assignment)
         }
 
 #if USE_FASTTREENATIVE
-        [DllImport("FastTreeNative", CallingConvention = CallingConvention.StdCall)]
+        internal const string NativePath = "FastTreeNative";
+        [DllImport(NativePath)]
         private static extern unsafe int C_Sumup_float(
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs]: Do you need `CallingConvention = CallingConvention.Cdecl` here?

File: src/Microsoft.ML.FastTree/FastTreeRanking.cs [hunk 3]
```diff
@@ -1090,7 +1090,7 @@ private static void PermutationSort(int[] permutation, double[] scores, short[]
                     }));
             }
 
-            [DllImport("FastTreeNative", EntryPoint = "C_GetDerivatives", CallingConvention = CallingConvention.StdCall, CharSet = CharSet.Ansi)]
+            [DllImport("FastTreeNative", EntryPoint = "C_GetDerivatives", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
```
Comment (wschin) [inline src/Microsoft.ML.FastTree/FastTreeRanking.cs]: Some functions use `StdCall` and some functions use `Cdecl` for importing things from `FastTreeNative`. Do we have different calling conventions in a single DLL?

File: src/Microsoft.ML.CpuMath/IntUtils.cs (hunk 1 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.CpuMath/IntUtils.cs]: I reverted this change

---
In reply to: [239656605](https://github.com/dotnet/machinelearning/pull/1833#discussion_r239656605) [](ancestors = 239656605)

File: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs [hunk 4]
```diff
@@ -833,7 +833,7 @@ private static unsafe class Native
                 }
             }
 
-            [DllImport(DllName), SuppressUnmanagedCodeSecurity]
+            [DllImport(NativePath, CallingConvention = CallingConvention.Cdecl), SuppressUnmanagedCodeSecurity]
```
Comment (wschin) [inline src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs]: This is the only `Decl` in this C# file?

File: src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs (hunk 2 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs]: No, everything except MKL should work via default calls.
MKL should use cdecl.

---
In reply to: [239656885](https://github.com/dotnet/machinelearning/pull/1833#discussion_r239656885) [](ancestors = 239656885)

File: src/Microsoft.ML.FastTree/FastTreeRanking.cs (hunk 3 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.FastTree/FastTreeRanking.cs]: Not any more!

---
In reply to: [239658091](https://github.com/dotnet/machinelearning/pull/1833#discussion_r239658091) [](ancestors = 239658091)

File: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs (hunk 4 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs]: not any more!

---
In reply to: [239658431](https://github.com/dotnet/machinelearning/pull/1833#discussion_r239658431) [](ancestors = 239658431)

File: src/Microsoft.ML.TimeSeries/FftUtils.cs [hunk 5]
```diff
@@ -166,35 +166,35 @@ private enum ConfigValue
...
         private static extern int CommitDescriptor(IntPtr desc);
 
         // See: https://software.intel.com/en-us/node/521978
-        [DllImport(DllName, EntryPoint = "DftiFreeDescriptor")]
+        [DllImport(DllName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "DftiFreeDescriptor")]
         private static extern int FreeDescriptor(ref IntPtr desc);
 
         // See: https://software.intel.com/en-us/node/521981
-        [DllImport(DllProxyName, EntryPoint = "MKLDftiSetValue", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Auto)]
+        [DllImport(DllProxyName, EntryPoint = "MKLDftiSetValue", CharSet = CharSet.Auto)]
```
Comment (wschin) [inline src/Microsoft.ML.TimeSeries/FftUtils.cs]: It looks we are using MKL. Is it not a `Cdecl`?

File: src/Native/CMakeLists.txt [hunk 6]
```diff
@@ -183,10 +184,5 @@ function(install_library_and_symbols targetName)
     endif()
 endfunction()
 
-add_subdirectory(CpuMathNative)
-add_subdirectory(FastTreeNative)
-add_subdirectory(LdaNative)
-add_subdirectory(MatrixFactorizationNative)
-add_subdirectory(FactorizationMachineNative)
```
Comment (Ivanidzo4ka) [inline src/Native/CMakeLists.txt]: revert

File: src/Microsoft.ML.TimeSeries/FftUtils.cs (hunk 5 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.TimeSeries/FftUtils.cs]: this is a proxy which we build ourselves, so it would use default convention. We can't change Mkl (which is not proxy) so for pure Mkl we have to use cdecl.

---
In reply to: [239658702](https://github.com/dotnet/machinelearning/pull/1833#discussion_r239658702) [](ancestors = 239658702)

File: src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs [hunk 7]
```diff
@@ -185,21 +185,21 @@ private unsafe struct MFModel
             public float* Q;
         }
 
-        private const string DllPath = "MatrixFactorizationNative";
+        private const string NativePath = "MatrixFactorizationNative";
 
-        [DllImport(DllPath), SuppressUnmanagedCodeSecurity]
+        [DllImport(NativePath), SuppressUnmanagedCodeSecurity]
```
[the remark this answers is not in the document]
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Recommender/SafeTrainingAndModelBuffer.cs]: it all depend on you compiler.
for x64 on windows it's stdcall.
I added compiler option to build in stdcall for x86.
Linux would use cdecl.

---
In reply to: [239662401](https://github.com/dotnet/machinelearning/pull/1833#discussion_r239662401) [](ancestors = 239662401)

File: src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs [hunk 8]
```diff
@@ -70,13 +71,14 @@ public override IntArray[] Split(int[][] assignment)
         }
 
 #if USE_FASTTREENATIVE
-        [DllImport("FastTreeNative", CallingConvention = CallingConvention.StdCall)]
+        internal const string NativePath = "FastTreeNative";
+        [DllImport(NativePath), SuppressUnmanagedCodeSecurity]
```
Comment (eerhardt) [inline src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs]: @jkotas - is the `SuppressUnmanagedCodeSecurity` attribute necessary/useful on either .NET Core or .NET Framework 4.6.1+? I'm wondering if we should just get rid of it in our code.

File: src/Native/CMakeLists.txt [hunk 9]
```diff
@@ -32,6 +32,7 @@ if(WIN32)
     add_compile_options(/FC) # use full pathnames in diagnostics
     add_compile_options(/DEBUG)
     add_compile_options(/GS)
+    add_compile_options(/Gz)
```
Comment (eerhardt) [inline src/Native/CMakeLists.txt]: Should we only do this for x86? Like we do in corefx?

[https://github.com/dotnet/corefx/blob/c1788c695d4349c522fc5620eff7d3dd46a0ab5f/src/Native/Windows/CMakeLists.txt#L47-L49](https://github.com/dotnet/corefx/blob/c1788c695d4349c522fc5620eff7d3dd46a0ab5f/src/Native/Windows/CMakeLists.txt#L47-L49)

File: src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs (hunk 8 above)
Comment (jkotas) [reply src/Microsoft.ML.FastTree/Dataset/DenseIntArray.cs]: It is useless for .NET Core. It is needed for good perf on .NET Framework, unfortunately.
