### PR TITLE
Fixes the build break introduced by the DNNImageFeaturizer PR

### LINKED ISSUE #1741: Build break caused by DnnImageFeaturizer PR (#1447)

### PR DESCRIPTION
**Pull request by vaeksare**
Corrects the location of the package assets download to fix the build break. Fixes #1741

### CODE REVIEW

File: src/Redist/Microsoft.ML.DnnImageFeaturizer.ModelRedist/Microsoft.ML.DnnImageFeaturizer.ModelRedist.proj [hunk 1]
```diff
@@ -53,6 +53,46 @@
     DestinationDir="$(ModelPlacementDir)\ResNet101Onnx" />
   </ItemGroup>
 
+  <ItemGroup>
+    <ModelFileCopy Include="$(ModelPlacementDir)\AlexNetPrepOnnx\AlexNetPreprocess.onnx"
+    TargetPath="$(PackageAssetsPath)\Microsoft.ML.DnnImageFeaturizer.AlexNet\tools\DnnImageModels\AlexNetPrepOnnx\AlexNetPreprocess.onnx" />
+  </ItemGroup>
```
Comment (Ivanidzo4ka) [inline src/Redist/Microsoft.ML.DnnImageFeaturizer.ModelRedist/Microsoft.ML.DnnImageFeaturizer.ModelRedist.proj]: Out of curiosity, why we download them in one place and then copying them to another?
Why we can't just have them in one place? What's the point of copy?

File: src/Redist/Microsoft.ML.DnnImageFeaturizer.ModelRedist/Microsoft.ML.DnnImageFeaturizer.ModelRedist.proj [hunk 2]
```diff
@@ -61,7 +101,14 @@
     <DownloadFilesFromUrl Items="@(ModelFiles)"/>
   </Target>
 
+  <Target Name="CopyDnnModelFiles"
+          DependsOnTargets="DownloadDnnModelFiles">
```
Comment (eerhardt) [inline src/Redist/Microsoft.ML.DnnImageFeaturizer.ModelRedist/Microsoft.ML.DnnImageFeaturizer.ModelRedist.proj]: This should have an `Inputs` and `Outputs` declared, so it doesn't need to run on incremental builds.
