### PR TITLE
Fix StopWordRemoverTransform bugs

### LINKED ISSUE #1629: StopWordsRemoverTransform uses a dictionary with ReadOnlyMemory<char> keys
This transform contains a dictionary to find the language of each example, and this bug causes the language to not be found in the dictionary.

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #1629 .
Also fix a bug with splitting a comma separated list of stop words into tokens.

### CODE REVIEW

File: src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs [hunk 1]
```diff
@@ -158,5 +158,18 @@ public static CommonOutputs.TransformOutput WordEmbeddings(IHostEnvironment env,
                 OutputData = view
             };
         }
+
+        internal sealed class ReadonlyMemoryComparer : IEqualityComparer<ReadOnlyMemory<char>>
```
Comment (sfilipi) [inline src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs]: >ReadonlyMemoryComparer [](start = 30, length = 22)

just wondering if this is the best place for this. Is there any utils classes to host it?

File: src/Microsoft.ML.Transforms/Text/StopWordsRemoverTransform.cs [hunk 2]
```diff
@@ -278,7 +278,7 @@ private static NormStr.Pool[] StopWords
                 if (_langsDictionary == null)
                 {
                     var langsDictionary = Enum.GetValues(typeof(Language)).Cast<Language>()
-                        .ToDictionary(lang => lang.ToString().AsMemory());
+                        .ToDictionary(lang => lang.ToString().AsMemory(), new TextAnalytics.ReadonlyMemoryComparer());
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Transforms/Text/StopWordsRemoverTransform.cs]: >new TextAnalytics.ReadonlyMemoryComparer() [](start = 74, length = 42)

Wouldn't it be easier to go other way around? and cast language from column from readonly<char> to string?

File: src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs [hunk 3]
```diff
@@ -158,5 +158,18 @@ public static CommonOutputs.TransformOutput WordEmbeddings(IHostEnvironment env,
...
+        {
+            public bool Equals(ReadOnlyMemory<char> x, ReadOnlyMemory<char> y)
+            {
+                return x.Span.SequenceEqual(y.Span);
+            }
+
+            public int GetHashCode(ReadOnlyMemory<char> obj)
+            {
+                return obj.ToString().GetHashCode();
```
Comment (justinormont) [inline src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs]: I assume the .ToString() is needed? 

ReadOnlyMemory has a .GetHashCode():
https://docs.microsoft.com/en-us/dotnet/api/system.readonlymemory-1.gethashcode?view=netcore-2.1

File: src/Microsoft.ML.Transforms/Text/StopWordsRemoverTransform.cs (hunk 2 above)
Comment (yaeldekel) [reply src/Microsoft.ML.Transforms/Text/StopWordsRemoverTransform.cs]: It would be easier for me :-), but I think it would be more expensive to create a new string for every row.

---
In reply to: [234047532](https://github.com/dotnet/machinelearning/pull/1641#discussion_r234047532) [](ancestors = 234047532)

File: src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs (hunk 3 above)
Comment (yaeldekel) [reply src/Microsoft.ML.Transforms/EntryPoints/TextAnalytics.cs]: The ReadOnlyMemory<T> implementation calls GetHashCode on a T[], and I'm not sure what that does. This is just to make sure that two different instances that represent the same string get hashed to the same value.

---
In reply to: [234101834](https://github.com/dotnet/machinelearning/pull/1641#discussion_r234101834) [](ancestors = 234101834)

File: src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs [hunk 4]
```diff
@@ -254,5 +254,18 @@ public static StringBuilder AppendSpan(this StringBuilder sb, ReadOnlySpan<char>
...
+        public sealed class ReadonlyMemoryCharComparer : IEqualityComparer<ReadOnlyMemory<char>>
+        {
+            public bool Equals(ReadOnlyMemory<char> x, ReadOnlyMemory<char> y)
+            {
+                return x.Span.SequenceEqual(y.Span);
+            }
+
+            public int GetHashCode(ReadOnlyMemory<char> obj)
+            {
+                return obj.ToString().GetHashCode();
```
Comment (eerhardt) [inline src/Microsoft.ML.Core/Data/ReadOnlyMemoryUtils.cs]: This is not a good idea, since it will allocate a new string every time GetHashCode is called.

I think we should use our Murmur hash algorithm to get a hash code instead.
