### PR TITLE
ML.NET-242: FastTreeRanking per-iteration loss metrics are empty

### LINKED ISSUE #242: FastTree: FastTreeRanking per-iteration loss metrics are empty
### System information

- **OS version/distro**: Various Windows 10 machines, Windows Server 2012 or 2016.
- **.NET Version (eg., dotnet --info)**: 4.7, 4.6.x

Although, not a system-related bug.

### Issue

- **What did you do?** Train on a dataset using `FastTreeRanking` with the `testFrequency` parameter set to something like 1. Optionally, add a validation set. FastTree will now report training metrics on the train (and validation) sets every N iterations. Do the same for `FastTreeRegression` and `FastTreeClassification`.
- **What happened?** For `Regression` and `Classification`, the expected output is printed. For `Ranking`, The header for the per-iteration test and validation metrics prints, but there are no metrics.
- **What did you expect?** I expected metrics to be printed for the `Ranking` case.

### Source code / logs

Sample output:
```[6] 'FastTree training' started.
trainNDCG:
validNDCG:
trainNDCG:
validNDCG:
trainNDCG:
validNDCG:
trainNDCG:
validNDCG:
```

### PR DESCRIPTION
**Pull request by rogancarr**
When training a FastTreeRanker using the `testFrequency` parameter, it is expected that NDCG is printed every testFrequency iterations. However, instead of NDCG, only empty strings are printed.

The root cause was that the `MaxDCG` property of the dataset was never calculated, so the NDCG calculation is aborted, leaving an empty string as a result.

This PR fixes the problem by computing the `MaxDCG` for the dataset when the Tests are defined (so that if the tests are not defined, the `MaxDCG` will never be calculated). Here, the `truncationLevel` of the `MaxDCG` calculation is hardcoded to 10, which is a nice round number, and within the range of the `DiscountMap` (11).

Fixes #242

### CODE REVIEW

File: src/Microsoft.ML.FastTree/FastTreeRanking.cs [hunk 1]
```diff
@@ -343,6 +343,9 @@ protected override void CustomizedTrainingIteration(RegressionTree tree)
         /// <returns>standard test for the dataset</returns>
         private Test CreateStandardTest(Dataset dataset)
         {
+            if (dataset.MaxDcg.Length == 0)
```
Comment (TomFinley) [inline src/Microsoft.ML.FastTree/FastTreeRanking.cs]: >dataset.MaxDcg.Length [](start = 16, length = 21)

Please replace `dataset.MaxDcg.Length` with `Utils.Size(dataset.MaxDcg)`. Under certain codepaths this array *may* be null. :P

**Comment by rogancarr** [comment]
Thanks for the review @TomFinley ! I updated the PR to use `Utils.Size()` and re-tested.
