### PR TITLE
PipelineSweeperMacro for Multi-Class Classification

### LINKED ISSUE #538: PipelineSweeping fails for MultiClass classification
### Issue

- **PipelineSweeper fails for 'TrainerKind': 'SignatureMultiClassClassifierTrainer'**
- **System.InvalidOperationException : Requested value 'Accuracy(micro-avg)' is not a member of the Enum type 'Metrics'**

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #538

- The PipelineSweeper currently only supports AUC as the optimization metric.  Trying to optimize on any other metric throws an exception.
- Need to fix the way metrics are handled by the PipelineSweeper Macro.
- Added a test case for MultiClass classification using the PipelineSweeper.

### CODE REVIEW

File: test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs [hunk 1]
```diff
@@ -362,6 +362,73 @@ public void EntryPointPipelineSweepRoles()
...
+                    },
+                  ]
+                }";
+
+            JObject graphJson = JObject.Parse(inputGraph);
+            var catalog = ModuleCatalog.CreateInstance(Env);
+            var runner = new GraphRunner(Env, catalog, graphJson[FieldNames.Nodes] as JArray);
+            runner.SetInput("TrainingData", datasetTrain);
+            runner.SetInput("TestingData", datasetTest);
+            runner.RunAll();
```
Comment (sfilipi) [inline test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs]: >runner.RunAll(); [](start = 12, length = 16)

do you think the test should have a check on the results, make sure they are the same all the time, at least.

Comment (abgoswam) [reply test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs]: Updated the unit test.

---
In reply to: [202747140](https://github.com/dotnet/machinelearning/pull/539#discussion_r202747140) [](ancestors = 202747140)

File: test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs [hunk 2]
```diff
@@ -362,6 +362,73 @@ public void EntryPointPipelineSweepRoles()
...
+        {
+            // Get datasets
+            var pathData = GetDataPath("adult.train");
+            var pathDataTest = GetDataPath("adult.test");
+            const int numOfSampleRows = 100;
+            const string schema =
+                "sep=, col=age:R4:0 col=workclass:TX:1 col=fnlwgt:R4:2 col=education:TX:3 col=education_num:R4:4 col=marital_status:TX:5 col=occupation:TX:6 " +
+                "col=relationship:TX:7 col=ethnicity:TX:8 col=sex:TX:9 col=Features:R4:10-12 col=native_country:TX:13 col=IsOver50K_:R4:14 header=+";
+            var inputFileTrain = new SimpleFileHandle(Env, pathData, false, false);
+#pragma warning disable 0618
```
[the remark this answers is not in the document]
Comment (abgoswam) [reply test/Microsoft.ML.Predictor.Tests/TestAutoInference.cs]: disables warning generated because of using ImportText (obsolete)   instead of Textloader.  

Perhaps in a future PR, we can update all the unit tests to use TextLoader. I can create a separate bug to track that.

---
In reply to: [202746784](https://github.com/dotnet/machinelearning/pull/539#discussion_r202746784) [](ancestors = 202746784)

File: src/Microsoft.ML/CSharpApi.cs [hunk 3]
```diff
@@ -15626,36 +15626,37 @@ public sealed class UniformRandomAutoMlEngine : AutoMlEngine
...
+            DrAtK = 19,
+            DrAtPFpr = 20,
+            DrAtNumPos = 21,
+            NumAnomalies = 22,
+            ThreshAtK = 23,
+            ThreshAtP = 24,
+            ThreshAtNumPos = 25,
+            Nmi = 26,
+            AvgMinScore = 27,
+            Dbi = 28
```
[the remark this answers is not in the document]
Comment (abgoswam) [reply src/Microsoft.ML/CSharpApi.cs]: Looks like they are auto generated by the CSharp API generator

---
In reply to: [203217022](https://github.com/dotnet/machinelearning/pull/539#discussion_r203217022) [](ancestors = 203217022)

File: src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+            ThreshAtNumPos,
+            Nmi,
+            AvgMinScore,
+            Dbi
+        };
+
+        /// <summary>
+        /// Mapp Enum Metrics to a SupportedMetric
+        /// </summary>
+        private static readonly Dictionary<string, SupportedMetric> _map = new Dictionary<string, SupportedMetric>
```
Comment (sfilipi) [inline src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: > _map [](start = 67, length = 5)

if the only usage for this is to contain a list of known metrics, the numb might be enough. 
Take a look at Enum.Parse. You can move the construction of new SupportedMetric in the GetSupportedMetric, if the conversion succeeds.

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 5]
```diff
@@ -524,6 +431,18 @@ public void AddEvaluated(PipelinePattern pipeline)
                     d += 1e-3;
                 _sortedSampledElements.Add(d, pipeline);
                 _history.Add(pipeline);
+
+                using (var ch = _host.Start("Suggested Pipeline"))
+                {
+                    ch.Info($"PipelineSweeper Pipeline Id : {pipeline.UniqueId}");
```
Comment (justinormont) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: Can we also print an increasing pipeline number? This lets the user see the progress of the sweeping.

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 6]
```diff
@@ -524,6 +431,18 @@ public void AddEvaluated(PipelinePattern pipeline)
...
+                    foreach (var transform in pipeline.Transforms)
+                    {
+                        ch.Info($"PipelineSweeper Transform : {transform.Transform}");
+                    }
+                    ch.Info($"PipelineSweeper Learner : {pipeline.Learner}");
+                    ch.Info($"PipelineSweeper Train Metric Value: {pipeline.PerformanceSummary.TrainingMetricValue}");
+                    ch.Info($"PipelineSweeper Test Metric Value: {pipeline.PerformanceSummary.MetricValue}");
```
Comment (justinormont) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: We're printing the primary sweeping metric here. How much work would it be to print all of the pipeline's metrics?

Generally when hand sweeping over a dataset, I'm watching multiple metrics. This is important as one metric often increases at the detriment of others. 

For instance, micro & macro accuracy often trade-off as some models end-up better at smaller classes or the majority classes. The best models improve the metrics in unison.

File: src/Microsoft.ML/CSharpApi.cs [hunk 7]
```diff
@@ -15626,36 +15626,37 @@ public sealed class UniformRandomAutoMlEngine : AutoMlEngine
 
         public abstract class AutoMlStateBase : ComponentKind {}
 
-        public enum AutoInferenceAutoMlMlStateArgumentsMetrics
+        public enum PipelineSweeperSupportedMetricsMetrics
```
Comment (justinormont) [inline src/Microsoft.ML/CSharpApi.cs]: Isn't MetricsMetrics a bit odd sounding?

File: src/Microsoft.ML/CSharpApi.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (justinormont) [reply src/Microsoft.ML/CSharpApi.cs]: If we serialize the enum, I think we'd want a fixed number. This could be serialized as a state object for the sweep so that the user can resume the sweep w/ the history of the sweep stored on disk.

**Comment by shauheen** [comment]
@abgoswam why do you have fixes issue number in `quotes`? That fails to make it actually associate this with #538

File: src/Microsoft.ML.PipelineInference/AutoInference.cs (hunk 6 above)
Comment (abgoswam) [reply src/Microsoft.ML.PipelineInference/AutoInference.cs]: Good idea. I need to explore how we can expose this functionality  for the PipelineSweeper.  One thing to note is that the other metrics would depend on the TrainerKind. 

I will track this ask as a separate task. Would not want to block this PR on this feature ask. 

---
In reply to: [203264334](https://github.com/dotnet/machinelearning/pull/539#discussion_r203264334) [](ancestors = 203264334)

File: src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+            { Metrics.NumAnomalies.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.NumAnomalies, true)},
+            { Metrics.ThreshAtK.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.ThreshAtK, false)},
+            { Metrics.ThreshAtP.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.ThreshAtP, false)},
+            { Metrics.ThreshAtNumPos.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.ThreshAtNumPos, false)},
+            { Metrics.Nmi.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.Nmi, false)},
+            { Metrics.AvgMinScore.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.AvgMinScore, false)},
+            { Metrics.Dbi.ToString(), new SupportedMetric(FieldNames.PipelineSweeperSupportedMetrics.Dbi, false)}
+        };
+
+        public static SupportedMetric GetSupportedMetric(IHostEnvironment env, string metricName)
```
Comment (yaeldekel) [inline src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: >env [](start = 74, length = 3)

Is this argument needed? If it's just used for the one check below, we can either have an IExceptionContext instead, or simply use Contracts.CheckNonEmpty().

Comment (yaeldekel) [inline src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: >string [](start = 79, length = 6)

You can pass a Metric here instead of a string, this way you won't need the dictionary, and instead just do a switch statement on the parameter.

File: src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs (hunk 4 above)
Comment (yaeldekel) [reply src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: I think Senja meant that the conversion from the enum to a string is not needed (see my comment below on the GetSupportedMetric method).

---
In reply to: [203220227](https://github.com/dotnet/machinelearning/pull/539#discussion_r203220227) [](ancestors = 203220227,203217600)

File: src/Microsoft.ML.PipelineInference/AutoInference.cs [hunk 9]
```diff
@@ -271,7 +176,9 @@ public enum Metrics
             }
 
             public AutoMlMlState(IHostEnvironment env, Arguments args)
-                : this(env, SupportedMetric.ByName(Enum.GetName(typeof(Arguments.Metrics), args.Metric)), args.Engine.CreateComponent(env),
+                : this(env,
+                      PipelineSweeperSupportedMetrics.GetSupportedMetric(env, Enum.GetName(typeof(PipelineSweeperSupportedMetrics.Metrics), args.Metric)),
```
Comment (yaeldekel) [inline src/Microsoft.ML.PipelineInference/AutoInference.cs]: >Enum.GetName [](start = 78, length = 12)

If you change the GetSupportedMetric method to take the Metrics value, then you won't need this, you can just pass args.Metric.

File: src/Microsoft.ML/CSharpApi.cs (hunk 7 above)
Comment (abgoswam) [reply src/Microsoft.ML/CSharpApi.cs]: This is the auto generated file (the CSharpAPI translation layer) .  

The name here results from concatenating the following from PipelineSweeperSupportedMetrics.cs

<snip>
    public sealed class PipelineSweeperSupportedMetrics
    {
        public enum Metrics
        { 
</snip>

The name used for the class / enum look fine to me. Any alternate suggestions ?

---
In reply to: [203265071](https://github.com/dotnet/machinelearning/pull/539#discussion_r203265071) [](ancestors = 203265071)

File: src/Microsoft.ML/CSharpApi.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (abgoswam) [reply src/Microsoft.ML/CSharpApi.cs]: Not sure if this is a general comment , or something that needs to be addressed ?

Btw, this is is auto generated file . The Enum you see here is defined in PipelineSweeperSupportedMetrics.cs

---
In reply to: [203267499](https://github.com/dotnet/machinelearning/pull/539#discussion_r203267499) [](ancestors = 203267499)

File: src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs (hunk 8 above)
Comment (abgoswam) [reply src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: Thanks for the clarification. Modified to using switch case as suggested.  

Am wondering if its just a matter of preference of using switch/case   over using a dictionary mapping ?

---
In reply to: [203462492](https://github.com/dotnet/machinelearning/pull/539#discussion_r203462492) [](ancestors = 203462492)

Comment (abgoswam) [reply src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: I removed the argument.  Is there a suitable Contracts.Check*  API that is used for an Enum argument?

---
In reply to: [203461762](https://github.com/dotnet/machinelearning/pull/539#discussion_r203461762) [](ancestors = 203461762)

**Comment by abgoswam** [comment]
Thanks . I didn't realize the description had quotes till you pointed it out

---
In reply to: [405928784](https://github.com/dotnet/machinelearning/pull/539#issuecomment-405928784) [](ancestors = 405928784)

File: src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs (hunk 8 above)
Comment (sfilipi) [reply src/Microsoft.ML.PipelineInference/PipelineSweeperSupportedMetrics.cs]: Maybe to avoid the dictionary & switch statement, you can just keep a whitelist of the maximizing metrics. In the GetSupportedMetric, you can retrieve the boolean from looking up the whitelist. 

---
In reply to: [203543398](https://github.com/dotnet/machinelearning/pull/539#discussion_r203543398) [](ancestors = 203543398,203462492)

File: src/Microsoft.ML/CSharpApi.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (justinormont) [reply src/Microsoft.ML/CSharpApi.cs]: It's a topic to consider for the future. 
When we serialize the enum, we'll either have to serialize the numeric form or the text form. A numeric form will be more stable, and for that we'd have to assign the numbers in the primary definition of the enum.

**Comment by abgoswam** [comment]
thanks for the review comments. This PR is now merged.
