### PR TITLE
Don't fail in case of const field in Collection source and extended support for type conversion

### LINKED ISSUE #537: `const` on the instance class will throw
Adding a:

```
    public const string MagicNone = " NONE ";
```

to an "instance" class (ie the class used to feed ML.NET the instances) will throw an ugly exception which is hard to figure out.

I think there is another issue where more careful reflecting of the class is suggested. Can't find it right now though

### PR DESCRIPTION
**Pull request by Ivanidzo4ka**
Fixes  #537.
Adds support for multiple basic C# types to convert Dataview <-> collection.

### CODE REVIEW

File: src/Microsoft.ML.Api/TypedCursor.cs [hunk 1]
```diff
@@ -280,11 +280,38 @@ private Action<TRow> GenerateSetter(IRow input, int index, InternalSchemaDefinit
                     if (fieldType.GetElementType() == typeof(string))
                     {
                         Ch.Assert(colType.ItemType.IsText);
-                        return CreateVBufferToStringArraySetter(input, index, poke, peek);
+                        return CreateVBufferSetter<DvText, string>(input, index, poke, peek, (x) => x.ToString());
```
Comment (TomFinley) [inline src/Microsoft.ML.Api/TypedCursor.cs]: >(x) => x.ToString() [](start = 93, length = 19)

Would `x => x.ToString()` not work for some reason?

File: src/Microsoft.ML.Api/TypedCursor.cs [hunk 2]
```diff
@@ -302,53 +329,108 @@ private Action<TRow> GenerateSetter(IRow input, int index, InternalSchemaDefinit
...
                     }
-                    else
+                    else if (fieldType == typeof(bool?))
                     {
-                        // T -> T
-                        Ch.Assert(colType.RawType == fieldType);
-                        del = CreateDirectSetter<int>;
+                        Ch.Assert(colType.IsBool);
+                        Ch.Assert(peek == null);
+                        return CreateActionSetter<DvBool, bool?>(input, index, poke, (x) => x.IsNA ? (bool?)null : (x.IsTrue ? true : false));
```
Comment (TomFinley) [inline src/Microsoft.ML.Api/TypedCursor.cs]: >x.IsNA ? (bool?)null : (x.IsTrue ? true : false) [](start = 92, length = 48)

We have this here:

[https://github.com/dotnet/machinelearning/blob/839bd6d96cc8afc946defed39f5ddb2028cf852a/src/Microsoft.ML.Core/Data/DvBool.cs#L110](https://github.com/dotnet/machinelearning/blob/839bd6d96cc8afc946defed39f5ddb2028cf852a/src/Microsoft.ML.Core/Data/DvBool.cs#L110)

So would a straightforward `x => (bool?)x` not work, rather than reproducing the logic in this method?

File: src/Microsoft.ML.Api/TypedCursor.cs [hunk 3]
```diff
@@ -280,11 +280,38 @@ private Action<TRow> GenerateSetter(IRow input, int index, InternalSchemaDefinit
                     if (fieldType.GetElementType() == typeof(string))
                     {
                         Ch.Assert(colType.ItemType.IsText);
-                        return CreateVBufferToStringArraySetter(input, index, poke, peek);
+                        return CreateVBufferSetter<DvText, string>(input, index, poke, peek, (x) => x.ToString());
+                    }
+                    else if (fieldType.GetElementType() == typeof(bool))
+                    {
+                        Ch.Assert(colType.ItemType.IsBool);
+                        return CreateVBufferSetter<DvBool, bool>(input, index, poke, peek, (x) => Convert.ToBoolean(x.RawValue));
```
Comment (TomFinley) [inline src/Microsoft.ML.Api/TypedCursor.cs]: >(x) => Convert.ToBoolean(x.RawValue) [](start = 91, length = 36)

Similarly, would casts not work here?

File: src/Microsoft.ML.Api/TypedCursor.cs [hunk 4]
```diff
@@ -280,11 +280,38 @@ private Action<TRow> GenerateSetter(IRow input, int index, InternalSchemaDefinit
...
+                    }
+                    else if (fieldType.GetElementType() == typeof(int))
+                    {
+                        Ch.Assert(colType.ItemType == NumberType.I4);
+                        return CreateVBufferSetter<DvInt4, int>(input, index, poke, peek, (x) => x.RawValue);
+                    }
+                    else if (fieldType.GetElementType() == typeof(short))
```
Comment (TomFinley) [inline src/Microsoft.ML.Api/TypedCursor.cs]: If we're doing this with `int`, the explicit casts would throw in the case of missing values, whereas things like this will just silently pass `int.MinValue`.

**Comment by TomFinley** [comment]
Hi @Ivanidzo4ka I was looking and maybe I'm just missing something obvious, but where is the code that handles the const fields?

File: src/Microsoft.ML.Api/TypedCursor.cs (hunk 4 above)
Comment (TomFinley) [reply src/Microsoft.ML.Api/TypedCursor.cs]: That is, I think we *do* want to throw here, if someone makes the mistake of using a type that doesn't support missing values, over data that actually has missing values.

**Comment by Ivanidzo4ka** [comment]
Sorry, for all this mess, I start with const field, and get carried away.

it's in SchemaDefinition.cs
// Const fields not need to be mapped.
                if (fieldInfo.FieldType == typeof(IChannel) || fieldInfo.IsLiteral)
                    continue;
IsLiteral is indication of const field, so I just skip it and don't infer column from it.

---
In reply to: [406310650](https://github.com/dotnet/machinelearning/pull/555#issuecomment-406310650) [](ancestors = 406310650)

File: src/Microsoft.ML.Api/ApiUtils.cs [hunk 5]
```diff
@@ -21,9 +21,10 @@ private static OpCode GetAssignmentOpCode(Type t)
             // REVIEW: This should be a Dictionary<Type, OpCode> based solution.
             // DvTexts, strings, arrays, and VBuffers.
             if (t == typeof(DvInt8) || t == typeof(DvInt4) || t == typeof(DvInt2) || t == typeof(DvInt1) ||
```
Comment (Zruty0) [inline src/Microsoft.ML.Api/ApiUtils.cs]: Fix the comment

File: src/Microsoft.ML.Api/SchemaDefinition.cs [hunk 6]
```diff
@@ -327,7 +327,8 @@ public static SchemaDefinition Create(Type userType)
                 // This field does not need a column.
                 // REVIEW: maybe validate the channel attribute now, instead 
                 // of later at cursor creation.
-                if (fieldInfo.FieldType == typeof(IChannel))
+                // Const fields not need to be mapped.
```
Comment (Zruty0) [inline src/Microsoft.ML.Api/SchemaDefinition.cs]: > not need [](start = 31, length = 9)

do not need

Comment (Zruty0) [reply src/Microsoft.ML.Api/SchemaDefinition.cs]: Also, this comment only applies to the IsLiteral clause. I suggest to decouple the 2 clauses and have a different comment for each.
```
// Const fields not need to be mapped.
if (fieldInfo.IsLiteral)
                    continue;
// Clause to handle the field that may be used to expose the cursor channel. 
// This field does not need a column.
// REVIEW: maybe validate the channel attribute now, instead 
// of later at cursor creation.
if (fieldInfo.FieldType == typeof(IChannel) || fieldInfo.IsLiteral)
                    continue;
```


---
In reply to: [203871821](https://github.com/dotnet/machinelearning/pull/555#discussion_r203871821) [](ancestors = 203871821)

File: src/Microsoft.ML.Api/DataViewConstructionUtils.cs [hunk 7]
```diff
@@ -129,112 +129,192 @@ private Delegate CreateGetter(int index)
...
+                        else
+                            Ch.Assert(outputType.GetElementType() == colType.ItemType.RawType);
+                        del = CreateDirectArrayGetterDelegate<int>;
+                        genericType = outputType.GetElementType();
                     }
                     else if (colType.IsVector)
                     {
                         // VBuffer<T> -> VBuffer<T>
                         // REVIEW: Do we care about accomodating VBuffer<string> -> VBuffer<DvText>?
+                        // REVIEW: why it's int and not long?
```
Comment (Zruty0) [inline src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: >// REVIEW: why it's int and not long? [](start = 24, length = 37)

This is a strange place to add this comment. 
We are doing MarshalInvoke here, right. We have the 'del' as a generic on some token type (it was historically always int), then in line 283 we make the correct getter.

File: src/Microsoft.ML.Api/DataViewConstructionUtils.cs [hunk 8]
```diff
@@ -129,112 +129,192 @@ private Delegate CreateGetter(int index)
...
+                        }
+                        else if (outputType == typeof(int))
+                        {
+                            // int -> DvInt4
+                            Ch.Assert(colType == NumberType.I4);
+                            return CreateGetterDelegate<int, DvInt4>(index, x => x);
+                        }
+                        else if (outputType == typeof(int?))
+                        {
+                            // int -> DvInt4
```
Comment (Zruty0) [inline src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: >int [](start = 31, length = 3)

int?

File: src/Microsoft.ML.Api/DataViewConstructionUtils.cs [hunk 9]
```diff
@@ -129,112 +129,192 @@ private Delegate CreateGetter(int index)
...
+                    var peek = DataView._peeks[index] as Peek<TRow, TSrc>;
                     Ch.AssertValue(peek);
-                    bool? buf = null;
-                    return (ValueGetter<DvBool>)((ref DvBool dst) =>
+                    TSrc buf = default;
+                    return (ValueGetter<TDst>)((ref TDst dst) =>
                     {
                         peek(GetCurrentRowObject(), Position, ref buf);
-                        dst = buf.HasValue ? (DvBool)buf.Value : DvBool.NA;
+                        dst = convert(buf);
```
Comment (Zruty0) [inline src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: >convert [](start = 30, length = 7)

If `convert` is an identity, we are still incurring a delegate method call here, which is not efficient.

File: src/Microsoft.ML.Api/DataViewConstructionUtils.cs [hunk 10]
```diff
@@ -129,112 +129,192 @@ private Delegate CreateGetter(int index)
...
+                        {
+                            // long -> DvInt8
+                            Ch.Assert(colType == NumberType.I8);
+                            return CreateGetterDelegate<long, DvInt8>(index, x => x);
+                        }
+                        else if (outputType == typeof(long?))
+                        {
+                            // long? -> DvInt8
+                            Ch.Assert(colType == NumberType.I8);
+                            return CreateGetterDelegate<long?, DvInt8>(index, (x) => x.HasValue ? x.Value : DvInt8.NA);
```
Comment (Zruty0) [inline src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: >(x [](start = 78, length = 2)

why not `x => x ?? DvInt8.NA` here and below?

File: src/Microsoft.ML.Api/DataViewConstructionUtils.cs (hunk 9 above)
Comment (Ivanidzo4ka) [reply src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: I don't have identity converts. even if I pass  is x=>x I convert from TSrc to TDst class and call implicit converter. Which I'm not sure how to express through generic classes.
I would like to get rid of them, I just don't know way how to do it.

---
In reply to: [203875078](https://github.com/dotnet/machinelearning/pull/555#discussion_r203875078) [](ancestors = 203875078)

Comment (Zruty0) [reply src/Microsoft.ML.Api/DataViewConstructionUtils.cs]: Oh I see now. Ok, why don't we call this `CreateConvertingGetterDelegate`, to make it clear that there's also `CreateDirectGetterDelegate`?

---
In reply to: [203876308](https://github.com/dotnet/machinelearning/pull/555#discussion_r203876308) [](ancestors = 203876308,203875078)

**Comment by Zruty0** [comment]
>         public static bool TryGetDataKind(this Type type, out DataKind kind)

Hmm, it seems that this change will have a destructive potential. Could you please verify that we won't run into issues trying to coly a `sbyte` into a `DvInt1` somewhere? 

I took a look myself, and feel like we're safe for now, but it would be better to double-check

---
Refers to: src/Microsoft.ML.Core/Data/DataKind.cs:183 in 49323f2. [](commit_id = 49323f26d04ae250308c46e97b4980f013dd39ab, deletion_comment = False)

File: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs [hunk 11]
```diff
@@ -205,5 +207,314 @@ public class IrisPrediction
...
+            // Therefore replace all null values to empty string if field is string.
+            if (type == typeof(string) && x == null)
+                x = "";
+            if (type == typeof(string) && y == null)
+                y = "";
+            if (x == null && y == null)
+                return true;
+            if (x == null && y != null)
+                return false;
+            return (x.Equals(y));
```
Comment (Zruty0) [inline test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: >( [](start = 19, length = 1)

parentheses unnecessary

File: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs [hunk 12]
```diff
@@ -205,5 +207,314 @@ public class IrisPrediction
...
+        }
+
+        public bool CompareThrougReflection<T>(T x, T y)
```
Comment (Zruty0) [inline test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: >Throug [](start = 27, length = 6)

Via. Or at least 'through'

File: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs [hunk 13]
```diff
@@ -205,5 +207,314 @@ public class IrisPrediction
...
+        public class ClassWithConstField
+        {
+            public const string ConstString = "N";
+            public string fString;
+            public const int ConstInt = 100;
+            public int fInt;
+        }
+
+        [Fact]
+        public void BackAndForthConversionWithBasicTypes()
```
Comment (Zruty0) [inline test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: >BackAndForth [](start = 20, length = 12)

'RoundTrip' is a more widely accepted term I think

File: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs [hunk 14]
```diff
@@ -205,5 +207,314 @@ public class IrisPrediction
...
+                new ConversionSimpleClass(){ fInt=int.MinValue+1, fuInt=uint.MinValue+1, fBool=true, fsByte=sbyte.MinValue+1, fByte = byte.MinValue+1,
+                    fDouble =double.MinValue+1, fFloat=float.MinValue+1, fLong=long.MinValue+1, fuLong = ulong.MinValue+1,
+                    fShort =short.MinValue+1, fuShort = ushort.MinValue+1, fString=""},
+                new ConversionSimpleClass(){},
+            };
+
+            var dataNullable = new List<ConversionNullalbeClass>()
+            {
+                new ConversionNullalbeClass(){ fInt=int.MaxValue-1, fuInt=uint.MaxValue-1, fBool=true, fsByte=sbyte.MaxValue-1, fByte = byte.MaxValue-1,
+                    fDouble =double.MaxValue-1, fFloat=float.MaxValue-1, fLong=long.MaxValue-1, fuLong = ulong.MaxValue-1,
```
Comment (Zruty0) [inline test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: > = [](start = 27, length = 2)

Could you Ctrl-K-D for proper spacing? Or just, generally, invoke magic for proper spacing?

File: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs [hunk 15]
```diff
@@ -205,5 +207,314 @@ public class IrisPrediction
...
+                    var enumerator = dataView.AsEnumerable<ConversionNotSupportedMinValueClass>(env, false).GetEnumerator();
+                    try
+                    {
+                        enumerator.MoveNext();
+                    }
+                    catch
+                    {
+                        gotException = true;
+                    }
+                    Assert.True(gotException);
```
Comment (Zruty0) [inline test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: >Assert.True(gotException); [](start = 20, length = 26)

is this the idiom?
I'd prefer something along the lines of 
```
try
{
  MoveNext();
  Assert.Fail();
}
catch
{
  Assert.True(true);
}

File: test/Microsoft.ML.Tests/CollectionDataSourceTests.cs [hunk 16]
```diff
@@ -205,5 +207,314 @@ public class IrisPrediction
...
+                var nullableDataView = ComponentCreation.CreateDataView(env, nullableData);
+                var enumeratorNullable = nullableDataView.AsEnumerable<ClassWithNullableArrays>(env, false).GetEnumerator();
+                var originalNullalbleEnumerator = nullableData.GetEnumerator();
+                while (enumeratorNullable.MoveNext() && originalNullalbleEnumerator.MoveNext())
+                {
+                    Assert.True(CompareThrougReflection(enumeratorNullable.Current, originalNullalbleEnumerator.Current));
+                }
+                Assert.True(!enumeratorNullable.MoveNext() && !originalNullalbleEnumerator.MoveNext());
+            }
+        }
```
Comment (Zruty0) [inline test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: >} [](start = 8, length = 1)

Good job on the new tests. I assume you ran test coverage of them, right?

Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/CollectionDataSourceTests.cs]: yep, all new changes are covered

---
In reply to: [203883396](https://github.com/dotnet/machinelearning/pull/555#discussion_r203883396) [](ancestors = 203883396)

**Comment by Ivanidzo4ka** [comment]
@dotnet-bot test Windows_NT Release

**Comment by TomFinley** [comment]
Ah I see, thank you @ivanidzo4ka. (Out of curiosity, readonly fields? Static fields?)

Also there are two possible things we could consider as reasonable for `const` fields. We could ignore them, or just produce a constant column at least, when it is an input, and force them to use the `NoColumn` attribute on any field (no matter its modifiers) to suppress. Not sure if you've thought about it.

---
In reply to: [406343983](https://github.com/dotnet/machinelearning/pull/555#issuecomment-406343983) [](ancestors = 406343983,406310650)

**Comment by Zruty0** [comment]
Producing a constant column is, I think, reasonable. Then again, we currently do not have *too* different code for reading and writing, and I think there's value to keep it this way. If we cannot read it back, it's reasonable not to allow writing it either.

As for forcing `[NoColumn]` : I would prefer to not have a mandatory attribute like this. For reading the fields back, we allow two mechanisms for 'non-column' fields: a `[NoColumn]` attribute, or a global `ignoreMissingColumns` parameter. I think it would be better to do what Ivan does now to consts (which is the same as what we currently do for propertiers).

---
In reply to: [406766414](https://github.com/dotnet/machinelearning/pull/555#issuecomment-406766414) [](ancestors = 406766414,406343983,406310650)
