### PR TITLE
AutoML.Net filter infinity value when calculate average score

### LINKED ISSUE #5339: AutoML.Net: CrossValSummaryRunner can't handle all-infinity metrics value.
CrossValSummaryRunner picks up the best model and score from cross validation in the following logic:
- get results from all validation runs
- if all run succeed, get the index of model with best score as return model, if all run's score is NaN or Infinity, uses the first model
- if all run succeed, get the score which is closest to the average score as return training score, if average score is NaN, use the first score (**BUG**)

The possible place that causes the bug is sometimes the average score can be Infinity, in which case the following function will return -1 and causes an index out of error exception

https://github.com/dotnet/machinelearning/blob/37af3f9db86414f4ec5b16a8734c90b498946caa/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L84

### Related issue
(The label column for this user's dataset is all empty, which is the root cause for this error) 
- https://github.com/dotnet/machinelearning-modelbuilder/issues/929

### PR DESCRIPTION
**Pull request by LittleLittleCloud**
### Fix issue:
- #5339 

This pr fixes #5339 by filtering out the infinity value when [calculating average scores](https://github.com/dotnet/machinelearning/blob/9d3e5452096ac61baf9d2a7ead5a963865fca7d5/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L155) from the results of cross validation runner, so that the average score won't be infinity value in any situation, so that the return value of [GetIndexCloestToAverage](https://github.com/dotnet/machinelearning/blob/37af3f9db86414f4ec5b16a8734c90b498946caa/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L84) will not be -1.

In rare case, when all the scores from cross-validation run are infinitive, the average score will be designated to nan. and the return value of [GetIndexCloestToAverage](https://github.com/dotnet/machinelearning/blob/37af3f9db86414f4ec5b16a8734c90b498946caa/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L84) will be 0

Noted: the +/- infinite value is filtered before calculating average score because of the same reason nan value is filtered. By doing that the evaluation for cross-validation runner might be better than the real situation.

### CODE REVIEW

File: src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs [hunk 1]
```diff
@@ -136,23 +136,29 @@ private static TMetrics GetAverageMetrics(IEnumerable<TMetrics> metrics, TMetric
...
+        private static double GetAverageOfNonNaNAndNonInfinityScores(IEnumerable<double> results)
         {
-            var newResults = results.Where(r => !double.IsNaN(r));
-            // Return NaN iff all scores are NaN
+            var newResults = results.Where(r => !double.IsNaN(r) && !double.IsInfinity(r));
+            // Return NaN iff all scores are NaN or Infinity
             if (newResults.Count() == 0)
                 return double.NaN;
+
             // Return average of non-NaN scores otherwise
```
Comment (justinormont) [inline src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs:162]: What are the cases being fixed by removing the +/-Infinity values? I'm not sure they should be filtered, as +/-Infinity can be a correct, and wanted, metric value. For instance, for log-loss reduction. 

Instead of filtering you could modify [GetIndexClosestToAverage()](https://github.com/dotnet/machinelearning/blob/f87a3bbd8adb12934dae0a0060813ce9b7500664/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L160-L182) to properly handle the average being +/-Infinity. 

Perhaps coded as:
```c#
 private static int GetIndexClosestToAverage(IEnumerable<double> values, double average) 
 { 
     // Average will be NaN iff all values are NaN. 
     // Return the first index in this case. 
     if (double.IsNaN(average)) 
         return 0; 

    /* -- New checks -- */

    // Return the largest metric value when the average is +Infinity
    if (double.IsPositiveInfinity(average))
        return values.IndexOf(values.Max());

    // Return the smallest metric value when the average is -Infinity
    if (double.IsNegativeInfinity(average))
        return values.IndexOf(values.Min());

   /* ...function continues as before... */
```

Comment (LittleLittleCloud) [reply src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs:162]: It's the same reason why we filter nan value out before calculating average score, there is no mathematical meaning to include infinite value either, thinking about what's the average score of [+inf, -1, 0, 1, -inf] should be.

If we want to keep +/- inf when calculating average score, we'd better keep nan as well. In that way, the evaluation for cross-validation runner is closer to ground truth.

Comment (justinormont) [reply src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs:162]: I think the right answer is to keep the +/-Infinity. 

NaN and Infinities have different uses. NaN is the lack of a value for a metric, used when it's inherently incalculable. Infinities are generally actual values of the metric. 

For instance, log-loss is Infinity when the model is fully confident (probability == 0 or probability == 1), and incorrect, about a prediction (some [background](https://github.com/dotnet/machinelearning/issues/2708#issuecomment-467106396)). 

AutoML․NET ignores NaN metric values because they are not actual values of the metric, and are often caused by a self-induced data issue in how the AutoML code creates its CV splits.

The retuned metric value from cross-validation, among other uses, is meant to be representative of the metric as if trained/scored on a larger dataset. In the case of log-loss == Infinity, somewhere in the CV test datasets, there is one or more rows giving an Infinity value, which would be part of this larger scoring dataset. To be representative of this larger scoring dataset, the output value of the cross-validation should also be Infinity.

Comment (LittleLittleCloud) [reply src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs:162]: I see, thanks for the explanantion

File: src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs [hunk 2]
```diff
@@ -157,13 +157,24 @@ private static double GetAverageOfNonNaNScores(IEnumerable<double> results)
             return newResults.Average(r => r);
         }
 
+        /// <summary>
+        /// return the index of value from <paramref name="values"/> that closest to <paramref name="average"/>. If <paramref name="average"/> is non, +/- inf, the first, max/min value's index will be return.
```
Comment (antoniovs1029) [inline src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs:161]: Nit: Mispelling "... if average is NaN*, +/- inf, ... "

File: src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs [hunk 3]
```diff
@@ -157,13 +157,24 @@ private static double GetAverageOfNonNaNScores(IEnumerable<double> results)
...
             // Average will be NaN iff all values are NaN.
             // Return the first index in this case.
             if (double.IsNaN(average))
                 return 0;
 
+            // Return the max value's index if average is positive inf.
+            if (double.IsPositiveInfinity(average))
+                return values.ToList().IndexOf(values.Max());
+
+            // Return the max value's index if average is positive inf.
```
Comment (antoniovs1029) [inline src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs:174]: Nit: The comment is the same as in the max case, it should say min and "negative inf"

**Comment by LittleLittleCloud** [comment]
> @LittleLittleCloud , gentle ping about this PR. Is there anything else you want to add to it, or is it ok if we merge it once it passes the 1 failing CI build? thanks

No that's all, I will close this PR.
