### PR TITLE
Port Time Series

### LINKED ISSUE #978: Time Series
**Time Series in ML.NET**
* Forecasting
  * Singular Spectrum Analysis
    * Modeling univariate time series. Implementation based on the model taken from http://arxiv.org/pdf/1206.6910.pdf. 

* Anomaly Detection 
  * Spike Detector
    * Detects spikes in an independent and identical(IID) sequence using adaptive kernel density estimation
  * Change Point Detector
    * Detects the change-points in an independent and identical(IID) sequence using adaptive kernel density estimation and martingales

* Smoothing transforms
  * Exponential Average Transform
    * Is a weighted average of the values: ExpAvg(yt) = a * yt + (1-a) * ExpAvg(yt-1).
  * Moving Average Transform
    * Applies a moving average on a time series
  * Percentile Threshold Transform
    * Is a sequential transform that decides whether the current value of the time-series belongs to the 'percentile' % of the top values in the sliding window. The output of the transform will be a boolean flag.
  * P Value Transform
    * Calculates the p-value of the current input in the sequence with regard to the values in the sliding window.

**New Features to come**
* **Estimator and PiGSTy APIs** for the below components
  * |Component|Priority|
     |---|---|
     | IidChangePointDetector | 0 |
     | IidSpikeDetector  | 0 |
     | SsaChangePointDetector| 0 |
     | ExponentialAverageTransform| 1 |
     | MovingAverageTransform| 1 |
     | PercentileThresholdTransform| 1 |
     | PValueTransform| 1 |
     | SlidingWindowTransform| 1 |
     
     Example:
      ```csharp
      var data = new[] { new Data() { Feature = 2 }, new Data() { Feature = 1} }; 
      var dataView = ComponentCreation.CreateDataView(Env, data); 
      var pipe = new SpikeDetectorEstimator(Env, new[]{ 
      new SpikeDetectorTransformer.ColumnInfo("Feature", "Anomaly", twnd:500, swnd:50) 
       }); 
      var result = pipe.Fit(dataView).Transform(dataView); 
      var resultRoles = new RoleMappedData(result);
      ```
* **Prediction Engine**
  * The prediction engine we have today is a stateless one. For time series it is important we update the state of the model as we make prediction in the case of SSA models that have temporal relation between data points. This will require creating a new variant of prediction engine that will be used by time series components listed above. #163 
  * Currently to achieve stateful prediction engine users have to write the below code and then create checkpoints by saving the model every so often. 
    ```csharp
               const int size = 10;
                List<Data> data = new List<Data>(size);
                var dataView = env.CreateStreamingDataView(data);
                List<Data> tempData = new List<Data>();
                for (int i = 0; i < size / 2; i++)
                    tempData.Add(new Data(5));

                for (int i = 0; i < size / 2; i++)
                    tempData.Add(new Data((float)(5 + i * 1.1)));

                foreach (var d in tempData)
                    data.Add(new Data(d.Value));

                var args = new IidChangePointDetector.Arguments()
                {
                    Confidence = 80,
                    Source = "Value",
                    Name = "Change",
                    ChangeHistoryLength = size,
                    Data = dataView
                };
               
               //Train
                var detector = TimeSeriesProcessing.IidChangePointDetector(env, args);
                //Anomaly Detection
                var output = detector.Model.Apply(env, dataView);
                var enumerator = output.AsEnumerable<Prediction>(env, true).GetEnumerator();
               //Save the updated model 
               detector.Model.Save();
      ```
  * Instead we could have a below API that allows the user to save the model at fixed intervals to a disk or a stream while updating the model. 
```csharp 
           using (var env = new LocalEnvironment(seed: 1, conc: 1))
            {
                // Pipeline
                var loader = TextLoader.ReadFile(env, MakeArgs(), new MultiFileSource(GetDataPath(TestDatasets.AnomalyDetection)));
                var cachedTrain = new CacheDataView(env, loader, prefetch: null);

                // Train.
                var IidDetector = new IidChangePointDetector(env, new IidChangePointDetector.Arguments
                {
                   Confidence = 80,
                    Source = "Features",
                    Name = "Change",
                    ChangeHistoryLength = size,
                    Data = dataView
                });
                var trainRoles = new RoleMappedData(cachedTrain, feature: "Features");
                var predictor = IidDetector.Train(new Runtime.TrainContext(trainRoles));

                PredictionEngine<Input, Prediction> model;
                using (var file = env.CreateTempFile())
                {
                    // Save model. 
                    var roles = new RoleMappedData(trans, feature: "Features");
                    using (var ch = env.Start("saving"))
                        TrainUtils.SaveModel(env, ch, file, predictor, roles);

                    // Load model.
                    using (var fs = file.OpenReadStream())
                        model = env.CreatePredictionEngine<Input, Prediction>(fs);
                }

                // Take a couple examples out of the test data and run predictions on top.
                var testLoader = TextLoader.ReadFile(env, MakeArgs(), new MultiFileSource(GetDataPath(TestDatasets.AnomalyDetection));
                var testData = testLoader.AsEnumerable<Input>(env, false);
                foreach (var input in testData.Take(10))
                {
                   //Anomaly detection + update the model.
                    var prediction = model.Predict(input);
                }                
               
               //Save the model with updated state.
                model.Save();
            }
```

* **Online Training**
   Currently we have to train the model with the entire train dataset to update the model but instead it would be nice if the model got updated as the data came in. #163

* **Evaluator**
  * Currently we don’t have any evaluator for time series. Rolling CV is better for time dependent datasets by always testing on data which is newer than the training data. Standard CV leaks future data in to the training set. Other names of Rolling CV include { walk-forward / roll-forward / rolling origin / window } CV. Refer to #1026

* **ARIMA model** 
It seems the first thing novice time series users look for in a toolkit when doing a forecasting task is ARMIA model because it is the first thing that comes up in search results for forecasting. While ARMIA model isn’t the most accurate or performant model but it is the most well-known forecasting model. We should consider bringing in a simple implementation of ARIMA in ML.NET. #929 

* **Time Series Featurizer**  
The more performant models are the one that combine the features from a time series transform with non-time series features and feed in the resulting vector into a black-box regression learning algorithm. For example, one could have two features A and B, where A will contain data points that have temporal relationship between them, example, stock price and B contains non-temporal feature like country or zip code. We could feed A into SSA transform that will extract various components from an individual feature value such as trend, level, seasonality and then repeat this for all the feature values of A and then combine the result vector with feature B that could be feed into a regressor for prediction. The feature extraction step could be SSA or it could be a deep learning model such as LSTM. The regressor could be any regression based learner.  #929 

... and many more with `time`.

### PR DESCRIPTION
**Pull request by codemzs**
Port of time series prediction. 
* ExponentialAverage
* IidChangePointDetector
* IidSpikeDetector
* PercentileThresholdTransform
* PValueTransform
* SlidingWindowTransform
* SsaChangePointDetector
* SsaSpikeDetector

fixes #978, #1092 and #1103

### CODE REVIEW

File: src/Microsoft.ML.TimeSeries/FftUtils.cs [hunk 1]
```diff
@@ -0,0 +1,296 @@
...
+            /* PackedFormat (for storing congugate-even finite sequence
+               in real array) */
+            CcsFormat = 54,       /* Complex conjugate-symmetric */
+            PackFormat = 55,      /* Pack format for real DFT */
+            PermFormat = 56,      /* Perm format for real DFT */
+            CceFormat = 57        /* Complex conjugate-even */
+        }
+
+        private const string DllName = "MklImports.dll";
+        private const string DllProxyName = "MklImports.dll";
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/FftUtils.cs]: You don't need one of them.

File: src/Microsoft.ML.TimeSeries/FftUtils.cs [hunk 2]
```diff
@@ -0,0 +1,296 @@
...
+                status = ComputeBackward(descriptor, inputRe, inputIm, outputRe, outputIm);
+                CheckStatus(status);
+            }
+            finally
+            {
+                if (descriptor != null)
+                    FreeDescriptor(ref descriptor);
+            }
+
+            // REVIEW saamizad: for some reason the native backward scaling for DFTI in MKL does not work.
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/FftUtils.cs]: >REVIEW saamizad [](start = 15, length = 15)

Cn you clean code from aliases?

File: test/Microsoft.ML.Tests/TimeSeries.cs [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+            public float Value;
+
+            public Data(float value)
+            {
+                Value = value;
+            }
+        }
+
+        [Fact]
+        public void ChangeDetection()
```
[the remark this answers is not in the document]
Comment (codemzs) [reply test/Microsoft.ML.Tests/TimeSeries.cs]: The seasonality one does call into MKL

---
In reply to: [219570581](https://github.com/dotnet/machinelearning/pull/977#discussion_r219570581) [](ancestors = 219570581,219570371)

**Comment by codemzs** [comment]
Yes, sir. I was planning on doing that! :)

---
In reply to: [423611446](https://github.com/dotnet/machinelearning/pull/977#issuecomment-423611446) [](ancestors = 423611446)

File: src/Microsoft.ML.TimeSeries/FftUtils.cs [hunk 4]
```diff
@@ -0,0 +1,295 @@
...
+        [DllImport(DllName, EntryPoint = "DftiCommitDescriptor")]
+        private static extern int CommitDescriptor(IntPtr desc);
+
+        // See: https://software.intel.com/en-us/node/521978
+        [DllImport(DllName, EntryPoint = "DftiFreeDescriptor")]
+        private static extern int FreeDescriptor(ref IntPtr desc);
+
+        // See: https://software.intel.com/en-us/node/521981
+        [DllImport(DllName, EntryPoint = "DftiSetValue")]
+        private static extern int SetValue(IntPtr desc, ConfigParam configParam, ConfigValue configValue);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/FftUtils.cs]: I spent almost two days in trying to figure out what to do with arglist params, which no longer supported for coreclr.

[https://software.intel.com/en-us/mkl-developer-reference-c-dftisetvalue](https://software.intel.com/en-us/mkl-developer-reference-c-dftisetvalue) 
MKL_LONG DftiSetValue( DFTI_DESCRIPTOR_HANDLE, DFTI_CONFIG_PARAM , ... );
that ... used to be supported through __arglist.

At some point I gave up and wrote proxy c++ code.
So if your tests start failing on Linux/Mac only, and you don't know why, this is probably the case.

File: Microsoft.ML.sln [hunk 5]
```diff
@@ -115,7 +115,7 @@ Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.ML.Analyzer", "sr
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.ML.StaticPipelineTesting", "test\Microsoft.ML.StaticPipelineTesting\Microsoft.ML.StaticPipelineTesting.csproj", "{8B38BF24-35F4-4787-A9C5-22D35987106E}"
 EndProject
-Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Microsoft.ML.DnnAnalyzer", "src\Microsoft.ML.DnnAnalyzer\Microsoft.ML.DnnAnalyzer\Microsoft.ML.DnnAnalyzer.csproj", "{73DAAC82-D308-48CC-8FFE-3B037F8BBCCA}"
+Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.ML.TimeSeries", "src\Microsoft.ML.TimeSeries\Microsoft.ML.TimeSeries.csproj", "{5A79C7F0-3D99-4123-B0DA-7C9FFCD13132}"
```
Comment (Zruty0) [inline Microsoft.ML.sln]: >TimeSeries [](start = 66, length = 10)

this looks like a merge error to me

File: src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs [hunk 6]
```diff
@@ -0,0 +1,148 @@
+﻿//------------------------------------------------------------------------------
+// <copyright company="Microsoft Corporation">
```
Comment (Zruty0) [inline src/Microsoft.ML.TimeSeries/IidChangePointDetector.cs]: >Microsoft [](start = 23, length = 9)

fix headers

File: src/Microsoft.ML.TimeSeries/SequentialAnomalyDetectionTransformBase.cs [hunk 7]
```diff
@@ -0,0 +1,655 @@
...
+using System.Collections.Generic;
+using Microsoft.ML.Runtime.CommandLine;
+using Microsoft.ML.Runtime.Data;
+using Microsoft.ML.Runtime.Internal.CpuMath;
+using Microsoft.ML.Runtime.Internal.Utilities;
+using Microsoft.ML.Runtime.Model;
+
+namespace Microsoft.ML.Runtime.TimeSeriesProcessing
+{
+    // REVIEW saamizad: This base class and its children classes generate one output column of type VBuffer<Double> to output 3 different anomaly scores as well as
```
Comment (Zruty0) [inline src/Microsoft.ML.TimeSeries/SequentialAnomalyDetectionTransformBase.cs]: >saamizad [](start = 14, length = 8)

remove aliases

File: src/Microsoft.ML.TimeSeries/FftUtils.cs (hunk 4 above)
Comment (codemzs) [reply src/Microsoft.ML.TimeSeries/FftUtils.cs]: thanks, @Ivanidzo4ka

File: src/Microsoft.ML.TimeSeries/SequentialAnomalyDetectionTransformBase.cs (hunk 7 above)
Comment (Zruty0) [reply src/Microsoft.ML.TimeSeries/SequentialAnomalyDetectionTransformBase.cs]: Keep the 'REVIEW' though

---
In reply to: [219996812](https://github.com/dotnet/machinelearning/pull/977#discussion_r219996812) [](ancestors = 219996812)

File: src/Native/build.proj [hunk 8]
```diff
@@ -100,6 +102,9 @@
     <ItemGroup>
       <NativePackageAsset Include="$(NativeAssetsBuiltPath)\$(NativeLibPrefix)MklImports$(NativeLibExtension)"
                           RelativePath="Microsoft.ML.HalLearners\runtimes\$(PackageRid)\native" /> 
+						  
+      <NativePackageAsset Include="$(NativeAssetsBuiltPath)\$(NativeLibPrefix)MklImports$(NativeLibExtension)"
+                          RelativePath="Microsoft.ML\runtimes\$(PackageRid)\native" />
```
Comment (eerhardt) [inline src/Native/build.proj]: We shouldn't be adding MklImports to the `Microsoft.ML` package. That was the reason we created `Microsoft.ML.HalLearners`, so every user of ML.NET doesn't need to download MklImports.

File: src/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.csproj [hunk 9]
```diff
@@ -0,0 +1,16 @@
+﻿<Project Sdk="Microsoft.NET.Sdk">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <IncludeInPackage>Microsoft.ML</IncludeInPackage>
```
Comment (eerhardt) [inline src/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.csproj]: As mentioned previously, we can't be putting Mkl into the `Microsoft.ML` package.

File: test/Microsoft.ML.Tests/TimeSeries.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (codemzs) [reply test/Microsoft.ML.Tests/TimeSeries.cs]: The test coverage is adequate for now. There were no tests before. This is a port to unblock a team that is currently using TLC binaries and we want them to start using ML.NET. There will be many more iterations in this area that will add API and more tests. 

---
In reply to: [221325088](https://github.com/dotnet/machinelearning/pull/977#discussion_r221325088) [](ancestors = 221325088,219570673)

**Comment by codemzs** [comment]
@eerhardt I have addressed your comments as per our offline conversation we agreed to address packaging to unblock this PR.

File: src/Native/build.proj [hunk 10]
```diff
@@ -100,6 +102,9 @@
     <ItemGroup>
       <NativePackageAsset Include="$(NativeAssetsBuiltPath)\$(NativeLibPrefix)MklImports$(NativeLibExtension)"
                           RelativePath="Microsoft.ML.HalLearners\runtimes\$(PackageRid)\native" /> 
+
```
Comment (eerhardt) [inline src/Native/build.proj]: (nit) whitespace issues here. random tabs in this file.

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj [hunk 11]
```diff
@@ -0,0 +1,13 @@
+<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Pack">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <PackageDescription>Microsoft.ML.TimeSeries contains ML.NET Time Series prediction algorithms. Uses Intel Mkl.</PackageDescription>
+  </PropertyGroup>
+
+  <ItemGroup>
+	<Content Include="$(PackagesDir)\mlnetmkldeps\$(MlNetMklDepsPackageVersion)\LICENSE.txt" Pack="true" PackagePath=".\NOTICE.txt" />
```
Comment (eerhardt) [inline pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: We should think about making a single MKL nuget package and then having TimeSeries and HalLearners both reference it. As this is today, if someone tried using both TimeSeries and HalLearners, the MklImports asset would collide.

Also, if there are bugs/changes in MKL that we need to take, now we need to service it in 2 separate nuget packages.

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj [hunk 12]
```diff
@@ -0,0 +1,13 @@
...
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <PackageDescription>Microsoft.ML.TimeSeries contains ML.NET Time Series prediction algorithms. Uses Intel Mkl.</PackageDescription>
+  </PropertyGroup>
+
+  <ItemGroup>
+	<Content Include="$(PackagesDir)\mlnetmkldeps\$(MlNetMklDepsPackageVersion)\LICENSE.txt" Pack="true" PackagePath=".\NOTICE.txt" /> 
+    <Content Include="..\common\CommonPackage.props" Pack="true" PackagePath="build\netstandard2.0\$(MSBuildProjectName).props" />
+  </ItemGroup>
```
Comment (eerhardt) [inline pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: This package should have a reference to the `Microsfot.ML` nuget package.

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj (hunk 11 above)
Comment (ericstj) [reply pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: Agree with Eric here.  We should be making people download this binary twice and relying on the build to de-dup it.

Comment (codemzs) [reply pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: I also agree and we spoke offline on this. I have opened a issue for this [https://github.com/dotnet/machinelearning/issues/1092](https://github.com/dotnet/machinelearning/issues/1092)

The challenge here is we know from past experience SymSGD breaks if it tries to consume MKL binaries in the form of a package. Hence we were shipping MKL binaries together with HALLearner package. 

---
In reply to: [221367285](https://github.com/dotnet/machinelearning/pull/977#discussion_r221367285) [](ancestors = 221367285)

File: test/Microsoft.ML.Tests/TimeSeries.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Ivanidzo4ka) [reply test/Microsoft.ML.Tests/TimeSeries.cs]: I would disagree. 
We have TestDataPipeMore.cs with baseline tests, and we also have EntryPoint tests in other repo, so why not bring them?

---
In reply to: [221331846](https://github.com/dotnet/machinelearning/pull/977#discussion_r221331846) [](ancestors = 221331846,221325088,219570673)

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj [hunk 13]
```diff
@@ -0,0 +1,14 @@
+<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Pack">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <PackageDescription>Microsoft.ML.TimeSeries contains ML.NET Time Series prediction algorithms. Uses Intel Mkl.</PackageDescription>
+  </PropertyGroup>
+
+  <ItemGroup>
+    <Content Include="$(PackagesDir)\mlnetmkldeps\$(MlNetMklDepsPackageVersion)\LICENSE.txt" Pack="true" PackagePath=".\NOTICE.txt" /> 
+    <Content Include="..\common\CommonPackage.props" Pack="true" PackagePath="build\netstandard2.0\$(MSBuildProjectName).props" />
```
Comment (Ivanidzo4ka) [inline pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: ><Content Include="..\common\CommonPackage.props" Pack="true" PackagePath="build\netstandard2.0\$(MSBuildProjectName).props" /> [](start = 4, length = 126)

Can we have comment, what this is for?

Comment (codemzs) [reply pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: Redistribution notice.

Comment (Ivanidzo4ka) [reply pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: I'm not talking about .\Notice.txt, I'm talking about  ..\common\CommonPackage.props

---
In reply to: [221393266](https://github.com/dotnet/machinelearning/pull/977#discussion_r221393266) [](ancestors = 221393266)

File: src/Native/MklProxyNative/CMakeLists.txt [hunk 14]
```diff
@@ -0,0 +1,21 @@
+project (MklProxyNative)
```
Comment (Ivanidzo4ka) [inline src/Native/MklProxyNative/CMakeLists.txt]: >MklProxyNative [](start = 9, length = 14)

[https://github.com/dotnet/machinelearning/blob/1ae6070a554a374dec4d9b9f746cfde481b033c7/src/Common/AssemblyLoadingUtils.cs#L143](https://github.com/dotnet/machinelearning/blob/1ae6070a554a374dec4d9b9f746cfde481b033c7/src/Common/AssemblyLoadingUtils.cs#L143)
add it to the list.

**Comment by Ivanidzo4ka** [comment]
> using Microsoft.ML.Runtime.Data;

Header

---
Refers to: test/Microsoft.ML.Tests/TimeSeries.cs:1 in 6f056d2. [](commit_id = 6f056d26a21e5e4347288796774885acefc6a32b, deletion_comment = False)

**Comment by Ivanidzo4ka** [comment]
> using Microsoft.ML.Runtime.Data;

And sort arguments :D

---
In reply to: [425581178](https://github.com/dotnet/machinelearning/pull/977#issuecomment-425581178) [](ancestors = 425581178)

---
Refers to: test/Microsoft.ML.Tests/TimeSeries.cs:1 in 6f056d2. [](commit_id = 6f056d26a21e5e4347288796774885acefc6a32b, deletion_comment = False)

File: test/Microsoft.ML.Tests/TimeSeries.cs [hunk 15]
```diff
@@ -0,0 +1,125 @@
...
+                    Name = "Change",
+                    ChangeHistoryLength = size,
+                    Data = dataView
+                };
+
+                var detector = TimeSeriesProcessing.IidChangePointDetector(env, args);
+                var output = detector.Model.Apply(env, dataView);
+                var enumerator = output.AsEnumerable<Prediction>(env, true).GetEnumerator();
+                Prediction row = null;
+                List<double> expectedValues = new List<double>() { 0, 5, 0.5, 5.1200000000000114E-08, 0, 5, 0.4999999995, 5.1200000046080209E-08, 0, 5, 0.4999999995, 5.1200000092160303E-08,
```
Comment (Ivanidzo4ka) [inline test/Microsoft.ML.Tests/TimeSeries.cs]: >1200000000000114E [](start = 80, length = 17)

I think Assert.Equal has third parameter: precision, so you don't have, if you set it to 4, you don't have to have this long constants. (I'm actually surprised tests are not falling due to precision errors)

File: src/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.csproj [hunk 16]
```diff
@@ -0,0 +1,16 @@
+﻿<Project Sdk="Microsoft.NET.Sdk">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <IncludeInPackage>Microsoft.ML.TimeSeries</IncludeInPackage>
+    <DefineConstants>CORECLR</DefineConstants>
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.csproj]: ><DefineConstants>CORECLR</DefineConstants> [](start = 4, length = 42)

I don't think you need this one

File: test/Microsoft.ML.Tests/TimeSeries.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (codemzs) [reply test/Microsoft.ML.Tests/TimeSeries.cs]: I didn't realize there were entrypoints test until later today but upon further investigation it seems we don't have datasets for some of those test, A4Benchmark-TS1.csv is missing and many of those tests are disabled for Linux because they don;t pass. Time Series won't be announced until 0.7 and legacy pipeline would be gone at that time. I'll port over whatever tests I can. 

---
In reply to: [221392605](https://github.com/dotnet/machinelearning/pull/977#discussion_r221392605) [](ancestors = 221392605,221331846,221325088,219570673)

File: src/Native/SymSgdNative/CMakeLists.txt [hunk 17]
```diff
@@ -18,4 +18,8 @@ endif()
 add_library(SymSgdNative SHARED ${SOURCES} ${RESOURCES})
 target_link_libraries(SymSgdNative PUBLIC ${MKL_LIBRARY})
 
+if(APPLE)
+    set_target_properties(SymSgdNative PROPERTIES INSTALL_RPATH "@loader_path;${MKL_LIB_PATH}")
```
Comment (eerhardt) [inline src/Native/SymSgdNative/CMakeLists.txt]: `MKL_LIB_PATH` points to our repo's `packages` folder. This isn't going to work for customers who install our NuGet package.

File: src/Native/build.proj [hunk 18]
```diff
@@ -89,18 +84,15 @@
...
     </ItemGroup>
 
     <ItemGroup>
       <NativePackageAsset Condition="('$(OS)' == 'Windows_NT' OR '$(StripNativeSymbols)' == 'True')
                                      AND '%(NativePackageAsset.Identity)' != '$(PlaceholderFile)'"
                           Include="@(NativePackageAsset->'%(RootDir)%(Directory)%(Filename)$(NativeLibSymbolExtension)')" />
     </ItemGroup>
-
-    <ItemGroup>
-      <NativePackageAsset Include="$(NativeAssetsBuiltPath)\$(NativeLibPrefix)MklImports$(NativeLibExtension)"
```
Comment (eerhardt) [inline src/Native/build.proj]: What NuGet package is MklImports shipping in?

**Comment by eerhardt** [comment]
>     public sealed partial class TestTimeSeries : TestDataPipeBase

Let's not put more tests in the `TestFramework` assembly. My goal/intention has been to make this assembly just contain the functionality that is common to all tests, but not have actual tests in side of it.

Maybe since TimeSeries has its own product assembly, it should deserve its own test assembly.

---
Refers to: test/Microsoft.ML.TestFramework/TimeSeries.cs:14 in 28ee009. [](commit_id = 28ee009aa2888a4ea054739859eff627f95dfbbb, deletion_comment = False)

**Comment by eerhardt** [comment]
>     public sealed partial class TestTimeSeries : TestDataPipeBase

Can you just move this constructor into the normal `TestTimeSeries` class? Then you don't need this partial class at all.

---
Refers to: test/Microsoft.ML.TestFramework/TestInitialization.cs:73 in 28ee009. [](commit_id = 28ee009aa2888a4ea054739859eff627f95dfbbb, deletion_comment = False)

File: src/Native/build.sh [hunk 19]
```diff
@@ -96,6 +96,12 @@ fi
 
 __cmake_defines="${__cmake_defines} -DVERSION_FILE_PATH:STRING=${__versionSourceFile}"
 
+# This should be done when nuget is published but until then lets keep these below lines.
+if [[ "$OSTYPE" == "darwin"* ]]; then
+    echo "Changing libMklImports.dylib's name to include @rpath."
+    install_name_tool "-id" @rpath/libMklImports.dylib "$__mkllibpath"/libMklImports.dylib
```
Comment (eerhardt) [inline src/Native/build.sh]: Similar comment here as before - this is only going to work during tests in our repo. How will it work for customers who are using our NuGet package?

File: src/Native/SymSgdNative/CMakeLists.txt (hunk 17 above)
Comment (codemzs) [reply src/Native/SymSgdNative/CMakeLists.txt]: We spoke offline about this. The current version has @loader_path that tells the loader to look into the same location as the referring binary, this will work for our users if did dotnet publish. We agreed to add another rpath that will also search in the nuget cache.

---
In reply to: [221632968](https://github.com/dotnet/machinelearning/pull/977#discussion_r221632968) [](ancestors = 221632968)

File: src/Native/build.sh (hunk 19 above)
Comment (codemzs) [reply src/Native/build.sh]: Senja will be updating the nuget today with this line. Also, I did mention above this is temp :)

---
In reply to: [221635422](https://github.com/dotnet/machinelearning/pull/977#discussion_r221635422) [](ancestors = 221635422)

**Comment by Ivanidzo4ka** [comment]
> "timestamps","value","anomaly","changepoint","trend","noise","seasonality1","seasonality2","seasonality3"

Is this manually generated file, or it's someone else dataset, and we need to acquire license for it?

---
Refers to: test/data/Timeseries/A4Benchmark-TS1.csv:1 in 28ee009. [](commit_id = 28ee009aa2888a4ea054739859eff627f95dfbbb, deletion_comment = False)

**Comment by codemzs** [comment]
> "timestamps","value","anomaly","changepoint","trend","noise","seasonality1","seasonality2","seasonality3"

I have regenerated the dataset using excel.

---
In reply to: [426046452](https://github.com/dotnet/machinelearning/pull/977#issuecomment-426046452) [](ancestors = 426046452)

---
Refers to: test/data/Timeseries/A4Benchmark-TS1.csv:1 in 28ee009. [](commit_id = 28ee009aa2888a4ea054739859eff627f95dfbbb, deletion_comment = False)

**Comment by eerhardt** [comment]
>     <ProjectReference Include="..\..\src\Microsoft.ML.TimeSeries\Microsoft.ML.TimeSeries.csproj" />

This shouldn't be necessary

---
Refers to: test/Microsoft.ML.TestFramework/Microsoft.ML.TestFramework.csproj:19 in be7ccff. [](commit_id = be7ccfff937d737d7542500c9121e347cdff83b8, deletion_comment = False)

**Comment by eerhardt** [comment]
>     public sealed class TimeSeries

Any reason why these tests aren't in the `Microsoft.ML.TimeSeries.Tests` project?

---
Refers to: test/Microsoft.ML.Tests/TimeSeries.cs:13 in be7ccff. [](commit_id = be7ccfff937d737d7542500c9121e347cdff83b8, deletion_comment = False)

**Comment by eerhardt** [comment]
> <Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

You can remove `ToolsVersion="15.0"`. It is not necessary.

---
Refers to: test/Microsoft.ML.TimeSeries.Tests/Microsoft.ML.TimeSeries.Tests.csproj:1 in be7ccff. [](commit_id = be7ccfff937d737d7542500c9121e347cdff83b8, deletion_comment = False)

**Comment by eerhardt** [comment]
>         [Fact(Skip = "TEMP: Missing MKL Binary.")]

When will this be addressed? You should log an issue if you plan on checking this test in disabled.

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:3753 in be7ccff. [](commit_id = be7ccfff937d737d7542500c9121e347cdff83b8, deletion_comment = False)

File: Microsoft.ML.sln [hunk 20]
```diff
@@ -427,6 +431,14 @@ Global
 		{8B38BF24-35F4-4787-A9C5-22D35987106E}.Release|Any CPU.Build.0 = Release|Any CPU
 		{8B38BF24-35F4-4787-A9C5-22D35987106E}.Release-Intrinsics|Any CPU.ActiveCfg = Release|Any CPU
 		{8B38BF24-35F4-4787-A9C5-22D35987106E}.Release-Intrinsics|Any CPU.Build.0 = Release|Any CPU
+		{5A79C7F0-3D99-4123-B0DA-7C9FFCD13132}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
+		{5A79C7F0-3D99-4123-B0DA-7C9FFCD13132}.Debug|Any CPU.Build.0 = Debug|Any CPU
+		{5A79C7F0-3D99-4123-B0DA-7C9FFCD13132}.Debug-Intrinsics|Any CPU.ActiveCfg = Debug|Any CPU
```
Comment (eerhardt) [inline Microsoft.ML.sln]: I've merged my PR: [https://github.com/dotnet/machinelearning/pull/1032](https://github.com/dotnet/machinelearning/pull/1032).  These will need to be updated to have `-Intrinsics` on the right side too. See the PR for what needs to be done.

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj [hunk 21]
```diff
@@ -0,0 +1,15 @@
+<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Pack">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <PackageDescription>Microsoft.ML.TimeSeries contains ML.NET Time Series prediction algorithms. Uses Intel Mkl.</PackageDescription>
+  </PropertyGroup>
+
+  <ItemGroup>
+    <Content Include="$(PackagesDir)\mlnetmkldeps\$(MlNetMklDepsPackageVersion)\LICENSE.txt" Pack="true" PackagePath=".\NOTICE.txt" />
```
Comment (eerhardt) [inline pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: I don't think we need the license file here since we are not packaging MKL in this nuget.

File: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs [hunk 22]
```diff
@@ -754,6 +754,11 @@ private void CheckLabel(RoleMappedData examples, out int weightSetCount)
 
         private static unsafe class Native
         {
+            static Native()
+            {
+                var t = ErrorMessage(0);
```
Comment (eerhardt) [inline src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs]: You can use:

```
_ = ErrorMessage(0);
```

instead of `var t`.  `_` signifies "I want to capture the variable, but I don't actually use the variable".

Comment (eerhardt) [inline src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs]: Let's add the reasoning/comment here on why we are doing this.

File: src/Native/SymSgdNative/CMakeLists.txt [hunk 23]
```diff
@@ -18,4 +18,8 @@ endif()
 add_library(SymSgdNative SHARED ${SOURCES} ${RESOURCES})
 target_link_libraries(SymSgdNative PUBLIC ${MKL_LIBRARY})
 
+if(APPLE)
+    set_target_properties(SymSgdNative PROPERTIES INSTALL_RPATH "@loader_path;@loader_path/../../../../../${MKL_LIB_RPATH};${MKL_LIB_PATH}")
```
Comment (eerhardt) [inline src/Native/SymSgdNative/CMakeLists.txt]: `${MKL_LIB_PATH}` shouldn't be necessary, right? When we are running in our repo, these assemblies should live together, so `@loader_path` should just take care of it.

File: src/Native/MklProxyNative/CMakeLists.txt [hunk 24]
```diff
@@ -0,0 +1,25 @@
...
+        SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
+        SET(CMAKE_INSTALL_RPATH "$ORIGIN/")
+    endif()
+endif()
+
+add_library(MklProxyNative SHARED ${SOURCES} ${RESOURCES})
+target_link_libraries(MklProxyNative PUBLIC ${MKL_LIBRARY})
+
+if(APPLE)
+    set_target_properties(MklProxyNative PROPERTIES INSTALL_RPATH "@loader_path;${MKL_LIB_PATH}")
```
Comment (eerhardt) [inline src/Native/MklProxyNative/CMakeLists.txt]: We shouldn't need `MKL_LIB_PATH` here, right?  MklProxyNative will always be in the same directory as MklImports.

File: src/Native/build.proj [hunk 25]
```diff
@@ -96,12 +96,16 @@
                                      AND '%(NativePackageAsset.Identity)' != '$(PlaceholderFile)'"
                           Include="@(NativePackageAsset->'%(RootDir)%(Directory)%(Filename)$(NativeLibSymbolExtension)')" />
     </ItemGroup>
-
+	
     <ItemGroup>
-      <NativePackageAsset Include="$(NativeAssetsBuiltPath)\$(NativeLibPrefix)MklImports$(NativeLibExtension)"
-                          RelativePath="Microsoft.ML.HalLearners\runtimes\$(PackageRid)\native" /> 
+      <NativePackageAsset Include="$(NativeAssetsBuiltPath)\$(NativeLibPrefix)MklProxyNative$(NativeLibExtension)"
```
Comment (eerhardt) [inline src/Native/build.proj]: This line needs to go above the previous ItemGroup.  The reason this ItemGroup exists down here is because the one above adds the symbols for the assemblies we produce in this repo.  Since `MklImports` is not produced by this repo, we have no symbols for it.  But `MklProxyNative` IS produced by this repo, so we need to package the `$(NativeLibSymbolExtension)` files as well.

File: src/Native/build.proj [hunk 26]
```diff
@@ -53,7 +53,7 @@
           DependsOnTargets="GenerateVersionHeader">
           
     <PropertyGroup>
-      <BuildArgs>$(Configuration) $(TargetArchitecture) --mkllibpath $(PackagesDir)mlnetmkldeps\$(MlNetMklDepsPackageVersion)\runtimes\$(PackageRid)\native</BuildArgs>
+      <BuildArgs>$(Configuration) $(TargetArchitecture) --mkllibpath $(PackagesDir)mlnetmkldeps\$(MlNetMklDepsPackageVersion)\runtimes\$(PackageRid)\native --mkllibrpath mlnetmkldeps/$(MlNetMklDepsPackageVersion)/runtimes/$(PackageRid)/native</BuildArgs>
```
Comment (eerhardt) [inline src/Native/build.proj]: There's no such thing as 'rpath' on Windows, right? We shouldn't need to use/pass it on Windows.

File: src/Native/build.sh [hunk 27]
```diff
@@ -49,6 +50,10 @@ while [ "$1" != "" ]; do
             shift
             __mkllibpath=$1
             ;;
+        --mkllibrpath)
+            shift
+            __mkllibrpath=$1
+            ;;
```
Comment (eerhardt) [inline src/Native/build.sh]: (nit) tabs at the end of this line

File: src/Native/MklProxyNative/MklProxyNative.cpp [hunk 28]
```diff
@@ -0,0 +1,176 @@
...
+
+    /* PackedFormat (for storing congugate-even finite sequence
+       in real array) */
+    CcsFormat = 54,       /* Complex conjugate-symmetric */
+    PackFormat = 55,      /* Pack format for real DFT */
+    PermFormat = 56,      /* Perm format for real DFT */
+    CceFormat = 57        /* Complex conjugate-even */
+};
+
+EXPORT_API(int) DftiSetValue(void *handle, ConfigParam config_param, ...);
```
Comment (eerhardt) [inline src/Native/MklProxyNative/MklProxyNative.cpp]: It would be nice having a comment here explaining why we need to make these "proxy" methods.

File: src/Native/SymSgdNative/CMakeLists.txt (hunk 23 above)
Comment (eerhardt) [inline src/Native/SymSgdNative/CMakeLists.txt]: >@loader_path/../../../../../${MKL_LIB_RPATH} [](start = 78, length = 44)

How about let's put the `../../..` outside of the CMake files as well? The whole relative path should be passed into `${MKL_LIB_RPATH}`, so here we can just say:

`@loader_path/${MKL_LIB_RPATH}`

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj [hunk 29]
```diff
@@ -0,0 +1,14 @@
+<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Pack">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <PackageDescription>Microsoft.ML.TimeSeries contains ML.NET Time Series prediction algorithms. Uses Intel Mkl.</PackageDescription>
+  </PropertyGroup>
+
+  <ItemGroup>
+    <Content Include="..\common\CommonPackage.props" Pack="true" PackagePath="build\netstandard2.0\$(MSBuildProjectName).props" />
```
Comment (eerhardt) [inline pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: `TimeSeries` doesn't ship any native assemblies, so it doesn't need this `.props` file.

**Comment by codemzs** [comment]
>         [Fact(Skip = "TEMP: Missing MKL Binary.")]

We need a real dataset for this. Opened issue #1120

---
In reply to: [426390719](https://github.com/dotnet/machinelearning/pull/977#issuecomment-426390719) [](ancestors = 426390719)

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:3753 in be7ccff. [](commit_id = be7ccfff937d737d7542500c9121e347cdff83b8, deletion_comment = False)

File: pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj [hunk 30]
```diff
@@ -0,0 +1,14 @@
+<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Pack">
+
+  <PropertyGroup>
+    <Authors>Intel</Authors>
```
Comment (eerhardt) [inline pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj]: Don't need to block the PR on this - but we should make sure CELA is fine with `Intel` listed as the author here.

File: pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj [hunk 31]
```diff
@@ -0,0 +1,12 @@
+<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Pack">
+
+  <PropertyGroup>
+    <TargetFramework>netstandard2.0</TargetFramework>
+    <PackageDescription>Microsoft.ML.TimeSeries contains ML.NET Time Series prediction algorithms. Uses Intel Mkl.</PackageDescription>
+  </PropertyGroup>
+
+  <ItemGroup><ProjectReference Include="../Microsoft.ML/Microsoft.ML.nupkgproj" />
```
Comment (eerhardt) [inline pkg/Microsoft.ML.TimeSeries/Microsoft.ML.TimeSeries.nupkgproj]: (nit) need a newline here after `<ItemGroup>`

File: pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj (hunk 30 above)
Comment (codemzs) [reply pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj]: Tensor flow Redist did the same.

File: src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs [hunk 32]
```diff
@@ -754,6 +754,9 @@ private void CheckLabel(RoleMappedData examples, out int weightSetCount)
 
         private static unsafe class Native
         {
+            //To triger the loading of MKL library since MKL proxy native library depends on it.
```
Comment (eerhardt) [inline src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs]: `MKL proxy` isn't used by SymSGD, but instead `SymSGDNative` is.

Comment (codemzs) [reply src/Microsoft.ML.HalLearners/SymSgdClassificationTrainer.cs]: Yikes, copy paste habits ...

---
In reply to: [222123162](https://github.com/dotnet/machinelearning/pull/977#discussion_r222123162) [](ancestors = 222123162)

File: src/Native/build.proj [hunk 33]
```diff
@@ -40,7 +40,7 @@
           DependsOnTargets="GenerateVersionSourceFile">
     <PropertyGroup>
       <StripArgs Condition="'$(StripNativeSymbols)' == 'True'">--stripSymbols</StripArgs>
-      <BuildArgs>--configuration $(Configuration) --arch $(TargetArchitecture) $(StripArgs) --mkllibpath $(PackagesDir)mlnetmkldeps/$(MlNetMklDepsPackageVersion)/runtimes/$(PackageRid)/native</BuildArgs>
+      <BuildArgs>--configuration $(Configuration) --arch $(TargetArchitecture) $(StripArgs) --mkllibpath $(PackagesDir)mlnetmkldeps/$(MlNetMklDepsPackageVersion)/runtimes/$(PackageRid)/native --mkllibrpath ../../../../../mlnetmkldeps/$(MlNetMklDepsPackageVersion)/runtimes/$(PackageRid)/native</BuildArgs>
```
Comment (eerhardt) [inline src/Native/build.proj]: I just realized that this is wrong.

`mkllibrpath` is used by our customers and we aren't shipping `mlnetmkldeps` to our customers. Instead we are shipping `Microsoft.ML.Mkl.Redist` and should use that package name and Version.

**Comment by eerhardt** [comment]
>         [Fact(Skip = "TEMP: Missing MKL Binary.")]

(minor) Can we add that issue link into the code?

---
In reply to: [426421800](https://github.com/dotnet/machinelearning/pull/977#issuecomment-426421800) [](ancestors = 426421800,426390719)

---
Refers to: test/Microsoft.ML.Core.Tests/UnitTests/TestEntryPoints.cs:3753 in be7ccff. [](commit_id = be7ccfff937d737d7542500c9121e347cdff83b8, deletion_comment = False)

File: pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj (hunk 30 above)
Comment (eerhardt) [reply pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj]: The value used by Tensorflow Redist was specified by CELA.

Comment (codemzs) [reply pkg/Microsoft.ML.Mkl.Redist/Microsoft.ML.Mkl.Redist.nupkgproj]: I will check with CELA and if anything needs to be changed I will change it.

---
In reply to: [222125803](https://github.com/dotnet/machinelearning/pull/977#discussion_r222125803) [](ancestors = 222125803)

File: src/Native/build.proj (hunk 33 above)
Comment (eerhardt) [reply src/Native/build.proj]: (nit) I would toLower `Microsoft.ML.Mkl.Redist`, since NuGet does that.  MacOS typically isn't case sensitive, but it would be best to use the right casing.

---
In reply to: [222124648](https://github.com/dotnet/machinelearning/pull/977#discussion_r222124648) [](ancestors = 222124648)

Comment (eerhardt) [reply src/Native/build.proj]: Also, consider adding a comment why we are doing this.

---
In reply to: [222136270](https://github.com/dotnet/machinelearning/pull/977#discussion_r222136270) [](ancestors = 222136270,222124648)
