### PR TITLE
Fixing names of trainer estimators

### LINKED ISSUE #2762: TrainersName pattern (Discussion)
https://github.com/dotnet/machinelearning/issues/2172 follow up on this one.
So right now we have mix of trainers names.
I want to standardize them.

We have following zoo of naming patterns:
`LogisticRegression`
`SdcaMultiClassTrainer`
`SgdNonCalibratedBinaryTrainer`
`LinearSvmTrainer`
`LightGbmMulticlassTrainer`
`MulticlassLogisticRegression`

My proposal is following:

`{AlgoName}(optional){Calibrated/NonCalibrated}{TypeOfTask}Trainer`

Where AlgoName is full name without abbreviations (SDCA->StochasticDualCoordinateAscent, Linearsvm ->LinearSupportVectorMachines) with exception of LightGBM.

I would also prefer to explicitly specify TypeOfTask even if algorithm exist only for one type. (Which would create weird abominations like OneVersusAllMulticlassTrainer, but i'm fine with that)

Does that sound good for you?
@sfilipi  @TomFinley  @eerhardt  @yaeldekel

### PR DESCRIPTION
**Pull request by abgoswam**
Fixes #2762 and #2172

### CODE REVIEW

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection/RandomizedPcaSampleWithOptions.cs [hunk 1]
```diff
@@ -28,15 +28,15 @@ public static void Example()
             // Convert the List<DataPoint> to IDataView, a consumble format to ML.NET functions.
             var data = mlContext.Data.LoadFromEnumerable(samples);
 
-            var options = new ML.Trainers.RandomizedPrincipalComponentAnalyzer.Options()
+            var options = new ML.Trainers.RandomizedPcaAnomalyDetectionTrainer.Options()
```
Comment (sfilipi) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection/RandomizedPcaSampleWithOptions.cs]: >RandomizedPcaAnomalyDetectionTrainer [](start = 42, length = 36)

can we leave  "trainer" out of the name?

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/AveragedPerceptronWithOptions.cs [hunk 2]
```diff
@@ -21,7 +21,7 @@ public static void Example()
             var trainTestData = mlContext.BinaryClassification.TrainTestSplit(data, testFraction: 0.1);
 
             // Define the trainer options.
-            var options = new AveragedPerceptronTrainer.Options()
+            var options = new AveragedPerceptronBinaryClassificationTrainer.Options()
```
Comment (sfilipi) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/AveragedPerceptronWithOptions.cs]: >AveragedPerceptronBinaryClassificationTrainer [](start = 30, length = 45)

I vote for AveragePerceptron.

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs [hunk 3]
```diff
@@ -61,7 +61,7 @@ public static void Example()
             // we could do so by tweaking the 'advancedSetting'.
             var advancedPipeline = mlContext.Transforms.Text.FeaturizeText("SentimentText", "Features")
                                   .Append(mlContext.BinaryClassification.Trainers.StochasticDualCoordinateAscent(
-                                      new SdcaBinaryTrainer.Options { 
+                                      new StochasticDualCoordinateAscentBinaryClassificationTrainer.Options {
```
Comment (sfilipi) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/BinaryClassification/StochasticDualCoordinateAscent.cs]: >StochasticDualCoordinateAscentBinaryClassificationTrainer [](start = 42, length = 57)

StochasticDualCoordinateAscent

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeansWithOptions.cs [hunk 4]
```diff
@@ -28,8 +28,8 @@ public static void Example()
             // A pipeline for concatenating the age, parity and induced columns together in the Features column and training a KMeans model on them.
             string outputColumnName = "Features";
             var pipeline = ml.Transforms.Concatenate(outputColumnName, new[] { "Age", "Parity", "Induced" })
-                .Append(ml.Clustering.Trainers.KMeans(
-                    new KMeansPlusPlusTrainer.Options
+                .Append(ml.Clustering.Trainers.KMeansPlusPlus(
+                    new KMeansPlusPlusClusteringTrainer.Options
```
Comment (sfilipi) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeansWithOptions.cs]: >KMeansPlusPlusClusteringTrainer [](start = 24, length = 31)

just KMeansPlusPlus maybe

File: src/Microsoft.ML.FastTree/FastTreeRegression.cs [hunk 5]
```diff
@@ -391,7 +391,7 @@ internal sealed class ObjectiveImpl : ObjectiveFunctionBase, IStepSearch
         {
             private readonly float[] _labels;
 
-            public ObjectiveImpl(Dataset trainData, RegressionGamTrainer.Options options) :
+            public ObjectiveImpl(Dataset trainData, GeneralizedAdditiveModelRegressionTrainer.Options options) :
```
Comment (sfilipi) [inline src/Microsoft.ML.FastTree/FastTreeRegression.cs]: >GeneralizedAdditiveModelRegressionTrainer [](start = 52, length = 41)

GeneralizedAdditiveModel

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection/RandomizedPcaSampleWithOptions.cs (hunk 1 above)
Comment (abgoswam) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/AnomalyDetection/RandomizedPcaSampleWithOptions.cs]: used acronym for Pca.  Kept suffix Trainer in the name of the class

---
In reply to: [264101278](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264101278) [](ancestors = 264101278)

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs [hunk 6]
```diff
@@ -27,7 +27,7 @@ public static void Example()
             // A pipeline for concatenating the age, parity and induced columns together in the Features column and training a KMeans model on them.
             string outputColumnName = "Features";
             var pipeline = ml.Transforms.Concatenate(outputColumnName, new[] { "Age", "Parity", "Induced" })
-                .Append(ml.Clustering.Trainers.KMeans(outputColumnName, numberOfClusters: 2));
+                .Append(ml.Clustering.Trainers.KMeansPlusPlus(outputColumnName, numberOfClusters: 2));
```
Comment (wschin) [inline docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs]:
```suggestion
                .Append(ml.Clustering.Trainers.KMeans(outputColumnName, numberOfClusters: 2));
```

**Comment by artidoro** [comment]
There is also `MetaMulticlassTrainer` that needs to be renamed.

**Comment by artidoro** [comment]
This is will solve part of #2623.

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs (hunk 6 above)
Comment (abgoswam) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs]: The algorithm that is  actually implemented  is [KmeansPlusPlus ](https://en.wikipedia.org/wiki/K-means%2B%2B) .   The underlying class is also called KMeansPlusPlus

This is also discussed here : https://github.com/dotnet/machinelearning/issues/2762#issuecomment-470229508

**Comment by abgoswam** [comment]
Tanks for pointing this out. This should be called `MetaTrainer` as per the summary 

---
In reply to: [471806679](https://github.com/dotnet/machinelearning/pull/2903#issuecomment-471806679) [](ancestors = 471806679)

File: docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs (hunk 6 above)
Comment (abgoswam) [reply docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs]: The algorithm that is  actually implemented  is [KmeansPlusPlus ](https://en.wikipedia.org/wiki/K-means%2B%2B) .   The underlying class is also called KMeansPlusPlus

This is also discussed here : [https://github.com/dotnet/machinelearning/issues/2762#issuecomment-470229508](https://github.com/dotnet/machinelearning/issues/2762#issuecomment-470229508)

---
In reply to: [264484798](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264484798) [](ancestors = 264484798)

File: src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs [hunk 7]
```diff
@@ -64,8 +64,8 @@ public Arguments()
                             // non-default column names. Unfortuantely no method of resolving this temporary strikes me as being any
                             // less laborious than the proper fix, which is that this "meta" component should itself be a trainer
                             // estimator, as opposed to a regular trainer.
-                            var trainerEstimator = new MulticlassLogisticRegression(env, LabelColumnName, FeatureColumnName);
-                            return TrainerUtils.MapTrainerEstimatorToTrainer<MulticlassLogisticRegression,
+                            var trainerEstimator = new LogisticRegressionMulticlassClassificationTrainer(env, LabelColumnName, FeatureColumnName);
```
Comment (sfilipi) [inline src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs]: >LogisticRegressionMulticlassClassificationTrainer [](start = 55, length = 49)

this will get ppl confused because it has both Regression and Multiclass on the name, but can't think of a good way to deal with it. would it be ok to just call it Logit @wschin @TomFinley

File: test/BaselineOutput/Common/Command/CommandTrainMlrWithStats-summary.txt [hunk 8]
```diff
@@ -1,4 +1,4 @@
-MulticlassLogisticRegression bias and non-zero weights
+LogisticRegressionMulticlassClassificationTrainer bias and non-zero weights
```
Comment (sfilipi) [inline test/BaselineOutput/Common/Command/CommandTrainMlrWithStats-summary.txt]: >LogisticRegressionMulticlassClassificationTrainer [](start = 0, length = 49)

how can this be shorter... anyone in favor of dropping 'Classification'

File: src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs [hunk 9]
```diff
@@ -154,7 +154,7 @@ public static class SdcaStaticExtensions
             var rec = new TrainerEstimatorReconciler.BinaryClassifier(
                 (env, labelName, featuresName, weightsName) =>
                 {
-                    var trainer = new SdcaBinaryTrainer(env, labelName, featuresName, weightsName, l2Regularization, l1Threshold, numberOfIterations);
+                    var trainer = new SdcaCalibratedBinaryClassificationTrainer(env, labelName, featuresName, weightsName, l2Regularization, l1Threshold, numberOfIterations);
```
Comment (sfilipi) [inline src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs]: >SdcaCalibratedBinaryClassificationTrainer [](start = 38, length = 41)

Did leave a note below, but i'd be ok dropping `Classificaiton` from all BinaryClassification and MulticlassClassification.

File: src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs (hunk 7 above)
Comment (abgoswam) [reply src/Microsoft.ML.Ensemble/Trainer/Multiclass/MulticlassDataPartitionEnsembleTrainer.cs]: I would especially hesitate to call it Logit . `Logits` has a different interpretation  related to the  unnormalized log-probabilities

---
In reply to: [264516270](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264516270) [](ancestors = 264516270)

File: src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs (hunk 9 above)
Comment (abgoswam) [reply src/Microsoft.ML.StaticPipe/SdcaStaticExtensions.cs]: note below .. am not getting you ?

---
In reply to: [264518672](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264518672) [](ancestors = 264518672)

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs [hunk 10]
```diff
@@ -136,7 +136,7 @@ public static class TreeExtensions
         }
 
         /// <summary>
-        /// Predict a target using generalized additive models trained with the <see cref="BinaryClassificationGamTrainer"/>.
+        /// Predict a target using generalized additive models trained with the <see cref="GamBinaryClassificationTrainer"/>.
```
Comment (eerhardt) [inline src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: I wonder if we should connect the acronyms in the doc:

`Predict a target using generalized additive models (GAM) trained with the <see cref="GamBinaryClassificationTrainer"/>.`

File: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs [hunk 11]
```diff
@@ -26,7 +26,7 @@ public static class KMeansClusteringExtensions
         ///  [!code-csharp[KMeans](~/../docs/samples/docs/samples/Microsoft.ML.Samples/Dynamic/Trainers/Clustering/KMeans.cs)]
         /// ]]></format>
         /// </example>
-        public static KMeansPlusPlusTrainer KMeans(this ClusteringCatalog.ClusteringTrainers catalog,
+        public static KMeansPlusPlusTrainer KMeansPlusPlus(this ClusteringCatalog.ClusteringTrainers catalog,
```
Comment (eerhardt) [inline src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: I think we should be consistent everywhere about this name. If we really intend for this to be `KMeansPlusPlus`, then we should update all the places that just use `KMeans`:

The name of the above class:
`public static class KMeansClusteringExtensions`

The name of the assembly:
`Microsoft.ML.KMeansClustering`

Is there any confusion about just using the name `KMeans`? Are there other `KMeans` algorithms besides `KMeans++`? It feels like we should be fine just using `KMeans`, but I'll leave it up to the experts.

File: src/Microsoft.ML.StandardTrainers/Standard/MultiClass/MetaMulticlassTrainer.cs [hunk 12]
```diff
@@ -15,7 +15,7 @@ namespace Microsoft.ML.Trainers
 {
     using TScalarTrainer = ITrainerEstimator<ISingleFeaturePredictionTransformer<IPredictorProducing<float>>, IPredictorProducing<float>>;
 
-    public abstract class MetaMulticlassTrainer<TTransformer, TModel> : ITrainerEstimator<TTransformer, TModel>, ITrainer<IPredictor>
+    public abstract class MetaTrainer<TTransformer, TModel> : ITrainerEstimator<TTransformer, TModel>, ITrainer<IPredictor>
```
Comment (eerhardt) [inline src/Microsoft.ML.StandardTrainers/Standard/MultiClass/MetaMulticlassTrainer.cs]: Here's a special case of our rule:

> {TypeOfTask} is added only only when the algorithm supports multiple kinds of tasks 

I don't believe `MetaTrainer` is a good name here since it too general. That name makes it sound like it can train anything. I think we should keep "multiclass" in the name.  So probably `MetaMulticlassClassificationTrainer`.

File: src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs [hunk 13]
```diff
@@ -9,15 +9,15 @@
...
+    using LROptions = LogisticRegressionBinaryClassificationTrainer.Options;
 
     /// <summary>
     /// TrainerEstimator extension methods.
     /// </summary>
     public static class StandardTrainersCatalog
     {
         /// <summary>
-        /// Predict a target using a linear classification model trained with <see cref="SgdBinaryTrainer"/>.
+        /// Predict a target using a linear classification model trained with <see cref="SgdCalibratedTrainer"/>.
```
Comment (eerhardt) [inline src/Microsoft.ML.StandardTrainers/StandardTrainersCatalog.cs]: Here's a place where the acronym `Sgd` isn't expanded out in the summary comments.

File: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs (hunk 11 above)
Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: [Kmeans++](https://en.wikipedia.org/wiki/K-means%2B%2B) is a slightly modified version of [Kmeans] ([https://en.wikipedia.org/wiki/K-means_clustering](https://en.wikipedia.org/wiki/K-means_clustering)) that has some smarts for choosing the initial cluster centers. The trainer estimator we have currently  implements  Kmeans++ 

For the specific  trainer implementation we have currently, we are using `KMeansPlusPlus`  for the MLContext name and `KMeansPlusPlusTrainer`  the Class name

I can envision that in the future one might even want to implement the vanilla Kmeans  algorithm itself.  As such to me it makes sense  to keep  the  name of  the static class  and assembly as just `KMeans` .   

---
In reply to: [264707009](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264707009) [](ancestors = 264707009)

File: src/Microsoft.ML.StandardTrainers/Standard/MultiClass/MetaMulticlassTrainer.cs (hunk 12 above)
Comment (abgoswam) [reply src/Microsoft.ML.StandardTrainers/Standard/MultiClass/MetaMulticlassTrainer.cs]: Yeah. It makes sense to treat this as a special case.

File: src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs (hunk 10 above)
Comment (abgoswam) [reply src/Microsoft.ML.FastTree/TreeTrainersCatalog.cs]: Thanks for the suggestion. Will fix.

File: src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs (hunk 11 above)
Comment (wschin) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: My feeling is that no one will add Kmeans as long as Kmeans++ exists. As you mentioned, Kmeans++ is a member of Kmeans family. Why can't we call it Kmeans? If someone want to implement the original Kmeans, it can be called NaiveKmeans.

Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: Sure. That makes sense.  Will rename it to `KMeans`  to keep things uniform

Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: Thanks. I also noticed there is a property  `InitializationAlgorithm`  to specify the initialization  mechanism 

So yeah. It should be just `KMeans`

---
In reply to: [264770186](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264770186) [](ancestors = 264770186)

Comment (abgoswam) [reply src/Microsoft.ML.KMeansClustering/KMeansCatalog.cs]: fixed.  We should indeed call it `KMeans` 

---
In reply to: [264757754](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264757754) [](ancestors = 264757754,264707009)

File: test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs [hunk 14]
```diff
@@ -105,7 +105,7 @@ private void TrainRegression(string trainDataPath, string testDataPath, string m
                 // once so adding a caching step before it is not helpful.
                 .AppendCacheCheckpoint(mlContext)
                 // Add the SDCA regression trainer.
-                .Append(mlContext.Regression.Trainers.StochasticDualCoordinateAscent(labelColumnName: "Target", featureColumnName: "FeatureVector"));
+                .Append(mlContext.Regression.Trainers.Sdca(labelColumnName: "Target", featureColumnName: "FeatureVector"));
```
Comment (eerhardt) [inline test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs]: when we update the cookbook samples files, it usually means the cookbook needs to be updated.

Comment (abgoswam) [reply test/Microsoft.ML.Tests/Scenarios/Api/CookbookSamples/CookbookSamplesDynamicApi.cs]: thanks for pointing this out!

---
In reply to: [264879257](https://github.com/dotnet/machinelearning/pull/2903#discussion_r264879257) [](ancestors = 264879257)

**Comment by abgoswam** [comment]
Thanks folks for the review comments!
