### PR TITLE
ONNXTransform Upgrade to Enable Non-tensor Types

### LINKED ISSUE #3900: "Onnx Type not supported" error while importing Custom Vision ONNX model
### System information

- **OS version/distro**: Win 10 Pro Build 17763.503
- **.NET Version (eg., dotnet --info)**: .Net FrameWork 4.7.2
- **ML.NET Version**:1.1.0
- **ONNX Version::** 1.0 / 1.2 

### Issue

- **What did you do?**
Exported a image classification(General(Compact)) ONNX model from Custom Vision and attempted to generate a ONNX Estimator in ML.NET

- **What happened?**
The model loading failed with error "Onnx type not supported".
This happens with all image classification ONNX models exported from Custom Vision.
Corresponding Tensorflow models work well in ML.NET.

- **What did you expect?**
It is possible to load ONNX models exported from Tensorflow/Scikit-learn. ML.NET should be able to accept ONNX models from Custom Vision.

### Source code / logs

var onnxEstimator = mLContext.Transforms.ApplyOnnxModel(OutputColumnNames, InputColumnNames, OnnxModelPath);

### Files
[onnx12.zip](https://github.com/dotnet/machinelearning/files/3316591/onnx12.zip)

### PR DESCRIPTION
**Pull request by wschin**
The current ONNXTransform only operates on tensor types. As many ONNX models (especially classifiers) produce Seq<Map<T, float>> where T can be either int or string, we should remove that limitation.

This should fix #3900.

### CODE REVIEW

File: src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj [hunk 1]
```diff
@@ -9,6 +9,7 @@
   <ItemGroup>
     <ProjectReference Include="..\Microsoft.ML.Core\Microsoft.ML.Core.csproj" />
     <ProjectReference Include="..\Microsoft.ML.Data\Microsoft.ML.Data.csproj" />
+    <ProjectReference Include="..\Microsoft.ML.OnnxConverter\Microsoft.ML.OnnxConverter.csproj" />
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj]: You can't make this change without also adding the reference to the NuGet package.

But in general, I don't think making OnnxTransformer dependent on OnnxConverter is a good idea. Instead, if there is code that needs to be shared, we can compile it into both libraries.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs [hunk 2]
```diff
@@ -0,0 +1,548 @@
...
+        }
+    }
+
+    /// <summary>
+    /// The corresponding <see cref="DataViewSchema.Column.Type"/> of ONNX's sequence type in <see cref="IDataView"/>'s type system.
+    /// In other words, if an ONNX model produces a sequence, a column in <see cref="IDataView"/> may be typed to <see cref="OnnxSequenceType"/>.
+    /// Its underlying type is <see cref="IEnumerable{T}"/>, where the generic type "T" is the input argument of
+    /// <see cref="OnnxSequenceType.OnnxSequenceType(Type)"/>.
+    /// </summary>
+    public sealed class OnnxSequenceType : StructuredDataViewType
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: Can you put top-level classes in their own file? One class per file is usually a good recommendation.

Here, the first class in the file is "internal", which makes it look like there are no public APIs being added.  But the public APIs are later in the file.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs [hunk 3]
```diff
@@ -0,0 +1,548 @@
...
+    /// To declare <see cref="OnnxSequenceType"/> column in <see cref="IDataView"/> as a field
+    /// in a <see langword="class"/>, the associated field should be marked with <see cref="OnnxSequenceTypeAttribute"/>.
+    /// Its uses are similar to those of <see cref="VectorTypeAttribute"/> and other <see langword="class"/>es derived
+    /// from <see cref="DataViewTypeAttribute"/>.
+    /// </summary>
+    public sealed class OnnxSequenceTypeAttribute : DataViewTypeAttribute
+    {
+        private Type _elemType;
+        /// <summary>
+        /// Create an image type without knowing its height and width.
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: Copy and paste left over.  Please fix everywhere.

File: test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs [hunk 4]
```diff
@@ -398,5 +399,163 @@ public void OnnxModelInMemoryImage()
...
+        private class ZipMapInput
+        {
+            [ColumnName("input")]
+            [VectorType(3)]
+            public float[] Input { get; set; }
+        }
+
+        private class ZipMapStringOutput
+        {
+            [OnnxSequenceType(typeof(IDictionary<string, float>))]
```
Comment (eerhardt) [inline test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs]: How about tests for the new `OnnxMap` type as well?

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs [hunk 5]
```diff
@@ -595,27 +708,37 @@ public override SchemaShape GetOutputSchema(SchemaShape inputSchema)
...
                 var inputNodeInfo = inputsInfo[idx];
-                var expectedType = OnnxUtils.OnnxToMlNetType(inputNodeInfo.Type);
+                var expectedType = ((VectorDataViewType)inputNodeInfo.MlnetType).ItemType;
                 if (col.ItemType != expectedType)
                     throw Host.ExceptSchemaMismatch(nameof(inputSchema), "input", input, expectedType.ToString(), col.ItemType.ToString());
             }
 
             for (var i = 0; i < Transformer.Outputs.Length; i++)
             {
+                var outputName = Transformer.Outputs[i];
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: This variable doesn't appear to be used

File: src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs [hunk 6]
```diff
@@ -20,67 +21,135 @@ namespace Microsoft.ML.Transforms.Onnx
...
             /// <summary>
             /// The shape of the node
             /// </summary>
-            public readonly OnnxShape Shape;
+            public OnnxShape Shape { get; }
             /// <summary>
             /// The type of the node
             /// </summary>
-            public readonly System.Type Type;
+            public System.Type OrtType { get; }
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs]: I don't really like `OrtType` and `MlnetType` for names. How about `OnnxType` and `DataViewType` instead?

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs [hunk 7]
```diff
@@ -0,0 +1,548 @@
...
+                    var methodInfo = typeof(NamedOnnxValue).GetMethod(nameof(NamedOnnxValue.AsTensor));
+                    var methodSpecialized = methodInfo.MakeGenericMethod(type);
+
+                    // Access the first element as a scalar.
+                    var accessInfo = typeof(Tensor<>).GetMethod(nameof(Tensor<int>.GetValue));
+                    var accessSpecialized = accessInfo.MakeGenericMethod(type);
+
+                    // NamedOnnxValue to scalar.
+                    Func<NamedOnnxValue, object> caster = (NamedOnnxValue value) => {
+                        var tensor = methodSpecialized.Invoke(value, new object[] { });
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: Is the `tensor` variable used?

File: src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj (hunk 1 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj]: Sure. I will compile the required part into ONNXTransformer instead of reusing it from ONNXConverter.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs (hunk 3 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: You're right. Many thanks.

File: src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs (hunk 6 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxUtils.cs]: I will do `TypeInOnnxRuntime` and `DataViewType`. Runtime can freely translate ONNX type to whatever it likes; for example, ONNX tensor can be mapped to `float[]`, `Tensor`, etc.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs (hunk 7 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: Nop. Thanks!

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs (hunk 5 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: Totally agree.

**Comment by wschin** [comment]
> 

Remove it if possible.

---
Refers to: src/Microsoft.ML.OnnxConverter/AssemblyInfo.cs:11 in 9e539b6. [](commit_id = 9e539b6ecb0f61edefc2d1f19374e3d27dd654bb, deletion_comment = False)

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs [hunk 8]
```diff
@@ -165,37 +179,40 @@ private static IRowMapper Create(IHostEnvironment env, ModelLoadContext ctx, Dat
...
             catch (OnnxRuntimeException e)
             {
                  throw Host.Except(e, $"Error initializing model :{e.ToString()}");
             }
 
             var modelInfo = Model.ModelInfo;
-            Inputs = (options.InputColumns.Count() == 0) ? Model.InputNames.ToArray() : options.InputColumns;
-            Outputs = (options.OutputColumns.Count() == 0) ? Model.OutputNames.ToArray() : options.OutputColumns;
+            Inputs = (options.InputColumns.Count() == 0) ? Model.ModelInfo.InputNames.ToArray() : options.InputColumns;
+            Outputs = (options.OutputColumns.Count() == 0) ? Model.ModelInfo.OutputNames.ToArray() : options.OutputColumns;
```
Comment (wschin) [inline src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: >options.OutputColumns.Count() == 0 [](start = 23, length = 34)

Check if we have test.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs [hunk 9]
```diff
@@ -0,0 +1,551 @@
...
+                {
+                    // Entering this scope means that a ONNX scalar is found. Note that ONNX scalar is typed to tensor without a shape.
+
+                    // Get tensor element type.
+                    var type = GetScalarDataViewType(typeProto.TensorType.ElemType).RawType;
+
+                    // Create a method to cast NamedOnnxValue to Tensor.
+                    var methodInfo = typeof(NamedOnnxValue).GetMethod(nameof(NamedOnnxValue.AsTensor));
+                    var methodSpecialized = methodInfo.MakeGenericMethod(type);
+
```
Comment (wschin) [inline src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: Remove.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs [hunk 10]
```diff
@@ -0,0 +1,551 @@
...
+                // Now, we see a Sequence in ONNX. If its element type is T, the variable produced by
+                // ONNXRuntime would be typed to IEnumerable<T>.
+
+                // Find a proper caster (a function which maps NamedOnnxValue to a .NET object) for the element in
+                // the ONNX sequence. Note that ONNX sequence is typed to IEnumerable<NamedOnnxValue>, so we need
+                // to convert NamedOnnxValue to a proper type such as IDictionary<>.
+                var elementCaster = GetDataViewValueCasterAndResultedType(typeProto.SequenceType.ElemType, out Type elementType);
+
+                // Set the .NET type which corresponds to the first input argument, typeProto.
+                resultedType = typeof(IEnumerable<>).MakeGenericType(elementType);
```
Comment (wschin) [inline src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: >resultedType = typeof(IEnumerable<>).MakeGenericType(elementType); [](start = 16, length = 66)

Remove.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs [hunk 11]
```diff
@@ -0,0 +1,551 @@
...
+            else if (typeProto.ValueCase == OnnxCSharpToProtoWrapper.TypeProto.ValueOneofCase.MapType)
+            {
+                // Entering this scope means a ONNX Map (equivalent to IDictionary<>) will be produced.
+
+                var keyType = GetNativeScalarType(typeProto.MapType.KeyType);
+                var valueType = GetNativeType(typeProto.MapType.ValueType);
+
+                // The resulted type of the object returned by the caster below.
+                resultedType = typeof(IDictionary<,>).MakeGenericType(keyType, valueType);
+
```
Comment (wschin) [inline src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: Remove.

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs [hunk 12]
```diff
@@ -412,103 +450,178 @@ private void UpdateCacheIfNeeded(long position, INamedOnnxValueGetter[] srcNamed
...
+                    var casted = denseTensor.Select(value => value.AsMemory());
+                    // Tensor<ReadOnlyMemory<char>> to Span<ReadOnlyMemory<char>>.
+                    // Note that string vector in ML.NET is typed to Span<ReadOnlyMemory<char>>.
+                    var buffer = new Span<ReadOnlyMemory<char>>(casted.ToArray());
+
+                    // Create VBufferEditor to fill "dst" with the values in "buffer".
                     var editor = VBufferEditor.Create(ref dst, (int)denseTensor.Length);
-                    denseTensor.Buffer.Span.CopyTo(editor.Values);
+                    buffer.CopyTo(editor.Values);
                     dst = editor.Commit();
```
Comment (wschin) [inline src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: >dst = editor.Commit(); [](start = 20, length = 22)

dst= new VBuffer<>

Comment (eerhardt) [reply src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: No, don’t make a new buffer here. Reuse the dst buffer.

File: src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj [hunk 13]
```diff
@@ -9,8 +9,8 @@
   <ItemGroup>
     <ProjectReference Include="..\Microsoft.ML.Core\Microsoft.ML.Core.csproj" />
     <ProjectReference Include="..\Microsoft.ML.Data\Microsoft.ML.Data.csproj" />
-    <ProjectReference Include="..\Microsoft.ML.OnnxConverter\Microsoft.ML.OnnxConverter.csproj" />
     <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="$(MicrosoftMLOnnxRuntimePackageVersion)" />
+    <PackageReference Include="Google.Protobuf" Version="$(GoogleProtobufPackageVersion)" />
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj]: You’ll need to add this reference to the pkg nupkgproj.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs (hunk 11 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: We can't remove it because it's an `out` argument.

---
In reply to: [298418480](https://github.com/dotnet/machinelearning/pull/3881#discussion_r298418480) [](ancestors = 298418480)

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs [hunk 14]
```diff
@@ -412,103 +450,178 @@ private void UpdateCacheIfNeeded(long position, INamedOnnxValueGetter[] srcNamed
...
+                    var denseTensor = namedOnnxValue.AsTensor<string>();
                     if (denseTensor == null)
-                        throw Host.Except($"Output column {namedOnnxValue.Name} doesn't contain a DenseTensor of expected type {typeof(T)}");
+                        throw Host.Except($"Output column {namedOnnxValue.Name} doesn't contain a DenseTensor of expected type {typeof(string)}");
+
+                    // Tensor<string> to Tensor<ReadOnlyMemory<char>>.
+                    var casted = denseTensor.Select(value => value.AsMemory());
+                    // Tensor<ReadOnlyMemory<char>> to Span<ReadOnlyMemory<char>>.
+                    // Note that string vector in ML.NET is typed to Span<ReadOnlyMemory<char>>.
+                    var buffer = new Span<ReadOnlyMemory<char>>(casted.ToArray());
```
Comment (eerhardt) [inline src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: You shouldn't have to `ToArray()` here that is wasting time and memory, instead:

```C#
    int length =  (int)denseTensor.Length;
    var editor = VBufferEditor.Create(ref dst, length);
    for (int i = 0; i < length; i++)
    {
        editor.Values[i] = denseTensor[i].AsMemory();
    }
    dst = editor.Commit();
```

Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: No problem. Thanks for this super smart and detailed comment!

File: src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj (hunk 13 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj]: Ok.

File: src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs (hunk 12 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs]: You're right.

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs (hunk 10 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: It's an `out` argument, so we need this line.

File: test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs (hunk 4 above)
Comment (wschin) [reply test/Microsoft.ML.OnnxTransformerTest/OnnxTransformTests.cs]: Unfortunately, ONNXRuntime doesn't allow us to create Map value as input and the Map value is always used as input of ONNX operator... I can add some smoke tests for sure.

---
In reply to: [298374926](https://github.com/dotnet/machinelearning/pull/3881#discussion_r298374926) [](ancestors = 298374926)

File: src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs (hunk 2 above)
Comment (wschin) [reply src/Microsoft.ML.OnnxTransformer/OnnxTypes.cs]: No problem. Btw, I still put "...DataViewType" and its "...DataViewTypeAttribute" in the same file for emphasizing that they are dual of each other.

---
In reply to: [298374249](https://github.com/dotnet/machinelearning/pull/3881#discussion_r298374249) [](ancestors = 298374249)
