### PR TITLE
Change ML.NET to work with .NET Framework 4.6.1

### LINKED ISSUE #1072: The new API does not work on .NET Framework < 4.7.1
It relies on the extension method in System.Linq "Append" that was added only in 4.7.1.

### PR DESCRIPTION
**Pull request by yaeldekel**
Fixes #1072 .

### CODE REVIEW

File: src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs [hunk 1]
```diff
@@ -72,7 +72,7 @@ public EstimatorChain<TNewTrans> Append<TNewTrans>(IEstimator<TNewTrans> estimat
             where TNewTrans : class, ITransformer
         {
             Contracts.CheckValue(estimator, nameof(estimator));
-            return new EstimatorChain<TNewTrans>(_estimators.Append(estimator).ToArray(), _scopes.Append(scope).ToArray());
+            return new EstimatorChain<TNewTrans>(_estimators.Concat(new[] { estimator }).ToArray(), _scopes.Concat(new[] { scope }).ToArray());
```
Comment (eerhardt) [inline src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs]: I'm not sure how concerned we are about perf in these methods, but another way would be to make our own `AppendElement` method:

```C#
public static T[] AppendElement(T[] array, T element)
{
    T[] result = new T[array.Length + 1];
    Array.Copy(array, result);
    result[array.Length] = element;
    return result;
}
```

Another option would be to use ImmutableCollections.... I don't think you'd have to pay a penalty for copying in that case. But I'm not sure we'd want to take a new dependency, if we aren't using ImmutableCollections already.

File: src/Microsoft.ML.StandardLearners/Standard/ModelStatistics.cs [hunk 2]
```diff
@@ -342,7 +342,7 @@ public CoefficientStatistics[] GetCoefficientStatistics(LinearBinaryPredictor pa
                 return null;
 
             var order = GetUnorderedCoefficientStatistics(parent, schema).OrderByDescending(stat => stat.ZScore).Take(paramCountCap - 1);
-            return order.Prepend(new CoefficientStatistics("(Bias)", bias, stdError, zScore, pValue)).ToArray();
+            return order.Prepend(new[] { new CoefficientStatistics("(Bias)", bias, stdError, zScore, pValue) }).ToArray();
```
Comment (eerhardt) [inline src/Microsoft.ML.StandardLearners/Standard/ModelStatistics.cs]: Which `order.Prepend` method is this?

Comment (eerhardt) [reply src/Microsoft.ML.StandardLearners/Standard/ModelStatistics.cs]: Ah, we have our own `shim` here: `src\Microsoft.ML.Core\Data\MetadataUtils.cs`

```
        /// <summary>
        /// Prepends a params array to an enumerable. Useful when implementing GetMetadataTypes.
        /// </summary>
        public static IEnumerable<T> Prepend<T>(this IEnumerable<T> tail, params T[] head)
        {
            return head.Concat(tail);
        }
```

**Comment by justinormont** [comment]
Closing/opening to re-check CI tests

File: src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs (hunk 1 above)
Comment (TomFinley) [reply src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs]: Hi @eerhardt -- we are using `ImmutableCollections`, and I am beginning to use it in my code. I really like it a lot, I think we ought to use it more.

File: src/Microsoft.ML.Data/DataLoadSave/TransformerChain.cs [hunk 3]
```diff
@@ -146,7 +146,7 @@ public TransformerChain<TNewLast> Append<TNewLast>(TNewLast transformer, Transfo
             where TNewLast : class, ITransformer
         {
             Contracts.CheckValue(transformer, nameof(transformer));
-            return new TransformerChain<TNewLast>(_transformers.Append(transformer).ToArray(), _scopes.Append(scope).ToArray());
+            return new TransformerChain<TNewLast>(_transformers.AppendElement(transformer), _scopes.AppendElement(scope));
```
Comment (ericstj) [inline src/Microsoft.ML.Data/DataLoadSave/TransformerChain.cs]: Looks like this type only has enumerable constructor, so you end up with 3 arrays for each param.  One that is size N, and two that are size N+1.  If you keep it as an enumerable, you can reduce this.  It can be further reduced if you have a constructor that takes an array with reference semantics.

It's also somewhat odd that TransformerChain has copy semantics for constructor params, but EstimatorChain has reference semantics (and thus doesn't have this array copy problem).
