### PR TITLE
Fixes build error when path contains space on Linux

### LINKED ISSUE #191: Project will not build because of space in build path
### System information

- **OS version/distro**: Windows 10 Home
- **.NET Version (eg., dotnet --info)**: 2.1.200, concerning ML .net V0.1.0

### Issue

- **What did you do?** Try to build from source
- **What happened?** When trying to build, I have a space in my user profile, for example let's say "John Smith".  So when I cloned to C:/users/John Smith/source/repo/machinelearning/ and tried to build using a command prompt (in the before directory) using command `start build.cmd -Release -TargetArchitecture:x64` 

Another window opened (expected) and it said `'C:\Users\John' is not recognized as an internal or external command, operable program or batch file`

Moving the folder up to C:/ it builds just fine. 
- **What did you expect?** To build

### Source code / logs

Its probably caused by %~dp0 in the build.cmd file.

### PR DESCRIPTION
**Pull request by tincann**
Fixes #191 (for Linux)

Similar to the problem on Windows, the paths used in the build scripts needed proper quoting.

### CODE REVIEW

File: init-tools.sh [hunk 1]
```diff
@@ -8,19 +8,19 @@ __DOTNET_PATH=$__TOOLRUNTIME_DIR/dotnetcli
 __DOTNET_CMD=$__DOTNET_PATH/dotnet
 if [ -z "$__BUILDTOOLS_SOURCE" ]; then __BUILDTOOLS_SOURCE=https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json; fi
 export __BUILDTOOLS_USE_CSPROJ=true
-__BUILD_TOOLS_PACKAGE_VERSION=$(cat $__scriptpath/BuildToolsVersion.txt | sed 's/\r$//') # remove CR if mounted repo on Windows drive
-__DOTNET_TOOLS_VERSION=$(cat $__scriptpath/DotnetCLIVersion.txt | sed 's/\r$//') # remove CR if mounted repo on Windows drive
-__ILASM_VERSION=$(cat $__scriptpath/tools-local/ILAsmVersion.txt | sed 's/\r$//') # remove CR if mounted repo on Windows drive
+__BUILD_TOOLS_PACKAGE_VERSION=$(cat "$__scriptpath/BuildToolsVersion.txt" | sed 's/\r$//') # remove CR if mounted repo on Windows drive
+__DOTNET_TOOLS_VERSION=$(cat "$__scriptpath/DotnetCLIVersion.txt" | sed 's/\r$//') # remove CR if mounted repo on Windows drive
+__ILASM_VERSION=$(cat "$__scriptpath/tools-local/ILAsmVersion.txt" | sed 's/\r$//') # remove CR if mounted repo on Windows drive
```
Comment (eerhardt) [inline init-tools.sh]: This line can actually just be removed, we don't have this file in this repo.  The init-tools script is shared between a few repos, and this line was blindly copied.

**Comment by weshaggard** [comment]
>@weshaggard - do you want the fixes to init-tools.sh and run.sh to be propagated to the other repos?

It looks like at least some of these are already in other repo's. At any rate I wouldn't bother propagating these as our move to our arcade toolset should make maintaining these type of scripts much easier.

File: init-tools.sh (hunk 1 above)
Comment (tincann) [reply init-tools.sh]: I've removed the references to ILasmVersion.txt in the build scripts for Windows and Linux: https://github.com/dotnet/machinelearning/pull/266
