### PR TITLE
Fix a bug with group Id column in CV macro and add NameColumn argument to CV and TrainTest macros

### LINKED ISSUE #456: Cross validation macro doesn't work with non-default group column name
Related to #292. When the fix for this bug was checked in (#291) there was a bug related to the GroupId and Weight columns, which causes the specified column names not to be passed to the evaluation entry point.

### LINKED ISSUE #466: CV macro should be able to pass a name column to the evaluator
When running in CV mode, the per-instance results data view contains the results from all folds. Having a name column enables identifying the examples, since they are not in the same order as the input data. Currently, there is no way to pass a name column to the evaluator in the CV macro.

### PR DESCRIPTION
**Pull request by yaeldekel**
This PR fixes bug #456, and also introduces a NameColumn argument to the TrainTest and CV macros, to enable the evaluator to use it in the per-instance results.
Fixes #456 
Fixes #466

### CODE REVIEW

File: src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs [hunk 1]
```diff
@@ -535,9 +535,9 @@ public float Cost
                 ch.Assert(groupColFieldType == typeof(string));
                 var inputGroup = inputInstance.GetType().GetField(groupColField).GetValue(inputInstance);
                 if (group != (Optional<string>)inputGroup)
-                    ch.Warning(warning, "group Id", label, inputGroup);
+                    ch.Warning(warning, "group Id", group, inputGroup);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs]: >group [](start = 52, length = 5)

ugh.
Thank you finding this, and fixing it!

**Comment by Ivanidzo4ka** [comment]
>                     _inputBuilder.TrySetValue(labelColField, label);

this pattern now appears in 4 places, should we refactor it?

---
Refers to: src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs:527 in 1d55c6c. [](commit_id = 1d55c6cffd0b3ce973f62129341e5dbf87125fd4, deletion_comment = False)

File: src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs [hunk 2]
```diff
@@ -130,12 +133,15 @@ public sealed class CombineMetricsInput
...
 
-            [Argument(ArgumentType.LastOccurenceWins, HelpText = "Column to use for example weight", ShortName = "weight", SortOrder = 6)]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Column to use for example weight", ShortName = "weight", SortOrder = 6)]
             public Optional<string> WeightColumn = Optional<string>.Implicit(DefaultColumnNames.Weight);
 
-            [Argument(ArgumentType.LastOccurenceWins, HelpText = "Column to use for grouping", ShortName = "group", SortOrder = 12)]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Column to use for grouping", ShortName = "group", SortOrder = 12)]
             public Optional<string> GroupColumn = Optional<string>.Implicit(DefaultColumnNames.GroupId);
 
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Name column name", ShortName = "name", SortOrder = 6)]
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs]: nit:
sort order is same for weight, kind, name, but 12 for group column.

File: src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs [hunk 3]
```diff
@@ -66,26 +66,29 @@ public sealed class Arguments
...
 
-            [Argument(ArgumentType.LastOccurenceWins, HelpText = "Column to use for example weight", ShortName = "weight", SortOrder = 11)]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Column to use for example weight", ShortName = "weight", SortOrder = 11)]
             public Optional<string> WeightColumn = Optional<string>.Implicit(DefaultColumnNames.Weight);
 
-            [Argument(ArgumentType.LastOccurenceWins, HelpText = "Column to use for grouping", ShortName = "group", SortOrder = 12)]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Column to use for grouping", ShortName = "group", SortOrder = 12)]
             public Optional<string> GroupColumn = Optional<string>.Implicit(DefaultColumnNames.GroupId);
+
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Name column name", ShortName = "name", SortOrder = 6)]
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs]: >6 [](start = 110, length = 1)

should it be 13?

File: src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs [hunk 4]
```diff
@@ -487,22 +496,22 @@ private static IMamlEvaluator GetEvaluator(IHostEnvironment env, MacroUtils.Trai
...
-                    return new RankerMamlEvaluator(env, new RankerMamlEvaluator.Arguments());
-                case MacroUtils.TrainerKinds.SignatureAnomalyDetectorTrainer:
-                    return new AnomalyDetectionMamlEvaluator(env, new AnomalyDetectionMamlEvaluator.Arguments());
-                case MacroUtils.TrainerKinds.SignatureClusteringTrainer:
-                    return new ClusteringMamlEvaluator(env, new ClusteringMamlEvaluator.Arguments());
-                case MacroUtils.TrainerKinds.SignatureMultiOutputRegressorTrainer:
-                    return new MultiOutputRegressionMamlEvaluator(env, new MultiOutputRegressionMamlEvaluator.Arguments());
-                default:
-                    throw env.ExceptParam(nameof(kind), $"Trainer kind {kind} does not have an evaluator");
+            case MacroUtils.TrainerKinds.SignatureBinaryClassifierTrainer:
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/CrossValidationMacro.cs]: >             [](start = 0, length = 12)

My VS put extra indent after "{" so if I format code, i get current formatting.
So next time if I happen to format this file, I'll revert your changes.
It's not a blocker, but maybe we need to discuss at some point default VS setting...

File: src/Microsoft.ML/Runtime/EntryPoints/TrainTestMacro.cs [hunk 5]
```diff
@@ -63,14 +63,17 @@ public sealed class Arguments
...
 
-            [Argument(ArgumentType.LastOccurenceWins, HelpText = "Column to use for example weight", ShortName = "weight", SortOrder = 11)]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Column to use for example weight", ShortName = "weight", SortOrder = 11)]
             public Optional<string> WeightColumn = Optional<string>.Implicit(DefaultColumnNames.Weight);
 
-            [Argument(ArgumentType.LastOccurenceWins, HelpText = "Column to use for grouping", ShortName = "group", SortOrder = 12)]
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Column to use for grouping", ShortName = "group", SortOrder = 12)]
             public Optional<string> GroupColumn = Optional<string>.Implicit(DefaultColumnNames.GroupId);
+
+            [Argument(ArgumentType.AtMostOnce, HelpText = "Name column name", ShortName = "name", SortOrder = 6)]
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML/Runtime/EntryPoints/TrainTestMacro.cs]: 13?

File: src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs [hunk 6]
```diff
@@ -549,9 +549,20 @@ public float Cost
...
+            var nameColField = _inputBuilder.GetFieldNameOrNull("NameColumn");
+            if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(nameColField))
+            {
+                var nameColFieldType = _inputBuilder.GetFieldTypeOrNull(nameColField);
+                ch.Assert(nameColFieldType == typeof(string));
+                var inputName = inputInstance.GetType().GetField(nameColField).GetValue(inputInstance);
+                if (name != (Optional<string>)inputName)
+                    ch.Warning(warning, "name", name, inputName);
+                else
+                    _inputBuilder.TrySetValue(nameColField, weight);
```
Comment (Ivanidzo4ka) [inline src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs]: >weight [](start = 60, length = 6)

name!

Comment (yaeldekel) [reply src/Microsoft.ML.Data/EntryPoints/EntryPointNode.cs]: Thank you for finding!

---
In reply to: [199586356](https://github.com/dotnet/machinelearning/pull/467#discussion_r199586356) [](ancestors = 199586356)
